### ISSUE TITLE
Are the ButtonMask values incorrect for track pad?

### ISSUE THREAD

**Issue by zecbmo** [ValveSoftware/openvr#100]
Context: getting the controller state using GetControllerStateWithPose or GetControllerState.

When clicking the track pad the `state_.ulButtonPressed` is returned as 4294967296.
Similar with the trigger.
For other buttons they are return as their equivalent mask ID ie Axis2 = 2 and so on.

With the track pad I am unable to get any indication of being pressed using
`return (state_.ulButtonPressed & buttonMask) != 0; `

This is how the controller functions are presented in the Unity Sample

**Comment by zecbmo** [comment]
Realizing now it is returning the maximum value for an unsigned 64 bit long. But would that make a difference to  `return (state_.ulButtonPressed & buttonMask) != 0;`

**Comment by JoeLudwig** [comment]
4294967296 dec is 0x1 0000 0000, which is bit 32 in this 64 bit value. That matches k_EButton_Axis0, which is the trackpad (and is also known as k_EButton_SteamVR_Touchpad).

Maybe you're casting down to 32 bits somewhere?

**Comment by zecbmo** [comment]
That has done the trick and helped find the issue! Thanks for the speedy reply!
