### ISSUE TITLE
[Question] Getting the position of tracked device at high frequency 

### ISSUE THREAD

**Issue by neuroimmersion** [ValveSoftware/openvr#1007]
Hello,

I am working for a VR platform developing experiment for researcher in neuroscience. In the context of those experiments I wish to access the position of the HMD/ControllerVive Tracker at high frequency (minimum 250 Hz) for motion analysis.

I get the positions data with GetDeviceToAbsoluteTrackingPose but the function does not give back the time when the pose is computed.

Does the system compute the coordinates each time the function GetDeviceToAbsoluteTrackingPose (when 0 is used for fPredictedSecondsToPhotonsFromNow)  is called ? Or does it compute the position at regular pace and then we access it via the function call ?

Just to be sure that I am not going to position data.

**Comment by JoeLudwig** [comment]
GetDeviceToAbsoluteTrackingPose computes the result on each call.

Why do you need poses at 250Hz?

**Comment by AlexanderMarinsek** [comment]
> get the positions data with GetDeviceToAbsoluteTrackingPose but the function does not give back the time when the pose is computed.

Thanks for the heads up Joe.

Why would this only be a problem at 250 Hz and not at lower frequencies? Also, what sort of artifacts do you mean?
