### ISSUE TITLE
vr::VRCompositor->Submit() returns GL_INVALID_OPERATION on "new" AMD drivers

### ISSUE THREAD

**Issue by JohnL33** [ValveSoftware/openvr#1013]
Hi!

So since AMD driver 18.8.1 (August last year), our call to vr::VRCompositor->Submit() has started throwing GL_INVALID_OPERATION while still returning VRCompositorError_None.  This wasn't a big issue until AMD incremented the recommended driver version and this issue persisted.  For what it's worth, this issue is not present on Nvidia cards, we're on OpenGL 4.4, using c++

```
vr::Texture_t eyeTexture = { 
		(void*)(uintptr_t)m_glTextureIndex, 
		vr::TextureType_OpenGL, 
		vr::ColorSpace_Gamma 
	};

ivrResult = vr::VRCompositor()->Submit((vr::EVREye)(eye), &eyeTexture);
```

We've updated to the latest version of openvr, tried submitting a pure black texture (width and height from GetRecommendedRenderTargetSize()), and per other issue threads here, we've tried a multi-sampled texture, and making sure the framebuffer & texture are unbound before calling submit.

Disclaimer, I can make the hellovr_opengl sample work.  So I guess what I'm really asking is what has changed and what could we have missed?  Any help or ideas are greatly appreciated!
Thanks!

**Comment by JohnL33** [comment]
Our internal gl format was RGBA, instead of RGBA8.  Sorry for cluttering 😅

**Comment by maxvollmer** [comment]
Thanks! Had the exact same issue and your comment saved me some headaches :D

**Comment by enexusde** [comment]
Possible duplicate https://github.com/TheGameCreators/AGK-Studio/issues/733
