### ISSUE TITLE
Please add Notifications interface to C# header file

### ISSUE THREAD

**Issue by BOLL7708** [ValveSoftware/openvr#1016]
The interface for Notifications is missing in the C# header, I've been using a [library](https://github.com/artumino/SteamVR_HUDCenter) where the header file was edited. It would be really nice if this could be added officially so we don't have to edit the header for each release of OpenVR.

[This](https://gist.github.com/BOLL7708/5a94abb59b2e13d21be42075ad175f4d) is a gist of what to add to the most recent header file, based on the [modifications](https://github.com/artumino/SteamVR_HUDCenter/blob/master/SteamVR_HUDCenter/SteamVR/open_api_patch.diff) done in the library mentioned. As it's a generated file there's not really a point to making a pull request.

I've [mentioned](https://github.com/ValveSoftware/openvr/issues/395#issuecomment-301232180) this as a comment in a different thread quite some time ago, but figured to have something happen I'll post about it specifically. 🤞

**Comment by aleiby** [comment]
Thanks, I've updated the source so this should show up in the next SDK or the one after that.  Also added the missing VRIOBuffer accessor.
