### ISSUE TITLE
m_pVRIOBuffer misspelled in C# header in 1.2.10

### ISSUE THREAD

**Issue by BOLL7708** [ValveSoftware/openvr#1033]
[Line 6062](https://github.com/ValveSoftware/openvr/blob/master/headers/openvr_api.cs#L6062) should say `m_pVRIOBuffer = null;` instead of `m_pIOBuffer = null;`

After changing that I could build again 😉

**Comment by kisak-valve** [comment]
Closing in favor of #1034.
