### ISSUE TITLE
[C#] Notification bitmap stops displaying going from 32bit to 64bit openvr_api.dll

### ISSUE THREAD

**Issue by BOLL7708** [ValveSoftware/openvr#1038]
This is using the C# headers.

For me running [this](https://github.com/BOLL7708/OpenVRNotificationTest) test project loads a bitmap off of disk, prepares it and successfully displays it in the notification that pops up in the headset.
![image](https://user-images.githubusercontent.com/12276837/52176444-3991da80-27b3-11e9-8e1d-e409510374f0.png)

If the only change I do is [switch](https://github.com/BOLL7708/OpenVRNotificationTest/tree/64bit) to the 64bit .dll there is no error, but the bitmap is no longer displayed, it's just an empty space.

![image](https://user-images.githubusercontent.com/12276837/52176447-4282ac00-27b3-11e9-9d92-b88a799f559c.png)

Am I missing something obvious I need to do here? 🤔 I have spent a bunch of hours trying to kick it into submission as 64bit with no success.

**Comment by AndersMalmgren** [comment]
Since SteamVR Unity plugin is preferred at x64 most Unity Devs are hit by this problem, me included.

**Comment by aleiby** [comment]
Thanks for reporting.  I've got a fix coming for this.
