### ISSUE TITLE
Never kill processes

### ISSUE THREAD

**Issue by ahtur** [ValveSoftware/openvr#1061]
Hi. 
The fact that vr::VRSettings()->SetBool(vr::k_pch_SteamVR_Section, vr::k_pch_SteamVR_NeverKillProcesses_Bool, true); doesn't have any effect (on SteamVR 1.2.7 at least), is it a bug or a feature ? Is there another way to change that value at runtime ?

**Comment by JoeLudwig** [comment]
This setting controls whether not vrserver will kill processes that don't respond to VREvent_Quit after 5 seconds. Are you seeing it not have that effect?

**Comment by ahtur** [comment]
Yes, SteamVR still kills my process even if I set the value to true.

**Comment by JoeLudwig** [comment]
Can you post a system report?

Also, if you just respond to VREvent_Quit by calling VR_Shutdown you wouldn't be killed regardless of this setting. SteamVR doesn't care if your process keeps running, it cares if it keeps vrclient.dll loaded.

**Comment by ahtur** [comment]
> Can you post a system report?
> 
> Also, if you just respond to VREvent_Quit by calling VR_Shutdown you wouldn't be killed regardless of this setting. SteamVR doesn't care if your process keeps running, it cares if it keeps vrclient.dll loaded.

That's exactly what I ended up doing but believing it is more of a workaround than a proper way to work with SteamVR.
Similarly, is there a way to detect when SteamVR is back on and call VR_Init again ? I guess I can't poll events anymore after VR_Shutdown :s

**Comment by JoeLudwig** [comment]
Calling VR_Shutdown after receiving VREvent_Quit is definitely the proper way to interact with SteamVR. That's the entire point of that event.

Can you tell me more about your app? If it's an overlay app you could just add yourself to the list that SteamVR auto-launches when it starts up.

**Comment by ahtur** [comment]
> Calling VR_Shutdown after receiving VREvent_Quit is definitely the proper way to interact with SteamVR. That's the entire point of that event.
> 
> Can you tell me more about your app? If it's an overlay app you could just add yourself to the list that SteamVR auto-launches when it starts up.

Ok cool :)
No, it's not an overlay app. It's a game-like app that supports multiple input devices at the same time : via DirectX for Gamepads and OpenVR for VR. If SteamVR crashes for whatever reason. I'd like the app to keep on running, basically outputting zeros for VR inputs until SteamVR comes back live again.

**Comment by JoeLudwig** [comment]
You could call VR_Init with VRApplication_Background as your application type. That will return VRInitError_Init_NoServerForBackgroundApp if SteamVR is not running, and success or failure as normal if it is running.

**Comment by ahtur** [comment]
> You could call VR_Init with VRApplication_Background as your application type. That will return VRInitError_Init_NoServerForBackgroundApp if SteamVR is not running, and success or failure as normal if it is running.

Great, I will try that, thanks !
I also have a similar question regarding controllers.  When I turn a controller off and on again during a session (we have very long game sessions where we don't use VR controllers all the time), I get tracking data again but noting from the actions anymore. Could you please suggest a way to get the actions again on the fly after turning off and on a controller ?
