### ISSUE TITLE
Can't change action Manifest path, can't get action manifest path.

### ISSUE THREAD

**Issue by mkultra333** [ValveSoftware/openvr#1067]
SteamVR has broken backwards compatability with my app, it should be using legacy controls but suddenly it is trying to load non-existent action manifests.

Steam support haven't gotten back to me, so in a desperate attempt to get VR working again for my users, I'm trying to update to the latest OpenVR so I can add action manifests and get it working again.

But I'm stuck at the very first hurdle.  

Calling SetActionManifestPath constantly returns VRInputError_MismatchedActionManifest, since I guess steam has set some bogus manifest that caused the whole problem in the first place.  

But I can't change whatever bogus manifest path steam has set, nor can I even get any idea of what it is.  Why is there no GetActionManifestPath function?

My released VR app is dead in the water at the moment because of these issues.  That means my users have paid for useless software.  Either steam needs to go back to correctly making my app use legacy VR controls, or I need some way to correct the action manifest paths steam is using.

**Comment by mikorigames** [comment]
When i publish the game and i run it on Steam i have the message “steam action manifest not found” and controller buttons don’t work. But if i run the game directly in the folder it works well.

**Comment by mkultra333** [comment]
I know of 3 other devs having this same issue.  One of them also could get it working by directly running the exe, I tried it but unfortunately it doesn't work for me.

One has tracked it down to a missing option on the steamworks vr options page.

https://github.com/ValveSoftware/steamvr_unity_plugin/issues/354#issuecomment-471807017

If in steamworks you go to App Data Admin / Misc / View Raw Settings and load the Raw Configuration Data page, you'll see a key "openvr_action_manifest_path" that has bad data, in my case just a blank "".
There's suppose to be a way to change this on the VR setting page but the option is missing.



What I really need is some way to get rid of this key completely, or set it to whatever will let my app go back to using legacy VR controls instead of action manifests.

**Comment by mkultra333** [comment]
> When i publish the game and i run it on Steam i have the message “steam action manifest not found” and controller buttons don’t work. But if i run the game directly in the folder it works well.

If you haven't already, it might be a good idea to put in a support request to steamworks.

https://help.steampowered.com/en/wizard/HelpWithPublishing?issuedid=923

I've put one in, so have several other devs, we're all waiting for any response.  Let me know if they get back to you.

**Comment by mikorigames** [comment]
Me too, I don’t have that option in my Steamwork page. Support request sent.

**Comment by EntroPiGames** [comment]
For anyone looking for a temporary fix to this problem, a user on the [Steamworks Development forums](https://steamcommunity.com/groups/steamworks/discussions/0/1836811737991032581/?tscn=1552410087#c1836811737993480682) came up with a way to set the value using an Ajax Request (in the web console) from the VR settings page:

> var appId = 1234;
> AppsAjaxRequest(
> 				g_szBaseURL + '/apps/setvrdata/' + appId,
> 				{
> 					'openvr' : $('vr_sdk_openvr').checked ? 1 : 0,
> 					'othervr' : $('vr_sdk_othervr').checked ? 1 : 0,
> 					'othervr_rift_13' : $('vr_sdk_othervr_rift13').checked ? 1 : 0,
> 										'cont_steamvr' : $('vr_controller_steamvr').checked ? 1 : 0,
> 					'action_manifest_path' : 'actions.json',
> 					'cont_oculus' : $('vr_controller_oculus').checked ? 1 : 0,
> 					'cont_xinput' : $('vr_controller_xinput').checked ? 1 : 0,
> 					'cont_kbm' :  $('vr_controller_kbm').checked ? 1 : 0,
> 					'playarea_seated' : $('vr_playarea_seated').checked ? 1 : 0,
> 					'playarea_standing' : $('vr_playarea_standing').checked ? 1 : 0,
> 					'playarea_roomscale_width' : $('vr_playarea_roomscale_width').value,
> 					'playarea_roomscale_depth' : $('vr_playarea_roomscale_depth').value,
> 					'playarea_360_required' : $('vr_playarea_360_required').checked ? 1 : 0,
> 					'vrheadset_streaming' : ( $J('input[name=vrheadset_streaming]:checked').attr('id') == 'vrheadset_streaming_hmdview' ) ? 1 : 0,
> 									},
> 				function ( results )
> 				{
> 					if ( results[ 'success' ] )
> 					{
> 						// no error, reload page
> 						$('AjaxOutput').innerHTML = 'Reloading...';
> 						RefreshCallback( results );
> 					}
> 					else
> 					{
> 						$('AjaxOutput').innerHTML = "<span style='color:red'>" + results.message + "</span>";
> 					}
> 				}
> 			);

This fixed won't work though if you need to revert to legacy controls.

**Comment by mkultra333** [comment]
Yeah, doesn't fix the issue for me unfortunately.  Does anyone here know how if there's a simple change that can be made to the above script to get the game to go back to legacy controls?  Perhaps a way to delete the 'action_manifest_path' key completely, or what it needs to be set to to use legacy controls?

**Comment by jonpile** [comment]
The Steamworks site has been updated with a fix for this issue, and I've gone through and updated all games that were inadvertently affected. Thanks for the report!

An update is coming soon for those that are looking to easily use the new VR input system support for an action manifest.

**Comment by mkultra333** [comment]
Just tested, checked my raw data, no more action manifest key, I published just to be sure.

Tested my game, worked fine again.  Tested SteamVR binding options, they brought up legacy controls instead of an error.

So it's looking good, thanks!
