### ISSUE TITLE
Access Room View Camera in Unity

### ISSUE THREAD

**Issue by tomday** [ValveSoftware/openvr#108]
Is there anyway to access the standard front-facing camera on the HTC Vive in unity. Something similar to the "Room View" Camera on the SteamVR Dashboard.

**Comment by JoeLudwig** [comment]
An API for the camera data is on our TODO list, but we don't have a date for when it will arrive. Keep an eye on the API updates.

**Comment by crevver** [comment]
Month later ping! 
Trying to translate my AR experience "Rainbow Jellies to Vive, everything is done, it is awesome, but would like to hook up external camera, so any advice on getting the the camera on, distorting etc helpful. 

Thx,
C
www.wrenar.com
