### ISSUE TITLE
Need help: Can't add device xxx: Can't add a second HMD

### ISSUE THREAD

**Issue by r57zone** [ValveSoftware/openvr#1085]
Hi, I’m trying to change the name of the "driver_sample" driver to "tovr". 
HeadsetWindow starts up, but the black screen, here is the log:
```
Driver 'tovr' started activation of tracked device with serial number '1000'
  driver tovr implements interfaces IVRSettings_002 ITrackedDeviceServerDriver_005 IVRDisplayComponent_002 IVRDriverDirectModeComponent_005 IVRCameraComponent_002 IServerTrackedDeviceProvider_004 IVRWatchdogProvider_001 IVRVirtualDisplay_002 IVRDriverManager_001 IVRResources_001 IVRCompositorPluginProvider_001 
Loaded server driver tovr (IServerTrackedDeviceProvider_004) from C:\Games\Steam\steamapps\common\SteamVR\drivers\tovr\tovr\bin\win64\driver_tovr.dll
Active HMD set to tovr.1000
Adding controller type to tovr_hmd
Driver 'tovr' finished adding tracked device with serial number '1000'
Can't add device tovr.1000: Can't add a second HMD
Driver 'tovr' not allowed to add tracked device with serial number '1000'
  driver tovr implements interfaces IVRSettings_002 ITrackedDeviceServerDriver_005 IVRDisplayComponent_002 IVRDriverDirectModeComponent_005 IVRCameraComponent_002 IServerTrackedDeviceProvider_004 IVRWatchdogProvider_001 IVRVirtualDisplay_002 IVRDriverManager_001 IVRResources_001 IVRCompositorPluginProvider_001 
Loaded server driver tovr (IServerTrackedDeviceProvider_004) from C:\Games\Steam\steamapps\common\SteamVR\drivers\tovr\tovr\bin\win64\driver_tovr.dll
App system.generated.vrstartup.exe (tovr_hmd) loaded default binding file:///C:/Games/Steam/steamapps/common/SteamVR/resources/config/legacy_bindings_generic_hmd.json
App openvr.component.vrcompositor (tovr_hmd) loaded default binding file:///C:/Games/Steam/steamapps/common/SteamVR/resources/config/vrcompositor_bindings_generic_hmd.json
Using existing HMD tovr.1000
```

```
Can't add device tovr.1000: Can't add a second HMD
Driver 'tovr' not allowed to add tracked device with serial number '1000'
```

Does anyone know what the problem is and how to fix it? Second vr display in extended mode.
If i run this driver as "driver_null" it works.

[Here](https://github.com/r57zone/test-driver) are the [sources](https://github.com/r57zone/test-driver/blob/master/TOVR%20SteamVR%20driver/samples/driver_sample/driver_sample.cpp), configs[[1]](https://github.com/r57zone/test-driver/blob/master/Steam/config/steamvr.vrsettings)[[2]](https://github.com/r57zone/test-driver/blob/master/Steam/steamapps/common/SteamVR/drivers/tovr/driver.vrdrivermanifest) and [binaries](https://github.com/r57zone/test-driver/tree/master/Steam/steamapps/common/SteamVR/drivers/tovr/tovr/bin).

**Comment by r57zone** [comment]
@JoeLudwig You don't know what the problem might be? Thanks.

**Comment by bjj** [comment]
You only need to call TrackedDeviceAdded once for your HMD device (ideally before Init returns, if you want to be detected in the normal driver load order).  You are calling it again at some point and failing because only one HMD is allowed.  You can add more devices, but they'd have to have other serial numbers and the additional ones can't be of type HMD.

(If you had gotten by the "no second HMD" check it would have printed "Rejecting duplicate..." because it's the same S/N as the existing device)

**Comment by r57zone** [comment]
@bjj I use Driver_Sample as a driver base. In Init, HMD is added 1 time and 2 times the controllers, all have different serial numbers.

**Comment by r57zone** [comment]
It also works if return the name Null, it is strange.

**Comment by r57zone** [comment]
I managed to fix the problem, I added the "if (! M_pNullHmdLatest)" check, but the driver still does not work. Now there’s some tracking problem и black screen. Why can not make Driver_sample, which works as it should?
