### ISSUE TITLE
IVRScreenshots::SubmitScreenshot is broken, always ScreenshotAlreadyInProgress after first submission

### ISSUE THREAD

**Issue by sbsce** [ValveSoftware/openvr#1087]
IVRScreenshots is not working correctly.

I am calling `IVRScreenshots::HookScreenshot` with 
`vr::EVRScreenshotType types[] = { vr::EVRScreenshotType::VRScreenshotType_Stereo };`
then listening for the `VREvent_RequestScreenshot` event that happens when the user triggers the default SteamVR screenshot by pressing system+trigger button, and the event works correctly the first time.

I'm then taking the screenshot, getting the paths using `IVRScreenshots::GetScreenshotPropertyFilename`, writing the screenshot as a .tga file to the paths, and submitting it using `IVRScreenshots::SubmitScreenshot`, of course with the correct handle and type that I initially got from the `VREvent_RequestScreenshot`.

`IVRScreenshots::SubmitScreenshot` returns no error, and the screenshot is successfully added to the Steam Library, so that all works. It only works once though. From that point on, it's no longer possible to trigger any screenshots. When the user presses system+trigger button again, nothing happens. `VREvent_RequestScreenshot` is never happening again. When I try to manually trigger a screenshot using `IVRScreenshots::TakeStereoScreenshot`, I do get the error code `VRScreenshotError_ScreenshotAlreadyInProgress (108)`.

So it works perfectly, once, but after that taking screenshots is broken because SteamVR thinks the first screenshot was never actually done.

**Comment by kisak-valve** [comment]
Related https://github.com/ValveSoftware/SteamVR-for-Linux/issues/185.

**Comment by bjj** [comment]
This should be fixed in tomorrow's beta (which will be 1.4.1)

**Comment by sbsce** [comment]
> This should be fixed in tomorrow's beta (which will be 1.4.1)

That's great news, thanks!

**Comment by sbsce** [comment]
I can confirm this is fixed now with 1.4.1
