### ISSUE TITLE
RuntimePath() causes an exception

### ISSUE THREAD

**Issue by sergioberg** [ValveSoftware/openvr#1093]
RuntimePath() sometimes causes an exception:

![image](https://user-images.githubusercontent.com/12216723/56010565-8f2bbb80-5cfd-11e9-8b0a-cf1e7591bd98.png)

openvr_api.dll v1.2.10
Windows 7SP1
Windows 10

**Comment by JoeLudwig** [comment]
Can you provide a .dmp file for this crash? I'd like to crack it open and see what's happening in openvr_api.dll.

**Comment by sergioberg** [comment]
[dump.zip](https://github.com/ValveSoftware/openvr/files/3076031/dump.zip)
This can be reproduced very easily, it happens if you call this function twice.

**Comment by JoeLudwig** [comment]
Thanks for the test app/repro case.

I don't see an exception from calling it twice running your code. When I call VR_RuntimePath twice from C++ the second call definitely corrupts the results of the first call. I'll fix that.

**Comment by JoeLudwig** [comment]
This will be fixed in the 1.5.x SDK.
