### ISSUE TITLE
Need help: Tracking not working error 102 (driver_sample changing name)

### ISSUE THREAD

**Issue by r57zone** [ValveSoftware/openvr#1094]
Hi, I’m trying to change the name of the "driver_sample" driver to "tovr". With name "driver_null" there are no problems and the driver works well, but if I try to change the name, tracking does not work.
Here is the log (red lines):
```
PoseUpdated from driver 7 for object 0 which is actually from 6
PoseUpdated from driver 7 for object 1 which is actually from 6
PoseUpdated from driver 7 for object 2 which is actually from 6
PoseUpdated from driver 7 for object 0 which is actually from 6
PoseUpdated from driver 7 for object 1 which is actually from 6
PoseUpdated from driver 7 for object 2 which is actually from 6
```
What does it mean? 
vr::VRServerDriverHost ()->TrackedDevicePoseUpdated () is called in its void RunFrame. This works in driver_null, but does not work when renamed.

[Here](https://github.com/r57zone/test-driver) are the [sources](https://github.com/r57zone/test-driver/blob/master/TOVR%20SteamVR%20driver/samples/driver_sample/driver_sample.cpp), configs[[1]](https://github.com/r57zone/test-driver/blob/master/Steam/config/steamvr.vrsettings)[[2]](https://github.com/r57zone/test-driver/blob/master/Steam/steamapps/common/SteamVR/drivers/tovr/driver.vrdrivermanifest) and [binaries](https://github.com/r57zone/test-driver/tree/master/Steam/steamapps/common/SteamVR/drivers/tovr/tovr/bin).

**Comment by r57zone** [comment]
@bjj Hi, could you tell what the problem is?

**Comment by peroht** [comment]
What does the output of your Steam\logs\vrserver.txt tell you about when it is trying to load your driver?

When you change the name of a driver you need to match the driver name in your code with the actual driver folder name. E.g. looking in the sample driver code you have this:

// keys for use with the settings API
static const char * const k_pch_Sample_Section = "driver_sample";

and looking in your folder structure you will see the same folder named "driver_sample". 

So if you rename your k_pch_Sample_Section to something else you also need to rename your folder.

**Comment by r57zone** [comment]
It seems that this section is responsible only for the section name in json config, but in any case, I have the folder name "tovr" and the section name "tovr" and the name of the dll files is "driver_tovr".

https://github.com/r57zone/test-driver/blob/master/TOVR%20SteamVR%20driver/samples/driver_sample/driver_sample.cpp#L54

https://github.com/r57zone/test-driver/tree/master/Steam/steamapps/common/SteamVR/drivers

**Comment by peroht** [comment]
Try driver_tovr instead.

**Comment by JoeLudwig** [comment]
I assume that driver 7 above is your driver. Do you know what driver 6 is? driver_lighthouse maybe?

One driver isn't allowed to set poses for another. It looks like your driver doesn't own the HMD and whatever objects 1 and 2 are, but is trying to set the poses for those devices.

**Comment by r57zone** [comment]
There are no other drivers except default. I not have base stations and HTC Vive.
I use VR Display in advanced mode.
The same driver works perfectly if "driver_null" is named, which is a bit strange.

**Comment by JoeLudwig** [comment]
I've improved the log message you're getting to look more like this: (This will be in 1.4.4. or 1.4.5)
`Fri Apr 26 2019 10:44:55.928 - PoseUpdated from driver gamepad (4) for device index 0 which is owned by driver lighthouse (13)
`

Some other driver is definitely providing an HMD and two other devices and then you're trying to update poses for those devices. Maybe drvier_null or driver_sample are still active?

**Comment by peroht** [comment]
In your steamvr.settings file have you added this under the steamvr section?

```
"steamvr" : {
        "activateMultipleDrivers": true
    }
```

**Comment by r57zone** [comment]
It seems that he is trying to update himself, but I do not understand why the different index, I tried to remove all other drivers except mine and still -102, the driver runs, but there is no tracking. Everyone (HMD - vr display extended, controller 1, controller 2) has different serial numbers, different IDs. I added protection from re-creation (although it worked without problems with the name driver_null). 

For some reason this works if the name is "driver_null", also the driver_null has a gray grid for centering. The "driver_null" name is somehow executed. 

@peroht yes, https://github.com/r57zone/test-driver/blob/master/Steam/config/steamvr.vrsettings

**Comment by JoeLudwig** [comment]
Can you post a system report?

**Comment by r57zone** [comment]
Like here https://www.groovypost.com/howto/generate-windows-10-system-diagnostics-report/ ?

**Comment by r57zone** [comment]
I have a test plugin (changing the position of the HMD and keyboard controllers). You can check my driver this way yet.
You need to unpack the [archive](https://github.com/TrueOpenVR/TrueOpenVR-Core/releases/download/0.7/TrueOpenVR.0.7.Portable.zip), run Settings, select the keyboard.
Then you can use the Steam driver https://github.com/r57zone/test-driver/tree/master/Steam

**Comment by kisak-valve** [comment]
Hello @r57zone, @JoeLudwig is asking for a SteamVR system report - https://github.com/ValveSoftware/SteamVR-for-Linux/blob/master/issue_template.md#how-to-collect-steamvr-system-information

**Comment by r57zone** [comment]
Made - https://www.sendspace.com/file/s1x6wg

**Comment by bjj** [comment]
@r57zone I hid that comment because the site appears to have a lot of malware and deceptive ads.

Can you upload your system report to something like gist or pastebin?

**Comment by r57zone** [comment]
@bjj on the download link there is a plain text file.

Ok here - https://github.com/r57zone/steam-log

**Comment by bjj** [comment]
We seem to be loading your driver twice.  I'm not sure why.  It's possible that something about your vrpathreg points to the same driver path twice, and we are not correctly de-duping it.

**Comment by r57zone** [comment]
@bjj "vrpathreg.exe show" shows 1 path to my driver.

**Comment by bjj** [comment]
@r57zone Can you paste the output in?  I suspect what's happening is that there's an explicit path to it (under "external drivers") as well as the implicit path (since you have installed it under your "Runtime path").  We find it both ways, and then load it both ways.

**Comment by r57zone** [comment]
@bjj 
```
Runtime path = C:\Games\Steam\steamapps\common\SteamVR
Config path = C:\Games\Steam\config
Log path = C:\Games\Steam\logs
External Drivers:
        C:\Games\Steam\steamapps\common\SteamVR Driver for Razer Hydra
        C:\Games\Steam\steamapps\common\SteamVR\drivers\tovr
```

**Comment by bjj** [comment]
Yes, your "external" path is actually pointing inside SteamVR's internal driver path, so there's one copy from being found automatically and one from being found explicitly.

I'll fix that bug, but you can use vrpathreg removedriver <path> in the mean time to remove that extra path

**Comment by r57zone** [comment]
Removed the path, it working, thanks for help.
