### ISSUE TITLE
SteamVR beta 1.4.1 breaks proximity sensor support through the SteamVR Input API

### ISSUE THREAD

**Issue by muchcharles** [ValveSoftware/openvr#1096]
SteamVR beta 1.4.1 seems to have broken the ability to do a generic headset binding for the proximity sensor through SteamVR input (and when SteamVR input is active the legacy way to check the proximity sensor doesn't work).  On the prior version this binding would work regardless of headset brand, so long as it had a sensor:

```
{
	"name": "Default bindings for Generic HMD",
	"controller_type": "generic_hmd",
	"bindings":
	{
	 "/actions/main" : {
          "sources" : [
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/main/in/generic_hmd_proximitysensor"
                  }
               },
               "mode" : "button",
               "path" : "/user/head/proximity"
            }
	  ]
	 }
	},
	"description": ""
}
```

The action's bActive and bData now always return false starting in 1.4.1.  I can give you a reproducing steam app id if needed.

I tested on stable and things work fine.  The prior beta before 1.4.1 worked fine too.

**Comment by muchcharles** [comment]
It works if I manually add a binding for a specific headset, but doesn't work with generic_hmd anymore.  This is crucial, because there is no way to know the names of every headset out there and new ones can arrive frequently in the future (e.g. no idea how to even add a binding for the Index at this point)!

**Comment by Mahallon** [comment]
Has there been a fix for this? @muchcharles I tried manually adding a binding for the index and its not working, How did you add the binding manually?

**Comment by muchcharles** [comment]
@Mahallon at one point they broke generic_hmd.json bindings so you had to make a specific one for each headset, but I think they've fixed that.  Add:
`generic_hmd.json`

`{
	"name": "Default bindings for Generic HMD",
	"controller_type": "generic_hmd",
	"bindings":
	{
	 "/actions/main" : {
          "sources" : [
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/main/in/generic_hmd_proximitysensor"
                  }
               },
               "mode" : "button",
               "path" : "/user/head/proximity"
            }
	  ]
	 }
	},
	"description": ""
}`


or Index-specific:

`index_hmd.json`

`{
	"name": "Default bindings for Valve Index HMD",
	"controller_type": "index_hmd",
	"bindings":
	{
	 "/actions/main" : {
          "sources" : [
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/main/in/generic_hmd_proximitysensor"
                  }
               },
               "mode" : "button",
               "path" : "/user/head/proximity"
            }
	  ]
	 }
	},
	"description": ""
}`

**Comment by Mahallon** [comment]
Thank you for such a quick reply! 

did you also have to include something like 
`{ "controller_type": "index_hmd", "binding_url": "bindings_index_hmd.json" },`

to the actions.json file or does it to that during the generation function?

**Comment by muchcharles** [comment]
Yeah you have to have it in the overall manifest, I'm using UE4 where if I remember right that is automatically generated (I think I had to maybe modify a source file that generates it to add it to the list).  I'm not sure about unity.
