### ISSUE TITLE
Accessing pose data of controllers/trackers in a background app in new IVRInput

### ISSUE THREAD

**Issue by peroht** [ValveSoftware/openvr#1103]
I am in the process of migrating a background app (EVRApplicationType::VRApplication_Background) to the new IVRInput system. 

I can not figure out how to access the pose data of a controller/tracker. I must be missing some piece of the puzzle. The only action i'd like to listen to is the controller pose updates.

The examples I am looking at (e.g. the hellovr_opengl) bind handles to specific actions, and I understand that bit. 

Starting here:
[https://github.com/ValveSoftware/openvr/blob/master/samples/hellovr_opengl/hellovr_opengl_main.cpp#L733](https://github.com/ValveSoftware/openvr/blob/master/samples/hellovr_opengl/hellovr_opengl_main.cpp#L733)

i understand it as this call will feed data from openvr to the this application in question. However I would like to get the pose of a controller/traker at any time. 

Looking at this call:

[https://github.com/ValveSoftware/openvr/blob/master/samples/hellovr_opengl/hellovr_opengl_main.cpp#L547](https://github.com/ValveSoftware/openvr/blob/master/samples/hellovr_opengl/hellovr_opengl_main.cpp#L547)

i understand that this is the default controllers to setup for e.g. vibration of the controller in the example.

How would I go about setting up a handle so that I get notified when the pose is updated?
e.g. I've tried adding paths such as 

"/user/hand/left"
"/user/hand/left/pose/raw"
"/user/hand/left/pose_raw"

but seem only to get zero out of the call to 

https://github.com/ValveSoftware/openvr/blob/master/samples/hellovr_opengl/hellovr_opengl_main.cpp#L776

where my subsequent calls to extract the position/quat render xyz=0 and qwxyz=0.5. I believe I am not setting up my action handle/path correctly.

This query was possible before using GetControllerStateWithPose() for specific devices.

How should i set up my call to UpdateActionState()?

[https://github.com/ValveSoftware/openvr/blob/master/samples/hellovr_opengl/hellovr_opengl_main.cpp#L731](https://github.com/ValveSoftware/openvr/blob/master/samples/hellovr_opengl/hellovr_opengl_main.cpp#L731)

What is the corresponding method to query this today?
What am I missing to make it work with the new system?

**Comment by JoeLudwig** [comment]
Hi Peter,

In the new input system you get pose data for a device by creating a pose action and then binding it to /pose/raw (or something like that) in your binding file.  Then you can get the actual transform with GetPoseActionData.

GetControllerStateWithPose is disabled once you start using the new input system (i.e. once you call SetActionManifestPath). What it returns for legacy apps is the latest controller state and the pose as of the time when that controller state was last changed. That pose is intended to use for throwing and such and is always historical.  (The pose you get from WaitGetPoses is predicted forward to the time when the current frame is expected to be emitted from the display, so it's about 2 frames ahead from the time when it was generated, depending on the attached hardware.)

Do do the equivalent of GetControllerStateWithPose you can call GetDigitalActionData on the action you're wanting a pose for, and then call GetPoseActionData with that time. 

You should call UpdateActionState once per input frame. Call it, then call Get*ActionData for your actions, then process that input in your app.  The results from Get*ActionData only update when you call UpdateActionState, so you need to call it on a regular basis.

You can see the action manifest for HelloVR for an example of how to set up pose actions: https://github.com/ValveSoftware/openvr/blob/master/samples/bin/hellovr_actions.json

**Comment by peroht** [comment]
Joe,
many thanks for the help and the clarifications.

I've worked a bit further and have now got a working action manifest file. 
I am able to use the Binding UI to remap buttons of the vive controller. 
I am able to call GetAnalogActionData()/GetDigitalActionData() and parse the results fine. 

However, when I call GetPoseActionData() I immediately get an access violation / unhandled exception in vrclient.dll. 

Based on the hellovr example, the action set I am using is:
/actions/demo

with the actions:
/actions/demo/in/AnalogInput
/actions/demo/in/HideCubes
/actions/demo/in/Hand_Left
/actions/demo/in/Hand_Right

Have I understood it correctly that I only need to call UpdateActionState () for the "/actions/demo" (as in the hellovr example) and then anything under that set will be populated? 

I am cleaning up my example code and will hopefully upload a branch to github next week to make things easier and investigate further.
