### ISSUE TITLE
Unhandled exeption in vrclient.dll causing crash upon call to GetPoseActionData()

### ISSUE THREAD

**Issue by peroht** [ValveSoftware/openvr#1105]
This is a new issue and continuation from #1103 . Please read it before.

When I call GetPoseActionData() on seemingly properly bound handles I get an access violation / unhandled exception in vrclient.dll. 
I see no such problem with analogue/digital remappings using GetAnalogActionData/GetDigitalActionData.

Also, to clarify, I would want to access the pose at any time, not just only when an analog/digital action has been fired. 

I've worked a bit further and have now got a working action manifest file that I register via SetActionManifestPath().
I am able to use the Binding UI to remap buttons of the vive controller. 
I am able to call GetAnalogActionData()/GetDigitalActionData() and parse the results fine. 

Based on the hellovr example, the limited action set I am using is:
/actions/demo

with the actions:
/actions/demo/in/AnalogInput
/actions/demo/in/HideCubes
/actions/demo/in/Hand_Left
/actions/demo/in/Hand_Right

Some observations: I have seen that if I have my app running, and if I have defined "/actions/demo/in/Hand_Left" in the manifest and matched it in the code - but have not yet executed the actual remapping in the UI - then the call to GetPoseActionData() returns fine and the pose is reported to not be active. The moment I use the UI and assign the left hand raw the call to GetPoseActionData() crashes my application.

Have I understood it correctly that I only need to call UpdateActionState () for the "/actions/demo" (as in the hellovr example) and then anything under that set will be populated? Or do i require an explicit call to UpdateActionState() for /actions/demo/in/Hand_Left and /actions/demo/in/Hand_Right? I do not really see that in the openvr example.

I am cleaning up my example code and will hopefully upload a branch to github next week to make things easier and investigate further.

In the mean time this is the manifest file:

```
{
    "default_bindings": [
        {
            "controller_type": "vive_controller",
            "binding_url": "vive_debugger_bindings_vive_controller.json"
        }
    ],
    "actions": [
        {
            "name": "/actions/demo/in/HideCubes",
            "type": "boolean"
        },
        {
            "name": "/actions/demo/in/AnalogInput",
            "type": "vector2"
        },
        {
            "name": "/actions/demo/in/Hand_Right",
            "type": "pose"
        },
        {
            "name": "/actions/demo/in/Hand_Left",
            "type": "pose"
        }
    ],
    "localization" : [
        {
            "language_tag": "en_US",
            "/actions/demo/in/AnalogInput" : "Analog Input",
            "/actions/demo/in/Hand_Right" : "Right Hand Pose",
            "/actions/demo/in/Hand_Left" : "Left Hand Pose"
        }
    ]
}
```

And here is the generated binding file:

```
{
   "alias_info" : {},
   "app_key" : "system.generated.vive_debugger.exe",
   "bindings" : {
      "/actions/demo" : {
         "poses" : [
            {
               "output" : "/actions/demo/in/hand_left",
               "path" : "/user/hand/left/pose/raw"
            },
            {
               "output" : "/actions/demo/in/hand_right",
               "path" : "/user/hand/right/pose/raw"
            }
         ],
         "sources" : [
            {
               "inputs" : {
                  "position" : {
                     "output" : "/actions/demo/in/analoginput"
                  }
               },
               "mode" : "trackpad",
               "path" : "/user/hand/left/input/trackpad"
            },
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/demo/in/hidecubes"
                  }
               },
               "mode" : "button",
               "path" : "/user/hand/left/input/trigger"
            }
         ]
      }
   },
   "controller_type" : "vive_controller",
   "description" : "",
   "name" : "My vive_debugger.exe configuration for Vive Controller",
   "options" : {},
   "simulated_actions" : []
}
```

**Comment by JoeLudwig** [comment]
Can you post a dump file of the crash? That should make it easy to track down.

Have you called SetActionManifestPath? How about UpdateActionState?  (It shouldn't crash regardless of the answers to those questions, but they might help me track it down.)

You need to call UpdateActionState with the action set handles you want to be active for the current input frame. Actions are contained within an action set, so if you call UpdateActionState for /actions/demo, you can then call GetPoseActionData for /actions/demo/in/hand_left and /acitons/demo/in/hand_right.  (Obviously you'd need to turn those action and action set names into handles with the appropriate functions.

**Comment by peroht** [comment]
Sure, here is one without the heap.
[vive_debugger.zip](https://github.com/ValveSoftware/openvr/files/3119130/vive_debugger.zip)

**Comment by JoeLudwig** [comment]
I have a fix for the crash. I'll get it into the 1.4.4 beta (not sure exactly when that will come out.)

In the meantime, you should be able to work around this by passing 0.01 for the prediction time instead of 0.

**Comment by JoeLudwig** [comment]
Actually my fix isn't really a fix.

What application type are you using? Still VRApplication_Background?

Does the crash go away if you call vr::VRCompositor() before calling vr::VRInput()->GetPoseActionState()?

**Comment by peroht** [comment]
Yes, still VRApplication_Background - never changed.

When I call vr::VRCompositor() right in the beginning the crash goes away, and it works as expected. Awesome.

I assumed you meant GetPoseActionData there.

To help you further I have attached some log files with the output from vrserver after several restarts. Log #5 is when it is working. Also I've added a log from my program when it is working so you can follow the chain of events in the dump I attached earlier. 

I will clean up the code and upload the repo to github next week.

[logs - vrserver and vive_debugger.zip](https://github.com/ValveSoftware/openvr/files/3120003/logs.-.vrserver.and.vive_debugger.zip)

**Comment by peroht** [comment]
Works nicely. Closing.
