### ISSUE TITLE
Can't map B/A button touches on right Oculus Touch controller

### ISSUE THREAD

**Issue by hlink** [ValveSoftware/openvr#1111]
See the image below. The "Use as Button" mapping option has "click" and "touch" for the left hand controller, but "touch" is not available with any options I can find on the right hand controller.

![image](https://user-images.githubusercontent.com/3581594/57175393-62e8f380-6e00-11e9-89d2-7ac2267ff7c2.png)

**Comment by kisak-valve** [comment]
Possible duplicate of #820.

**Comment by hlink** [comment]
This was fixed in the Steam VR beta (I apparently wasn't opted into the beta branch on this dev machine).
