### ISSUE TITLE
How to control position of the headset using controller?

### ISSUE THREAD

**Issue by off99555** [ValveSoftware/openvr#1112]
Suppose that a Vive headset is displaying something, and tracking well.
I want to disable its position tracking and override by my own tracking implementation. It could be as simple as using Vive controller to determine where the headset will be.
E.g. if the controller is moved to position X, the headset will be at position X too (maybe with some offset).

How would I go about doing this? Suppose that I should also have the option to not override rotation, only position.
## What I tried so far
I've tried writing a driver to set the position of a VIRTUAL headset before and it works. But it's not involving accessing any Vive controller. It's just about using the keyboard to move the virtual headset. 
The problem I'm facing now is that when I try to include `openvr.h` to access pose of the controller instead of keyboard, there is error saying there is redefinition occur.
So I cannot use controller. It's probably caused by including both `openvr_driver.h` and `openvr.h` with have duplicate code.

![image](https://user-images.githubusercontent.com/15215732/57183946-ff34f800-6edd-11e9-8953-8cbd4ac59a86.png)

**Comment by cwlmyjm** [comment]
**openvr_driver.h** is used for driver and **openvr.h** is used for vr application, you might want to use controller in your driver but I think it's better to divide in two projects: driver and vr application(like Background or Utility), vr application can read controller status and pass data to driver. There exists many same definitions in two headers, so I think it is not designed for using together.

**Comment by off99555** [comment]
But I just want to override the position of the headset. If I do it as you
suggest then I'll need to do some networking to pass the data to the
driver, right?
What do you think?

**Comment by off99555** [comment]
OK. I went and comment all the code in `openvr.h`, then I uncomment only the parts that I use. Turns out that it works!
I can now call `VR_Init()` inside a driver function like `GetPose()`. It's working. I can now copy the controller position to the headset using UniverseRawAndUncalibrated pose.
The next problem I meet is that I don't know which `EVRApplicationType` to pass into the `VR_Init()` function, so I just passed `VRApplication_Scene` which is too big for my job. (It stops other apps).
Another issue is that when I quit SteamVR, there is unexpected error happening.
![image](https://user-images.githubusercontent.com/15215732/57299205-2e29b480-70fe-11e9-90d1-3a2a340cb1e1.png)

 I think it's probably about shutting down the `IVRSystem`. I tried putting the `VR_Shutdown()` function inside `Deactivate()` function of the driver but it is still causing the same unexpected error.


1. Which application type should I use if I just want the system to just access position from a controller?
2. How do I shutdown IVRSystem inside a driver properly?

**Comment by JoeLudwig** [comment]
Calling VR_Init from inside your driver is going to end in tears.

You would be much better off running a second process that calls VR_Init and talking to it via IPC.

**Comment by off99555** [comment]
@JoeLudwig Hahaha. That's what I am facing right now.
I also thought about using IPC but I think it's going to cause a lot of problems as I am an amateur with IPC in C++.
Anyway, I've found a function called `vr::VRServerDriverHost()->GetRawTrackedDevicePoses()` that is callable without the need to initialize the VR system. It's exactly what I need. It means that I can just ditch the `VR_Init` and use only driver header file.

So the only problem I have now is how do I get property of device at index `i` given that I don't have access to `IVRSystem` ? Do you know it

**Comment by off99555** [comment]
I think that my question/issue is slowly turning into a tutorial. LOL

**Comment by JoeLudwig** [comment]
Check out CVRPropertyHelpers (which you can get from vr::VRProperties() inside a driver). You can query any properties you like with that interface, including model number, etc.

**Comment by off99555** [comment]
@JoeLudwig 
I'm trying to use the `vr::VRProperties()->GetStringProperty()` but I don't quite understand the arguments.
```cpp
	/** Returns a single typed property. If the device index is not valid or the property is not a string type this function will
	* return 0. Otherwise it returns the length of the number of bytes necessary to hold this string including the trailing
	* null. Strings will always fit in buffers of k_unMaxPropertyStringSize characters. */
	uint32_t GetProperty( PropertyContainerHandle_t ulContainerHandle, ETrackedDeviceProperty prop, VR_OUT_STRING() void *pvBuffer, uint32_t unBufferSize, PropertyTypeTag_t *punTag, ETrackedPropertyError *pError = 0L );


	/** Returns a string property. If the device index is not valid or the property is not a string type this function will
	* return 0. Otherwise it returns the length of the number of bytes necessary to hold this string including the trailing
	* null. Strings will always fit in buffers of k_unMaxPropertyStringSize characters. */
	uint32_t GetStringProperty( PropertyContainerHandle_t ulContainerHandle, ETrackedDeviceProperty prop, VR_OUT_STRING() char *pchValue, uint32_t unBufferSize, ETrackedPropertyError *pError = 0L );

	/** Returns a string property as a std::string. If the device index is not valid or the property is not a string type this function will
	* return an empty string. */
	std::string GetStringProperty( vr::PropertyContainerHandle_t ulContainer, vr::ETrackedDeviceProperty prop, vr::ETrackedPropertyError *peError = nullptr );
```
What do I send as the first argument? Can you write a short 2-3 lines example?

Suppose what's I'm trying to do is to create this boolean:
```cpp
m_vrSystem->GetTrackedDeviceClass(deviceIndex) == vr::ETrackedDeviceClass::TrackedDeviceClass_Controller
```
What's a similar statement using `VRProperties()`?

**Comment by JoeLudwig** [comment]
See vr::VRProperties()->TrackedDeviceToPropertyContainer(...)  It'll turn any device index into that first argument.

You're probably already using that function in your driver:
https://github.com/ValveSoftware/openvr/blob/b72abcebff7e6c6c70ce8ac8f6a09b70d44397e2/samples/driver_sample/driver_sample.cpp#L192

**Comment by off99555** [comment]
It's working! 😋 
I think the core of what I want to do is pretty much done.
This code finds the first device that is a controller:
```cpp
		uint32_t controllerIdx = 1;
		vr::CVRPropertyHelpers* props = vr::VRProperties();
		for (uint32_t i = 0; i < vr::k_unMaxTrackedDeviceCount; i++)
		{
			vr::PropertyContainerHandle_t container = props->TrackedDeviceToPropertyContainer(i);
			vr::ETrackedPropertyError err;
			int32_t deviceClass = props->GetInt32Property(container, 
				vr::ETrackedDeviceProperty::Prop_DeviceClass_Int32, &err);
			if (deviceClass == vr::ETrackedDeviceClass::TrackedDeviceClass_Controller)
			{
				controllerIdx = i;
				break;
			}
		}
```
I run this everytime in `GetPose()`. If you know a better way to optimize it, please tell me.
Thank you very much.

**Comment by peroht** [comment]
Speaking about first device.. 

I'd recommend you to also look up the actual manufacturer/model number of the controller instead of immediately consuming the first one. 

From what I've learned there is nothing that guarantees that the first controller is the one you always want since the numbers of devices can change now and then.

**Comment by AkayabeKimitsu** [comment]
Heey! 

I know it may be silly question, but can you share, how do you set headset position?

I really can't move it with trackeddeviceposeupdated, like i do with controllers,
I'm setting id to 0 for hmd, but it don't appear to be working.

Sorry for very short ask, but any help would be appsomething (I'll be thankful).
Thanx!

**Comment by off99555** [comment]
@AkayabeKimitsu In the driver code for the headset, there is a GetPose() function that you need to return whatever position you want the headset to be at. In my case, I just return a controller's position.

**Comment by AkayabeKimitsu** [comment]
Oh! It's working!
Thanks for replying.
