### ISSUE TITLE
Unable to edit "Vive" bindings any more (stable or beta branch)

### ISSUE THREAD

**Issue by peroht** [ValveSoftware/openvr#1116]
With the new input system I am defining an action "/actions/omnitrack/in/treadmill_tracker" to pose tracking data to an application. This means the application can be driven with either the HMD, a Vive controller, a Vive Tracker or whatever device is posting a pose. 

With 1.3.23 I am able to edit the "Vive" controller and bind the raw pose to a "treadmill_tracker" path. 

However, 
In 1.4.9 Beta I do not see the "Vive" controller in the binding interface anymore. I am thus unable to bind the raw pose to the "treadmill_tracker" path. According to vrserver the binding file for Vive is loaded. The treadmill_tracker action appears at the top with a warning saying it is not bound. 

In 1.4.9 Beta I only see the following items
"Index Controller"
"Oculus Touch"
"Vive Controller"

where did the
"Vive" go?

This does not work in the 1.7.15 or 1.8.14 beta branch. Any news?

**Comment by hendrik-schulte** [comment]
We have the same problem!

**Comment by peroht** [comment]
I've written about this here:
#1159 https://github.com/ValveSoftware/openvr/issues/1159

SteamVR 1.7.15.

**Comment by peroht** [comment]
I've tried this with 1.8.20 without success using a Vive headset. However with a Vive Pro headset this works. 
[https://github.com/ValveSoftware/openvr/issues/1250](url)
