### ISSUE TITLE
Overlay applications stopped receiving input API actions

### ISSUE THREAD

**Issue by dantman** [ValveSoftware/openvr#1135]
Previously I managed to get the SteamVR Input API working with an overlay application (using the Unity plugin and ValveSoftware/steamvr_unity_plugin#336) and it was properly receiving actions from the SteamVR Input API.

However I opened up my project recently and found that it is no longer receiving actions from the input API.

- Logs indicate it successfully registers with SteamVR and identifies itself with the correct id
- Logs indicate it "successfully load(s) 8 actions from the action manifest"
- The binding UI indicates that actions for my overlay are correctly bound to my Vive controller
- However despite this, while the overlay is running in the SteamVR Unity plugin's "Input Live View" window's debugging none of the actions ever go "Active" when I press the bound buttons on the controller and my code never receives the events that were previously working when buttons are pressed.

My only guess here is that an update to the SteamVR runtime stopped handling bindings for overlays correctly. I tried switching to the beta and the issue is the same. I also tried updating the SteamVR Unity plugin and openvr api and it's still not working.

**Comment by Hokage3211** [comment]
I very much need a fix for this, as the current fix suggested does exactly what I needed, but disables any interaction because all tracked controllers and HMD objects become empty and don't show position at all.

**Comment by Hokage3211** [comment]
*edit, while the controllers seem to track and operate fine, the headset does appear to not track in unity, possibly need to check for it elsewhere?

**Comment by dantman** [comment]
It appears my issue was actually caused by a race condition. SteamVR's Initialize event started firing before my code that registers the event listener. As a result my SteamVR Input handling code stopped being enabled.
