### ISSUE TITLE
VRInput::GetSkeletalBoneData incompatible with ulRestrictedToDevice

### ISSUE THREAD

**Issue by ascmt** [ValveSoftware/openvr#1140]
If VRInput::UpdateActionState() is called with VRActiveActionSet_t::ulRestrictedToDevice set to a valid and appropriate VRInputValueHandle_t parameter, VRInput::GetSkeletalBoneData() will return VRInputError_NoData.

Tested with setting ulRestrictedToDevice to handles for "/user/hand/left" and "/user/hand/left/input/skeleton/left".

Setting ulRestrictedToDevice to k_ulInvalidInputValueHandle in the UpdateActionState() call allows GetSkeletalBoneData() to return VRInputError_None and appears to correctly fill out the bone transform array.

For "/user/hand/left" the corresponding GetDigitalActionData() call still succeeds and reports input as expected, so this appears to be a problem specific to GetSkeletalBoneData().

**Comment by dmorate** [comment]
Hello, 
I use this
`vr::VRActiveActionSet_t actionSet;
actionSet.ulActionSet = m_ActionSet;
actionSet.ulRestrictedToDevice = k_ulInvalidInputValueHandle;`

**Comment by ascmt** [comment]
@dmorate Yes, please reread the OP.  The bug occurs when setting anything OTHER than actionSet.ulRestrictedToDevice = k_ulInvalidInputValueHandle.

**Comment by dmorate** [comment]
@ascmt following the doc [https://github.com/ValveSoftware/openvr/wiki/SteamVR-Skeletal-Input](url)

>  be sure to pass vr::k_ulInvalidInputValueHandle as the ulRestrictToDevice parameter, since skeletal actions don't support restricting to a particular device.

**Comment by ascmt** [comment]
Yes, that is exactly a problematic restriction that prevents compartmentalization of input loops, forcing one to perform a global UpdateActionState just to update the skeleton.  It is counter-intuitive given the rest of the VRInput API's input-path structure and usage examples.  It makes the ulRestrictedToDevice parameter practically useless for applications that want to use the skeleton, which does not seem like a sensible general restriction.

If it is indeed technically impossible to restrict skeleton with an input handle, then a preferable solution would be to have a separate explicit skeleton update call, instead of requiring a global UpdateActionState() call with k_ulInvalidInputValueHandle.  If the skeleton functionality cannot conform to the full API, then it should have its own.

**Comment by joevdh** [comment]
Hi ascmt, I'm not able to reproduce this issue locally.  Here's the code I'm testing with:

```
// Get the device handle for the user's left hand
vr::VRInputValueHandle_t hLeftHandDevice = vr::k_ulInvalidInputValueHandle;
{
	vr::EVRInputError eGetSourceError = vr::VRInput()->GetInputSourceHandle( "/user/hand/left", &hLeftHandDevice );
	if ( eGetSourceError != vr::VRInputError_None )
	{
		printf( "Error %s returned from GetInputSourceHandle\n", GetStringForVRInputError( eGetSourceError ) );
		return;
	}
}
		
std::vector<vr::VRActiveActionSet_t> vecActionSets;
vr::VRActiveActionSet_t set = { 0 };
set.ulActionSet = m_ulActionSet;
set.ulRestrictedToDevice = hLeftHandDevice;	// Restrict to left hand
vecActionSets.push_back( set );

vr::EVRInputError eUpdateActionStateError = vr::VRInput()->UpdateActionState( &vecActionSets[ 0 ], sizeof( vr::VRActiveActionSet_t ), (uint32_t)vecActionSets.size() );
if ( eUpdateActionStateError != vr::VRInputError_None )
{
	printf( "Error %s returned from UpdateActionState\n", GetStringForVRInputError( eUpdateActionStateError ) );
	return;
}

// Left Hand should have data available without errors
{
	vr::InputSkeletalActionData_t skeletalActionData;
	vr::EVRInputError eGetSkeletalActionError = vr::VRInput()->GetSkeletalActionData( m_ulActionSkeletonLeftHand, &skeletalActionData, sizeof( skeletalActionData ) );
	if ( eGetSkeletalActionError != vr::VRInputError_None )
	{
		printf( "Error %s returned from GetSkeletalActionData\n", GetStringForVRInputError( eGetSkeletalActionError ) );
		return;
	}

	if ( skeletalActionData.bActive )
	{
		vr::EVRInputError eBoneError = vr::VRInput()->GetBoneHierarchy( m_ulActionSkeletonLeftHand, m_boneParents, kHandBoneCount );
		if ( eBoneError != vr::VRInputError_None )
		{
			printf( "Error %s returned from GetBoneHierarchy\n", GetStringForVRInputError( eBoneError ) );
			return;
		}

		vr::EVRInputError eGetSkeletalBoneError = vr::VRInput()->GetSkeletalBoneData(
			m_ulActionSkeletonLeftHand,
			vr::EVRSkeletalTransformSpace::VRSkeletalTransformSpace_Model,
			vr::EVRSkeletalMotionRange::VRSkeletalMotionRange_WithController,
			m_leftHandTransforms,
			kHandBoneCount );

		if ( eGetSkeletalBoneError != vr::VRInputError_None )
		{
			printf( "Error %s returned from GetSkeletalBoneData\n", GetStringForVRInputError( eGetSkeletalBoneError ) );
			return;
		}
	}
}


// Right Hand should get filtered out by the device restriction
{
	vr::InputSkeletalActionData_t skeletalActionData;
	vr::EVRInputError eGetSkeletalActionError = vr::VRInput()->GetSkeletalActionData( m_ulActionSkeletonRightHand, &skeletalActionData, sizeof( skeletalActionData ) );
	if ( eGetSkeletalActionError != vr::VRInputError_None )
	{
		printf( "Error %s returned from GetSkeletalActionData\n", GetStringForVRInputError( eGetSkeletalActionError ) );
		return;
	}

	// This is false because of the device restriction
	if ( skeletalActionData.bActive )
	{
		vr::EVRInputError eBoneError = vr::VRInput()->GetBoneHierarchy( m_ulActionSkeletonRightHand, m_boneParents, kHandBoneCount );
		if ( eBoneError != vr::VRInputError_None )
		{
			printf( "Error %s returned from GetBoneHierarchy\n", GetStringForVRInputError( eBoneError ) );
			return;
		}

		vr::EVRInputError eGetSkeletalBoneError = vr::VRInput()->GetSkeletalBoneData(
			m_ulActionSkeletonRightHand,
			vr::EVRSkeletalTransformSpace::VRSkeletalTransformSpace_Model,
			vr::EVRSkeletalMotionRange::VRSkeletalMotionRange_WithController,
			m_rightHandTransforms,
			kHandBoneCount );

		if ( eGetSkeletalBoneError != vr::VRInputError_None )
		{
			printf( "Error %s returned from GetSkeletalBoneData\n", GetStringForVRInputError( eGetSkeletalBoneError ) );
			return;
		}
	}
}
```

**Comment by ascmt** [comment]
@joevdh  Just to be clear: You are saying that the originally posted use case *should* work despite the subsequently cited documented limitation posted by @dmorate ?

Fortunately I was able to work around this issue for my goals.  Unfortunately I do not have time to further experiment, but I can give you a summary of differences between your test code above and my original usage:

* I do not see the initialization of m_ulActionSkeletonLeftHand / m_ulActionSkeletonRightHand.  I init'd mine with "/actions/main/in/skeletonleft" and "/actions/main/in/skeletonright" matching my action manifest json.

* My sequence of API calls was:
0. Cache various handles at startup AFTER a controller is detected (Knuckles EV3s were my test device, in case that matters)
[Update loop]
1. UpdateActionState /user/hand/left
2. GetDigitalActionData /user/hand/left
3. UpdateActionState /user/hand/right
4. GetDigitalActionData /user/hand/right
5. GetSkeletalBoneData /actions/main/in/skeletonleft

#5 consistently returned VRInputError_NoData.  

Speculative idea: Did the UpdateActionState call in #3 for the right hand stomp the internal data I expected to be there from #1?  If restricting to one device path still causes destructive behavior to unrelated device path data in UpdateActionState(), that is counter-intuitive and would be good to at least document.

Feel free to close this issue whenever you want, it is unlikely I will be able to devote any more time to this as I already have a workaround for my purposes and deadlines.

**Comment by joevdh** [comment]
Yes, the most recent UpdateActionState sets the internal configuration for future calls to all the OpenVR APIs.  So after restricting the data to the right hand in #3, requesting the bone data for the left hand should not work.  Also, you should be calling GetSkeletalActionData between calls to UpdateActionState and any other skeletal input calls, so that you can first check that the action is active for the current call (see the parts of the sample code above with skeletalActionData.bActive).

**Comment by LaySoe** [comment]
I Like apps(google🇲🇲🇲🇲🇲🇲)
