### ISSUE TITLE
IVRSystem.EVRButtonId has duplicate values

### ISSUE THREAD

**Issue by carrotstien** [ValveSoftware/openvr#1151]
IVRSystem.EVRButtonId contains (among others):

k_EButton_Grip = 2,
k_EButton_Dashboard_Back = 2,
k_EButton_IndexController_A = 2

how would i differentiates between press A on the index controller, or pressing the Grip on the index controller. Am I misunderstanding something?

**Comment by JoeLudwig** [comment]
Dashboard_Back is meant to indicate the "back" action to overlay apps. It's not really a button.

Grip and A are, in fact, both bound to the same action for legacy applications (i.e. those that use the API you're referring to here.) To get support for all of the inputs and feature of the Index controller, you'll need to use the new input system. (Or if you just want one more button, you could use Axis2-4 and get the extra data out. Rebinding is pretty flexible, even for legacy apps.)

Regardless, the old input system is deprecated at this point, so we're not making any changes to that API or its associated constants.

**Comment by shuimujinghua** [comment]
where is the new input system?

**Comment by JoeLudwig** [comment]
https://github.com/ValveSoftware/openvr/wiki/SteamVR-Input
