### ISSUE TITLE
Is there a way to get OpenVR (SteamVR) version in runtime?

### ISSUE THREAD

**Issue by risa2000** [ValveSoftware/openvr#1158]
Whenever I start SteamVR the components (e.g. vrcompositor, vrserver, etc.) announce their version in the log, e.g.:
```
Sun Jul 21 2019 23:20:35.144 - vrcompositor.exe 1.5.16 startup with PID=14836, config=D:\Games\Steam\config, runtime=D:\Games\Steam\steamapps\common\SteamVR
```
or
```
Sun Jul 21 2019 23:20:32.667 - vrserver.exe 1.5.16 startup with PID=12308, config=D:\Games\Steam\config, runtime=D:\Games\Steam\steamapps\common\SteamVR
```
Here the version is `1.5.16` which corresponds also to what SteamVR shows on the window bar. But so far I have not found any way to access this version in the runtime. The only reference I found in the source code are C `#define`s, but this does not help me much.

Does anyone know if there is a way to get it? I would like to know for diagnostic purposes on which runtime my app is running.

**Comment by JoeLudwig** [comment]
There's not currently a way to return this. We can add it to the API, but would like to know what you intend to use it for?  Just diagnostics?

We don't release SDKs until after the new version is shipped out to everybody and we don't support old versions of SteamVR. So the answer from this API should always be either the current beta version or the current released version.

**Comment by risa2000** [comment]
I am writing an app which (among others) collects the properties (TrackedDeviceProperty) about basically anything which is connected and stores it as reference for comparisons. It is kind of measurement of the VR headset (and VR subsystem).

These properties may appear (or disappear) or change the value, either because SteamVR has added them, or because the device vendor started to support them, so in order to put some order in those random records, I was hoping to record also OpenVR version, so when (in the future) I would use those records for the reference, I would also know what I am comparing the new record to.

The other use I can see, that while I can record the SDK version at the build time (which is defined in the sources), having the runtime information as well, I could decide how much my "build" version diverges from the actual one, again just for the purpose of being able to say that my "measurement" is probably no longer relevant.

I guess that either way it is not really a must. I just was wondering if I missed something, or it is really not available. However, if you add it I would be happy.

**Comment by TheDeveloperGuy** [comment]
@risa2000 I expect it will be difficult to get this added, as Valve is not keen to support anything but the latest version, or have any app/driver change its behaviour based on particular OpenVR versions. Your use case is obviously "safe", but in general adding this could open the door for "bad behaviour". In any case, there is a 'version.txt' file in the SteamVR 'bin' folder that you could find and query programatically.

**Comment by JoeLudwig** [comment]
The 1.6.x SDK will include IVRSystem::GetRuntimeVersion().
