### ISSUE TITLE
glDebugMessageCallback and "const void *userParam" doesn't work on some systems

### ISSUE THREAD

**Issue by ChristophHaag** [ValveSoftware/openvr#116]
This is about this debug callback in the hellovr sample application: https://github.com/ValveSoftware/openvr/blob/01e9d9a99f9d2230854b960846be8056e6cd9f96/samples/hellovr_opengl/hellovr_opengl_main.cpp#L441

Relevant Link on Stackoverflow: http://stackoverflow.com/a/26419861

In the current version of glxext.h the function is defined as
`typedef void (APIENTRY  *GLDEBUGPROCARB)(GLenum source,GLenum type,GLuint id,GLenum severity,GLsizei length,const GLchar *message,const void *userParam);`
ant so the  works for me on Archlinux.

But there are apparently users on less recent systems where the `const void *userParam` parameter doesn't work and it produces this error: http://codepad.org/tMOcXdIn

**Comment by JoeLudwig** [comment]
This will be fixed in the next SDK update.
