### ISSUE TITLE
Missing information about driver profile inputs

### ISSUE THREAD

**Issue by SDraw** [ValveSoftware/openvr#1179]
- There is no information about input type 'pinch'. Is it made for virtual or real input? Is it possible to create and use this input type through OpenVR API? 
- What is 'capsense_source' property and how to use it?

**Comment by JoeLudwig** [comment]
Does that mean you figured it out?

Pinch is for a virtual input that combines two other inputs, one from capsense and one from a force sensor, into a thing that supports the "grab" mode. For Knuckles, these are the trigger and the trackpad. Unless your controller has a similar arrangement of two analog inputs, pinch probably won't do you much good.

**Comment by SDraw** [comment]
Thank you for better clarification.
