### ISSUE TITLE
Treadmill device mapping broken for legacy input games

### ISSUE THREAD

**Issue by joemarshall** [ValveSoftware/openvr#1182]
Treadmill devices don't seem to be able to map to legacy controller actions any more. This is mentioned in #1153 which talks about a fix for games using the new input system, which turned up in 1.7 beta, but as far as I can see this fix doesn't do anything to fix legacy input games?

Any idea when treadmill stuff in legacy games will be fixed?

**Comment by JoeLudwig** [comment]
We should stick with one bug for this issue. Please explain what you mean by "broken" over in #1153 

Is the "apply this to X hand" option not showing up for legacy actions in 1.7.x?
