### ISSUE TITLE
Request elbows and knees added to tracker_types

### ISSUE THREAD

**Issue by olsoneric** [ValveSoftware/openvr#1185]
When managing trackers from the devices menu, there are no options for elbows or knees.

Users will be confused when assigning a tracker for a knee because other types like keyboard or shoulder will have to be reused for left_knee and right_knee.

If adding these four entries is acceptable, it "should" be a trivial to add.  Ideally: 
 - Copy and make a one line change to `vive_tracker_left_shoulder_profile.json` into similar files for left_elbow, right_elbow, left_knee, and right_knee.
 - Add four lines in `vive_tracker_profile.json` for those files.

Thanks for considering

**Comment by JashanChittesh** [comment]
I just posted this same request to the SteamVR Unity Plugin repository ... but here is probably the better place. Link: https://github.com/ValveSoftware/steamvr_unity_plugin/issues/527

**Comment by 1runeberg** [comment]
@kisak-valve - am working on this, can you add me in as the assignee please :)

**Comment by 1runeberg** [comment]
fyi - this has been done, just some UI stuff happening in the background, but will hopefully bubble into beta by next week.

**Comment by 1runeberg** [comment]
This is added in the new beta:
https://steamcommunity.com/games/250820/announcements/detail/1705111889399665068

**Comment by JashanChittesh** [comment]
Very awesome! I have just added a PR to the SteamVR Unity Plugin that extends SteamVR_Input_Source accordingly: https://github.com/ValveSoftware/steamvr_unity_plugin/pull/645
