### ISSUE TITLE
Writing hmd pose driver:: I want help()!

### ISSUE THREAD

**Issue by AkayabeKimitsu** [ValveSoftware/openvr#1187]
Hello openvr users!
I've made driver for controllers 
and vive trackers emulating in the universe.
Driver works normally, poses, rots, 
everything works correctly.
Now, i'd like to override hmd position
and not rotation with my vive tracker.
Cannot do vrsettings trackingoverride cause
it override rotation too.

Soo...
I've added vrserver->trackedeviceposeupdated
or sth written like that, which use tracker's 
pose and override to hmd. But it aint work!
So i want your help to make everything
to work.

I call that function, using pose element returning pose from it. Like for controller,
but set id 0 like for hmd.
Everything with hmd pos is based on
Razer's hydra driver
and openvr-opentrack driver.

I can post driver codes etc. 
But if someone will interest in that.
Reddit post:
https://www.reddit.com/r/SteamVR/comments/cvmvrp/making_hmd_pose_driver_help/

And if someone know how to build
steamvr osvr driver, it would be nice,
cause cmake cannot find existing files with
path specified lol.

Anyway, hope some nice people help me.
Bye

**Comment by AkayabeKimitsu** [comment]
Hello people!

We're big step closer to get it to work! 

ᕙ(＠°▽°＠)ᕗ

I've found hook for ovrinputemulator:

https://github.com/naelstrof/VRPlayspaceMover

which is actually freakin' good. 😁

We can use k2vr to send head poses to

driver based on playspacemover.

୧(＾ 〰 ＾)୨

I'll post next updates and when done, 

I can post driver or setup here.

Anyway, other suprising ideas accepted!

I reccomend to post on reddit, anyway.

〜Bye! つ◕ ᴥ ◕つ

**Comment by JoeLudwig** [comment]
You should be aware that the technique used in OpenVR Input Emulator (and it sounds like VR Playspace Mover) is likely to cause crashes the next time the driver interface changes. It is inherently unsafe in the face of changes to the driver interface and will result in users going into safe mode. You shouldn't use it if at all possible.

**Comment by TheDeveloperGuy** [comment]
@JoeLudwig There is another way to alter HMD poses of a closed source driver?

**Comment by JoeLudwig** [comment]
No, there are only ways that end in tears.

It's something we're thinking about, though. These "hook drivers" are a major source of instability in SteamVR, but provide functionality that some people want.

**Comment by AkayabeKimitsu** [comment]
@JoeLudwig
So, anyway to write some driver?
It does not matter for me ifit would be instable. 
Or apply some offsets to hmd?
Idk, greg made that, but that ain't openSRC.
Any-way?

**Comment by TheDeveloperGuy** [comment]
@JoeLudwig What is the status of this?

https://github.com/ValveSoftware/openvr/wiki/TrackingOverrides

**Comment by AkayabeKimitsu** [comment]
Solved. Going to post driver later.
Sayoonara! (Bye xd)

**Comment by LaySoe** [comment]
Please. I watched the app

**Comment by dailafing** [comment]
I am here nearly 2 years later, because I would like to rotate the playspace programmatically in the openvr Driver i'm writing, for my own hardware.
I'm shocked that this functionality hasn't been added yet.
