### ISSUE TITLE
What I need to do to transform from the default portrait to landscape display in driver?

### ISSUE THREAD

**Issue by matrixcr** [ValveSoftware/openvr#119]
My custom driver need to deal with a landscape display. The openvr seems asumed portrait mode at default. Which APIs I should touch in the driver to do the transformation?

**Comment by JoeLudwig** [comment]
You're saying the hardware that you're using with your custom driver is defaulting to portrait? That seems like a problem with the EDID coming from that hardware rather than anything in OpenVR.

**Comment by matrixcr** [comment]
Yes, the hardware is defaulting to landscape. I guess many LED displays of mobile is in landscape mode by default. It's seems that OpenVR assumes portrait. Is there any chance I can tell OpenVR the orientation or transform the openvr render target textures from portrait to landscape orientation before they're scanned out?

**Comment by JoeLudwig** [comment]
OpenVR doesn't care about portrait vs. landscape. It just obeys what the driver tells it.

My suggestion would be to return the left eye on the top and the right eye on the bottom from GetEyeOutputViewport. Then rotate the views in the distortion function you return from ComputeDistortion. Everything else in the system should work fine after that.

If your display is sometimes landscape and sometimes portrait, just figure out which mode it's in at startup and return the appropriate stuff from those two functions.

**Comment by matrixcr** [comment]
Won't it introduce some distortion due to the different aspect ratio after rotate the views in ComputeDistortion?

**Comment by JoeLudwig** [comment]
As long as the aspect ratio of the viewports in the window (post-rotation) matches the aspect ratio in the recommended render target size there shouldn't be any extra scaling.
