### ISSUE TITLE
Issue with overlays (SteamVR 1.7.X)

### ISSUE THREAD

**Issue by sergioberg** [ValveSoftware/openvr#1191]
If the current VR application does not giving a stable framerate (For example No Man's Sky, 45 constant fps on reprojections) then there is glitch with practically every overlay... even with SteamVR's own overlays.

Video:
https://www.youtube.com/watch?v=ws46D655lFA

Example with screenshots:

frame 1:
Move the laser pointer down (or mouse pointer in the viewer)
![frame0](https://user-images.githubusercontent.com/12216723/64632201-15b20980-d412-11e9-989f-524c95557109.PNG)

frame 2:
Here is the issue, frame from the past
![frame1](https://user-images.githubusercontent.com/12216723/64632322-4abe5c00-d412-11e9-854a-5da81cda10d6.PNG)

frame 3:
![frame2](https://user-images.githubusercontent.com/12216723/64632375-6164b300-d412-11e9-840b-aa353b04dabb.PNG)

This issue occur with SteamVR 1.7.X only.

**Comment by aleiby** [comment]
Thanks!  This should be fixed in the next update.  I suspect you may still be able to make this happen with overlay_viewer open for the currently viewed overlay, but it should no longer happen during the normal operation of things.
