### ISSUE TITLE
SteamVR Keyboard: Backspace/delete doesn't work with Notepad; also breaks suggestions

### ISSUE THREAD

**Issue by JashanChittesh** [ValveSoftware/openvr#1195]
I ran into two issues with backspace/delete that are probably caused by the same bug, those both happened when making some notes in SteamVR Desktop, in the Windows Notepad application:

* Keyboard backspace does nnot wowork
* Keyboard Suggestions: type "wo", select "work", you get "wowork"

The "predictive suggestions" need to delete what was already typed of the word, which may actually be done but as the "deleting" doesn't work, it doesn't have an effect.

**Comment by kisak-valve** [comment]
Partial duplicate of https://github.com/ValveSoftware/VR-Community-Bugs/issues/218.

**Comment by JashanChittesh** [comment]
Yes, that is a duplicate. I have added the part about the suggestions as a comment there and will close this.
