### ISSUE TITLE
SteamVR 1.8.2 - Overlays attached to tracked devices are broken, rapidly re-positions

### ISSUE THREAD

**Issue by sergioberg** [ValveSoftware/openvr#1204]
https://steamcommunity.com/app/250820/discussions/3/1626286205686821786/

https://www.youtube.com/watch?v=0HuidvlZ2Dg

SteamVR 1.8.2 - Overlays attached to tracked devices are broken, rapidly re-position

**Comment by Zamundaaa** [comment]
Same issue here. The internal frame timing graph just flickers around and is practically unusable.

**Comment by OFWModz** [comment]
+1

**Comment by JoeLudwig** [comment]
This is fixed in the 1.8.3 beta update. Thanks for the report.

https://steamcommunity.com/games/250820/announcements/detail/1590257408671189167
