### ISSUE TITLE
Unable to load driver...error 103.

### ISSUE THREAD

**Issue by godbyk** [ValveSoftware/openvr#121]
I've built and installed an OpenVR driver and called `vrpathreg adddriver` on the path, but when I try to start SteamVR, it gives me an error 103 in the log file.

A snippet from `vrserver.txt`:
```
Fri May 20 2016 00:57:28.132 - Unable to load driver osvr from c:\osvr32\lib\openvr\osvr\bin\win32\driver_osvr.dll.
Fri May 20 2016 00:57:28.132 - Unable to load driver osvr because of error 103. Skipping.
```

Output from `vrpathreg`:
```
Runtime path = C:\Program Files (x86)\Steam\steamapps\common\SteamVR\
Config path = C:\Program Files (x86)\Steam\config
Log path = C:\Program Files (x86)\Steam\logs
External Drivers:
        c:\osvr32\lib\openvr\osvr
```

Directory listing:
```
> tree /f c:\osvr32\lib\openvr
Folder PATH listing for volume BOOTCAMP
Volume serial number is 20E4-7F19
C:\OSVR32\LIB\OPENVR
+---osvr
    +---bin
        +---win32
                driver_osvr.dll
                driver_osvr.lib
```

It looks like error 103 is `VRInitError_Init_FileNotFound`, but the driver libraries are where I think they should be.

Any ideas as to what could trigger this error or how I could further troubleshoot it?

Thanks!

**Comment by regoecuaycong** [comment]
wrong

**Comment by godbyk** [comment]
I figured it out. I had missed copying over a library dependency.

**Comment by JoeLudwig** [comment]
Windows is pretty annoying in that case. Glad you found it.

**Comment by moisesquintero** [comment]
Hey godbyk, what was the libary dependency that you were missing because I made a driver but my vrserver is indicating that the file does not exist with error code 103.

**Comment by godbyk** [comment]
@moisesquintero For SteamVR-OSVR, we use a few different libraries (e.g., `osvrClient.dll`, `osvrRenderManager.dll`). I used [Dependency Walker](http://www.dependencywalker.com/) to track down the missing library.

**Comment by moisesquintero** [comment]
Yes I have used Dependency Walker and it seems no dependencies are missing. But still the issue persists.

**Comment by godbyk** [comment]
@moisesquintero In that case, you might double-check that the folder name matches the suffix of the driver DLL filename. There may be other cases in which that error is thrown, but I'm not aware of them.

**Comment by moisesquintero** [comment]
Thanks, I found the issue with the dependency walker as a wrong 64 bit version was being used instead of 32 bit.

**Comment by godbyk** [comment]
@moisesquintero Ah, yes. I've been there, too. :)

**Comment by moisesquintero** [comment]
Hi godbyk  user, I have been trying to change the orientation of my headset with openvr, do you know a way to override the orientation of the headset while its still active. Keep in mind that the headset is not a tracked device.

**Comment by godbyk** [comment]
@moisesquintero Just call [`TrackedDevicePoseUpdated()`](https://github.com/ValveSoftware/openvr/blob/master/headers/openvr_driver.h#L2271) with whatever pose you'd like.

**Comment by moisesquintero** [comment]
Yes the function TrackedDevicePoseUpdated works only for virtual drivers and not for cases in which lets sat you have an oculus headset, then the function does not work for that device.

**Comment by godbyk** [comment]
@moisesquintero I'm afraid I don't understand what you're trying to do. Sorry.

**Comment by moisesquintero** [comment]
I am trying to use left and right arrow keys from the keyboard to be able to look left or right in the vr as opposed to having to rotate the headset to be able to look to other places.

**Comment by walrus** [comment]
@moisesquintero would you mind explaining what you mean by 'a wrong 64-bit version was being used'? I appear to be having a similar issue, only all of my dependencies *appear* to be 64-bit, as is the DLL.
