### ISSUE TITLE
Bug: Instead of Vive controllers, Steam Controller began to appear.

### ISSUE THREAD

**Issue by r57zone** [ValveSoftware/openvr#1210]
![](https://user-images.githubusercontent.com/9499881/65384922-44e14880-dd39-11e9-891d-270e310190b2.PNG)
After the SteamVR updates, instead of the Vive Controller, Steam Controllers began to appear, and the buttons also stopped working.
Have the controller names changed? I used to use [these](https://github.com/TrueOpenVR/SteamVR-TrueOpenVR/blob/master/OpenVR/samples/driver_sample/driver_sample.cpp#L555-L563). 
In older versions everything was ok - https://youtu.be/HWtdCc_f4ww?t=831

**Comment by JoeLudwig** [comment]
The names didn't change, and this is all working fine in normal SteamVR. I would suggest you file a bug with TrueOpenVR, but it looks like that's you. Maybe there's some other bug in all the wrapping you're doing? 

If you're doing any wrapping of driver_lighthouse.dll, that's not supported. API changes in the driver interface can easily break things. Things may remain broken until the next SDK update.

**Comment by r57zone** [comment]
driver_lighthouse.dll is not used. In SteamVR 1.3.22 <= it worked, but then it stopped, due to the SteamVR update. 
New headers did not help.

**Comment by JoeLudwig** [comment]
If driver_lighthouse isn't used, how did you ever have support for Vive controllers?

There have been lots of SteamVR updates since 1.3.22, some of which changed interfaces, albeit in ways that were intended to be backward compatible.  You will probably need to do some more digging on your side to narrow this down.

**Comment by r57zone** [comment]
A class controller driver of was added to "driver_sample", in Activate they are set to property "vive controllers". This implementation of many drivers on github.

**Comment by JoeLudwig** [comment]
So you're saying that this isn't actually a Vive controller, it's just trying to look like one?

If you call and get Prop_RenderModelName_String from the app side, do you get "vr_controller_vive_1_5"?

**Comment by r57zone** [comment]
Yes, these are different devices that pretend to be a vive controller. For example, Razer Hydra, PlayStation Move's or even just Arduino controllers.

Yes, this parameter is set to [this value](https://github.com/TrueOpenVR/SteamVR-TrueOpenVR/blob/master/OpenVR/samples/driver_sample/driver_sample.cpp#L560).

**Comment by r57zone** [comment]
Other drivers seem to be broken too. Razer Hydra stopped working in some games, on a different driver. Cool standard.

**Comment by r57zone** [comment]
@bjj Hi, do you happen to know what the problem may be?

**Comment by r57zone** [comment]
Bug was in the auto-detection of controllers depending on the assigned buttons, very strange behavior.
