### ISSUE TITLE
Use Vive tracker from inside OpenVR driver

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#1211]
I want to use a Vive tracker for HMD tracking in my own headset driver. I don't see any way of doing that apart from writing a "hook" driver (which we all know is "bad m'kay"), capturing the poses from the tracker and then passing them on to my own driver. Simple redirection is not going to work (if there is even such a thing in OpenVR), as I need to change the orientation and position origin to match how it's mounted on the HMD.

Is there a way to do this, or do I just start writing the "hook" driver already?

**Comment by spayne** [comment]
Would IVRServerDriverHost::GetRawTrackedDevicePoses work for you?

**Comment by TheDeveloperGuy** [comment]
Thanks, that's a good suggestion. However, there's a bigger issue, which may need a "hook" driver to fix, in that the tracker is listed in SteamVR as a "generic" controller. It would need to not show up at all in SteamVR, becoming part of the HMD driver. 

I guess it would be possible to  disable the tracker driver in SteamVR (thereby disabling all trackers, even if others were being used for other purposes), and read the HID data from the USB device, but that is a lot more work.

**Comment by TheDeveloperGuy** [comment]
I've written the "hook" driver, it seems to be the only way to go until Valve adds some way to do this kind of thing without hooking. It turns the tracker into a base station (as far as SteamVR is concerned) and steals its pose updates.

**Comment by TheDeveloperGuy** [comment]
@JoeLudwig This seems to work fine, but IIRC you said something about hooking the "lighthouse" driver.

**Comment by TheDeveloperGuy** [comment]
Simple hook driver (for IVRServerDriverHost) to change the driver role was all that was needed. Hooking methods in the "Lighthouse" driver is doomed to failure, as there are too many different types of driver interfaces using that driver, and hooking inevitably breaks it.

**Comment by risa2000** [comment]
> Simple hook driver (for IVRServerDriverHost) to change the driver role was all that was needed.

@TheDeveloperGuy are you saying that you finally found a solution, or that it would have been a solution, had you found it?

I am currently experimenting with something similar (using tracker to track a headset) and the only way I found so far was wrapping lighthouse driver inside my driver and changing the device class on the fly.

**Comment by TheDeveloperGuy** [comment]
> > Simple hook driver (for IVRServerDriverHost) to change the driver role was all that was needed.
> 
> @TheDeveloperGuy are you saying that you finally found a solution, or that it would have been a solution, had you found it?
> 

I change the driver role for the tracker to tracking reference and snoop on the pose updates. Apart from changing the role of a specific device instance (ie. not all trackers), I don't alter the behaviour or loading of the lighthouse driver in any way. 

There's probably a better and easier way through bindings or somesuch, but I haven't had a chance to experiment with that.

**Comment by risa2000** [comment]
> I change the driver role for the tracker to tracking reference and snoop on the pose updates.

I am afraid, I got stuck right on the first sentence :). I would assume the Vive tracker would be picked up by lighthouse driver automatically, and I am not sure how one can change the "driver role" (I assume you mean `device class`), before it is registered by the driver (except by rewriting the tracker config directly in the tracker).

Even with changed role/class how do you "snoop" on the updates? By using `IVRServerDriverHost::GetRawTrackedDevicePoses` as proposed by @spayne above? If yes, how it would be different from not changing the device's class?

**Comment by TheDeveloperGuy** [comment]
> I've written the "hook" driver, it seems to be the only way to go until Valve adds some way to do this kind of thing without hooking. It turns the tracker into a base station (as far as SteamVR is concerned) and steals its pose updates.

Yes, device class. You need to write a hook driver for this kind of thing. It's very bad and shouldn't be encouraged, because if you don't get everything exactly right it will crash the Lighthouse driver and SteamVR, and no one will like you very much ;)
