### ISSUE TITLE
Pinky and Ring fingers bend when hand rotates, how can I disable this?

### ISSUE THREAD

**Issue by guiglass** [ValveSoftware/openvr#1216]
I just downloaded the steamvr_unity_plugin and can clearly see that whenever I roll my hand over the skeleton's fingers appear to move strangely, I think it is intentional but I need to disable this:

This is causing major misalignment with my project, and I have found no way to disable it:
https://youtu.be/2nBFGUcjIsI

Even in the Steam example you can clearly see that the bending causes undesireable effects, where the Alien floppy hand bends unexpectedly when flipped over:
https://youtu.be/VYil9uY7kds

And I am doing something very similar to the Alien Floppy hands in my game, this is why I have to find some kind of solution to this!!

I see no mention of anything useful in SteamVR_Action_Skeleton or SteamVR_Behaviour_Skeleton. I have no clue where to look next. Who should I ask? Where is this bending even coming from??

Please can some help me figure out a way to disable this?

**Comment by kisak-valve** [comment]
Closing in favor of https://github.com/ValveSoftware/steamvr_unity_plugin/issues/554.
