### ISSUE TITLE
HMD not tracking when make a build with Unity

### ISSUE THREAD

**Issue by dpggit** [ValveSoftware/openvr#1219]
In Unity 2018.3 editor hmd works fine but once i make a build HMD doesnt move at all

**Comment by peroht** [comment]
Did you build the correct scene?

**Comment by dpggit** [comment]
I am using 2019.2.11 and now works, dont know if was cause the Unity update

**Comment by peroht** [comment]
Thats great it works. Feel free to close this issue if is resolved.
