### ISSUE TITLE
OpenVR not updated

### ISSUE THREAD

**Issue by dzleon** [ValveSoftware/openvr#122]
I've been tracking down problems with the OSVR_Vive plugin failing to load. It is trying to load the Steamvr driver_lighthouse.dll and request a ServerTrackedDeviceProvider using the SDK, which requests a IServerTrackedDeviceProvider_002 interface. The lighthouse driver was compiled with the IServerTrackedDeviceProvider_003 interface which doesn't exist yet in this repository.

The openvr_api.dll included in the SteamVR beta is newer than the one in this repository, how far behind is this repo supposed to be behind development?

**Comment by JoeLudwig** [comment]
Loading one of the bundled drivers without using the rest of the system is not supported. The Lighthouse, Oculus, and Null drivers compile from the same headers as the rest of the system so they will often use a newer interface that is not yet available in the SDK. That means they're potentially going to break your driver without notice and it may be a month or more until the matching SDK ships.

The versioning guarantee we make for drivers is that old driver binaries work with new builds of SteamVR. If you have a driver binary from a published SDK 0.9.20 or newer that driver can be loaded by vrserver and that will continue to be the case.
