### ISSUE TITLE
Memory leak in VR_InitInternal2

### ISSUE THREAD

**Issue by risa2000** [ValveSoftware/openvr#1221]
@mann1x here (https://github.com/cmbruns/pyopenvr/issues/71) pointed out that he observed a memory leak when repeatedly calling OpenVR init function.

I was able to reproduce it in the native code:
```c++
#include <iostream>

#define OPENVR_BUILD_STATIC
#include <openvr/openvr.h>

//  Initialize OpenVR subsystem and return IVRSystem interace.
vr::IVRSystem* init_vrsys(vr::EVRApplicationType app_type)
{
    vr::EVRInitError eError = vr::VRInitError_None;
    vr::IVRSystem* vrsys = vr::VR_Init(&eError, app_type);

    if (eError != vr::VRInitError_None) {
        std::cerr << vr::VR_GetVRInitErrorAsEnglishDescription(eError) << '\n';
        return nullptr;
    }
    return vrsys;
}

int main(int argc, char* argv[])
{

    while(true) {
        // Initializing OpenVR runtime (IVRSystem)
        auto vrsys = init_vrsys(vr::VRApplication_Background);
        if (nullptr != vrsys) {
            break;
        }
    }

    vr::VR_Shutdown();
    return 0;
}
```
When running this code without starting SteamVR, the `VR_Init` call fails with an error `Not starting vrserver for background app (121)`. Each failure seem to leak ~ 100KB on the stack in function `VR_InitInternal2` as illustrated on the picture below.

![openvr_init_mem_leak](https://user-images.githubusercontent.com/1336835/67326386-c255cf80-f516-11e9-9ebb-7c282e843da6.png)

This apparently becomes a problem when someone repeatedly calls `VR_Init` in an attempt to detect whether SteamVR has started.

The issue is observed on the stable 1.7.15 and the latest beta as well.

**Comment by kisak-valve** [comment]
Hello @risa2000, this issue is already being tracked at #195. Closing as a duplicate.

**Comment by risa2000** [comment]
@kisak-valve Thanks for letting me know, it is funny how the reports look similar even though I was not aware of the former.
Anyway, do you plan to fix? Why has it been open for so long?
