### ISSUE TITLE
SteamVR Input / Actions - GetStateDown & GetStateUp not working ( Unity C# )

### ISSUE THREAD

**Issue by AtomicOtaku** [ValveSoftware/openvr#1222]
Hi,

I've been working on a project since May and since then I've had no issues, but suddenly as of a bit less than a month ago I haven't been able to use GetStateDown for Vive controller input anymore. I hadn't changed my scripts at all, it just stopped working. Since then I've messed around with it and found that GetState still works (returns true every frame and I don't want this) but GetStateDown and GetStateUp are both broken.

I've checked the SteamVR Input Live View in Unity and my actions are indeed changing from False to True when I press the desired controller button, but for some reason that's as far as it goes. Despite changing from False to True it doesn't seem like it triggers the function call.

if (placeStep.GetStateDown(SteamVR_Input_Sources.RightHand)) // doesn't work
if (placeStep.GetStateUp(SteamVR_Input_Sources.RightHand)) // doesn't work
if (placeStep.GetState(SteamVR_Input_Sources.RightHand)) // works but not what I want

I've tried other workarounds of different ways to code this such as booleanAction.stateDown and AddOnStateDownListener() but these didn't work either. I'm currently at a loss. I've tried pretty much everything short of making my own StateDown function using the currently working GetState, but I'd rather not do such a temporary fix when I'd hope this could get fixed at some point.

I'd appreciate any help or ideas because I've hit a wall and haven't been able to use this for weeks now. Thanks!

**Comment by dpggit** [comment]
Amazing i was about to post the same issue, updated to the new htc vive input utility and made may actions GetStateDown & GetStateUp not work anymore and destroyed the bindings
I really hate the new action system, i had so many problems that i cant count them, losing many days of work just trying to solve all this, everytime i update something related with this NEVER WORKS

**Comment by dpggit** [comment]
Try to remove HTC VIVE INPUT if you have it, tried removing it now and GetStateDown & GetStateUp worked again

**Comment by chengnay** [comment]
Using latest SteamVR Plugin (v2.4.5), GetStateDown and GetStateUp is not working. No Vive Input Utility  imported.

**Comment by AtomicOtaku** [comment]
> Try to remove HTC VIVE INPUT UTILITY if you have it, tried removing it now and GetStateDown & GetStateUp worked again

I'd hope I don't have to go down that path. I don't really know what's all packaged in there but it seems fairly essential? Unless it's a very specific part of that folder that you mean. I wouldn't want to remove my ViveCameraRig object and all that's contained under it. Hopefully now that this is gaining some traction it'll see a fix soon, at least.

**Comment by chengnay** [comment]
@AtomicOtaku Please update your VIU from [GitHub](https://github.com/ViveSoftware/ViveInputUtility-Unity), it fixes the GetStateUp and GetStateDown not working issue.

**Comment by AtomicOtaku** [comment]
@chengnay Thank you very much! Downloaded it and after importing and fixing up a couple things it works perfectly. So glad it's fixed.
