### ISSUE TITLE
Dashboard Overlays no longer apply Transforms

### ISSUE THREAD

**Issue by elvissteinjr** [ValveSoftware/openvr#1224]
Unfortunately I've not been paying attention to this recently, so I can't pinpoint the version. It certainly is broken in SteamVR 1.8.16 beta and works in 1.7.15 stable, however.

Calls to VROverlay::SetOverlayTransformAbsolute() do not seem to do anything on dashboard overlays in the current beta version. It does work for normal floating overlays.
This is not intentional, is it?

**Comment by JoeLudwig** [comment]
Dashboard overlays are positioned by the dashboard itself, but no longer use the transform field to accomplish that.

What are you doing with transforms on dashboard overlays? Wouldn't they just be overridden by the dashboard the next time it's summoned (or the next time the user changes tabs?)

**Comment by elvissteinjr** [comment]
I'm writing a desktop mirror overlay with a separate UI overlay that goes below (and slightly in the front) the dashboard one.  I was hoping to lift the dashboard overlay a up a bit without doing any spacing on the overlay texture itself. Additionally also to give the user the option to freely position it relative to the dashboard, though the usefulness of that is debatable.
I suppose I could also use an empty dummy dashboard overlay and have the main mirror one floating as well if necessary. But I'd prefer not having to do that.

While the transform does reset, I don't see the issue with just re-applying the offset when needed. I think in past experiments that move was visible to the user when done on VREvent_OverlayShown, but a bit of trickery on the overlay application's end should be able to hide that (an event to react before it's displayed would be ideal, but messing with overlay alpha should give the desired effect too, even if a bit hacky).

While not relevant to myself, this also breaks the Desktop Overlay translation options in OpenVR-Advanced-Settings. Though I'm not sure if messing with Steam's desktop overlay counts as legitimate use-case there.

**Comment by guygodin** [comment]
I have the same issue. In the Virtual Desktop Dashboard, the desktop is now a meter higher than it was before and the call to SetOverlayTransformAbsolute no longer adjusts the position

**Comment by JoeLudwig** [comment]
Setting the transform on dashboard overlays is no longer supported. In a 1.9 build in the next couple weeks those calls will start returning an error instead of just silently failing to do what they used to.

We hope to offer some of this flexibility (and probably much more) again down the road, but for now this just isn't an option.

**Comment by guygodin** [comment]
Ok, how do I set the height of my overlay then? It seems to only support a width and assumes a square texture. Thanks

**Comment by JoeLudwig** [comment]
Set mouse scale to your width and height in pixels. And submit a texture with a matching width and height.

Is that not working? It certainly used to.

**Comment by JoeLudwig** [comment]
Note that if you weren't setting mouse scale before, the laser mouse events you get now will be in pixels instead of UVs so you'll likely have to remove a multiple somewhere else.

**Comment by guygodin** [comment]
Got it, thanks. The mouse scale did the trick
