### ISSUE TITLE
VR_GetRuntimePath missed in openvr_api.cs

### ISSUE THREAD

**Issue by sergioberg** [ValveSoftware/openvr#1225]
**VR_GetRuntimePath missed in openvr_api.cs**
VR_INTERFACE bool VR_GetRuntimePath( VR_OUT_STRING() char *pchPathBuffer, uint32_t unBufferSize, uint32_t *punRequiredBufferSize );

**old RuntimePath is not works and lead to crash.**
	[DllImportAttribute("openvr_api", EntryPoint = "VR_RuntimePath", CallingConvention = CallingConvention.Cdecl)]
	internal static extern string RuntimePath();

openvr_api.cs & openvr_api.dll - 1.7.15

**Comment by zite** [comment]
Thanks for the report! This should be fixed in the 1.8.19 release https://github.com/ValveSoftware/openvr/releases
