### ISSUE TITLE
Get/SetOverlayCurvature don't seem to make any visible changes

### ISSUE THREAD

**Issue by CircuitLord** [ValveSoftware/openvr#1235]
I was over the moon when I saw they re-added overlay curving support. However, after testing it out it doesn't seem to actually do anything.

I hooked it all up into my existing overlay software, and SetOverlayCurvature seemingly sets the value, and doesn't give any errors, as well as GetOverlayCurvature returning whatever value I set on the overlay. I've tried all sorts of values, 0-1 like it says, and random numbers like 100 just to see if I could get it to make any visible change, to no avail, my overlays are still flat as pancakes.

Has anyone else got this working yet, am I just missing something super obvious? The only docs I can find are the 2 sentences in the header file :/

Thanks!

**Comment by kpbg** [comment]
Same here

**Comment by elvissteinjr** [comment]
The newest SteamVR Beta curves the entire dashboard, so I'd assume the needed functionality is in the code now. The functions continue to not do anything, however. GetOverlayCurvature() also returns 0 if called on one of the curved overlays of the dashboard.
Hope it can be sorted out now.

And please don't restrict this to dashboard overlays or something, I need this for a normal one.

**Comment by JoeLudwig** [comment]
This beta includes a fix for curvature in the API not doing anything: https://steamcommunity.com/games/250820/announcements/detail/1705111889403213561

It's never going to work in 1.9.x, so you should avoid shipping anything that depends on curvature until 1.10.x is the default build for everyone.
