### ISSUE TITLE
Overlay limit/functionality is too low for a cockpit overlay

### ISSUE THREAD

**Issue by dantman** [ValveSoftware/openvr#1238]
When using my Elite Dangerous cockpit overlay ([Elite VR Cockpit](https://github.com/dantman/elite-vr-cockpit)) it's pretty easy to end up getting the `OverlayLimitExceeded` error from SteamVR.

Fundamentally this is because each system function button needs to be a separate overlay (because they are freely placed by the user on many different planes), there are a large number of ship functions the user may place a button for, and other controls and bits of UI require their own overlays.

I do try to limit the overlays where I can, e.g. I managed to make the "Escape / Edit mode / Menu mode / [Main Ship / Fighter / SRV / Map]" button set use a single overlay instead of 3-7 overlays. However there is a finite and small number of reductions I can make this way. If I implement every idea I can think of to reduce the overlay count, I can only reduce it by 5. Meanwhile I have other feature ideas that will require more overlays.

As a result with about 17 or more ship function buttons I use, 3-4 for flight controls, 4 for hands, 1-4 more for key UI I personally start rubbing up against the edges of the limit. Running my overlay alongside TurnSignal, OpenVR Advanced Settings, and whatever overlays SteamVR uses on its own I can end up triggering the `OverlayLimitExceeded` error (say nothing about also wanting to run OVRDrop). I end up having to hard quit those other overlays in order to run my own.

I can't tell you exactly how many overlays each program uses and what the counts I get in different circumstances are; since OpenVR uses a random ulong for overlay handles and doesn't provide a function to list overlays or even a debug view to show you what overlays (by key, name) are registered.

----

In theory I have the capability to render a single 3d overlay from the HMD perspective leveraging a Unity camera to render all the buttons, controls, etc... to a stereoscopic texture with a depth map; instead of creating a separate OpenVR overlay for every button, control, etc... that needs a separate plane in 3d space. However the OpenVR Overlay API does not allow me to do so.

So barring that type of functionality, the OpenVR overlay limit really needs to be raised another factor or two.

**Comment by BOLL7708** [comment]
Just as a side note, you say there is no list of overlays which might be true about the OpenVR APIs (I haven't checked), but at least there is a tool in SteamVR that provides handles, names, and a plethora of other properties, the Overlay Viewer. 😮
![image](https://user-images.githubusercontent.com/12276837/68552735-aa3ce600-041a-11ea-98aa-36de1d7d58b4.png)
For anyone who doesn't know, it's available from the SteamVR status window > Developer > Overlay Viewer.

**Comment by dantman** [comment]
> Just as a side note, you say there is no list of overlays which might be true about the OpenVR APIs (I haven't checked), but at least there is a tool in SteamVR that provides handles, names, and a plethora of other properties, the Overlay Viewer. 😮

Yay, there actually is a way to inspect the overlay list. Boo, it doesn't look like they tested it on a 4K TV with UI scaling, cause the table items are squashed and hard to read.

**Comment by dantman** [comment]
Ok, so. Perfectly reasonable setup sitting in an ED cockpit with my overlay.
- 1x OpenVR Camera PIP overlay
- 4x OpenVR Advanced Settings overlays
- 20x system_ overlays
- 3x TurnSignal overlays
- 4x Valve Steam overlays
- Elite VR Cockpit overlays (28):
  - 2x controller overlays
  - 2x tooltip overlays (ephemeral)
  - 1x Ship joystick representation
  - 2x Ship throttle representation
  - 2x 6DOF controller interface (semi-ephemeral)
  - 1x Meta panel (Escape, Edit mode, Menu mode)
  - 1x Error message warning me ED is not focused and controls will not function
  - 17x Ship function buttons

Total: 60

And of course if I turn on edit mode to change the cockpit layout:
- The 6DOF controller becomes non-ephemeral
- 2x Edit mode panel overlay

And if I want to turn on OVRdrop, that's another 5.

So yeah, I can see how I'm rubbing up against the overlay limit. Even when I'm courteous enough to destroy my overlays when they aren't visible instead of reserving an overlay for every button the user has in their settings (in which case my ship function buttons would be 2+13+2+9=26 and there would be 4 more for the map controls meaning I'd have at least 41 overlays reserved, subject to other controls that would add more overlays).

But of course this is my personal cockpit setup. If someone wanted to use targeting buttons (1-10), buttons to fire chaff/heatsinks/shield cells/ecm, toggle rotation correction/orbit lines they would have even more overlays.

----

Given that Valve themselves alone take up 25 overlays by default. I can't believe they expect the entire community of every overlay you may ever want built for SteamVR to make due with only 39 available overlay slots to be shared by every single overlay developer in the world.

**Comment by JoeLudwig** [comment]
I'll increase the limit in 1.9. (Probably just by doubling it to 128.)

**Comment by JoeLudwig** [comment]
Ok, this number is 128 in 1.9.1 for sure, so I'm closing the bug.

**Comment by dantman** [comment]
> I'll increase the limit in 1.9. (Probably just by doubling it to 128.)

Thanks. There are still other reasons being able to create a 3d overlay instead would be better for my overlay. But this will at least give me more breathing room and let me use my overlay without needing to quit others.
