### ISSUE TITLE
HelloVR example doesn't build

### ISSUE THREAD

**Issue by thezenmaster** [ValveSoftware/openvr#124]
It appears LoadRenderModel and LoadTexture functions are renamed to LoadRenderModel_Async and LoadTexture_Async in the OpenVR library, but the Hello VR example is not updated accordingly. After adding the _Async part the project builds and runs fine.

Just update the 2 functions in the example. Thank you!

**Comment by JoeLudwig** [comment]
This will be fixed in the next SDK release.

**Comment by thezenmaster** [comment]
Great, thanks!
