### ISSUE TITLE
SteamVR doesn't destroy dashboard overlays [SteamVR 1.9.3]

### ISSUE THREAD

**Issue by sergioberg** [ValveSoftware/openvr#1245]
SteamVR doesn't destroy dashboard overlays with SteamVR 1.9.3
Regardless of whether the overlay application calls the 
[c#] public EVROverlayError DestroyOverlay(ulong ulOverlayHandle)
 or not on exit, SteamVR does not destroy it. Re-launching the overlay application makes it impossible to use this overlay (if not restarting SteamVR).
This problem takes place only with dashboard overlays.

**Comment by sergioberg** [comment]
The issue still occur with SteamVR Beta 1.9.4

**Comment by JoeLudwig** [comment]
This is fixed in main and will be fixed in a future 1.9 build. Keep an eye on the release notes.
