### ISSUE TITLE
Manage Trackers UI show trackers as being disconnected

### ISSUE THREAD

**Issue by peroht** [ValveSoftware/openvr#1251]
As the title says, the UI displays the trackers as being Disconnected. The power action works successfully. 

![2019-11-22 Vive trackers](https://user-images.githubusercontent.com/14336296/69425272-edf0f300-0d2a-11ea-89c9-58a255655fb9.png)

(Changing their role successfully update their abilities and show button presses in device settings).

**Comment by JoeLudwig** [comment]
Thanks for the report. This is fixed in a future version of SteamVR 1.9.
