### ISSUE TITLE
[Driver] How to deactivate controller

### ISSUE THREAD

**Issue by Mvivant** [ValveSoftware/openvr#1259]
Hello,

I create a driver for OpenVR for tracked device, when I plug my controller (connection) I call the function vr::VRServerDriverHost()->TrackedDeviceAdded.
But when I unplug my controller (disconnection) I don't know how to deactivate my vr::ITrackedDeviceServerDriver and remove it.

Is it possible ?

Thanks!

**Comment by LaySoe** [comment]
Thankfully

**Comment by TheDeveloperGuy** [comment]
AFAIK you can't. Just send pose(s) with poseIsValid and deviceIsConnected set to false and let SteamVR worry about it.

**Comment by Mvivant** [comment]
Hello,

Thanks, it works.

Now I want to change the icon for my controller, for example blink, alert, searching, so I change the pose.result but nothing change.

What is the function to call for change the status of my controller ?

**Comment by TheDeveloperGuy** [comment]
@Mvivant Treat the openvr_driver.h file as the most documentation you're going to get on SteamVR behaviour and try to find answers there. From a text search (for "searching") in that file, it appears the answer is to send a state event with the required state.

**Comment by Mvivant** [comment]
Thanks but how send event ? what is the function ?

**Comment by TheDeveloperGuy** [comment]
I've taught you how to fish, now go fish...

**Comment by TheDeveloperGuy** [comment]
If you get completely stuck, and you catch me in a moment when I'm on here, I'll try to help you, but I don't work for Valve and I'm very busy, so it's best (as you've probably figured out already) to start learning how to help yourself, as this is actually a "issue reporting forum" and not a general assist forum, so you won't get answers from Valve employees unless you show them you've done all you can do to find the answer yourself. You may be better off with one of the "community" forums, eg.:

https://steamcommunity.com/app/358720/discussions/0/

**Comment by TheDeveloperGuy** [comment]
As I'm here I'll leave an example of the event for IPD change notification. You should be able to figure out how to send the event you need from that:

```
VREvent_Ipd_t data = { m_flIPD };
vr::VRServerDriverHost()->VendorSpecificEvent(m_unObjectId, vr::VREvent_IpdChanged, (VREvent_Data_t&)data, 0);

```
