### ISSUE TITLE
BUG: XBox gamepad support is completely broken in current (v1.8.x) and beta (v1.9.x) SteamVR dashboard

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#1265]
It's possible to bring up the SteamVR dashboard using the gamepad, but that's it. Not possible to close it or do anything else once it is open. Dashboard is obviously not reading the gamepad at all. Seems to be related to removal of gamepad related dashboard APIs in v1.8.19 SDK. 

Does anyone even test this stuff before releasing? Gamepad support is used by a lot of SteamVR users, so priority needs to be given to ensuring it works before releasing a new version of SteamVR.

**Comment by JoeLudwig** [comment]
Do you have custom bindings for your HMD or for the gamepad? When you bring up the dashboard with the gamepad it should use face mouse, and then let you click the trigger on the gamepad to left click.

**Comment by TheDeveloperGuy** [comment]
No custom bindings for HMD or gamepad. Nothing works at all with gamepad (XBox) when dashboard is up, and there's no way to close it. I suspect this hasn't even had rudimentary testing, as no button (apart from holding down "back" button to bring up dashboard) does anything at all.

**Comment by JoeLudwig** [comment]
Can you post a system report so I can see what's different between your machine where it doesn't work and mine where it does?

**Comment by TheDeveloperGuy** [comment]
Attached, thanks. Getting this complaint from a lot of users, so it's probably not something specific to my machine. 

[SteamVR-2019-12-10-PM_07_18_00.txt](https://github.com/ValveSoftware/openvr/files/3946262/SteamVR-2019-12-10-PM_07_18_00.txt)

**Comment by TheDeveloperGuy** [comment]
Can confirm this is still broken in latest SteamVR, on every machine I've tested it on. @JoeLudwig maybe it's going to give better results if you compare your machine (the only one it's been tested successfully on?!) with a clean SteamVR installation? It appears your machine has something non-standard which makes this work.

**Comment by JoeLudwig** [comment]
I think I see the problem. If the laser mouse pose isn't bound on the HMD, it can't function as the laser mouse and the clicks on the gamepad can't do anything.

I'll fix that in the generic_hmd binding file you're using by default right now. You can fix this for your users by adding an input profile for your HMD devices, and then setting that input profile to point to a compositor binding file that has the pose action in the lasermouse action set bound.  (You, or your users, can fix it for yourself by binding that action in the UI, but that would be a local change.)

The fix on our end will ship in the 1.10.x beta, which is likely going to start the first week of January.

**Comment by TheDeveloperGuy** [comment]
Thanks, I'll test and close this if everything works with that change.

**Comment by JoeLudwig** [comment]
This is the vrcompositor_bindings_generic_hmd.json that will be in 1.10 in case you want to clone it to get a fix into iVRy sooner: 
```
{
   "action_manifest_version" : 0,
   "alias_info" : {},
   "app_key" : "openvr.component.vrcompositor",
   "bindings" : {
      "/actions/lasermouse" : {
         "poses" : [
            {
               "output" : "/actions/lasermouse/in/pointer",
               "path" : "/user/head/pose/raw"
            }
         ],
         "sources" : [
         ]
      }
   },
   "category" : "steamvr_input",
   "controller_type" : "generic_hmd",
   "description" : "",
   "name" : "Default SteamVR Dashboard bindings for Generic HMDs",
   "options" : {},
   "simulated_actions" : []
}

```

**Comment by TheDeveloperGuy** [comment]
Thanks, made a custom input profile using this and it seems to work. Looking briefly at the other HMD input profiles, it looks as if only Index would work with gamepads in current SteamVR.
