### ISSUE TITLE
Driver Role for controller 

### ISSUE THREAD

**Issue by Mvivant** [ValveSoftware/openvr#1266]
Hello,

I want to create a driver for a new locomotion controller that works with the left and right controller (htc, oculus or WMR) in the same time, it is a complementary controller.
I don't know which role to use ?
```
/** Describes what specific role associated with a tracked device */
enum ETrackedControllerRole
{
	TrackedControllerRole_Invalid = 0,					// Invalid value for controller type
	TrackedControllerRole_LeftHand = 1,					// Tracked device associated with the left hand
	TrackedControllerRole_RightHand = 2,				// Tracked device associated with the right hand
	TrackedControllerRole_OptOut = 3,					// Tracked device is opting out of left/right hand selection
	TrackedControllerRole_Treadmill = 4,				// Tracked device is a treadmill
	TrackedControllerRole_Max = 5
};
```
If I choose left or right hand, it replaces the current left or right controller, it is not good.
And when I use OptOut or Treadmill, I see it in the controller settings and I bind the action for rotate or bind trackpad but that doesn't work in the game.

Is it normal ?

**Comment by Mvivant** [comment]
https://github.com/ValveSoftware/openvr/issues/886

**Comment by JoeLudwig** [comment]
Where is the data for your device coming from? If your device is intended to be used at the same time as right hand or left hand, you shouldn't use those.

**Comment by Mvivant** [comment]
@JoeLudwig, to make things clearer, how would you handle the following [demo](https://www.youtube.com/watch?v=3LXGt7sJzl0) (action starting at about 15 seconds)? No controllers, yet we move in the VR world.

**Comment by peroht** [comment]
@Mvivant , for this I suggest you use the TrackedControllerRole_Treadmill. It was created for this reason. 

How do you control motion today when you've implemented the device with steamvr? 
The common approach would be for you to add Trackpad functionality to your driver. Then you would register your driver with SteamVR and then via the Binding UI you would tie your locomotion action to the Trackpad of your driver/device.

Here is some overall information of how it can work with our device:
https://medium.com/omnifinity/configure-steamvr-to-work-with-the-omnideck-treadmill-84eb198d7a0e

**Comment by Mvivant** [comment]
Hi thanks for reply!

I use the trackpad functionality but it doesn't works if I use TrackedControllerRole_Treadmill.
When I bind the trackpad locomotion in SteamVR UI, I can't move on the game.
Why I have this behaviour ?

**Comment by peroht** [comment]
Is the application using the new or old input binding system?

If the application you are trying to control is not built with the new SteamVR input system the user needs to go a bit deeper. When you have your driver working, and have mapped the trackpad to the action you need to go to the "Extra settings" tab and select the "Return bindings with X hand".

Then the binding from your driver should be tied to the legacy action.

**Comment by peroht** [comment]
Glad it worked and that you finally got your driver working. 

I do not think so. From what I understand you do this from the application side - not from the driver side.

**Comment by JoeLudwig** [comment]
> But is it possitble that is checked (true) by default ?

You are able to ship bindings with your driver for apps if you want to have some defaults. Otherwise, checking that box is up to the user or developer who is building the bindings. 

Sounds like you got things working, so I'm going to close this. Let me know if there's still a lingering issue.
