### ISSUE TITLE
Cache the result of Prop_ContainsProximitySensor_Bool

### ISSUE THREAD

**Issue by godbyk** [ValveSoftware/openvr#127]
Does the `Prop_ContainsProximitySensor_Bool` property need to be requested so frequently or can its value be cached? It's unlikely an HMD is going to sprout a proximity sensor from one microsecond to the next.

**Comment by JoeLudwig** [comment]
Are you asking about vrserver requesting this from the driver or an application requesting it from the API?

In the bundled-in drivers the call to GetBoolTrackedDeviceProperty is just a switch statement that returns a cached value. Do you have a driver where it's significantly more expensive?

**Comment by godbyk** [comment]
I'm asking about the vrserver requesting the property from the driver.

It's not a performance issue for our driver. We're just returning a constant value.

But I'm logging each property request to help determine which properties I need to implement first, and the log file gets spammed with requests for the `Prop_ContainsProximitySensor_Bool` property. I thought it was odd that the server would need to request this property with such frequency as it's unlikely to change during runtime.

**Comment by JoeLudwig** [comment]
The only place this property is requested on the server is when TrackedDevicePoseUpdated is called by the driver. Not sure how often you're calling that function in your driver, but in the Lighthouse driver it's called on the order of 1100 times per second.  I would just exclude that property from your logging.

In general we don't cache anything at the callsite unless making the call is a performance problem. It's way too easy to cache too long and cause a bug. (Not that "does the HMD have a proximity sensor" is likely to change.)
