### ISSUE TITLE
90GB vrclient_Steam.txt log file for 3 days of logging (seems input related)

### ISSUE THREAD

**Issue by muchcharles** [ValveSoftware/openvr#1271]
The default log verbosity level of steamvr seems to be logging too much about the input system on each tick.

vrclient_Steam.txt grep to about 90GB over just 3 days or so (when I look inside to see earliest entries).

    /mnt/c/Program Files (x86)/Steam/logs$ ls -s vrclient_Steam.txt
    89454272 vrclient_Steam.txt
    
    /mnt/c/Program Files (x86)/Steam/logs$ patterns="/user/hand
    /filters/"
    /mnt/c/Program Files (x86)/Steam/logs$ LANG=C grep -v -F "${patterns}" vrclient_Steam.txt | wc -c
    144028

Note the output of `ls -s` is in KB where `wc -c` is in bytes (144KB).  That's showing that almost all the data in the log files (89GB - 144KB) is entries containing '/user/hand' or '/filters'.

**Comment by muchcharles** [comment]
I'm on beta 1.9.12 but it seems to be logging just as verbosely on stable 1.9.13.

Watching the logs, they are quite until as soon as index controllers are turned on.

**Comment by JoeLudwig** [comment]
Can you provide some samples of the spammiest ones?

**Comment by muchcharles** [comment]
@JoeLudwig this seems to be caused by the valve ue4 steam input plugin calling:

    VRSettings()->SetBool(k_pch_SteamVR_Section, k_pch_SteamVR_DebugInput, true, &BindingFlagError);

It calls it only in editor mode, but since it is the VRSettings interface I think that call persists it into the main steamvr.vrsettings and then it ends up affecting everything afterwards.

**Comment by muchcharles** [comment]
I think you can probably close this one and we can reopen:

https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/91

**Comment by JoeLudwig** [comment]
See my comment in https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/91

I'll kill the spam in 1.9.14.
