### ISSUE TITLE
TrackedDevicePose_t::vAngularVelocity is always reported as 0 by the Odyssey+

### ISSUE THREAD

**Issue by LukeRoss00** [ValveSoftware/openvr#1272]
The headset fails to report its angular velocity through OpenVR.

It might be a general issue with all WMR headsets, although for the moment I have only verified it with an Odyssey+ user.

The field is filled correctly by the lighthouse driver, for instance with the Index.

**Comment by JoeLudwig** [comment]
Unfortunately the Windows Mixed Reality driver does not provide SteamVR with angular velocity, so there's nothing for us to provide to the application.
