### ISSUE TITLE
Environments in 1.9

### ISSUE THREAD

**Issue by kpbg** [ValveSoftware/openvr#1273]
As the old environments are now effectively gone, please at least allow an option to launch SteamVR Home in a specific destination and without going through or getting back to the primary Home environment. In a commercial environment, we really don't want the people to see "Most popular SteamVR games". All we want is to put them in some initial lobby before they jump into the game.
The latest updates you are doing are nice, but this one will make a lot of businesses to stick with 1.8.21. SteamVR Home isn't really LBVR friendly :/

**Comment by BOLL7708** [comment]
Just expanding on this. It's been a while since I used SteamVR Home, but at least in the past we had the option to set a home environment, meaning any environment could be the default. Is this what is asked for or something else?

As an alternative, to get a custom environment in the construct it is still possible to set a background. This is what I'm doing, using the dome projection the bottom half of the background will be mapped as ground. It's, well, the substitute I found for now.

What bothers me slightly though is that the base environment is now the circular ground pattern, which is useful, but when using the dome projection I find it redundant and would love to have an option to hide it. Same with the base stations, when using four of them one is usually covering the overlay/dashboard as we no longer can hide them with a custom model. I digress 😅

**Comment by kpbg** [comment]
I spent some time with the current state of SteamVR Home before opening this issue and there is no way to "Automatically Visit a destination". Using the background isn't a good workaround when you are to put thousand of people through it. We were using a holodeck environment, as it helps the people (who never done VR before) to better orient how they should be positioned in the real world as well as it gets them much more WOWed compared to the now default empty environment + background.
And I'll definitely be missing the base station and controller skins as well. Despite I never noticed anything like this, I guess this has been causing performance issues that led to their removal. Can't figure out another reason :)

Until a better branding option shows up - we are sticking over 1000 PCs running SteamVR to 1.8.*

**Comment by freemancw** [comment]
You can automatically visit a destination on startup by setting it as your Home destination. To do so, visit the destination on your own, open the content browser, and click [Set as Home](https://steamcommunity.com/sharedfiles/filedetails/?id=1940554339). Most of the SteamVR environments were bulk-converted to destinations, so it's possible the exact environment you were using is already available as a destination in Home.

**Comment by kpbg** [comment]
Thanks!
Next related question is - can we forbid access to the content browser? This is all cool for the home users, but worrisome in a commercial environment.

**Comment by JoeLudwig** [comment]
Your best bet there is probably to unbind any actions that you don't want your users to do, and then disable settings in the dashboard (or disable the entire dashboard.) They'll be able to press the menu button in home all they like, it just won't do anything.

**Comment by freemancw** [comment]
For now, if you want to disable the menu, do the following. Instructions are given for Index Controllers but the steps are basically the same for other controller types:

1. Click on the SteamVR 1.9.3 hamburger menu in vrmonitor.
2. Click Devices->Controller Settings.
3. Click Manage Controller Bindings.
4. Make sure SteamVR Home is selected in the modal that pops up.
5. Click on "Custom" for Active Controller Binding.
6. Click on "Edit this Binding".
7. Click on the "Default" tab.
8. Scroll down to the "B Button" and delete the "Use as Button" binding for Toggle Menu.
9. Click "Delete" on the confirmation modal that pops up.
10. Click on "Save Personal Binding".

This should disable the menu.

**Comment by kpbg** [comment]
Great stuff! Thank you both.

Last question -- where the downloaded environments are saved on the hdd?

**Comment by freemancw** [comment]
For example: C:\Program Files (x86)\Steam\steamapps\workshop\content\250820

The numbers you find in that folder are the workshop IDs. One way of finding the ID is by visiting the workshop item and looking in the URL on the Steam Community site. Workshop ID 1910866740 is here:

https://steamcommunity.com/sharedfiles/filedetails/?id=1910866740&searchtext=

**Comment by kpbg** [comment]
So I have this one installed:
https://steamcommunity.com/sharedfiles/filedetails/?id=692340263

But I don't see it here:
![image](https://user-images.githubusercontent.com/10502446/71205754-bfbfee00-22ab-11ea-8d67-fc61d248238b.png)


Also, I have this one installed as well, but it doesn't let me "Visit" it in VR:
https://steamcommunity.com/sharedfiles/filedetails/?id=686754013
I guess it's not converted?

**Comment by freemancw** [comment]
Try unsubscribing + resubscribing?

**Comment by kpbg** [comment]
I did try that multiple times :/ 

I also tried to delete the folder before resubscribing -- it does not create a new folder. I also subscribed to some entirely new environments (which I didn't have before 1.9.*) and they doesn't appear in this folder. Looks like they now land somewhere, but I can't figure out where exactly.

**Comment by kpbg** [comment]
For the sake of the test, I just installed 1910866740 from your example, I have it currently running and I don't have that folder under C:\Program Files (x86)\Steam\steamapps\workshop\content\250820

**Comment by kpbg** [comment]
Alright, ignore that. My SteamVR is not on C:

Thank you for your help!

**Comment by freemancw** [comment]
Great! Please let us know if you have other issues.
