### ISSUE TITLE
is k_unMaxBoneNameLength supposed to include or exclude the NUL?

### ISSUE THREAD

**Issue by elect86** [ValveSoftware/openvr#1274]
As titled..

when used [here](https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L4546) for example for `pchBoneName`:
```
virtual EVRInputError GetBoneName( VRActionHandle_t action, BoneIndex_t nBoneIndex, VR_OUT_STRING() char* pchBoneName, uint32_t unNameBufferSize ) = 0;
```

Ps: sorry for the bothering but I dont have right now a scenario where I can quickly test this

**Comment by JoeLudwig** [comment]
It's the size of the buffer, and the buffer will need space for the bone name and the null character. No bone name can be longer than 31 characters, plus one for the null.  

I'll make the documentation in the header file more clear on this point.
