### ISSUE TITLE
Release 1.9.15 hast k_nSteamVRVersionBuild set to 16, should be 15

### ISSUE THREAD

**Issue by TheWhiteAmbit** [ValveSoftware/openvr#1279]
Release 1.9.15 hast k_nSteamVRVersionBuild set to 16, should be 15

**Comment by JoeLudwig** [comment]
The bug is actually in the release notes. This is the openvr.h header that matches the 1.9.16 version of SteamVR.

**Comment by TheWhiteAmbit** [comment]
Where can I find the release notes?

**Comment by JoeLudwig** [comment]
https://github.com/ValveSoftware/openvr/releases/tag/v1.9.15

**Comment by jeremyselan** [comment]
Thanks, we've pushed out a new release with proper 1.9.16 labeling. (The binaries and headers are unchanged).
