### ISSUE TITLE
ResetSeatedZeroPose Not working in Unity.

### ISSUE THREAD

**Issue by VictoryTea** [ValveSoftware/openvr#1285]
Valve.VR.OpenVR.System.ResetSeatedZeroPose();
Valve.VR.OpenVR.Compositor.SetTrackingSpace(Valve.VR.ETrackingUniverseOrigin.TrackingUniverseSeated);

Calling these should reposition the users current location IRL to the desired position in game, yes? Or, am I misunderstanding this: https://github.com/ValveSoftware/openvr/wiki/IVRSystem::ResetSeatedZeroPose

I've been reaching out on the SteamVR Developer Hardware Forums and being told to reset the position manually because ResetSeatedZeroPose() doesn't work.

This seems to be a very common issue, since 2012: https://forum.unity.com/threads/openvr-how-to-reset-camera-properly.417509/#post-2792972

We are being forced to find workarounds, or does everyone including myself just misunderstand how to use this?

Thanks..

**Comment by VictoryTea** [comment]
Window > SteamVR Input > Advanced Settings > SteamVR Settings > "Tracking Space Origin" drop-down menu, "Tracking Universe Seated"

Alternatively, Project Window > SteamVR_Resources > Resources > SteamVR_Settings > "Tracking Space Origin" drop-down menu, "Tracking Universe Seated"

Once properly selected, one only needs to call Valve.VR.OpenVR.System.ResetSeatedZeroPose(); for example, on button state down, then manually adjust desired height.

**Comment by ll-M-ll** [comment]
I've gone back to latest semi working version with was preview.3
