### ISSUE TITLE
No key response using NOLO hardware in game that uses HTC Vive

### ISSUE THREAD

**Issue by Hettylool** [ValveSoftware/openvr#1287]
Hello

I am the technical development leader of nolo. We have developed a software that uses NOLO's 6DoF hardware, accesses the OPENVR protocol, and simulates HTC to report data to SteamVR. At present, the button does not take effect in boneworks. This game uses htc vive The keys are normal during the game. With the nolo device, there is no key response in the game, only the location.

What factors will affect the button not responding, such as profile other factors? (The attachment contains the profile file that nolo is using, please check)

In addition, if controller_type adds a nolo_controller, what do we need to do?

Thanks for your continued support and help!

**Comment by peroht** [comment]
Does your openvr driver expose some button/trackpad functionality that the user can activate and then tie the locomotion game actions to the button/trackpad via the SteamVR Binding UI?

**Comment by Hettylool** [comment]
How can I make the button public to all SteamVR game developers?
