### ISSUE TITLE
OpenVR SDK v1.9.16 openvr.h breaks compile on V2013

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#1288]
New struct Compositor_StageRenderSettings has inline initialisers which don't compile under VS2013:

```
openvr.h(3110): error C2797: 'vr::Compositor_StageRenderSettings::m_PrimaryColor': list initialization inside member initializer list or non-static data member initializer is not implemented
openvr.h(3111): error C2797: 'vr::Compositor_StageRenderSettings::m_SecondaryColor': list initialization inside member initializer list or non-static data member initializer is not implemented
```

**Comment by TheDeveloperGuy** [comment]
Apparently OpenVR SDK silently dropped support for Visual Studio 2013 in the latest SDK:

https://github.com/ValveSoftware/openvr/issues/1281

Many prebuilt support libraries use standard library linkages that are not compatible with 2015 and onwards (due to a breaking change in MS standard C/C++ libraries). Breaking build support for Visual Studio 2013 will cause a lot of issues, where source code or updated binaries are not available for the support libraries.

**Comment by aleiby** [comment]
Thanks, I'll remove those in the next update.

**Comment by TheDeveloperGuy** [comment]
Fixed in later version.
