### ISSUE TITLE
IVRSystem::TriggerHapticPulse argument is incorrectly labeled.

### ISSUE THREAD

**Issue by thesbros** [ValveSoftware/openvr#129]
The usDurationMicroSec argument of [IVRSystem::TriggerHapticPulse](https://github.com/ValveSoftware/openvr/wiki/IVRSystem::TriggerHapticPulse) says it is the duration of the haptic pulse in microseconds, but it is actually the strength of the haptic pulse.

**Comment by subnet-** [comment]
Quote of "mptp" from the Steam Forums:

> The parameter you pass into TriggerHapticPulse is measured in microseconds, with the max value (in my tests) being 3999, which is 4ms - each frame at 90Hz is 11ms long.
Because of this, if you're pulsing each frame, the effect of pulse length is felt subjectively as vibration strength.

> If you want longer vibrations, try something like this:

```cpp
//length is how long the vibration should go for
//strength is vibration strength from 0-1
IEnumerator LongVibration(float length, float strength) {
    for(float i = 0; i < length; i += Time.deltaTime) {
        SteamVR_Controller.Input([index]).TriggerHapticPulse((ushort)Mathf.Lerp(0, 3999, strength));
        yield return null;
    }
}
```
>And for pulsed vibrations

```cpp
//vibrationCount is how many vibrations
//vibrationLength is how long each vibration should go for
//gapLength is how long to wait between vibrations
//strength is vibration strength from 0-1
IEnumerator LongVibration(int vibrationCount, float vibrationLength, float gapLength, float strength) {
    strength = Mathf.Clamp01(strength);
    for(int i = 0; i < vibrationCount; i++) {
        if(i != 0) yield return new WaitForSeconds(gapLength);
        yield return StartCoroutine(LongVibration(vibrationLength, strength));
    }
}
```


Source: https://steamcommunity.com/app/358720/discussions/0/405693392914144440/#c357284767229628161
