### ISSUE TITLE
SteamVR Input Chord conflict with advanced input options

### ISSUE THREAD

**Issue by ykeara** [ValveSoftware/openvr#1295]
### Issue

 Advanced Options such as `double` can interfere with chords being registered

### Example

an `a click` + `b click` chord cannot be bound while `a double` is also bound.

### Other Issue's (design decision?)

- Chords not having access to advanced features
  - I.E. Can't make a chord `double a` + `double b`
  - also can't make a chord such as `long press a` + `press b`

- Empty Action needs to be present to see option
  - I.e. If you want to bind `b click` you must have a action for a `b button` even if its empty.

**Comment by JoeLudwig** [comment]
Once you configure Double or Long buttons switch into a mode where the click only happens for one frame. That's what Held is for. Does this work if you chord with Held instead of with Click/Single?

**Comment by ykeara** [comment]
Closing the Issue.

This Covers the main issue and the first sub-issue.

Essentially

your chords are not looking for  a click + b click, but a moment that both a + b are activated.

This means that holding a and pressing b will trigger the cord, and vice-versa, but that pressing a then pressing b will not trigger it.

Understanding that while double clicking chords might still make sense..... you don't differentiate between hold a and then press b, or press a and b at the same time.

And you have your advanced options balanced against that.


Also going to assume second sub-issue is a design decision to avoid clutter.
