### ISSUE TITLE
SteamVR Beta 1.10.x SetOverlayRendermodel no longer works as expected. 

### ISSUE THREAD

**Issue by Xiexe** [ValveSoftware/openvr#1309]
I was previously able to call SetOverlayRendermodel(), feeding it the path to a properly formatted .obj, and have a model displayed within my overlay application. 

After the 1.10 updates, this stopped working, it seemingly now does nothing, wether it be targeting models that worked before, or even the models within the SteamVR Rendermodels Resources folder. 

This functionality is fairly useful, and I would like to personally see it fixed as I'm using it to display certain UI elements.

**Comment by ChristophHaag** [comment]
I've encountered the same. `SetOverlayRenderModel()` returns `VROverlayError_PermissionDenied`.

This might have broken it (but I haven't tested it) https://steamcommunity.com/games/250820/announcements/detail/4067248059946729366 "Fix for showing render models for generic tracked objects (e.g. Logitech Stylus)."

**Comment by Xiexe** [comment]
Ah, I should have checked the error. I don't know why, but I didn't think to in this case. Glad I'm not the only one though.

I did figure that 1.10.3 was the update that broke it, but I haven't been able to test that theory.

**Comment by lubosz** [comment]
This is reproducible in xrdesktop
Our minimal example for that is:
https://gitlab.freedesktop.org/xrdesktop/gxr/blob/master/examples/overlay_models.c

**Comment by RosmicG** [comment]
Has this been fixed yet? I would love for this to work but its still broken

**Comment by jeremyselan** [comment]
This is currently disabled in 1.10.  Can you share more information about your use cases?  We have re-architected the underlying engine, and this may be a good opportunity to more directly address your needs.  Are you actually interested in attaching render models to overlays? Or were you taking advantage of this to have our compositor draw a render model (and the overlay was superfluous)?

**Comment by Xiexe** [comment]
I was personally using this to draw lasers and other 3D UI elements within Overlays. 

Specifically, I had touch typing on a keyboard with a sphere that was used to indicate how close your hand was to touching the keys, and I had lasers and custom controller render models to show where you where pointing easier from afar.

I'd really love if this was re-enabled, or a replacement was made.

**Comment by nnaaanachi** [comment]
In our case, we were rendering the controller models to provide a good point of reference in 3d space when adjusting overlays attached to them and were using it as a cheap means to render a pointer from the controller to an overlay.

**Comment by emulamer** [comment]
Definitely would like to have this functionality.  We'd like to be able to render (ideally a textured) model as an overlay instead of it being limited to a 2D plane.

**Comment by Xiexe** [comment]
Any news on this? I realize that support was removed via the changelogs, but I'd really like to be able to have some way of displaying custom render models in an overlay application. That was the only way to do it as it stands, and I feel that it's a pretty important feature due to the reasons I mentioned earlier.

**Comment by ScruffyRules** [comment]
I use Xiexe's overlay fairly often while in VR, I used to use the render models as a way to know where my cursor is pointing but now I have to wave my hand around to find it.

**Comment by CircuitLord** [comment]
We really need some form of render models. The range of what we can do with 2D overlays can be extremely limiting at times. Things like pointers, fancy UI stuff, or basically just any 3d model you want the user to see should definitely be possible.

While the old system was kind of clunky and undocumented at best, there's not really a good reason that it should of been removed unless it was causing serious issues elsewhere.

Is there any chance we can get a new, more well documented and supported system for showing 3D objects as overlays, or at the very least have the previous system re-enabled for us?

**Comment by AndreGroeschel** [comment]
+1 for overlay render models! We would like to do some more advanced fx and interfaces that are simply not possible with 2D overlays

**Comment by alexander-clarke** [comment]
My planned usage was to use a photogrammetry scan of my room to overlay on to other apps (so that I can see my sofa and sit down in something like google earth VR for example). Also if I could fade this model in and out as a chaperone that would be great.

**Comment by FlameSoulis** [comment]
Bumping this. I had a group of VR developers talk about this when I asked about such. Something like this shouldn't go under the radar or, if the issue is resolved, be left open.

**Comment by Xiexe** [comment]
> Bumping this. I had a group of VR developers talk about this when I asked about such. Something like this shouldn't go under the radar or, if the issue is resolved, be left open.

I've recently had a discussion with a SteamVR developer (not going to name names out of courtesy).

Unfortunately, as far as I could get from the prying I did, it seemed that the likely answer/attitude towards this is "won't be fixed."

I'd at least like to have an official reply to the issue though, and for them to close it, if they're not going to bring it back.

**Comment by JoeLudwig** [comment]
The implementation for this function isn't coming back..

Your best bet at this point is to render the 3D stuff on your side and use [IVROverlay::SetOverlayTransformProjection](https://github.com/ValveSoftware/openvr/blob/4c85abcb7f7f1f02adaf3812018c99fc593bc341/headers/openvr.h#L4000) to draw that into the scene with a second overlay.
