### ISSUE TITLE
Clarify supported C++ Standard

### ISSUE THREAD

**Issue by SuperV1234** [ValveSoftware/openvr#1314]
Constructs such as `auto` and `nullptr` are being used in OpenVR, which is great. I went through the README and briefly skimmed through the docs, but could not find an official "supported standard".

Does OpenVR target C++11? 14? 17? 20? 

It would be a good idea to make it clear and easily visible, so that contributors know what they can use.

**Comment by JoeLudwig** [comment]
The header files in the SDK (i.e. openvr.h) target C++11, and will likely continue to target C++11 indefinitely. That's important to support as broad a range of apps as possible. (There's also a C header that targets... C99 I think?)

SteamVR uses C++11 internally at the moment. That code is mostly closed source, so not particularly relevant for the Github repo. 

The one bit that is relevant is the public version of openvr_api.dll (or .so). If we move the internal build tools forward to a newer standard at some point we may need to make a call about that library. Most of what it does is path manipulation and file IO, so std::filesystem would be nice to have. That's not an imminent change, however, so we'll work that out when we get there.

So the answer to your question is: C++11. If you're writing code that you intent to offer a pull request for, it needs to be C++11.

**Comment by SuperV1234** [comment]
Thanks. I think it is worthwhile mentioning this in the README or documentation.
