### ISSUE TITLE
personal bindings not loaded for TWDSaintsAndSinners (and a few other games as well)

### ISSUE THREAD

**Issue by CybershoesVR** [ValveSoftware/openvr#1317]
# Steps to reproduce:

1. run TWD: Saints&Sinners
2. create steamvr_input bindings in the controller bindings menu for index controller
3. save bindings to vr-input-workshop
4. restart game

# What happens:

5. default bindings are loaded

# What should happen:

5. personal bindings are remembered

# Additional Info:

It seems, that:
1) the game registers as legacy input
2) steamvr loads steamvr_input bindings from workshop
3) steamvr detects a mismatch  (steamvr_input != legacy)
4) steamvr rejects personal bindings
5) game changes into steamvr_input mode

## relevant lines from the vrserver.log

```
Mon Feb 17 2020 21:58:53.776 - New Connect message from C:\Program Files (x86)\Steam\steamapps\common\TWDSaintsAndSinners\TWD\Binaries\Win64\TWD-Win64-Shipping.exe (VRApplication_Scene) (Args: TWD -steam -culture=en) 17004 
Mon Feb 17 2020 21:58:53.776 - StartSceneApplicationTransitionFromProcess( 17004, C:\Program Files (x86)\Steam\steamapps\common\TWDSaintsAndSinners\TWD\Binaries\Win64\TWD-Win64-Shipping.exe, steam.app.916840)
Mon Feb 17 2020 21:58:53.776 - AppInfoManager.StartSceneApplicationTransitionFromProcess: Found app info for starting key steam.app.916840
Mon Feb 17 2020 21:58:53.776 - AppInfoManager.ProcessConnected BEGIN 17004 C:\Program Files (x86)\Steam\steamapps\common\TWDSaintsAndSinners\TWD\Binaries\Win64\TWD-Win64-Shipping.exe 1 steam.app.916840
Mon Feb 17 2020 21:58:53.785 - SetApplicationPid appkey=steam.app.916840 pid=17004, external transition
Mon Feb 17 2020 21:58:53.785 - SetApplicationPid: Setting app steam.app.916840 PID to 17004
Mon Feb 17 2020 21:58:53.785 - AppInfoManager.ProcessConnected END
Mon Feb 17 2020 21:58:53.785 - Enabling legacy input for steam.app.916840
Mon Feb 17 2020 21:58:53.787 - steam.app.916840 (vive) attempting to load default config from file:///C:/Program%20Files%20%28x86%29/Steam/steamapps/common/SteamVR/resources/config/legacy_bindings_generic_hmd.json
Mon Feb 17 2020 21:58:53.787 - steam.app.916840 (vive_controller) attempting to load current setting config from vr-input-workshop://1977021775
Mon Feb 17 2020 21:58:53.787 - Processing message VRMsg_Connect from TWD-Win64-Shipping (17004) took 0.0112 seconds
Mon Feb 17 2020 21:58:54.227 - Unknown action set /actions/main
Mon Feb 17 2020 21:58:54.227 - User had an invalid config selected for steam.app.916840(vive_controller) version 0 < 0 (0) category steamvr_input != legacy. Setting back to default URL file:///C:/Program%20Files%20%28x86%29/Steam/steamapps/common/SteamVR/drivers/htc/resources/input/legacy_bindings_vive_controller.json
Mon Feb 17 2020 21:58:54.229 - steam.app.916840 (vive_controller) attempting to load default config from file:///C:/Program%20Files%20%28x86%29/Steam/steamapps/common/SteamVR/drivers/htc/resources/input/legacy_bindings_vive_controller.json
Mon Feb 17 2020 21:58:55.355 - Discarding steam.app.916840 (vive_controller) binding query result because its category steamvr_input doesn't match the manifest's category legacy
Mon Feb 17 2020 21:59:04.349 - Remembering SetActionManifestPath call from steam.app.916840: file:///C:/Users/User/AppData/Local/TWD/Saved/Config/steamvr_actions.json
Mon Feb 17 2020 21:59:04.351 - steam.app.916840 (vive_controller) attempting to load default config from file:///C:/Program%20Files%20%28x86%29/Steam/steamapps/common/TWDSaintsAndSinners/TWD/Config/SteamVRBindings/vive_controller.json
```

**Comment by frostworx** [comment]
pretty sure this linux SteamPlay/Proton issue is related:
https://github.com/ValveSoftware/Proton/issues/3483#issuecomment-589949969

**Comment by CybershoesVR** [comment]
Maybe we need to mention that we've uninstalled our Cybershoes driver for this test. Therefore this seems to concern all systems. In the TWD community, it's a big topic as Quest+Virtual Desktop relies on personal bindings. The two other games are Apex Construct & Spiderman: Far from Home. Quite sure there are more games affected.

**Comment by CybershoesVR** [comment]
@JoeLudwig Can you take a look, please? Maybe you can provide some insights.

**Comment by metainf** [comment]
I'm seeing this issue as well for Arizona Sunshine and Arizona Sunshine Arcade. Although I'm not seeing it for older versions of Arizona Sunshine, which seems to suggest that its an issue with games that use the current binding system being defaulted to the legacy system on launch for some reason.

**Comment by JoeLudwig** [comment]
Do you get a message like this in your vrserver.txt log?

Tue Mar 03 2020 13:45:05.334 - User had an invalid config selected for steam.app.<number>(knuckles) version 0 < 0 (0) category steamvr_input != legacy. Setting back to default URL file:///C:/Program%20Files%20%28x86%29/SteamBeta/steamapps/common/SteamVR/drivers/indexcontroller/resources/input/legacy_bindings_index_controller.json
file:///C:/Program%20Files%20%28x86%29/SteamBeta/steamapps/common/SteamVR/resources/config/legacy_bindings_generic_hmd.json

If so, I think we have a fix on the way.

**Comment by CybershoesVR** [comment]
@JoeLudwig Thank you! We tested this on the current **beta** branch: works great.

**Comment by Patola** [comment]
With the latest update of TWDSaintsandSinners this issue came back.

**Comment by CybershoesVR** [comment]
@Patola TWDSS have changed their steamapp ID and renamed some of the actions they use. E.g. what was moveforwardright is now moveforward. Old bindings lost. New bindings do work.
