### ISSUE TITLE
Could you please Add libraries and binaries for MinGW

### ISSUE THREAD

**Issue by Dmi3Dev** [ValveSoftware/openvr#133]
Just like the title says: 
Could you please Add libraries and binaries for MinGW.

Who will benefit from it: 
All the developers, who don't want to put up with limitations of Visual Studio and (sorry, couldn't find better words) non standard behavior of Visual C++ compiler. Developers who build cross platform applications. It's so much easier not to have to add #ifdefs and workarounds for stuff that Visual C++ don't support, or interpret differently during compile.

Personally I don't have enough space (and will) to install Visual Studio. I got separate VC compiler, but lack of ability to debug makes it very frustrating, to say the least. Since openvr isn't very open, you would make my life (and lives of many other developers) a lot easier by adding support for it.
Thank you.

**Comment by MajortomVR** [comment]
I just want to add my voice here to say i would love this too! As a Linux user i prefer choice and it's much easier to use the same toolchain for cross platform development (my IDE of choice is Codeblocks).

**Comment by johnv-valve** [comment]
I am not sure what you are asking for. linux 32-bit and 64-bit libraries are provided, can you be more specific about what you need?

**Comment by Dmi3Dev** [comment]
Please correct me if I'm wrong, but as far as I know libraries compiled in Linux are not compatible with Windows. 
To be more specific, I would be happy to have libraries compiled with 
mingw-w64-x86_64-gcc 5.3.0
Maybe someone still need 32-bit libraries for MinGW, those would be:
mingw-w64-i686-gcc 5.3.0
Thank you.

**Comment by tunabrain** [comment]
Just chiming in to say I would absolutely love MinGW binaries as well! To clarify, MinGW is a Windows port of gcc. It is available standalone or, more conveniently, can be installed with the package manager of MSYS2 ( https://msys2.github.io/ ), which also provides a usable bash shell and environment on Windows.

As far as I know MinGW has its own ABI, so linux binaries are not compatible. MSVC binaries are only compatible with MinGW for C interfaces. C++ binaries produced by MSVC are not compatible.

In general, if OpenVR already compiles with gcc, then compiling with MinGW should not be too difficult. The main source of error is if you are using OS macros to detect the compiler or vice versa (e.g. doing #if defined(_WIN32) to enable MSVC specific flags, or assuming that defined(GNUC) implies a non-Windows system). Always use compiler macros (_MSC_VER, __GNUC__, __clang__) to detect the compiler, and OS macros (__APPLE__, __linux__, _WIN32) to detect the OS. Other than that you can assume MinGW to behave like gcc.

**Comment by MajortomVR** [comment]
What i tried to say is, it would be great to be able to compile with mingw on windows because i could use the same IDE on linux and windows (codeblocks). Thanks for looking into this!

**Comment by petterarvidsson** [comment]
I would really like this as well, I think it also would solve #103

**Comment by tunabrain** [comment]
For everyone interested in this, I've found a workaround.

Since openvr also allows retrieving raw function tables from VR_GetGenericInterface, it is possible to generate wrapper classes that expose the same methods as the original header, but call into openvr function tables internally. That way the header links to the portable C interface, but can be used exactly like the C++ interface.

This allows using the current DLLs with MinGW without needing additional work from Valve. This header can also be used from MSVC and will work even if MSVC changes its C++ ABI, which it does every now and then.

There are different ways to do this. My version is available here: https://gist.github.com/tunabrain/84a3f234d4baa6d438b642f14522999c
It was generated automatically from the original OpenVR header using a simple python script: https://gist.github.com/tunabrain/1fc7a4964914d61b5ae751d0c84f2382

I've managed to compile and run the sample programs using MinGW with this header.

**Comment by Dmytry** [comment]
Wow, that's quite awesome work @tunabrain! Man I was trying to do that with the official vr_capi header and it does not even tell you - not at any point whatsoever - that you have to prefix with FnTable:

**Comment by tunabrain** [comment]
I was struggling with the same problem - only after reading through the C# bindings did I figure out what was missing. The C API hasn't been seeing much love, but that is still something that should probably be mentioned in the docs.

**Comment by Dmytry** [comment]
Yeah what tipped me off something was seriously crazy was including the c++ api for some reason and seeing that VR_GetGenericInterface (helpfully blocked with "#if 0" is the same function as the one C++ api uses to get pointers to vtables), which made me think that it was altogether one of those 100% broken never worked things.

**Comment by holocronweaver** [comment]
Just to be clear to Valve employees, the tunabrain has provided a temporary workaround. This issues remains unresolved.

**Comment by ekmett** [comment]
As (primarily) a Haskell developer, this would go a long way towards increasing the usability of this library to me.

**Comment by lukexi** [comment]
@ekmett I'm using @tunabrain's workaround now in https://github.com/lukexi/openvr-hs (as part of https://github.com/lukexi/rumpus which is compiled in MSYS2 and shipping happily on Steam!)

**Comment by HadrianusAugustus** [comment]
I am using mingw-w64 4.9.2, it is working with @tunabrain's solution.
For the record, helping others find this solution, GetEyeToHeadTransform or GetProjectionMatrix were providing a segmentation fault, now it is working perfectly.
Thanks a lot for your help

**Comment by DataBeaver** [comment]
i686-w64-mingw32-g++ 6.1.1 (the current version in Debian unstable) can successfully use the provided libraries.  I am cross-compiling from Linux.

**Comment by Dmytry** [comment]
Very interesting. Does it work ok when the function returns a struct? I
don't remember if there's that in openvr sources but I know the larger than
64 bit return values are problematic with gcc/msvc.

**Comment by DataBeaver** [comment]
It looks like you are right unfortunately :(  Trying to call a function that returns a struct will segfault.  MY code was still at a very early stage when I made the previous comment and I hadn't used any such functions yet.  There aren't many such functions, but IVRSystem::GetEyeToHeadTransform is a pretty important one.

I'll see if I can make any sense of the relevant disassembly and find a workaround when it isn't almost 4am.

**Comment by Dmytry** [comment]
Tunabrain's workaround seems the most solid... I personally went with using
C api directly except for some code I copy pasted from the example for now
(which I'll eventually refactor out). Anything involving some custom
assembly is going to be very fragile.

Other issue with GCC is that overloads in MSVC are in the reverse order,
and in GCC in sane order (the kind you'd expect). I.e. if you have two
overloaded functions MSVC will group them together and reverse them.

**Comment by HadrianusAugustus** [comment]
I confirm @tunabrain's solution works well for IVRSystem::GetEyeToHeadTransform issue with mingw64 and for all access to openvr API.
Thanks again

**Comment by DataBeaver** [comment]
All right, so here's what I've learned.

The Visual C++ 32-bit calling convention for member functions is to pass "this" in ecx.  MinGW follows this convention when returning void or register-sized values.  When returning structs, Visual C++ passes an address for storing the return value as the first stack parameter (hidden at source code level).  Inexplicably MinGW decides to swap these two, instead passing "this" on stack and the return value address in ecx.

What this means is that these two functions should have the same call signature at machine code level:
```C++
Thing func();
void func(Thing *);
```
However MinGW generates different assembly for calling them as member functions.  The first one is incompatible with Visual C++, but the second one is compatible.  My solution is to take a pointer to the member function returning a struct and reinterpret_cast it to the second form:

```C++
void OpenVRDevice::configure_view(StereoView &view) const
{
	vr::IVRSystem *vr_sys = vr::VRSystem();

#if defined(__GNUC__) && defined(_WIN32)
	typedef void (vr::IVRSystem::*FuncPtr)(vr::HmdMatrix34_t *, vr::EVREye);
	FuncPtr get_eye_to_head_transform = reinterpret_cast<FuncPtr>(&vr::IVRSystem::GetEyeToHeadTransform);

	vr::HmdMatrix34_t left, right;
	(vr_sys->*get_eye_to_head_transform)(&left, vr::Eye_Left);
	(vr_sys->*get_eye_to_head_transform)(&right, vr::Eye_Right);
#else
	vr::HmdMatrix34_t left = vr_sys->GetEyeToHeadTransform(vr::Eye_Left);
	vr::HmdMatrix34_t right = vr_sys->GetEyeToHeadTransform(vr::Eye_Right);
#endif
	
	view.set_eye_matrices(convert_matrix(left), convert_matrix(right));
}
```
I've tested it and it works.  In my opinion it's a better solution than modifying a header from the SDK.

**Comment by tunabrain** [comment]
That works, but I will stress that these implementation details are not standardized and can change even within the same compiler across different versions. The other downside is that you need to modify every call site (i.e. have two code paths for every call)..

The motivation of modifying the header was that a) it was as portable as possible, i.e. does not rely on implementation details, and b) is completely transparent, i.e. allows you to use the OpenVR API as if the wrapper wasn't there. The latter ensures that the code you write is portable across build systems, and that you can use third-party code that uses OpenVR.

**Comment by Dmytry** [comment]
I think the most robust solution is to use official C api. E.g. yours is
likely to break with a GCC update.

Here's what I do:

#include "openvr/headers/openvr_capi.h" // works across compilers
...
VR_IVRSystem_FnTable *pVRSystem=NULL;
...
const std::string fntable_prefix("FnTable:");

pVRSystem = (VR_IVRSystem_FnTable *)VR_GetGenericInterface((fntable_prefix
+ IVRSystem_Version).c_str(), &err);
...
// this works fine:
matrix=pVRSystem->GetEyeToHeadTransform(EVREye(eye));

By the way, tunabrain's solution auto-generates wrappers for the official C
api, and should be pretty robust as well.

I used to (reluctantly) do calling convention workaround stuff for
SteamWorks SDK before they added C api, because it was literally the only
way back then (short of making a wrapper and compiling it with MSVC), and
it did break on several occasions. Highly don't recommend.

**Comment by DataBeaver** [comment]
A GCC update breaking my solution would imply a calling convention change, which would break the binaries of pretty much every existing C++ library out there.  I don't think it's all that likely to happen.  What could be a source of breakage though is if the OpenVR API changes; my reinterpret_cast would mask any changes in the signature of the affected functions.

If a GCC update does break it, then it would also break any MinGW libraries provided by Valve.  Can we expect them to keep track of those updates and ship alternative libraries, and for users to craft their build systems so they can select the appropriate library based on compiler version?

**Comment by tunabrain** [comment]
>  I don't think it's all that likely to happen
Unfortunately it does happen - ABI changes are not unprecedented. I have had it happen on minor version bumps on MSVC, and I believe it also happens on major version bumps on gcc. It's one of the reasons C++ libraries are much less popular than C libraries: Unlike the C ABI, the C++ ABI is not standardized. Binaries of any C++ library that is not actively maintained will stop working with newer compiler versions after some time.

The C ABI is rock solid on the other hand. One of the accidental benefits of the wrapper header is that it calls the C API internally, so it is very unlikely to break in the future. You could even use the wrapper header with MSVC, in case the native MSVC libraries stop working after a compiler update.

**Comment by Dmytry** [comment]
> A GCC update breaking my solution would imply a calling convention change, which would break the binaries of pretty much every existing C++ library out there. I don't think it's all that likely to happen. 

I had to use that kind of solution for Steam's SDKs before they added C API - namely I had to add a dummy integer argument before the rest of the arguments, because GCC was using more registers for argument passing than MSVC. And yes it did break somewhere between GCC 4.4 and GCC 4.8 , when mingw made their thiscall default.

With @tunabrain's solution the only potential issue is that his wrapper generator may not process the headers for the future versions of OpenVR API . The generated wrapper however will continue to work through OpenVR's versioning / backwards compatibility.

**Comment by jespertheend** [comment]
I'm not sure if openvr.h actually got updated but I ran the python script from @tunabrain and it caused a couple of errors because there were too many brackets for some reason. I fixed them manually and I'm using this right now https://gist.github.com/jespertheend/27ec16a18f36dff8a6f76ef57bb4d3d0

**Comment by tunabrain** [comment]
You are correct! The script broke with an openvr.h update.

I've fixed the script and regenerated the headers. The new headers are available here:
https://gist.github.com/tunabrain/84a3f234d4baa6d438b642f14522999c
And the fixed generator script here:
https://gist.github.com/tunabrain/1fc7a4964914d61b5ae751d0c84f2382

**Comment by LancePutnam** [comment]
@tunabrain the header you regenerated does not appear to be for 1.0.5. @jespertheend's solution works.

**Comment by tunabrain** [comment]
@LancePutnam You're right! I regenerated the 1.0.5 headers with the scripts, they are available here:

https://gist.github.com/tunabrain/84a3f234d4baa6d438b642f14522999c
They're almost identical with @jespertheend 's headers, so the script still seems to work for 1.0.5.

**Comment by StrikerMan780** [comment]
Please give us MinGW libraries for the SteamWorks API as well, thanks.

**Comment by blitz-research** [comment]
> I regenerated the 1.0.5 headers with the scripts, they are available here:

Thank you very much for this, worked first time for my project!

**Comment by blitz-research** [comment]
Any chance of updating this for latest header?

**Comment by tunabrain** [comment]
@blitz-research : I've generated new headers from the current git head and uploaded them here:
https://gist.github.com/tunabrain/84a3f234d4baa6d438b642f14522999c

I don't have a Vive set up right now and can't test the above, but at least compilation seems to succeed.

**Comment by blitz-research** [comment]
Thank you very much, all working fine so far.


On Fri, Jan 12, 2018 at 8:55 AM, Benedikt Bitterli <notifications@github.com

**Comment by photex** [comment]
This would be wonderful and allow me to more easily cross-compile from Linux to Windows.

**Comment by photex** [comment]
Hey uh... I did not actually unassign anybody here... github just did that after I posted a comment :confused:  ... @johnv-valve maybe this repo has some wild permissions issues?

**Comment by nicolayr** [comment]
Since it doesn't seem to have been mentioned here - precompiled OpenVR binaries are available for MSYS2/MinGW, so if you're using that you can get the library using pacman:

`pacman -S mingw64/mingw-w64-x86_64-openvr`

Then add something like the following to CMakeList.txt:

```
find_library(OPENVR_LIB NAMES openvr_api)
link_libraries("${OPENVR_LIB}")
```

**Comment by JoeLudwig** [comment]
We don't have any test apps that use MinGW, and would probably break such binaries all the time. You're better off building from source or using binaries provided by a third party like @nicolayr is pointing at.

FWIW, the code in openvr_api changes very rarely and doesn't depend on what version of openvr.h you're using. You shouldn't need to rebuild this library when moving to a new SDK unless we add a new top level VR_<whatever> C function.

**Comment by LancePutnam** [comment]
@nicolayr thanks for pointing out OpenVR inclusion in pacman under Mingw-64/MSYS2. I got it to work, but still had to use @tunabrain 's script (https://gist.github.com/tunabrain/1fc7a4964914d61b5ae751d0c84f2382) to produce a compatible C++ header.

**Comment by Alexpux** [comment]
I'm add generating mingw C++ header for openvr as @tunabrain ask me
