### ISSUE TITLE
Active VR game

### ISSUE THREAD

**Issue by AndreGroeschel** [ValveSoftware/openvr#1332]
Hi there,

we are developing an overlay application and would like to retrieve the current VR game the user is playing. Is this possible through OpenVr? Also is there a callback to get notified if the user changes the game?

Thanks,
André

**Comment by BOLL7708** [comment]
You can listen to `VREvent_SceneApplicationChanged` and run `OpenVR.Applications.GetCurrentSceneProcessId()` to get the current app ID.

**Comment by AndreGroeschel** [comment]
thank you! that did the trick :)
