### ISSUE TITLE
samples:hellovr_opengl failed.

### ISSUE THREAD

**Issue by hundry1986** [ValveSoftware/openvr#134]
The samples project build succeeded. 
But when I launched hellovr_opengl.exe, It reported: "Failed to find interface 'IVRCompositor_015'".
All HTC Vive components were connected, and steamvr checked them already.
Is there anything I missing?
I saw "Compositor initialization failed. See log file for details", but where is the log?  There is a "hellovr_opengl.tlog" directory, but I find nothing wrong.

**Comment by MajortomVR** [comment]
You can find the logs when you open the SteamVR Settings -> General: On the bottom right is a button "View Logs". It opens the folder with the log files.

Have you tried restarting the vive. Do other applications work?

**Comment by hundry1986** [comment]
Thank you for replying.
Other applications work well.
theBlu, Virtual Desktop, etc.
I checked vrcompositor.txt:
Failed to get tracked camera frame dimensions!
Tracked Camera: Failed to create static GPU resources.
D3D11 Camera Initialization failure.
I installed unreal engine 4 last night and this project worked this morning.
So maybe D3D11?
I only installed DXSDK11(DXSDK_Jun10) before.

**Comment by kristyfuwa** [comment]
Unable to init VR runtime:Installation path could not be located(110)

**Comment by Elou44** [comment]
Hi there,
I could compile "hellovr_opengl" sample successfully, my SteamVR is in "Ready" state but   
I have the following runtime error: "Failed to find interface 'IVRCompositor_016'".  All I can see is a white window that remains opened for 2 seconds. 

Any help would be much appreciated,

Best Regards

**Comment by JoeLudwig** [comment]
Is it possible that you're using an old build of SteamVR? IVRCompositor_016 was new with the most recent default build update on July 5th: http://steamcommunity.com/games/250820/announcements/detail/606114725478332420

**Comment by Elou44** [comment]
Indeed, I had an incompatibility between my steamVR build and the openvr SDK.
I did checkout SDK to v1.0.1 version and it worked.

Thank you very much for the heads up :)

**Comment by Xieminhust** [comment]
hello,I use the newest SDK  and meet the same problem ,the program failed at vr::VRCompositor(),and it always return false ,what can i do

**Comment by hundry1986** [comment]
sorry for replying so late...
1. update steamvr
2. update sdk
3. check openvr_api.dll file. (steamvr\bin and sdk\bin)
my program crashed because I only updated sdk, but not steamvr.

2017-03-29 21:24 GMT+08:00 Xieminhust <notifications@github.com>:
