### ISSUE TITLE
UE4.24 SteamVR Motion Controller Material

### ISSUE THREAD

**Issue by pixelcitystudio** [ValveSoftware/openvr#1355]
I have a problem with the show controller model option in motion controller component, in the editor I see the right material, but in a packaged game, the material is missing. It was fixed in 4.23 but I think it came back in 4.24. Is this a known bug?

The other issue is that, WMR controller models in the game are showing up as index controllers and both the left controller only.

![image](https://user-images.githubusercontent.com/50789023/79177987-a1857d00-7dc9-11ea-9072-5c111b5404d9.png)

**Comment by 1runeberg** [comment]
Hi @pixelcitystudio, 

**Re: Material missing in builds**
As per the ticket you opened in the UE Plugin repo - this should be better answered by Epic Games as the MotionControllerComponent and its Display Device Model feature is developed and maintained by them:

https://answers.unrealengine.com/questions/234597/screenspace-portals-on-vr.html

From the OpenVR side, the Index controller render models and materials can also be manually imported in your project from here:
{X}:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\indexcontroller\resources\rendermodels

Re: WinMR
I just tested with 4.24 using both the latest SteamVR Beta and the stable SteamVR1.10.32 and the WinMR models appear to be rendering correctly using the vanilla Epic VR template:
![image](https://user-images.githubusercontent.com/17371351/79184745-62ead380-7e58-11ea-8633-327fdafb4b79.png)

you may want to double check that you have the WinMR driver properly installed in Steam though. As mentioned above, the implementation for UE4's default "Display Device Model" feature though is done by Epic, and they should be able to address these questions better as we didn't do this part of the implementation in the engine.

Cheers,
Rune

**Comment by pixelcitystudio** [comment]
I reported this as a bug with Epic as well. I thought maybe this is a better place to report this but may be not.

As for the WMR controller issue goes... can you test this in a packaged game instead of in editor?

**Comment by 1runeberg** [comment]
WinMR Render Models on my end are rendering properly in a build, the M_DefaultDevice material however isn't packaged automatically/properly - so this is something you'd have to raise directly with Epic as this is part of the engine implementation and not OpenVR's.

**Comment by 1runeberg** [comment]
I've poked the Epic XR Team directly  as well.

**Comment by 1runeberg** [comment]
I've poked the Epic XR Team directly as well, but it's always better to get as many direct developer feedback via their normal channels.

**Comment by pixelcitystudio** [comment]
Thank you!
For the wmr issue, do you think it may be because I do not see WMR here as an option at all? The controls for wmr worked though
![image](https://user-images.githubusercontent.com/50789023/79283455-87a57200-7e7d-11ea-9440-dbea5ed1275b.png)

**Comment by pixelcitystudio** [comment]
The WMR seems to be a non-issue now. It is just the textures and I will work with epic on it.

**Comment by pixelcitystudio** [comment]
@1runeberg any update on this?

**Comment by 1runeberg** [comment]
> @1runeberg any update on this?

Sorry I haven't received any info, but this an Epic issue so its best to contact them directly :)

**Comment by pixelcitystudio** [comment]
Ok thanks for the update.

Quick question regarding the render models.... where can I find the render model for WMR controller? And I can't find materials for any of the controllers either in the steamvr directory

I dont see it here:

![image](https://user-images.githubusercontent.com/50789023/83701223-9df2c300-a5ce-11ea-8e8b-22e3e1c9a271.png)

**Comment by 1runeberg** [comment]
> @1runeberg Ok thanks for the update.
> 
> Quick question regarding the render models.... where can I find the render model for WMR controller? And I can't find materials for any of the controllers either in the steamvr directory
> 
> I dont see it here:
> 
> ![image](https://user-images.githubusercontent.com/50789023/83701223-9df2c300-a5ce-11ea-8e8b-22e3e1c9a271.png)

It would've been installed with the Windows Mixed Reality Driver.

Typically it'll be in your appdata:
{drive}:\Users\{username}\AppData\Local\Microsoft\Windows\OpenVR

**Comment by pixelcitystudio** [comment]
@1runeberg Ok thanks, what about the materials for all these models?

**Comment by 1runeberg** [comment]
> @1runeberg Ok thanks, what about the materials for all these models?

are you not seeing them there?

**Comment by 1runeberg** [comment]
if you meant a UE Material, I dont think Microsoft distributes those, but UE should be able to import the obj material if you drag-and-drop the controller obj to the editor's content folder, in the **"... Uniform Scale"** option, set to **100**, "**Create New Material**" and click Import All, you should get something like this:

![image](https://user-images.githubusercontent.com/17371351/83715611-29bd2b80-a671-11ea-8bcf-61516274f3c0.png)

You might want to adjust/play around with import rotation as well.

**Comment by pixelcitystudio** [comment]
I see them... thank you!
