### ISSUE TITLE
Rename 64-bit openvr_api.dll/lib to openvr_api64.dll/lib

### ISSUE THREAD

**Issue by GregSlazinski** [ValveSoftware/openvr#136]
In case if I want to distribute 2 EXE in the same folder (one 32-bit, one 64-bit), I can't, because they both need openvr_api.dll which has the same name for 32-bit and 64-bit.

What I want to have is 2 game executables in the same folder:
Folder/Game 32.exe
Folder/Game 64.exe
Folder/openvr_api32.dll
Folder/openvr_api64.dll

With current naming system, I can't do that, because both 32/64 bit openvr_api.dll has the same name.

**Comment by cmbruns** [comment]
+1 this change would make things more convenient for pyopenvr python bindings where I'm already renaming the shared libraries:
https://github.com/cmbruns/pyopenvr/tree/master/src/openvr

**Comment by JoeLudwig** [comment]
See https://github.com/ValveSoftware/openvr/issues/92

**Comment by GregSlazinski** [comment]
Hi,

Yes I've already seen that, however I still think this should be changed.

Because I can't mix 32/64 bit exe's in one location.

If not can you at least provide static libraries? Because this is what I really want the most.
This would solve the DLL naming issue because I wouldn't need the DLL files.
https://github.com/ValveSoftware/openvr/issues/138

Thanks
