### ISSUE TITLE
1 out of 2, 2.0 base stations work

### ISSUE THREAD

**Issue by envi270** [ValveSoftware/openvr#1363]
Hi i got a oculus s with the vice trackers full body  with 2.0 base stations. both base station work fine on their own. but not together as steam vr doesn't detect it. if anyone could help me out here that would be great thanks :)

**Comment by JoeLudwig** [comment]
The SteamVR discussion forums on Steam are a better place for this kind of question: https://steamcommunity.com/app/250820/discussions/

The first thing I would check, though, would be that they are on different channels. You can see what channel they are on in the SteamVR system report.

**Comment by envi270** [comment]
Thanks for the reply, the problem I had was not knowing how to change the
channel. I had to use a pin at the back to change it. This fixed the
problem.
