### ISSUE TITLE
Wrong FoV degrees reported for Index HMD by GetFloatTrackedDeviceProperty()

### ISSUE THREAD

**Issue by Raivr-dev** [ValveSoftware/openvr#1375]
OpenVR reports a field of view of 70 degrees for the Index HMD, both horizontal and vertical.
For a Vive and a VivePro it reports 85 degrees Field of View, both horizontal and vertical. That seems right.

Why does it report such a low number for the Index?
Is there a better way to get the Field of View of an HMD?

Currently, I'm using:

`GetFloatTrackedDeviceProperty(vr::k_unTrackedDeviceIndex_Hmd, vr::Prop_ScreenshotHorizontalFieldOfViewDegrees_Float, &err);
`

I know there's the word "Screenshot" in the property name but I didn't find anything else to get a FoV.

**Comment by Raivr-dev** [comment]
To answer my own question, use:

`GetProjectionRaw( EVREye eEye, float *pfLeft, float *pfRight, float *pfTop, float *pfBottom )`

**Comment by BOLL7708** [comment]
Oh yeah, the screenshot FoV is something I use in one of my applications, it's the size of the biggest square that can be fit inside the intersecting parts of the headset's field of view 😅 I'll take a look at the values you found though as that is also interesting... 😗

**Comment by Raivr-dev** [comment]
Ah, OK, so that's what `Prop_ScreenshotHorizontalFieldOfViewDegrees_Float `is for.

The `GetProjectionRaw()` gets you the tangents of the mentioned angles. Convert to degrees and add the left value of the left eye to the right value of the right eye. That gets you the horizontal projection FoV of the HMD. Not all of that FoV is visible to the user though.
