### ISSUE TITLE
Provide static libraries without the need for DLL files

### ISSUE THREAD

**Issue by GregSlazinski** [ValveSoftware/openvr#138]
I like to distribute my apps without the swarm of DLL files.
To have a folder with like 20 DLL files that's super messy, I've seen other games do it.
So I always compile 3rd party libs that I use as static LIB files, and link them to EXE, and there's no need for other files. But OpenVR does not have source code included, so it's not an option.

Also sometimes it's desirable to distribute just a single EXE to other people, for example to download one EXE file from a website, as installer, and run it straight away.
If I'd like to include some VR rendering in that installer, then I can't do because no DLL.

Please provide static LIB option without the DLL.

Thanks

**Comment by stfairy** [comment]
I believe it's much more important to provide source code, so people can do whatever they want, so it becomes really "open".

**Comment by jherico** [comment]
Providing static libraries isn't trivial.  It would mean they'd have to provide number different static libraries for various compilers, c-runtimes, multi-threaded vs single threaded, and if you need to build in debug mode, they have to include a bunch of debug runtimes as well.  In lieu of a cmake buildable source distribution, a DLL makes the most sense.

**Comment by GregSlazinski** [comment]
Hi,

There's no need for varoius compilers :
Windows uses Microsoft Visual Studio, latest version is recommended, so VS 2015
Mac uses Xcode
Linux uses GCC

I don't see the point of single threaded, so multi-threaded of course.

On Windows "Runtime - Multi-Threaded (/MT)" is just great

I don't have any need for debug libraries, I need them for release applications.

DLL's have this problem so I can't work with that:
https://github.com/ValveSoftware/openvr/issues/136

**Comment by jherico** [comment]
@GregSlazinski so you don't want Valve to provide static libraries in general, just static libraries *for you*.  My company builds with VS 2013, we use Multi-Threaded DLL linking, and we need to be able to build and run our application in debug mode, you know, for development.

And there are simple ways you could work work around #136 without Valve renaming the DLLs.

**Comment by GregSlazinski** [comment]
You can run apps in debug mode, when linking with other libs that are compiled in release mode.
At least I can do that with "Runtime - Multi-Threaded (/MT)"

I always stay up to date with technology, so I don't see any point with sticking with VS 2013 when you can use the latest version, and still be able to create apps for WinXP.

> And there are simple ways you could work work around #136 without Valve renaming the DLLs.
Sorry I'm not aware of a solution to the problem.

**Comment by jherico** [comment]
> You can run apps in debug mode, when linking with other libs that are compiled in release mode.

Yeah, good luck with that.  Even if it compiles and links, it's a recipe for disaster, because the memory allocation and deallocation routines are different.  The only way that's safe is if you're certain that nothing allocated in the library is ever released in the app, or vice versa.

> I always stay up to date with technology, so I don't see any point with sticking with VS 2013

It doesn't matter what *you* do, it just matters that VS 2013 is still widely used.  The Oculus SDK, which comes with static libraries, goes all the way back to VS 2010, and with 32/64 bit that's 8 different static libraries.  People still complain.

> Sorry I'm not aware of a solution to the problem.

Wrap the code that uses the OpenVR API in your own DLL, which loads from a different directory depending on whether it's 64 or 32 bit.  Then put the corresponding OpenVR dll in the directory with each version of the plugin.  Or wrap your whole app into a launcher executable which is just a stub that launches a 64 bit or 32 bit executable depending on the environment.

**Comment by GregSlazinski** [comment]
> Wrap the code that uses the OpenVR API in your own DLL, which loads from a different directory depending on whether it's 64 or 32 bit. Then put the corresponding OpenVR dll in the directory with each version of the plugin. Or wrap your whole app into a launcher executable which is just a stub that launches a 64 bit or 32 bit executable depending on the environment.

Thanks for the ideas, however I strongly believe that instead of creating even more complex solutions to workaround existing problems. The problems should be fixed at the root, then there's no need for workarounds in the first place.

There is a simple solution to people using old VS (2010, 2013) -> update to latest version.
Sorry I don't want to change the point of this thread into a different discussion.

I kindly ask Valve to provide static libraries.

Thank you very much.

**Comment by JoeLudwig** [comment]
We don't have a single project at Valve that's upgraded to VS 2015 yet. Usually we're a version back. It just takes a while to get hundred of people and hundreds of projects updated. That means we'd have internal customers that need 2013 and probably external customers on 2012 and 2010. (Fortunately I think we can safely ignore 2008. :)

The SDK used static libs for a time early in its life and it was a huge pain for all the reasons @jherico mentioned. DLLs allow us to hide all the dependencies. We're not going back to the bad old days.

Fortunately there are several workarounds for you to use, including the ones above. Another option would be to drop your 32-bit binary. 32 bit versions of Windows aren't supported by SteamVR in any case, so everybody will be able to use your 64 bit binaries.

**Comment by GregSlazinski** [comment]
Thank you for the reply.

In that case I think the best solution would be to provide source code, so people can compile for any configuration they need.

However I have a feeling that's not going to happen.

**Comment by TheWhiteAmbit** [comment]
You can compile different platform targets in one and the same VS, as long as you have the compilers installed. Greg, do not worry about jherico, he is in any VR discussion and he always knows the distributors do it absolutely correct without the chance of failing - whatever they would do - always. For him only "developers holding iPhones wrong" exist, in no way any improvements can be made to OpenVR or LibIVR. Most funny thing about it, a few months ago he did not even know what OpenVR is at all, an now he already is an expert on it. If providing a Debug-Release of a Static-Library is such a huge problem (seen enough *d.libs in my live to proove it is no problem) - then just leave the Debug-Libs away. This would not be worse than DLLs without Debug-Info. I could argue against each and everything he keeps praying to people, but I am so sick of him killing discussions by "you are holding it worng"...

**Comment by aardappel** [comment]
> Wrap the code that uses the OpenVR API in your own DLL, which loads from a different directory depending on whether it's 64 or 32 bit. Then put the corresponding OpenVR dll in the directory with each version of the plugin. Or wrap your whole app into a launcher executable which is just a stub that launches a 64 bit or 32 bit executable depending on the environment.

Really? I need to do all that just to be able to have my app potentially run in VR mode? All that to save Valve the trouble of running a build server to output 8 or so static libs that everyone can benefit from? Please, give us static libs, or if that is really too much work, source.

**Comment by GregSlazinski** [comment]
Please provide static libs. 
Thank you

**Comment by GregSlazinski** [comment]
Using static libraries has several benefits:
-Application starts faster, because the OS doesn't need to perform a file search for the DLL
-Application starts faster, because the OS doesn't need to dynamically link the DLL file with the application code at runtime
-Application can be distributed as a standalone EXE without the need of any extra files
-Application size will be smaller, because when you use static library, then only used functions/codes are linked into the EXE (unused stuff is ignored), but with the DLL you're forced to include all unused data
-There's no risk of someone replacing the DLL file with another (possibly malformed version)
-possibly more which I haven't thought of

**Comment by aardappel** [comment]
More importantly, why not just give developers the choice? The convenience for Valve to not have to deal with running a few more builds doesn't seem to stack up against the many developers and even more users it potentially affects.
