### ISSUE TITLE
Any way to check if HTC VIVE device is tracked by both optical and inertial tracking system or only by inertial? 

### ISSUE THREAD

**Issue by jakubmazu** [ValveSoftware/openvr#1380]
Hello,
as in title.
I need to know if measure of position of device (tracker, controller) was done when it was tracked by optical system, because when it is measures are more precise.
Greetings

**Comment by Raivr-dev** [comment]
Take a look at `struct TrackedDevicePose_t` in openvr.h.
When optical data and IMU data is valid you'll have `TrackingResult_Running_OK` and `bPoseIsValid` true.
If you throw a towel over the controller (no optical tracking, only IMU), you'll have `TrackingResult_Calibrating_OutOfRange` and `bPoseIsValid` still true.
A second or two later `bPoseIsValid` goes false.

**Comment by jakubmazu** [comment]
Thank You for comment it's very useful!

**Comment by HsunhuiLin** [comment]
Hi, I came across this issue and because the positional data of our tracking device would start drifting during that one or two seconds. Is there possibly any way to detect that?
