### ISSUE TITLE
IVROverlay::ShowMessageOverlay() only returns VRMessageOverlayResponse_CouldntFindSystemOverlay

### ISSUE THREAD

**Issue by elvissteinjr** [ValveSoftware/openvr#1383]
I only use this function to display error dialogs so I hadn't been looking at it recently.
It did work mid-April and the same code just returns immediately with VRMessageOverlayResponse_CouldntFindSystemOverlay in the current stable (1.11.12) or beta (1.12.5) build of SteamVR.

It's not the end of all, but I found this function pretty convenient so it would be great if this could be fixed.

**Comment by JoeLudwig** [comment]
This is fixed in 1.14.10.
