### ISSUE TITLE
How to Get HMD Screen Resolution

### ISSUE THREAD

**Issue by GregSlazinski** [ValveSoftware/openvr#139]
How to Get HMD Screen Resolution?

I've found only this: 'GetRecommendedRenderTargetSize'
however it returns the size already adjusted by the scale factor.

I want to know the native resolution of the HMD display.

Thanks

**Comment by JoeLudwig** [comment]
You can use the IVRExtendedDisplay interface to get the geometry of the actual display.

What are you going to use it for?

**Comment by GregSlazinski** [comment]
That's what I tried to do

```
   if(vr::IVRExtendedDisplay *d=vr::VRExtendedDisplay())
   {
      int32_t x=0, y=0; uint32_t w=0, h=0; d->GetWindowBounds(&x, &y, &w, &h);
      VR._res.set(w, h);
   }else VR._res.zero();
```

However the problem is that vr::VRExtendedDisplay() returns null, but sometimes it worked before.

I want to display the resolution as debug info / statistics to the user.

**Comment by JoeLudwig** [comment]
The IVRExtendedDisplay is only available if the compositor isn't running. If you start SteamVR from Steam it will start the compositor automatically and that interface won't be available. I'll look into removing that restriction in a future update.

**Comment by GregSlazinski** [comment]
Thanks, that would be great.

**Comment by stfairy** [comment]
is it faster to run with or without the compositor?
