### ISSUE TITLE
OpenVR Controller Only Driver

### ISSUE THREAD

**Issue by DaylightNebula** [ValveSoftware/openvr#1398]
Hi,

I am working on VR controllers.  Essentially I want to have a driver that acts as controllers with an external driver handling the HMD.  My attempts at executing this have not been successful.  I have tried building a driver from the ground up, and also remove the HMD from a know good driver.  How should I approach writing a "controller only" driver?

**Comment by JoeLudwig** [comment]
This is essentially what the gamepad driver does. It does the by including the following in its driver.vrdrivermanifest file:
```
    "alwaysActivate": true
```

That tells SteamVR to activate the driver (and its devices) in addition to the HMD.

**Comment by DaylightNebula** [comment]
It worked, thank you!
