### ISSUE TITLE
GetDXGIOutputInfo always returns -1

### ISSUE THREAD

**Issue by GregSlazinski** [ValveSoftware/openvr#140]
https://github.com/ValveSoftware/openvr/wiki/IVRSystem::GetDXGIOutputInfo

Just wanted to report this is is always returning -1 even though OpenVR works fine, and I can connect and render everything OK.
My setup:
Laptop with GeForce 650m GT + Intel HD 4000
DirectX 11
Windows 10
Latest Nvidia GPU drivers
Oculus DK1
Oculus Runtime 0.8
Latest OpenVR

Also the C++ headers say:
```
	/** If an error occurs both indices will be set to -1.
	*/
	virtual void GetDXGIOutputInfo( int32_t *pnAdapterIndex ) = 0;
```

"both indices" however there's just one index, not two.

I call this like that:
```
      vr::EVRInitError error; if(_vr=vr::VR_Init(&error, vr::VRApplication_Scene))
      {
         if(_compositor=vr::VRCompositor())
         {
             int32_t adapter_index=-1; _vr->GetDXGIOutputInfo(&adapter_index);
```

**Comment by LibreVR** [comment]
> "both indices" however there's just one index, not two.

That's a remnant of an older revision of that function. You can still see the original function signature [on the wiki](https://github.com/ValveSoftware/openvr/wiki/IVRExtendedDisplay::GetDXGIOutputInfo).

**Comment by JoeLudwig** [comment]
I fixed this comment. It will ship in an SDK update a month or so from now.

	/** [D3D10/11 Only]
	* Returns the adapter index that the user should pass into EnumAdapters to create the device 
	* and swap chain in DX10 and DX11. If an error occurs the index will be set to -1. The index will 
	* also be -1 if the headset is in direct mode on the driver side instead of using the compositor's
	* builtin direct mode support.
	*/

(In your case the way that Oculus's direct mode works prevents this function from returning an index.)
