### ISSUE TITLE
Suppress logging from SteamVR infrastructure when launching application with vrenv.sh

### ISSUE THREAD

**Issue by mcourteaux** [ValveSoftware/openvr#1402]
I am on Linux, and I run my OpenVR-enabled application using the `vrenv.sh`:

```sh
~/.local/share/Steam/steamapps/common/SteamVR/bin/vrenv.sh ./myapp
```
Which works great; however, the console gets spammed with all sorts of logging messages from SteamVR software running in separate processes (like `vrdashboard`, `vrcompositor`, `vrserver`, `vrmonitor`), which got spawned upon `vr::VR_Init()`. Is there a way to surpress those, or run this "server-side infrastructure" of the SteamVR software in another terminal (such that the terminal that I'm actually using gets no spam)?

The logging even continues after my application has quit, which makes the terminal very hard to use as output keeps disturbing me trying to type in new commands.

**Comment by lostgoat** [comment]
> (like vrdashboard, vrcompositor, vrserver, vrmonitor), which got spawned upon vr::VR_Init().

`vr::VR_Init()` will launch these processes if they aren't currently running. Therefore, an alternative approach would be to launch these apps in a separate terminal before launching your app.

Try opening a separate terminal and running `bin/vrstartup.sh`

**Comment by mcourteaux** [comment]
That indeed clears out most of the clutter. Very helpful thank you!

I still get a list of shaders being loaded in the output of my application. But if that's all, I'm completely fine with it!
```
shaders/vulkan/distort_vs.spv
shaders/vulkan/distort_vs_layered.spv
shaders/vulkan/distort_vs_nd.spv
shaders/vulkan/distort_vs_latest_nd.spv
shaders/vulkan/distort_vs_layered_nd.spv
shaders/vulkan/distort_vs_reproject.spv
shaders/vulkan/distort_vs_reproject_nd.spv
shaders/vulkan/distort_vs_reproject_mv.spv
shaders/vulkan/distort_geom_vs.spv
shaders/vulkan/distort_geom_curved_vs.spv
shaders/vulkan/distort_geom_uvs_embedded_vs.spv
shaders/vulkan/distort_geom_curved_uvs_embedded_vs.spv
shaders/vulkan/distort_geom_ptnorm_vs.spv
shaders/vulkan/distort_geom_ptnorm_curved_vs.spv
shaders/vulkan/distort_geom_ptnorm_uvs_embedded_vs.spv
shaders/vulkan/distort_geom_ptnorm_curved_uvs_embedded_vs.spv
shaders/vulkan/distort_geom_fresnel_vs.spv
shaders/vulkan/distort_geom_vignette_vs.spv
shaders/vulkan/distort_geom_aa_lines_vs.spv
shaders/vulkan/distort_geom_aa_circles_vs.spv
shaders/vulkan/distort_geom_hard_bounds_aa_lines_vs.spv
shaders/vulkan/distort_geom_hard_bounds_aa_squares_vs.spv
shaders/vulkan/distort_geom_aa_quads_vs.spv
....
```
