### ISSUE TITLE
Using vive tracker without HMD

### ISSUE THREAD

**Issue by 0xDEADBEFF** [ValveSoftware/openvr#1403]
I am trying to set up tracking using one HTC VIVE base station (1.0) in mode A and one HTC tracker (2.0). 
OS Ubuntu 18.04.4 TLS, GeForce RTX 2060, steamvr beta 1.13.8

I followed [triadsemi](http://help.triadsemi.com/en/articles/836917-steamvr-tracking-without-an-hmd) tutorial on using the null driver. Unfortunately, it doesn't work and I am getting None as tracker position. 

Have anyone faced this issue? Would creating my own driver based on driver_sample help? 
Could anyone comment on how to make a virtual driver to track the position of the VIVE tracker?

![Screenshot from 2020-07-02 12-57-25](https://user-images.githubusercontent.com/66426207/86782450-bccdf480-c067-11ea-9b07-03d83e99889a.png)

**Comment by TheDeveloperGuy** [comment]
There's no easy/elegant way to do this, although there is always a way. In order to do this in my driver, I made a 'hook' driver to catch device activation requests, and changed the type of the tracker to a tracking reference (to avoid SteamVR trying to do anything with the tracker). The 'hook' driver then intercepts the pose updates from the tracker and sends them to the headset driver to use as a pose, which it then submits itself. This is on Windows, I don't know how one would go about making a 'hook' driver on Linux, or whether it's even possible.

Hopefully, some time before the heat death of the universe, Valve will make a more elegant way to achieve this.

**Comment by 0xDEADBEFF** [comment]
Thanks, @TheDeveloperGuy !

I am not sure how to make the 'hook' driver interact with the original tracker's driver. Do I need to replace it?
Is the pose submitted as the pose of the headset or pose of the tracker? 
Would it be possible to extend your solution to use multiple trackers/controllers? 

Could you please share your project or some key points?

**Comment by TheDeveloperGuy** [comment]
Suggest you read up on what a 'hook' driver is, as your questions indicate you don't know. You definitely can't replace the Lighthouse driver, as it's used for many things, and doing anything other than what I've described will at best stop any and all Valve devices from working and at worst crash SteamVR. Hooking the 'lighthouse' driver is about as 'hostile' a thing as you can do on SteamVR, and so it's not a recommended route if you can avoid it. You've managed to pick out about the one single use case where there is (as far as I know) no other way to achieve what you want (hint hint, Valve developers!).

Not sure why you'd want to use multiple trackers to track a single headset, if your question is can other trackers and controllers work while I'm taking the poses from a single tracker and diverting them to the headset driver, then the answer is yes. My driver is closed source and part of a commercial product, so can't share much more than what I have (which is enough, once you've re-read my comment a few times and filled in the blanks with your own research). In any case it would be of almost zero value to you as it's Windows based and you're working on Linux. 

This is definitely very much in the "advanced" category of SteamVR driver development, so it's quite likely you will need to do quite a lot more SteamVR driver development before you're even able to fully understand what needs to be done. Unfortunately bashing one's head against the wall (metaphorically speaking) for months/years is about the only way to get the necessary knowledge. Valve engineers will answer some of your questions, once you can demonstrate enough knowledge in your question to be able to glean anything from a one or two line answer. However they will avoid driver hooking topics, as it's definitely deep in "not recommended/sanctioned by Valve" territory.

**Comment by TheDeveloperGuy** [comment]
An easier, less elegant way to achieve this, is to develop a separate process, that runs in SteamVR "client" space and communicates the poses from the tracker to your headset driver. That will work, except you'll get the tracker showing up in SteamVR as a tracker (as you have already), and being stuck to your face in some applications. The 'hook' driver is only necessary if you don't want SteamVR to see the tracker as a tracker.

**Comment by JoeLudwig** [comment]
Can you describe what you're trying to do in more detail? Why do you need the tracker poses in a driver (as opposed to an application)?

**Comment by TheDeveloperGuy** [comment]
@JoeLudwig For my driver (and how I read the OP's UC) it's to use a tracker to track the headset in a Lighthouse setup where the headset doesn't have Lighthouse tracking.

**Comment by JoeLudwig** [comment]
Same story for you, 0xDEADBEFF ?

**Comment by 0xDEADBEFF** [comment]
Hi @JoeLudwig. It is not exactly the same. 

I want to use the tracker to track the orientation of a [robot](https://sites.google.com/view/roboticsbenchmarks/).
I access the orientation of the tracker at the application level using pyopenvr lib. 

I want to set up tracking using only Lighthouse base station and tracker without **any** physical headset.
To run the steamvr I need to emulate the headset and make everything connected. 
I tried to do so by setting "activateMultipleDrivers" = true and enabling the null driver but it doesn't work. 
I assume that writing my own driver could help.

Sorry for a not clear statement.  Could you suggest how to achieve that?

**Comment by JoeLudwig** [comment]
@0xDEADBEFF 
You should be able to leave the null driver disabled and set "requireHmd" to false in the "steamvr" section of your settings file. No driver should be necessary for that.

**Comment by 0xDEADBEFF** [comment]
@JoeLudwig 
I tried to do that and got the message "The base station is not currently tracking any devices. Make sure it is in view of your headset". That's why I assumed that I need a headset. 
Could you please suggest how to deal with it? 

![2020-07-08_16-25-44](https://user-images.githubusercontent.com/66426207/86924349-038b1f80-c138-11ea-97a8-3971d463c5c6.png)

![8EDF3E00-FC84-412E-A10A-275D3215FFFC](https://user-images.githubusercontent.com/66426207/86924570-51078c80-c138-11ea-93f9-96a2c2fe953e.jpg)

**Comment by JoeLudwig** [comment]
I happen to have two base station 2.0s, but they're both tracking with requireHmd=false, a single Vive Tracker, and no HMD plugged in. More or less exactly your setup, except with base 2.0s.

![image](https://user-images.githubusercontent.com/303656/86978922-dbe68800-c134-11ea-8186-a4484dc8c9f0.png)

Does that tracker track if there's an HMD plugged in, but it's occluded from the base station under a box, desk, etc.?

**Comment by JoeLudwig** [comment]
You are **very** close to that base with your tracker. Does it work if you move it a meter or more away?

**Comment by JoeLudwig** [comment]
Can you post the entire system report? The log files may be illuminating.

**Comment by JoeLudwig** [comment]
One more suggestion: Go into the Manage Vive Trackers UI and set the role on that tracker to something. Mine is set to Held in Hand, but pretty much anything would probably help. This won't affect the way the tracking works, but might affect the way it's reported in the API.
![image](https://user-images.githubusercontent.com/303656/86979328-dfc6da00-c135-11ea-9efc-1a874f701ac8.png)

**Comment by 0xDEADBEFF** [comment]
@JoeLudwig sorry for the long reply I was away from my PC

This is the row logs https://gist.github.com/0xDEADBEFF/0da40b4277a77fb5ff1c2ed3b324b929

**Comment by 0xDEADBEFF** [comment]
Also in the web console I see such messages:

```
Mon Jul 20 2020 13:41:19.839791 - [Status Alert] Invalid Entry: (System: -101/0 1) (Button: -101/0)
Mon Jul 20 2020 13:41:19.842775 - [Status Alert] VRInitError_None_Header (-101)
```

**Comment by 0xDEADBEFF** [comment]
Also my Devices -> Manage Vive trackers looks empty 
I hope very much that this would help to figure out the issue

![Screenshot from 2020-07-20 13-57-00](https://user-images.githubusercontent.com/66426207/87930674-29e28080-ca91-11ea-9c1d-dc88e31905b8.png)

**Comment by 0xDEADBEFF** [comment]
The same issue exists on Windows. 
I also noticed that I can not connect to my BS using Bluetooth. 
I can connect to it using PC settings but it is not recognized by the SteamVR.

**Comment by 0xDEADBEFF** [comment]
> You are **very** close to that base with your tracker. Does it work if you move it a meter or more away?

Finally, I figured it out. If I move the base station 2 meters away from the tracker everything works! 
Thanks!
