### ISSUE TITLE
SetOverlayTexture does not work with OpenGL texture

### ISSUE THREAD

**Issue by jangxx** [ValveSoftware/openvr#1408]
I've been trying to get a normal OpenGL texture to display as an overlay for several days now, but it simply doesn't work without generating any errors. My code basically boils down to this:

```c++
GLuint testTexture;
glGenTextures(1, &testTexture);
glBindTexture(GL_TEXTURE_2D, testTexture);

glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA8, width, height, 0, GL_RGBA, GL_UNSIGNED_BYTE, pixelData); // pixelData is just some gradients
glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);

// .. other stuff ..

vr::VROverlay()->SetOverlayTexture(overlayHandle, &testTexture);
```

but the overlay is never visible. None of the calls return an error and the logfile contains a line like `Created shared texture 'Scene create OpenGL, -1 3811550060' 512x512 (1 mips)` which seems to indicate success to me.
If I replace the call to `SetOverlayTexture` with a call to `SetOverlayFromFile`, it works great, so there doesn't seem to be anything wrong  with my calls to the OpenVR APIs. I'm really at a loss at this point, especially since there don't seem to be any examples or tutorials which use `SetOverlayTexture` with anything but a framebuffer texture created by Qt. I'm only using GLFW and GLEW and there's really no reason to bloat my project with a bunch of Qt stuff I don't need. I'm on Windows 10 with a NVIDIA graphics card, so none of the reported AMD problems should be relevant to my problems either.

Are there any special flags I need to set in my OpenGL context or something, or is the support for OpenGL textures just broken at the moment? Or maybe I've overlooking something obvious?

**Comment by ChristophHaag** [comment]
You want to use OpenVR's wrapper struct for textures:
```c
Texture_t tex;
tex.handle = (void*)(uintptr_t) texture;
tex.eColorSpace = ColorSpace_Auto;
tex.eType = TextureType_OpenGL;
VROverlay()->SetOverlayTexture(handle, &tex);
```

Here's some older example code for linux I had around: https://gist.github.com/ChristophHaag/474c77f48fbddcb2b3ea0c67bf578d8f

**Comment by jangxx** [comment]
Huh, I guess that's what I get for trying to post something coherent at like 3 am. I forgot to mention that I was already using the wrapper of course, otherwise the code wouldn't compile after all. I initially didn't want to do this, but here is my complete "minimal" example which demonstrates my problem: https://gist.github.com/jangxx/97bf429e762573378912d16577c05424

Comparing it to your code (thanks a lot for that, btw!), I see two things that are jumping out to me as different; You are casting the `GLuint` to a void pointer (`tex.handle = (void*)(uintptr_t) texture;`) and you are calling `glFinish();` before setting the overlay texture. Maybe if I do the same it would finally work, but I'll have to try it for myself this evening.

**Comment by ChristophHaag** [comment]
Yea

> TextureType_OpenGL = 1,  // Handle is an OpenGL texture name or an OpenGL render buffer name, depending on submit flags

means you use the actual texture id as the handle, not a pointer to it. That requires an ugly cast like the above not to get type warnings from the compiler (Or use static_cast in c++).

**Comment by jangxx** [comment]
I tried to cast the `GLuint` into a void pointer and it worked perfectly! Thanks a lot!
