### ISSUE TITLE
BUG/BREAKING CHANGE: Textures passed to Present() method of IVRVirtualDisplay are not valid

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#1409]
In the 1.13.x versions of SteamVR, the textures passed to IVRVirtualDisplay::Present() aren't able to be used for anything (CopyResource, CreateShaderResourceView), error is E_INVALIDARG (0x80070057). Drivers are built with v1.12.x OpenVR SDK and don't have this issue on 1.12.x versions of SteamVR (fortunately have an older version handy to verify against). This behaviour happens on latest version and previous version of Windows 10, as well as latest and older versions of GPU drivers. 

What changed, how do I fix this? Major issue for me as I have a commercial driver (and a client with a commercial driver) that uses this driver interface.

**Comment by TheDeveloperGuy** [comment]
Previously textures passed to Present() were of format DXGI_FORMAT_R8G8B8A8_UNORM, now they are of format DXGI_FORMAT_R8G8B8A8_TYPELESS. Why is this? Is it a bug? Previously the driver just used the same texture format as the texture it was given, now it has to do some kind of conversion before it can use the texture. @JoeLudwig please clarify.

**Comment by TheDeveloperGuy** [comment]
Needless to say, but this further breaks the already broken https://github.com/ValveSoftware/virtual_display sample...

**Comment by TheDeveloperGuy** [comment]
This is a really *bad* change. Is the driver now supposed to assume texture formats coming from SteamVR? Can it assume R8G8B8A8 texture formats? How, exactly, is the driver supposed to handle typeless texture formats?

**Comment by JoeLudwig** [comment]
We changed all the internal textures used in SteamVR to typeless to make them more flexible to work with. We're going to switch the textures handed to virtual display drivers back to their concrete types to roll back that part of this change.

In the meantime, when working with typeless formats, you need to specify the concrete format for reading/writing. For instance, you can create a ShaderResourceView of format DXGI_FORMAT_R8G8B8A8_UNORM on an underlying texture resource of format DXGI_FORMAT_R8G8B8A8_TYPELESS. You can also make a Shader resource view of format DXGI_FORMAT_R8G8B8A8_UNORM_SRGB on the same underlying if you want the output colors in SRGB space.

**Comment by TheDeveloperGuy** [comment]
Yeah, that's what I did. I'm only converting DXGI_FORMAT_R8G8B8A8_TYPELESS formats at the moment, because I didn't want to put a massive switch in for every possible TYPELESS texture format. Is there a possibility that SteamVR will provide non-R8G8B8A8 texture formats, as I don't want to wake up on a Sunday with multiple users reporting a broken driver again?

**Comment by JoeLudwig** [comment]
I definitely encourage you (and all developers) to use the beta so you get advanced warning of coming changes before they hit most users.

We are switching back to the typed formats in 1.14. We don't currently have any plans to switch to larger than 32 bit formats.

Here's the switch statement we use to upgrade a typeless format:
```
DXGI_FORMAT PromoteTypelessForShaderIfNecessary( DXGI_FORMAT format, EColorSpace eColorSpace )
{
	switch ( format )
	{
	case DXGI_FORMAT_R32G32B32A32_TYPELESS:
		return DXGI_FORMAT_R32G32B32A32_FLOAT;
	case DXGI_FORMAT_R32G32B32_TYPELESS:
		return DXGI_FORMAT_R32G32B32_FLOAT;
	case DXGI_FORMAT_R16G16B16A16_TYPELESS:
		return DXGI_FORMAT_R16G16B16A16_FLOAT;
	case DXGI_FORMAT_R10G10B10A2_TYPELESS:
		return DXGI_FORMAT_R10G10B10A2_UNORM;

	case DXGI_FORMAT_R24G8_TYPELESS:
		return DXGI_FORMAT_R24_UNORM_X8_TYPELESS;
	case DXGI_FORMAT_R32G8X24_TYPELESS:
		return DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS;

	case DXGI_FORMAT_R8G8B8A8_TYPELESS:
		return (eColorSpace == ColorSpace_Linear) ? DXGI_FORMAT_R8G8B8A8_UNORM : DXGI_FORMAT_R8G8B8A8_UNORM_SRGB;
	case DXGI_FORMAT_B8G8R8A8_TYPELESS:
		return (eColorSpace == ColorSpace_Linear) ? DXGI_FORMAT_B8G8R8A8_UNORM : DXGI_FORMAT_B8G8R8A8_UNORM_SRGB;
	}

	return format;
}
```

**Comment by TheDeveloperGuy** [comment]
@JoeLudwig Thanks, generally do, will make a point of doing it.
