### ISSUE TITLE
BUG:  vr::VROverlay()->ShowMessageOverlay() doesn't work any more

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#1411]
So, when I originally tested my software (a SteamVR client, not a driver), I used this function and it worked just fine. Now it doesn't do anything at all. It appears to not work with either SteamVR 1.12.x or 1.13.x, whether or not the dashboard is visible when it is called. How I'd like it to work (and how it worked previously), is I call it, it shows a message overlay, whether or not the dashboard is visible.

What happened?

**Comment by TheDeveloperGuy** [comment]
@JoeLudwig Please assign this to someone. I'd like to avoid having to invent my own wheel, and would prefer to use the SteamVR one. Thanks.

**Comment by elvissteinjr** [comment]
I'd like to second this once again, as a I did in #1383 already.

The reason for it breaking is that SteamVR no longer creates the system.messageoverlay overlay, so ShowMessageOverlay() just returns _VRMessageOverlayResponse_CouldntFindSystemOverlay_. 
I have not checked what it does if some other application were to create an overlay with that key and allow the compositor or vrwebhelper to render to it. Wouldn't be a solution if that worked anyways.

In general I'm not sure if it's worth hoping to get this fixed. SteamVR gets updates, but doesn't really seem like anyone from Valve is reading the issue tracker anymore. Steam forums bug report section is slightly less abandoned, but it's flooded with end user reports my last attempts there weren't that fruitful either.

I guess that's not the kind of response you wanted to get notified for after all that time. Sorry about that.

**Comment by JoeLudwig** [comment]
Closing as a dup of #1383

**Comment by TheDeveloperGuy** [comment]
Well, I guess getting some response after 3 months (even if it is just to shut down bug reports) is progress... Seems Valve needs to up their game regards regression testing, instead of putting the responsibility on developers using their API.

**Comment by TheDeveloperGuy** [comment]
Can confirm it's working in latest release.
