### ISSUE TITLE
Feature request: Auto-launch of background applications

### ISSUE THREAD

**Issue by BOLL7708** [ValveSoftware/openvr#1424]
# Background
I've made a plethora of background applications over the years, mostly private but lately a number of [public](https://github.com/BOLL7708) ones as well. Considering this, it feels a bit lacking to not have the option to include background applications for automatic launching with SteamVR, which right now is possible for [overlay applications](https://user-images.githubusercontent.com/12276837/90338069-41a51a00-dfe7-11ea-8fe8-bd3fc1f29a02.png). I have previously made [a suggestion](https://steamcommunity.com/app/250820/discussions/4/3148519094651049732/) for this on the SteamVR forums.

# Suggestion
1. Let us register background applications for inclusion in a similar list to overlay applications.
2. For applications enabled for launching with SteamVR, only launch them if not already running.

Regarding 1, I imagine an API call where we can register the current executable, with or without a title, for inclusion in said list of toggleable background applications. I'm not sure how it currently works with overlay applications though, I imagine it is when registering a panel in the dashboard, but perhaps there are good hooks that would also work for background applications already.

Regarding 2, my own applications disconnect from SteamVR when it is quitting, letting the background application stay alive between boots of SteamVR, which background applications have no problem doing most of the time. Right now I pop a dialog that says only one instance can run at any one time, but I can remove this if SteamVR will launch it regardless, so it's not really a big problem.

In the end I just want me and my users to not have to launch these applications manually every session 😅 Sure I can set them to autorun with Windows, but seeing how the overlay applications can auto-launch with SteamVR makes me think it could be done in the same way.

**Comment by JoeLudwig** [comment]
This should already be supported. Make an "application manifest" for your background applications. There's not much documentation out there on those, but you can look in your <steam>/config/steamapps.vrmanifest file for an example. Set the background apps to be "overlay" apps in the manifest. That will put them in the UI.  This is what Steam does automatically for apps that have a SteamVR Overlay launch option.

There is a bunch of special handling for scene apps, but the other app types generally mean "not scene, but in this specific way", so it should be fine if the application API treats background and overlay apps the same.

**Comment by BOLL7708** [comment]
I've actually tried exactly this due to recommendations from other developers, I realize now though that it might have been while my manifest had the wrong encoding, which I noticed one of my applications still had, whoops #1382

Setting "is_dashboard_overlay" to true in the manifest did make my application pop up in the list, hurray! It also launches successfully with SteamVR 👍

I bumped into an issue though, which might be interesting. My applications have all been made so they gracefully disconnect from SteamVR when it quits, and reconnects when SteamVR is available again. This behavior is now preventing SteamVR from launching again if I don't close my applications manually in between.

1. Launch SteamVR with my app, close SteamVR but not my app, launch SteamVR again, it fails and pops [this dialog](https://user-images.githubusercontent.com/12276837/90435406-3cbb9580-e0cf-11ea-938b-f149a03418b1.png), repeatedly.
2. Launch my app manually, launch SteamVR, close SteamVR but not my app, launch SteamVR again, it will be successful.
3. Launch SteamVR with my app, close SteamVR and then my app, launch SteamVR again, it will be successful.

The easy solution would be to just have my application terminate when SteamVR closes, it's not always what I want though, and I'm not sure if this is expected behavior so I'm making a note here 😅 Might move it into a separate issue I guess.

I'm using SteamVR beta 1.14.6, [here](https://github.com/ValveSoftware/openvr/files/5086404/SteamVR-2020-08-17-PM_09_28_48.SteaVR.will.not.launch.if.auto-launched.app.is.still.running.txt) is the last system report after doing all this testing.

**Comment by JoeLudwig** [comment]
I assume that at the moment it's failing, if you look in the Steam UI, the Steam client still thinks that SteamVR is running.  Does it look like that to you?

Is there an actual pending SteamVR update? Seems like there wouldn't be if you're on 1.14.6...

**Comment by JoeLudwig** [comment]
And yeah moving that specific issue (which likely affects all non-Steam overlay apps) to its own issue would be good.

Interestingly, if your app were distributed via Steam it likely wouldn't have this problem.

**Comment by BOLL7708** [comment]
Steam recognizes that SteamVR has shut down, or at least the VR button goes gray again.

I do see SteamVR workshop content in my downloads that have supposedly finished, says 0/0 bytes though and I still get the same dialog if I repeat the failure case. 🤷‍♂️ Not sure what is going on there. I will move this to a new ticket.

**Comment by BOLL7708** [comment]
Closed this as there is a suitable work-around and the issue I found has been registered separately.
