### ISSUE TITLE
 Failed to initialize VR Compositor

### ISSUE THREAD

**Issue by Jeff0821** [ValveSoftware/openvr#1440]
Dear experts,
when i run the samples with HTC Vive pro device, it is output below error messages:

Loading settings 3
Compositor initialization failed. See log file for details
CMainApplication::BInit - Failed to initialize VR Compositor!
Shutdown complete. Exiting

Could you please help!

**Comment by LouHan-0325** [comment]
I've had similar problems. Maybe you need to update SteamVR.

**Comment by Jeff0821** [comment]
Yes, you are right!
I found the reason is the version between openVR and steamVR is not match which make this error...
I checkout openVR by tag that match with my steamVR, and it works OK now.
Thank you for your help!

**Comment by Jeff0821** [comment]
The reason is the version between openVR and steamVR is not match which make this error...
Solution: checkout openVR by tag that match with the steamVR version
