### ISSUE TITLE
Update driver-side api to new version is required?

### ISSUE THREAD

**Issue by gb2111** [ValveSoftware/openvr#1442]
Hello. Seems latest SteamVR update 1.14.15 affected few apps using driver-side api like mine WalkinVR, Natural Locomotion and few others. Can you please update so we can get them working?

Best,
Greg

**Comment by TheDeveloperGuy** [comment]
Usually the SDK follows the release by a few days to a week so that they can be (more or less) sure that everyone is on the new version before anything tries to use it.

**Comment by gb2111** [comment]
not this time.
