### ISSUE TITLE
IVRSettings::SetString() not working

### ISSUE THREAD

**Issue by sebafreeskate** [ValveSoftware/openvr#1443]
Hello, I've been trying for a while to get rid of SteamVR grid (happened when app hangs or somthing like that).
I think i found a way: it can be disabled with an option gridColor with a zero alpha channel. Already tryed it manually trought config file and it works exactly as needed.
But i faced a problem when trying to do it programmaticly via openvr.h API.
Here is my code:

	vr::VRSettings()->SetString("steamvr", "gridColor", "#0000000", &SetError);

	bSyncResult = vr::VRSettings()->Sync(true, &SyncError);

there are no errors, and bSynkResult is true. But this code makes no effect on SteamVR grid appearence.
Please help me ti fugure out: what iam doing wrong.

**Comment by okawo80085** [comment]
just a thought, but maybe steamvr doesn't let apps control the chaperone? you know the only thing the doesn't let people accidently bump into walls/furniture/other irl objects

**Comment by okawo80085** [comment]
> just a thought, but maybe steamvr doesn't let apps control the chaperone? you know the only thing the doesn't let people accidently bump into walls/furniture/other irl objects

nvm, right after you set the value use the settings api to get a value from any section/field

**Comment by okawo80085** [comment]
i was wrong again

it DOES save section changed back into the config file

the only catch is that it saves everything into the steamvr's config file, no matter which driver the section is coming from, it looks like the changes are saved into the `steamvr.vrsettings` file

**Comment by flamingsun** [comment]
> Hello, I've been trying for a while to get rid of SteamVR grid (happened when app hangs or somthing like that).
> I think i found a way: it can be disabled with an option gridColor with a zero alpha channel. Already tryed it manually trought config file and it works exactly as needed.
> But i faced a problem when trying to do it programmaticly via openvr.h API.
> Here is my code:
> 
> ```
> vr::VRSettings()->SetString("steamvr", "gridColor", "#0000000", &SetError);
> 
> bSyncResult = vr::VRSettings()->Sync(true, &SyncError);
> ```
> 
> there are no errors, and bSynkResult is true. But this code makes no effect on SteamVR grid appearence.
> Please help me ti fugure out: what iam doing wrong.

Hi, I have the same quesstion, did you solve it ? I found Optitrack openvr driver config software can change it successfully !

**Comment by JoeLudwig** [comment]
SteamVR does not support zero alpha on the chaperone color. The value that is actually used will apply a minimum so chaperone bounds will remain visible.

All of the "set" functions are also disabled from scene apps. It's not entirely clear, but that might have been involved in a couple of the issues folks were having above. The return type of the set functions is void, so there's no way to return an error, but the vrclient_<exename>.txt log file should have a line about scene apps being unable to modify settings.
