### ISSUE TITLE
Reprojection for bad framerates (fps<45)

### ISSUE THREAD

**Issue by thomasbochtler** [ValveSoftware/openvr#145]
The OpenVR SDK with the "allow reprojection" flag set to true sometimes seems to ignore new rendered/submitted frames. It looks like this only happens, if the achieved frame rate is far below 45 fps (e.g. 25 fps or less). 

The submitted frames are shown on the mirror window, but not on the hmd display, where reprojection occasionally runs for up to a few seconds and then suddenly "snaps" back to a submitted frame.

This effect is also visible in the frame timing tool, where the WaitGetPoses Graph hits zero for a the time only reprojections is running. Therefore we disable reprojection for the time beeing, since our engine will not be able to hit 45fps right now.

Could the reprojection be fixed to correctly return to the submitted frames or to work for framerates below 45fps?

Or will there be an option for a "full" asynchronous time warp like the Oculus SDK ATW?

**Comment by akaStiX** [comment]
Latest SteamVR has support for async reprojection
