### ISSUE TITLE
vrmonitor url handler stopped working in SteamVR version 1.15.1

### ISSUE THREAD

**Issue by sergioberg** [ValveSoftware/openvr#1453]
vrmonitor url handler stopped working in SteamVR version 1.15.1
It is not possible to use "vrmonitor://debugcommands" in SteamVR 1.15.1

**Comment by sergioberg** [comment]
What's interesting is that "vrmonitor://open/knockknock" works, while  "vrmonitor://debugcommands" commands is not

**Comment by sergioberg** [comment]
Correction, only "vrmonitor://debugcommands/system_dashboard_toggle" does not work

**Comment by JoeLudwig** [comment]
12 of the debug command handlers moved to another spot in the code, and system_dashboard_toggle was one of them. That's probably what caused this.  I'll get it fixed up.

Can I ask what you use this vrmonitor URL for?

**Comment by sergioberg** [comment]
> 12 of the debug command handlers moved to another spot in the code, and system_dashboard_toggle was one of them. That's probably what caused this. I'll get it fixed up.
> 
> Can I ask what you use this vrmonitor URL for?

@JoeLudwig 

My app fpsVR ( https://store.steampowered.com/app/908520/fpsVR/ ) uses it for certain purposes: 
1) To detect current resolution, it temporary closes dashboard (while dashboard is opened 3d scene resolution may be lowered), then calling CompositorDumpImages()  (Because there is no other good approach https://github.com/ValveSoftware/openvr/issues/970 ), and then back opens dashboard to my overlay to show result. 
All this would be unnecessary if OpenVR would allow to determine the resolution at any time and without using CompositorDumpImages(). I would just show the user the current render resolution, right in the in-game overlay (not in the dashboard overlay).

2) In order to close the dashboard when my application starts. I don't know for what reason, but sometimes SteamVR for some reason opens the dashboard at random when SteamVR starts. This happens if my app launches automatically with SteamVR.

3) The application has a function that takes a screenshot of the game, this can be useful if the user does not currently have controllers enabled. This function is called either by a combination of keys on the keyboard, or from the menu that is available in VR and on the desktop. To take a screenshot in normal resolution, the dashboard must be closed.

**Comment by JoeLudwig** [comment]
Thanks for the details.

This is fixed in 1.15.2 (when that drops, which is soon.)
