### ISSUE TITLE
Using application api in a driver

### ISSUE THREAD

**Issue by haavarpb** [ValveSoftware/openvr#1455]
Hello, I am making a custom driver for a device that has a vive tracker mounted on it. The idea is to provide my device with a position based on the vive tracker. I have set up the new steamvr input system so that I get the vive tracker pose in an isolated application, which is built as a shared library (dll) when used along with the driver library. However, SteamVR crashes after VR_init is called in the tracking library. The openvr_api.dll is present.

I realize this might be more of a general software problem, but perhaps someone can confirm to me that it is possible to solve my problem this way?

Regards

**Comment by TheDeveloperGuy** [comment]
You can't use application API in a driver. If you need application API services in your driver, you'll need to make a separate process and call them from there. You can use IPC of one kind or another to communicate between your app and driver.

**Comment by haavarpb** [comment]
Thank you for your response!

Your suggested idea was my plan B, but as you mention, I will have to set up communication as well. I guess that will have to do.

Just for reference, why is it that you can't use both at the same time? I'm quite new to more advanced topics such as shared libraries and processes, and I realize these can be quite intricate.

**Comment by TheDeveloperGuy** [comment]
Who knows? Probably by design. If you're trying to do "client" things in a "server" context you probably have a design issue in your approach. There is no "right" way to do what you're trying to achieve though, as it isn't catered for in the OpenVR design (assuming you're wanting to redirect the Tracker's tracking to your own device, either a controller or HMD), and there isn't even an easy way.

**Comment by haavarpb** [comment]
Could tracking override work for this problem?

**Comment by TheDeveloperGuy** [comment]
You could reopen this and change it to a feature request. At present (without hooking, which sounds like it is beyond your current skill level), there is no way to redirect the Tracker's tracking, and not have it also present as a device in SteamVR. So, for now, I'd either use IPC or just use "server side" functions to get the tracking (GetRawTrackedDevicePoses), and live with the additional tracked device.

**Comment by Quixotic7** [comment]
I was able to successfully use the OpenVR.h header inside a driver, see https://github.com/ValveSoftware/openvr/issues/1489 for details.
