### ISSUE TITLE
Rendering custom boundary on top of SteamVR

### ISSUE THREAD

**Issue by off99555** [ValveSoftware/openvr#1456]
If I want a custom boundary like Oculus (the curvy boundary), what knowledge/topic that I need to understand?

![image](https://user-images.githubusercontent.com/15215732/95619732-42af7080-0a99-11eb-85d7-f6e39e8d2586.png)

I tried OpenVR overlay, but it's just a 2D plane, it's not a live 3D model. I want to create external app that renders on top of SteamVR image, like Oculus. I think it relies me to use Unity or Unreal engine as the app. **Please tell me how to render dynamic 3D models on top of SteamVR image with the OpenVR driver.**

Optionally, what kind of knowledge is needed to do good VR runtime app for the play area setup purpose only (I don't mind complexity)?

**Comment by Raivr-dev** [comment]
Is your goal to get the Oculus boundaries?
If you just want a more detailed 'curvy' boundary you can use SteamVR's advanced method of setting up the chaperone.

**Comment by off99555** [comment]
I also want the user to define the boundary and the floor level like in this video: https://www.youtube.com/watch?v=NHgGOL-_Euo

**Comment by Raivr-dev** [comment]
A "_custom boundary on top of SteamVR_" is available in the beta branch of my app called _Stop Sign VR_.
I like the way the Oculus Guardian system allows the user to draw the boundary. Maybe I'll implement something like that in the future. For now, it uses the SteamVR Chaperone boundary, which can import the WMR and Oculus boundaries.

**Comment by off99555** [comment]
The answer is to grab the final back buffer frame of SteamVR and then send to your app.
See example: https://github.com/ValveSoftware/virtual_display
