### ISSUE TITLE
Using TrackingOverrides without Chaperone interference

### ISSUE THREAD

**Issue by TobiSchluter** [ValveSoftware/openvr#1460]
I'm using TrackingOverrides to track the headset (Vive Pro or Index) with external cameras. My use case requires very precise and reproducible location relative to other tracked objects. This is something the Lighthouse is not designed for, so I'm happy to do it myself. (What I'm doing is described in a bit of detail [here](https://lp-research.com/location-based-vr-tracking/))

My problem is that I cannot get rid of the request to do a Room Setup while keeping the high accuracy of my tracking. As a secondary problem this implies that I cannot use the VR View on my desktop as it only works with an existing room calibration. I will outline below how a room calibration interferes with my use case.

What I would like is for SteamVR to either not care about room calibration if a TrackingOverride for the headset is in place or to allow me to substitute my own chaperone file together with a universe id.

The only way to remove the Room Calibration request seems to be to 1) turn on the base stations and 2) do a room setup. This is not what I want because then SteamVR seems to try to align my tracked coordinates with the Lighthouse coordinate system, defeating the purpose of what I am doing. The value of `Prop_CanUnifyCoordinateSystemWithHmd_Bool` doesn't seem to influence this behavior. If the Lighthouses are turned off, the request to setup the room reappears and the VR View becomes black again, defeating the purpose of doing the Room Setup in the first place.  I investigated using `IVRChaperone` and `IVRChaperoneSetup` to undo this or create my own room calibration, but that fails for two reasons:
1) I cannot do any changes if the Lighthouses are turned off (`vr::VRChaperone::GetCalibrationState` is not OK). So I cannot do my own room calibration.
2) with the Lighthouses turned on, I can undo the offset introduced by the Lighthouse via `IVRChaperoneSetup::SetWorkingSeatedZeroPoseToRawTrackingPose` (or `...Standing...`) but since this is now relative to the Lighthouse it destroys the accuracy and reproducibility of my own tracking as well as the precise relation between the HMD and other tracked objects. 

The only workaround that I can think of would be to have a few other static items in the room (static to avoid artefacts from timing differences), track them precisely and feed them though SteamVR, use them to evaluate the transformation between my tracking and SteamVR, and undo the transformation on the application level -- which is not nice and destroys the "drop-in" property of my driver.

At some point in the past I could set `Prop_DriverProvidedChaperonePath_String` and `Prop_CurrentUniverseId_Uint64` with carefully chosen contents and the warning would disappear. I understand that this was never documented to work, as these properties only apply to the HMD and not to the trackers that provide the TrackingOverride data.

I would be grateful if you could provide a way to allow me to use my tracking coordinates unaltered.

**Comment by TobiSchluter** [comment]
Thank you, I haven't, will take a look. My case is different from the Rift in that I'm not actually writing a driver for the headset where it's straightforward to avoid the room setup, but maybe I can trick it with those keys.

I guess I could hook into SteamVR, but I'd strongly prefer to stay within documented APIs (well, for low values of documented :). I also found a DIRTY way of getting rid of the room setup message as long as the Lighthouses are turned off, but I'd prefer if the Lighthouses could stay on in case e.g. somebody in the same room wants to use them simultaneously.

**Comment by TobiSchluter** [comment]
It doesn't seem to do the trick, I'm afraid. If the Lighthouses are off, I get the "Perform Room Setup" warning unconditionally. It even allows me to do it, just for it to ignore the result (good!), the message to pop up again (bad!) and the display mirror not working (bad!). If I turn on the base stations, the room setup readjusts the center and yaw direction (both bad!).

**Comment by TobiSchluter** [comment]
Ok, the magic is the undocumented Prop_OverrideContainer_Uint64. Unfortunately this also overrides the icons in the VR Monitor and (probably) the input profile. Also the device path is changed, so I suspect this will lead to weird failures with other software down the road.

I'll close this for now as the functionality is there.

**Comment by oneday1992** [comment]
What are the successful practices? The same question?
