### ISSUE TITLE
What are the correct steps to create a virtual device driver based on sample driver and virtual display driver?

### ISSUE THREAD

**Issue by windy32** [ValveSoftware/openvr#1464]
The sample driver on the master branch works and we can view the scene from hellovr. The HMD implements IVRDisplayComponent.

The virtual display driver (https://github.com/ValveSoftware/virtual_display) is a bit out-dated (last updated 2 years ago). It is designed to support display transmission across network. The HMD implements IVRVirtualDisplay.

Recently I'm trying to implement a virtual openvr driver which can feed virtual pose info into apps, and also dump rendered vr images onto disk. Basically, I'm thinking about merging the logic from the sample driver and the virtual display driver.

The CRemoteDevice is totally removed, as we just need to dump images.
Instead of implementing IVRDisplayComponent, the HMD implements IVRVirtualDisplay.

To simplify the problem, vsync is ignored and we can dump images as fast as possible.

I've been hacking for 2 days, but still unable to get it working yet.

The latest error log from compositor looks like this:

```
Wed Oct 28 2020 15:50:14.443 - //==============================================================================================
Wed Oct 28 2020 15:50:14.443 - ================================================================================================
Wed Oct 28 2020 15:50:14.443 - ================================================================================================
Wed Oct 28 2020 15:50:14.443 - vrcompositor.exe 1.14.16 startup with PID=7436, config=C:\Program Files (x86)\Steam\config, runtime=C:\Program Files (x86)\Steam\steamapps\common\SteamVR
Wed Oct 28 2020 15:50:14.443 - VR compositor 1.14.16 (v1600466902) starting up
Wed Oct 28 2020 15:50:14.487 - Closing pipe SteamVR_Namespace because it was broken from the other end
Wed Oct 28 2020 15:50:14.487 - CSharedResourceNamespaceClient::Init(): received namespace data 6108
Wed Oct 28 2020 15:50:14.494 - [Settings] Load Default Json Settings from C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\htc\resources\settings\default.vrsettings
Wed Oct 28 2020 15:50:14.494 - [Settings] Load Default Json Settings from C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\lighthouse\resources\settings\default.vrsettings
Wed Oct 28 2020 15:50:14.494 - [Settings] Load Default Json Settings from C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\null\resources\settings\default.vrsettings
Wed Oct 28 2020 15:50:14.495 - [Settings] Load Default Json Settings from C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\sample\resources\settings\default.vrsettings
Wed Oct 28 2020 15:50:14.495 - [Settings] Load Default Json Settings from C:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources\settings\default.vrsettings
Wed Oct 28 2020 15:50:14.495 - [Settings] Load Json Settings from C:\Program Files (x86)\Steam\config\steamvr.vrsettings
Wed Oct 28 2020 15:50:14.497 - Events created
Wed Oct 28 2020 15:50:14.504 - Found bad mirror window settings: 
Wed Oct 28 2020 15:50:14.513 - Reading EDID vendor Id timed out.
Wed Oct 28 2020 15:50:14.513 - CGraphicsDevice Init...
Wed Oct 28 2020 15:50:14.513 - Headset display is virtual
Wed Oct 28 2020 15:50:14.635 - Failed to create backbuffer for virtual display!
Wed Oct 28 2020 15:50:14.635 - Failed to init graphics device
Wed Oct 28 2020 15:50:14.636 - Failed to initialize compositor
Wed Oct 28 2020 15:50:14.636 - Failed to start compositor: VRInitError_Compositor_FailedToCreateVirtualDisplayBackbuffer
```

Any suggestions about the correct steps to implement such a virtual driver?

**Comment by TheDeveloperGuy** [comment]
> Instead of implementing IVRDisplayComponent, the HMD implements IVRVirtualDisplay.

You'll need to implement both. You'll also need to implement your own way to get the virtual display texture onto the screen, and you'll need to simulate vsync, or things won't work properly.

**Comment by windy32** [comment]
> > Instead of implementing IVRDisplayComponent, the HMD implements IVRVirtualDisplay.
> 
> You'll need to implement both. You'll also need to implement your own way to get the virtual display texture onto the screen, and you'll need to simulate vsync, or things won't work properly.

After implementing both. I can successfully dump images.

However I'm not sure about how to simulate (ignore) vsync. The IVRVirtualDisplay api only requires vsync related info in its GetTimeSinceLastVsync interface, but does not specify what should be provided if vsync is not used.

The current implementation looks like this:

```
class CEncoder
...
void Run()
...
	// original remoteDevice.Transmit is disabled
	// m_pRemoteDevice->Transmit(desc.Width, desc.Height, desc.Format,
	// 	(const BYTE*)mapped.pData, mapped.RowPitch, m_flVsyncTimeInSeconds);

	// 1. dump texture
	dump_texture_to_file(...);

	// 2. update dump index
	update_frame_count();

	// 3. update the time texture is dumped
	update_last_vsync_time(SystemTime::GetInSeconds());
...
class CSampleDeviceDriver: public ITrackedDeviceServerDriver, public IVRDisplayComponent, public IVRVirtualDisplay
...
	virtual bool GetTimeSinceLastVsync( float* pfSecondsSinceLastVsync, uint64_t* pulFrameCounter )
	{
		*pfSecondsSinceLastVsync = get_last_vsync_time();
		*pulFrameCounter = get_frame_count();
		return true;
	}
```

Is it the correct way to disable vsync? In this case how frequently images are dumped just depends on how quickly frames are rendered.

**Comment by TheDeveloperGuy** [comment]
> The IVRVirtualDisplay api only requires vsync related info in its GetTimeSinceLastVsync interface

Yes, you will need to provide something resembling actual vsync timing there, or the VR rendering pipeline won't work properly. Amongst other things, "how quickly frames are rendered" depends on that. You can see if your timing is working correctly from the "performance graph" that can be displayed in the SteamVR status window.
