### ISSUE TITLE
How to implement a tracked virtual controller?

### ISSUE THREAD

**Issue by windy32** [ValveSoftware/openvr#1468]
I'm trying to implement a virtual device driver in which I can feed virtual pose info into apps.

I started with the latest sample driver. In CSampleDeviceDriver (the HMD class), if we change the vecPosition and qRotation in GetPose() into some random values, we can see the main camera is moving and rotating.

CSampleControllerDriver (The controller class) also implements ITrackedDeviceServerDriver. But its tracking functionality seems to be disabled by default. First I tried to enable it again:

```diff
index 9ad6990..eb510e6 100644
--- a/samples/driver_sample/driver_sample.cpp
+++ b/samples/driver_sample/driver_sample.cpp
@@ -419,7 +419,7 @@ public:
                vr::VRProperties()->SetBoolProperty( m_ulPropertyContainer, Prop_IsOnDesktop_Bool, false );

                // our sample device isn't actually tracked, so set this property to avoid having the icon blink in the status window
-               vr::VRProperties()->SetBoolProperty( m_ulPropertyContainer, Prop_NeverTracked_Bool, true );
+               // vr::VRProperties()->SetBoolProperty( m_ulPropertyContainer, Prop_NeverTracked_Bool, true );

                // even though we won't ever track we want to pretend to be the right hand so binding will work as expected
                vr::VRProperties()->SetInt32Property( m_ulPropertyContainer, Prop_ControllerRoleHint_Int32, TrackedControllerRole_RightHand );
@@ -469,7 +469,7 @@ public:
        {
                DriverPose_t pose = { 0 };
                pose.poseIsValid = false;
-               pose.result = TrackingResult_Calibrating_OutOfRange;
+               pose.result = TrackingResult_Running_OK;
```

Then I launched hellovr again. However, the SteamVR window still shows that the controller is not being tracked. (The HMD is always being tracked though).

Do I miss something important in order to enable tracking of controllers?

**Comment by TheDeveloperGuy** [comment]
>
> pose.poseIsValid = false;
>

poseIsValid must be true for a tracked device.

**Comment by windy32** [comment]
> > pose.poseIsValid = false;
> 
> poseIsValid must be true for a tracked device.

After setting poseIsValid to true, the controller is still not being tracked.

**Comment by windy32** [comment]
> > pose.poseIsValid = false;
> 
> poseIsValid must be true for a tracked device.

The problem seems to be in RunFrame(). After adding the code below the controller can be tracked:

```c++
	if (m_unObjectId != vr::k_unTrackedDeviceIndexInvalid)
	{
		vr::VRServerDriverHost()->TrackedDevicePoseUpdated(m_unObjectId, GetPose(), sizeof(DriverPose_t));
	}
```

This piece of code can be found in the HMD class, but not the controller class

**Comment by TheDeveloperGuy** [comment]
A real headset or controller provides tracking notifications to SteamVR when it receives tracking from the hardware. The example driver is contrived in this regard.

PS. It is common courtesy to thank people that take time out of their day to help you. 

https://github.com/ValveSoftware/openvr/issues/1464

**Comment by windy32** [comment]
> A real headset or controller provides tracking notifications to SteamVR when it receives tracking from the hardware. The example driver is contrived in this regard.
> 
> PS. It is common courtesy to thank people that take time out of their day to help you.
> 
> #1464

Thank you TheDeveloperGuy! I just noticed that you are not a contributor of this repo, but you have replied to most of the issues here.

The OpenVR documentation is far from perfect. For example, a tutorial document is missing, and a lot of concepts are not discussed in details, leading to a rather steep learning curve. I hope that this issue would help the next person implementing a tracked controller based on the official sample driver.

**Comment by TheDeveloperGuy** [comment]
Who knows what happens at Valve? I expect the developers there are beaten if they are too helpful.
