### ISSUE TITLE
BUG: How to deal with SteamVR 'idle' detection for streaming headsets?

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#1469]
Recent versions of SteamVR will ignore proximity detectors and the SteamVR "pause VR when headset is idle" setting, and will simply stop generating frames when an 'idle' situation is detected (ie. no sensor changes). This is typically after 10 seconds, as per the documentation. However, sometimes it doesn't kick in at all (suggesting uninitialised variables). Regardless, this interferes with connection watchdogging, as the headset is unable to detect whether there is a connection issue, or whether SteamVR has simply elected to stop generating frames. There are of course mechanisms one can devise to work around yet another annoying unwanted SteamVR "feature", which require additional development and testing, and are subject to their own edge cases which would cause them to fail. 

It's possible for SteamVR applications to detect transitions to and from 'idle' state, but there doesn't appear to be any way (short of yet another multi-process solution to get 'user-land' SteamVR functionality into 'driver-land') of getting the k_EDeviceActivityLevel_Idle and k_EDeviceActivityLevel_UserInteraction notifications at a driver level. Or is there? Inquiring minds want to know. Or perhaps just honouring the user's "pause VR when headset is idle" setting would work? 

Seems to have become an issue in SteamVR 1.14.x

I expect this bug report will be ignored, like all others, and I will need to do my own workarounds, as usual. But, of course, there is an outside chance this will get addressed and fixed if it is reported and none if it isn't. We live in hope.

**Comment by peroht** [comment]
Great question. I have not checked lately myself, is this a similar scenario/states when cabled as if when having the vive wireless module on the htc vive? I understand it wants to save on battery/cpu/gpu due to being wireless.

**Comment by dariohtc** [comment]
@peroht  did you check if EVREventType::VREvent_EnterStandbyMode fires when losing a wireless connection and subsequently EVREventType::VREvent_LeaveStandbyMode when reconnected?

**Comment by TheDeveloperGuy** [comment]
This is for a driver, not a client. The driver needs to be able to detect when SteamVR enters 'idle' and stops rendering. Been writing OpenVR drivers for long enough to know that this issue will be ignored by Valve developers, and so will have to implement my own workaround because it needs to be fixed *now*. A "fix" will then be implemented in 6-12 months time by Valve developers, but they won't actually consult any driver developers that need it, and so it will become another useless/unusable SteamVR feature. Fun times.

**Comment by peroht** [comment]
@dariohtc I have not yet checked lately on the client side with wireless about the firing of those events. I'd hope they are properly fired but I'll check as soon as possible.
 
@TheDeveloperGuy You are not alone on the frustration side. I have also had to roll a few workarounds between the openvr client- and driver sides over the years, pulling many gray hairs in the process.

How does one detect the k_EDeviceActivityLevel_Idle  etc on the driver side? 
(I've mainly used PollNextEvent() on the client side)

**Comment by TheDeveloperGuy** [comment]
> How does one detect the k_EDeviceActivityLevel_Idle etc on the driver side?

You can't, hence this issue.

**Comment by peroht** [comment]
> You can't, hence this issue.

I see.

> It's possible for SteamVR applications to detect transitions to and from 'idle' state, but there doesn't appear to be any way (short of yet another multi-process solution to get 'user-land' SteamVR functionality into 'driver-land') of getting the k_EDeviceActivityLevel_Idle and k_EDeviceActivityLevel_UserInteraction notifications at a driver level. 

I interpreted your statement as if there existed a method call to detect the k_EDeviceActivityLevel_Idle and k_EDeviceActivityLevel_UserInteraction on the client side. And that it was only missing on the driver side. But now I understand it was missing on both sides?

**Comment by TheDeveloperGuy** [comment]
> I interpreted your statement as if there existed a method call to detect the k_EDeviceActivityLevel_Idle and k_EDeviceActivityLevel_UserInteraction on the client side. And that it was only missing on the driver side. But now I understand it was missing on both sides? 

I suggest reading what you're commenting on (your replies indicate you have not), and only doing so if you have something useful to add. I'm not talking about client-side, I don't care about client-side, and this has nothing to do with client-side. It's a bug report for Valve developers regards OpenVR headset drivers.

**Comment by peroht** [comment]
I am sorry for wanting to learn more about the problem from your expertise on either side. I hope Valve will find some valve time to put on the issue.

**Comment by TheDeveloperGuy** [comment]
> I am sorry for wanting to learn more about the problem from your expertise on either side.

Apologies if my reply seemed dismissive, it is frustrating to have to repeat information. All of the answers you seek are in my replies.

**Comment by TheDeveloperGuy** [comment]
Seems to be fixed in later versions, no workarounds necessary.
