### ISSUE TITLE
IVRSettings::SetString() not working

### ISSUE THREAD

**Issue by flamingsun** [ValveSoftware/openvr#1470]
Hello, I've been trying to read and write TrackingOverrides section with  steamvr.vrsettings file, read is ok , but write not working.

steamvr.vrsettings file content:

   "TrackingOverrides" : {
      "/devices/optitrack/optitrack-controller-a" : "/devices/hand-a",
      "/devices/optitrack/optitrack-controller-b" : "/devices/hand-b",
      "/devices/optitrack/optitrack-head" : "/user/head"
   },

Here is my code:

        char buf[1024];
        vr::VRSettings()->GetString("TrackingOverrides", "/devices/optitrack/optitrack-controller-a", buf, sizeof(buf));//ok

        vr::EVRSettingsError err;
        vr::VRSettings()->SetString("TrackingOverrides", "/devices/optitrack/optitrack-controller-a", "/devices/obeero/obr_a", &err);

**Comment by okawo80085** [comment]
are you doing this from a driver or an app?

**Comment by flamingsun** [comment]
> are you doing this from a driver or an app?

An app, I had found another app can change the content of steamvr.vrsettings file  successfully, but I don't know how it works .

**Comment by flamingsun** [comment]
Yeah, Thanks Jesus Christ, I slove it !

Here is my code:
m_pVRSystem = vr::VR_Init( &eError, vr::VRApplication_Scene );  // error
m_pVRSystem = vr::VR_Init( &eError, vr::VRApplication_Background );   //ok

Only change the second param of VR_init function  to vr::VRApplication_Background,
vr::VRSettings()->GetString() and vr::VRSettings()->SetString() both work fine.
