### ISSUE TITLE
SteamVR provides no option for Windows Mixed Reality Bindings

### ISSUE THREAD

**Issue by A20T3M4** [ValveSoftware/openvr#1471]
My users are reporting that their controller inputs don't work in our game when using a Windows Mixed Reality headset. Even after they set up a custom binding they say they see their controllers tracking but none of the buttons work. I went into Unity to check if we had a default binding set up and I noticed that the SteamVR Input binding window has no option for Windows Mixed Reality when I try to select which controller to make bindings for. Is there any way to make default bindings for Windows Mixed Reality headsets using SteamVR?
![Screenshot 2020-11-04 233059](https://user-images.githubusercontent.com/22603847/98562769-67edf500-2278-11eb-8d31-91c061c1fe18.png)

**Comment by JoeLudwig** [comment]
The option for the mixed reality controller should appear if you install the Mixed Reality driver: https://store.steampowered.com/app/719950/Windows_Mixed_Reality_for_SteamVR/
