### ISSUE TITLE
I can't get my IVRVirtualDisplay implementation to work

### ISSUE THREAD

**Issue by Mick76** [ValveSoftware/openvr#1472]
Hi, I'm making a small driver that uses IVRVirtualDisplay to get the texture from the backbuffer but my problem starts with it never entering any of the IVRVirtualDisplay functions, however its ITrackedDeviceServerDriver functions do work.

I'm creating .txt files at various points of the program to check that things are working:

- The Activate() function works.

- The GetComponent() function successfully returns the implementation when pchComponentNameAndVersion is equal to IVRVirtualDisplay_002.

- The Deactivate() function also works, this is where I write if the program entered the Present() function during execution, but it always says it didn't.

am I missing something?

so far my code looks like this: https://github.com/Mick76/VR_Driver/blob/main/driver_Test1.cpp

**Comment by TheDeveloperGuy** [comment]
https://github.com/ValveSoftware/openvr/issues/1464

**Comment by Mick76** [comment]
> #1464

Thanks for the link to the post, I tried to follow the valve's virtual display example that the post you cited mentions, and also implement IVRDisplayComponent and IVRVirtualDisplay as it says in the comments, but still I can't get it to work. also I just uploaded the changes to the repository that I put in the description of this post in case you want to see the new code
