### ISSUE TITLE
Object ID question

### ISSUE THREAD

**Issue by godbyk** [ValveSoftware/openvr#148]
I'm guessing that the object ID passed into the `ITrackedDeviceServerDriver::Activate()` method is the value that should be passed as the first argument to the `IServerDriverHost::TrackedDevicePoseUpdated()` and other callback methods?

Is this assumption correct?  Where else is this object ID used?

**Comment by JoeLudwig** [comment]
That's correct. This is also the Tracked Device Index of the object in the application side of the API.

**Comment by godbyk** [comment]
Thanks for the information. These little connections seem to be missing from the documentation currently. Is there any way we (developers) can help with that?

**Comment by JoeLudwig** [comment]
I just removed the restriction to who can edit the Wiki. If there's a page where this information would have helped you, please feel free to make the docs better.
