### ISSUE TITLE
What process hosts SteamVR watchdog?

### ISSUE THREAD

**Issue by off99555** [ValveSoftware/openvr#1486]
I installed sample driver and pressed key Y. This will wake up the HMD.
Even after I already close SteamVR, all the vr*.exe are all closed, the HMD can still wake up with this Y key.
![image](https://user-images.githubusercontent.com/15215732/100808376-a1281800-3466-11eb-9b38-bd78a57c83d8.png)

I am wondering which process is listening for my key press if all the vr*.exe are already closed?
i.e. which process is running the watchdog driver in the background and how do I turn it off?

Another question: it seems that if I changed the key Y to T and rebuild the driver again, it doesn't seem like the new driver is used at all, I still have to press key Y to wakeup the HMD. How do I properly build a new watchdog driver?

**Comment by JoeLudwig** [comment]
steam.exe loads drivers to implement watchdog mode.

Did you build both the 32-bit and 64-bit versions of the driver? Steam is a 32-bit process so it loads the 32-bit DLL.

**Comment by off99555** [comment]
@JoeLudwig Cool. I use Batch Build and now it works!
![image](https://user-images.githubusercontent.com/15215732/100809169-1d6f2b00-3468-11eb-80d9-27ca493267ec.png)

Does this mean that I have to close steam and SteamVR before building correct?

**Comment by JoeLudwig** [comment]
Steam loads the DLL when SteamVR exits. So you'll need to close both in order to not have the DLL be loaded while you're trying to build it.

Sounds like your issue is resolves, so I'm going to close this one.
