### ISSUE TITLE
How do I provide default keybindings for my driver?

### ISSUE THREAD

**Issue by off99555** [ValveSoftware/openvr#1487]
Suppose I create a new driver called `mycontroller` which exposes a single button called `Submit` which is similar to `Trigger` button in Vive controller. Games will not know that my controller exist so when people press the submit button, nothing happens in the game. I want to define default bindings for my controller such that every game that already binds the trigger button of the Vive to shoot action will support my controller as well.
Imagine my controller just as a button for shooting (it's not supposed to do anything else beside shooting).

Ideally, my Submit button would work like Vive trigger. I'm willing to put some effort to define keybinding for every game that my controller will support (shooting games). The primary requirement is that the user must not need to do this keybinding setup.

Question 1: **How do I provide default keybindings for my driver without the need for users to manually do it themselves?**

Question 2: How do I programmatically unbind a button from an action (while in-game)? For example: I'm using my submit button for shooting and then I want the Vive trigger to not shoot anymore (but it can still do something else e.g. activate a menu)

Question 1 is more important. if you can only answer that, then it's enough. If there's no easy answer to question 2 then I will do a hack where I need to load/modify/save the JSON keybindings of user when they are playing games.

**Comment by okawo80085** [comment]
it is possible to ship bindings with your driver, to do that in your input profiles you need to add a `default_bindings` section, here is an [example from my driver](https://github.com/okawo80085/hobo_vr/blob/master/hobovr/resources/input/hobovr_hmd_profile.json#L21), that section needs to be a list filled with blocks like these
```json
{
    "app_key" : "<app key>",
    "binding_url" : "<local path to the binding file>"
}
```
again check the example, also about those app keys and binding urls, steamvr uses them too, you can try to just used the same app keys/binding urls

if you never had the "pleasure" of dealing with a binding file, you can either check the ones steamvr uses, or the ones in my driver

and as to programmatically changing them, well... try it yourself first

**Comment by off99555** [comment]
This solution of providing bindings work! About programmatically changing the binding, I'm thinking of modifying the JSON before SteamVR starts. Let me try that first.
