### ISSUE TITLE
Universe ID

### ISSUE THREAD

**Issue by godbyk** [ValveSoftware/openvr#149]
Where does a driver get the universe ID from?

To support direct mode, I have to return a valid universe ID for the `Prop_CurrentUniverseId_Uint64` and `Prop_PreviousUniverseId_Uint64` properties. I'm currently returning `1` for both (as `0` didn't work).

**Comment by JoeLudwig** [comment]
The Lighthouse driver maintains a list of every base station it's ever seen and an internally generated universe ID for each set of base stations. If you first start up in a room with base stations 101 and 102 the system will generate a universe ID (say X) and write all of that information to lighthousedb.json. If you then move the computer to another room with base stations 201 and 202 it will notice that they're different and create a NEW universe ID (say Y). Move the computer back to the first room and you'll automatically get universe ID X again.

If your tracking system has this kind of identification where it can infer the space the user is in from the globally unique IDs of the base stations you should do something similar. This allows chaperone information to be stored simultaneously for both rooms and to switch back and forth without user intervention.  

For a tracking system where the origin is defined by something that's always moved with the headset and the computer, like an outside-in camera based system probably would, it's fine to return a constant non-zero value. Chaperone will store its information under whatever non-zero value you return. The important thing to consider is that the Chaperone system will require the user to run room setup once for each unique value of Universe ID that you return on that user's machine.

**Comment by godbyk** [comment]
Thanks for the great explanation, @JoeLudwig!
