### ISSUE TITLE
App exit unwillingly when closing SteamVR

### ISSUE THREAD

**Issue by off99555** [ValveSoftware/openvr#1490]
I have a pretty basic OpenVR code here:
```cpp
#include <iostream>
#include <openvr.h>

using namespace std;
using namespace vr;


void quit()
{
	VR_Shutdown();
	exit(0);
}

int main()
{
	EVRInitError err = VRInitError_None;
	IVRSystem* sys = VR_Init(&err, EVRApplicationType::VRApplication_Background);
	if (err)
	{
		const char* errDesc = VR_GetVRInitErrorAsEnglishDescription(err);
		cerr << "ERROR: " << errDesc << endl;
		quit();
	}
	for (unsigned int i = 0;; i++)
	{
		cout << i << endl;
	}
}

```
It initializes the background app, and then print numbers forever in a loop.
When I run this app, open SteamVR (manually), the app will print normally.
But when I close SteamVR (manually), the app exits with error code 0.

This behavior is very strange. I put the app in an infinite loop but somehow closing SteamVR forces the app to exit?
I have found that if I don't do `VR_Init` line then the app won't quit. It's like `VR_Init()` is telling SteamVR to kill the process when SteamVR exits. But why would SteamVR do that?

I want my process to run forever. I want to write an app that just prints position of headset as long as SteamVR is on. If it closes, the app should just freeze, and then when SteamVR is on again, the app continues printing position.

How do I make sure my process will not exit unwillingly?

**Comment by bddckr** [comment]
See #878.

**Comment by off99555** [comment]
@bddckr Thanks!. It works.
Here is the modified code in case anyone want to copy:
```cpp
#include <iostream>
#include <openvr.h>

using namespace std;
using namespace vr;


void quit()
{
	VR_Shutdown();
	exit(0);
}

int main()
{
	EVRInitError err = VRInitError_None;
	IVRSystem* sys = VR_Init(&err, EVRApplicationType::VRApplication_Utility);
	if (err)
	{
		const char* errDesc = VR_GetVRInitErrorAsEnglishDescription(err);
		cerr << "ERROR: " << errDesc << endl;
		quit();
	}
	for (unsigned int i = 0;; i++)
	{
		VREvent_t event;
		while (sys && sys->PollNextEvent(&event, sizeof event))
		{
			switch (event.eventType)
			{
			case VREvent_Quit:
				sys->AcknowledgeQuit_Exiting();
				VR_Shutdown();
				sys = nullptr;
				break;
			}
		}
		cout << i << endl;
	}
}

```

**Comment by off99555** [comment]
@bddckr BTW, do you know how to check whether SteamVR runtime is running?
I don't want to check `IsHmdPresent()` because it doesn't tell me whether SteamVR is running.

**Comment by bddckr** [comment]
I've been calling `VR_Init` repeatedly and checked the error it gives. If you only init as a background app it won't start the runtime for that call.

Due to #195 being a thing to this day I am doing all of this in a tiny separate process that just checks whether it can init successfully. If it can I do some IPC back to the actual app to let it know to try initing itself now. That separate process gets restarted every few hundred checks to keep memory pressure down.

**Comment by off99555** [comment]
Wow. If everyone has to do this, imagine the hours wasted hacking instead of developing. Would you mind sharing the IPC protocol you are using to communicate between processes?

**Comment by bddckr** [comment]
I'm afraid it's all NDA'd. Perhaps @BOLL7708 has an implementation of this in one of his open-source projects? 🙏

**Comment by Raivr-dev** [comment]
You can just check whether process with name "vrserver.exe" is running.

**Comment by off99555** [comment]
@Raivr-dev That's what we are looking for: A more efficient hack!

**Comment by BOLL7708** [comment]
I do work in C# so it looks a bit different, but as @bddckr mentioned, initializing in a loop is one way to detect SteamVR being open, and what I do. In short I run `OpenVR.InitInternal(...)` at an interval until it reports `EVRInitError.None` and returns state > 0, that means we've successfully connected.

Even if there would be a memory leak when initiating repeatedly, as mentioned in one of the issues referenced, most of my applications support being launched with SteamVR and in that case the init loop will usually only run once.
