### ISSUE TITLE
Driver-supplied models

### ISSUE THREAD

**Issue by godbyk** [ValveSoftware/openvr#150]
Can a driver supply models for its own base station, controllers, etc.?  Where should the files be installed?

**Comment by yushen0403** [comment]
Have you tried to return a render model name for vr::Prop_RenderModelName_String?
those models are located in "C:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources\rendermodels", looks like we can put our own models in there and specify its name in driver with that property, it's on my plan to implement such a customized model, but not now. Maybe you can have a try? don't forget to give some feedback here.

**Comment by godbyk** [comment]
@yushen0403 Currently, I'm using the Oculus camera as a standin until I make my own model. I assume dropping my models into that directory would work, but I haven't tried it yet. Generally, though, since I don't like installing files into directories that aren't under my control, I wondered if the driver-supplied models could live in the driver's config directory or similar.

**Comment by SecondReality** [comment]
@godbyk Yes they can.The razer hydra drivers have an example of this (in the drivers rendermodels/hydra_controller folder).

See https://github.com/ValveSoftware/driver_hydra

**Comment by JoeLudwig** [comment]
Yes. Put the render model in <driver directory>/<driver name>/resources/rendermodels/<render model name>/<render model name>.obj.  Then return "{<driver name>}<render model name>" for the Prop_RenderModelName_String property.
