### ISSUE TITLE
Reading Knuckle joystick cause me to get both joystick and trackpad

### ISSUE THREAD

**Issue by off99555** [ValveSoftware/openvr#1500]
```cpp
// assume ctrl_idx is the device index of the left controller
VRControllerState_t ctrl_state;
if (sys->GetControllerState(ctrl_idx, &ctrl_state, sizeof ctrl_state))
{
  auto axis = ctrl_state.rAxis[0]; // this will contain the x,y value of both joystick and trackpad
}
```
How do I get only the joystick?

**Comment by BOLL7708** [comment]
As this method for getting the controller state is [deprecated ](https://github.com/ValveSoftware/openvr/blob/e3d37563fd0405117f035c111346f60ca12625ba/headers/openvr.h#L2230) it's most likely using data that is enabled by the legacy bindings in the newer input system. This binding by default maps the trackpad and joystick to the same input axes, I presume as that can match both Rift or Vive controllers.

**Comment by off99555** [comment]
So I need to use IVRInput ? Can I use that in Overlay app? Because I don't think Overlap allows user to define key in SteamVR binding window.

**Comment by BOLL7708** [comment]
I use that in background applications even so yeah, should work I guess, as long as the dashboard is not up at least. I think you can override that though. 

If your application does not show up in the list of apps, make sure you toggle Advanced Settings in the bottom left corner of the SteamVR settings window and then from the Controllers view click the now visible button Show Old BInding UI. This lists mostly anything and is what I have to use for my own non-Steam applications.

**Comment by ChristophHaag** [comment]
The Index Controller hardware actually reports thumbstick and trackpad as the exact same values. You can decide whether it's trackpad or thumbstick input based on whether the trackpad is touched. This is probably what the action input system does internally too.

IVRInput works in overlay apps and the app should appear in the steamvr bindings ui automattically but there are some rules, for example if you call `SetOverlayInputMethod` with `VROverlayInputMethod_Mouse`, you won't get input from actions anymore. There has been some work improving overlay usability in steamvr, see for example this thread https://github.com/ValveSoftware/openvr/issues/1236#issuecomment-573846119

I think for dashboard overlays you have to use PollNextOverlayEvent and handle the `VREvent_Mouse*` events.

**Comment by off99555** [comment]
@ChristophHaag If you decide whether it's trackpad or thumbstick based on whether the trackpad is touch then what happens if you touch both the thumbstick and the trackpad?

Also, I see that `ctrl_state.rAxis[0]` also contains the joystick value of the treadmill driver. I don't want this. I only want the joystick. So I think the only way out is to use IVRInput system. Is there a simple logic to achieve what I want?

**Comment by ChristophHaag** [comment]
It favors the trackpad position over the thumbstick position it seems.

Starting with moving the thumbstick to a position and then touching the trackpad zeroes the thumbstick position. Starting with touching the trackpad and then moving the thumbstick will keep the tthumbstick position at zero.

You can try it in steamvr settings -> controllers -> test controller https://youtu.be/H9JtuToLq5U

**Comment by JoeLudwig** [comment]
Just to echo what others here have said, if you want both trackpad and thumbstick input from Knuckles at the same time you'll need to use SteamVR Input. That's definitely the right API to use for new applications in any case.
