### ISSUE TITLE
Feature Request: Infinite Farplane support to GetProjectionMatrix

### ISSUE THREAD

**Issue by VPVR** [ValveSoftware/openvr#1512]
HmdMatrix44_t GetProjectionMatrix( Hmd_Eye eEye, float fNearZ, float fFarZ ) does not support infinite far planes. would it be possible to add this feature? Current workaround for me is to set this for the HTC Vive to
m[2][2] = -1.0f;
m[2][3] = -fNearZ;
manually, but I'm not sure if this is correct for all HMDs, or will be wrong in a future version of OpenVR.

**Comment by JoeLudwig** [comment]
You should check out GetProjectionRaw:
```
	/** The components necessary to build your own projection matrix in case your
	* application is doing something fancy like infinite Z */
	virtual void GetProjectionRaw( EVREye eEye, float *pfLeft, float *pfRight, float *pfTop, float *pfBottom ) = 0;
```
