### ISSUE TITLE
WaitGetPoses() not blocking for consistent amounts of time

### ISSUE THREAD

**Issue by kenzomenzo** [ValveSoftware/openvr#1515]
Hi! We are developing an engine using OpenVR, and consistently run at a lower FPS (45 or 30) due to the demands of the engine. We are trying to get the FPS to be as consistent as possible, and in order to do this have been relying on WaitGetPoses() blocking until 3ms before the next vsync. However, sometimes the function will return almost immediately, but other times will block for much longer than expected. For example, if we try to render at 30FPS, and our engine takes 27ms to simulate and render a frame, we'd expect approximately 3ms of blocking until the next running start, 3ms before vsync. Instead we see 0.5ms or 10ms of blocking, seemingly at random. I've read that WaitGetPoses() will sometimes return immediately if you are running behind, but this behavior does not seem consistent. Any ideas on what causes this variability, and how we can consistently run at lower FPS?

**Comment by TheWhiteAmbit** [comment]
This issue is years old. I don't expect it to be ever fixed. All timing are horribly wrong in OpenVR, the sad thing is I guess most of these faults are due to the idea of making the API smart to fix broken software. But in reality this breaks all clean written code.

**Comment by kenzomenzo** [comment]
Thanks for the response! I see, seems like we are just going have to work around this. Thankfully we have found some good methods for mitigating the inconsistency.

**Comment by kenzomenzo** [comment]
After some investigation it turns out that the in-build Windows sleeping functions were interfering with our timings. We did however find that turning off Motion Smoothing in Steam VR settings did help with this issue. Hopefully this helps someone if they have similar issues!
