### ISSUE TITLE
SteamVR not working with Oculus Quest at all

### ISSUE THREAD

**Issue by firehacker12** [ValveSoftware/openvr#1518]
I added the Player prefab from SteamVR into my scene, made sure in project settings for Unity that OpenVR and Oculus were enabled and XR was initialized on start. Restarted Unity and clicked play but only the preview showed my headset moving and I got no output to my headset so it was completely black.

The camera rig prefab allows me to see in my game HMD input and output work, but the controllers do not give any input and I cannot see them. I feel like SteamVR is completely broke with Oculus Link (Quest).

Unless I am doing something wrong, SteamVR does not seem to be working for Oculus Link (Quest).

**Comment by firehacker12** [comment]
Solved. Had to do with project settings.

Things to make sure of in case if either:
A. Your screen when using SteamVR output to headset is black
B. Hands are invisible
C. UI is only visible in 1 eye

Under Project settings, make sure where it says XR Plug-In management, ONLY OpenVR is selected. When I had both OpenVR and Oculus enabled it must've conflicted.

Set your stereo rendering mode to Multi-Pass (NOT single-pass instanced, this will result in your UI only rendering to 1 eye as of my current unity version)

Also make sure of your XR being initialized on setup and if none of that worked I recommend trying the SteamVR interaction demo provided in SteamVR or deleting and reinstalling/updating SteamVR.

Unity 2019 LTS (2019.4.20f1)

**Comment by dariol** [comment]
@firehacker12  just to clarify are you sure it wasn't something else? Targeting both OpenVR and Oculus works for me as well as using single pass on 2019.4.x LTS.  Which version of 2019.3 were you using?
