### ISSUE TITLE
Objets are shaking, latency and image plume

### ISSUE THREAD

**Issue by dvralex** [ValveSoftware/openvr#1522]
Hello,

We develop our own HMD. Our OpenVR plugin is based on official sample code.
As for now we have IMU working at 500hz. But image is very dizzy, have a latency, objects shaking abit while rendering and moving head. 

Anyone know how to solve it?
thanks!

**Comment by tacticalbacon89** [comment]
*Bump* i still haven't figured this out,  when moving your head there is a jitter effect anyong know a solution such as motion smoothing or something similar

**Comment by JoeLudwig** [comment]
You will need to implement a filter of some kind to turn IMU data into smoothed velocities and angular velocities for prediction.  Exactly how you do that is up to you, though.

This isn't an issue with OpenVR or SteamVR so I'm going to close it.

**Comment by dvralex** [comment]
> 
> 
> You will need to implement a filter of some kind to turn IMU data into smoothed velocities and angular velocities for prediction. Exactly how you do that is up to you, though.
> 
> This isn't an issue with OpenVR or SteamVR so I'm going to close it.

But thing is that same happening with original Steam HDK...where we do not use our own filter or so
