### ISSUE TITLE
Custom driver : How to get the path of the driver directory to open a file ?

### ISSUE THREAD

**Issue by nickos64252** [ValveSoftware/openvr#1523]
Hello,

I created a custom driver and everything work fine.

My problem is that I have a custom file I want to open. For now, I open it with an absolute path, but if I go on another computer and Steam is in another folder, it will not work.

I would like to get the path of the driver. Is it possible ? 

Regards

Nicolas

**Comment by JoeLudwig** [comment]
Is the file in your driver directory? We usually do that by getting the path to the DLL and figuring it out from there:
  https://stackoverflow.com/questions/6924195/get-dll-path-at-runtime
  
It's not clear from your question if you're doing this, but you should generally **not** assume that your driver will be inside the SteamVR directory. Usually drivers are installed with "vrpathreg.exe adddriver <path>" and can be anywhere on your hard drive. They won't necessarily be in the Steam directory, even.

**Comment by nickos64252** [comment]
Yes, the file is in my custom driver directory.
Thank you , it is exactly what I was looking for. (For the reasons you mentionned).

Regards

Nicolas
