### ISSUE TITLE
SetOverlayTransformProjection() - 'projection overlay'

### ISSUE THREAD

**Issue by Raivr-dev** [ValveSoftware/openvr#1527]
```
IVROverlay:

Added support for overlays that support projections via SetOverlayTransformProjection
```

I notice that SetOverlayTransformProjection() must be called per eye. What is a 'projection overlay' used for, how does it work? Is it meant for applications like Aardvark?

**Comment by JoeLudwig** [comment]
It's meant for any overlay application that is trying 3D images. Generally you would call it once per eye per frame.
