### ISSUE TITLE
[QUESTION] Getting size of texture from IVRCompositor::GetMirrorTextureGL

### ISSUE THREAD

**Issue by mcoffin** [ValveSoftware/openvr#1531]
Is there any way to know the metadata about the texture given to you by `IVRCompositor::GetMirrorTextureGL`, in particular the dimensions? I unfortunately need to copy it in to system memory, but it's hard to construct an image when you don't know the dimensions of the texture. I saw that the *windows* OBS plugin uses a DX11 query to get it done, but I couldn't find a similar approach for OpenGL when only given the texture identifier.

Thanks in advance for the help; hopefully I'll be able to start seeing `IVROverlay` instances on OBS on Linux soon!

**Comment by Zamundaaa** [comment]
You should be able to get the texture size in OpenGL with something like
```
int w, h;
int miplevel = 0;
glGetTexLevelParameteriv(GL_TEXTURE_2D, miplevel, GL_TEXTURE_WIDTH, &w);
glGetTexLevelParameteriv(GL_TEXTURE_2D, miplevel, GL_TEXTURE_HEIGHT, &h);

**Comment by mcoffin** [comment]
@Zamundaaa - Thank you. I actually did some OpenGL learning on the side to figure it out and was able to finish the project. You can check it out at [mcoffin/obs-openvr](https://gitlab.com/mcoffin/obs-openvr) if you're interested. Thanks for confirming that I got the right solution, though!
