### ISSUE TITLE
[question] How do you convert "calibrated" coordinates to "raw" coordinates from a driver?

### ISSUE THREAD

**Issue by nullnothing** [ValveSoftware/openvr#1532]
I'm currently working on a driver for OpenVR which allows me to set the positions of tracked devices. It currently works fine on my end (using Virtual Desktop to stream wirelessly to an Oculus Quest 2), but a friend of mine (using HTC Vive with Valve Index controllers) cannot get it to work properly.

For them, using the driver to set the controller's position to {0, 0, 0} and rotation to {1, 0, 0, 0} puts it at the exact position & rotation of one of their base stations, whereas the desired outcome would be in the middle of the play space, at the floor height, facing the "forward" arrow on the floor.

I assume this is because I'm directly setting the DriverPose's vecPosition & qRotation to the desired coordinates, without taking calibrated coordinates into account, which would only work if the raw coordinates for {0, 0, 0} happen to "line up" with the universe center/origin, as they appear to do with my VR setup.

I've tried to solve the issue for the past couple days, but I cannot come up with a working solution.

The closest I've come to figuring it out was using `GetWorkingStandingZeroPoseToRawTrackingPose` (from a helper program, as it isn't available in the driver) to get the zero pose (which I assume is meant to be in the middle of the playspace, at floor level) in raw coordinates, then adding the desired position & rotation as offsets to that, but that resulted in the controller being slightly off-center, and about 1-2 metres off the ground.

I've also looked at issues #641 and #617, but I can't figure out the necessary math to calculate & apply the difference (or, in the case of #641, I can't figure out the equivalent functions in C++)

Is there something I'm missing? Can someone please point me in the right direction?

All help is appreciated, thank you for reading!

**Comment by Rectus** [comment]
If I understand it right, the driver itself is responsible for providing the mapping between the raw and calibrated coordinates in the first place. 

OpenVR does not seem to provide any interface for accessing the tracking space of other drivers, nor any other support for combining devices that use different tracking spaces. Applications that use multiple spaces, for example OpenVR-InputEmulator, insert themselves between the drivers and SteamVR by hooking the function calls. Note that this is unsupported and may break every time the API is updated.

**Comment by TobiSchluter** [comment]
If you don't mind the hack, the information needed for the translation from raw to calibrated is in `c:\program files (x86)\steam\config\chaperone_info.vrchap` You need to find out the Universe ID first by getting the property container handle for device zero (= HMD) and then reading `Prop_CurrentUniverseId_Uint64`.

That said, all the necessary math appears to be in #617, just take the matrix `difference` and apply it to the hand controller coordinates before adding your transforamtion on top.

**Comment by nullnothing** [comment]
Hi all & thanks very much for the replies. Thank you @TobiSchluter for tip. I don't mind the hack at all! The problem with the math in #641 was that it appeared to use Unity3D functions that I couldn't find equivalents for in C++.

However, I've since dug around a bit and found this [Matrices.cpp](https://github.com/ValveSoftware/openvr/blob/master/samples/shared/Matrices.cpp) library in the OpenVR samples, which appears to implement all of the functions necessary, but the fact that you need to [convert SteamVR matrices](https://github.com/ValveSoftware/openvr/blob/master/samples/hmd_opencv_sandbox/common_hello.cpp#L31) in order to use them leaves me with a couple of questions as to how I'd convert it back into a SteamVR matrix.

You see, I've searched far and wide but I can't figure out the "format" of a SteamVR matrix, and I'm not sure if it's any different than that of the Matrix4 class provided by the linked Matrices.cpp file. The conversion function linked above appears to add some ["fixed parameters"](https://i.imgur.com/jqZYKWF.png) that aren't from the original SteamVR matrix. My best guess is that it's an empty Quaternion ( {1, 0, 0, 0} ), but I'm not sure as I don't have much experience with matrices.

Would you happen to know what these "mystery numbers" are, and if they're important for converting back into a SteamVR matrix? Or, at least, can you point me toward some SteamVR matrix documentation?

Many thanks for your time & best wishes to you all!

**Comment by Rectus** [comment]
The SteamVR matrix seems to be formatted in a column-major order with units in meters, the same as the [OpenGL matrix format](http://www.songho.ca/opengl/gl_transform.html#matrix). That Matrix4 class uses the row major format and that conversion function just transposes the matrix. The last column is just there since you need a square matrix to be able to invert it. It has identity values so it won't affect the calculations.

**Comment by nullnothing** [comment]
That sounds like enough to get me going for now. Thank you for the straightforward explanation! I'll close the issue for now, but if I have additional questions (that I can't answer myself), I'll probably re-open this issue to avoid cluttering the issue list.

Thank you both again for your time & assistance, you've been very, very helpful! I wish you all the best!
