### ISSUE TITLE
SteamVR 1.17.1 - 1.17.12: GetApplicationAutoLaunch() return false while overlay app is configured to autostart

### ISSUE THREAD

**Issue by sergioberg** [ValveSoftware/openvr#1537]
SteamVR 1.17.2 (since 1.17.1)
**GetApplicationAutoLaunch() always return false**

Example (C#): 
AutoStart = OpenVR.Applications.GetApplicationAutoLaunch("steam.overlay.908520");

returned value always false

meanwhile steam.overlay.908520.vrappconfig:
{
   "autolaunch" : true,
   "last_launch_time" : "0"
}

**SetApplicationAutoLaunch() always return VRApplicationError_UnknownApplication**

Application uses OpenVR SDK 1.12.5 

**Update:**
What else I noticed, if I close SteamVR, manually delete the .vrappconfig file, start SteamVR again, then both functions start working correctly for my application, but after restarting SteamVR, the problem comes back.

**Comment by Raivr-dev** [comment]
I'm using OpenVR API 1.16.8 (with Stop Sign VR) and SteamVR beta 1.17.2.
GetApplicationAutoLaunch() returns what is set in SteamVR Settings Startup/Shutdown for app key "steam.overlay.1196450".
But for app key "steam.overlay.908520" it always returns false.
Maybe you can only get the autolaunch state for the running app itself?

**Comment by sergioberg** [comment]
> Maybe you can only get the autolaunch state for the running app itself?
But I am trying to get the autostart status from this (908520) running application. I'm not talking about that I'm trying to get the status from another application.

**Comment by sergioberg** [comment]
And although the 1.7.2 update partially fixed the problems with displaying autorun settings in SteamVR itself, obviously not all problems have been fixed there. If I close my application, then the line with the setting for my application disappears in the settings. Here, obviously, not all problems have been fixed that appeared since 1.7.1

**Comment by sergioberg** [comment]
I tried running SteamVR many times and found out that the problem does not always happen.
And I found a pattern. Here is the message in the vrclient_fpsVR.txt log:

Fri Mar 26 2021 03:54:40.148 - Received success response from vrserver connect
**Fri Mar 26 2021 03:54:42.386 - Timed out waiting for a good app key**
Fri Mar 26 2021 03:54:42.386 - App key after connect message:steam.overlay.908520

When I this "timeout" happens - i have this issue.

**Comment by sergioberg** [comment]
I did update OpenVR SDK from 1.12 to latest version 1.16.8 for my application.... and "Timed out waiting for a good app key" still triggering issue.

**Comment by sergioberg** [comment]
Another issue with IVRApplications interface: 
if manually run application, app gets appkey like system.generated.fpsvr.exe, in this case it's impossible to use IdentifyApplication( uint32_t unProcessId, const char *pchAppKey ), it is always return VRApplicationError_UnknownApplication.
I checked steamapps.vrmanifest file, my application should be recognized as known app, but it is not.

**Comment by Raivr-dev** [comment]
I tested again, also using app key 1494460 (Desktop+). Now GetApplicationAutoLaunch() works with all, including fpsVR (908520). Still on SteamVR beta 1.17.2, but I did have a Steam update.
Can you get the correct autolaunch status of other apps (e.g. 1196450 and 1494460)?

I also get the VRApplicationError_UnknownApplication calling IdentifyApplication(), unless I supply a correct app key pointed to by pchAppKey, which seems strange as I suppose the key should be the output.
I normally use GetApplicationKeyByProcessId().

**Comment by sergioberg** [comment]
@Raivr-dev 
I wanted to test what you suggested, but I made mistake and instead of GetApplicationAutoLaunch () used IsApplicationInstalled () .... and saw that the function was returning false for fpsVR. Haha. It looks like this is some kind of Steam bug I had. And by the way, I ran the integrity check before and it didn't help. After I discovered it, I uninstalled fpsVR and installed again. And the problem went away. Thanks :)

There is still a bug in the settings for autorun overlays in the SteamVR interface. Sometimes not all overlay apps are displayed there, including your app.

**Comment by Raivr-dev** [comment]
> bug in the settings for autorun overlays in the SteamVR interface

I haven't seen that, but it's good that the other problem went away.

**Comment by sergioberg** [comment]
I was wrong, the issue still persist.

Fri Mar 26 2021 03:54:42.386 - Timed out waiting for a good app key
Fri Mar 26 2021 03:54:42.386 - App key after connect message:steam.overlay.908520

GetApplicationAutoLaunch() returns false.

**Comment by sergioberg** [comment]
1.17.3: issue persist (tried restart SteamVR many times)
switching 1.16.10: no issue (tried many times)
switching to 1.17.3: issue persist (tried many times)
reinstalling fpsVR: (issue returns after second restart of SteamVR)
switching 1.16.10: no issue (tried many times)

**Comment by sergioberg** [comment]
@JoeLudwig Please, can you see what has changed in 1.7. * related to the launch of overlays and related to my issue?

**Comment by sergioberg** [comment]
> I tested again, also using app key 1494460 (Desktop+). Now GetApplicationAutoLaunch() works with all, including fpsVR (908520). Still on SteamVR beta 1.17.2, but I did have a Steam update.
> Can you get the correct autolaunch status of other apps (e.g. 1196450 and 1494460)?
> 
> I also get the VRApplicationError_UnknownApplication calling IdentifyApplication(), unless I supply a correct app key pointed to by pchAppKey, which seems strange as I suppose the key should be the output.
> I normally use GetApplicationKeyByProcessId().


Created a new Background app. So... issue is not just with fpsVR
https://imgur.com/a/5p0FYtJ

**Comment by sergioberg** [comment]
IsApplicationInstalled - 908520 : True
IsApplicationInstalled - 1009850 : True
IsApplicationInstalled - 1196450 : True
IsApplicationInstalled - 1494460 : True
GetApplicationProcessId - 908520 : 33632
GetApplicationProcessId - 1009850 : 32240
GetApplicationProcessId - 1196450 : 29316
GetApplicationProcessId - 1494460 : 34568
GetApplicationAutoLaunch - 908520 : True
**GetApplicationAutoLaunch - 1009850 : False**
GetApplicationAutoLaunch - 1196450 : True
GetApplicationAutoLaunch - 1494460 : True

**Comment by sergioberg** [comment]
I turned off autostart for applications: 908520, 1196450, 1494460  
1.7.3:
IsApplicationInstalled - 908520 : True
IsApplicationInstalled - 1009850 : True
IsApplicationInstalled - 1196450 : True
IsApplicationInstalled - 1494460 : True
**GetApplicationProcessId - 908520 : 54052 (??? Why did SteamVR launch this?)**
GetApplicationProcessId - 1009850 : 50924 (OK)
GetApplicationProcessId - 1196450 : 0   (OK)
GetApplicationProcessId - 1494460 : 0   (OK)
GetApplicationAutoLaunch - 908520 : False    (OK, Autorun is disabled)
**GetApplicationAutoLaunch - 1009850 : False  (???, Autorun is NOT disabled)**
GetApplicationAutoLaunch - 1196450 : False  (OK, Autorun is disabled)
GetApplicationAutoLaunch - 1494460 : False  (OK, Autorun is disabled)

One more try and all the following:
IsApplicationInstalled - 908520 : True
IsApplicationInstalled - 1009850 : True
IsApplicationInstalled - 1196450 : True
IsApplicationInstalled - 1494460 : True
GetApplicationProcessId - 908520 : 0  (OK)
GetApplicationProcessId - 1009850 : 21432 (OK)
GetApplicationProcessId - 1196450 : 0 (OK)
GetApplicationProcessId - 1494460 : 0 (OK)
GetApplicationAutoLaunch - 908520 : False
GetApplicationAutoLaunch - 1009850 : False (???, Autorun is NOT disabled)**
GetApplicationAutoLaunch - 1196450 : False
GetApplicationAutoLaunch - 1494460 : False

**Comment by sergioberg** [comment]
The above is a confirmation that the problem can be observed with any overlay application, but below is a confirmation that this is happening not only on my PC:

7 of 29 (24%) tested PC with SteamVR 1.17.4 has this issue
0 of 17 (0%) tested PC with SteamVR 1.16.10 has this issue

The test consisted in checking the value returned through the API (GetApplicationAutoLaunch) and the value in the autorun config file (steam.overlay.*.vrappconfig)

**Comment by sergioberg** [comment]
1.17.5: not fixed

**Comment by zite** [comment]
Hiya, just to clarify the current situation. This is happening on your computer 100% of the time, and on other people who you've had test 25%?

Would you mind confirming this is still happening on 1.17.8?

Can you reproduce the error and then email me a SteamVR System Report? (SteamVR Menu -> Create System Report) keithb@valvesoftware.com

**Comment by sergioberg** [comment]
> Hiya, just to clarify the current situation. This is happening on your computer 100% of the time, and on other people who you've had test 25%?
> 
> Would you mind double-confirming this is still happening on 1.17.8?
> 
> Can you reproduce the error and then email me a SteamVR System Report? (SteamVR Menu -> Create System Report) [keithb@valvesoftware.com](mailto:keithb@valvesoftware.com)


Yes, on my PC I reproduce it with 100% probability with SteamVR 1.17.8. 
And as for those beta testers from whom I took the data, I'm sure that in fact they all have this issue, they just probably have more than one overlay application installed. I got info about one of it  only (fpsVR).

If I install many overlay apps from Steam, the issue will happens with only one of them. And it won't have to be fpsVR, it could be any of them. But it will always be the same app until you add or remove another autorun application. 

To test on beta testers again, I will need to release a new beta version. It takes time. Let me know if it needs to be done. 

I will email you a report from my PC.

**Comment by sergioberg** [comment]
1.17.12 build is a candidate for a full release, but issue still not fixed

For my application, I already made a workaround (it just read the settings file directly...)
but I think it's better to fix this bug.

**Comment by JoeLudwig** [comment]
@sergioberg We still haven't been able to reproduce this problem.

Can you try calling `GetApplicationPropertyUint64` with the app key and `GetApplicationPropertyUint64` on the machine where this is failing? Does that function return `VRApplicationError_UnknownApplication`, `VRApplicationError_PropertyNotSet`, or something else?

**Comment by sergioberg** [comment]
> @sergioberg We still haven't been able to reproduce this problem.
> 
> Can you try calling `GetApplicationPropertyUint64` with the app key and `VRApplicationProperty_LastLaunchTime_Uint64` on the machine where this is failing? Does that function return `VRApplicationError_UnknownApplication`, `VRApplicationError_PropertyNotSet`, or something else?

Code:
`                EVRApplicationError test = EVRApplicationError.None;
                OpenVR.Applications.GetApplicationPropertyUint64("steam.overlay.908520", EVRApplicationProperty.LastLaunchTime_Uint64, ref test);
                Log("Test:" + test.ToString());`

Result:
= 2021-06-03T20:38:08.5919789+03:00 = Test:**PropertyNotSet**

**Comment by JoeLudwig** [comment]
This should be fixed in 1.17.14: https://store.steampowered.com/news/app/250820/view/3044976533780947487
