### ISSUE TITLE
Uploading steamVR drivers to steamPipeline

### ISSUE THREAD

**Issue by badaaim** [ValveSoftware/openvr#1539]
Hi,

We have a working driver for a custom hardware which we want to now implement a version of it in the steam pipeline for ease of sharing with other users. We have been pointed towards a requirement of steamapp ID for this. 

The documentation for steamworks SDK refers a lot to an application and its steamapp ID, is it necessary to have an application made specifically just to share drivers? _Perhaps poorly phrased but hopefully the question comes across enough_

Is there a documentation specific to hardware drivers and not application?

**Comment by TheDeveloperGuy** [comment]
1) You don't need to distribute via Steam, it's quite easy to make your own installer. Use vrpathreg.exe to add your driver path to SteamVR.
2)  If you do want to distribute via Steam, you need to make some kind of EXE  that will start SteamVR to use for your "app's" Launch button. You need a Valve dev to mark your steamapp ID as a SteamVR driver.

**Comment by JoeLudwig** [comment]
All of those are great answers. (Especially the third one, as attempting to use the Steamworks SDK in a driver will end in tears.)

I believe you can also enter a Steam URL in your launch option so you don't need an exe. Something like `steam://run/250820` should work.

Several drivers do distribute via Steam. If that seems most appropriate for your hardware, start the normal "publish software on Steam" process and when it gets to the point where folks are evaluating your submission, they'll send me an email to connect us. There are a couple of manual steps

**Comment by badaaim** [comment]
Thank you guys, really appreciate it.
