### ISSUE TITLE
Stuck pixels caused by software Added Green noise

### ISSUE THREAD

**Issue by KevinComerford** [ValveSoftware/openvr#155]
I noticed that my headset seemed to have quite a few stuck pixels, I dug into the issue and I was surprised that it wasn't a hardware issue. It's software. The compositor is adding an extra green noise across the whole screen and a line of green pixels down the middle of the views which causes the pixels to appear stuck. This is very distracting in darker areas.

 I managed to get an image onto the headset without using the compositor and the 'stuck' pixels were fully functional. I noticed the same issue both on my personal vive at home and the vive pre at work. Interesting variation is that the noise pattern differs between headsets.

I'm not sure if this is caused by an overly aggressive mura correction or something else, but it's frustrating that it's a software issue that I can't seem to affect. It also seems to be causing people to think that their headsets are defective.

**Comment by jeremyselan** [comment]
Would you update to the latest SteamVR Beta, and let us know if it alleviates this issue? We have added a fix, "Improved appearance of bright pixel outliers, in some headsets" which addresses a similar symptom in many headsets.  Thanks!

http://steamcommunity.com/app/250820

**Comment by KevinComerford** [comment]
Yeah, this mostly fixes it. The stuck pixels are practically gone. I still see the aforementioned green line down the center, but it's much dimmer now. That should ideally be gone entirely, but it's certainly not distracting anymore. Good job!
