### ISSUE TITLE
Steam not auto closing games - urgent

### ISSUE THREAD

**Issue by kpbg** [ValveSoftware/openvr#1557]
Hi Guys,

I know this isn't OpenVR, but I'm not sure where such a thing should be reported. As of today, after an update to Steam (not SteamVR), the games are no longer closing. I can start and run as many of them as I want:

![image](https://user-images.githubusercontent.com/10502446/120034421-b50f9980-c005-11eb-9aff-cc436295680a.png)

I hope that's a bug and not a feature.. I got it duplicated on 4 different machines in different parts of the world.

**Comment by JoeLudwig** [comment]
In fact this is a SteamVR feature, and I'm unable to reproduce it. What kind of headset are you using? Are you running those games in SteamVR mode?

Can you post a SteamVR system report?

**Comment by kpbg** [comment]
I have duplicated that on:
- my home PC that's running SteamVR without any attached headset

- my office PC that is running Valve Index / SteamVR Report:
[SteamVR-2021-05-29-AM_02_10_24.zip](https://github.com/ValveSoftware/openvr/files/6563653/SteamVR-2021-05-29-AM_02_10_24.zip)

- 2 x Customer PCs running Vive Pro + Wireless Adapter

I have tested only with OpenVR and the behavior is pretty consistent between those PCs

**Comment by kpbg** [comment]
I missed to mention the customer tested on his home PC as well (not sure what HMD) and at first it was working as usual. He then restarted Steam and the issue started there as well. We have also tried all the "Clear download/cookies/browser cache" buttons that we know about in Steam.

**Comment by kpbg** [comment]
It looks like the issue got sorted out over the weekend.
