### ISSUE TITLE
VRControlPanel VRDashboardManage

### ISSUE THREAD

**Issue by lisaxiaolicai** [ValveSoftware/openvr#156]
the openvr_api.dll export VRControlPanel VRDashboardManage.. functions, but the head file have not defined these, how to use these functions??? Does anybody know? thanks in advance

**Comment by JoeLudwig** [comment]
These are private internal interfaces that vrmonitor.exe and vrdashboard.exe use to interact with the system. The header part of these interfaces isn't published.

**Comment by lisaxiaolicai** [comment]
Thank u
