### ISSUE TITLE
[Question] SetOverlayRaw with bitmap data from C# fails and returns VROverlayError_RequestFailed after ~200 calls

### ISSUE THREAD

**Issue by nullnothing** [ValveSoftware/openvr#1565]
Hey there! For context, I'm currently working on a program which uses overlays to add/emulate some customization for the watch faces in Rec Room. This requires me to render frames onto an overlay, which would be positioned to roughly match up with the in-game watch.

The way I've decided to go about this is by using C# with GDI+ to dynamically generate bitmaps, and use the OpenVR API to set an overlay texture with that bitmap. After looking around for implementation ideas, I found [this reddit thread](https://www.reddit.com/r/ValveIndex/comments/jx59d8/how_i_can_create_my_own_overlay_with_c/gcv3wts/) which pointed me in the right direction.

I got it all working, and it was rendering frames surprisingly quickly, but then it stopped at ~200 frames. In fact, it always stops after around 200 calls. The `SetOverlayRaw` function returns `VROverlayError_RequestFailed` after that point, which I have not been able to find any information about whatsoever.

That's why I'm turning to the folks here, who probably know more than me about these APIs. I've tidied up the repo and my code can be found [here.](https://github.com/nullnothing/RecWatch)

To save you the extra work of figuring out what my code is doing and where it does the relevant stuff, here are the key parts of the code:
[Program.cs, line 51](https://github.com/nullnothing/RecWatch/blob/main/src/Program.cs#L51) is the main loop where the frames are rendered. I have created a simple overlay wrapper class in [Overlay.cs](https://github.com/nullnothing/RecWatch/blob/main/src/Overlay.cs), which also contains the function I use to get the bitmap data onto the overlay, found on [line 29](https://github.com/nullnothing/RecWatch/blob/main/src/Overlay.cs#L29).

I believe I'm doing everything correct here.. I thought this problem may be related to previous textures not being released or something so I made sure to call `ClearOverlayTexture`, but the problem persists. I also thought that the problem may be related to the speed at which I am changing the overlay texture, but after trying up to ~100ms of delay between updates, the issue still occurs.

I don't know what else to say about this issue. I have no idea why it's happening.. searches for `VROverlayError_RequestFailed` return no helpful results, and even searching for it in this repo's issue list returns no results as of writing. If you need more information, please don't hesitate to ask, and I'll get back to you ASAP.

Any and all help is greatly appreciated, thank you for taking the time to read through this, cheers!

**Comment by kisak-valve** [comment]
It doesn't help with the error, but https://github.com/ValveSoftware/openvr/issues/772#issuecomment-380539744 seems relevant here.

**Comment by nullnothing** [comment]
@kisak-valve Thank you for that! I'll use `SetOverlayTexture` instead. Still, this issue feels a bit like there's a bug hiding somewhere.. not sure if it's mine or not, though.
