### ISSUE TITLE
[BUG] In latest SteamVR Home non-Oculus controllers are sometimes rendered as Rift controllers.

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#1569]
I have a custom controller, with its own controller model (Playstation Move). In SteamVR dashboard the controller model is displayed, as well as (transparently) in SteamVR Home when the controller is idle. When moving the controllers around in SteamVR Home, on most systems a "Mickey Mouse" (white with exaggerated finger size) hand is displayed. However, on some systems, the Oculus Rift CV1 (black) controller is displayed. Nothing untoward is shown in the vrserver.txt log, and there's certainly nothing that would confuse SteamVR into thinking the controller was an Oculus controller. What could cause this? And how can I fix it?

**Comment by danwillm** [comment]
I just tried and am able to reproduce this as well with a custom device - render models appear fine in the SteamVR Dashboard, but not in SteamVR Home.

I remember a recent update to SteamVR Home introduced:  
* `Changed tutorials to default to a Rift S - style controller if the controller type is unknown` - https://store.steampowered.com/news/app/250820/view/2984181743609843391

I assume this issue stemmed from that update - looks like the avatar gloves ("Mickey Mouse") hands are appearing for all new users (I think?) but in fact it looks like it's not possible for any user to get the custom render models for custom devices showing up in SteamVR Home. Users that are presented with the hands intitally and that try to change the render model selected in SteamVR Home (through the SteamVR Home settings panel) only gives the option to switch to Rift Controllers and not the custom render models - is that the same for you?

**Comment by TheDeveloperGuy** [comment]
I do not see (in any of the various SteamVR and SteamVR Home settings) anything relating to changing controller models. In terms of customising the avatar (the closest I could see to where changing the controller model might be), I get an option to change headset, but not controllers. 

SteamVR seems to be in a mess regards this, as it appears to be assuming that any custom controller that's not Vive or Index is Oculus. So, for avatar hands to actually work, I would have to implement fake skeletal tracking for a non-existent hand. Whereas it should actually just be showing the controller models (like it used to). 

@JoeLudwig any chance this can get fixed?

**Comment by joeprime** [comment]
It sounds like there are two things going on here:
1) you're seeing Rift controllers when using a custom controller
2) you've lost the ability to have the unlit rendermodel as your controller model (the one that matches what you see in the SteamVR dashboard)
Is that correct?

**Comment by joeprime** [comment]
Can you run SteamVR Home with your custom controller attached, and type vr_info into the console, and tell me what it says?



to run the Home console, you have to do the following shenanigans:

1) Launch SteamVR Home 
2) Run <Steam Install Directory>\steamapps\common\SteamVR\tools\steamvr_environments\game\bin\win64\vconsole2.exe
3) Add a new tab/port by clicking the top left plus button:
 
        ![image](https://user-images.githubusercontent.com/88051975/127200462-335e2e47-4b6b-486c-bed2-b7c85dcd16bd.png)

4) Change the port from 29000 to 29009:
 
        ![image](https://user-images.githubusercontent.com/88051975/127200486-02dc8640-1c7a-40f9-87cc-e9b5a25982f1.png)

**Comment by TheDeveloperGuy** [comment]
@joeprime 
1. Yes, in some instances (although not on my machines - on my machines it's displaying 'mickey mouse' hands).
2. Yes.

vr_info:
Controller 0 Brand: ivry
Controller 0 Manufacturer: Sony
Controller 0 Model: PS Move
Controller 0 Render Model: {ivry}/rendermodels/psmove_controller
Controller 0 Serial Number: Right Motion Controller
Controller 0 type: playstation_move

The Home console is spammed with this message:
Unknown controller type name 'playstation_move' - falling back to HMD manufacturer name.

**Comment by joeprime** [comment]
I'll take a look at restoring the unlit rendermodel to SteamVR Home, but for the time being, you should be able to force it back by either typing this into vconsole:
`vr_use_steamvr_controller_model 1`
Or adding this to your game launch options for SteamVR in Steam:
`+vr_use_steamvr_controller_model 1`

**Comment by joeprime** [comment]
Thanks for the vr_info spew, btw!

I'm having a hard time reproducing the bug where the Rift controller shows up, so if that happens again on a machine, please send me the spew from vr_info in vconsole from that machine if you can get it from the user.

Also, the vr_info spew also contains information on the HMD, which is helpful. (but if you're not seeing that problem, probably not relevant for your issue)

**Comment by TheDeveloperGuy** [comment]
Thanks, I've asked those users experiencing the 'Rift controller' issue to provide the vr_info output, and will relay it here if I receive any response to that.

**Comment by TheDeveloperGuy** [comment]
@joeprime I've received some feedback from users that are getting Rift controllers in Home. The vr_info output is identical to what I get on my machine, with no mention of Rift or Oculus. For completeness, here is the full output of vr_info:

[   VR       ]: HMD Brand: ivry
[   VR       ]: HMD Manufacturer: OSVR
[   VR       ]: HMD Model: iVRy
[   VR       ]: Render Model: generic_hmd
[   VR       ]: HMD Serial Number: PSVR Headset
[   VR       ]: HMD Expected Controller Type: 
[   VR       ]: 
[   VR       ]: Controller 0 Brand: ivry
[   VR       ]: Controller 0 Manufacturer: Sony
[   VR       ]: Controller 0 Model: PS Move
[   VR       ]: Controller 0 Render Model: {ivry}/rendermodels/psmove_controller
[   VR       ]: Controller 0 Serial Number: Right Motion Controller
[   VR       ]: Controller 0 type: playstation_move
[   VR       ]: 
[   VR       ]: Controller 1 Brand: ivry
[   VR       ]: Controller 1 Manufacturer: Sony
[   VR       ]: Controller 1 Model: PS Move
[   VR       ]: Controller 1 Render Model: {ivry}/rendermodels/psmove_controller
[   VR       ]: Controller 1 Serial Number: Left Motion Controller
[   VR       ]: Controller 1 type: playstation_move
[   VR       ]: 
[   VR       ]: Refresh Rate: 120.00 Hz (120/1) 8.333 ms/frame
[   VR       ]: 
[   VR       ]: Window Rect:        462x462 @ (0,0)
[   VR       ]: Viewport Left Eye:  411x462 @ (0,0)
[   VR       ]: Viewport Right Eye: 411x462 @ (411,0)
[   VR       ]: Recommended Render Target Size: 1176x1320 totaling 1,552,320 pixels per eye requiring 279 million pixels/sec.
[   VR       ]: 
[   VR       ]: FOV Left Eye  (L/R/T/B): 49.72/49.72/53.27/53.27  (H/V): 99.44/106.53
[   VR       ]: FOV Right Eye (L/R/T/B): 49.72/49.72/53.27/53.27  (H/V): 99.44/106.53
[   VR       ]: Stereo FOV (H/V): 99.44/106.53
[   VR       ]: Overall FOV (H/V): 99.44/106.53
[   VR       ]: 
[   VR       ]: Clip Space Bounds Left Eye  (L/R/T/B): -1.1800/1.1800/-1.3400/1.3400
[   VR       ]: Clip Space Bounds Right Eye (L/R/T/B): -1.1800/1.1800/-1.3400/1.3400
[   VR       ]: 
[   VR       ]: Raw matrices from SteamVR (all units in meters):
[   VR       ]: 
[   VR       ]:                         AbsoluteTrackingToTracking
[   VR       ]:                      1.000    0.000    0.000    0.000
[   VR       ]:                      0.000    1.000    0.000    0.000
[   VR       ]:                      0.000    0.000    1.000    0.000
[   VR       ]:                      0.000    0.000    0.000    1.000
[   VR       ]: 
[   VR       ]:                            TrackingToMiddleEye
[   VR       ]:                      0.976   -0.199   -0.089   13.231
[   VR       ]:                      0.193    0.979   -0.066   -2.003
[   VR       ]:                      0.100    0.048    0.994   17.209
[   VR       ]:                      0.000    0.000    0.000    1.000
[   VR       ]: 
[   VR       ]:         MiddleEyeToLeftEye                    MiddleEyeToRightEye
[   VR       ]:   1.000    0.000    0.000   -0.032      1.000    0.000    0.000    0.032
[   VR       ]:   0.000    1.000    0.000    0.000      0.000    1.000    0.000    0.000
[   VR       ]:   0.000    0.000    1.000    0.000      0.000    0.000    1.000    0.000
[   VR       ]:   0.000    0.000    0.000    1.000      0.000    0.000    0.000    1.000
[   VR       ]: 
[   VR       ]:         ProjectionLeftEye                     ProjectionRightEye
[   VR       ]:   0.847    0.000    0.000    0.000      0.847    0.000    0.000    0.000
[   VR       ]:   0.000    0.746    0.000    0.000      0.000    0.746    0.000    0.000
[   VR       ]:   0.000    0.000   -1.000   -1.000      0.000    0.000   -1.000   -1.000
[   VR       ]:   0.000    0.000   -1.000    0.000      0.000    0.000   -1.000    0.000
[   VR       ]: //-----------------------------------------------------------------------------------------

The headset manufacturer is set to OSVR, as this was necessary in older versions of Home to get the gamepad to work correctly for input in Home. It's probably not necessary any more.

**Comment by joeprime** [comment]
We shipped a beta update today that enables the user to choose between cartoony glove hands and the controller rendermodel. Please let me know if that's working out for you.

**Comment by TheDeveloperGuy** [comment]
@joeprime Thanks. I can't find anywhere to set the controller model, and haven't received any feedback yet from users that were experiencing the actual bug (rift controllers showing). Also, glove hands don't really work for controllers that don't provide hand skeletal mapping (laser mouse emits from incorrect location), so I'm not sure that there is any value in allowing the user to set them (and particularly in defaulting to them).

**Comment by TheDeveloperGuy** [comment]
@joeprime Console is still getting spammed with:

Unknown controller type name 'playstation_move' - falling back to HMD manufacturer name.

So, I assume the issue still exists.

**Comment by TheDeveloperGuy** [comment]
@joeprime So that's it? No comments or follow up? 

"We shipped a beta update today that enables the user to choose between cartoony glove hands and the controller rendermodel. Please let me know if that's working out for you."

I see absolutely zero difference between this and previous non-working versions. Where is the user enabled to choose between non-working or random controller models and the model supplied by the controller driver developer? Why should they even have to? Cartoon hands *don't work properly* unless the driver provides skeletal data.

**Comment by joeprime** [comment]
I was out last week so my kids could see their grandparents in person for the first time in a couple years. I'm also out next week.
Looking at the code again today, I was about to implement a fix for not seeing the gloves/controller options, but I realized it's effectively the same as your driver no longer claiming OSVR as the HMD manufacturer, so you should test whether that works for you. (My intended fix was to always use the generic tracked controllers path if unknown tracked controllers are found, independent of the HMD manufacturer name.)

Claiming OSVR as the HMD manufacturer, since that forces you down the gamepad (ie, no tracked controllers) path. (I had no idea until now that path can coexist (somewhat?) with having tracked controllers - but apparently it can, if yours are working at all.)

You could also test that adding -vr_force_generic_tracked to your commandline allows you to see the cartoony gloves and the controller rendermodel options, but changing the HMD manufacturer is the better long term solution.

As for hiding the gloves option for controllers that don't provide a hand skeleton, Home doesn't know whether a hand skeleton is being provided by the driver, but it is something we've talked about plumbing through. I don't have a timeline for when that'll happen, however.

**Comment by TheDeveloperGuy** [comment]
@joeprime Thanks for the info. Unfortunately I can't really test this, as I don't get the issue on my machines, and the users that reported this issue have dropped off the planet (so much for quality beta testers!). I originally claimed OSVR as the headset manufacturer, as this was the only way to get gamepads working in SteamVR Home (that software needs some serious repairs!). Is that part at least fixed(ish) at this point? It's a *REALLY* frustrating game of cat and mouse trying to get things working on SteamVR, without any documentation or support, and every other release of SteamVR breaks something new that used to work.

**Comment by joeprime** [comment]
We don't have an explicit path for having both gamepads and tracked controllers working simultaneously, and I'm working from home this week in between trips, so I can't test that configuration. I think your best path forward is to try changing the HMD manufacturer name, and see if gamepads still work.

If that doesn't work, I can think about how to improve support for that configuration, and see if there's something straightforward I can do.

**Comment by TheDeveloperGuy** [comment]
Thanks! I tried changing headset manufacturer, and got the option in SteamVR Home avatar settings to change hands. However, there was only a choice of mickey mouse hands and nothing else. A user did get back to me and report that they are still getting Oculus controllers with the latest SteamVR Beta (and "OSVR" manufacturer).

**Comment by joeprime** [comment]
I'm surprised that you don't see both gloves and rendermodel after removing "OSVR". What do you see if you add `-vr_force_generic_tracked` to your commandline?

To run Home with a specific commandline, it's easiest to run it directly, rather than from SteamVR.
So you'd create a shortcut to:
`Steam\steamapps\common\SteamVR\tools\steamvr_environments\game\bin\win64\steamtours.exe`
and add the following arguments:
`-vr -vr_force_generic_tracked -allowmultiple`

**Comment by TheDeveloperGuy** [comment]
Apologies, different machine that wasn't running the SteamVR beta, so if I run the beta and I don't set the manufacturer to "OSVR", then the controller models can be set in Home. If I use the "force generic" command-line, I don't know what happens in controller model selection because none of the controller button mappings work (including trigger). Not setting manufacturer to "OSVR" breaks gamepad input. I will open another issue for that.

**Comment by TheDeveloperGuy** [comment]
I've opened another issue for the broken hand models: https://github.com/ValveSoftware/openvr/issues/1579

**Comment by TheDeveloperGuy** [comment]
Users experiencing this issue report that it is fixed in latest beta when setting HMD manufacturer to something other than "OSVR". I will close this issue, but I believe that displaying anything other than the controller model for "unknown" controller/HMD types is incorrect. The user can have an option to use "avatar hands" if they choose to, but that should not be the default.

**Comment by TheDeveloperGuy** [comment]
Users experiencing this issue report that it is fixed in latest beta/release when setting HMD manufacturer to something other than "OSVR". I will close this issue, but I believe that displaying anything other than the controller model for "unknown" controller/HMD types is incorrect. The user can have an option to use "avatar hands" if they choose to, but that should not be the default.

**Comment by TheDeveloperGuy** [comment]
Users experiencing this issue report that it is fixed in latest beta when setting HMD manufacturer to something other than "OSVR". I will close this issue, but I believe that displaying anything other than the controller model for "unknown" controller/HMD types is incorrect. The user can have an option to use "avatar hands" if they choose to, but that should not be the default.
