### ISSUE TITLE
[Question] Creating a driver that runs without room setup?

### ISSUE THREAD

**Issue by dcbork** [ValveSoftware/openvr#1572]
I have been working on my own VR headset without base station support and have found that SteamVR room setup often blocks me from using any games or even unity sometimes. However, since I am don't using base stations I cannot complete the room setup. Is there a trick to this? I have not been able to figure out how to disable room setup.

**Comment by TheDeveloperGuy** [comment]
Run Room Setup, select "Standing Only". If your headset is 3DOF only, then enter your height while playing (sitting or standing) when prompted for a height. To disable Room Setup, you'd need to create your own chaperone JSON file and change some SteamVR settings manually in the steamvr.vrsettings file. This is not a support forum, if you want user support for SteamVR, use:

https://steamcommunity.com/app/250820/discussions/

**Comment by dcbork** [comment]
> Run Room Setup, select "Standing Only". If your headset is 3DOF only, then enter your height while playing (sitting or standing) when prompted for a height. To disable Room Setup, you'd need to create your own chaperone JSON file and change some SteamVR settings manually in the steamvr.vrsettings file.
> 
> This is not a support forum, if you want user support for SteamVR, use:
> 
> https://steamcommunity.com/app/250820/discussions/

My apologies.

**Comment by oneday1992** [comment]
Has the problem been solved? I'm currently experiencing this problem. I can't understand the above reply.
