### ISSUE TITLE
[Question] Is is possible to tell which lighthouse a tracker is using? 

### ISSUE THREAD

**Issue by PetSven** [ValveSoftware/openvr#1573]
I have a two V2.0 lighthouses and a v3.0 tracker. My understanding is that a tracker only uses one lighthouse at a time to track movements. I need to know which lighhouse the tracker is using for tracking at any given time. Is this information available? I did not see a variable with this information in the api document.

**Comment by BOLL7708** [comment]
Where have you heard they only use one station? It has been my understanding they use the sweeps from up to four base stations, all at the same time. The old base stations were sweeping in turn so also using two stations at the same time. 🤔

**Comment by PetSven** [comment]
I noticed it was only using one lighthouse when I was testing it. For example, only one lighthouse is highlighted in the steam vr window. And the distance value I get back from getDeviceToAbsoluteTrackingPose is relative to that device.

**Comment by BOLL7708** [comment]
With only a Tracker in the space, I get all four of my v2 base stations to show up with a v3 Tracker. 🤔 So not sure what is up at your end. And if the tracking origin is at a base station, that sounds like no room calibration, or that the fact it does not detect all of them it's not using a calibration at all.

**Comment by PetSven** [comment]
Thanks. I calibrated the system and it fixed this problem. However, the system is now not working unless there is headset connected. But I am trying to set a tracker only system. I am going to test it more later and see if I can find a way around this.

**Comment by JoeLudwig** [comment]
Lighthouse v2 devices will use up to four base stations at a time. One of them, which is chosen when that constellation of bases is seen for the first time, will be the origin in RawAndUncalibrated space, but they're all participating.
