### ISSUE TITLE
[BUG]: SteamVR Home has hard-coded paths for controller input based on headset manufacturer

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#1578]
My HMD driver supports multiple different kinds of headsets (mobile, PSVR), some of which have controllers (eg. Google Daydream or Oculus mobile), some of which don't have controllers (eg. iPhone), and some of which may or may not have controllers depending on the user's environment (eg. PSVR). In addition, it supports NoloVR tracking and controllers, which can add controllers to a headset that doesn't have built in controllers. 

So, I have to switch headset manufacturers to known presets (eg. "OSVR" for gamepad & "HTC" for motion controllers). This kind of works in some scenarios, but in general isn't manageable, for example in the case where the user starts SteamVR with a gamepad and no controllers connected and then turns on a wireless motion controller while SteamVR is running. In this case, there is no way for the driver to know whether or not the user is going to turn on a controller. 

If the driver sets manufacturer to "HTC" (motion controllers), then gamepads won't work properly, which is a problem as the user might not even have motion controllers. If the driver sets the manufacturer to "OSVR", then SteamVR can select random controller models for motion controllers and gamepads won't work properly. 

So, these hard-coded paths need to become "hints" and not "rules", as the driver can never know what the user will do ahead of time (for instance they may plug in a NoloVR setup after SteamVR has already started, turning a 3DOF setup with gamepad into a 6DOF setup with motion controllers). 

SteamVR needs to user "gamepad laser mouse" unless motion controllers are present, in all instances, ie. use gamepad input until a motion controller is detected. Even an actual OSVR headset can be used with NoloVR, so there is no real-world scenario where SteamVR can reliably predict which controllers a user could be using.

**Comment by joeprime** [comment]
Okay, so it looks like you want dynamic switching between gamepad and tracked controller support, **but not both simultaneously**.

Is that correct?

There's already a code path that supports that dynamic switch, but that path isn't currently enabled for OSVR, (or unknown/future HMDs) so enabling that dynamic switch should be straightforward.

**Comment by TheDeveloperGuy** [comment]
That is correct. I think it's reasonable to expect the user to use motion controllers if they've turned them on. Should I be faking "HTC" all of the time to cater for all 3 use cases ("gamepad only", "motion controller only", "gamepad and motion controller")? Or is there a more elegant way?

**Comment by joeprime** [comment]
My plan is to remove the hmd manufacturer checks entirely, and in the case where I don't recognize the controller type, return generic tracked controller if a controller is present, and gamepad otherwise. (this check is done dynamically, so if you turn on or off your controllers, it'll switch immediately)

So you should return whatever the appropriate HMD manufacturer name is, but Home won't use that information for anything anymore.

**Comment by TheDeveloperGuy** [comment]
Hmmm, as long as that doesn't break input for the custom controller (as -vr_force_generic_tracked does). 

In terms of "turning off controllers", I don't see any way to tell SteamVR that the controller doesn't exist any more. Turning off a gamepad (for example) does not remove it's icon from the SteamVR status.

**Comment by joeprime** [comment]
How does input for the custom controller work? If you're hoping to get tracking from the controller, and input from a gamepad, that's not a path that exists in Home.

As for turning off controllers, as soon as SteamVR returns no tracked device index for controllers, or false for IsTrackedDeviceConnected for the found controllers, Home will fall back to gamepad. The existence of a gamepad isn't actually checked.

**Comment by TheDeveloperGuy** [comment]
It's a PSMove controller, it has its own input paths that are different to Vive for example. It has trigger in common, and input mappings for Home that map to the various functions. That all works. However, when -vr_force_generic_tracked is used, none of those mappings work any more, and the trigger doesn't register either (only button that registers is "system"). I don't have any use case in mind where gamepad and motion controllers are used simultaneously. It's one or the other, as you intimate and everyone expects.

**Comment by joeprime** [comment]
So if you put -vr_force_generic_tracked on the commandline, then you don't get input from the PSMove controller?
How about if you put -vr_force_gamepad_controller on the commandline instead? (-vr_force_generic_tracked takes precedence, so you'll have to remove that)

The weird thing here is that Home is relying on SteamVR to provide it action data, and then it just acts on those actions without worrying about where they came from, so I don't have any theory as to how adding a commandline option to Home could change the actions that Home gets from SteamVR.
Actually, I have a vague theory that seems unlikely, but if you didn't have any bindings it might be possible the PSMove controller is sending gamepad events that the game is picking up directly. The legacy gamepad path is only enabled (and I don't know whether it even still works) when the controller type is gamepad.
So that theory lines up with what we're seeing, but I'd put exactly $0 on that being the problem. Although I don't have any better theories yet...

Can you verify that you're specifying PSMove input bindings for Home to SteamVR?

Can you send over a SteamVR system report so I can get a better sense of what's what?

**Comment by TheDeveloperGuy** [comment]
> it might be possible the PSMove controller is sending gamepad events that the game is picking up directly

That is not possible. 

> Can you verify that you're specifying PSMove input bindings for Home to SteamVR?

Yes, as I said everything works fine without the -vr_force_gamepad_controller command-line

steamvr_environments_bindings_psmove.json
`{
   "bindings" : {
      "/actions/default" : {
         "sources" : [
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/default/in/togglemenu"
                  }
               },
               "mode" : "button",
               "path" : "/user/hand/right/input/triangle"
            },
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/default/in/togglemenu"
                  }
               },
               "mode" : "button",
               "path" : "/user/hand/left/input/triangle"
            },
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/default/in/showinventory"
                  }
               },
               "mode" : "button",
               "path" : "/user/hand/right/input/square"
            },
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/default/in/lclick"
                  }
               },
               "mode" : "button",
               "parameters" : {
                  "haptic_amplitude" : "0"
               },
               "path" : "/user/hand/right/input/trigger"
            },
            {
               "inputs" : {
                  "pull" : {
                     "output" : "/actions/default/in/handcurl"
                  }
               },
               "mode" : "trigger",
               "path" : "/user/hand/right/input/trigger"
            },
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/default/in/pad"
                  },
                  "position" : {
                     "output" : "/actions/default/in/trackpad"
                  },
                  "touch" : {
                     "output" : "/actions/default/in/padtouch"
                  }
               },
               "mode" : "trackpad",
               "path" : "/user/hand/right/input/trackpad"
            },
            {
               "inputs" : {
                  "south" : {
                     "output" : "/actions/default/in/rclick"
                  }
               },
               "mode" : "dpad_click",
               "parameters" : {
                  "sub_mode" : "click"
               },
               "path" : "/user/hand/right/input/trackpad"
            },
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/default/in/pad"
                  },
                  "position" : {
                     "output" : "/actions/default/in/trackpad"
                  },
                  "touch" : {
                     "output" : "/actions/default/in/padtouch"
                  }
               },
               "mode" : "trackpad",
               "path" : "/user/hand/left/input/trackpad"
            },
            {
               "inputs" : {
                  "pull" : {
                     "output" : "/actions/default/in/handcurl"
                  }
               },
               "mode" : "trigger",
               "path" : "/user/hand/left/input/trigger"
            },
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/default/in/lclick"
                  }
               },
               "mode" : "button",
               "parameters" : {
                  "haptic_amplitude" : "0"
               },
               "path" : "/user/hand/left/input/trigger"
            },
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/default/in/showinventory"
                  }
               },
               "mode" : "button",
               "path" : "/user/hand/left/input/square"
            },
            {
               "inputs" : {
                  "south" : {
                     "output" : "/actions/default/in/rclick"
                  }
               },
               "mode" : "dpad_click",
               "parameters" : {
                  "sub_mode" : "click"
               },
               "path" : "/user/hand/left/input/trackpad"
            },
            {
               "inputs" : {
                  "scroll" : {
                     "output" : "/actions/default/in/scroll"
                  }
               },
               "mode" : "trackpad_scroll",
               "path" : "/user/hand/left/input/trackpad"
            },
            {
               "inputs" : {
                  "scroll" : {
                     "output" : "/actions/default/in/scroll"
                  }
               },
               "mode" : "trackpad_scroll",
               "path" : "/user/hand/right/input/trackpad"
            },
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/default/in/use"
                  }
               },
               "mode" : "button",
               "parameters" : {
                  "haptic_amplitude" : "0"
               },
               "path" : "/user/hand/right/input/trigger"
            },
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/default/in/use"
                  }
               },
               "mode" : "button",
               "parameters" : {
                  "haptic_amplitude" : "0"
               },
               "path" : "/user/hand/left/input/trigger"
            }
         ]
      },
      "/actions/move" : {
         "sources" : [
            {
               "inputs" : {
                  "center" : {
                     "output" : "/actions/move/in/teleport"
                  },
                  "east" : {
                     "output" : "/actions/move/in/turnright"
                  },
                  "north" : {
                     "output" : "/actions/move/in/teleport"
                  },
                  "west" : {
                     "output" : "/actions/move/in/turnleft"
                  }
               },
               "mode" : "dpad_click",
               "parameters" : {
                  "deadzone_pct" : "50",
                  "overlap_pct" : "0"
               },
               "path" : "/user/hand/right/input/trackpad"
            },
            {
               "inputs" : {
                  "center" : {
                     "output" : "/actions/move/in/teleport"
                  },
                  "east" : {
                     "output" : "/actions/move/in/turnright"
                  },
                  "north" : {
                     "output" : "/actions/move/in/teleport"
                  },
                  "west" : {
                     "output" : "/actions/move/in/turnleft"
                  }
               },
               "mode" : "dpad_click",
               "parameters" : {
                  "deadzone_pct" : "50",
                  "overlap_pct" : "0"
               },
               "path" : "/user/hand/left/input/trackpad"
            }
         ]
      },
      "/actions/prop_tool" : {
         "sources" : [
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/prop_tool/in/drop"
                  }
               },
               "mode" : "button",
               "path" : "/user/hand/right/input/square"
            },
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/prop_tool/in/menu"
                  }
               },
               "mode" : "button",
               "path" : "/user/hand/right/input/triangle"
            },
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/prop_tool/in/pad"
                  },
                  "position" : {
                     "output" : "/actions/prop_tool/in/trackpad"
                  },
                  "touch" : {
                     "output" : "/actions/prop_tool/in/padtouch"
                  }
               },
               "mode" : "trackpad",
               "path" : "/user/hand/right/input/trackpad"
            },
            {
               "inputs" : {
                  "east" : {
                     "output" : "/actions/prop_tool/in/padright"
                  },
                  "north" : {
                     "output" : "/actions/prop_tool/in/padup"
                  },
                  "south" : {
                     "output" : "/actions/prop_tool/in/paddown"
                  },
                  "west" : {
                     "output" : "/actions/prop_tool/in/padleft"
                  }
               },
               "mode" : "dpad_click",
               "path" : "/user/hand/right/input/trackpad"
            },
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/prop_tool/in/use"
                  },
                  "pull" : {
                     "output" : "/actions/prop_tool/in/trigger"
                  }
               },
               "mode" : "trigger",
               "path" : "/user/hand/right/input/trigger"
            },
            {
               "inputs" : {
                  "position" : {
                     "output" : "/actions/prop_tool/in/joystick"
                  }
               },
               "mode" : "trackpad",
               "path" : "/user/hand/right/input/trackpad"
            },
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/prop_tool/in/menu"
                  }
               },
               "mode" : "button",
               "path" : "/user/hand/left/input/triangle"
            },
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/prop_tool/in/pad"
                  },
                  "position" : {
                     "output" : "/actions/prop_tool/in/trackpad"
                  },
                  "touch" : {
                     "output" : "/actions/prop_tool/in/padtouch"
                  }
               },
               "mode" : "trackpad",
               "path" : "/user/hand/left/input/trackpad"
            },
            {
               "inputs" : {
                  "position" : {
                     "output" : "/actions/prop_tool/in/joystick"
                  }
               },
               "mode" : "trackpad",
               "path" : "/user/hand/left/input/trackpad"
            },
            {
               "inputs" : {
                  "east" : {
                     "output" : "/actions/prop_tool/in/padright"
                  },
                  "north" : {
                     "output" : "/actions/prop_tool/in/padup"
                  },
                  "south" : {
                     "output" : "/actions/prop_tool/in/paddown"
                  },
                  "west" : {
                     "output" : "/actions/prop_tool/in/padleft"
                  }
               },
               "mode" : "dpad_click",
               "path" : "/user/hand/left/input/trackpad"
            },
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/prop_tool/in/use"
                  },
                  "pull" : {
                     "output" : "/actions/prop_tool/in/trigger"
                  }
               },
               "mode" : "trigger",
               "path" : "/user/hand/left/input/trigger"
            },
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/prop_tool/in/drop"
                  }
               },
               "mode" : "button",
               "path" : "/user/hand/left/input/square"
            }
         ]
      }
   },
   "controller_type" : "playstation_move",
   "description" : "Default PlayStation Move bindings for SteamVR Home",
   "name" : "PlayStation Move Bindings"
}`

**Comment by joeprime** [comment]
Thanks - I'll take a look at these later today.
There's another experiment we can try, which is you can type "joystick 1" into vconsole, (while running with -vr_force_generic_tracked) and see if that changes anything. (I realize you said the PSMove can't be sending gamepad events to windows, but it's an easy test, so I thought it might still be worth trying)

**Comment by TheDeveloperGuy** [comment]
I think we're getting side-tracked here. I can't do as you ask, as vconsole2 doesn't work for logging port 29009 if Home is started from the command-line. In any case, the PSMove controller doesn't and can't produce gamepad events, it's simply not that kind of controller. 

If I start Home with the "force generic" command-line it sometimes (well once so far) will act like expected (ie. controller mappings work), but will usually not work (ie. system button works, but no other controller buttons). As Home is not recognising the headset manufacturer, or the controller type it says as much (repeatedly ad infinitum) in the vconsole, I think we're getting the expected behaviour (it's saying "falling back to generic tracked controller" in the vconsole) . I expect that the lack of controller mappings working is as likely to be from it being started on command-line as anything else. Not my business though. My business is that the controllers work in normal operation, which they seem to do when not setting "OSVR" as the HMD manufacturer. It seems that whatever bugs in Home necessitated that previously have subsequently been fixed. 

So, it seems that setting the HMD manufacturer to not "OSVR" is sufficient to get the behaviour I'm expecting. If Home is going to drop HMD manufacturer based assumptions, that's probably enough. There are weird things going on with the game controller, I suggest you test the 3 different scenarios detailed previously when you have a chance and fix any issues you find there. A *BIG* problem with Home is that it doesn't appear to be tested often/ever with gamepads. It needs to be.
