### ISSUE TITLE
Is there a way to show a test image/texture on the HMD display without touch? 

### ISSUE THREAD

**Issue by matrixcr** [ValveSoftware/openvr#159]
I'm trying to get a test image show in the HMD's display exactly as it is. Is it possible to do it through openvr. I knew that one possible method is to turn the HMD to extended display and render the image via D3D or OpenGL, but I want to do it in steamvr. Thanks.

**Comment by zao** [comment]
`Submit()`ing your eye images with `Submit_LensDistortionAlreadyApplied` may achieve some of what you desire, as it's intended for applications that apply distortion themselves with the data from `vr::IVRSystem::ComputeDistortion()`. See the comment for that flag for a bit more text.

**Comment by matrixcr** [comment]
Yes, it's just avoid applying distortion compensation. What I want is some way to write the image to the frame buffer directly.
