### ISSUE TITLE
[BUG]: SteamVR log closes before drivers

### ISSUE THREAD

**Issue by SimLeek** [ValveSoftware/openvr#1614]
We added `DriverLog` messages on the `IServerTrackedDeviceProvider::Cleanup` method, but it looked like they were never called in the console (http://localhost:27062/console/index.html). It turns out the SteamVR log itself closes before the driver cleanup function is called. The cleanup function _is_ called, but we only confirmed that much later by writing to a file instead of the log.

If there are any branching if-then or try-catch instructions in `IServerTrackedDeviceProvider::Cleanup`, we'll have to be send them to a separate log file for us to know what's going on, which defeats the purpose of having the SteamVR log.

**Comment by okawo80085** [comment]
Also very annoying to debug when you can't tell what happens on cleanup

**Comment by TheDeveloperGuy** [comment]
Attach your debugger to vrserver.exe, put breakpoints where you need them in your driver.

**Comment by okawo80085** [comment]
> Attach your debugger to vrserver.exe, put breakpoints where you need them in your driver. Debugging driver startup is harder, as SteamVR startup is a moving target.

Except thats an even bigger pain when we don't use VisualStudio while also shipping a driver for Linux too, attaching gdb to SteamVR on Linux is just annoying, literally dumping logs to a file takes less time to set up.

None of that should be an excuse for `IVRDriverLog::Log()` to stop writing to console *before* `VR_CLEANUP_SERVER_DRIVER_CONTEXT()` is called in `IServerTrackedDeviceProvider::Cleanup()`.

**Comment by TheDeveloperGuy** [comment]
Another way to deal with this is to do all your cleanup in the driver _Deactivate()_ method. _DriverLog()_ is still functional at that point. That is what I do, and in _Cleanup()_ all I do is delete driver objects.

**Comment by okawo80085** [comment]
In the last SteamVR beta it appears to be fixed, not in the webconsole (which turns out exits before driver cleanup), but the text file version of the logs, those now gets the last driver logs before SteamVR exits. I can get all my logs now, so i'm happy :)

> I interpret Cleanup() as being for freeing memory objects only, and very late in the destruction process, so I'm not sure this is even a bug.

Fair enough, but before even the text file versions of the logs didn't reach that point (at least on Linux which is what i'm mostly concerned about), enough to qualify to be a bug IMO.

**Comment by SimLeek** [comment]
In that case, the SteamVR log no longer closes before the drivers, so this is fixed. Strange that the info isn't in the web-console though.

**Comment by okawo80085** [comment]
> In that case, the SteamVR log no longer closes before the drivers, so this is fixed. Strange that the info isn't in the web-console though.

Now that they fixed the text file logs, you can see that the web-console host exits before driver cleanup.
