### ISSUE TITLE
TrackingOverrides enhancement

### ISSUE THREAD

**Issue by aawilliams85** [ValveSoftware/openvr#1615]
The TrackingOverrides feature is useful, but limited.  Is there some way within OpenVR currently, or with some enhancement, that the reference pose could be modified before being applied to the target?

For example, if building a custom controller driver and overriding the position with one provided by a Vive Tracker, it would be great if a position and rotation adjustment could be applied in the TrackingOverride configuration to make sense for that controller without modifying the Vive Tracker itself.

Something that could be dynamically updated via an API would be great, but something that loads fixed values from steamvr.vrsettings at startup would still be incredibly helpful.  Is there a way?

**Comment by danwillm** [comment]
If I understand correctly, you could always apply the offset programmatically in your driver. 

Alternatively, the vive trackers have their own configuration file for SteamVR firmware, which you can pull from them using the lighthouse console, adjusting the head.position properties allow you to offset the trackers by a certain position, then you can reupload the configuration to the tracker.

**Comment by aawilliams85** [comment]
Thanks for the ideas!

Can you elaborate on programming the offsets into my driver?  I had attempted to use a similar method to what is seen in OpenGloves (https://github.com/LucidVR/opengloves-driver/blob/develop/src/ControllerPose.cpp) and apply offsets, which looks great while holding the controller still, but seemed to exhibit a lot of wobbling while in motion.  When I tried OpenGloves itself, it seemed to exhibit the same behavior -- maybe there is a different method that would have better performance?  I'm pretty new to all of this.  The tracking override, by comparison, gave great performance with no wobbling.

I did consider adjusting the configuration file like you mention, although that would limit my ability to move the same trackers around to multiple accessories I'm tinkering with.  I suppose it's better than nothing!

**Comment by danwillm** [comment]
There wa a recent change we made to OpenGloves that should have fixed that, to properly align the angular acceleration with the object:

https://github.com/LucidVR/opengloves-driver/blob/develop/src/ControllerPose.cpp#L77

Let me know if that works for you.

**Comment by aawilliams85** [comment]
I missed that update, how timely!  I tried using the new method and seem to be getting very good results even with a lot of fast motion.

Thanks for pointing me in the right direction and for helping develop such a good example driver!

**Comment by danwillm** [comment]
No problem!

I've been putting together my own documentation and made a few changes to the sample driver included in the repo, which might also help you. Let me know what you think of them:

https://github.com/danwillm/openvr/tree/sample-driver-improvements/samples/driver_sample

**Comment by aawilliams85** [comment]
This is great, really helpful to see everything in one place with enough detail to clarify for a beginner like me!  Bookmarking for reference for sure.
