### ISSUE TITLE
Custom driver to dump frames as fast as possible?

### ISSUE THREAD

**Issue by biosmanager** [ValveSoftware/openvr#1616]
I'm trying to create a custom OpenVR driver that dumps frames as fast as possible. I need this for a custom hardware prototype that uses Vive trackers but not any form of displays.
What is the best way to do this?
Currently I'm just returning a zero time since the last VSync. See here:
https://github.com/biosmanager/openvr-uncapped/blob/cf5ae5c76bc078666f6fd15a73f78191e5b7bf20/drivers/driver_uncapped/driver_uncapped.cpp#L392

But the framerate in my Unity application is much lower compared to running it without SteamVR enabled ( 700 FPS -> 160 FPS). Basically I just want to retrieve poses from the Vive trackers as fast as possible without doing any HMD rendering.

**Comment by danwillm** [comment]
If you want to _just_ receive poses as fast as possible from a device, you could poll `GetRawTrackedDevicePoses` from the driver to receive these updates at an interval that's up to you.

**Comment by okawo80085** [comment]
If you want to just receive tracker poses and you don't have a display in your hardware, why are you implementing an HMD device? If all you are interested in is tracking to it with a generic tracker or a controller, an HMD device *needs* to present frames properly if you're using the `vr::IVRVirtualDisplay` component. @danwillm and @TheDeveloperGuy make a good point!

**Comment by biosmanager** [comment]
Thanks for all the quick answers so far!

A bit of background: I'm using 3 Vive 3.0 trackers in Unity for a research study. At first I tried the SteamVR null driver but that was capped at 60 Hz so I hacked this spaghetti code together - with it I can at least reach 100+ Hz.

What I'm trying to achieve: use the standard Vive trackers with the SteamVR binding stuff in Unity to update poses as fast as possible so I can post-process the data later for analysis.

Do I have to implement just a tracked device for this? Or is it even necessary to implement a custom driver?
I'm not sure what is the correct approach to achieve this, can you lead me in the right direction?

**Comment by TheDeveloperGuy** [comment]
Why use Unity for a data capture application? And why write a driver for hardware that already has a driver? Write a OpenVR client app in C++ to read the trackers in a loop in very few lines of code, rather than using a multi-gigabyte gaming engine in conjunction with a mangled VR headset driver. K.I.S.S.

**Comment by biosmanager** [comment]
> Why use Unity for a data capture application? And why write a driver for hardware that already has a driver? Write a OpenVR client app in C++ to read the trackers in a loop in very few lines of code, rather than using a multi-gigabyte gaming engine in conjunction with a mangled VR headset driver. K.I.S.S.

I'm doing other stuff in the engine, not just data collection. The trackers are not solely used for measuring.

**Comment by TheDeveloperGuy** [comment]
I don't know Unity, but you need to decouple the sensor reading from the frame rate, there is no reason they should be tied together. It's possible to run SteamVR without a HMD, but I don't know if Unity supports that. In any case, you may be better off asking your questions in one of the SteamVR developer forums on Steam. This is for reporting issues in SteamVR, and is not a developer support forum.

**Comment by biosmanager** [comment]
I guess then I have to directly use the OpenVR C# bindings and call `GetDeviceToAbsoluteTrackingPose`.
To my understanding, I cannot use `WaitGetPoses` or any of the binding stuff from `IVRInput` as this is tied to the compositor/HMD framerate, is that correct?

**Comment by okawo80085** [comment]
@biosmanager Im not sure what exactly you expect from lighthouse tracking, but the tracking update rate will not be higher than 60hz (iirc this is the sampling rate for lighthouse tracking), you might be able to fetch device poses at a higher rate, but the data in those poses is updated at 60hz.

**Comment by biosmanager** [comment]
I created a custom Unity package to decouple OpenVR tracking from the SteamVR plugin (which requires an HMD to be present) and from the compositor.
If anybody is interested: https://github.com/biosmanager/unity-openvr-tracking
I know about the sampling rate of the lighthouses but the rotation integration is much faster (1000 Hz sampling, 500 Hz reporting).

**Comment by okawo80085** [comment]
> I created a custom Unity package to decouple OpenVR tracking from the SteamVR plugin (which requires an HMD to be present) and from the compositor. If anybody is interested: https://github.com/biosmanager/unity-openvr-tracking I know about the sampling rate of the lighthouses but the IMU integration is much faster (1000 Hz sampling, 500 Hz reporting).

This makes more sense, way more than a custom driver that messes with frame timings.

**Comment by biosmanager** [comment]
Yeah, I also came to that conclusion due to this conversation.
Thank you very much for your help!
