### ISSUE TITLE
Reset Seated Position 

### ISSUE THREAD

**Issue by Frarean** [ValveSoftware/openvr#1617]
I wanted to reset the seated position using ResetSeatedZeroPose but apparently the function no longer exists.
What alternative do I have ? 
I'm building a plugin for a game and I just need OpenVR to extract the position and rotation of the headset and controllers and then I use these to animate some stuff ingame. I'm using GetDeviceToAbsoluteTrackingPose to get the data, however I can't seem to find a way to have the orientation of the headset coincide with my own orientation when I start tracking. I just need the initial orientation to be right. Setting the seated position beforehand and then trying not to move too much until the plugin has started won't do. Is there a function in the API that will allow me to do this ? Or should I do it by hand and apply a transformation matrix at every frame ?

**Comment by Rectus** [comment]
The function got moved to `IVRChaperone::ResetZeroPose()`

https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L3062

**Comment by Frarean** [comment]
Thanks, it worked !
