### ISSUE TITLE
Failed to terminate vrcompositor.exe

### ISSUE THREAD

**Issue by jrbudda** [ValveSoftware/openvr#162]
Just got the SteamVR beta update for 6/14 which applies to me since I do a non-steam game. It's not working as it says in the notes and launching SteamVR. Instead I get a vrmonitor popup that says 'Failed to terminate vrcompositor.exe'

Maybe I'm doing something wrong. Is there something specific or some order I should be initialing things?

**Comment by jrbudda** [comment]
vrclient.txt
Tue Jun 14 2016 18:35:39.437 - Starting vrcompositor process: E:\Steam\steamapps\common\SteamVR\bin\win64\vrcompositor.exe 
vrmonitor.txt
Tue Jun 14 2016 18:35:39.553 - TerminateZombieProcesses()
vrcompositor.txt
Tue Jun 14 2016 18:35:40.001 - VR compositor (v1465940731) starting up

**Comment by jrbudda** [comment]
it would see the compositor is being started just before TerminateZombieProcesses(), which is then trying to close it.

**Comment by jrbudda** [comment]
Confirmed I can get SteamVR to launch by manually delaying the compositor initialization a couple seconds after system.

**Comment by jrbudda** [comment]
I would suggest changing TerminateZombieProcesses to fail silently and not prevent startup.

**Comment by JoeLudwig** [comment]
This should be fixed in the latest beta: http://steamcommunity.com/games/250820/announcements/detail/606113082981449686

Thanks for the detailed report.

**Comment by jrbudda** [comment]
Thanks!
