### ISSUE TITLE
Accessing device inputs from devices that have no role associated with them

### ISSUE THREAD

**Issue by danwillm** [ValveSoftware/openvr#1621]
I have a particular use case where I would like to get device inputs from trackers that do not have roles associated with them: they will not be the current active controllers that are being held in hand, and they won't have a tracker role like foot, waist, shoulder etc. (set to invalid).

I will know the id of the tracker, and I have been trying to use `GetControllerState` to get the current states of the inputs for this device, however even though the method returns true, it doesn't seem to fill the struct with any data:

```c++
vr::VRControllerState_t state;
vr::VRSystem()->GetControllerState(i, &state, sizeof(state));

//state.ulButtonPressed is 0
```

Is there any additional set up that I need to do to get this method working? (I haven't created any extra bindings files or anything), or is it possible to achieve this functionality with the new input system?

Thank you very much in advance.

**Comment by danwillm** [comment]
I've managed to get this functionality by hooking `IVRDriverInput`.

Unless there's something that I've missed, it looks like there isn't an alternative way to get this functionality?

**Comment by danwillm** [comment]
I guess I'll close this... while hooking isn't ideal, I think it's the only option to have this functionality.

If anyone has any better suggestions, please do let me know. Thanks.

**Comment by okawo80085** [comment]
> Unless there's something that I've missed, it looks like there isn't an alternative way to get this functionality?

Considering that `vr::VRSystem()->GetControllerState()` was deprecated in favor of the new `IVRInput` interface, i don't think there is any alternatives to getting inputs now...

**Comment by everskies** [comment]
> I guess I'll close this... while hooking isn't ideal, I think it's the only option to have this functionality.
> 
> If anyone has any better suggestions, please do let me know. Thanks.

Have you managed to figure out how to do this? I'm struggling with the exact same thing where I'm trying to get the POGO pin state of Vive trackers. 
If not, would you mind explaining how you went about hooking into the IVRDriverInput?
