### ISSUE TITLE
Know when loss of tracking occurs?

### ISSUE THREAD

**Issue by Loeloe02** [ValveSoftware/openvr#1623]
I'm trying to make it so that when my vr headset loses sight of my controller, the tracking switches to my custom tracker (wich just uses a IMU so it's not accurate). I want to use the tracking override function but I am trying to find a way to know when. Is there any boolean that I can acces wich says controller in range or something like that?

**Comment by okawo80085** [comment]
> Is there any boolean that I can acces wich says controller in range or something like that?

No

**Comment by Loeloe02** [comment]
Alright thx

**Comment by okawo80085** [comment]
To clarify: there is no built in function that drivers have to communicate that a tracked device is out of view of another device.

There is a way to tell if a device lost tracking though, and that's checking the `result` and `poseIsValid` of the device's pose struct, *however* this is generally vendor specific and does not guaranty your desired behavior, so *unfortunately* this approach is not suitable for your use case.
