### ISSUE TITLE
SetHighQualityOverlay() doesn't work

### ISSUE THREAD

**Issue by matrixcr** [ValveSoftware/openvr#163]
I used to show a image on a high quality overlay, it works fine before my steamvr get updated yesterday. It now just shows the steamvr grids now. Here's the code snippet. What's wrong?

		vr::IVROverlay *overlay = vr::VROverlay();
		vr::EVROverlayError err = overlay->FindOverlay(overlayKey, &m_overlay);
		if (err == vr::VROverlayError_UnknownOverlay)
		{
			err = overlay->CreateOverlay(overlayKey, overlayTitle, &m_overlay);
			if (err != vr::VROverlayError_None)
				return;
		}

		overlay->SetHighQualityOverlay(m_overlay);
		overlay->SetOverlayFlag(m_overlay, vr::VROverlayFlags_Panorama, true);
		overlay->SetOverlayFromFile(m_overlay, strFullPath.c_str());
		overlay->SetOverlayAlpha(m_overlay, 1.0f);

		vr::HmdMatrix34_t mat;
		mat.m[0][0] = 1.0f; mat.m[1][0] = 0.0f; mat.m[2][0] = 0.0f;
		mat.m[0][1] = 0.0f; mat.m[1][1] = 1.0f; mat.m[2][1] = 0.0f;
		mat.m[0][2] = 0.0f; mat.m[1][2] = 0.0f; mat.m[2][2] = 1.0f;
		mat.m[0][3] = 0.0f; mat.m[1][3] = 0.0f; mat.m[2][3] = -0.25f;

		overlay->SetOverlayTransformTrackedDeviceRelative(m_overlay, vr::k_unTrackedDeviceIndex_Hmd, &mat);
		overlay->ShowOverlay(m_overlay);

**Comment by JohnAlcatraz** [comment]
@matrixcr Could you tell me of this issue was fixed for you again? You closed this, so I assume it worked again?
