### ISSUE TITLE
Displays not blanked on sleep state, sleep state not entered immediately upon proximity sensor out of range

### ISSUE THREAD

**Issue by Danny-Dunn** [ValveSoftware/openvr#1631]
I am working on a driver plugin for SteamVR/openvr. We have a proximity sensor. We can correctly pass the proximity sensor to SteamVR, and moving in front of the sensor will wake SteamVR, and prevent sleep. However, the architecture of our driver requires that the SteamVR compositor blank the displays upon entering the sleep state, because the driver does not include a compositor. Also, we require SteamVR to enter the sleep state immediately upon the prox sensor going out of range. Is this possible?

**Comment by danwillm** [comment]
The time that the display is on for is a user configured setting in SteamVR, and not (to the best of my knowledge) something that the hardware vendor should be adjusting themselves. You could always blank the display yourself by checking when the proximy sensor goes out of range, instead of relying on SteamVR to trigger your sleep method.

The call that openvr makes to your sleep method should be where you blank the display, and I believe the compositor won't do that for you.

**Comment by Danny-Dunn** [comment]
By "blanking" the displays, I meant writing an all-black frame to them. Since SteamVR is the end compositor in this case(it is rendering directly to the displays), I do not believe it is possible for our driver to write any frames to the displays since SteamVR would own the framebuffer of the HDMI output. It is possible for our driver to tell the HMD to power down the displays, but this fully disconnects the HDMI, and takes a long time to resume again.

Looks like I'll probably need a(very basic) compositor then.

**Comment by okawo80085** [comment]
I think you're confusing `IVRDisplayComponent` (a display component that uses SteamVR's compositor, you don't have direct control over this display component, you only set startup parameters for it, after start up it just continuously streams frames *(almost)* without a care in the world) with SteamVR's compositor, it's *your* job to implement proper sleep states for your display when `GetComponent()` is called, if `IVRDisplayComponent` is preventing you from doing that, implement a different display component. You always can just bypass SteamVR's compositor and use your own with `IVRVirtualDisplay` or `IVRDriverDirectModeComponent`.

**Comment by Danny-Dunn** [comment]
> I think you're confusing `IVRDisplayComponent` (a display component that uses SteamVR's compositor, you don't have direct control over this display component, you only set startup parameters for it, after start up it just continuously streams frames _(almost)_ without a care in the world) with SteamVR's compositor, it's _your_ job to implement proper sleep states for your display when `GetComponent()` is called, if `IVRDisplayComponent` is preventing you from doing that, implement a different display component. You always can just bypass SteamVR's compositor and use your own with `IVRVirtualDisplay` or `IVRDriverDirectModeComponent`.
> 
> There is an example Valve provides for `IVRVirtualDisplay` (and `IVRDriverDirectModeComponent` is very similar) in the wiki, [can be found here](https://github.com/ValveSoftware/openvr/wiki/Driver-direct-mode) and [here](https://github.com/ValveSoftware/virtual_display/blob/master/driver_virtual_display/driver_virtual_display.cpp#L508).

This is the answer, but I'll be opening another issue due to the lack of examples/documentation for how either `IVRVirtualDisplay` or `IVRDriverDirectModeComponent` work on Linux.

**Comment by ChristophHaag** [comment]
> on Linux.

ALVR tried to use this interface but dfidn't get it working. There is an issue here https://github.com/ValveSoftware/SteamVR-for-Linux/issues/409 with (non working) example code.
