### ISSUE TITLE
SteamVR Status window staying out of frame/no longer displaying after Windows performs a rescale of application in response to display device changes and in some cases stays unreachable even after a restart of SteamVR

### ISSUE THREAD

**Issue by TheJokingTeen** [ValveSoftware/openvr#1633]
SteamVR's Status Window doesn't even want to come back using Win + arrow keys.
Windows is partly to blame, but this is really weird and annoying, and seems to be less broken on other win32 applications.

**Comment by danwillm** [comment]
It might be better to ask this question in the bug reports section of SteamVR: https://steamcommunity.com/app/250820/discussions/3/

**Comment by TheJokingTeen** [comment]
good point

**Comment by TheJokingTeen** [comment]
> It might be better to ask this question in the bug reports section of SteamVR: https://steamcommunity.com/app/250820/discussions/3/

How about here: https://github.com/ValveSoftware/VR-Community-Bugs/issues
