### ISSUE TITLE
Windows 11 issue

### ISSUE THREAD

**Issue by sergioberg** [ValveSoftware/openvr#1639]
4 months have passed since Windows 11 was released, SteamVR still does not work properly with this operating system. Does Valve have any plans to support this operating system?
Issue: continous frame drops with Windows 11.
Headsets tested: Vive, Vive Pro 2, Index and Quest 2.

Appearance of a issue probably depends on what z-order windows has (for SteamvVR (vrcompositor.exe) - Steam window as it is parent procces for vrcompositor.exe, for the Oculus vr compositor - the Oculus service window, by default it is disabled, but it can be enabled via debug tool), as well as the state of the window and the states of windows that overlap it (states: Minimized, Normal, Maximized). The issue with continuous frame drops occurs when these windows in a certain order and state.

Issue can be easily reproduced. Just run SteamVR via Steam, run any vr game, minimize steam window or/and get any window and miximize it to overlap all other, wait for 5 seconds.
The issue can also occur when, for example, a main window of application (for example, Discord) maximized, but Steam and Steamvr windows overlap it, and it displays a notification on top of Steam window.
The issue can occur with the compositors processes (vrcompositor.exe or/and the oculus service) and with the vr game process. Separately or simultaneously, it all depends on the order of the windows and their states

I found what for SteamVR compositor, the issue can be solved if run vrstartup.exe via desktop shorcut. In this case parent procces for  vrstartup.exe and vrcompositor.exe will be explorer.exe which has main window with very high and constant z-order.

**Comment by okawo80085** [comment]
First, you'll need to clarify you issue, what exactly is wrong?
Is it a visual bug? Is it only the case with the status window?
Please provide screenshots and any other info, because your current description is not very helpful.

Also if this is related to how Windows 11 does Z layering, *I fail to see how it's SteamVR's fault for Windows 11 being jank*.

But in either case, more info will help to resolve this issue.

**Comment by sergioberg** [comment]
@okawo80085 
![image](https://user-images.githubusercontent.com/12216723/153742665-76982fd4-ddf9-4bc5-9e3b-1584bd2b52fd.png)

Continous frame drops

Windows 11 changed WDDM version. I can only theorize, but perhaps the problem lies in how Windows 11 handle the exclusive full-screen mode. As far as I understand the vr compositor works in exclusive full-screen mode. Now any application interferes with the operation of the video card, depending on the height of its priority can cause frame drops. 

> Also if this is related to how Windows 11 does Z layering, I fail to see how it's SteamVR's fault for Windows 11 being jank.

SteamVR must adapt to the new changes in the new operating system. Maybe Valve should take this issue to Microsoft and work it out together. Interestingly, the Windows Mixed Reality compositor does not have this problem. It is not possible to reproduce frame drops on the side of their compositor.

This issue has been reported by people on the SteamVR forum. Some contacted support and received a response that Windows 11 is not yet supported. This topic has been discussed for a long time.

As the author of an overlay application that shows performance stats in VR (fpsVR), I receive complaints that it is my application that is causing the issue. But any running application after starting SteamVR can cause the problem (my application has a window on the desktop), or rather, any window that appears can cause the problem, if the windows described in my first post do not have the highest order on the desktop.
Now in the beta version of my application, I have added and testing a feature for windows manipulation so that users with Windows 11 do not experience this issue. But this is a very crude crutch.

**Comment by sergioberg** [comment]
I can offer a simple and quick solution, I'm sure it will work. It is necessary that the vrcompositor.exe process has its own window, and this window should be TOPMOST window (always on top windows). It is not even necessary to display something in it, it can be transparent.

**Comment by sergioberg** [comment]
> Now as to fixing it, and well also finding the root cause of the problem, because this really smells like Oculus driver's fault.

This has nothing to do with the Oculus driver. The problem is observed on different headsets. I have personally observed this on Quest 2/Index/Vive/Vive Pro 2. This is observed even without SteamVR, i.e. the issue can be reproduced similarly on Oculus compositor without running SteamVR.

**Comment by TheDeveloperGuy** [comment]
Stepping in here to correct some misconceptions (for future readers):

- Index/Vive/PSVR drivers do not use IVRDriverDirectModeComponent, whereas Oculus and WMR drivers do.
- Oculus compositor does not create any window for Quest. All rendering is done to texture, which is then compressed and sent to headset. Go/Quest/Quest2 is not a video device in any traditional sense of the word when it is connected to PC. 
- SteamVR compositor creates a fullscreen (unless using a debug driver) window in Extended (GDI) or Exclusive (VR-Direct) mode for IVRDisplayComponent devices with no IVRDriverDirectModeComponent or IVRVirtualDisplay component (also depends on properties set in Activate()). 

As can be seen from above, there is nothing in common between Oculus/WMR and Vive/Index output paths in SteamVR, so the issue is most likely a Windows 11 issue that is not specific to any headset. Microsoft has either worked around or correctly coded the solution to whatever is actually causing this.

**Comment by okawo80085** [comment]
> * SteamVR compositor creates a fullscreen (unless using a debug driver) window in Extended (GDI) or Exclusive (VR-Direct) mode for IVRDisplayComponent devices with no IVRDriverDirectModeComponent or IVRVirtualDisplay component (also depends on properties set in Activate()).

I guess i'll go through the IVRVIrtualDisplay component example again, pretty sure i missed something last time i got a go at IVRVirtualDisplay component.
Thanks for the correction!

**Comment by TheDeveloperGuy** [comment]
> I guess i'll go through the IVRVIrtualDisplay component example again, pretty sure i missed something last time i got a go at IVRVirtualDisplay component. 

Good luck with that. That example is needlessly complex. In any case the virtual display interface is useless (or more or less useless) as there is no way to do ATW with it. It's usable for streaming to devices that don't have their own compositor with ATW (eg. Cardboard).

**Comment by okawo80085** [comment]
> Good luck with that. That example is needlessly complex. In any case the virtual display interface is useless (or more or less useless) as there is no way to do ATW with it. It's usable for streaming to devices that don't have their own compositor with ATW (eg. Cardboard).

Ah, well i'll still go take another go at it, i'm kinda cursed to need to support those in my driver anyway...

**Comment by TheDeveloperGuy** [comment]
> 
> Ah, well i'll still go take another go at it, i'm kinda cursed to need to support those in my driver anyway...
>

It's certainly a lot easier than the IVRDriverDirectModeComponent interface, and at least there is an example. I support all 3 display interfaces in my driver (historically, the virtual interface came quite some time after the direct mode one, and so if you've been in this game a while, it's sad that the virtual interface is less useful than the undocumented, more complex direct mode one). It's a lot of work, most of which is trial and error.

**Comment by sergioberg** [comment]
> * Oculus compositor does not create any window for Quest. All rendering is done to texture, which is then compressed and sent to headset. Go/Quest/Quest2 is not a video device in any traditional sense of the word when it is connected to PC.

OVRServer_x64.exe process  does not create any window by default. But it possible to enable console window on desktop.
Manipulating this window has the same effect on the appearance of the problem.

**Comment by TheDeveloperGuy** [comment]
> 
> OVRServer_x64.exe process does not create any window by default. 

Well, it does, when using a Rift or DK1/DK2. For Rift it creates an Exclusive (VR-Direct) fullscreen window. For DK2 it can create an Extended or Exclusive fullscreen window. Don't know/care about DK1 (but guessing only Extended). Rift behaviour is the same as WMR behaviour (and Vive/Index in "VR-Direct" mode).

**Comment by sergioberg** [comment]
> For Rift it creates an Exclusive (VR-Direct) fullscreen window.

I meant the window only on the desktop, and only in the context of the mentioned Quest 2 :)

In short, it seems that when determining the priority, Windows 11 generally stopped taking into account all windows outside the desktop that is displayed on the user's monitor.

**Comment by okawo80085** [comment]
> It's certainly a lot easier than the IVRDriverDirectModeComponent interface, and at least there is an example. I support all 3 display interfaces in my driver (historically, the virtual interface came quite some time after the direct mode one, and so if you've been in this game a while, it's sad that the virtual interface is less useful than the undocumented, more complex direct mode one). It's a lot of work, most of which is trial and error.

Yeah i know, im trying to avoid it as the plague, i've seen how painful it is when someone else tried to implement it.

**Comment by TheDeveloperGuy** [comment]
> 
> Yeah i know, im trying to avoid it as the plague, i've seen how painful it is when someone else tried to implement it.
>

None of them are particularly hard or complex to implement once you cut away all of the stuff that doesn't need to be done. The virtual interface is trivial to implement, but that is hidden by the overly complex example. The driver direct interface is similarly trivial once you realise that most of the implementation is a simple texture management system. The trial and error part is regarding texture locks, but I've gotten relevant help from Valve devs when I've needed it, and it's all recorded in here if one was to go digging.

**Comment by TheDeveloperGuy** [comment]
> 
> Yeah i know, im trying to avoid it as the plague, i've seen how painful it is when someone else tried to implement it.

The only point in implementing driver direct is for headsets that have their own compositor that does ATW. So, unless you are constraining yourself to phone VR (not including GearVR), you'll need to do this. A good reference for driver direct is LibreVR ReVive, which does exactly the opposite (implements an Oculus compositor using OpenVR). Historically, driver direct was designed for Oculus headsets. Microsoft WMR didn't make any changes to that interface when the WMR driver for OpenVR was developed AFAIK.

**Comment by okawo80085** [comment]
> The only point in implementing driver direct is for headsets that have their own compositor that does ATW. So, unless you are constraining yourself to phone VR (not including GearVR), you'll need to do this. A good reference for driver direct is LibreVR ReVive, which does exactly the opposite (implements an Oculus compositor using OpenVR). Historically, driver direct was designed for Oculus headsets. Microsoft WMR didn't make any changes to that interface when the WMR driver for OpenVR was developed AFAIK.

I'll take a look than, thanks!

**Comment by sergioberg** [comment]
Fixed in beta 1.22.5

Seems to be fixed with:

![image](https://user-images.githubusercontent.com/12216723/161485112-b696e347-70bc-4f15-ae0c-533e9116c221.png)

taken from here: https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setprocessinformation

**Comment by sergioberg** [comment]
Tried this code for Quest 2, helps too, and can be used for nonbeta SteamVR:
![image](https://user-images.githubusercontent.com/12216723/161504866-a3941444-265b-4503-ab79-bdd48c64d1a5.png)

**Comment by bernhardberger** [comment]
This has again become relevant imho with the Pico Neo 3 Link.. latest SteamVR beta as of today.

**Comment by sergioberg** [comment]
> This has again become relevant imho with the Pico Neo 3 Link.. latest SteamVR beta as of today (only trsted it with the current SteamVR beta). No problem in Windows 10 but in W11 it has all the symptoms and effects discussed in this very issue.
> 
> Oculus seems to have solved it by now.

I don't think so.
This has nothing to do with any headsets. This only applies to process timers settings in Windows 11. It's fixed in SteamVR.
