### ISSUE TITLE
Driver can't activate devices

### ISSUE THREAD

**Issue by okawo80085** [ValveSoftware/openvr#1643]
This is not really a bug, but its not obvious either, and it can be frustrating nonetheless if you encounter it for the first time.

If there is no active HMD (and `"requireHMD"` is not set to false in the `"steamvr"` section of vrsettings) none of the devices your driver tries to active will ever get activated.
And it's confusing because in driver logs it still looks like they are getting activated
```
...
Thu Mar 10 2022 11:19:39.054569 - Driver '<driver name>' started activation of tracked device with serial number '<device serial number>'
...
```
But the device's `Activate()` method never gets called.

Honestly those logs can be improved a bit, but other than that the fix is simple:
Either have an active HMD or set `"requireHMD"` to false in the `"steamvr"` section of vrsettings

The latter can even be done automatically in your driver's `IServerTrackedDeviceProvider` implementation `Init()` method, e.g.
```c++
bool need_restart = vr::VRSettings()->GetBool("steamvr", "requireHmd");
if (need_restart) {
DriverLog("driver: 'requireHmd' is enabled, need a restart...\n");
vr::VRSettings()->SetBool("steamvr", "requireHmd", false);
return VRInitError_Init_Retry;
}
```
So yeah, weird issue, *not a bug*, but deserves to be documented.

**Comment by danwillm** [comment]
I am reasonably certain this can be resolved by setting `alwaysActivate` to true in the driver manifest.

For non-hmd tracked device, I think the behaviour is that if this key is not there/set to false, the device will not activate unless it uses the same tracking system as the hmd, which also includes if there is no hmd connected.

I don't think it's needed to force an update of `requireHmd` - I've never needed to go that far, and it's not a particularly nice solution either :P

You can see our example here: https://github.com/LucidVR/opengloves-driver/blob/develop/openglove/driver.vrdrivermanifest#L2

If you don't have a headset connected the gloves still activate, which I assume is the behviour you want?

**Comment by okawo80085** [comment]
You have a point there, setting `alwaysActive` to true might not work in my case, but i like the idea :P

**Comment by okawo80085** [comment]
Yeah setting `alwaysAlive` to true did not work for my driver, but instead my driver temporarily disables `requireHmd` and resets it on my driver's cleanup if it was on.

**Comment by okawo80085** [comment]
Also im closing this because this is not really a bug and there are multiple working solutions, but more discussion on the topic is always welcomed!

**Comment by danwillm** [comment]
just to make sure, it's `alwaysActivate` not `alwaysAlive`.

**Comment by okawo80085** [comment]
> just to make sure, it's `alwaysActivate` not `alwaysAlive`.

Yeah tried that, still get the behavior described originally.

**Comment by AmberElferink** [comment]
I have a similar issue. Activate does not get called for my driver, while the messages show the same as above. I have a Windows Mixed Reality headset attached, but that apparently does not trigger it. Setting requireHmd=false does trigger it, however, then it does not recognize my WMR headset anymore. I did set alwaysActivate=true. Runframe weirdly does get called correctly every frame.

I have one other example driver, which should display exactly the same behaviour (I largely copied the files) (https://github.com/finallyfunctional/openvr-driver-example). Both drivers have alwaysActivate=true. However, that driver's Activate does get called with the headset connected and even gets called twice when setting requireHmd=false (you also see two icons appearing in SteamVR).  I think there is some small detail somewhere that causes this within a driver, but I have been comparing and trying things for 8 hours now. It would be great to know what settings can cause Activate not to trigger.

**Comment by okawo80085** [comment]
Weird, my driver doesn't seem to call Activate twice on devices when an HMD is present, while at the same time if `requireHMD` is set to true without and HMD present none of them have their Activate called at all.
Having `alwaysActivate` on or off didn't magically make SteamVR call my device's Activate methods.

I really don't have the time to look at the driver you linked, but my driver is open too, so you can compare them yourself if you want to.
My driver source: https://github.com/HoboVR-Labs/hobo_vr/tree/driver_madness_7/driver
My driver builds (if you want to test it at runtime): https://github.com/HoboVR-Labs/hobo_vr/actions/workflows/cmake.yml?query=branch%3Adriver_madness_7++
