### ISSUE TITLE
Cannot read from camera video stream

### ISSUE THREAD

**Issue by Auruss** [ValveSoftware/openvr#165]
I initialized the video stream service without any errors. Once I try to read from that stream using GetVideoStreamBuffer(..) I get VRTrackedCameraError_InvalidFrameHeaderVersion as an error.
What exactly does it mean? Would be nice to get a human-readable error when using the GetError... function.

**Comment by apseeler** [comment]
You need to ensure that if you want the frame header from GetVideoStreamFrameBuffer() via passing in a vr::CameraVideoStreamFrameHeader_t *pFrameHeader that you also pass the uint32_t nFrameHeaderSize to the size of that structure, which we are using for structure versioning.

What is the size you see for vr::CameraVideoStreamFrameHeader_t ?

**Comment by Auruss** [comment]
Ooh okay I see, I'm binding against rust and It was 104 instead of 100. I'm sorry I didn't think about the size. Thanks for your help!
