### ISSUE TITLE
Controller bindings failed to work since SteamVR updates to 1.22

### ISSUE THREAD

**Issue by inlet511** [ValveSoftware/openvr#1659]
**Detail information and files need to reproduce the bug**:
[bug report.zip](https://github.com/ValveSoftware/openvr/files/8797134/bug.report.zip)

**Summary**:
**Operating System**: Windows 10 Education Edition, 64bit
**Operating System Version**: 20H2
**Operating System Internal Version**: 19042.1706

**Issue**: Input binding stopped working for custom Open VR driver in games since updating SteamVR to version 1.22

**How to Reproduce Issue**: 
1.	Connect VR hardware properly, like any version of Vive or Oculus.
2.	Extract my file attachment, Copy folder Driver_and_source/Driver/sitwalk folder to Steam VR Driver folder(e.g. C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers)
3.	Start Steam and Steam VR. Open the game “Halflife:Alyx”(Or any other VR games that supports continuous movement)
4.	From the small Steam VR window, go to Devices>Controller Settings>Test Controllers, Switch to “#/USER/TREADMILL”, and try to press Keys W A S D on keyboard, there should be reaction in the UI showing that this custom binding is working correctly. In the real-world driver, the input is driven by our hardware, but here for simplicity, I’m using keyboard for demonstration. 
![a](https://user-images.githubusercontent.com/8900169/170959791-d823b059-48c0-4058-b8f8-0337258461a5.png)
![b](https://user-images.githubusercontent.com/8900169/170959846-cc798d2c-38cc-4ec9-9abc-233aef450f56.png)

 
5.	Than go to Manage Controller Bindings, do this:
 ![c](https://user-images.githubusercontent.com/8900169/170959945-3e31c40b-a64e-4b2a-8360-7a9d7f12d026.png)
Make sure “Current Controller” is set to sitwalk_controller, and press “Create new bindings” or “Edit” the current binding according to the menu context.
 
![d](https://user-images.githubusercontent.com/8900169/170960019-ae202b90-b0ba-43d4-8eb3-5dfba0e37f4d.png)

6.	Use Alyx for example, set the movement tab properly using bindings for Vive controller or Oculus Touch for reference. Here I’m using this binding: 
![e](https://user-images.githubusercontent.com/8900169/170960095-5846827d-afcf-431f-9caa-14f0d8ed214f.png)

The same bindings for Vive Controller is:
 
![f](https://user-images.githubusercontent.com/8900169/170960172-65c10f80-2225-4b1e-9182-59278627bf84.png)

And for Oculus Touch:
![g](https://user-images.githubusercontent.com/8900169/170960212-815b1262-b728-4755-966d-4709590c52b9.png)

 So I Believe it’s the correct settings.

7.	In the game, set the controlling style to “Continuous movement”

**Bugs**:
I can’t control movement of character in game using WASD key. Actually no response in game at all.

**What to Expect**:
Since both the Vive controller and Oculus Touch controls the movement well in game, I’m expecting my custom controller do the same.

**Extra Information**:
I did make it work before I updated Steam to the newest version, that was in March 17th this year. The bindings were a little bit different though, it was like this:
![h](https://user-images.githubusercontent.com/8900169/170960288-6973a822-40b9-482b-8e87-1fd93dec749d.png)
 
This binding also used bindings for Vive Controller and Oculus Touch as references, but now it changed. I also tried bindings like this but it doesn’t work.

**Comment by nnuber** [comment]
I tested your driver and was not able to reproduce the problem. Using WASD did move me in HL: Alyx. I tested with the public version of SteamVR 1.22.12.

Please reproduce the problem and upload a SteamVR system report.

**Comment by inlet511** [comment]
> I tested your driver and was not able to reproduce the problem. Using WASD did move me in HL: Alyx. I tested with the public version of SteamVR 1.22.12.
> 
> Please reproduce the problem and upload a SteamVR system report.

Hi nnuber, It's very exciting to hear that you got it working! Thank you!
I tried on two computers but both failed, can't move with WASD on keyboard.(I've noticed that after clicking the WASD keys, the vive controller movement also stopped working for several seconds before it works well again.)
Attachments are the two copies of system reports.
Thanks a lot!
[SteamVR-2022-06-02-PM_12_13_43.txt](https://github.com/ValveSoftware/openvr/files/8820803/SteamVR-2022-06-02-PM_12_13_43.txt)
[SteamVR-2022-06-02-PM_12_35_25.txt](https://github.com/ValveSoftware/openvr/files/8820805/SteamVR-2022-06-02-PM_12_35_25.txt)

**Comment by nnuber** [comment]
The issue could be in your bindings. I am testing using the default bindings that you include in your driver. From the system report, I see that you are using your own custom bindings from the workshop:
`(sitwalk_controller) attempting to load current setting config from vr-input-workshop://2812053822`

In your most recent workshop binding file (which may not exactly be the one above), you have configured the treadmill to teleport instead of walk:
`             {
               "inputs" : {
                  "east" : {
                     "output" : "/actions/move/in/teleport"
                  },
                  "north" : {
                     "output" : "/actions/move/in/teleport"
                  },
                  "south" : {
                     "output" : "/actions/move/in/teleport"
                  },
                  "west" : {
                     "output" : "/actions/move/in/teleport"
                  }
               },
               "mode" : "dpad",
               "parameters" : {
                  "sub_mode" : "touch"
               },
               "path" : "/user/treadmill/input/joystick"
            },`
            
But in your manifest binding file, it is correctly configured to walk:
`            {
               "inputs" : {
                  "east" : {
                     "output" : "/actions/move/in/walk"
                  },
                  "north" : {
                     "output" : "/actions/move/in/walk"
                  },
                  "south" : {
                     "output" : "/actions/move/in/walk"
                  },
                  "west" : {
                     "output" : "/actions/move/in/walk"
                  }
               },
               "mode" : "dpad",
               "parameters" : {
                  "sub_mode" : "touch"
               },
               "path" : "/user/treadmill/input/joystick"
            }`

Try using your default binding file and see if it works.

**Comment by inlet511** [comment]
> The issue could be in your bindings. I am testing using the default bindings that you include in your driver. From the system report, I see that you are using your own custom bindings from the workshop: `(sitwalk_controller) attempting to load current setting config from vr-input-workshop://2812053822`
> 
> In your most recent workshop binding file (which may not exactly be the one above), you have configured the treadmill to teleport instead of walk:
> 
> ```
>              {
>                "inputs" : {
>                   "east" : {
>                      "output" : "/actions/move/in/teleport"
>                   },
>                   "north" : {
>                      "output" : "/actions/move/in/teleport"
>                   },
>                   "south" : {
>                      "output" : "/actions/move/in/teleport"
>                   },
>                   "west" : {
>                      "output" : "/actions/move/in/teleport"
>                   }
>                },
>                "mode" : "dpad",
>                "parameters" : {
>                   "sub_mode" : "touch"
>                },
>                "path" : "/user/treadmill/input/joystick"
>             },
> ```
> 
> But in your manifest binding file, it is correctly configured to walk:
> 
> ```
>             {
>                "inputs" : {
>                   "east" : {
>                      "output" : "/actions/move/in/walk"
>                   },
>                   "north" : {
>                      "output" : "/actions/move/in/walk"
>                   },
>                   "south" : {
>                      "output" : "/actions/move/in/walk"
>                   },
>                   "west" : {
>                      "output" : "/actions/move/in/walk"
>                   }
>                },
>                "mode" : "dpad",
>                "parameters" : {
>                   "sub_mode" : "touch"
>                },
>                "path" : "/user/treadmill/input/joystick"
>             }
> ```
> 
> Try using your default binding file and see if it works.

Thank you Nanthan, you are right! It is the problem of bindings, somehow I've never tried the default bindings I wrote. It did work!
I also did experiments in other games, as long as the bindings are correct, everything works fine.
You saved my day, thanks a lot!
