### ISSUE TITLE
vrpathreg has a new output "NO DRIVER NAME FOUND" 

### ISSUE THREAD

**Issue by iesser** [ValveSoftware/openvr#1667]
When registering a custom driver using 'vrpathreg adddriver', the out put of 'vrpathreg show' shows "[ NO DRIVER NAME FOUND ]" in front of the external driver(s).
This message seems relatively new.

What does this message mean, and how can a driver be named correctly?

**Comment by okawo80085** [comment]
They changed the way external drivers are shown about 6 months ago, if a driver path entry has a `"[ NO DRIVER NAME FOUND ]"` in front of it's path that means SteamVR could not resolve the name of your custom driver, meaning that the names in your driver manifest and/or your driver dir and/or your driver binary are not matching.

**Comment by JoeLudwig** [comment]
You can see the format of the driver manifest here: https://github.com/ValveSoftware/openvr/wiki/DriverManifest
