### ISSUE TITLE
IVRDriverDirectModeComponent::GetFrameTiming() function doesn't work

### ISSUE THREAD

**Issue by leedc20** [ValveSoftware/openvr#1690]
I built a custom VR driver using IVRDriverDirectModeComponent in OpenVR 1.23.7.  I have tried to get a timing stats using GetFrameTiming() function. The function is called after Present(). But the all values in pFrameTiming structure are zero.  Anyone used this function? 

Thanks.

**Comment by Rectus** [comment]
The frame timing stats are written by the driver and read by applications. `GetFrameTiming()` only provides the data structure for your driver to write the data into.

**Comment by leedc20** [comment]
aha, got it. thank you.
