### ISSUE TITLE
When is OpenVR SDK 1.24.6 released? 

### ISSUE THREAD

**Issue by leedc20** [ValveSoftware/openvr#1691]
The latest version of SteamVR is 1.24.6.  I have checked the version of openvr_api.dll in C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win64.  The dll version was 1.24.6.  It would be cool if OpenVR 1.24.6 can be released as well.

**Comment by Rectus** [comment]
Valve only updates the SDK when there are new user-facing features exposed through the API. 1.24 didn't come with anything new that could be accessed through the API, so it doesn't make any sense to release an update.

**Comment by leedc20** [comment]
okay cool. thank you @Rectus
