### ISSUE TITLE
IVRCompositor::WaitGetPoses De-Sync frame rate. 90Hz HMD get 50-80FPS and results in jitter image.

### ISSUE THREAD

**Issue by chihirobelmo** [ValveSoftware/openvr#1692]
Hi, First of all, thanks to the great Open VR development.
I'm a member of a Flight Simulator development team. 
We are now developing VR mode for our product, **We use Open VR 1.23.7** and facing a problem.

**Vive Cosmos, Vive Cosmos Elite, and Pimax does not Sync FPS to half of their refresh rate, and we have a jitter image on HMD.**

VRHMD should sync its frame rate to its refresh rate or half of it.
Vive Cosmos has 90Hz so it should cap FPS to 90, if it's not available because of performance, it should cap FPS to 45.

However, **I get 50-80fps with Vive Cosmos.**
This makes the **image de-sync and the scene image look "half previous frame half current frame".**
Head rotation makes a jittery image.

With Rift S (80Hz) I get a 40fps cap and the scene is smooth and natural when I move my head.

If I understand correctly It is OpenVR API `IVRCompositor::WaitGetPoses` that waits until good timing to show a frame. which makes FPS cap. It seems the API is not working correctly for some VRHMDs but works OK for others.

Our render thread is like this (not exact same code as we can't public exact one...but the general idea):

```cpp
void RendererD3D11::renderThread()
{
    while (true)
    {
        if (WaitforSomethingAvailable())
        {
            somethingPrepareToRender();

            if (weHaveDrawList())
            {
                executeDrawList();

                if (IsVR())
                {
                    vr_compositor_->Submit(vr::Eye_Left,  &leftEyeTexture);
                    vr_compositor_->Submit(vr::Eye_Right, &rightEyeTexture);
                }

                presentFrameDrawList();
                releaseFrameDrawList();
            }
            if (IsVR())
            {
                vr_compositor_->PostPresentHandoff(); // removing it does not help.
                vr_compositor_->WaitGetPoses();
            }
        }
    }
}
```

can we get advice on how we can prevent de-sync?

Regards,

**Comment by chihirobelmo** [comment]
FYI we also tried 
```cpp
void RendererD3D11::renderThread()
{
    while (true)
    {
        if (WaitforSomethingAvailable())
        {
            somethingPrepareToRender();

            if (weHaveDrawList())
            {
                executeDrawList();
                presentFrameDrawList();
                releaseFrameDrawList();
            }
        }
        if (IsVR())
        {
            vr_compositor_->Submit(vr::Eye_Left,  &leftEyeTexture);
            vr_compositor_->Submit(vr::Eye_Right, &rightEyeTexture);
            vr_compositor_->WaitGetPoses();
        }
    }
}
```
but the same problem still persists.

**Comment by chihirobelmo** [comment]
![image](https://user-images.githubusercontent.com/32677587/194742884-80c88826-4c30-4cac-931a-649332434b91.png)

I could confirm the same phenomenon with Open VR DX12 sample code.
I raised the rendering resolution to 500% to make this light demo drop FPS.
You can see FPS is between 11-22ms(90-45fps) but not capped to either value.

**Comment by Rectus** [comment]
The frame rate behavior sounds like the difference between asynchronous and synchronous reprojection. When only asynchronous reprojection is active, SteamVR will not immediately throttle the frame rate to half. Instead when a frame takes too long, `WaitGetPoses()` will return immediately instead of blocking, and you will see a variable frame time. This part sounds like normal behavior, and shouldn't cause any rotational jitter on its own.

Are you getting the same kind of jitter in the sample application?

**Comment by chihirobelmo** [comment]
> Are you getting the same kind of jitter in the sample application?

Yes. As the sample application is not that heavy performance I set the resolution to 500% from the SteamVR setting to drop FPS and I got the same jittery I see in our software. It has a cycle it jitters (no cap) and it rotates smoothly (with fps cap). Like the steam VR performance graph, I put above. (BTW our software doesn't output SteamVR graph somehow...)

**Comment by Rectus** [comment]
In that case, it sounds like it could be an issue with the setup. If other applications are also experiencing the same issue, it sounds like reprojection is broken overall.

I don't know if it is SteamVR itself or the headset vendors middleware that handles reprojection on those headsets, but it could be an issue on either side, or with GPU drivers.

**Comment by chihirobelmo** [comment]
> In that case, it sounds like it could be an issue with the setup. If other applications are also experiencing the same issue, it sounds like reprojection is broken overall.

However, I did not have such a problem so far with other VR titles... ex: DCS World, and Microsoft Flight Simulator. 
I'm going to re-check how it works in those other softwares again though.

**Comment by chihirobelmo** [comment]
2 other people on our team also reported the problem...

**Comment by chihirobelmo** [comment]
I don't think it's a setup problem as we have the same problem with the same device for the other 3-4 members now.
the problem also happens to the sample code. It seems Open VR side bug.

**Comment by Rectus** [comment]
Yeah, if it only affects apps compiled by you, and not other OpenVR apps, it does suggest something is up with the OpenVR SDK. You could try compiling with an older release, or swapping out openvr_api.dll with an older one to see if that changes anything.

**Comment by chihirobelmo** [comment]
![image](https://user-images.githubusercontent.com/32677587/195948477-deb74fcb-310f-4c22-8c6a-c537703f1e81.png)
 
We found that SteamVR Frame Timing is not catching our game framerate. Maybe this is why we can't get FPS cap with WaitGetPoses() as described in https://www.diva-portal.org/smash/get/diva2:1586436/FULLTEXT01.pdf _3.1. Synchronization_.

As far as I can think of we have WaitGetPoses() at our render loop though... is there anything that cause no FPS detect issue...or are we just not putting WaitGetPoses() logic in the right place in our codes??????

**Comment by Rectus** [comment]
That could be the case. `WaitGetPoses()` should be called as close as possible to starting the rendering, so after the game logic for the frame has been done. If I understand your pseudocode, it should probably be between `WaitforSomethingAvailable()` and `somethingPrepareToRender()`. It doesn't explain why it would affect the sample code though.

**Comment by chihirobelmo** [comment]
I checkout v1.10 of OpenVR and tried the sample code. somehow dx12 sample code has also had the same jitter since this version.
I even re-installed Windows10 pro yesterday so it should not be a setup issue.

![image](https://user-images.githubusercontent.com/32677587/195980194-8efaa895-f704-4d4a-84ee-d960302cbc7b.png)

maybe our "FPS not showing" problem can be not the reason for jittering, worth try fixing though.

**Comment by chihirobelmo** [comment]
I put a very simple clock counter for the open VR dx12 sample code:

```cpp
        clock_t start = clock();
	vr::VRCompositor()->WaitGetPoses(m_rTrackedDevicePose, vr::k_unMaxTrackedDeviceCount, NULL, 0 );
	clock_t end = clock();
```

the result was like 5-10ms
The counting rendering loop starts to end it's always 11ms.
(I still have a jitter on the sample code too though)

```cpp
	vr::VRCompositor()->WaitGetPoses(m_rTrackedDevicePose, vr::k_unMaxTrackedDeviceCount, NULL, 0 );
	clock_t end = clock();
        start = clock();
```

When I count the time for our game, WaitGetPoses only took 2ms.
However our rendering thread loop count around 60-70fps(16ms) for Vive Cosmos so WaitGetPoses is not waiting enough time for refresh rate sync... I wonder where another 6ms has gone...

**Comment by Rectus** [comment]
The important thing to check is whether `WaitGetPoses()` returns with consistent times relative to the headset VSync. 

Here is an example from the Unreal profiler for an app that stalls in the render thread every other frame (rendering at 120Hz). Note how the green `WaitGetPoses()` call at the bottom attempts to keep the end time consistent across frames.
![rendertiming_with_runningstart](https://user-images.githubusercontent.com/4642151/196150691-c66771e9-57b2-4fd5-9921-27cd56829e22.png)



I tested running the dx12 sample with an artificial sleep just before the submit calls, using a Valve Index with Motion Smoothing off (rotational reprojection only). I get a similar result in the frame timing, but no judder apart from what is normal for rotational reprojection.
![bild](https://user-images.githubusercontent.com/4642151/196152619-748fe467-3051-461b-bb34-965502a05e39.png)
![bild](https://user-images.githubusercontent.com/4642151/196152891-d62f024c-197f-489a-bdf3-1841083c9b70.png)
Note the red Late Start spikes in the CPU graph. They indicate that `WaitGetPoses()` has been called after its normal return time and will return immediately.

**Comment by Rectus** [comment]
It's likely up to the individual headset drivers to share the frame timing data with SteamVR. I don't have any non-native headsets to test with, so I'm not sure how much of the data each driver fills in.

**Comment by chihirobelmo** [comment]
`const float displayFreqHz = vr_pHMD_->GetFloatTrackedDeviceProperty(vr::k_unTrackedDeviceIndex_Hmd, vr::Prop_DisplayFrequency_Float);`

this returns my Vive Cosmos 90Hz(11ms) and Rift S 80Hz so Open VR should know it.

**Comment by Rectus** [comment]
I mean the data in the `Compositor_FrameTiming` struct. At least some of the data seems to be filled in by the driver, and it is the data the frame timing graphs are plotted from.

**Comment by chihirobelmo** [comment]
I have Rift S, Vive Cosmos, and Quest 2 now and other members use Reverb G2 and Pimax 8K+. Except for Rift S, all headsets have the same problem. I first thought its a Vive cosmos-specific problem because at first fewer members tested VR, but now I don't think it's an individual headset driver problem.......

Maybe we call API wrongly, we have a unique thread pool like the game simulation thread, and the render thread runs separately... but we are stuck here there are not that many unique ways to call API as long as if we simply Submit() WaitGetPoses() in the same render loop......no idea anymore.

**Comment by chihirobelmo** [comment]
I moved WaitGetPose() and Submit() to another thread that does a sim and renders the loop. The jitter became small. I find now Quest2(72hz) caps 36-72fps most of the time. with the same situation that Vive cosmos were running at 60fps. So VR sync seems working for Quest2.

I think we had 2 different jitter causes, one was coming from our thread loop miss sync...  I guess the left-right eye had a different frame time texture at certain frame rates, but the other jitter is coming from WaitGetPose() not working for some HMDs. Especially Vive Cosmos, it does not cap fps to 45 yet, it floats around 50-80 constantly. The jitter became small but there is a jitter still remains when I rotate my head. 

 So Open VR sync is working... but not for certain HMDs.

**Comment by Rectus** [comment]
Whether a headset caps at the half frame rate or not seems to depend on if the driver actively throttles it. If the headset does spacial reprojection (Asynchronous Space Warp, Motion Smoothing, Motion Reprojection), it will always throttle down and cap it as soon as it fails to reach the full frame rate. Otherwise it should not need to cap the frame rate directly, as getting a delayed frame should still allow it to be reprojected correctly. You can check if that is making a difference by turning off the spacial reprojection in the headset settings for the headsets that do cap it.

A possibility for why `WaitGetPoses()` isn't working is if there is something else in the application blocking trying to synchronize the frames. Make sure the Present call to the desktop window doesn't have VSync on it, and that nothing else if forcing VSync on.

**Comment by chihirobelmo** [comment]
> If the headset does spacial reprojection (Asynchronous Space Warp, Motion Smoothing, Motion Reprojection), it will always throttle down and cap it as soon as it fails to reach the full frame rate.

I find if I disable Asynchronous Space Warp from Oculus Debug Tool, Quest2 also de-sync (not cap frame rate to half of its refresh rate) so that I can have "in-between" FPS and can see small jittery. For Vive cosmos disabling or enabling Motion Smoothing does not help throttle down. Another teammate has Vive Cosmos Elite and seems Elite doesn't have Motion Smoothing! So yeah It seems special projection not working for certain HMDs......

**Comment by chihirobelmo** [comment]
> A possibility for why `WaitGetPoses()` isn't working is if there is something else in the application blocking trying to synchronize the frames. Make sure the Present call to the desktop window doesn't have VSync on it, and that nothing else if forcing VSync on.

Now here comes the possibility.

I find it caps FPS more often when I moved WaitGetPose and Submit to another thread, which is Simulation Loop Thread but also deciding which things to draw from which camera position and rotation... however, FPS still floats around between half and full refresh rate sometimes.

I'm guessing there is some kind of wait command that blocks WaitGetPose to predict the next frame comes in how many milliseconds... we have the render thread that runs in parallel with the sim loop, rendering the previous frame while the sim loop renders the next one.

```cpp
Renderer()->StartNewFrameDrawList();
WaitGetPose();
DrawFrame(drawList);
Submit();
Renderer()->waitFrameDrawListExecutionEnd();  // The next loop of renderer cannot begin until the previous one has finished. This wait happens here.
```

**Comment by Rectus** [comment]
Manually waiting for the rendering to be done sounds like it would cause the issues. If I understand it right, `WaitGetPoses()` will already wait for the frame to be done. It's very unclear, but the documentation for `PostPresentHandoff()` in the header file suggests that the compositor can't do any of its rendering work until either it or `WaitGetPoses()` is called. Ideally `WaitGetPoses()` should be called as soon as possible after submitting the frame.

I'm also not sure if calling `WaitGetPoses()` from another thread works properly. It is usually called from the render thread.

I think this is the way the render thread loop should usually work. When the threads are synced and the sim thread has a frame ready in time, it should not block the render thread so that `WaitGetPoses()` gets called soon after the render is complete.
```c++
 WaitForFrameFromSimThread(); // Sync sim thread and render thread
 WaitGetPoses();
 Renderer()->StartNewFrameDrawList();
 DrawFrame(drawList);
 Submit();
 ```

If it is necessary to wait for the rendering to be done, the documentation for `PostPresentHandoff()` suggests that it should be called first like this.
```c++
 WaitForFrameFromSimThread();
 WaitGetPoses();
 Renderer()->StartNewFrameDrawList();
 DrawFrame(drawList);
 Submit();
 PostPresentHandoff();
 Renderer()->waitFrameDrawListExecutionEnd();
 ```

**Comment by Rectus** [comment]
> I'm guessing there is some kind of wait command that blocks WaitGetPose to predict the next frame comes in how many milliseconds...

Yes, the runtime keeps track of the headset VSync and blocks `WaitGetPoses()` until a few milliseconds before it to give the render thread as much time as possible. Valve calls this feature Running Start.

This presentation has a lot of information about how it works, but it's very old and some things in it are probably outdated. It even predates the `WaitGetPoses()` function. The running start is also longer than 2ms now.
https://www.youtube.com/watch?v=JO7G38_pxU4

**Comment by chihirobelmo** [comment]
I disabled the parallel rendering thread for VR mode so now it is rendered in the same thread.

```cpp
WaitGetPoses();

Renderer()->startNewFrameDrawList();

DrawFrame(drawList);

Renderer()->startFrameDrawListExecution();
Renderer()->presentFrameDrawList();
Renderer()->releaseFrameDrawList();

Submit();
PostPresentHandoff();
```

The head rotation has gone now and it's really smooth now.
However it jitters for head translation, and when I roll the in-game camera (so HMD is not moving but the player is rolling in the game thus the camera too) it jitters heavily.

**Comment by chihirobelmo** [comment]
I see some "blur" something different than jitters that not shows on the monitor when I roll the in-game camera...I believe this is some kind of projection artifact and is natural for VR games.

**Comment by Rectus** [comment]
That sounds like ghosting, which is normal for rotation-only reprojection.

**Comment by chihirobelmo** [comment]
I have Vive Cosmos and now head rotation/transition works smoothly now. However another member with Vive Cosmos Elite reports head rotation smooth bad head transition makes bad jitter. Is there a possibility of head transition only de-syncs the frame rate? or is it some kind of projection method problem? IIRC Vive Cosmos Elite has a unique projection method.

**Comment by Rectus** [comment]
HTC might also have their own implementation in the Vive software.

**Comment by chihirobelmo** [comment]
we found out we need to turn on "vive motion compensation" from vive console to remove transition jitter.
I believe our VR is almost complete thanks to your help @Rectus !

I'll keep this issue open for a while...maybe until we release the next version public with VR...in case of another jitter is found, but thx!

**Comment by chihirobelmo** [comment]
We've released FalconBMS4.37 which is the first version to support VR thanks to your help! @Rectus 
Closing this issue.
