### ISSUE TITLE
analog input from trigger

### ISSUE THREAD

**Issue by BBBBBbruce** [ValveSoftware/openvr#1696]
Hello,

I have read that the trigger can produce analog signal. I am trying to get the output to display on the debug console. 
However, I still get 0 and 1 only. I thought this should be something to do with the binding where in the controller_binding.json, I still set the 'mode' to 'button'. I could not find any document mention about the options of 'mode'. But I guess there is a 'mode' called 'trigger' as I can set it in SteamVR. But changing 'mode' to 'trigger' did not solve my problem.

All I did is taken the hellovr_opengl sample, add new bindings in controller.json and action.json. And then I add new handler to catch the data similar to the trackpad sample. The codes:

```
 {
   "inputs" : {
      "click" : {
         "output" : "/actions/demo/in/triggerAnalog"
      }
   },
   "mode" : "trigger",
   "path" : "/user/hand/right/input/trigger"
}
```

```
   {
      "name": "/actions/demo/in/triggerAnalog",
      "type": "vector1"
    }
```

```
float triggeranalog;
...
vr::InputAnalogActionData_t analogData_trigger;
if (vr::VRInput()->GetAnalogActionData(m_actiontriggeranalog, &analogData_trigger, sizeof(analogData_trigger), vr::k_ulInvalidInputValueHandle) == vr::VRInputError_None && analogData_trigger.bActive)
	{
		triggeranalog = analogData_trigger.x;
		
	}

std::cout << "trigger analog: " << triggeranalog << std::endl;
```

**Comment by Rectus** [comment]
The "click" input is boolean. Changing it to "pull" should give an analog value. 

I suggest looking at the binding menu in SteamVR for what inputs are available for each controller button. If you enable the debug options in the developer settings, it will also let you see and generate binding files directly from the menu.

**Comment by BBBBBbruce** [comment]
Thank you, that is very helpful. I found a file called 'bindings_vive_controller.json' under 
`Steam\steamapps\common\SteamVR\tools\steamvr_environments\game\steamtours\cfg\bindings_vive_controller.json`

I assume this contains all of the possible bindings I can use with my vive controller

**Comment by Rectus** [comment]
Yes, although it doesn't show some things, like which mode values and settings are available for each type of input.

**Comment by BBBBBbruce** [comment]
Are there any documentations might mention this?

**Comment by Rectus** [comment]
I don't think so, apart from looking what is available in the binding menu.

**Comment by BBBBBbruce** [comment]
I found this, it is quite useful: [Input Profile](https://github.com/ValveSoftware/openvr/wiki/Input-Profiles)
