### ISSUE TITLE
OpenVR CAPI references type VROverlayHandle_t without defining it

### ISSUE THREAD

**Issue by jherico** [ValveSoftware/openvr#17]
compile errors galore.  Corrected locally by declaring `typedef intptr_t VROverlayHandle_t;` before including openvr_capi.h

**Comment by lukexi** [comment]
Fixed!
https://github.com/ValveSoftware/openvr/commit/1daef6027f37a8ecb6b86439f66e04e74970b2b9#diff-1aed950f5e3868e2a73cdbd7ba439a2bR43
