### ISSUE TITLE
openvr-1.23.7.tar.gz release sha256 changed?

### ISSUE THREAD

**Issue by risa2000** [ValveSoftware/openvr#1721]
I have been using the release link to v1.23.7 (https://github.com/ValveSoftware/openvr/archive/refs/tags/v1.23.7.tar.gz) in my build with SHA256 check. It seems that the `sha256` of the `openvr-1.23.7.tar.gz` has changed from:
```
sha256: "CBE2AFBFC9ED9C6C5ED7DF7929F9B1F5ECFD858B849B377005D4881B72B910B3"
```
to
```
sha256: "E30D08882DCF4B697ED2A084DA8575B6B842239396F93E3A5F344CCFBD99D217"
```
Anyone knows what happened?

**Comment by risa2000** [comment]
It looks like a problem on my end. Tried on another machine and the calculated SHA256 came out with the first value. Cannot say right now, which machine is right, but chances are the first one is (if anyone can verify it for me, would be helpful).

**Comment by danwillm** [comment]
This was a change github made globally to the compression they use for archives, and so changed the checksums. They have since revert the change.

**Comment by kisak-valve** [comment]
Thanks @danwillm, https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/ for reference.
