### ISSUE TITLE
Use IVRDisplayComponent to display on two display(one display for left eys,the other for right eye)?

### ISSUE THREAD

**Issue by fww0071215** [ValveSoftware/openvr#1727]
Recently I'm working on the openVR to develop our own VR device driver,our VR system architecture is as follows: 

"the VR game" => "openVR"  => "our openVR driver" => "video card".the video card HDMI1 is connected to display1 the HDMI2 is connected to display2.

My progress is ：
I use the openVR driver sample display the VRgame screen（both left and right eys）on a sigle display , here is what I did：
	Use "simplehmd" sample and i changed some code, such as IsDisplayRealDisplay return true 、 set Prop_DisplayDebugMode_Bool false and changed some config  "window_width": 1920, "window_height": 1080.
	
I meet some problem :
1. My test environment is two 1080p display, and I can't display the game screen on two display, if I set the config "window_x": 0, "window_y": 0, "window_width": 3840, "window_height": 1080, the vrcompositor seems crashed, and nothing display on my screen;
2. I did many test, such as change the code IsDisplayRealDisplay return false, now the screen seems display well,  at least the window appears, but the window is full dark red, my VRgame screen cannot display on it, and after i click on the screen, the screen both left and right eys come to the primary screen, and now i can see the VRgame screen, openvr foreground display bug？.

Can anyone help me to solve this problem, I just want the vr display on two displays.

**Comment by TheDeveloperGuy** [comment]
I don't believe this is possible using the standard IVRDisplayComponent. You'll need to use IVRVirtualDisplay or IVRDriverDirectModeComponent, which give you the texture to display. You can then split that texture out to 2 displays or whatever else you need to do. (2) is a bug in IVRDisplayComponent when it is used in 'extended' mode. I doubt you will have any luck in getting that fixed, as no commercial headsets use that mode, and I don't think anyone is really working on OpenVR any more.

**Comment by fww0071215** [comment]
> n't think anyone is really working on

I see, Thanks bro.
