### ISSUE TITLE
how to rotate display in direct display mode ?

### ISSUE THREAD

**Issue by yangjiudan** [ValveSoftware/openvr#174]
my hmd is portrait, it could be recorgnized by steam vr through osvr and osvr-steamvr plugin.
but the image show on my hmd is rotated, is there a way to rotate it back?

**Comment by JoeLudwig** [comment]
You can rotate the views using the return values from ComputeDistortion in your driver. Rotate the UV values you return from that function and you will rotate the images as they are sampled in the distortion shader.

**Comment by yangjiudan** [comment]
@JoeLudwig, thanks. now I can rotate it.
but I found that the image in both eyes is not extramliy different, why is this happend?
(normaly the image in both eyes should be similar to look stereo)

**Comment by yangjiudan** [comment]
@JoeLudwig, thanks for your answer, maybe I didn't explane the problem clear, what I mean is rotate the whole display buffer my hmd display is portrait it need to recieve a 1080x1920 display buffer, but now the steam vr send a 1920x1080 buffer to my display. so only one eye showed on half of the display rotated 90 degree, and the other eye is out side the display screen..

**Comment by JoeLudwig** [comment]
Ah, I misunderstood.

What are you returning from GetWindowBounds? Sounds like it's 1920x1080. Should be the other way around. The two viewports should also be top and bottom instead of left and right.  Do those things and the trick to rotate with the distortion shader should work fine.

**Comment by yangjiudan** [comment]
thanks, yes I have did like you said and it works good.
but somettimes steamvr send a rotated image to my hmd, and after close steamvr and reopen it will act normal, it's strange.
