### ISSUE TITLE
ROS2 with openvr always fails

### ISSUE THREAD

**Issue by buckleytoby** [ValveSoftware/openvr#1744]
Hi, I'm porting robosavvy's vive_ros repo into ros2 and no matter what I do, every time I start a ROS2 node it always fails with error
`[ros2run]: Aborted`

I'm using Ubuntu 22.04, ROS2 Humble, openvr 1.23.7 cpp, and a NULL HMD
A very basic ROS2 node call with cause the failure:

```
#include "rclcpp/rclcpp.hpp"
int main(int argc, char **argv)
{
    rclcpp::init(argc, argv);
    auto node = std::make_shared<rclcpp::Node>("my_node_name");
    rclcpp::spin(node);
    rclcpp::shutdown();
    return 0;
}
```

**Comment by LeiYangJustin** [comment]
Any update? Same problem here
