### ISSUE TITLE
"simplecontroller" driver example does not work in new Unity Games

### ISSUE THREAD

**Issue by alecamaracm** [ValveSoftware/openvr#1752]
The controllers simulated by the "simplecontroller" example driver work in SteamVR home and old games, but they are not tracked in new Unity titles such as the last version of Beat Saber.

**Comment by danwillm** [comment]
Hi,
This is most likely due these games not having associated bindings for the example driver controller. You can generate the bindings by going to the bindings UI in steamvr. There's an example of how to do that here:
https://github.com/ValveSoftware/openvr/tree/master/samples/drivers/drivers/tutorial#bindings

**Comment by alecamaracm** [comment]
Hey, thanks for your response. It is working now.
And in case this also happens to someone else, make sure that you are in-game when you create the bindings, not just in SteamVR home. Bindings created for Beat Saber while in SteamVR Home are of type "legacy", which you won't be able to use once in-game if the game uses OpenXR
