### ISSUE TITLE
BUG: IVRVirtualDisplay is broken in SteamVR 2.0+

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#1775]
Other driver modes (IVRDriverDirectModeComponent and IVRDisplayComponent) are fine. My IVRVirtualDisplay-based driver works in every other SteamVR release that has supported IVRVirtualDisplay. 

Not sure exactly what the issue is yet, but essentially SteamVR doesn't give it frames.

**Comment by TheDeveloperGuy** [comment]
@jeremyselan @JoeLudwig Was it decided that developers using SteamVR features should be ignored if they report bugs in a SteamVR Beta? Was under the impression that that was both the point of the beta and the issue tracker...

**Comment by TheDeveloperGuy** [comment]
The problem, if anyone at Valve even cares, is that Present() is never called on the IVRVirtualDisplay subclass. Did Valve change the signature, fail to release an updated SDK, and break backwards compatibility with old drivers? That's what it looks like.

**Comment by TheDeveloperGuy** [comment]
In fact nothing is called on the IVRVirtualDisplay subclass. Even patching the "openvr_driver.h" for the IVRVirtualDisplay_001 version doesn't result in anything. So, all versions of IVRVirtualDisplay are completely broken in SteamVR 2.0. Great stuff.

**Comment by TheDeveloperGuy** [comment]
No error messages in either vrserver.txt or vrcompositor.txt, just doesn't work. Wonderful QA, Valve!

**Comment by TheDeveloperGuy** [comment]
In the absence of anyone at Valve ever reading or addressing this, it can be assumed that support for IVRVirtualDisplay is no longer available in SteamVR 2.0+. Anyone relying on that for their driver is SOL and will have to find alternatives.

**Comment by TheDeveloperGuy** [comment]
Even going back to OpenVR SDK 1.0.13, the last version to support IVRVirtualDisplay_001, doesn't help. IVRVirtualDisplay is broken and there's no way around it.

**Comment by kisak-valve** [comment]
Hello @TheDeveloperGuy, per "A fix for IVRVirtualDisplay interface." in the [2.0.10 SteamVR beta](https://steamcommunity.com/games/250820/announcements/detail/3739736044852822548) update, please opt into SteamVR's beta client and retest.

**Comment by TheDeveloperGuy** [comment]
Fine, it's fixed. We'll never know how Valve managed to get untested code released. Until the next show-stopper bug that could have been avoided if they tested properly, did code reviews or paid attention to bug reports... I am NOT happy with this mess. I had to come back early from vacation to work around this.
