### ISSUE TITLE
When steamvr is updated from 1.27.5 to 2.0.8, the custom driver cannot run properly.

### ISSUE THREAD

**Issue by 2621690255** [ValveSoftware/openvr#1779]
As the title says, How should I solve this problem, or will the official update the driver sample?
Or does anyone know how to downgrade steamvr?

**Comment by 7ep3s** [comment]
if your problem is that the vr window disappears after launching steamvr, try this

[https://github.com/ValveSoftware/openvr/issues/1780#issuecomment-1821645037](https://github.com/ValveSoftware/openvr/issues/1780#issuecomment-1821645037)
