### ISSUE TITLE
OpenVR SDK 1.26.7 AccessViolationException report

### ISSUE THREAD

**Issue by kpbg** [ValveSoftware/openvr#1782]
Hi Valve,

I have updated our C# project to the latest SDK + DLL
Now, every time I add a new desktop window to the SteamVR dashboard, our project crashes with AccessViolationException.
I have been able to duplicate this behavior on multiple PCs and it should be easy to reproduce:
- Start Steam
- Start SteamVR
- Add <any> of your desktop apps to the SteamVR dashboard

Other than the "AccessViolationException", Visual Studio doesn't provide any other details.

Could you please look into it?

Another one that I'm not sure if it is openvr or SteamVR or Steam related, but regardless if "Show Desktop Tabs" is set to "On" or "Off", the desktop tabs are allowed on the dashboard. The only way to temporarily get rid of them is by exiting Steam. Then SteamVR reverts to the previous layout and the tabs are not there.  Probably nothing to do with openvr, but I'm mentioning it just in case.

**Comment by zite** [comment]
Are you saying SteamVR crashes or your application? If its SteamVR can you provide the crash dump? (C:\Program Files (x86)\Steam\dumps). Does it only crash with your application's window or are you getting errors trying to pin all desktop windows?

**Comment by kpbg** [comment]
> Are you saying SteamVR crashes or your application? If its SteamVR can you provide the crash dump? (C:\Program Files (x86)\Steam\dumps). Does it only crash with your application's window or are you getting errors trying to pin all desktop windows?

It's my application that crashes. It stays still and does nothing and as soon as I use the plus icon from the new SteamVR Dashboard (the new one that has the deeper Steam integration) and add any of my running programs (let say Chrome) as an Overlay, my app crashes. If I just press the plus button and then close it without adding any program, my app doesn't crash. I'm heavily utilizing OpenVR for over 5 years and there is no other case when my app crashes. As soon as I do the described step, it crashes. If I could hide the Desktop Tabs, that would be good enough, but this SteamVR option doesn't work with the new update (it only works when I [Exit] Steam).

**Comment by zite** [comment]
I'm not seeing this happen with other overlays so I'll need some more information. What is your application? Can you reproduce the problem and then create a system report? SteamVR Menu -> Create System Report. Email that to me with the relevant vrclient log. You should find a log in C:\Program Files (x86)\Steam\logs that starts with vrclient_[name-of-your-app].txt. keithb@valvesoftware.com

**Comment by kpbg** [comment]
Closing the issue. 

It was caused by not setting capacity to the StringBuilder that's supplied to GetOverlayName and GetOverlayKey
