### ISSUE TITLE
Support Array Texture Submission in D3D12

### ISSUE THREAD

**Issue by cshenton** [ValveSoftware/openvr#1792]
As far as I can tell, OpenVR supports array texture submission on OpenGL, Vulkan, and Metal, but not D3D12.

Could you please add support for array texture submission in D3D12? Any reasonably efficient VR renderer will output either to an array texture or a side-by-side, so using OpenVR means a redundant copy.

Presumably Valve has codepaths for D3D12 array submission internally since it's a requirement for OpenXR, so I'd really appreciate it if you exposed those to OpenVR as well.

**Comment by aleiby** [comment]
Give this a try: https://github.com/ValveSoftware/openvr/blob/v2.2.3/headers/openvr.h#L3497

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by cshenton** [comment]
Would appreciate more info. Is this indicating D3D12 is not a well supported API going forward? Given this feature is supported in other APIs.
