### ISSUE TITLE
Unexpected projection matrix extents for FOV calculation

### ISSUE THREAD

**Issue by UltraEngine** [ValveSoftware/openvr#1798]
When using ivrsystem->GetProjectionRaw() my top and bottom extents are not the same.

With an HTC Vive, the top angle is -55.7750092 degrees and the bottom angle is 55.6199341.

Why this discrepancy? This makes some basic 3D math in shaders not work. Is this a bug? I have never seen a projection matrix that didn't point straight forward.

```c++
float left, right, top, bottom;
system->GetProjectionRaw(vr::Eye_Left, &left, &right, &top, &bottom);
float a0 = ATan(top);
float a1 = ATan(bottom);
```

**Comment by aleiby** [comment]
What Rectus said is the reason.
If your app cannot support off-center projection matrices, what you can do is take the max and build your own, then make sure to pass it back to SteamVR when you call IVRCompositor::Submit using `VRTextureWithDepth_t` (you can safely leave the depth texture handle null if that is problematic).

**Comment by UltraEngine** [comment]
Ah okay. I think this is basically what is going on. The screens are not facing the viewer straight-on:
![hmd](https://github.com/ValveSoftware/openvr/assets/64279130/91ed4a96-5e07-4b8d-b4f0-5de46c18706a)
