### ISSUE TITLE
Undistorted frame seems too strecht out

### ISSUE THREAD

**Issue by Outssiss** [ValveSoftware/openvr#1805]
Hello. I'm trying to access the camera frames on a HTC Vive Pro but the images I get using the function `GetVideoStreamFrameBuffer`
with the `VRTrackedCameraFrameType_Undistorted` appear to be really stretch out
![muymak](https://github.com/ValveSoftware/openvr/assets/102683728/28ceaa07-da27-49eb-8947-17a85e94e565)
Is this how they are supposed to look like?

I was expecting them look more like this:
![muybien](https://github.com/ValveSoftware/openvr/assets/102683728/6ca6790a-aebf-42c8-8953-1aa8baa463f1)
Which is how they look when activating the passthrough from the headset itself.

**Comment by Rectus** [comment]
I think the built-in undistortion is always set up to give you something that contains the entire frame, and with the Vive cameras you end up with that X shaped frame to fit in the corners.

If you are having problems with the end result mismatching the room view, check how you are reprojecting the images. The basic SteamVR room view is projected onto a cylinder a set distance from the camera.

**Comment by Outssiss** [comment]
> I think the built-in undistortion is always set up to give you something that contains the entire frame, and with the Vive cameras you end up with that X shaped frame to fit in the corners.
> 
> If you are having problems with the end result mismatching the room view, check how you are reprojecting the images. The basic SteamVR room view is projected onto a cylinder a set distance from the camera.

I was just getting the undistortes image like that, converting it to an OpenGL texture then submitting it back to the headset with IVRCompositor::Submit.

How should It be done then?

**Comment by Outssiss** [comment]
> The camera API just provides frames directly from the camera perspectives. It has no knowledge of the HMD display perspective or when the frames will be displayed for the user.
> 
> You will need to unproject the image coordinates into the roomscale tracking space using the camera projection matrices and the pose of the camera when the frame was taken (provided in the frame header). For the right camera, you will also need to transform the coordinate to the left camera space before using the pose.
> 
> Then project the coordinate with the regular HMD MVP matrix.
> 
> I have some old examples of modifying the OpenVR example to add passthrough support (they might need extra work to function with the Vive Pro frame format):
> 
> This one combines the unprojection and projection to a single reprojection matrix, and applies it in the vertex shader: https://gist.github.com/Rectus/521f6dc9d4294cc6107ec0e2226bb469
> 
> This one calculates the UV offset of the reprojection, and applies it to the vertices directly: https://gist.github.com/Rectus/4a52b4c662de0eb9e662f900d84df63d
> 
> I also have an OpenXR API layer and Unreal plugin that implement the reprojection: https://github.com/Rectus/openxr-steamvr-passthrough https://github.com/Rectus/UE4SteamVRPassthrough

For the last couple of weeks I've been trying to learn about the projection matrix and how they work. I belive I have them more or less figured. I still need to learn how shaders work but it's progress at least. The thing I don't get right now is how to access the image coordinates to then unproject them.

**Comment by Rectus** [comment]
Sorry, my explanation was kinda bad, I still have barely any idea of what I'm doing, even though I've been at it for three years now (still with zero documentation available). 

Generally the shader provides the image coordinates, and you provide the matrix to it and do the math to reproject the coordinates and sample the image at the result. I'm not sure what the best practices are here, all the methods I've found are pretty roundabout.

In my first example, in the vertex shader, the reprojection is applied to the vertices of a quad that fills the screen-space. This causes the quad to move, so that the fragment shader will sample the image at the right coordinates. In this case you only need to calculate a projection matrix and multiply it with the vertex coordinates in the shader (note that the example has the matrix split into two parts applied on after the other).

**Comment by Outssiss** [comment]
> Sorry, my explanation was kinda bad, I still have barely any idea of what I'm doing, even though I've been at it for three years now (still with zero documentation available).
> 
> Generally the shader provides the image coordinates, and you provide the matrix to it and do the math to reproject the coordinates and sample the image at the result. I'm not sure what the best practices are here, all the methods I've found are pretty roundabout.
> 
> In my first example, in the vertex shader, the reprojection is applied to the vertices of a quad that fills the screen-space. This causes the quad to move, so that the fragment shader will sample the image at the right coordinates. In this case you only need to calculate a projection matrix and multiply it with the vertex coordinates in the shader (note that the example has the matrix split into two parts applied on after the other).

Okay I think I understand. The "scene" is just one (or two? because of both eyes) quad that fills the entire screen and the images obtained from the camera are put on the quad and then the matrix are applied to the vertex of said quad/s. That's the general idea at least?

**Comment by Rectus** [comment]
You got it. In the example it's two different quads, so they each have half the UV range for their own halves of the frame texture.
