### ISSUE TITLE
Steam Link: Event VREvent_StandingZeroPoseReset not triggered when using Steam Link

### ISSUE THREAD

**Issue by alex-freeaim** [ValveSoftware/openvr#1807]
# Overview
When using the new Steam Link app from the Meta Quest store, the recenter button that is normally on the Steam VR dashboard is no longer there. Instead, the user recenters by holding the right Oculus button down for a few seconds. But this does not trigger the VREvent_StandingZeroPoseReset event.

SteamVR: 2.2.4
HMD: Quest 2
OS: Windows 10
SDK: 1.26.7

#  Steps to Reproduce

1. You can create a driver with code like the following:
```c++
vr::VREvent_t event {};
while (VRServerDriverHost()->PollNextEvent(&event, sizeof event)) 
{
    switch (event.eventType) 
    {
        case vr::VREvent_StandingZeroPoseReset:
            // log a message
            break;
...
```
2. Use the Steam Link app to connect from the Meta Quest to Steam on a PC.
3. Recenter by pressing the right Oculus button for a few seconds.

Expected:
The VREvent_StandingZeroPoseReset event is triggered causing a log message to show up.
Actual:
The VREvent_StandingZeroPoseReset is not triggered, so no log message shows up.

# Work Arounds

By viewing the Steam VR dialog on the desktop (see image), the recenter option can be pressed, which does trigger the event.

![image](https://github.com/ValveSoftware/openvr/assets/137712797/5e1fa05a-1a28-4122-a887-afa90ff1bdea)

Another workaround is to listen to the VREvent_ChaperoneFlushCache event instead, which is triggered when the playspace is recentered with Steam Link.

**Comment by alex-freeaim** [comment]
Just an update after using the VREvent_ChaperoneFlushCache event for a few weeks. We've found it to be an unreliable indicator as to when an actual recenter happens. This event gets triggered in other scenarios so relying on it will result in many false positivies.

**Comment by danwillm** [comment]
Hi,
This is fixed on steamvr beta, could you opt into it and let me know if it works for you?
Thanks.

**Comment by alex-freeaim** [comment]
Hey Dan. Just tested it and it's now working. The VREvent_StandingZeroPoseReset event is detected when I reset my playspace center while using Steam Link. Thanks!
