### ISSUE TITLE
Models missing from openvr demos

### ISSUE THREAD

**Issue by RubenGarcia** [ValveSoftware/openvr#183]
When I run the demos, I get the following warnings:
Unable to load render model lh_basestation_vive
Unable to load render model for tracked device 1 (lighthouse.lh_basestation_vive)
Unable to load render model vr_controller_vive_1_5
Unable to load render model for tracked device 3 (lighthouse.vr_controller_vive_1_5)

Where can these models be found?

**Comment by RubenGarcia** [comment]
The models are in
C:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources\rendermodels
But I can't seem to get openvr to find them.

**Comment by RubenGarcia** [comment]
I did a DrMemory drstrace.
When openvr tries to open the obj files, a straneous "\??\" is inserted at the beginning of the string and the open fails.

NtCreateFile
	arg 0: 0x000000000508f2b8 (type=HANDLE*, size=0x8)
	arg 1: 0x80100080 (type=unsigned int, size=0x4)
	arg 2: len=0x30, root=0x0, name=248/538 "\??\C:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources\rendermodels\lh_basestation_vive\lh_basestation_vive.obj", att=0x42, sd=0x0000000000000000, sqos=0x000000000508f2a8 (type=OBJECT_ATTRIBUTES*, size=0x8)
	arg 3: 0x000000000508f2c8 (type=IO_STATUS_BLOCK*, size=0x8)
	arg 4: <null> (type=LARGE_INTEGER*, size=0x8)
	arg 5: FILE_ATTRIBUTE_NORMAL (type=named constant, value=0x80, size=0x4)
	arg 6: FILE_SHARE_READ|FILE_SHARE_WRITE (type=named constant, value=0x3, size=0x4)
	arg 7: FILE_OPEN (type=named constant, value=0x1, size=0x4)
	arg 8: FILE_SYNCHRONOUS_IO_NONALERT|FILE_NON_DIRECTORY_FILE (type=named constant, value=0x60, size=0x4)
	arg 9: <null> (type=<struct>*, size=0x8)
	arg 10: 0x0 (type=unsigned int, size=0x4)
    succeeded =>
	arg 2: <NYI> (type=PORT_MESSAGE*, size=0x8)
	retval: 0x0 (type=NTSTATUS, size=0x4)
    succeeded =>
	arg 0: 0x000000000508f2b8 => 0x35c (type=HANDLE*, size=0x8)
	arg 3: status=0x0, info=0x1 (type=IO_STATUS_BLOCK*, size=0x8)
	retval: 0x0 (type=NTSTATUS, size=0x4)

**Comment by RubenGarcia** [comment]
On further study, it seems all file open operations have the "\??" prefix, and they work, so the error might be something else.

**Comment by sistevenrose** [comment]
@RubenGarcia ProcessMonitor (https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx) might be able to give you some clues.
