### ISSUE TITLE
Render texture validity

### ISSUE THREAD

**Issue by Merwan19** [ValveSoftware/openvr#186]
Hello,

I tried with an opengl texture that is not multisampled with IVRCompositor::Submit() and I have an error "VRCompositorError_InvalidTexture"

I render this texture onscreen and there is not problem :/

What are the constrains to validate a texture ?

Cheers

**Comment by ArionTT** [comment]
@Merwan19 Hi, Did you fixed this problem ?
I have meet same problem on Linux version. Can I know same result about the problem?
