### ISSUE TITLE
[BUG]: Cannot open the developer console, or close SteamVR

### ISSUE THREAD

**Issue by okawo80085** [ValveSoftware/openvr#1864]
So when i try to open the developer console or close SteamVR it wants to calls a `steamvr://*` link, but a handler for it is not set so i get a popup like this instead
![image](https://github.com/user-attachments/assets/477adc1a-f343-4c14-b9ab-cc9dfc83bea8)

calling `xdg-open` from a terminal with the webconsole link seems to work fine, but why isn't SteamVR calling it? Did the initial SteamVR setup fail to set something up for me?

My system is this:
```
Void 6.6.41_1 x86_64 AuthenticAMD notuptodate rrrrmmnFFFFFFF
```

Tested SteamVR version is this: `2.6.2`

**Comment by kisak-valve** [comment]
Hello @okawo80085, this is functionally the same issue as https://github.com/ValveSoftware/SteamVR-for-Linux/issues/710. Feel free to add a note to that issue report that `steamvr://` is also affected.

Closing as a duplicate.
