### ISSUE TITLE
why allow the install of something which is not ARM compatible?

### ISSUE THREAD

**Issue by tekntrash** [ValveSoftware/openvr#1867]
if you type pip install openvr in an a jetson orin it installs fine

then you try to run it and it complains it cannot find libopenvr_api_64.so, where it clearly it is there

then you do a "file libopenvr_api_64.so" and it tells you it is " ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=d2ec240be64cd7987918bc8341b8614d45859f28, not stripped" 

thus, NOT an ARM compilation!

Couldn't they just NOT make that pip available for ARM architectures then?

**Comment by kisak-valve** [comment]
Hello @tekntrash, this question should be directed at that maintainers of that python binding package.

Looks like https://pypi.org/project/openvr/ -> https://github.com/cmbruns/pyopenvr.
