### ISSUE TITLE
Missing 90Hz mode when using a PSVR2 headset with an AMD graphics card

### ISSUE THREAD

**Issue by Anheurystics** [ValveSoftware/openvr#1869]
The headset itself supports 90 and 120 Hz, but for some reason (either due to the runtime itself or the graphics driver), the 120Hz option is force selected automatically with no choice of switching. Seems to be a problem only with AMD devices, as Nvidia graphics cards can switch between 90 and 120 Hz.

**Comment by TheDeveloperGuy** [comment]
This is a "feature" of the AMD drivers, and the only way it can be worked around is by deleting the 120Hz modes from the PSVR2 EDID.

**Comment by Anheurystics** [comment]
Thanks for the reply, appreciate the work you've done on this. Is this something that can be overridden by Custom Resolution Utility? The VR2 headset only shows up on the list of displays when Direct Mode is disabled, so I'm not sure if modifications would carry over once Direct Mode is enabled.

**Comment by TheDeveloperGuy** [comment]
No idea. Why don't you try it? How are you disabling Direct Mode?

**Comment by Anheurystics** [comment]
Just tried it, Custom Resolution Utility doesn't show the VR2 headset as active in its default, Direct Mode state. Using SteamVR to disable Direct Mode (Three horizontal bar menu in SteamVR window > Developer > Developer Settings > Disable Direct DIsplay Mode) makes it appear in CRU, at the cost of the headset not working with SteamVR at all. So it doesn't seem like modifying the EDID works, at least for the PSVR2 adapter

**Comment by TheDeveloperGuy** [comment]
It's possible to use hardware to override the EDID, but unless you already have a DP-AUX emulator (that I produced in limited numbers, and have no plans to produce more of) that route is not available. I was able to get the Sony driver working on AMD @ 90Hz with some messing around. I'll see if I can package that into the soon to be available driver overrider that I'm making as part of my efforts to override/add to the behaviour of the Sony driver.

You can close this as it's not a SteamVR issue.

**Comment by TheDeveloperGuy** [comment]
Interesting, the latest PSVR2 firmware allows the headset to switch EDIDs. It offers the 90/120Hz EDID or 90Hz only by deleting the 120Hz EDID. 

Hello Sony! :)
