### ISSUE TITLE
OpenVR CAPI uses the bool type

### ISSUE THREAD

**Issue by jherico** [ValveSoftware/openvr#19]
a number of functions and structures in the C API reference bool, which is not a C type until C99.  the CAPI header should either avoid the use of bool or should include `<stdbool.h>` to ensure it's properly declared.

**Comment by lukexi** [comment]
Looks to be fixed in 0.9.12
https://github.com/ValveSoftware/openvr/blob/master/headers/openvr_capi.h#L39
