### ISSUE TITLE
Can't get Model, View, Projections matrices for GLSL

### ISSUE THREAD

**Issue by senseyan** [ValveSoftware/openvr#193]
Hi!

I'm new to openVR and maybe this is trivial but when I get the pose matrix for my model or the view matrices I have something like : 

```
0.951529 -0.164457 -0.259896 -0
0.0195898 0.875722 -0.482418  0
0.306934  0.453943  0.836497 -0
0.424304  0.0358461 0.232017  1
```

and for my shaders I need something like : 

```
A 0 0 X
0 B 0 Y
0 0 C Z
0 0 0 1
```

I can't use directly a MVP matrix for my shaders.

I get those values by using : 

```
vr::VRCompositor()->WaitGetPoses(m_rTrackedDevicePose, vr::k_unMaxTrackedDeviceCount, NULL, 0);
[...]
m_rmat4DevicePose[nDevice] = ConvertSteamVRMatrixToMatrix4(m_rTrackedDevicePose[nDevice].mDeviceToAbsoluteTracking);
[...]
m_mat4HMDPose = glm::inverse(m_rmat4DevicePose[vr::k_unTrackedDeviceIndex_Hmd]);
```

What are the values in those matrices? Euler angles? Quaternions representation? and how can I transform them intro "classical" opengl matrices?

Thanks !

**Comment by godbyk** [comment]
I think you might be expecting row-major matrices instead of column-major?

If you transpose the matrix, does it appear to be what you want?

**Comment by jherico** [comment]
```

**Comment by tamarous** [comment]
Hi, @senseyan, I encountered the same problem as yours. Have you now figured out the meaning of each elements in m_mat4HMDPose?

**Comment by rafaloz** [comment]
the first 3 columns are a rotation matrix that represents the orientation of the HMD and the last one is the position. the last row should be 0 0 0 1, to make easier computations with other matrices.
