### ISSUE TITLE
64-bit OpenVR library for macOS

### ISSUE THREAD

**Issue by mummey** [ValveSoftware/openvr#197]
Hello,

Thank you for providing the macOS version of the OpenVR library. Are there plans to offer a 64-bit version like on Windows and Linux? I want to use some other libraries with OpenVR but they are 64-bit only.

Thank you,
Brian Walsh

**Comment by kearwood** [comment]
It appears that the OSX libraries are universal 32bit + 64bit even though the directory has a "32" suffix.

**Comment by mummey** [comment]
Well what do you know... I suppose I should have just tried it out to see if it worked. Thank you.
