### ISSUE TITLE
Displaying Regular Desktop Windows on HMD Display

### ISSUE THREAD

**Issue by WaffleTime** [ValveSoftware/openvr#198]
Hello,

I'm essentially just looking to be pointed in the right direction for streaming individual windows or even the entire desktop to an HMD with OpenVR. 

I see that the Compositor is able to submit textures and this seems to be the main interface for drawing to the HMD. However, I'm not sure if OpenVR already has anything in place for displaying regular windows. So the real question is, is it going to be necessary to capture the contents of a window as a texture and submit that to the Compositor?

**Comment by JoeLudwig** [comment]
Yes, you'll need to capture the contents of the window as a texture and submit it to the compositor. That's how Desktop view in the dashboard works.  Virtual Desktop and other similar products do something similar.
