### ISSUE TITLE
Oculus Touch B and Y buttons not supported

### ISSUE THREAD

**Issue by Matt-Twistplay** [ValveSoftware/openvr#199]
The B and Y buttons on the Oculus Touch controllers don't appear to register in the ulButtonPressed flags of vr::VRControllerState_t.

e.g.
```
vr::VRControllerState_t state;
vr_system_handle->GetControllerState(right_device_index, &state);

if(state.unPacketNum != right_prev_packet_id) {
    
    //state.ulButtonPressed == 0 when B or Y buttons are pressed
    //state.ulButtonTouched == 0 also when B or Y buttons are touched
}

```
Interestingly, the packet number seems to change when B or Y are pressed, but the button flags don't.

All the other buttons on the Oculus Touch seem to work fine and the buttons on my Vive sticks do too.

**Comment by Matt-Twistplay** [comment]
To elaborate, the B and Y buttons do however, mimic the small black button that brings up the Vive menu stuff on the Vive sticks. Perhaps these buttons are not currently exposed for that reason. Is it possible to disable the Vive menu? Or map it to a more sensible button on the Oculus Touch if not? (e.g. the Oculus button).

**Comment by JeffLeinbaugh** [comment]
That is correct. B and Y are currently mapped to the SteamVR system button and not passed to the application. The Oculus button can't be used for this purpose since it is not accessible through the OVR API, and there is not a way to use a custom button remapping at this time.

**Comment by Matt-Twistplay** [comment]
Thanks for replying. Are you planning on fixing this before the Oculus Touch controllers are released? If not, when?

**Comment by AndreasHassing** [comment]
Any news on this @JeffLeinbaugh? 😃.

**Comment by JoeLudwig** [comment]
SteamVR now reserves the menu button instead of the B and Y buttons. That's the one on the left-hand controller that's in the spot opposite the Oculus button.  B and Y are now available to applications.

**Comment by AndreasHassing** [comment]
@JoeLudwig is there any documentation for this? I can't seem to find it anywhere. This issue and #323 both show up on Google when searching for Oculus Touch and OpenVR, but none of them describe this new functionality.
