### ISSUE TITLE
Readme is a text file instead of markdown/RST

### ISSUE THREAD

**Issue by gravyboat** [ValveSoftware/openvr#2]
Noticed the Readme is a text file and was going to change that, but it looks like this file is generated internally according to #1. Is it possible to modify this internally? Text gets kind of messy if the Readme expands anywhere past what it currently is, plus it just doesn't look as nice.

**Comment by JoeLudwig** [comment]
If the readme expands much beyond what it is right now, we can switch to markdown. Text works fine for two sentences, so for now this isn't worth changing.
