### ISSUE TITLE
Unable to Trigger Overlay in helloworldoverlay Sample

### ISSUE THREAD

**Issue by andrelevi** [ValveSoftware/openvr#20]
Hi,

A couple of weeks ago I spent some time developing a test QT widget based upon your `helloworldoverlay` sample.  I was using controllers with the non-GDC firmware dated 6/29/15 (or sometime in June).  At the time, I was able to show/hide the QT widget overlay fine via the tiny black button.

Today I downloaded the latest version of openVR and I am no longer able to trigger the overlay via the tiny black button.  I am also unable to spawn the overlay using the `helloworldoverlay` sample that I was forking off of before. It's been a couple of weeks since the last time I've used anything related to the openvr overlays, and a number of SteamVR updates have occurred since my last use, so I was wondering if out-of-sync software/firmware could causing the tiny black button input to not be recognized.

I was hoping that you guys might have an idea of why I am unable to spawn the overlay like before.  I'm on Windows 7 with the latest stable (non-beta) SteamVR plugin, and I can verify via the other SteamVR apps that the inputs on my controllers are being recognized (though no other apps use the black button, so I can't verify that input specifically).  I have tested with a controller using the  `vcf_wired_controller_vrc_v2.bin` firmware (dated 6/29/15, or sometime in June), and with a controller using the more recent 7/6/15 version of that firmware.

Any suggestions would be greatly appreciated.  Thanks for your time!

**Comment by JoeLudwig** [comment]
Did you actually show and hide your overlay in response to the system button? (That the tiny black button.) Or was it happening automatically?

This whole area is still in the works. We are hoping to make the updated system button support available in the next couple weeks. In the meantime you'll need to show and hide the overlay yourself. You could do that with the red (app menu) button or by running/stopping the app from outside of VR.

**Comment by andrelevi** [comment]
Before, simply clicking the system button would toggle the overlay automatically, without me needing to manually map any inputs or interface with the `COpenVROverlayController` class / `vr` namespace.  Things worked out of the box, so I was able to fork the `overlaywidget` files and start QT development immediately, while ignoring the inner workings of the `openvroverlaycontroller`.

I can't pinpoint any code in the `COpenVROverlayController` related to the toggling of the overlay. Can you give me an idea of any flags/calls I might need to touch to toggle the overlay manually?  Thanks

**Comment by JoeLudwig** [comment]
Take a look at VROverlay()->ShowOverlay( <handle>). You'll need to create the overlay with VROverlay()->CreateOverlay() instead of CreateDashboardOverlay() until we get the rest of the dashboard shipped.

**Comment by andrelevi** [comment]
Gotcha. Thanks Joe. Will give that a shot.

**Comment by andrelevi** [comment]
So I tried `CreateOverlay()` instead of `CreateDashboardOverlay()` along with calling `ShowOverlay()` after the `SetWidget()` code.  Calling `ShowOverlay()` does result in `IsOverlayVisible()` returning true, but still no overlay is shown.

I was wondering if maybe the overlay is actually being shown, but at a position that is unviewable (as in the default position, as I'm not manually setting any positional data).  I remember that before you could aim where you would spawn the overlay.

Any other suggestions by chance?  Thanks

**Comment by JoeLudwig** [comment]
Your overlay is probably facing backwards and is being culled. I would try to figure out a space in world-space that makes it visible.

You could make that easier, probably, by making one of the buttons on the controller move the overlay to the controller's transform. That should make it easier to experiment with transforms and the like.

**Comment by andrelevi** [comment]
Hey Joe, I dug through the header declarations to try and piece things together, but I was having trouble figuring out how to get the numerous arguments needed for the chain of calls to position based upon the controller's transform matrix.

In the mean time, I've just been developing my Qt widget, which I assume will be a fairly easy drop in with the overlay/dashboard controller like it was before.  During my previous testing, I vaguely remember Qt animations being ~30-40 fps (eyed, I couldn't get an accurate profile when hooking into paint calls) when composited over a medium-intensity vr app.  Does this sound about right to you?  Btw, this was my observation when animating QObjects with QPropertyAnimation and changing position, so not with OpenGL or anything lower level.

I also faintly remember that the overlaycontroller specified widget dimensions of 1512x1680, and that smaller widgets would be scaled to fit, while larger widgets would overflow.  Is there any specific thinking behind that aspect ratio?  Or was it chosen randomly, and is subject to change?  Just curious, as our current widget designs are for a more standard ~16:9 aspect ratio.

Looking forward to the next push!

**Comment by JoeLudwig** [comment]
No idea about the frame rate of Qt animations, but it mostly doesn't matter. The compositor will draw at 90Hz and the overlays themselves can update at a slower rate.

We are expecting dashboard overlays to be 16:9 and 1080p is plenty of pixels. The HMDs coming out next year are about 1k x 1k per eye, so 1080p is going to be filtered down in any case.

**Comment by JoeLudwig** [comment]
We just pushed out a beta update with the dashboard present. You should now be able to call CreateDashboardOverlay and have it show up there.

If you run into specific bugs with dashboard overlays, please open new issues for them.
