### ISSUE TITLE
Driver_null, how to use second display.

### ISSUE THREAD

**Issue by nikitos1550** [ValveSoftware/openvr#202]
Hello!

How to put image on second display with driver_null, if I have two 1920x1080 monitors?
One is on the left (position 0,0), another is on the right (position 1920,0).

Are there any utility which can help ma check the actual position of monitors?

**Comment by JoeLudwig** [comment]
Take a look at the settings for the null driver. There are two to set window position, which you can set to 1920,0 to put the display on your second monitor:
https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L1626

**Comment by nikitos1550** [comment]
Yeah, but really I have issue, that on GTX1070 I still have picture on position 0,0. On Amd RX480 I just don`t see picture anywhere.
