### ISSUE TITLE
GetDeviceToAbsoluteTrackingPose: prediction interval is capped? Poses filtered?

### ISSUE THREAD

**Issue by echuber2** [ValveSoftware/openvr#206]
I'm working on some research related to pose prediction and perceived latency so I've been messing with the prediction interval that can be provided to GetDeviceToAbsoluteTrackingPose. Relatively large values (several seconds to many seconds) do not seem to produce the extreme response that I would have expected with a naive approach to the prediction; however, a small negative value does seem to produce the expected response. Is there a hard cap to the acceptable input range for this parameter? Can Valve say anything about the specific filtering method or prediction algorithm used? (I have been asking many questions about this function and WaitGetPoses. For research purposes I'm thinking I might have to implement my own prediction from scratch in order to make definitive statements about what is being expressed.)

**Comment by JoeLudwig** [comment]
The prediction time is clamped to dt = +/-100ms from an actual sample. dt is computed using the system time when the pose was calculated for (which will always be in the past) and now plus the requested prediction time. We maintain a pose history for 100ms, so total "backward prediction" can extend up to 200ms and will be more accurate. Obviously the smaller the prediction dt the more accurate the resulting pose will be.

The prediction model is very simple: 
  position_predicted = velocity * dt + position0
  (And the equivalent for rotation and angular velocity.)

There is enough error in the moment to moment acceleration that it isn't used for prediction.

**Comment by echuber2** [comment]
Thank you for the detailed response.

**Comment by echuber2** [comment]
Now I'm a little confused about the -200ms limit. Do you mean that for negative values in a range from [0,-100ms], GDTATP is automatically fetching a historical pose, while for values [-100,-200] it is calculating a backward prediction based on the oldest historical pose, and negative values beyond -200 are clamped? ***Or,*** do you mean that one could use GetFrameTiming to fetch an old pose and feed it to GDTATP, which only performs a numerical prediction and does not peek into the history itself? Also, it seems that GetFrameTiming's documentation claims it stores 128 frames of poses, which would be well over 1sec of pose history at 90Hz, not 100ms.

**Comment by JoeLudwig** [comment]
GDTATP ignores the contents of the pose and figures out what to return based on internal data. It has up to 100ms of history internally and will clamp to not predict more than +-100ms from any pose. That means best case if you predict backward -200ms it'll get the oldest pose (which is 100ms old) and predict backward 100ms from there.

Frame timing is a completely separate system and has its own limitations. It only stores poses for the HMD where GDTATP works on all devices. The poses stored in the frame timing data are not used in calls to GDTATP, they're just saved off post-prediction poses that would have been returned from WaitGetPoses on that frame.

**Comment by echuber2** [comment]
Thanks. It's been said that WaitGetPoses calls GDTATP internally to get the pose predictions, so I guess it is doing that and storing them in the buffer. Then if I wanted to replace GDTATP, I wonder if I could do it this way:

- call WaitGetPoses to get a mostly-accurate FrameTiming in the history
- call GDTATP manually with prediction time interval of 0 to get a baseline pose
- modify that pose based on my own prediction algorithm, and hope the timing data from the latest FrameTiming is still close enough

**Comment by JoeLudwig** [comment]
You could certainly give that a shot.  WaitGetPoses predicts forward to the time when the photons for that frame are going to come out of the display. You would need to do the same thing with your own predicted values.
