### ISSUE TITLE
GetEyeToHeadTransform

### ISSUE THREAD

**Issue by yqt2015** [ValveSoftware/openvr#207]
in head file, the is fuction is defined like this:  
virtual HmdMatrix34_t GetEyeToHeadTransform( EVREye eEye ) = 0;

Why return a 3X4 Matrix??  not a 4X4 Matrix.  Could anyone tell me why? thanks in advance

**Comment by echuber2** [comment]
You know the bottom row should be [0 0 0 1]. See ConvertSteamVRMatrixToMatrix4 in the hellovr sample.

**Comment by LibreVR** [comment]
As @echuber2 has said, the bottom row is constant. The first three columns describe the orientation and the fourth column describes the translation.

The only reason to make it a 4x4 matrix is to make it homogeneous so you can use it in matrix multiplications.

**Comment by yqt2015** [comment]
thx!
