### ISSUE TITLE
win64 debug

### ISSUE THREAD

**Issue by yahavt** [ValveSoftware/openvr#21]
While compiling the code in win64 i can't debug it..

**Comment by JoeLudwig** [comment]
Can you tell us more? There is a libopenvr_api.so.dbg file. Is it not loading for some reason?

Do you have the same problem with Linux32 or Windows?

**Comment by yahavt** [comment]
I work on windows environment.
I compiled my code with the win64 version of "openvr_api.lib", and I copy to my output folder "openvr_api.dll" and "openvr_api.pdb".

When I run the software in release mode it works, while in debug I get an exception.
When I debug the assemble code it looks like that in debug mode there is an internal call to raise an exception - 

`dynamic initializer for 'g_ThreadMainThreadID''(void)
    c:\buildslave\steamvr_rel_win32\build\src\common\vrcommon\threadtools.cpp
000000001C23444B  call        ThreadSetDebugName (01C21C8E0h)
ThreadSetDebugName(const char *)
    Plat_IsInDebugSession
    call        qword ptr [__imp_RaiseException (01C235080h)] 

Any thought?

**Comment by JoeLudwig** [comment]
Sorry about the Linux/Windows confusion. Apparently I can't read on Friday.

The mechanism to set a thread name on Windows is [kinda dumb](https://msdn.microsoft.com/en-us/library/xcb2z8hs.aspx). There is an exception thrown, but it is immediately caught and discarded. It's safe to ignore this exception.

In general I find it more useful to only break on C++ exceptions if they're unhandled. If you break on them all you'll hit things like this and a bunch of internal exceptions in third party libraries.
