### ISSUE TITLE
GetVideoStreamTextureGL() not working with Undistorted camera frame type

### ISSUE THREAD

**Issue by yhnchang** [ValveSoftware/openvr#212]
`VRTrackedCamera::GetVideoStreamTextureGL()` works perfectly with `VRTrackedCameraFrameType_Distorted` specified. However, whenever the frame type is changed to `VRTrackedCameraFrameType_Undistorted`, the function returns `VRTrackedCameraError_InvalidSharedTextureHandle (110)`.

`VRTrackedCamera::GetVideoStreamFrameBuffer()`, on the other hand, works with both frame types.

OpenVR Version: v1.0.2

**Comment by apseeler** [comment]
This is correct. 

There is no distinct GL texture handle for VRTrackedCameraFrameType_Undistorted.

Instead use the GL texture handle from **VRTrackedCameraFrameType_MaximalUndistorted** coupled
with the texture bounds from GetVideoStreamTextureSize() using **VRTrackedCameraFrameType_Undistorted** to identify the inscribed u/v subregion.

**Comment by yhnchang** [comment]
Thanks for the instruction! It works now. :)

**Comment by neworldforus** [comment]
Hi!
I received your email from you.
How can I have a look at what you all are working as I'm very new at this Githut?
I didn't know even that I subscribe to your thread(?). Do you call it the thread?

If then, what kind of the thread is it?
What kind of programming is being done?
How can I get to your thread?

**Comment by yhnchang** [comment]
@neworldforus Welcome to Github! This thread is ValveSoftware/openvr Issue #212. If you're reading this from an email notification then you can access this thread by the "View it on Github" link at the bottom of the mail. On this page, You can see your thread notification settings in the sidebar on the right. The Notification section, usually appears at the bottom of the sidebar, shows you the reason you are receiving notifications, along with a button to subscribe/unsubscribe to the notifications.
