### ISSUE TITLE
IVRSettings Interface not found

### ISSUE THREAD

**Issue by jrbudda** [ValveSoftware/openvr#218]
As of latest SteamVR beta and OpenVR 1.0.2 cannot get IVRSettings with version 001. Returns 105: Interface not found.

**Comment by JoeLudwig** [comment]
Are you calling from a driver or an application?

**Comment by jrbudda** [comment]
Application. The error goes away when opting out of the steamvr beta.

**Comment by JoeLudwig** [comment]
Can you post the line of code that's returning Interface not Found?   I'm not able to repro with this:

	vr::VR_GetGenericInterface( "IVRSettings_001", &error );

**Comment by jrbudda** [comment]
Hmm. Well I'm using the JOpenVR wrapper found here https://github.com/phr00t/jMonkeyVR/blob/master/src/jopenvr/JOpenVRLibrary.java

I had not noticed but the exact version string it is using is: 	
`public static String IVRSettings_Version = "FnTable:IVRSettings_001";`

It's only returning this error with IVRSettings in the beta build, tho, system, compositor, overlay all seem to work with the fnTable bit. I'm not entirely sure where that comes from. Will test without that in the string as soon steam finishes downloading the beta branch again.

**Comment by jrbudda** [comment]
After further experimentation the fntable: prefix seems necessary when calling from managed into native code and it's what the c# headers do. Removing the prefix does not cause the 105 error but any use of the function table causes memory access exceptions. Have had many bug reports of the 105 error, all fixed by opting out of steamvr beta.

**Comment by JoeLudwig** [comment]
This should be fixed in the latest beta update: http://steamcommunity.com/games/250820/announcements/detail/610621429037542937
