### ISSUE TITLE
SetGraphicsDevice is missing from header file

### ISSUE THREAD

**Issue by ennuma** [ValveSoftware/openvr#219]
From this link: https://github.com/ValveSoftware/openvr/wiki/IVRCompositor_Overview
It mentions SetGraphicsDevice which deos not exist in openvr.h anymore. Is this funciton deprecated or am I missing anything? Which function should I use to set graphics device now? 
Thank you in advance

**Comment by JoeLudwig** [comment]
IVRCompositor is no longer needed. The compositor figures out the graphics device based on the texture that is passed in.

I updated the Wiki to reflect that.
