### ISSUE TITLE
Maximum Qt Widget Size for Dashboards?

### ISSUE THREAD

**Issue by andrelevi** [ValveSoftware/openvr#22]
Hi, I noticed that the update yesterday no longer enforces 16:9 1080p, and that I can use up to ~21:9 1080p before any scaling occurs.  Can you please give me the exact maximum dimensions in pixels before scaling occurs?  This is so I know the hard limits for the size of my Qt widgets.  Thanks.

**Comment by JoeLudwig** [comment]
There is no maximum in pixels. The scaling happens in world-space units, so it's actually in meters.

The maximum aspect ratio is intended to be 48:9. If you see anything narrower than that scaling, please let us know and give us details about your overlay (or even better: a test project.)
