### ISSUE TITLE
Controller RenderModel is overly simplistic

### ISSUE THREAD

**Issue by ekmett** [ValveSoftware/openvr#222]
The RenderModels are provided as a sort of 'lowest common denominator' for interaction, but when sitting in the SteamVR home room you can look at the controllers and they'll show power usage, current state of the depressed trigger, finger placement on the touch pad, etc.

Using the controller model I can get access to through the OpenVR API, I can display none of these things. The controllers feel "dead" to users.

I can of course build my own models and manually articulate them, but then, of course, verisimilitude will be compromised should the user use different devices.

I realize that it would complicate the API tremendously, but this does feel like a pain point worth tracking here. That said, perhaps the resolution doesn't belong here but rather inside the SteamWorks API so they can provide detailed models to improve the cohesiveness of the design.

**Comment by jeremyselan** [comment]
The rendermodel API does provide the functionality you're looking for, sorry it's not more immediately obvious.  Please checkout the rendermodel 'component' API:
https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L2776

You can enumerate and draw each render model component individually (example components: trackpad, trackpad 'touch' indicator', trigger, etc).   GetComponentState(...) allows you to query dynamic object transforms and visibility.

The SteamVR home room functionality you refer to uses only this public API.  The simplified interface you mention is the lowest common denominator for users who don't want this more functional (and complex) API.

**Comment by jeremyselan** [comment]
Also see: 
https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L2677

RenderModel_ComponentState_t : mTrackingToComponentRenderModel is the transform matrix you'll want to support dynamic motion.

You should also obey the ( uProperties & VRComponentProperty_IsVisible ), otherwise components with dynamic visibility (such as the touch indicator) will always be drawn.

**Comment by ekmett** [comment]
Beautiful, thanks!

**Comment by elect86** [comment]
Isn't there a way to load the single components through `vr::VRRenderModels()->LoadRenderModel_Async(...)`?
