### ISSUE TITLE
QTableWidget extreme poor perf in overlays

### ISSUE THREAD

**Issue by rrkpp** [ValveSoftware/openvr#225]
Hi all,

Apologies if I'm missing something obvious, but it seems that Qt's QTableWidget performs really poorly exclusively in VR. I noticed my dashboard overlay would start to lag quite a bit with as little as 5 rows in a QTableWidget, but runs perfectly fine as a regular desktop application.  To test, I made a fresh Qt project consisting only of a QTableWidget filled with 50 simple QTableWidgetItems, which again ran perfectly on desktop and horribly in VR. 

I've attached the fresh Qt project with source as well as binaries for the VR overlay and desktop versions of the app for comparison. Having QTableWidget perform properly in VR would be extremely helpful in making useful dashboard overlays for OpenVR.

Thanks!

[TableTest.zip](https://github.com/ValveSoftware/openvr/files/410203/TableTest.zip)

**Comment by JoeLudwig** [comment]
This is something you'll need to take up with the Qt folks. Maybe they have performance problems rendering to textures?

**Comment by hanjiang08** [comment]
@rrkpp Hi, I cannot see any widget in the HMD when I run the sample "helloworldoverlay". I would like to know if the problem is related to my NVIDIA graphics card whose type is GeForce 940MX. Can you give my some suggestion?
Thanks.
