### ISSUE TITLE
Is OpenVR library free to use for commercial?

### ISSUE THREAD

**Issue by alexpeng3d** [ValveSoftware/openvr#231]
I am a VR developer, I think OpenVR library is a powerful VR library and
developers used this library can create his HMD quickly,  
We are developing a HMD and trying to plugin to OpenVR HMD driver. 
Do we need to pay royalty or license fee if we add a HMD driver into OpenVR?
Could I sell my HMD device based on OpenVR?

**Comment by LibreVR** [comment]
OpenVR is [licensed under the MIT license](https://github.com/ValveSoftware/openvr/blob/master/LICENSE). As long as you abide by the rules specified there you are free to use OpenVR for anything you want and you are of course allowed to sell your own device.

**Comment by JoeLudwig** [comment]
It's actually the BSD 3-clause license. You're welcome to do anything permitted by that license. There are no royalties on either the device or application side. If you want to distribute your driver on Steam, please contact Valve via: vrlicensing@valvesoftware.com
