### ISSUE TITLE
SteamVR beta doesn't return default setting values

### ISSUE THREAD

**Issue by LibreVR** [ValveSoftware/openvr#241]
When calling `vr::VRSettings()->GetInt32()` for a setting that cannot be found, the SteamVR beta will always return 0 instead of the default value that was supplied as a parameter.

This will cause serious issues in applications that rely on the default value being returned. In my case it divided by zero, fortunately no one was hurt.

Other settings functions may also be affected, I haven't tested those yet.

**Comment by JoeLudwig** [comment]
Should be fixed in the beta update that just shipped: http://steamcommunity.com/games/250820/announcements/detail/611748296262250684

**Comment by LibreVR** [comment]
Thanks for fixing it so quickly.
