### ISSUE TITLE
hellovr_opengl.exe' has exited with code -1073741790 (0xc0000022)

### ISSUE THREAD

**Issue by naive231** [ValveSoftware/openvr#248]
I clone current repository and build it with Visual Studio 2015 in samples/, everything's fine.
When I debug the program(Start Debugging in Visual Studio 2015), it shows the error message box, says that : "The application can't executed correctly, press 'confirm' to close it.".

The console also contains the error message:
"The program '[46360] hellovr_opengl.exe' has exited with code -1073741790 (0xc0000022)."

What's wrong with it?

**Comment by zao** [comment]
It's likely that you don't have the `openvr_api.dll` library in your program directory, working directory, or PATH. It's also possible that you're missing a runtime library that the OpenVR library is built against.

You could test these things by downloading Dependency Walker (of the right architecture type) and see what DLLs it appears to be missing, but it has some known false positives.

**Comment by naive231** [comment]
@zao 
I use $(OutputPath) to 'Output Directory' setting value, and check samples/bin/win32/. I am sure that I has the 'openvr_api.dll'. So it isn't the root cause.

**Comment by naive231** [comment]
I eventually knows what is going on. I clone the project with cygwin, so its owner is not `Administrators:None`. After I change the owner to `Administrators:None` of all files, it can be executed well.

**Comment by bysse** [comment]
I'm running Windows 10 and I've never had this problem before, even though I always clone from cygwin. Eventually I just downloaded the zip archive of master and everything just started to work.

**Comment by naive231** [comment]
I test that again, this time I download and extract it, change ownership, then rename the extracted folder. But it raised the same error again. Finally I change the folder name back, then it worked again. Is that normal?

**Comment by naive231** [comment]
@bysse 
I confirmed that the issue has directed relationship with the cygwin.
I download the code from github, extract it with `unzip` in cygwin, building is ok, but it raised the error.
Same code but extracted by 7-zip, it runs well.

It is really so weird.
