### ISSUE TITLE
No FOV change in Unity 5.4*

### ISSUE THREAD

**Issue by 1auralynn** [ValveSoftware/openvr#262]
In Unity 5.4, camera FOV changes aren't being displayed as in 5.3. Oculus, GearVR, are still functional. We think it's an issue with OpenVR. 

Disclaimer: Our early access title uses **brief and gentle** FOV changes to zoom in and out of levels of magnification.

**Comment by JoeLudwig** [comment]
Using an FOV that doesn't match the physical FOV of the display is a really bad idea. You can make people sick very quickly that way.

Unity 5.4 added native support for OpenVR, which is probably why it always uses the right FOV.

You should find some other way to signal your magnification transitions.

**Comment by 1auralynn** [comment]
So, this is intentional? 

Our effect combines a radial blur post process effect to mask the effect a bit, and we've had no one complaining of motion sickness yet, though we are still testing. It's the only reliable way we've found to give the impression of zooming without crashing through geometry while still giving a sense of depth. 

We'll continue developing with 5.3 until this is implemented.

**Comment by JoeLudwig** [comment]
Yes, this is intentional. 

You can always render with another field of view and draw that in front of the VR camera, but it's a really bad idea. You would be better off doing something like letterboxing to give the impression of a reduced field of view without actually distorting the image in the center.

**Comment by 1auralynn** [comment]
Unfortunately, we're going to need to distort the image somehow if we're
going to have an effect that simulates moving between scales of
magnification, and preferably do it in a way that has some kind of a
sensation of depth, not just a flat texture enlarging. Check out our actual
gameplay here: https://cosmworlds.com/cosm-worlds-within-worlds

We did attempt to just use camera motion to achieve the same effect but a)
it doesn't look as good and b) some objects are close to the camera and so
the camera can only move a little bit towards them before crashing through,
so we either crash through or it doesn't look like you're going anywhere,
and are just in the next environment.

-LL

*Laura Lynn Gonzalez*
Dynamoid | Co-founder
dynamoid.com
Oakland, CA
