### ISSUE TITLE
how to send the panorama video streams to vive

### ISSUE THREAD

**Issue by lugui2009** [ValveSoftware/openvr#268]
Recently ,I am using vahana to create Live VR video.And ,in the vahana,I can choose vive to look at the these VR videos.And is there somebody knows how to realize this feature. I also want to send my video streams to vive ,  which part should I use in openvr? Thank you .

**Comment by JoeLudwig** [comment]
I'm not sure I complete understand your application, but there are three ways I can think of:

- Use an existing program like Whirligig or Virtual Desktop
- Write your own 3D app and render into the render target per eye, then submit those textures through the normal IVRCompositor interfaces that 3D apps use.
- Create an overlay with IVROverlay and set one of the Panorama flags on that overlay: https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L2284
