### ISSUE TITLE
Multisampling issue with OpenVR and DirectX 11

### ISSUE THREAD

**Issue by grummelgrisgram** [ValveSoftware/openvr#271]
I implemented a DirectX 11 application working with OpenVR. Without multisampling, everything's fine.
With multisampling enabled, result is also fine. But DirectX debug information shows the following errors when submitting the images:

> D3D11 ERROR: ID3D11DeviceContext::CopySubresourceRegion: If CopySubresourceRegion is used with Multisampled or D3D11_BIND_DEPTH_STENCIL Resources, then the source and destination Subresource must have the same dimensions. [ RESOURCE_MANIPULATION ERROR #281: COPYSUBRESOURCEREGION_INVALIDSOURCE]
> D3D11 ERROR: ID3D11DeviceContext::CopySubresourceRegion: If CopySubresourceRegion is used with Multisampled or D3D11_BIND_DEPTH_STENCIL Resources, then the whole Subresource must be copied. DstX, DstY, and DstZ must all be 0, while pSrcBox must be NULL. [ RESOURCE_MANIPULATION ERROR #280: COPYSUBRESOURCEREGION_INVALIDSOURCEBOX]
> D3D11 ERROR: ID3D11DeviceContext::CopySubresourceRegion: Cannot invoke CopySubresourceRegion with a mismatch between the source Resource Multisampling (Samples:8, Quality:1) and the destination Resource Multisampling (Samples:1, Quality:0). [ RESOURCE_MANIPULATION ERROR #283: COPYSUBRESOURCEREGION_INVALIDSOURCESTATE]

This messages happen inside OpenVR. The change which led to these messages was the ordinary modification for multisampling in DirectX 11:
- setting DXGI_SWAP_CHAIN_DESC SampleDesc.Quality to 1
- setting DXGI_SWAP_CHAIN_DESC SampleDesc.Count to 2, 4 or 8 (doesn't matter)
- setting D3D11_RASTERIZER_DESC MultisampleEnable to TRUE
- setting D3D11_RASTERIZER_DESC AntialiasedLineEnable to TRUE
- setting depth stencil D3D11_TEXTURE2D_DESC SampleDesc.Count and SampleDesc.Quality to the same as done for DXGI_SWAP_CHAIN_DESC
- setting D3D11_DEPTH_STENCIL_VIEW_DESC ViewDimension to D3D11_DSV_DIMENSION_TEXTURE2DMS instead of D3D11_DSV_DIMENSION_TEXTURE2D

I'm also using DXGI_FORMAT_R8G8B8A8_UNORM_SRGB gamma corrected textures and swap chain buffer format.
Without multisampling, DXGI_FORMAT_R8G8B8A8_UNORM has also worked. With multisampling, only DXGI_FORMAT_R8G8B8A8_UNORM_SRGB seem to work at all. This may be another bug.

**Comment by danielrid** [comment]
This bug still exists in 1.04.

Submitting a DXGI_FORMAT_R8G8B8A8_UNORM fails for multisampled surfaces but works for non-multisampled surfaces.

If I use a multisampled DXGI_FORMAT_R8G8B8A8_UNORM_SRGB surface then submission works, but colors are off.

Would be nice if we can get the same DXGI_FORMAT_R8G8B8A8_UNORM behavior for multisampled surfaces as well, as it works great without multisampling.

Thanks!

**Comment by TheWhiteAmbit** [comment]
you can not resolve or copy-subresource a MSAA resouce with D3D11_BIND_DEPTH_STENCIL just do it in a shader and it will work. This is not a bug.

**Comment by JoeLudwig** [comment]
Looks like this was resolved a while ago.
