### ISSUE TITLE
VREvent_Keyboard_t cNewInput type

### ISSUE THREAD

**Issue by rib** [ValveSoftware/openvr#289]
Something seems amis here...

In openvr.h we have:

``` c
/** Used for keyboard events **/
struct VREvent_Keyboard_t
{
    char cNewInput[8];  // Up to 11 bytes of new input
    uint64_t uUserValue;    // Possible flags about the new input
};
```

_(Note: the `cNewInput` comment doesn't seem to match the array length)_

While in openvr_capi.h we have:

``` c
typedef struct VREvent_Keyboard_t
{
    char * cNewInput[8]; //char[8]
    uint64_t uUserValue;
} VREvent_Keyboard_t;
```

_An array of pointers instead of bytes_

In openvr_api.json we have:

``` json
{"struct": "vr::VREvent_Keyboard_t","fields": [
{ "fieldname": "cNewInput", "fieldtype": "char [8]"},
{ "fieldname": "uUserValue", "fieldtype": "uint64_t"}]}
```

I guess this is a bug with the script generating openvr_capi.h

**Comment by schell** [comment]
I've run into this as well - my guess is it's meant to be `char [8]` and *not* `char * [8]`.

**Comment by Plagman** [comment]
Seems like it, thanks for the report.

**Comment by kisak-valve** [comment]
Closing per "Fixed cNewInput and rchRenderModelComponentName having an incorrect type" in the [v1.0.17](https://github.com/ValveSoftware/openvr/releases/tag/v1.0.17) openvr release.
