### ISSUE TITLE
0.9.10 is completely broken on Mac OS X with updated SteamVR

### ISSUE THREAD

**Issue by d235j** [ValveSoftware/openvr#29]
The OpenVR Mac OS X dylib is unable to communicate with SteamVR BuildID 805924 — the OpenVR server never starts. If I downgrade to BuildID 768489, it seems to function.
I have not tested yet on Windows or Linux, but it would not surprise me if this breakage occurs on other platforms too — EDIT: This issue only affects Mac OS X.

**Comment by feilen** [comment]
Also having issues on Linux. The 'normal' and 'beta' builds refuse to work, but the 'Previous' build lets me play my games without issues.

**Comment by d235j** [comment]
@feilen hmm... 32-bit or 64-bit, or both? I don't think I tested with both.

**Comment by feilen** [comment]
Both, as far as I can tell. 64-bit hellovr, 32-bit with TF2.

**Comment by plipay** [comment]
Seeing this issue on Ubuntu too. 
Mon Oct 12 19:05:04 2015 - Unable to create shared mem to get port number for pipe VR_Pipe
gets thrown and fails to initialize. Was working before on the older builds

**Comment by d235j** [comment]
The beta released yesterday (BuildID 815763) is still broken.

**Comment by d235j** [comment]
Still a problem with today's release :-(

**Comment by indianajohn** [comment]
I am also affected by this issue, with the beta build released today. Weird thing is that I was able to launch InMind VR on my DK2 headset.

For those of you using old builds, how might I go about downgrading my build?

**Comment by d235j** [comment]
Today's beta fixes this particular bug. However, it seems to introduce a new issue, where the vrserver is no longer able to load the driver. Neither the provided oculus driver, nor the OSVR driver that is built with this SDK, works.
