### ISSUE TITLE
GetStringTrackedDeviceProperty returns garbage

### ISSUE THREAD

**Issue by MegaManSE** [ValveSoftware/openvr#292]
If the size of the string passed into GetStringTrackedDeviceProperty is less than the required storage size, garbage (string filled with random characters) is returned.  I've seen instances of the required storage size being up to 77 chars so far whereas vr::k_unTrackingStringSize is only 32.

**Comment by jeremyselan** [comment]
Thanks for the feedback, there are a few issues here.

Are you looking at the return error code?  If the passed in buffer is small than required, pError should be set to vr::TrackedProp_BufferTooSmall.  Check out this wrapper, which you may prefer: https://gist.github.com/jeremyselan/d567b427298d46e1f9882333b6af5a94

Next, the documentation is incorrect - k_unTrackingStringSize is not used.  The max string length supported in openvr is 65535, vr::k_unMaxPropertyStringSize.  We've gone ahead and removed k_unTrackingStringSize, and updated the documentation accordingly. Sorry for the confusion.

We're also updating the SteamVR runtime to set the buffer[0] to null, when non-success error codes are returned. This will hopefully make it easier to debug by steering API users towards the error code. This will ship in a future update.
