### ISSUE TITLE
Difference between qWorldFromDriverRotation and qDriverFromHeadRotation

### ISSUE THREAD

**Issue by nikitos1550** [ValveSoftware/openvr#293]
Hello!

Could somebody explain meaning of following values:

`vr::HmdQuaternion_t qWorldFromDriverRotation;
double vecWorldFromDriverTranslation[ 3 ];
vr::HmdQuaternion_t qDriverFromHeadRotation;
double vecDriverFromHeadTranslation[ 3 ];`

How are they related to each other?

**Comment by nikitos1550** [comment]
There are three coordinate systems:

- world
- driver 
- HMD

most unclear is what HMD coordinate system and driver coordinate system.

**Comment by echuber2** [comment]
I think HMD/head is supposed to be oriented with the origin at the head center and -Z looking forward, world is the world position as in the tracked volume for standing mode, and driver is whatever internal coordinate system the sensors are actually using raw. A comment in the header seems to describe it pretty well. https://github.com/ValveSoftware/openvr/blob/master/headers/openvr_driver.h

**Comment by nikitos1550** [comment]
Well, I can easily understand why do we need go from driver space to world space.
But why do we need transformation from HMD to driver? I can understand driver to HMD, but HMD to driver sounds that internally we have HMD coordinate system, than we are getting Driver coordinate system and than World coordinate system.

Where OpenVR uses HMD c.s. and where does it use Worl c.s. ?

**Comment by echuber2** [comment]
Have you studied the hellovr sample project? HMD space is local with respect to the head pose. Driver space is whatever raw space your drivers and tracking hardware use internally, which may not represent the center of the HMD or the orientation in the way HMD space would expect. If they happen to be the same then fine, use identity. Otherwise that quaternion represent the difference between the coordinate systems. Then if you have a way to relate your raw device coordinate system to the HMD local space, you also need a way to relate the world space of the tracked volume to your raw device coordinates.

**Comment by echuber2** [comment]
I re-read your comment and it seems like the question is about why we need the inverse transformation. There are many reasons why you might want the inverse transformation. What if you position the eye in HMD space with respect to the HMD origin, then need to transform it into device space, then into world space.

**Comment by nikitos1550** [comment]
Now, I realize that HDM to Driver is inversed transformation/translation. It means that we can easily convert from HMD to Driver and from Driver to HMD, no difference.
Also I understand what is driver coordinate space.

Than my question is, where do we use HMD coordinate space (I assume that we are using it when we are rendering image for HMD) and where do we use World coordinate space. How are HMD and World coordinate spaces related to each other? Your previous explanation about it, is a bit unclear for me.

**Comment by nikitos1550** [comment]
I think I understand what is going on. With WorldFromDriver DriverFromHead. We have full chain
World <-> Driver <-> HMD. Driver space is in the middle, so we are measuring everything in the middle and than know how to get HDM c,s. related to World c.s.

Thanks!
