### ISSUE TITLE
HELP!All eyes show same texture.

### ISSUE THREAD

**Issue by rzwm** [ValveSoftware/openvr#296]
Hello Everyone:
    In my code, I use `IVRCompositor::Submit()` to submit difference textures to difference eyes. Concretely, I submit `TextureA` to left eye, and `TextureB` to right eye.It runs okay in a long time.
    But about 15days ago(during this period, my engine code had some changes), I suddenly found that my game showing error in HTC VIVE randomly(**about 15% chance**).When I first submit `TextureA` to left eye then `TextureB` to right eye, VR shows `TextureB` in all eyes; when I first submit `TextureB` to right eye then `TextureA` to left eye, VR shows `TextureA` in all eye. All the time, I draw `TextureA` and `TextureB` to my own window after submit, and they show all right. It's really strange.
My code looks like this:

``` cpp
// Draw textures
// ...

// Yes, now I turst nothing
glUseProgram(0);
glBindTexture(GL_TEXTURE_2D, 0);
glFlush();
glFinish();
vr::Texture_t texture2 = { (void*)fbd[1]->m_nResolveTextureId, vr::API_OpenGL, vr::ColorSpace_Gamma };
vr::EVRCompositorError error = m_pVRCompositor->Submit(vr::Eye_Right, &texture2);

glBindTexture(GL_TEXTURE_2D, 0);
glFlush();
glFinish();
vr::Texture_t texture1 = { (void*)fbd[0]->m_nResolveTextureId, vr::API_OpenGL, vr::ColorSpace_Gamma };
error = m_pVRCompositor->Submit(vr::Eye_Left, &texture1);

glBindTexture(GL_TEXTURE_2D, 0);
glFlush();
glFinish();

UpdateHMDPose();
```

I have checked below possibilities：
- Reinstall HTC VIVE driver; (result : no help)
- Reinstall SteamVR; (result :no help)
- Reinstall graphics card driver; (result: no help)
- Try SDK demo and other games; (result : they are all okay)
- View result code; (result : the result code is always VRCompositorError_None)
- Add `glFlush()`/`glFinish()`/`glBindTexture(GL_TEXTURE_2D, 0)` after each submit; (result : no help)
- Try install old version of SteamVR;(result :But I don't know where to find the old version= =)
- Make 'TextureA' load from a local pure blue image and 'TextureB' load from a local pure red image;(result: randomly, left eye and right eye showing same color--last submited texture's color)

Now I really don't know how to resolve this problem.Do have someone had resolved this problem, or may someone who know sumbit's internal code give me some guides?
    **Please help~Thank you!**

**Comment by zao** [comment]
This problem appeared in a SteamVR beta version around the time you say, when they made some changes regarding screenshots.

My team narrowed it down to the fact that we created textures before initializing OpenVR. The only way we could work around this bug in SteamVR was to ensure that absolutely _no_ OpenGL textures were created in the application before initializing OpenVR.

I should've reported it back then, but was swamped with other things.

**Comment by cmdrf** [comment]
Same problem here. I always get the texture for the right eye on both eyes. Chaperone bounds are OK on the left eye, but on the right eye, I see the bounds for both eyes. Steam overlay looks OK.

I'm pretty sure I don't create any textures before initializing OpenVR.

**Comment by rzwm** [comment]
Thanks for your clue, zao! And the same thanks to you, cmdrf. 

But now I can't verify if this bug can be avoid by adjust the order of **creating textures** and **init OpenVR**，nor only because I couldn't reappear this bug in passed 1 hours= =, but it is hard to me to put all **creating textures** after **init OpenVR** in my software.

So I will wait for a better solution. And for the glory of the programmers, I pray it will come soon.

**Comment by rzwm** [comment]
My pray must has be heared. I found the solution of avoiding this bug : **Do Not Open Steam**.

When I open Steam then open SteamVR, this bug reappears frequently. And if I open SteamVR directly without Steam, this bug goes away. Oh, I am so happy.

Another test should be reported. I modify the demo **hellovr_opengl** by putting the creating of textures before `VR_Init()` then test, the result is all okay, no bug appears(Ofcouse Steam is open). So "creating textures before init OpenVR"is not the necessary condition.

**Comment by zao** [comment]
It's very possible that we've triggered the same bug (shows content from one eye, and the second eye shows both chaperone overlays) in different ways.

In our case, it was 100% reproducable in our codebase and the only condition we narrowed it down to was the texture creation, no binds or parameter changes at all.

**Comment by jeremyselan** [comment]
Can you give the latest SteamVR beta a try, and let us know if it addresses your issue?

https://steamcommunity.com/games/250820/announcements/detail/599369548909298226

Thanks!

**Comment by rzwm** [comment]
**ATTENTION**
In last response, I say **Do Not Open Steam** to avoid this bug. But yesterday I found the SteamVR I run without Steam is an old version installed by VivePort. So this bug cannot avoid by close Steam. Sorry for my misleading.

@jeremyselan   And I have test the lasted beta version of SteamVR(1477423729) , it doesn't work, this bug appears as well. It says "Fix for right eye occasionally showing left image in some rare cases.", but my bug is "Both eyes show lasted submitted texture occasionally", not only right eye goes wrong.

When this bug appears, I feel my eyes being harmed. It is a bad experience.

**Comment by cmdrf** [comment]
With the latests SteamVR beta, the chaperone bounds are now correctly shown on both eyes. However, I still have the texture for the right eye on both eyes.

**Comment by Plagman** [comment]
We have a lead on a fix, will post an update when we know more. Thanks!

**Comment by RickLamb** [comment]
Any update on this? Can you repro the bug 100% now?
(I'm now allocating a random unused rendertarget between primary buffers and resolve targets to workaround the issue)

**Comment by jdahl** [comment]
I have the same issue, ran it though RenderDoc and compared it to the hello world project that does work but was unable to find anything that look out of the ordinary. I'm not using MSAA if that matters.

**Comment by echuber2** [comment]
@RickLamb Can you elaborate on your workaround technique?

**Comment by destrofer** [comment]
I had some different issues when I first started coding for HTC Vive, but maybe if you do things in the same order I do you will have this issue fixed. Some or all listed things might be irrelevent, but still ...

* When creating frame buffer for your eyes make sure you bind the appropriate texture and render buffer before attaching them to the frame buffer. My order of actions for creating eye frame buffers is:
  - generate frame buffer,
  - bind frame buffer,
  - generate texture,
  - bind texture,
  - configure and create empty texture,
  - attach texture to frame buffer,
  - generate render buffer,
  - bind render buffer,
  - create storage for render buffer,
  - attach render buffer to frame buffer,
  - unbind render buffer,
  - unbind texture,
  - unbind frame buffer.
* Make sure you call `WaitGetPoses()` of Compositor before rendering. *Without it `Submit()` was returning an error that compositor had no focus.*
* Make sure that before binding an eye frame buffer for rendering you bind its texture and render buffer first. Also when finished rendering before submitting you unbind frame buffer first and then its render buffer and texture. *Without this I had issues with all other textures getting destroyed (becoming black and totally transparent).*
* If you are using multisampling make sure you attach, bind and unbind "multisampled" frame buffer's texture to `GL_TEXTURE_2D_MULTISAMPLE` target. *Without this frame buffer was working, but antialiasing was missing and there were some graphical issues.*
* Again if you are using multisampling make sure you use `glRenderbufferStorageMultisample()` when creating render buffers. *Without this my application was silently crashing after second `Submit()` without throwing any exceptions.*

In case you don't understand what I mean by "unbinding" - it's binding a 0.

Here's my C# code for rendering routine:

```CS
		private static void RenderFrame() {
			Matrix4 matrix;
			EVRCompositorError error;
			// at this point:
			// EyeBuffer1 is RenderToTextureBuffer (frame buffer) that has texture and render buffer attached
			// EyeBuffer2 is RenderToTextureBuffer (frame buffer) that has only texture attached
			Texture_t texData = new Texture_t {
				handle = (IntPtr)EyeBuffer2.Texture.Id,
				eType = EGraphicsAPIConvention.API_OpenGL,
				eColorSpace = EColorSpace.Gamma
			};
			VRTextureBounds_t texBounds = new VRTextureBounds_t {
				uMin = 0f,
				vMin = 0f,
				uMax = 1f,
				vMax = 1f
			};

			if( VRCompositor != null ) {
				TrackedDevicePose_t[] renderPoses = new TrackedDevicePose_t[OpenVR.k_unMaxTrackedDeviceCount];
				TrackedDevicePose_t[] gamePoses = new TrackedDevicePose_t[OpenVR.k_unMaxTrackedDeviceCount];
		
				error = VRCompositor.WaitGetPoses(renderPoses, gamePoses);
				if( error != EVRCompositorError.None )
					GameDebugger.Log(LogLevel.Error, "WaitGetPoses: {0}", error);
				
				for( int i = 0; i < OpenVR.k_unMaxTrackedDeviceCount; i++ ) {
					if( renderPoses[i].bPoseIsValid ) {
						VRDevicePoses[i] = renderPoses[i].mDeviceToAbsoluteTracking.ToIGEMatrix();
						VRDeviceTypes[i] = VR.GetTrackedDeviceClass((uint)i);
					}
				}
				
				// render left eye
				GL.Enable(EnableCap.Multisample);
				EyeBuffer1.Bind(); // binds texture then render buffer then frame buffer
				View.SetView(0, 0, (int)RecommendedWidth, (int)RecommendedHeight);
				GameEngine.StartFrame();
				
				matrix = GetProjectionMatrix(EVREye.Eye_Left);
				View.SetMode3D(ref matrix);
				
				matrix = Matrix4.Invert(Matrix4.Mult(GetPoseMatrix(EVREye.Eye_Left), VRDevicePoses[OpenVR.k_unTrackedDeviceIndex_Hmd]));
				GL.LoadMatrix(ref matrix);
				
				RenderEyeView(EVREye.Eye_Left);
				
				GameEngine.EndFrame();
				EyeBuffer1.Unbind(); // unbinds frame buffer then render buffer then texture
				GL.Disable(EnableCap.Multisample);

				EyeBuffer1.CopyTo(EyeBuffer2);

				error = VRCompositor.Submit(EVREye.Eye_Left, ref texData, ref texBounds, EVRSubmitFlags.Submit_Default);
				if( error != EVRCompositorError.None )
					GameDebugger.Log(LogLevel.Error, "Left eye: {0}", error);

				// render right eye
				GL.Enable(EnableCap.Multisample);
				EyeBuffer1.Bind();
				GameEngine.StartFrame();
				
				matrix = GetProjectionMatrix(EVREye.Eye_Right);
				View.SetMode3D(ref matrix);
				
				matrix = Matrix4.Invert(Matrix4.Mult(GetPoseMatrix(EVREye.Eye_Right), VRDevicePoses[OpenVR.k_unTrackedDeviceIndex_Hmd]));
				GL.LoadMatrix(ref matrix);
				
				RenderEyeView(EVREye.Eye_Right);
				
				GameEngine.EndFrame();
				EyeBuffer1.Unbind();
				GL.Disable(EnableCap.Multisample);

				EyeBuffer1.CopyTo(EyeBuffer2);
				
				error = VRCompositor.Submit(EVREye.Eye_Right, ref texData, ref texBounds, EVRSubmitFlags.Submit_Default);
				if( error != EVRCompositorError.None )
					GameDebugger.Log(LogLevel.Error, "Right eye: {0}", error);
			}

			// Render to main window 
			View.ResetView();

			GameEngine.StartFrame();
			
			View.SetMode3D();
			Render3D();
			
			View.SetModeUI();
			RenderUI();

			GameEngine.EndFrame();
			
			Game.Window.SwapBuffers();
		}
```

I really hope this will help you identify and fix your problem, because it took me hours of trial and error to make things work right for me.

**Comment by jeremyselan** [comment]
We've updated SteamVR with another fix. Could you give it a try?
https://steamcommunity.com/games/250820/announcements/detail/555460077649652611

Thanks!

**Comment by RickLamb** [comment]
Confirmed fixed for me.
