### ISSUE TITLE
GetProjectionRaw

### ISSUE THREAD

**Issue by nikitos1550** [ValveSoftware/openvr#298]
Hello!

Could somebody explain meaning of plLeft, plRight, plTop and plBottom?
`
/** The components necessary to build your own projection matrix in case your
		* application is doing something fancy like infinite Z */
		virtual void GetProjectionRaw( EVREye eEye, float *pfLeft, float *pfRight, float *pfTop, float *pfBottom ) = 0;
`

Maybe there is some information about math model behind these parameters?

**Comment by jeremyselan** [comment]
Those define the field-of-view in the left, right, top, and bottom parts of the view frustum.  Search for "Perspective Projection Matrix" for more info.
http://www.songho.ca/opengl/gl_projectionmatrix.html
