### ISSUE TITLE
Chaperone data (found in *.vrchap file) is only available through SDK when HMD is tracked

### ISSUE THREAD

**Issue by oldio** [ValveSoftware/openvr#30]
Using 0.9.10, calling bounds info using the IVRChaperone interface (i.e. GetSoftBoundsInfo GetHardBoundsInfo) will only give valid data when:

vr::VRChaperone()->GetCalibrationState() == ChaperoneCalibrationState_OK

and GetCalibrationState() returns OK when the HMD is being tracked. Just wondering why we have this limitation if the actual data is already available in the *.vrchap file.

Ideally, it would be nice to initialize the bounds geometry at system startup instead pushing it to an update loop.

**Comment by JoeLudwig** [comment]
The limitation is there because we don't know which tracking universe your HMD is in until the base stations are  known. The .vrchap file can simultaneously store a calibration for any number of different rooms and we pick the room based on what base stations are in that room.

**Comment by oldio** [comment]
Thanks for the explanation.
