### ISSUE TITLE
Lens distortion applying is so complicate.

### ISSUE THREAD

**Issue by VegaLay** [ValveSoftware/openvr#305]
Is there any easy way like a google cardboard profile maker?

https://vr.google.com/cardboard/viewerprofilegenerator/

**Comment by godbyk** [comment]
OSVR's [distortionizer](https://github.com/OSVR/distortionizer) program might be useful.

**Comment by jeremyselan** [comment]
You should not need to apply lens distortion yourself.  Just submit the undistorted images and the compositor takes care of it as the images are presented to the HMD.  The old approach of passing predistorted images has been deprecated for some time - we will be removing this from our example code in the near term.

**Comment by VegaLay** [comment]
@godbyk 
Great. I got this json file. Where should I put this?

@jeremyselan 
Thank you but I don't know how can the compositor do that.
-------------------------------------------------------
{
    "hmd": {
        "distortion": {
            "k1_red": 0.590996,
            "k1_green": 0.590996,
            "k1_blue": 0.590996
        },
        "eyes": [
            {
                "center_proj_x": 0.250000,
                "center_proj_y": 0.500000
            }
        ],
        "fullscreen": 0
    }
}

**Comment by VegaLay** [comment]
vec2 uv;

/// Barrel Distortion ///

float d=length(uv);
float z = sqrt(1.0 - d * d);
float r = atan(d, z) / 3.14159;
float phi = atan(uv.y, uv.x);

uv = vec2(r*cos(phi)+.5,r*sin(phi)+.5);

**Comment by VegaLay** [comment]
virtual DistortionCoordinates_t ComputeDistortion( EVREye eEye, float fU, float fV ) 
{
    float hX;
    float hY;
    double rr;
    double r2;
    double theta;

    rr = sqrt((fU - 0.5f)*(fU - 0.5f) + (fV - 0.5f)*(fV - 0.5f));
    r2 = rr * (1 + 0.52f*(rr*rr*rr*rr) + 0.51f*(rr*rr));
    theta = atan2(fU-0.5f, fV-0.5f);
    hX = sin(theta)*r2*0.86;
    hY = cos(theta)*r2*0.86;

    DistortionCoordinates_t coordinates;
    coordinates.rfBlue[0] = hX + 0.5f;
    coordinates.rfBlue[1] = hY + 0.5f;
    coordinates.rfGreen[0] = hX + 0.5f;
    coordinates.rfGreen[1] = hY + 0.5f;
    coordinates.rfRed[0] = hX + 0.5f;
    coordinates.rfRed[1] = hY + 0.5f;
    return coordinates;
}

**Comment by HelenXR** [comment]
hi,@VegaLay  @godbyk 
I use OSVR's distortionizer generate HMD_config.json contain below information:
{
    "hmd": {
        "distortion": {
            "k1_red": 0.407998,
            "k1_green": 0.407998,
            "k1_blue": 0.407998
        },
        "eyes": [
            {
                "center_proj_x": 0.271596,
                "center_proj_y": 0.507813
            }
        ],
        "fullscreen": 0
    }
}

you only modify the ComputeDistortion interface?
and How to use this parameter(k1_red,k1_green,k1_blue,center_proj_x,center_proj_y) to ComputeDistortion .
I don't understand your last reply,look forward to your reply.

**Comment by TheDeveloperGuy** [comment]
Might be worth looking how the OSVR Steam driver uses the info...

**Comment by godbyk** [comment]
The [SteamVR-OSVR driver](https://github.com/osvr/SteamVR-OSVR) uses [OSVR-RenderManager](https://github.com/sensics/OSVR-RenderManager) to parse the JSON config and interpolate the values.

**Comment by TheDeveloperGuy** [comment]
Look at the section "Software Correction" here, you've got 'k1' for radial distortion, you can discard the tangential distortion. Most lenses need more than 1 'k' parameter, and Google's tool allows for that. I'm not sure if OSVR's doesn't or whether you just haven't set it up.

https://en.wikipedia.org/wiki/Distortion_(optics)

**Comment by TheDeveloperGuy** [comment]
Google's tool (and Cardboard in general) doesn't provide for correcting chromatic aberration, so either ignore it (like VegaLay) or use a tool that does (haven't used OSVR distortion tool, so can't speak for it).

**Comment by HelenXR** [comment]
@TheDeveloperGuy @godbyk 
Thank you for your replys.
Last 2 days ,I studied the oculus on distortion correction articles, such as [Understanding the Oculus Rift Distortion Shader](http://rifty-business.blogspot.jp/2013/08/understanding-oculus-rift-distortion.html),and Distortion Correction(in oculus sdk overview 5.6.2).
the first link contain your wikipedia link,then I get some Distortion correction theory,now I have to Use the code to implement this theory into  ComputeDistortion( EVREye eEye, float fU, float fV ) (one openVR API) .
I think i need to port SteamVR-OSVR this part code to openVR,there are some challenges :-(

@VegaLay  if you can post your openVR code about ComputeDistortion function,That should be good :-).

**Comment by TheDeveloperGuy** [comment]
@HelenXR VegaLay's code is above (14 Nov)...

**Comment by HelenXR** [comment]
i see VegaLay's code below message:
```

rr = sqrt((fU - 0.5f)*(fU - 0.5f) + (fV - 0.5f)*(fV - 0.5f));
r2 = rr * (1 + 0.52f*(rr*rr*rr*rr) + 0.51f*(rr*rr));
theta = atan2(fU-0.5f, fV-0.5f);
hX = sin(theta)*r2*0.86;
hY = cos(theta)*r2*0.86;

DistortionCoordinates_t coordinates;
coordinates.rfBlue[0] = hX + 0.5f;
coordinates.rfBlue[1] = hY + 0.5f;
coordinates.rfGreen[0] = hX + 0.5f;
coordinates.rfGreen[1] = hY + 0.5f;
coordinates.rfRed[0] = hX + 0.5f;
coordinates.rfRed[1] = hY + 0.5f;
return coordinates;

```

but his distortion parameter is below:
```

    "distortion": {
        "k1_red": 0.590996,
        "k1_green": 0.590996,
        "k1_blue": 0.590996

```
How do the parameters correspond to VegaLay's formula?

>

**Comment by HelenXR** [comment]
I get it ,thank you  for all  :-)
