### ISSUE TITLE
Controller identification based on space

### ISSUE THREAD

**Issue by h3teroerectus** [ValveSoftware/openvr#307]
We have created multiple new devices after the Synapse class, but some are specifically designed for left hand/right hand, and are static in space. Is there a way to identify them based on physical position when starting the game, or are there any hard-coded IDs I could use to confirm which is which?

**Comment by JoeLudwig** [comment]
In the JSON:
"tracked_controller_role" : "left_hand",
Or
"tracked_controller_role" : "right_hand",

**Comment by h3teroerectus** [comment]
Thanks so much Joe! If I add custom properties to tracked_controller_role, how can I get them from within Unity?

**Comment by JoeLudwig** [comment]
You can get which device fits which role with GetTrackedDeviceIndexForControllerRole and GetControllerRoleForTrackedDeviceIndex. Once you set the right/left handness of the device these two functions should automatically return the right values.

**Comment by h3teroerectus** [comment]
That is awesome, I really appreciate it. Last (stupid) question, where is the json file?

**Comment by JoeLudwig** [comment]
The JSON file I'm referring to is the calibration file that's store on the device itself.

**Comment by h3teroerectus** [comment]
That's what I thought, thanks. I was hoping I could just whip a test together with the default controllers before our hardware guy comes back with the actual objects.
