### ISSUE TITLE
Please add IVRSystem::GetVisibleAreaMesh

### ISSUE THREAD

**Issue by mbgoogle** [ValveSoftware/openvr#309]
It would be very useful for full-screen effects that are rendered without a depth or stencil buffer bound to get a mesh representing the visible area, which would simply be the geometrical inverse of IVRSystem::GetHiddenAreaMesh

**Comment by jeremyselan** [comment]
Our upcoming API update will have this capability.

**Comment by mbgoogle** [comment]
That's great to hear! Is there an ETA for the update?

**Comment by jeremyselan** [comment]
The new API has been pushed. 

https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L1315

GetHiddenAreaMesh( eEye, vr::k_eHiddenAreaMesh_Inverse ) should do what you're looking for.
