### ISSUE TITLE
Display things in front of chaperone bounds

### ISSUE THREAD

**Issue by mcmonkey4eva** [ValveSoftware/openvr#312]
I'm writing an OpenGL-based VR program.

How would I make it so certain things appear in front of the chaperone bounds, rather than behind?

In particular, the controllers should always be in front of the boundary.
Also sometimes world geometry and various moving objects in-game will move in closer than the bounds.

This produces under default render config an odd sensation where objects appear to be massive in the distance, rather than simple normal sized and directly in front of you!

Ideally, I would be able to submit a depth buffer alongside the actual color buffer to each eye.

**Comment by JoeLudwig** [comment]
The chaperone bounds draw on top of everything to prevent apps from hiding them. If an app could draw over them the user wouldn't see them, which wouldn't be safe.

**Comment by mcmonkey4eva** [comment]
I could swear this doesn't happen with controllers normally
