### ISSUE TITLE
[Unity] Installation is missing .meta files, all asset references broken, plugin unusable

### ISSUE THREAD

**Issue by akbyrd** [ValveSoftware/openvr#313]
Observed with OpenVR 1.0.3, 1.0.2, and 1.0.1, and Unity 5.4.2f2.

**Problem**
When I create a brand new Unity project and copy the contents of the unity_plugin\Assets folder to my new project's Assets folder all references to assets are broken. This means prefabs have multiple 'missing scripts', scenes contain 'Missing Prefab', and materials have no textures plugged in.

This is non-trivial to repair and effectively makes the plugin unusable.

![brokenvr](https://cloud.githubusercontent.com/assets/484784/20313475/af1d7d10-ab1c-11e6-8ae6-0bf394c250b1.png)

**Explanation**
The listed release .zip files (and likely others, those are the only ones I checked) do not contain any of the associated .meta files in the unity_package subfolder. The GUIDs stored in these files is how Unity tracks asset references in addition to import settings. Unity will generate these automatically based on file path and name, but it would appear that algorithm has changed, the assets in the .zip release are organized into a different folder hierarchy than in the source project, or there's another aspect to GUID generation outside of file path that is different on my machine than the one used to create the release. The result is that the GUID stored in e.g. a prefab so it knows which script is attached is different than new GUID that gets generated in my project.

**Solution**
Meta files should be considered part of the associated asset and included in releases. This either means copying them along with the actual assets, or using Unity's 'Export Package...' functionality to create a .unitypackage. The current configuration is fragile, loses asset information (in the form of import settings), and is prone to breakages such as this.

**Comment by akbyrd** [comment]
Reproduced with OpenVR 1.0.3 and Unity 5.3.5p4.

**Comment by aleiby** [comment]
The unity_package subfolder was uploaded to this repro primarily to make it easier to reference in forum posts, etc and propose changes.  I'm actually going to move this to a separate repro on github, and will upload meta files there.  In the meantime, you should use the version on the Unity Asset Store for importing into project.  http://u3d.as/content/valve-corporation/steam-vr-plugin
