### ISSUE TITLE
_countof() is a MSVC specific macro

### ISSUE THREAD

**Issue by ChristophHaag** [ValveSoftware/openvr#315]
https://github.com/ValveSoftware/openvr/blob/84e877f1e099173378759189609b90870f422130/samples/hellovr_opengl/hellovr_opengl_main.cpp#L1303

A short google search gives e.g. this C++ solution that could be used on other compilers:
```c++
template <typename T, std::size_t N>
constexpr std::size_t countof(T const (&)[N]) noexcept
{
return N;
}
```
http://www.g-truc.net/post-0708.html

**Comment by finostro** [comment]
By pasting the suggested code into hellovr_opengl_main.cpp  I managed to compile the hellovr example under linux, although when starting it gives a message that it does not detect an HMD and exits. 

All the other programs in the samples folder fail to compile under linux with the following error:

    /Code/VR/openvr/samples/build$ make
    [  3%] Automatic moc and uic for target driver_sample
    [  3%] Built target driver_sample_automoc
    [ 17%] Built target driver_sample
    [ 20%] Automatic moc and uic for target hellovr_opengl
    [ 20%] Built target hellovr_opengl_automoc
    [ 41%] Built target hellovr_opengl
    [ 44%] Automatic moc and uic for target helloworldoverlay
    [ 44%] Built target helloworldoverlay_automoc
    [ 48%] Building CXX object helloworldoverlay/CMakeFiles/helloworldoverlay.dir/__/shared       /pathtools.cpp.o
    c++: fatal error: no input files
    compilation terminated.
    /bin/sh: 1: -fPIC: not found
    /bin/sh: 1: -fPIC: not found
    helloworldoverlay/CMakeFiles/helloworldoverlay.dir/build.make:62: recipe for target    'helloworldoverlay/CMakeFiles/helloworldoverlay.dir/__/shared/pathtools.cpp.o' failed
    make[2]: *** [helloworldoverlay/CMakeFiles/helloworldoverlay.dir/__/shared/pathtools.cpp.o] Error 127
    CMakeFiles/Makefile2:262: recipe for target 'helloworldoverlay/CMakeFiles/helloworldoverlay.dir/all'     failed
    make[1]: *** [helloworldoverlay/CMakeFiles/helloworldoverlay.dir/all] Error 2
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2

I hope this helps, I'm super exited about linux support for the vive. 
Cheers!

**Comment by ChristophHaag** [comment]
Pasted as is? I personally changed the function name from countof to _countof: https://aur.archlinux.org/cgit/aur.git/tree/countof.patch?h=openvr-git
but maybe there is some magic with functions that start with an underscore, I don't know c++ that well.

Your problem is unrelated: `/bin/sh: 1: -fPIC: not found`. That's an option for the compiler that tells it to create "position independent code", but something with the CMakeLists.txt or Makefile is wrong...

Anyway, I didn't get it to work with steamvr-osvr (always error 301), but with the null driver you can test it: https://gist.github.com/ChristophHaag/79587495848f34771a0a2589eb42f198

For now it doesn't work on anv/radv open source vulkan drivers but I hear that maybe next week we may already see something working on radv already. Maybe.
No idea what it does on the proprietary vulkan drivers.

**Comment by finostro** [comment]
Well, I modified the call from _countof to countof. 
It was only called once. 

Also, what would the null driver do?

Thanks!

**Comment by ChristophHaag** [comment]
This is fixed now.
