### ISSUE TITLE
1.04 GetOverlayErrorNameFromEnum is missing the new 1.04 error values

### ISSUE THREAD

**Issue by spayne** [ValveSoftware/openvr#317]
Using 1.04 on Win32, Calling  VROverlay()->GetOverlayErrorNameFromEnum() with  the two new 1.04 values VROverlayError_TooManyMaskPrimitives, and VROverlayError_BadMaskPrimitive returns  "Unknown EVROverlayError (29)" and "Unknown EVROverlayError (30)"

I expected it to return "VROverlayError_TooManyMaskPrimitives (29)" and "VROverlayError_BadMaskPrimitive (30)"

**Comment by jeremyselan** [comment]
Thanks, this will be fixed in an upcoming release.

**Comment by spayne** [comment]
They are fixed in 1.05. Thanks!
