### ISSUE TITLE
IVR::Overlay SetOverlayGamma not present in C# API?

### ISSUE THREAD

**Issue by BenWoodford** [ValveSoftware/openvr#318]
[Found here](https://github.com/ValveSoftware/openvr/wiki/IVROverlay::SetOverlayGamma) but there's no code for it in the C# API. Is it even in the DLL?

**Comment by aleiby** [comment]
It has been removed.  I've also remove the documentation page now.

Instead, when you call IVROverlay.SetTexture you pass in a Texture_t struct which specifies the colorspace of the texture.
