### ISSUE TITLE
Dashboard Overlays How to control the display and hide Overlay Management.

### ISSUE THREAD

**Issue by dnybz** [ValveSoftware/openvr#321]
Hi there, I have a couple of questions:
First, I create a Dashboard Overlays How do I hide or show Overlay Management, I try to use ShowOverlay / HideOverlay But I do not know the Overlay Management handle or name, please tell me what to do, thanks!

**Comment by JoeLudwig** [comment]
I'm not sure what you mean by "overlay management", but you can show your overlay in the dashboard with all the other controls by calling IVROverlay::ShowDashboard and passing in the key of your overlay.

**Comment by dnybz** [comment]
"overlay management" is area marked in red in the picture
![12](https://cloud.githubusercontent.com/assets/1235501/20778955/683fc74e-b7ac-11e6-97ec-32ce6916d009.png)

HellowordOverlay how to hide it

**Comment by JoeLudwig** [comment]
There is no way to hide the dashboard controls if the user has pressed the system button. What is your application, and why do you want to hide those controls?

**Comment by dnybz** [comment]
My application scenario is the combination of VR Game Hall and DashboardOverlay.
VR game hall is unity3d program, when the user clicks VR games in the VR game hall, will send a message to the DashboardOverlay to start the VR game.
When the user presses the system key when the exhaled DashboardOverlay, by clicking the DashboardOverlay "exit and return VR game hall" button to end the VR game, and start the VR game hall again, this time I found that can not hide Overlay program, must press System key to be able to hide Overlay. I would like to hide all Overlays when returning to the VR Game Hall via DashboardOverlay

**Comment by BenWoodford** [comment]
I've got the same issue, with the same use case - a game launcher and accompanying overlay. When the user hits the big, custom "Exit Game" button on the custom overlay it should close the dashboard as well but I cannot for the life of me find a way to do this.

I'd settle for simulating a button press and sending it to SteamVR but even that seems to be out of the question.

**Comment by OliverEberlei** [comment]
Did anyone ever figure out how to do this? The Steam Overlay does the same thing when launching a game, so it has to be possible somehow.

**Comment by JoeLudwig** [comment]
@OliverEberlei The dashboard hides itself whenever an app transition begins. That's how Steam is "hiding" the dashboard. It just happens as a side effect of Steam launching a game.

**Comment by OliverEberlei** [comment]
Thanks for your reply Joe. I am trying to recreate that behaviour.
OpenVR.Applications.LaunchInternalProcess and System.Diagnostics.Process.Start start the app without closing the dashboard.
Calling OpenVR.Applications.LaunchApplication( "openvr.tool.steamvr_room_setup" ) does close the dashboard, however I don't know how to launch games through this interface. For Space Pirate Trainer I tried the App Id, Exe name, and store name. Is there a way to find out the app key for the installed games? Or better yet, can I use "LaunchApplication" to launch any .exe? I am trying to start games that are not registered with steam.

When I press the "System" Button in the bottom right corner of the dashboard and then select "Cancel" in the menu it also closes the dashboard without launching an app. Is there a way to replicate that behaviour? Basically I want to implement a "Resume Game" Button in my dashboard tab which simply returns to the game that is currently running.

**Comment by BenWoodford** [comment]
As a note, this doesn't occur if you have an already running application that hooks into OpenVR and sets itself as the scene (usual use case, game launcher that opens an environment after leaving a game).

@OliverEberlei, you're looking for GetApplicationCount and GetApplicationKeyByIndex (and then, GetApplicationPropertyString to get the name, image, etc)

**Comment by OliverEberlei** [comment]
Thanks Ben.

In case anyone else find this and wants to achieve the same effect, I have found a super hacky solution. I am using this in a very controlled environment, so it works for now, but... yeah. Don't use this in anything that you deploy to someone else :-)

I simply call
OpenVR.Applications.LaunchApplication( "openvr.tool.steamvr_tutorial" );

And then I've replaced the steamvr_tutorial.exe with a simple "Hello World" console application. This closes the dashboard because there is an App transition (as Joe suggested) but it doesn't open another VR application.

It's super hacky. But I have a very controlled environment so it works for now. 

@JoeLudwig For the future, I would love to be able to call OpenVR.Overlay.CloseDashboard or something like that. Would that be possible to add to the API?

**Comment by daveyflavin** [comment]
@dnybz I was wondering if you could give me some pointers as to how you created the HelloWorld overlay? I want to create something similar to bring up a list of games that I can select and launch. I basically want to replace the SteamVR dashboard with my own but unfortunately I'm new when it comes to this stuff so any help would be greatly appreciated

**Comment by uLan08** [comment]
I am not too sure about this, but try setting the launch options of SteamVR dashboard launch options to `-nosteamvr -nodashboard`.

**Comment by bddckr** [comment]
`-nosteamvr -nodashboard` doesn't work for the use case of a custom app/game launcher as it means you can't show the dashboard, which is the only thing that steals focus from the currently active VR scene app.

That focus-stealing is needed to make sure the rendering scene app is notified about a loss of interactivity. The SteamVR Unity plugin (and I assume the integration into UE4, too) use this to pause the running game while the dashboard is up.

**Comment by uLan08** [comment]
Well idk with you, but it worked for us. What we did is when we press the system button our overlay pops up. To enable this we had to set `sendSystemButtontoAllApps` to `true` but sadly I forgot exactly where that setting is.

**Comment by bddckr** [comment]
Yes but at that point you're using Overlays, not Dashboard Overlays. That works, but doesn't send the "input focus lost" event.

I think that in addition to the `CaptureInputFocus` and `ReleaseInputFocus` could work these days, I had my troubles getting it to work in the past.

Thanks for the reminder!

**Comment by uLan08** [comment]
Ah right. I forgot that there are differences between those. I guess it's up to the use case then.

**Comment by asaeed** [comment]
The original question seemed to refer to the "bottom bar" on the steamvr dashboard, which contains volume controls, etc. Is it possible to hide that bar?

**Comment by theLadi** [comment]
@OliverEberlei  Have you found any other way for this? Are you still using the hacky solution?
Is there a way that you could send "System button"-press event to the SteamVR even queue and trigger the  "dashboard hide"-action.

**Comment by echuber2** [comment]
Sorry I have nothing to contribute to this, but it sounds like an issue the developers will decline to fix. If the user wants to display the system dashboard it's probably not good to allow the software to hide it. There may be a way to design around it.

**Comment by JoeLudwig** [comment]
We don't support hiding half of the dashboard. You're welcome to turn off the entire dashboard with the option in the developer settings.

**Comment by GimpMaster** [comment]
@JoeLudwig one simple solution to this is to just set the opacity to 0 and set the input to none on all those system dashboard overlays. You can find the names by using the overlay_viewer.exe tool. Worked for me!!!

**Comment by vinayak-vc** [comment]
In future if someone needs, here is the solution that I used. 

```
private static void HideTab( string key )
    {
        CVROverlay overlay = OpenVR.Overlay;
        WriteLine("Overlay init");
        if (overlay == null)
        {
            WriteLine("Overlay is null");
            return;
        }
        WriteLine("Overlay is not null");
        ulong tabHandle = 0;
        EVROverlayError findOverlayError = overlay.FindOverlay(key, ref tabHandle);

        if (findOverlayError != EVROverlayError.None)
        {
            WriteLine("Couldn't find overlay '" + key + "': " + findOverlayError);
            if (i < 6)
            {
                System.Threading.Thread.Sleep(5000);
                i += 1;
                HideTab(key);
                return;
            }
            i = 0;
            return;
        }

        WriteLine("Disabling " + key);
        if (key == "system.vrdashboard" || key == "system.dashboard.controls.background")
        {
            overlay.SetOverlayAlpha(tabHandle, 0);
        }
        else
        {
            overlay.SetOverlayFlag(tabHandle, VROverlayFlags.NoDashboardTab, true);
        }


        WriteLine("Disabled " + key);
    }
```
