### ISSUE TITLE
Oculus Rift Touch Buttons and Haptic Feedback

### ISSUE THREAD

**Issue by plmayer** [ValveSoftware/openvr#323]
Hi,

I'm trying to integrate the Oculus Rift Touch controllers from within the SteamVR Unity Scripts. While the Grip, Trigger, and TrackpadPress buttons can be checked via the SteamVR_Controller.GetPress() method, the B, Y, and App Menu buttons don't seem to register at all. The A and X buttons register as "ApplicationMenu". Furthermore, haptic rumble feedback doesn't seem to do anything.

To be clear, this code:

`device = SteamVR_Controller.Input(...someIndex...);`
`print(device.GetState().ulButtonPressed)`

simply returns all zeroes if the B, Y, and app menu are pressed.

Is this a known issue? Has anyone got the Touch controllers working with OpenVR?

Thanks!

-plmx

**Comment by JeffLeinbaugh** [comment]
Try the latest SteamVR beta update. The B and Y buttons register as k_EButton_ApplicationMenu. A and X register as k_EButton_A. Haptics should also be functional now.

**Comment by plmayer** [comment]
Confirmed. Thanks!

**Comment by JohnAlcatraz** [comment]
There is still an issue with haptics and Oculus Touch controllers, I've created a new thread about it: #639
