### ISSUE TITLE
Method to mask hidden area moved, but there is no documentation as to where

### ISSUE THREAD

**Issue by ChunkBuster** [ValveSoftware/openvr#325]
Where has the code to early-z reject unused fragments been moved to? It used to reside within SteamVR_CameraMask.cs but since then the method has been changed, the class has become deprecated, but there is no note as to where the code resides now other than "SteamVR_CameraMask is deprecated in Unity 5.4 - REMOVING"

**Comment by aleiby** [comment]
This is performed in native code now.

You can still download the older version of the SteamVR plugin as long as you use a version of Unity older than v5.4.

You can still access the data by calling OpenVR.System.GetHiddenAreaMesh.  This function now takes a second parameter to specify if you want the normal hidden area mesh or its inverse, or a line loop representing the boundary.  The inverse is useful for optimizing fullscreen fx.
