### ISSUE TITLE
Apply distortion realtime

### ISSUE THREAD

**Issue by prsyahmi** [ValveSoftware/openvr#328]
Hi, we want users to have the ability to change lens distortion settings and see them live but since the distortion is applied only once right after the device has been added/activated we can only see the effect of changing distortion parameters after restarting SteamVR. This make the task to apply correct lens distortion tedious.

Is it possible for current version or could it be implemented in the future to apply new distortion parameter, like how changing the IPD works just by calling IServerDriverHost::PhysicalIpdSet (or for distortion something like, IServerDriverHost::ApplyDistortion)?

Thanks.

**Comment by aleiby** [comment]
You can send event VREvent_LensDistortionChanged to cause the compositor to refresh.  This will likely cause a hitch though.

**Comment by HelenXR** [comment]
@prsyahmi 
How to generate distortion parameters and how to use distortion parameters?I see cardboard and osvr have distortion tool,but openVR doesn't provide,Can you give me some advice.
