### ISSUE TITLE
Oculus touch visual controller models

### ISSUE THREAD

**Issue by plmayer** [ValveSoftware/openvr#329]
When using the Oculus touch controllers, the visual representation of the controllers in the virtual world is that of the Vive controllers. It would be nice to have a representation of the touch controllers in VR as well. 

Is this planned or somehow configurable?

**Comment by JeffLeinbaugh** [comment]
This is planned. Oculus Touch controllers will have their own default render model.

**Comment by plmayer** [comment]
I'll assume then that they'll just start working automatically at some point in the future and I don't have to write any specific code. Thanks!
