### ISSUE TITLE
Oculus Touch aim in SteamVR dashboard/keyboard wrong

### ISSUE THREAD

**Issue by jrbudda** [ValveSoftware/openvr#333]
I don't have a Rift but this is from a user:

The SteamVR keyboard is very confused as to what controller aiming direction to use. I already posted a question about what rotation is being applied to the 'forward' direction of the Touch [here](http://steamcommunity.com/app/358720/discussions/0/1842367319512930229/) (I would like to know the answer to this too)

What he's seeing is the keyboard is using the 'forward' direction of the controllers but drawing the line at whatever rotation you're using to mimic the Oculus standard aim.

Here's a pretty clear picture.
http://i.imgur.com/8G7cVlN.png

Edit: Specifically this occurs when I call vrOverlay.showKeyboard from in-game. If he opens the SteamVR dashboard via the system button and opens the keyboard from there the keyboard functions normally. He also reports the keyboard opened-in game he can't switch which controller is being used.

**Comment by jrbudda** [comment]
Just as follow up this is not Oculus exclusive. I modified the vive controller's json to the same X angle and same problem using Vive.

**Comment by JeffLeinbaugh** [comment]
Thanks for reporting this. There is a bug in handling the pointing direction for the in-game keyboard. It has been fixed and will be available in the next beta update.

The active controller for the in-game keyboard will switch based on which controller is currently pointing at it. This behavior hasn't changed, but the pointing direction bug likely made this especially hard to figure out.
