### ISSUE TITLE
helloworldoverlay sample: vr::API_OpenGL doesn't exist anymore

### ISSUE THREAD

**Issue by ChristophHaag** [ValveSoftware/openvr#335]
https://github.com/ValveSoftware/openvr/blob/9d48ccf90d709382a137de9bc429aab5f7cea5de/samples/helloworldoverlay/openvroverlaycontroller.cpp#L191

I believe it has been replaced with `vr::TextureType_OpenGL`

**Comment by jeremyselan** [comment]
Whoops, thanks.
