### ISSUE TITLE
Open VR Stingray

### ISSUE THREAD

**Issue by Edozie101** [ValveSoftware/openvr#34]
Is there any plans to integrate Autodesk Stingray support, if not is it possible to set up a repo so people can start building it out ?

**Comment by JoeLudwig** [comment]
The license for the OpenVR SDK would certainly allow you to start working on a Stingray integration and share that integration with anyone: https://github.com/ValveSoftware/openvr/blob/master/LICENSE

I don't know anything about the Stingray engine or license, so from that end you'll have to figure out what's allowed.
