### ISSUE TITLE
Building hellovr_opengl_main on OSX

### ISSUE THREAD

**Issue by abencomo** [ValveSoftware/openvr#340]
Has anyone been able to build the **hellovr_opengl_main** sample on a Mac OSX?  I'm able to compile it with Eclipse CDT, but I'm getting a "Undefined symbols for architecture i386" error when it tries to link it, as shown below.

Building target: hellovr_opengl_main
Invoking: MacOS X C++ Linker
g++ -L"/Users/abencomo/Documents/workspace/vive/hellovr_opengl_main/lib" -m32 -o "hellovr_opengl_main"  ./src/hellovr_opengl_main.o   -lopenvr_api
Undefined symbols for architecture i386:
in hellovr_opengl_main.o
  "_glViewport", referenced from:
      CMainApplication::RenderStereoTargets() in hellovr_opengl_main.o
      CMainApplication::RenderCompanionWindow() in hellovr_opengl_main.o
  "_glewExperimental", referenced from:
      CMainApplication::BInit() in hellovr_opengl_main.o
  "_glewGetErrorString", referenced from:
      CMainApplication::BInit() in hellovr_opengl_main.o
  "_glewInit", referenced from:
      CMainApplication::BInit() in hellovr_opengl_main.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [hellovr_opengl_main] Error 1

<img width="360" alt="screen shot 2016-12-17 at 3 06 35 pm" src="https://cloud.githubusercontent.com/assets/7515273/21290351/9b800c38-c46b-11e6-98f2-15129db83767.png">

**Comment by bjornbytes** [comment]
Try modifying the g++ command to include the OpenGL framework (`-framework OpenGL`) and link against glew (`-lglew`).

**Comment by abencomo** [comment]
It did not make any difference.  Thanks though.

<img width="819" alt="screen shot 2016-12-17 at 4 06 22 pm" src="https://cloud.githubusercontent.com/assets/7515273/21290531/d81ae1fc-c472-11e6-8b86-8abe33d00c62.png">

**Comment by tcoppex** [comment]
Hey @abencomo,
Try to build using CMake on the command line, it was not tested against OS X but it could help.

**Comment by natbro** [comment]
all the SDK samples that work on macOS now build properly with cmake.
