### ISSUE TITLE
ResetSeatedZeroPose() Event

### ISSUE THREAD

**Issue by jespertheend** [ValveSoftware/openvr#343]
Is there an event that notifies the application when ResetSeatedZeroPose() is called.
If the user presses the 'reset seated position' button in the VR menu for example.
There doesn't seem to be an event for this when looking at [VREvent_t](https://github.com/ValveSoftware/openvr/wiki/VREvent_t), do we have to call IVRSystem::GetSeatedZeroPoseToStandingAbsoluteTrackingPose() in the main loop instead?

**Comment by JoeLudwig** [comment]
VREvent_SeatedZeroPoseReset is sent when ResetSeatedZeroPose is called.

**Comment by jespertheend** [comment]
Thanks! It wasn't on the wiki page but now I see there's a whole list of events in [openvr.h](https://github.com/ValveSoftware/openvr/blob/b96746068239d5571a4d1ff77577517cc4ca1326/headers/openvr.h#L395-L527)
