### ISSUE TITLE
HMD driver - render width and height params

### ISSUE THREAD

**Issue by nikitos1550** [ValveSoftware/openvr#344]
Hello!
I am setting render width and height to extreamly small values like 100 x 100 pixels.
I assume to see low quality image, but some apps are not affected with it and still render image at full resolution.
For example InCell is not affected by render width and height, only preview image is affected.
The Lab intro is not affected, but scenes with gameplay are affected.

Why so? Is it depends of app or are there some details?

**Comment by JoeLudwig** [comment]
GetRecommendedRenderTargetSize() is a recommendation on both the driver and application side, not a requirement. The application is free to render whatever size render target it wants and the compositor will down-scale as necessary as part of the distortion processing.
