### ISSUE TITLE
My windows application exits when SteamVR game starts

### ISSUE THREAD

**Issue by Lordpeara** [ValveSoftware/openvr#345]
My windows application has openvr as dependency, which catches triggering controller buttons and checks  whether controllers are visible in displayed scene.

I used IVRSystem::GetControllerStateWithPose() and it catches controllers triggers successfully.
However, whenever I use VRCompositor::WaitGetPoses() it kills the other app (Mine or OpenVR Game)

Can I resolve this? If so, How to do it?

**Comment by JoeLudwig** [comment]
Only one Scene application can run at a time, and only the scene application can call WaitGetPoses. WaitGetPoses is synchronized with the compositor's frame loop, and OpenVR doesn't support two processes being synchronized that way at the same time.

You should be able to get access to the same data calling VR_Init with Overlay as your app type, and then by using IVRSystem::GetDeviceToAbsoluteTrackingPose or IVRCompositor::GetLastPoses to get the poses.

**Comment by echuber2** [comment]
My understanding was that VAC bans based on modifications to game executables or runtimes, but creating an overlay application like this just receives duplicate information about the controller states without modifying the running game state or executables, so it wouldn't be VAC bannable. I may be wrong.
