### ISSUE TITLE
Request: Expose function to enable/disable collision bounds overlay in compositor

### ISSUE THREAD

**Issue by oldio** [ValveSoftware/openvr#35]
This is more of a suggestion than an issue.

Would be great to have a toggle in the Compositor interface to enable/disable the collision bounds overlay. In certain games, users might want to have a custom look and will prefer to just use the collision bounds geometry to do their own rendering.

**Comment by JoeLudwig** [comment]
Showing the collision bounds is important to keep users safe. Eventually there may be some user options in this area, but this isn't something apps are going to control.
