### ISSUE TITLE
How to develop a driver with IVRDriverDirectModeComponent?

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#351]
I have a custom HMD I am trying to develop an OpenVR driver for. It doesn't configure as a Windows monitor, so I need to get the Compositor output directly and feed it to the HMD. It seems the way to do this would be to use IVRDriverDirectModeComponent, but I cannot find any way to get the Compositor/SteamVR to call anything other than DestroyAllSwapTextureSets. 

I can license a piece of software to create a virtual monitor and then capture the output and send it to the HMD. This works (more or less) on Windows 8/8.1, but has poor performance on Windows 10/10AU (something to do with VSync). 

So, what is the intended method for supporting HMDs that are not Windows monitors? If IVRDriverDirectModeComponent is the intended method, then how does one use that with no documentation or examples?

TIA

**Comment by JoeLudwig** [comment]
The next SDK update will have a property you can set in the driver to enable this behavior.  Until then the only way to enable this functionality is to start the name of your driver with "oculus".

**Comment by TheDeveloperGuy** [comment]
Thanks, that works. Any chance of getting a brief synopsis of what the SubmitLayer() and Present() methods are supposed to be doing? Also, what does the unFormat argument of the CreateSwapTextureSet() represent? It seems that it might be a DXGI_FORMAT value...

**Comment by vr-developer** [comment]
> The next SDK update will have a property you can set in the driver to enable this behavior. Until then the only way to enable this functionality is to start the name of your driver with "oculus".
And this is the intended method for doing what you're trying to do.

Can you specify, please, what version will have the property? Thanks!

**Comment by TheDeveloperGuy** [comment]
@JoeLudwig It may be early days to ask this question, but is this interface likely to change with the new SDK, or is the only significant change (from a driver point of view) the property?

**Comment by JoeLudwig** [comment]
Well oddly enough the biggest upcoming change in the driver interface is everything to do with properties. Those changes will show up in an SDK in approximately early February.

IVRDriverDirectModeComponent hasn't changed. That's no guarantee that it won't change down the road, but we'll keep things backward compatible.

**Comment by superjallu** [comment]
What does 'name of driver' mean here? Filename of dll implementing driver? Some key value in steamvr.vrsettings? Some property returned by driver?

**Comment by TheDeveloperGuy** [comment]
My experience is that you won't get answers to questions on this topic that: (1) don't show a fair level of understanding of what you're doing, (2) can be answered by yourself (digging in header files, trial-and-error etc.). Bear in mind that this driver interface is semi-public and pretty much unsupported. It is also a *very* complex driver to write, and you have next to no chance of doing so if you're stumbling on questions like this... ;)

**Comment by superjallu** [comment]
@TheDeveloperGuy  Well I have already written a functional OpenVR-driver. It uses some ugly hacks to capture image from compositor window and therefore I would like to use more official way to get stereo images. I have spent half a day with trial and error, but it would be much more efficient to know instead of trying things randomly.

As far as I know driver interface is public, it just does not have any documentation. Looks like it is better to wait for next release in February than ask questions here.

**Comment by Balderick** [comment]
We could ask Valve to open up the steamvr tracking hdk to end users!?.

**Comment by TheDeveloperGuy** [comment]
@JoeLudwig Thanks for SDK update, new property works, don't have to call driver "oculus_" something. :)

**Comment by TheDeveloperGuy** [comment]
There is some more documentation on this interface: 

// ----------------------------------------------------------------------------------------------
// Purpose: This component is used for drivers that implement direct mode entirely on their own
//			without allowing the VR Compositor to own the window/device. Chances are you don't
//			need to implement this component in your driver.
// ----------------------------------------------------------------------------------------------

**Comment by JoeLudwig** [comment]
Just for posterity... This is the new property: Prop_UsesDriverDirectMode_Bool

**Comment by TheDeveloperGuy** [comment]
@JoeLudwig Just out of curiosity, why was this property necessary? Wouldn't returning a IVRDriverDirectModeComponent pointer from GetComponent() have been enough?

**Comment by JoeLudwig** [comment]
Other parts of the internal code need to do things differently if that component is going to be used. I suppose it would have been possible to do that based on whether or not GetComponent returned anything, but it would have been way more than the three lines of code required to add the property. :)
