### ISSUE TITLE
How to mimic behaviour of 'Null' HMD plugin

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#353]
If a plugin is named 'null' (unfortunately doesn't work with 'null' prefix), then the Compositor will create the window as borderless in the center of the main monitor. I'm developing a custom HMD driver for SteamVR, and am having some issues (due to it not being visible to Windows as a monitor). Being able to have a borderless window (as opposed to fullscreen) removes some issues I'm having.

Is there some way to force the Compositor to create the HMD window as borderless (as opposed to full screen) without naming the plugin 'null' (which obviously conflicts with the built-in 'null' driver)? Ideally, I'd like to be able to create the window as borderless and specify it's size and placement. A plugin called 'null' is able to create the borderless window, but it can't specify it's position (it's always in the center of the main monitor regardless of the 'WindowX' and 'WindowY' settings.

**Comment by echuber2** [comment]
I suppose this isn't quite what you want, but you can compile a particular app to display a borderless window using SDL2 or whatever toolkit you're using. http://stackoverflow.com/a/22995938

**Comment by TheDeveloperGuy** [comment]
Not going to help much here. The HMD window gets created by OpenVR/SteamVR.

**Comment by Balderick** [comment]
Does this comment in another open issue help? https://github.com/ValveSoftware/openvr/issues/97#issuecomment-218433708

**Comment by TheDeveloperGuy** [comment]
A driver named 'null' will have it's borderless (not fullscreen) window created at the center of the main monitor. There is no way to change it's position from the config, because the Compositor (or whatever creates the HMD window) will not pay any attention to the WindowX and WindowY settings. What they couldn't understand in that issue, is that calling the driver 'null' changes its behaviour in this regard. If you need proof of this, compile the sample driver and see how it's behaviour changes when it is called 'sample' and when you rename it to 'null'. Any driver not named 'null' will have it's HMD window created fullscreen.

**Comment by Balderick** [comment]
AFAIK steamvr compositor needs full screen to load

**Comment by TheDeveloperGuy** [comment]
Methinks you need to re-read what I've written here... ;)

**Comment by Balderick** [comment]
> A driver named 'null' will have it's borderless (not fullscreen) window created at the center of the main monitor. 

Expected behaviour.

> There is no way to change it's position from the config, because the Compositor (or whatever creates the HMD window) will not pay any attention to the WindowX and WindowY settings.

Nothing is being rendered to hmd because you called null driver and you just need to work out which options to use to manage your window in windows desktop display.

**Comment by TheDeveloperGuy** [comment]
Briefly, (for those who don't understand how HMD drivers work, but still want to comment on this issue), all OpenVR HMDs (outside of Oculus or any other using the IVRDriverDirectModeComponent interface) are rendered to via a window which is created by OpenVR. The window is either opened borderless or fullscreen depending on whether the driver is called 'null' or not. I'm asking for a way to create the window borderless without renaming my driver 'null'. 

I'm pretty sure there isn't one, hence I'm raising it as an issue...

**Comment by Balderick** [comment]
Going by the last post of the discussion you referred to is actually asking the same question.  https://github.com/ValveSoftware/openvr/issues/97#issuecomment-218435432

Maybe your missing the same thing as that guy?

**Comment by TheDeveloperGuy** [comment]
Do you know how to force OpenVR to use the 'borderless' flag when creating the window? There is one way, renaming your HMD driver to 'null'. Do you know another way? If not, there's nothing to add here...

**Comment by TheDeveloperGuy** [comment]
'Hacks' not necessary. Driver can be implemented with IVRDriverDirectModeComponent interface.
