### ISSUE TITLE
Android studio

### ISSUE THREAD

**Issue by emad-Saleh** [ValveSoftware/openvr#354]
How can I implement it with android studio??....there is no build apk option after cloning it ?

**Comment by JoeLudwig** [comment]
OpenVR does not currently support Android.

**Comment by emad-Saleh** [comment]
Is there any plan to support android soon ??

**Comment by Balderick** [comment]
Or eLinux maybe?

**Comment by JoeLudwig** [comment]
We are working on full Linux support. I'm not sure what eLinux is.

We don't have immediate plans for an Android port.

**Comment by bgSosh** [comment]
> We don't have immediate plans for an Android port.

@JoeLudwig Sorry to comment on a closed issue.  I'd really appreciate it if you could give me a brief update on what the likelihood of an Android port is in the near future.  I imagine nothing has changed here, but if you could confirm this one way or the other that would be great.  Thank you!

**Comment by Balderick** [comment]
Apps like Steam App for Android just means we need official support for steams native streaming feature being used remotely, which would mean virtual windows, vGPUs could be used to stream steam games to android devices.

Paperspace and Liquidsky use GRID tech, just like GFN does, which means android devices have replaced my gaming rig.

This makes SteamOS, steam link and gaming spec PC's redundant, from my perspective.

Have absolutely no doubts vGPUs delivering Steam games from the cloud is the future for all steam users.

Nvidias development soc/platform Jetson can run embedded Linux version of Ubuntu.  I intended eLinux to mean Linux for embedded devices (non x86_64 devices)
