### ISSUE TITLE
SteamVR license?

### ISSUE THREAD

**Issue by gnauhnedaj** [ValveSoftware/openvr#356]
My team is making our own HMD and developing OpenVR driver, everythings works great but now we have some questions about license.

From the [post](https://github.com/ValveSoftware/openvr/issues/231), Joe said it's BSD license but I wonder if SteamVR is the same? Is it free to use SteamVR to demo our HMD at formal event? Any license?

**Comment by Balderick** [comment]
Cybercafe license is needed to use steam content for public use.

**Comment by gnauhnedaj** [comment]
What if we only use SteamVR with our content for demo?

**Comment by Balderick** [comment]
The very first senetence from the first link above is:  

> If you are interested in using Steam's content or services in a public setting, you should join the Steam Site Licensing Program (formerly Cybercafé Program). To do so, you can sign up directly at https://partner.steamgames.com/.

**Comment by gnauhnedaj** [comment]
@Balderick thanks, I'll look into it.

**Comment by gnauhnedaj** [comment]
Close #356
