### ISSUE TITLE
How to use the API?

### ISSUE THREAD

**Issue by rafaloz** [ValveSoftware/openvr#357]
Hello,

I'm doing a project for my university in VR, but i lack basic knowledge in the use of this API. So my question is how do i start using it? I've to create a Visual Studio project where I add the openvr.dll? Is this the way to use it? Is there any guide you know about?

**Comment by petethor** [comment]
Maybe not a guide but you can look at this piece of code for a small example of how to acquire tracking data:
[https://github.com/Omnifinity/OpenVR-Tracking-Example](url)

**Comment by tamarous** [comment]
Check the sample project hellovr_opengl. It shows you how to use the API clearly.

**Comment by rafaloz** [comment]
Thanks for your answers!
