### ISSUE TITLE
Some clarification on IVRDriverDirectModeComponent driver?

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#358]
So, I've managed to implement a (more or less) working HMD driver for my custom HMD (which doesn't configure as a monitor under Windows) using the IVRDriverDirectModeComponent component (as per the suggestions in https://github.com/ValveSoftware/openvr/issues/351 ). 

I have two questions which I haven't been able to infer from trial-and-error or other sources:

1) What is the format supplied to the CreateSwapTextureSet() method? I'm assuming it's DXGI_FORMAT, and it seems to be working OK like that.
2) What is the syncTexture supplied to the Present() method? It's not a texture that the driver created, and it's not always supplied. In the instances that it is supplied it's not obvious what it should be used for (seems like it's a 1x1 texture in some instances).

**Comment by aleiby** [comment]
1. Yes.
2. Answered in your other issue.
