### ISSUE TITLE
OpenVR driver SDK no longer works with SteamVR on Mac

### ISSUE THREAD

**Issue by d235j** [ValveSoftware/openvr#37]
The latest beta of SteamVR, which has finally resolved #29, has also brought a more major issue: SteamVR no longer will load any real HMD driver on Mac OS X.
The Oculus driver (with Oculus Runtime 0.5) fails with little useful feedback, with "Unable to load driver oculus from /Users/user/..." and "Error 103: Unable to load driver "oculus".
The SteamVR-OSVR driver (https://github.com/OSVR/SteamVR-OSVR), which is built using this SDK, has a different error. SteamVR seemingly believes that the returned class derived from vr::ITrackedDeviceServerDriver is not an HMD, and bails out. However, the device is of class TrackedDeviceClass_HMD.

Unfortunately, due to these issues, SteamVR/OpenVR is now completely unusable on Mac OS X. These issues may affect other operating systems as well, but I have not had a chance to check.

**Comment by feilen** [comment]
The 'beta' release works for the first time in a couple months for me. Linux 64-bit.

**Comment by d235j** [comment]
@feilen: what HMD are you using it with? It works for me on Mac but only with the null driver.

**Comment by feilen** [comment]
Oculus DK2, oculus drivers. Trying to get the OSVR drivers working now.

Keep in mind this is the 'beta' build, none of the others worked (but they haven't for a couple months)

**Comment by d235j** [comment]
I was able to get it to work even when broken by starting the SteamVR vrserver manually.

**Comment by feilen** [comment]
Have you had the chance to test the OSVR driver on Linux? I haven't been
able to get that to work at all.

**Comment by d235j** [comment]
@feilen what error are you getting? I tested it on Mac and Linux before the latest SteamVR beta, and as long as I'd start the SteamVR vrserver manually, it would work just fine.
