### ISSUE TITLE
Necessary to do own lens distortion when using IVRDriverDirectModeComponent driver?

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#372]
It appears that the HMD driver must do its own lens distortion when using the IVRDriverDirectModeComponent interface. Is there any way to get OpenVR to do the lens distortion in this case?

**Comment by TheDeveloperGuy** [comment]
Definitely no way to do this right now. Would involve driver passing composed eye textures back to OpenVR, then getting them back, before doing a final composition for display, so less overhead for the driver to do it itself.

**Comment by JoeLudwig** [comment]
Just to confirm your conclusion: Yes, you'll need to do your own distortion correction (and any other panel fix-up required for your HMD) when writing a driver this way.
