### ISSUE TITLE
Get refresh rate Hmd

### ISSUE THREAD

**Issue by jespertheend** [ValveSoftware/openvr#373]
Is there any way to get the refresh rate of the connected Hmd? I couldn't find anything in Compositor_FrameTiming.

I'm trying to adjust the resolution to the performance and I'm currently using m_flCompositorIdleCpuMs but this seems to change when async reprojection is enabled. So I had a look at the Lab Renderer and it seems like it's using [VRDevice.refreshRate](https://docs.unity3d.com/ScriptReference/VR.VRDevice-refreshRate.html) and [VRStats.gpuTimeLastFrame](https://docs.unity3d.com/ScriptReference/VR.VRStats-gpuTimeLastFrame.html) to get the frame timing, is there any way to get this data using the OpenVR SDK?

**Comment by JoeLudwig** [comment]
Take a look at Prop_DisplayFrequency_Float. You can fetch it with GetFloatTrackedDeviceProperty on IVRSystem.
