### ISSUE TITLE
Tracked camera Sample can`t find QT platform plugin "windows".

### ISSUE THREAD

**Issue by aprentis** [ValveSoftware/openvr#379]
Hi everybody! 

I`ve compiled samples as it was said in readme. 

"hellovr_opengl" works great with my HTC Vive, but the others do not work at all. 

"helloworldoverlay.exe" shows this mistake
![default](https://cloud.githubusercontent.com/assets/17255184/22100194/94aa30d0-de3f-11e6-8c9c-97bc1584ec9e.png)

"tracked_camera_openvr_sample.exe"  shows this 
![default](https://cloud.githubusercontent.com/assets/17255184/22100263/e5ffe628-de3f-11e6-842f-81c2663f5bba.png)

I`ve looked in Google aboit last mistake, and found this page(https://forum.qt.io/topic/43205/solved-failed-to-start-because-it-could-not-find-or-load-the-qt-platform-plugin-windows/6). I`ve copied from Qt platforms directory to samples bin folder, but nothing changed, this mistake remains. 

Visual Studio has helped a little: both examples went with the same error. 
![2017-01-19_13-11-48](https://cloud.githubusercontent.com/assets/17255184/22102726/85b0217a-de49-11e6-9ff9-ac47e87fcb95.png)

Could anybody help me with this?

**Comment by TheDeveloperGuy** [comment]
Have you installed Qt? It looks like the samples only provide the 32-bit Windows platform plugin. Are you building in 64-bit?

**Comment by aprentis** [comment]
Yes, i`ve installed Qt, and i`m building on 64-bit windows 10(and 8.1 on another machine). 

All main Qt libraries are automatically copied to bin folder while building with CMake, so Qt is surely found.

**Comment by BoJunHuang** [comment]
Did you delete all the Qt dlls that were in the bin folder?
It seems like dll version mismatch.

**Comment by BoJunHuang** [comment]
By the way, did you try windeploy to deploy all the dlls you need?
http://doc.qt.io/qt-5/windows-deployment.html

**Comment by aprentis** [comment]
i`ve tried windeploy, after running it both applications began to show me  error message similar to the first screenshot in this topic. "The procedure entry point could not be located in the DLL".

**Comment by aprentis** [comment]
Now it seems to be working correctly. 

I`ve deleted everyrhing in samples/bin then build the project with CMake and ran windeploy. 

Thanks everybody!
