### ISSUE TITLE
Cant use Vive controllers without headset plugged in. Even over direct USB.

### ISSUE THREAD

**Issue by chipweinberger** [ValveSoftware/openvr#382]
Before you used to be able to plug the controllers in over USB or use the USB wireless dongle even without a vive headset plugged in. Now you no longer can. You get "Hmd not detected." and the api does not return any controller data.

"requireHmd" in steamvr.vrsettings does not seem to change this behavior. You then instead just get "Hmm, that shouldn't have happened" and still nothing from the api.

**Comment by u-cap** [comment]
Has there been any indication this will be resolved?

**Comment by u-cap** [comment]
See also
  http://steamcommunity.com/app/507090/discussions/0/135508017190302200/

**Comment by lgbeno** [comment]
Please take a look at the following tutorial: https://www.triadsemi.com/2017/03/28/steamvr-tracking-without-an-hmd

**Comment by Balderick** [comment]
@JoeLudwig @bendotcom Why do we need to use a wrapper to send steamvr tracked device input to steam games when requireHmd : false is used to ignore connected hmds or when there is no hmd connected?.

**Comment by bjj** [comment]
> Why do we need to use a wrapper

What wrapper?  I don't understand what you are asking.

> when requireHmd : false is used to ignore connected hmds

That will not ignore connected HMDs.  It will only allow successful startup without an HMD present.  If the HMD is connected, it will be used, even if requireHmd:false

> Vive Tracker being used as head tracker for non htc hmds is one example why we need working steamvr tracked devices in steamvr apps when requireHmd : false is called.

Please be more specific about how it's not working for you.  Every time I see a problem reported with "requireHmd:false" I try it myself and it works.  If you could be more specific about your configuration I could try that as well.

**Comment by Balderick** [comment]
The pyopenvr wrapper that @lgbeno  links too in post that I replied too.


found simply activating multiple drivers, setting requireHmd to false together with 3nabling the null driver in its default.vr settings file only was enough to get steamvr status to say "Ready" and allow vive controllers to be used without a headset.

I used osvr semantic paths to set an alias which sets Vive Tracker as head tracker which means I can attach the vive tracker to a hat to have working head tracking in steamvr apps being run on the desktop primary display.

**Comment by bjj** [comment]
Ok, to so clarify:  You have no problem getting requireHmd:false to work as designed/expected, which is the topic of this issue.

You have an unrelated feature request, which is to have a non-HMD object act as a tracker for some custom display, which you have described in #605

**Comment by Balderick** [comment]
Well that is one way of looking at it.

Sorry to have wasted your time and apologise for my poor communication skills.

**Comment by Balderick** [comment]
require : hmd causes the Not Ready indicating ipc connection error so allthough steamvr room layout can see and track devices steamvr apps can not use them.
