### ISSUE TITLE
How can HMD driver notify OpenVR that lens distortion has changed?

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#389]
I want to be able to change lens distortion parameters while OpenVR is running, but can't find a way to do that (please do not bog this down with why, that is not relevant to this discussion). 

There is a server event sent to VR applications "VREvent_LensDistortionChanged", but there doesn't seem any way for the HMD driver to send this to the OpenVR server. At the moment, I'm setting the "Prop_FieldOfViewLeftDegrees_Float" etc. properties, but doing this repeatedly seems to eventually confuse OpenVR and it needs a complete shutdown to render correctly again.

**Comment by TheDeveloperGuy** [comment]
Seems like updating the properties is enough. The issue was in my driver where I was losing the screen to lens distance in some cases.

**Comment by JoeLudwig** [comment]
You can also send VREvent_LensDistortionChanged via the VendorSpecificEvent function. It's one of the couple of system events that are allowed from a driver.

**Comment by TheDeveloperGuy** [comment]
@JoeLudwig Thanks, good to know, as I'm not so sure it's my driver any more ;)

Seems like changing lens parameters a lot (ie. more than a real-world user would) might "confuse" OpenVR eventually.

**Comment by TheDeveloperGuy** [comment]
@JoeLudwig Thanks, seems to work, although it's hard to tell beyond it doesn't crash the server or have any adverse effects. I'm sending 0,0 as the event data, as I don't see anything else that I could send... :)

**Comment by HelenXR** [comment]
@TheDeveloperGuy  I also encountered the need to modify the distortion in real time.
what do you mean "Seems like updating the properties is enough.",Can you share this with us?

@JoeLudwig How to send "VREvent_LensDistortionChanged " Event,I can't find related methods in driver_samples.cpp,Is there a related demo program.

We look forward to your replys :-)

**Comment by TheDeveloperGuy** [comment]
@HelenXR It isn't enough, you also need to send the event.

**Comment by HelenXR** [comment]
@TheDeveloperGuy  How to send the event?

**Comment by JoeLudwig** [comment]
You create a VREvent_Data_t struct and call IVRServerDriverHost::VendorSpecificEvent. This is one of a couple of events that is white-listed.

**Comment by HelenXR** [comment]
@JoeLudwig @TheDeveloperGuy 
I get it!
thanks for your helps!
