### ISSUE TITLE
What is Prop_UserHeadToEyeDepthMeters_Float supposed to represent?

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#398]
Can't find any docs on what this driver property is supposed to represent. Anyone know?

**Comment by TheDeveloperGuy** [comment]
The sample HMD driver sets it, so it must be used for something. Or just set it to zero and forget about it? :)

**Comment by JoeLudwig** [comment]
It's an eye relief adjustment that's useful is certain unusual circumstances. You can just not set it and you'll end up with the default value (which is 0 for floats.)
