### ISSUE TITLE
GetControllerState doesn't work with Oculus Touch when proximity sensor isn't active

### ISSUE THREAD

**Issue by davidt2115** [ValveSoftware/openvr#399]
I don't know how the oculus sdk works, but I really need to be able to get button state for the oculus touch with the headset off to speed up development. Is there any way for me to do this? 

I thought about taping the proximity sensor, but don't really want to run the rift constantly when I'm not using it. The tracking and pose works fine, but I can't get the buttons.

**Comment by davidt2115** [comment]
I also noticed there is no position tracking without the proximity sensor active. Is there any way to get this or is it a limitation of the oculus sdk? It would really speed up development not needing to put on the HMD constantly

**Comment by JeffLeinbaugh** [comment]
The latest SteamVR beta update lets you get Touch controller input without wearing the headset. This change will come to the default release soon.

Touch positional tracking is not available unless the Rift headset is moving or the proximity sensor is triggered. This seems to be an Oculus SDK limitation.
