### ISSUE TITLE
Any way for HMD driver to issue (something like) VREvent_SeatedZeroPoseReset?

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#403]
Is there any way for a HMD driver to tell OpenVR to "recenter"? It seems that the VREvent_SeatedZeroPoseReset event may have this purpose, but issuing it as a vendor specific event doesn't do anything.

**Comment by JoeLudwig** [comment]
There is currently no way for a driver to zero the seated pose. That event is sent as a result of the seated pose being zeroed (rather than as the cause of it.)

Can you describe your situation a bit? When would you want to trigger a seated pose rezeroing?

**Comment by TheDeveloperGuy** [comment]
@JoeLudwig I'm working on a wireless headset. When one moves physical locations (ie. to another room) it would be useful to be able to recenter the HMD (for example when the seating postion in the new location faces a different direction).

In light of there being "currently no way", I guess I will have to transform the orientation in the driver.

**Comment by HelenXR** [comment]
I also encountered such a situation,I send Event "VREvent_SeatedZeroPoseReset",return errror message"VendorSpecificEvent 804 outside of reserved range" in "vrserver.txt" file.
@JoeLudwig 
Based on the following 2 points,I think "recenter" is needed:
1.sensor work for a long time (more than 10 minutes), there will be some drift (even if the fusion algorithm is good enough), we need to manually perform a "recenter",I saw holographice's HMD do it.
2.the direction of the user playing the HMD may not be the starting position of the application

**Comment by Balderick** [comment]
3.   User starts steamvr and openvr from steam large mode on PC due too steamvr dashboard bugs.  This means hmd needs recentered after placing on head and is ready to use.

**Comment by HelenXR** [comment]
I think I solved this problem and I am excited to share it with you.
I searched for resources about "recenter" for a long time , I didn't find the corresponding algorithm to do "recenter",then I see Oculus have a interface about this,like below:
```
This can be modified using the API call ovr_RecenterTrackingOrigin, which resets 
the tracking origin to the headset’s current location and sets the yaw origin to the 
current headset yaw value. Additionally, it can be manually specified to any location 
using the API call ovr_SpecifyTrackingOrigin.
```
however,Oculus not share "ovr_RecenterTrackingOrigin" source code :-(.
But this gives me some inspiration,All of a sudden, I felt like I was thinking about it. It made me jump out of bed,and  took some hours to program,I check it in openVR driver is fine :-).
- Thinking:
[](url)![1](https://cloud.githubusercontent.com/assets/12227445/23250479/52054b6e-f9e4-11e6-90c8-cfedd64d0efb.jpg)
![2](https://cloud.githubusercontent.com/assets/12227445/23250528/852063b2-f9e4-11e6-970d-5dec3bf6e01b.jpg)
 - Code:
Chinese programmers popular words"say is nothing,show your code!"
```
//①Get yaw_offset
			float m_fYawOffset;
			vr::HmdVector3d_t radian,degree;
			//get origin yaw from quaternion
			radian = QuaternionToEuler(m_Pose.qRotation);
			RadianToDegree(radian.v,degree.v);
                        //degree.v[0] is roll,degree.v[1] is yaw,degree.v[2] is pitch
			m_fYawOffset = degree.v[1];	
```
```
//②Recenter yaw with yaw_offset:
			double yaw_degree_new,yaw_degree_origin;
			vr::HmdVector3d_t radian,degree;
			//get origin yaw from quaternion
			radian = QuaternionToEuler(m_Pose.qRotation);
			RadianToDegree(radian.v,degree.v);
			yaw_degree_origin = degree.v[1];	

			//recenter yaw ,get yaw_degree_new
			yaw_degree_new = yaw_degree_origin - m_fYawOffset;
			if(yaw_degree_new > 180)
				yaw_degree_new= -360 + yaw_degree_new;
			else if(yaw_degree_new < -180)
				yaw_degree_new = 360 + yaw_degree_new;

			//transform degree to quaternion
			degree.v[1] = yaw_degree_new;
			DegreeToRadian(degree.v,radian.v);
			m_Pose.qRotation = EulerToQuaternion(radian);
```
The above 4 functions source code is below :
```
#define M_PI    3.14159265358979323846264338327950288   /* pi */
vr::HmdVector3d_t QuaternionToEuler(vr::HmdQuaternion_t q)
{
	HmdVector3d_t e;
	double x,y,z,w;
	x = q.x;
	y = q.y;
	z = q.z;
	w = q.w;
	double test = x*y + z*w;
	if (test > 0.499) { 
		e.v[0] = 2 * atan2(x, w);
		e.v[1] = M_PI / 2.0;
		e.v[2] = 0;
		return e;
	}
	if (test < -0.499) { 
		e.v[0] = -2 * atan2(x, w);
		e.v[1] = -M_PI / 2;
		e.v[2] = 0;
		return e;
	}
	double sqx = x*x;
	double sqy = y*y;
	double sqz = z*z;
	e.v[0] = atan2(2 * y*w - 2 * x*z, 1 - 2 * sqy - 2 * sqz);
	e.v[1] = asin(2 * test);
	e.v[2] = atan2(2 * x*w - 2 * y*z, 1 - 2 * sqx - 2 * sqz);
	return e;	
}

vr::HmdQuaternion_t EulerToQuaternion(vr::HmdVector3d_t e)
{
	vr::HmdQuaternion_t q;
	double c1 = cos(e.v[0] / 2);
	double s1 = sin(e.v[0] / 2);
	double c2 = cos(e.v[1] / 2);
	double s2 = sin(e.v[1] / 2);
	double c3 = cos(e.v[2] / 2);
	double s3 = sin(e.v[2] / 2);
	double c1c2 = c1*c2;
	double s1s2 = s1*s2;
	q.w = c1c2*c3 - s1s2*s3;
	q.x = c1c2*s3 + s1s2*c3;
	q.y = s1*c2*c3 + c1*s2*s3;
	q.z = c1*s2*c3 - s1*c2*s3;
	return q;
}

void DegreeToRadian(const double in[3], double out[3])
{
    out[0] = in[0] * (M_PI / 180.0);
    out[1] = in[1] * (M_PI / 180.0);
    out[2] = in[2] * (M_PI / 180.0);
}

void RadianToDegree(const double in[3], double out[3])
{
    out[0] = in[0] * (180.0 / M_PI);
    out[1] = in[1] * (180.0 / M_PI);
    out[2] = in[2] * (180.0 / M_PI);
}
```
- Effect
test in steam game "InCellVR".
1.before "recenter" is not right orientation like this:
![3](https://cloud.githubusercontent.com/assets/12227445/23250539/9161f47e-f9e4-11e6-8a48-66e3e78333d1.jpg)
 2.after above "recenter" :
![4](https://cloud.githubusercontent.com/assets/12227445/23250550/9b931b4e-f9e4-11e6-8102-cda79daf3199.jpg)
 - Summary
The above method is based on an easy way to understand ,in fact,"radiantodegree" or "degreetoradian" is not neccessary,only for debug,and then it should be able to directly through the quaternion multiplied by the Rotation matrix is enough,like this:
quaternion(new) = quaternion(ori) * Rotation matrix.

**Comment by LoSealL** [comment]
@HelenXR Hi, thanks for sharing your method, it works well but I suppose there may be one possible issue when comes into 6 DOF recenter (recentering Room space).
For example, when I recenter quaternion by your method, the room space coordinate remains unchanged, if I walk forward, which should lead to increase or decrease in Z-axis, but it's not correct in the room space coordinate, therefore the character in game walks in a wrong direction.
To solve this problem, I think we need to get the HMD rotation on start as an offset, so we can rotate the room space coordinate when `recenter`.

**Comment by TheDeveloperGuy** [comment]
@LoSealL https://github.com/ValveSoftware/openvr/issues/470#issuecomment-295645892

**Comment by HelenXR** [comment]
@LoSealL
I test in 6DOF situation，It work fine。
Most of the 6DOF tracking system, such as Ximmerse or Nolo。They need to do recenter at the beginning of the station to the base station，you can try that.

**Comment by TheDeveloperGuy** [comment]
Worked around this issue.
