### ISSUE TITLE
FindOverlay to get handle to steam overlay

### ISSUE THREAD

**Issue by robnewton** [ValveSoftware/openvr#416]
I'm trying to use IVROverlay::FindOverlay() to get a handle to the stock steamvr overlay but I cannot find the overlay key for it. Can anyone point me in the right direction?

**Comment by spayne** [comment]
I've seen people just use "valve.steam.desktop" e.g.
https://github.com/matzman666/OpenVR-AdvancedSettings/blob/6c7240fcf6c387939f80c2fff15245d84ad703dd/src/tabcontrollers/UtilitiesTabController.cpp#L10

**Comment by robnewton** [comment]
Excellent that was it. I didn't have the third part "desktop"

**Comment by robnewton** [comment]
Actually that was aptly named and is only the dektop overay. Still can't find the overlay key for the main steam VR settings/game selection overlay. I've guessed just about everything I can think of.

**Comment by robnewton** [comment]
Bingo. Scanning content of all files in the Steam config directory for "valve.steam" turned up a few log files with entries that contained the name "valve.steam.bigpicture"

**Comment by robnewton** [comment]
For anyone else coming by this in the future:

`valve.steam.desktop (Desktop)
valve.steam.desktop.thumb (Desktop (Thumb))
valve.steam.bigpicture (Steam)
valve.steam.bigpicture.thumb (Steam (Thumb))
system.vrdashboard (VR Dashboard)
system.powermenu (Power Menu)
system.powermenu.thumb (Power Menu (Thumb))
system.notificationhistory (History)
system.notificationhistory.thumb (History (Thumb))
system.settings (Settings)
system.settings.thumb (Settings (Thumb))
system.keyboard (Keyboard)
system.messageoverlay (Message Overlay)
system.messageoverlay.thumb (Message Overlay (Thumb))
system.IPDValue (IPD Setting)
system.ScreenshotProgress (Screenshot Progress)
system.CameraSurfaceUI (Camera Surface UI)
system.DefaultTransition (Default Transition)
system.controllerstatus.1 (system.controllerstatus.1)
system.controllerstatus.2 (system.controllerstatus.2)
system.dashboardfade (Fades the world for the dashboard)
system.dashboard.controls.background (Sits behind dashboard controls)
system.dashboard.active.background (Sits behind active dashboard)`
