### ISSUE TITLE
No way to init OpenVR without Compositor

### ISSUE THREAD

**Issue by thomasgauthier** [ValveSoftware/openvr#42]
I'm using OpenVR in an app that already has stereoscopic rendering, I want to use only tracking data from OpenVR and use the IVRExtendedDisplay interface. From looking at documentation and header files, there's no real way to init IVRSystem without launching the compositor. When the compositor is present vr::ExtendedDisplay() return NULL and there's no way around that. I've tried SetDisplayVisibility(true) but it returns 0 without giving proper explanation of the error.

**Comment by JoeLudwig** [comment]
VR_Init does not launch the compositor.  If you write an app that just calls VR_Init and never calls VR_GetGenericInterface on the compositor or the VRCompositor() function, then the compositor won't run.

Doing your own distortion processing is probably the wrong thing to do for anything you plan to ship to actual customers. There are other visual fixups and features you will be missing if you do that.

**Comment by ChrisDenham** [comment]
@JoeLudwig 
Can I pick up on your comment above: "Doing your own distortion processing is probably the wrong thing to do for anything you plan to ship to actual customers."

As I've been looking at the hellovr_opengl example provided here as a base for developing my own application. I notice it does start the VRCompositor, so I wondered if the lens distortion processing code in that example was necessary if it is better to use the "built-in" handling of lens distortion correction? Also, if that code is unnecessary, the example could be much leaner and a better template to follow.

**Comment by JoeLudwig** [comment]
That sample is old and busted. It predates the compositor, so it is from a time when all apps needed to do their own distortion processing. When we published the first OpenVR SDK we changed it to default to using the compositor, but didn't pull out the manual distortion stuff. Hopefully we'll get to that in a future update to the sample.

**Comment by ChrisDenham** [comment]
Ok, thanks. How is the sample busted? It seemed to work ok for me, at least with oculus dk2. Can you give.me any idea when the example might be updated? I'm keen to get on with an OSG integration and would like to start with a solid foundation.

**Comment by JoeLudwig** [comment]
Busted might be a strong word. It definitely leads you down some paths you don't need to go down anymore with respect to distortion. As long as you ignore those bits it's otherwise a fine sample.

**Comment by ChrisDenham** [comment]
So, what is actually performing the distortion in that example? It looks as though it is being performed by the code in the example, but that implies it is not then also being done by the compositor. Is there a compositor option I missed that controls that? Or have I got the wrong end of the stick?

**Comment by ChrisDenham** [comment]
Ah, curiouser. I see there are default params on the compositor submit function but looks at though it would need to specify 'Submit_LensDistortionAlreadyApplied' as the last parameter if doing external distortion?

**Comment by ChrisDenham** [comment]
@JoeLudwig
Ok, I think I'm getting there.. albeit slowly. Presumably the distortion applied in the example is only used for the on-screen mirror window, but is not used for the image on the HMD? If so, I'm still left with a slight puzzle in that adding the `Submit_LensDistortionAlreadyApplied` option to the `vr::VRCompositor()->Submit` call seems to make no difference to the image on my HMD. So, does that mean external distortion is not supported (at least on Oculus DK2)?

**Comment by aleiby** [comment]
Correct.  I need to wire that up to use their non-distort layer when
passing that flag.  When I first hooked up their compositor, that layer
wasn't working properly.

**Comment by ChrisDenham** [comment]
Ok, thanks. By the way, I don't really need that flag to work, but it's good to know, as things make a bit more sense to me now. I wondered if some confusion could be be avoided if compositor submit returned an error code for unsupported options?
