### ISSUE TITLE
Gets "illegal declaration of anonymous 'struct'" error in winnt.h files when trying to build sample projects

### ISSUE THREAD

**Issue by DayVidZhou** [ValveSoftware/openvr#429]
When attempting to build any sample projects using msvc 14 2015 I get the "illegal declaration of anonymous 'struct'" error in winnt.h files 

![vrsampleerror](https://cloud.githubusercontent.com/assets/9309271/23569394/05a420a2-002d-11e7-8f70-9c0d113416f1.PNG)

**Comment by RobertPotter** [comment]
I'm also having the same problem, did you manage to resolve this?

**Comment by DayVidZhou** [comment]
Yah actually, forgot to update this. you gotta goto the property pages (a little wrench icon) for the project and in the configuration properties go to C/C++ and goto the language section and change the Disable Language Extension from 'Yes (/Za)' to 'No'

**Comment by RobertPotter** [comment]
Perfect! Thank you very much!
