### ISSUE TITLE
Visual Studio 2017 support / ETA

### ISSUE THREAD

**Issue by sbd1138** [ValveSoftware/openvr#437]
Was just looking to see what the ETA was for adding Visual Studio 2017 support (projects/libraries)?  I'm looking to plan out my own migration to 2017 (from 2010), which of course is predicated on my required 3rd party SDKs adding that support.

**Comment by stfairy** [comment]
What is wrong with the current libraries?

**Comment by sbd1138** [comment]
Yep, that's an incomplete thought on my part; I forgot that OpenVR is distributed/linked as DLLs (and thus just simple import .libs).  Typically if you're *statically* linking (and depending on your code generation requirements) you'd need to be able to build the libraries yourself or have them provided for the particular toolchain/settings you're using, which presumes the library has been tested against it in some form ("officially supported").

**Comment by JoeLudwig** [comment]
You've discovered our secret plan. :)
