### ISSUE TITLE
HelloWorldOverlay.exe run error

### ISSUE THREAD

**Issue by keimura** [ValveSoftware/openvr#439]
![helloworldoverlayerror](https://cloud.githubusercontent.com/assets/25837139/23920906/c5937996-08b9-11e7-9123-00f4ccdadfdb.PNG)

After building in qt 5.8 32bit when I go to run the exe file it gives me this error. Has anyone else run into this as well?

**Comment by EldarZ** [comment]
the samples bin folder contains qt dlls from a version older than 5.8, try replacing them with the equivalent dlls from your qt installation folder.
