### ISSUE TITLE
OpenSceneGraph integration.

### ISSUE THREAD

**Issue by ChrisDenham** [ValveSoftware/openvr#44]
I've been scouting around for examples of an integration of OpenSceneGraph and openvr, but didn't really find anything. I started working on it myself (using the hellovr_opengl example for hints) but wondered if anyone else out there had done any work on this, or has any pointers to similar projects?

**Comment by ChrisDenham** [comment]
If anyone wants to take a look at my first stab at an OSG - OpenVR integration, you can take a look here:
https://github.com/ChrisDenham/osgopenvrviewer

So far, I've only tested it on Windows with Oculus DK2, so I'd be interested to know if/how it performs on other platforms and VR devices.

**Comment by JoeLudwig** [comment]
Best of luck with your integration!
