### ISSUE TITLE
Image has been successfully displayed in the HMD, but the picture is upside down, why?

### ISSUE THREAD

**Issue by lbgongfu** [ValveSoftware/openvr#440]
Image has been successfully displayed in the HMD, but the picture is upside down, why?Use OpenGL

**Comment by TheWhiteAmbit** [comment]
maybe because you switched up and down coordinates while submitting pictures?

**Comment by lbgongfu** [comment]
Thanks!This is a mistake, and has been revised.

**Comment by kisak-valve** [comment]
Closing as this issue appears to have been resolved.

**Comment by SamXiaosheng** [comment]
> Thanks!This is a mistake, and has been revised.
recently, i meet the same problem, could you share your solution?

**Comment by SamXiaosheng** [comment]
is the problem attributed to the OpenGL coordinate? How to transform the VR coordinate?
