### ISSUE TITLE
Proximity Sensor - No VREvent_Button(Un)Press events on Oculus CV1

### ISSUE THREAD

**Issue by kalmiya** [ValveSoftware/openvr#446]
Even though the Oculus CV1 reports it _does_ support the proximity-sensor (reported by HMD->GetBoolTrackedDeviceProperty(vr::k_unTrackedDeviceIndex_Hmd, Prop_ContainsProximitySensor_Bool, &pe) - it does **not** seem to generate the appropriate VREvent_Button(Un)Press events.

The only "alternative" I see is by using VREvent_TrackedDeviceUserInteractionStarted(/Ended) which understandably has a few seconds delay before they trigger (especially the Ended one), instead of being instantaneous, which isn't great...

**Comment by JeffLeinbaugh** [comment]
This will be fixed in an upcoming release. Thanks for the report.
