### ISSUE TITLE
How can I test if the sample driver is working as it should

### ISSUE THREAD

**Issue by dashingstag** [ValveSoftware/openvr#452]
vers 1.0.6
I have compiled the driver_sample example and seemed to have installed it but I am unable to tell if it is working as intended. 

I opened steamvr and this is the result i get from the server logs

Wed Mar 29 2017 19:35:28.776 - sample: Using settings values
Wed Mar 29 2017 19:35:28.776 - sample: driver_null: Serial Number: 
Wed Mar 29 2017 19:35:28.776 - sample: driver_null: Model Number: 
Wed Mar 29 2017 19:35:28.776 - sample: driver_null: Window: 0 0 0 0
Wed Mar 29 2017 19:35:28.776 - sample: driver_null: Render Target: 0 0
Wed Mar 29 2017 19:35:28.776 - sample: driver_null: Seconds from Vsync to Photons: 0.000000
Wed Mar 29 2017 19:35:28.776 - sample: driver_null: Display Frequency: 0.000000
Wed Mar 29 2017 19:35:28.776 - sample: driver_null: IPD: 0.063000
Wed Mar 29 2017 19:35:28.776 - Driver sample attempted to add tracked device with no serial number
Wed Mar 29 2017 19:35:28.776 -   driver sample implements interfaces IVRSettings_002 ITrackedDeviceServerDriver_005 IVRDisplayComponent_002 IVRDriverDirectModeComponent_002 IVRControllerComponent_001 IVRCameraComponent_002 IServerTrackedDeviceProvider_004 IVRWatchdogProvider_001 
Wed Mar 29 2017 19:35:28.776 - Loaded server driver sample (IServerTrackedDeviceProvider_004) from D:\openvr-master\openvr-master\samples\bin\drivers\sample\bin\win64\driver_sample.dll
Wed Mar 29 2017 19:35:28.776 - Driver sample has no suitable devices.
Wed Mar 29 2017 19:35:28.777 - Unable to load driver sample from D:\openvr-master\openvr-master\samples\bin\drivers\sample\bin\win64\bin\win64\driver_sample.dll.
Wed Mar 29 2017 19:35:28.777 - Unable to load driver sample because of error 103. Skipping.
Wed Mar 29 2017 19:35:28.777 - Not loading driver null because it is disabled in settings
Wed Mar 29 2017 19:35:28.777 - No connected devices found. Returning best error VRInitError_Init_HmdNotFound
Wed Mar 29 2017 19:35:28.777 - Allowing driver load failure VRInitError_Init_HmdNotFound for application vrmonitor (10020) because it is vrmonitor
Wed Mar 29 2017 19:35:28.777 - Processing message VRMsg_Connect from vrmonitor (10020) took 0.0109 seconds
Wed Mar 29 2017 19:35:28.885 - New Connect message from D:\Steam\steamapps\common\SteamVR\bin\win32\vrcompositor.exe (VRApplication_Background) (Args: ) 4208 
Wed Mar 29 2017 19:35:28.887 - Creating builtin app for D:\Steam\steamapps\common\SteamVR\bin\win32\vrcompositor.exe (VRApplication_Background)
Wed Mar 29 2017 19:35:28.887 - Setting app system.generated.vrcompositor.exe PID to 4208
Wed Mar 29 2017 19:35:28.887 - Refusing connect from vrcompositor (4208) because VRInitError_Init_HmdNotFound
Wed Mar 29 2017 19:35:28.887 - IPCPipe(vrcompositor (4208)): Process disconnected.
Wed Mar 29 2017 19:35:28.887 - Process vrcompositor (4208) disconnected

below is my vrsettings.json (i did this manually as I could not find mine in my config file)
{
   "jsonid" : "vrsettings",
   "steamvr" : {
		"activateMultipleDrivers" : true
		// "ipd": 0.0635,
		// "forcedDriver": "null",
		// "forcedHmd": "",
		// "requireHmd": true,
		// "displayDebug": false,
		// "enableDistortion": true,
		// "displayDebugX": 0,
		// "displayDebugY": 0,	
		// "sendSystemButtonToAllApps": false,
		// "loglevel": 3,
		// "background": "backgrounds/image_%d.png", (now requires fully qualified path)
		// "backgroundCameraHeight": 1.6,
		// "backgroundDomeRadius": 10.0, (0.0 == Infinite)
		// "directMode": true,
		// "usingSpeakers": true, (only works in some Unity games current)
		// "speakersForwardYawOffsetDegrees": 90.0,
		// "renderTargetMultiplier": 1.0
		// ^ Make sure your last entry does not include a trailing comma (use jslint when in doubt to verify format).
	},
   "driver_lighthouse": {
		// "disableimu": false,
		// "usedisambiguation": "tdm",
		// "disambiguationdebug": 0,
		// "primarybasestation": 0,
		// "lighthousename": "",
		// "maxincidenceangledegrees": 60.0,
		// "uselighthousedirect": true,
		// "dbhistory": false
	},
   "driver_null" : {
		// drivers are searched in alphabetical order, so you may need steamvr.forcedDriver="null" as well
		 "enable": true,
		 "id": "Null Driver",
		 "serialNumber": "Null 4711",
		 "modelNumber": "Null Model Number",
		 "windowX": 100,
		 "windowY": 100,
		 "windowWidth": 1920,
		 "windowHeight": 1080,
		 "renderWidth": 1344,
		 "renderHeight": 1512,
		 "secondsFromVsyncToPhotons": 0.1,
		 "displayFrequency": 90
   },
   "version" : "1"
}

**Comment by JoeLudwig** [comment]
This is your problem:
> Wed Mar 29 2017 19:35:28.776 - Driver sample attempted to add tracked device with no serial number

What serial number are you passing to TrackedDeviceAdded in your sample driver? There should be a default that it's picking up from here: https://github.com/ValveSoftware/openvr/blob/master/samples/bin/drivers/sample/resources/settings/default.vrsettings

**Comment by dashingstag** [comment]
yes I have this file in my folders and it seems to be loaded in

[Settings] Load Default Json Settings from D:\openvr-master\openvr-master\samples\bin\drivers\sample\resources\settings\default.vrsettings

{
   "driver_sample" : {
      "enable" : true,
      "serialNumber" : "1234",
      "modelNumber" : "SampleModel 1",
      "windowX" : 20,
      "windowY" : 20,
      "windowWidth" : 800,
      "windowHeight" : 600,
      "renderWidth" : 400,
      "renderHeight" : 300,
      "secondsFromVsyncToPhotons" : 0.011,
      "displayFrequency" : 0
   }
}

is it also weird hat i have to make my own vrsettings.json in steam/config? also i have steam in D drive. would that be the problem?

Below is the full debug message
Process vrmonitor (13068) has initiated a quit all
Thu Mar 30 2017 09:14:02.033 - Sending Quit event to process vrmonitor (13068)
Thu Mar 30 2017 09:14:02.072 - New Connect message from D:\Steam\steamapps\common\SteamVR\bin\win32\vrcompositor.exe (VRApplication_Background) (Args: ) 11840 
Thu Mar 30 2017 09:14:02.072 - Refusing connect from vrcompositor (11840) because we are shutting down
Thu Mar 30 2017 09:14:02.072 - IPCPipe(vrcompositor (11840)): Process disconnected.
Thu Mar 30 2017 09:14:02.072 - Process vrcompositor (11840) disconnected
Thu Mar 30 2017 09:14:02.210 - IPCPipe(vrmonitor (13068)): Process disconnected.
Thu Mar 30 2017 09:14:02.210 - Process vrmonitor (13068) disconnected
Thu Mar 30 2017 09:14:02.220 - VR server shutting down
Thu Mar 30 2017 09:14:02.272 - Listener thread ending
Thu Mar 30 2017 09:14:10.999 - ================================================================================================
Thu Mar 30 2017 09:14:10.999 - ================================================================================================
Thu Mar 30 2017 09:14:11.000 - VR server (v0) starting up with config=D:\Steam\config
Thu Mar 30 2017 09:14:11.001 - Skipping external driver  because it is not a directory
Thu Mar 30 2017 09:14:11.002 - [Settings] Load Default Json Settings from D:\Steam\steamapps\common\SteamVR\resources\settings\default.vrsettings
Thu Mar 30 2017 09:14:11.002 - [Settings] Load Default Json Settings from D:\Steam\steamapps\common\SteamVR\drivers\lighthouse\resources\settings\default.vrsettings
Thu Mar 30 2017 09:14:11.002 - [Settings] Load Default Json Settings from D:\openvr-master\openvr-master\samples\bin\drivers\sample\resources\settings\default.vrsettings
Thu Mar 30 2017 09:14:11.002 - [Settings] Load Default Json Settings from D:\Steam\steamapps\common\SteamVR\drivers\null\resources\settings\default.vrsettings
Thu Mar 30 2017 09:14:11.002 - [Settings] Load Json Settings from D:\Steam\config\steamvr.vrsettings
Thu Mar 30 2017 09:14:11.003 - Unable to read app config file from D:\Steam\config\appconfig.json. No applications will be available
Thu Mar 30 2017 09:14:11.035 - [DriverManager] Create new Resource Driver Manager
Thu Mar 30 2017 09:14:11.036 - Skipping external driver  because it is not a directory
Thu Mar 30 2017 09:14:11.037 - Load Json firmware manifest from D:\Steam\steamapps\common\SteamVR\drivers\lighthouse\firmware\manifest.vrfirmware
Thu Mar 30 2017 09:14:11.037 - Add Json firmware manifest from D:\Steam\steamapps\common\SteamVR\drivers\htc\resources\firmware\manifest.vrfirmware
Thu Mar 30 2017 09:14:11.043 - New Connect message from D:\Steam\steamapps\common\SteamVR\tools\bin\win32\vrmonitor.exe (VRApplication_VRMonitor) (Args: -startedbyvrbutton) 15968 
Thu Mar 30 2017 09:14:11.046 - Creating builtin app for D:\Steam\steamapps\common\SteamVR\tools\bin\win32\vrmonitor.exe (VRApplication_VRMonitor)
Thu Mar 30 2017 09:14:11.046 - Setting app system.generated.vrmonitor.exe PID to 15968
Thu Mar 30 2017 09:14:11.046 - Unable to load driver leap from D:\Steam\steamapps\common\SteamVR\drivers\leap\bin\win64\driver_leap.dll.
Thu Mar 30 2017 09:14:11.046 - Unable to load driver leap because of error 103. Skipping.
Thu Mar 30 2017 09:14:11.052 - lighthouse: Attached HID Devices:
Thu Mar 30 2017 09:14:11.052 - lighthouse:     No devices
Thu Mar 30 2017 09:14:11.052 -   driver lighthouse implements interfaces IVRSettings_002 ITrackedDeviceServerDriver_005 IVRDisplayComponent_002 IVRDriverDirectModeComponent_002 IVRControllerComponent_001 IVRCameraComponent_002 IServerTrackedDeviceProvider_004 IVRWatchdogProvider_001 
Thu Mar 30 2017 09:14:11.052 - Loaded server driver lighthouse (IServerTrackedDeviceProvider_004) from D:\Steam\steamapps\common\SteamVR\drivers\lighthouse\bin\win64\driver_lighthouse.dll
Thu Mar 30 2017 09:14:11.052 - Driver lighthouse has no suitable devices.
Thu Mar 30 2017 09:14:11.053 - error VRInitError_Driver_RuntimeOutOfDate when initing driver oculus from D:\Steam\steamapps\common\SteamVR\drivers\oculus\bin\win64\driver_oculus.dll.
Thu Mar 30 2017 09:14:11.053 - Unable to load driver oculus because of error 204. Skipping.
Thu Mar 30 2017 09:14:11.054 - error VRInitError_Driver_RuntimeOutOfDate when initing driver oculus_legacy from D:\Steam\steamapps\common\SteamVR\drivers\oculus_legacy\bin\win64\driver_oculus_legacy.dll.
Thu Mar 30 2017 09:14:11.054 - Unable to load driver oculus_legacy because of error 204. Skipping.
Thu Mar 30 2017 09:14:11.055 - sample: Using settings values
Thu Mar 30 2017 09:14:11.055 - sample: driver_null: Serial Number: 
Thu Mar 30 2017 09:14:11.055 - sample: driver_null: Model Number: 
Thu Mar 30 2017 09:14:11.055 - sample: driver_null: Window: 0 0 0 0
Thu Mar 30 2017 09:14:11.055 - sample: driver_null: Render Target: 0 0
Thu Mar 30 2017 09:14:11.055 - sample: driver_null: Seconds from Vsync to Photons: 0.000000
Thu Mar 30 2017 09:14:11.055 - sample: driver_null: Display Frequency: 0.000000
Thu Mar 30 2017 09:14:11.055 - sample: driver_null: IPD: 0.063000
Thu Mar 30 2017 09:14:11.055 - Driver sample attempted to add tracked device with no serial number
Thu Mar 30 2017 09:14:11.055 -   driver sample implements interfaces IVRSettings_002 ITrackedDeviceServerDriver_005 IVRDisplayComponent_002 IVRDriverDirectModeComponent_002 IVRControllerComponent_001 IVRCameraComponent_002 IServerTrackedDeviceProvider_004 IVRWatchdogProvider_001 
Thu Mar 30 2017 09:14:11.055 - Loaded server driver sample (IServerTrackedDeviceProvider_004) from D:\openvr-master\openvr-master\samples\bin\drivers\sample\bin\win64\driver_sample.dll
Thu Mar 30 2017 09:14:11.055 - Driver sample has no suitable devices.
Thu Mar 30 2017 09:14:11.055 - Unable to load driver sample from D:\openvr-master\openvr-master\samples\bin\drivers\sample\bin\win64\bin\win64\driver_sample.dll.
Thu Mar 30 2017 09:14:11.055 - Unable to load driver sample because of error 103. Skipping.
Thu Mar 30 2017 09:14:11.055 - Not loading driver null because it is disabled in settings
Thu Mar 30 2017 09:14:11.055 - No connected devices found. Returning best error VRInitError_Init_HmdNotFound
Thu Mar 30 2017 09:14:11.055 - Allowing driver load failure VRInitError_Init_HmdNotFound for application vrmonitor (15968) because it is vrmonitor
Thu Mar 30 2017 09:14:11.055 - Processing message VRMsg_Connect from vrmonitor (15968) took 0.0125 seconds
Thu Mar 30 2017 09:14:11.165 - New Connect message from D:\Steam\steamapps\common\SteamVR\bin\win32\vrcompositor.exe (VRApplication_Background) (Args: ) 2332 
Thu Mar 30 2017 09:14:11.168 - Creating builtin app for D:\Steam\steamapps\common\SteamVR\bin\win32\vrcompositor.exe (VRApplication_Background)
Thu Mar 30 2017 09:14:11.168 - Setting app system.generated.vrcompositor.exe PID to 2332
Thu Mar 30 2017 09:14:11.168 - Refusing connect from vrcompositor (2332) because VRInitError_Init_HmdNotFound
Thu Mar 30 2017 09:14:11.168 - IPCPipe(vrcompositor (2332)): Process disconnected.
Thu Mar 30 2017 09:14:11.168 - Process vrcompositor (2332) disconnected

**Comment by dashingstag** [comment]
It appears that I may have succeeded.
There is a green symbol at the HMDlighted up on my steamVR interface

It appears that I had to place the folder sample into the Steam\steamapps\common\SteamVR\drivers
directory. Sorry if this was common knowledge.


Thu Mar 30 2017 09:33:07.956 - sample: Using settings values
Thu Mar 30 2017 09:33:07.956 - sample: driver_null: Serial Number: SampleModel 1
Thu Mar 30 2017 09:33:07.956 - sample: driver_null: Model Number: 
Thu Mar 30 2017 09:33:07.956 - sample: driver_null: Window: 20 20 800 600
Thu Mar 30 2017 09:33:07.956 - sample: driver_null: Render Target: 400 300
Thu Mar 30 2017 09:33:07.956 - sample: driver_null: Seconds from Vsync to Photons: 0.011000
Thu Mar 30 2017 09:33:07.956 - sample: driver_null: Display Frequency: 0.000000
Thu Mar 30 2017 09:33:07.956 - sample: driver_null: IPD: 0.063000
Thu Mar 30 2017 09:33:07.957 -   driver sample implements interfaces IVRSettings_002 ITrackedDeviceServerDriver_005 IVRDisplayComponent_002 IVRDriverDirectModeComponent_002 IVRControllerComponent_001 IVRCameraComponent_002 IServerTrackedDeviceProvider_004 IVRWatchdogProvider_001 
Thu Mar 30 2017 09:33:07.957 - Loaded server driver sample (IServerTrackedDeviceProvider_004) from D:\Steam\steamapps\common\SteamVR\drivers\sample\bin\win64\driver_sample.dll
Thu Mar 30 2017 09:33:07.957 - Active HMD set to sample.SampleModel 1
Thu Mar 30 2017 09:33:07.957 - Guessing frequency of current display mode because SDL failed us
Thu Mar 30 2017 09:33:07.957 - Processing message VRMsg_Connect from vrmonitor (12368) took 0.709 seconds
Thu Mar 30 2017 09:33:07.958 - DXGI thread failed to get SDL display index
Thu Mar 30 2017 09:33:08.019 - New Connect message from D:\Steam\steamapps\common\SteamVR\bin\win32\vrcompositor.exe (VRApplication_Background) (Args: ) 5172 
Thu Mar 30 2017 09:33:08.021 - Creating builtin app for D:\Steam\steamapps\common\SteamVR\bin\win32\vrcompositor.exe (VRApplication_Background)
Thu Mar 30 2017 09:33:08.021 - Setting app system.generated.vrcompositor.exe PID to 5172
Thu Mar 30 2017 09:33:08.021 - Using existing HMD sample.SampleModel 1
Thu Mar 30 2017 09:33:08.778 - [Settings] Save Json Settings to D:\Steam\config\steamvr.vrsettings
Thu Mar 30 2017 09:33:08.778 - Processing message VRMsg_Settings_Sync from vrcompositor (5172) took 0.0159 seconds
Thu Mar 30 2017 09:33:08.778 - Processing message VRMsg_Settings_GetBool from vrmonitor (12368) took 0.0159 seconds
Thu Mar 30 2017 09:33:09.023 - Processing message VRMsg_AddApplicationManifest from vrmonitor (12368) took 0.00926 seconds
Thu Mar 30 2017 09:33:09.065 - [System] Not launching home app, since home app option isn't enabled.
Thu Mar 30 2017 09:33:09.085 - New Connect message from D:\Steam\steamapps\common\SteamVR\tools\bin\win32\vrdashboard.exe (VRApplication_Overlay) (Args: ) 6448 
Thu Mar 30 2017 09:33:09.088 - Creating builtin app for D:\Steam\steamapps\common\SteamVR\tools\bin\win32\vrdashboard.exe (VRApplication_Overlay)
Thu Mar 30 2017 09:33:09.088 - Setting app system.generated.vrdashboard.exe PID to 6448
Thu Mar 30 2017 09:33:09.088 - VRDashboard watchdog enabled for pid:6448
Thu Mar 30 2017 09:33:09.088 - Using existing HMD sample.SampleModel 1
Thu Mar 30 2017 09:33:09.314 - New Connect message from D:\Steam\steam.exe (VRApplication_Overlay) (Args: steam://rungameid/250820) 16816 
Thu Mar 30 2017 09:33:09.317 - Creating builtin app for D:\Steam\steam.exe (VRApplication_Overlay)
Thu Mar 30 2017 09:33:09.317 - Setting app system.generated.steam.exe PID to 16816
Thu Mar 30 2017 09:33:09.317 - Using existing HMD sample.SampleModel 1
Thu Mar 30 2017 09:33:09.347 - D:\Steam\config\steamapps.vrmanifest - No applications in manifest
Thu Mar 30 2017 09:33:19.328 - 0 - entering standby
Thu Mar 30 2017 09:33:34.698 - [Settings] Save Json Settings to D:\Steam\config\steamvr.vrsettings
Thu Mar 30 2017 09:33:36.833 - [Settings] Save Json Settings to D:\Steam\config\steamvr.vrsettings
Thu Mar 30 2017 09:33:37.824 - [Settings] Save Json Settings to D:\Steam\config\steamvr.vrsettings

**Comment by dashingstag** [comment]
not sure why the model number still isnt showing though. I think i saw a fix for this in a branch https://github.com/ValveSoftware/openvr/pull/342/files 
but havent tested it yet

**Comment by JoeLudwig** [comment]
You don't need to copy your driver to any particular spot.  The last couple steps on this page let your driver work from wherever: https://github.com/ValveSoftware/openvr/wiki/Driver-Documentation

You will need the fix from that pull request to make model number work. That change will be in the next SDK update. Obviously for a non-toy driver you're going to want to provide a model number based on what you glean from the actual device rather than a user setting.
