### ISSUE TITLE
BUG: How to get rid of 'extended mode' warnings in IVRDriverDirectModeComponent driver?

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#454]
In the case of a IVRDriverDirectModeComponent driver, it doesn't make sense for OpenVR to give 'extended mode' warnings, as OpenVR is not in control of the display output. In particular, my driver doesn't even have a Windows display output (direct mode or extended mode), so any message in this respect is meaningless. The Oculus IVRDriverDirectModeComponent driver doesn't give this warning, so there must be some way for the driver to tell OpenVR to 'not care' or 'shut up' about this. What is it?

**Comment by TheDeveloperGuy** [comment]
Seems like all of the 'direct mode' SteamVR settings should be removed or disabled when running with this type of driver too.

**Comment by TheDeveloperGuy** [comment]
@aleiby How does the Oculus driver turn off this warning? I've gone through (and tried) all of the public properties, even non-intuitive ones (like setting universe to Oculus etc.).

**Comment by vicdxxx** [comment]
it is hard to achieve openvr driver in steam vr, I DIY one, but it can not direct mode too

**Comment by TheDeveloperGuy** [comment]
Cool story Bro!

**Comment by aleiby** [comment]
I think the Oculus driver only works because we actually wind up detecting that the display is in direct mode (using nvidia/amd private interfaces) since the driver provides proper edid vid/pid.  For devices that are not actually present (e.g. streaming to a mobile device) I'm in the process of adding a new IVRVirtualDisplay interface which drivers can implement and will hopefully be a better and easier path for such devices.

**Comment by TheDeveloperGuy** [comment]
Ok, so in other words, there is "no way at present" to remove this warning?

**Comment by TheDeveloperGuy** [comment]
@JoeLudwig @aleiby Possible to review the IVRVirtualDisplay interface before it gets set in stone?

**Comment by Balderick** [comment]
How do the ms vr platform devices access "vr mode"?    AFAIK these devices (hmds) must use thunderbolt or something to pipe audio video and data through one USB cable.   These devices definitely do not support direct mode.   We may see other methods of switching to vr dedicated mode soon though is likely to be dependent on proprietary driver white listing also.

**Comment by LoSealL** [comment]
@aleiby Hi aleiby, I'm very pleased to hear that IVRVirtualDisplay interface is on the way, because there are more and more wireless solutions trying to stream game content to hmd. Do you have any plan when this interface will be added?

**Comment by TheDeveloperGuy** [comment]
Key can be set in steamvr.vrsettings to disable warning.
