### ISSUE TITLE
Version Info for open_vr.dll

### ISSUE THREAD

**Issue by siddharthuniv** [ValveSoftware/openvr#455]
Hi,

We have a process at our company to have all dlls being  versioned. Can you provide version info for openvr_api.dll? 

Thank you,

Sid

**Comment by jrbudda** [comment]
yes plz. https://github.com/ValveSoftware/openvr/issues/132

**Comment by kisak-valve** [comment]
Closing as a duplicate of #132.

**Comment by siddharthuniv** [comment]
Could you please explain why the duplicate and this issues were closed and not resolved? There are quite some people who would like it to be versioned.

**Comment by kisak-valve** [comment]
@siddharthuniv, #132 is currently an open issue report, this is indicated directly below the title at the top of that issue report.
