### ISSUE TITLE
OpenVR DX12 crashing with VIVE, fine with Oculus

### ISSUE THREAD

**Issue by jebmayers** [ValveSoftware/openvr#456]
Hi,

We have implemented DX12 support in our engine using the documentation here:
https://github.com/ValveSoftware/openvr/wiki/DirectX12

Aside from one issue this is working fine with Oculus. However, with the VIVE headset I get a crash shortly after the first calls to vr::VRCompositor()->Submit. No error is returned from these functions.

I get the following debug output:

Thu Mar 30 2017 15:23:29.122 - [Chaperone] Universe changed from 0 to 1489158717.
Thu Mar 30 2017 15:23:29.266 - Capturing Scene Focus
Thu Mar 30 2017 15:23:29.315 - Created shared texture 'Scene create D3D12, 0' 1911x2020 (1 mips)
Thu Mar 30 2017 15:23:29.317 - Created shared texture 'Scene create D3D12, 0' 1911x2020 (1 mips)
Thu Mar 30 2017 15:23:29.318 - Created shared texture 'Scene create D3D12, 0' 1911x2020 (1 mips)
Thu Mar 30 2017 15:23:29.320 - Created shared texture 'Scene create D3D12, 1' 1911x2020 (1 mips)
Thu Mar 30 2017 15:23:29.321 - Created shared texture 'Scene create D3D12, 1' 1911x2020 (1 mips)
Thu Mar 30 2017 15:23:29.323 - Created shared texture 'Scene create D3D12, 1' 1911x2020 (1 mips)

The very next call to the vr::VRCompositor() crashes with a com error:

Exception thrown at 0x00007FFBDC4C7788 in MyTitle_x64.exe: Microsoft C++ exception: _com_error at memory location 0x000000000014F790.
Exception thrown at 0x00007FFBDC4C7788 in MyTitle_x64.exe: Microsoft C++ exception: _com_error at memory location 0x000000000014F790.

And the next call:

Exception thrown at 0x00007FFBDC4C7788 in MyTitle_x64.exe: Microsoft C++ exception: _com_error at memory location 0x000000000014F7F0.
Exception thrown at 0x00007FFBDC4C7788 in MyTitle_x64.exe: Microsoft C++ exception: _com_error at memory location 0x000000000014F370.

Followed by device removal.

D3D11: Removing Device.
D3D12: Removing Device.

This is pretty much game over for our app. Has anyone seen this problem before?

Many thanks,

Jeb Mayers

**Comment by danginsburg** [comment]
Resolved this issue privately with developer.  The problem turned out to be that the VrTextureBounds_t uMax/vMax exceeded 1.0.  The DirectX12 render path was more sensitive about this than DX11 and was throwing the exception.  For now, we have not changed SteamVR but instead recommended that the developer clamp the UV bounds.  We may look at clamping the UV bounds internally in the future.
