### ISSUE TITLE
vive tracker supported?

### ISSUE THREAD

**Issue by joohwankim** [ValveSoftware/openvr#458]
I wonder whether OpenVR currently supports the new vive trackers, and if not, whether there is any plan for that. I just tried it assuming that it is the same as controllers, but it did not work. I think it is not a difficult job to add the support because the function (and probably the interface as well) seems to be almost identical to the controllers.

**Comment by JoeLudwig** [comment]
The Vive tracker is fully supported. Just look for objects with the tracked device class TrackedDeviceClass_GenericTracker .

**Comment by joohwankim** [comment]
Thanks a lot!
