### ISSUE TITLE
How to report button event?

### ISSUE THREAD

**Issue by HelenXR** [ValveSoftware/openvr#465]
I modify the Hydra driver,The main code is as follows:
```
TrackedDeviceButtonPressed(left_hand->m_nUniqueObjectId, vr::k_EButton_SteamVR_Trigger, 0.0);
msleep(100);
TrackedDeviceButtonUnpressed(left_hand->m_nUniqueObjectId, vr::k_EButton_SteamVR_Trigger, 0.0)
```
But it doesn't work.

**Comment by HelenXR** [comment]
I see i should also need to operate TrackedDeviceAxisUpdated  
send button is not easy :-(

**Comment by TheDeveloperGuy** [comment]
@HelenXR I trust you got my email, if not, please let me know and I'll resend. To answer your question, you're sending the wrong value to TrackedDeviceButton...(). You need to send vr::ButtonMaskFromId(vr::k_EButton_SteamVR_Trigger).

**Comment by HelenXR** [comment]
@TheDeveloperGuy 
First of all, thank you for your  many times helps
" I trust you got my email" 
this email is about "direct mode"? I receive some message of your replay about direct mode,but  i  am preparing for the Hongkong Electronics Fair during this week.I am sorry I can't reply the discuss this week.I need to integrate a position tracker based on a binocular camera and two controllers (like PSVR).

**Comment by JoeLudwig** [comment]
Looks like @TheDeveloperGuy covered this one.
