### ISSUE TITLE
Getting devices status

### ISSUE THREAD

**Issue by xrgo** [ValveSoftware/openvr#466]
Hello! I am trying to replicate the steamVR mini window within my app, to show the HMD, controllers, and basestations status/icons. the problem is I am not sure how to get this information from the API, currently I am reading events, so for instance if I have **event.eventType == vr::VREvent_TrackedDeviceActivated** I will show the proper icon, its kinda working...
But I don't think that's the correct way, for example I don't have a way to get the initial state of the devices and I don't have an event for low battery.

The obvious thing to me is that somehow I have to get an **EVRState** but I have no idea how to correctly get it...
if I do:
```
    if( event.eventType == vr::VREvent_StatusUpdate ){
        if( event.data.status.statusState == vr::VRState_Ready ){
            //GREEN
        }
        else if( event.data.status.statusState == vr::VRState_NotReady ){
            //RED
        }
    }
```
I can only get the state of the "title" (Ready or Not Ready)

if I print **event.data.status.statusState** for every event, it seems to be doing some stuffs when devices change status but the numbers it prints are nothing to do with any of the **EVRState**

anyone has some code that can share??

Many thanks in advance!

**Comment by JoeLudwig** [comment]
Take a look at the rest of the functions in IVRSystem. The status window uses GetTrackedDeviceClass, pose information, and a bunch of properties to figure out what to show.

**Comment by xrgo** [comment]
Thank you, I was hopping I have missed something that can give me an EVRState, so it seems that I have to figure out the right combination of events, poses and properties for each icon/state. Thanks
