### ISSUE TITLE
Support for dual-display HMDs

### ISSUE THREAD

**Issue by godbyk** [ValveSoftware/openvr#468]
We've succeeded in implementing the `IVRDriverDirectModeComponent` interface in the OSVR SteamVR driver and it now outputs to our compositor. This works well for single-display devices.

Now we're looking at supporting dual-display devices—that is, an HMD that has two HDMI inputs—one display per eye.

Our compositor supports these devices natively, but we're having difficulty getting SteamVR to startup successfully with this configuration.

We we run SteamVR, the SteamVR compositor complains:

```
Thu Mar 30 2017 16:52:40.244 - Headset display is on desktop
Thu Mar 30 2017 16:52:40.245 - Invalid adapter (-1, -1) specified!
Thu Mar 30 2017 16:52:40.246 - Failed to initialize compositor
Thu Mar 30 2017 16:52:40.247 - Failed to start compositor: VRInitError_Compositor_Failed
```

The SteamVR compositor says the headset display is on the desktop, even though the OSVR driver is reporting that the headset is in direct mode and is not on the desktop.

What role does the SteamVR compositor play when the `IVRDriverDirectModeComponent` interface is in use?  Does it still perform checks for the existence of a display?

What do we need to do to get a SteamVR driver with the `IVRDriverDirectModeComponent` interface to work with dual-display devices?

Thanks!

**Comment by TheDeveloperGuy** [comment]
Set these properties:

SetBoolProperty(m_ulPropertyContainer, Prop_IsOnDesktop_Bool, false); 
SetBoolProperty(m_ulPropertyContainer, Prop_UsesDriverDirectMode_Bool, true);

Implement these driver methods:

return false from IsDisplayOnDesktop()
return false from IsDisplayRealDisplay()

The OpenVR compositor doesn't (shouldn't!) do any kind of display checking for a direct mode driver. There are some bugs(?) where it will report that the display is in "extended mode" (benign, but somewhat irritating) regardless of what's going on in your driver, and you'll get a DXGI error message in your log (benign).

How you deal with dual displays is up to your compositor. You'll be composing the separate left and right eye textures into whatever your output is.

**Comment by godbyk** [comment]
I had everything set correctly except for `IsDisplayRealDisplay()`. Adjusting that to return `false` when using my own compositor fixed the problem.

Thanks, @TheDeveloperGuy for the pointer!

**Comment by botsolutionsventure** [comment]
hey, @TheDeveloperGuy a follow up question regarding to this thread~ 

i am trying to understand how steamVR compositor works for dual-display (2 HDMI output), does it work the same as 1 HDMI output? if not, what is the difference?

thanks!

**Comment by TheDeveloperGuy** [comment]
@botsolutionsventure The short answer is it doesn't support dual-display. If you want that you will have to either use the IVRDriverDirectModeComponent or IVRVirtualDisplay interface and deal with the output yourself.

**Comment by botsolutionsventure** [comment]
thanks @TheDeveloperGuy I am a newbie here. so IVRDriverDirectModeComponent is the HMD driver API right? steamVR compositor is in runtime, if we implement HMD driver API to support dual HMD, it doesn't mean we do anything regarding to runtime compositor, right? 

i wonder how @godbyk  can handle the dual display case? what HMD do you have? 

thanks~

**Comment by TheDeveloperGuy** [comment]
@botsolutionsventure You will need to implement your own compositor if you go down the IVRDriverDirectModeComponent route. If you're a newbie, you can forget about being able to do that, it's non-trivial to say the least! In any case if you write an HMD driver to whichever interface you choose, you don't have to worry about what the SteamVR compositor does, as that's "not your problem". You will need to implement the driver through one of the fore-mentioned driver interfaces, where you'll get the texture for each eye (a little bit more work on IVRVirtualDisplay as you'll get a single side-by-side texture that you'll have to split) from the SteamVR runtime. You'll need to then get those textures to your display somehow. 

godbyk was developing a driver for OSVR (which has it's own compositor, and hence can do whatever it likes with the texture the driver gives it). 

Developing HMD drivers is what I do, so if you want to discuss this further offline, leave your email address here and I'll contact you directly.

**Comment by botsolutionsventure** [comment]
@TheDeveloperGuy Great answer, i would love to talk to you more about my problem, please contact me through lizhengmin@gmail.com

**Comment by Balderick** [comment]
The steamvr-osvr driver is what godbyk was referring too, which is an openvr driver.    godbyk is adding support for two display hmds already supported in osvr to the steamvr-osvr driver, for openvr support.

The steamvr-osvr driver tries to support all osvr supported devices through one openvr driver.

**Comment by DavidChen528** [comment]
> i would love to talk to you more about my problem, please contact me through



> @botsolutionsventure You will need to implement your own compositor if you go down the IVRDriverDirectModeComponent route. If you're a newbie, you can forget about being able to do that, it's non-trivial to say the least! In any case if you write an HMD driver to whichever interface you choose, you don't have to worry about what the SteamVR compositor does, as that's "not your problem". You will need to implement the driver through one of the fore-mentioned driver interfaces, where you'll get the texture for each eye (a little bit more work on IVRVirtualDisplay as you'll get a single side-by-side texture that you'll have to split) from the SteamVR runtime. You'll need to then get those textures to your display somehow.
> 
> godbyk was developing a driver for OSVR (which has it's own compositor, and hence can do whatever it likes with the texture the driver gives it).
> 
> Developing HMD drivers is what I do, so if you want to discuss this further (offline), leave your email address here and I'll contact you directly.

 I would like to talk to you more about my problem, please contact me through david_chen528@163.com
