### ISSUE TITLE
osx32 lib needs to be updated to 0.9.14

### ISSUE THREAD

**Issue by rramsden** [ValveSoftware/openvr#47]
The lib for osx32 needs to be updated to 0.9.14 its still on 0.9.13

**Comment by mummey** [comment]
Yep, this method is broken on Mac because its lib hasn't been updated.

    VR_INTERFACE const char *VR_CALLTYPE VR_GetVRInitErrorAsEnglishDescription( vr::EVRInitError error );

**Comment by rramsden** [comment]
Looks like the OSX lib was just updated to 0.9.16 so closing this issue
https://github.com/ValveSoftware/openvr/commit/c174bafe1e3d150ff44d23209f89e312bda93189
