### ISSUE TITLE
C# LoadRenderModel_Async throw AccessViolationException

### ISSUE THREAD

**Issue by LamerTex** [ValveSoftware/openvr#471]
I'm using OpenVR in a 3D cad .NET application in C# and I've successfully integrated the tracking of both the HMD and controllers using "higher level" function of the application, loading directly the 3D models (converting the .obj files in .str).
It works fine but the controllers are always the "base model" without leds and pressed buttons like in the native applications created via unity or directly in OpenCV (and c++ like the  HelloVR example in this repository), so I was trying to get the models and textures directly from the OpenVR api and then somehow using them in my application.

Looking at the HelloVR example the steps to load the render models (and then the textures) are simply:

- `vr::IVRRenderModels* m_pRenderModels =(vr::IVRRenderModels*)vr::VR_GetGenericInterface(vr::IVRRenderModels_Version, &eError );`

- `vr::RenderModel_t *pModel;`

- `vr::EVRRenderModelError error = m_pRenderModels->LoadRenderModel_Async( pchRenderModelName, &pModel );`

In C# this become a bit more complex (because of the conversion from ptr to struct and viceversa), but I think I'm doing it correctly with:      
- `IntPtr renderModelPtr = OpenVR.GetGenericInterface(OpenVR.IVRRenderModels_Version, ref eError);`
`IVRRenderModels renderModels = Marshal.PtrToStructure<IVRRenderModels>(renderModelPtr);`
- `RenderModel_t pModel = new RenderModel_t();`
   `IntPtr modelPointer = Marshal.AllocHGlobal(Marshal.SizeOf(pModel));`
   `Marshal.StructureToPtr(pModel,modelPointer,false);`
 -  `EVRRenderModelError error = renderModels.LoadRenderModel_Async(pchRenderModelName, ref modelPointer);`

renderModel is initialized without problems and with _Marshal.AllocHGlobal_  the render model should be allocated somewhere in the memory of the process (with a size of 32 bytes as returned from _Marshal.SizeOf(pModel)_ ).
When _LoadRenderModel_Async_ is called a System.AccessViolationException is thrown with the error message "Attempted to read or write protected memory. This is often an indication that other memory is corrupt."
 It seems like a problem with the IntPtr modelPointer, but I didn't find any other way to create a pointer to a RenderModel_t and no example that use OpenVR in C# to see how to do this...

Thanks for your time!

**Comment by echeese** [comment]
You may want to check out how the Unity Plugin does this: https://github.com/ValveSoftware/steamvr_unity_plugin/blob/master/Assets/SteamVR/Scripts/SteamVR_RenderModel.cs

**Comment by LamerTex** [comment]
Thanks you @echeesewith, with all the research to find some examples in C # I never opened the Unity Plugin repository because I didn't want to use Unity so I automatically removed everything that had unity in the name... that was a really bad choice
With that code all is way more clear and I was using the completely wrong structures/methods :D 
The correct way in C# to do what I was trying to do is:
- `CVRRenderModels renderModels = OpenVR.RenderModels;`
- `IntPtr modelPointer = System.IntPtr.Zero;`
- `EVRRenderModelError errorRender =  renderModels.LoadRenderModel_Async(modelName, ref modelPointer);`
Then I can get the RenderModel_t from the IntPtr with
- `RenderModel_t pModel = (RenderModel_t)Marshal.PtrToStructure(modelPointer, typeof(RenderModel_t));`

Now I can study that repository to learn how to use correctly OpenVR in C#, thanks for your help.
