### ISSUE TITLE
Correct way for HMD driver to trigger SteamVR exit?

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#473]
Seen some references to the possibility that the HMD driver can cause SteamVR to exit, and see it happening in the Oculus driver (turn off the DK2 and SteamVR will exit).

I'm using this:

VREvent_Reserved_t data = { 0, 0 };
vr::VRServerDriverHost()->VendorSpecificEvent(m_unObjectId, vr::VREvent_DriverRequestedQuit, (VREvent_Data_t&)data, 0);

It works, but is it the "right" way to do this?

**Comment by vicdxxx** [comment]
so cool

**Comment by vicdxxx** [comment]
you just try it...check it is work or not

**Comment by JoeLudwig** [comment]
Yes, that's the right way to do this.

**Comment by Copter64** [comment]
Which language is this, and is this while running their SDK I am assuming?
