### ISSUE TITLE
Vive Camera and Augmented Reality

### ISSUE THREAD

**Issue by JoshKlint** [ValveSoftware/openvr#484]
I am attempting to implement augmented reality via the Vive front-facing camera.  I want to draw the video feed onto the scene background in the same manner that the “room view” option does in SteamVR:
https://i.ytimg.com/vi/npg3Zt-WILU/maxresdefault.jpg

I am able to obtain the video feed data and draw it onscreen but am not sure how to position the image.  I suspect GetCameraProjection() might contain the needed info, but it is not clear how to draw and project the image to match the “room view” option:
http://steamcommunity.com/sharedfiles/filedetails/?id=913606944

**Comment by strungoutonvr** [comment]
Drop me an email if you want to collaborate... alex@strungoutonvr.com - I am starting to work on a similar project and need to solve this as well.  I have a few ideas on how to approach this - I am not sure vive really considered using the camera for AR, but I certainly see the need.

**Comment by alexbu92** [comment]
Have you ever figured it out?

**Comment by CharlyGirotNYU** [comment]
@JoshKlint, @strungoutonvr . Have you find a way through it ?

**Comment by JoshKlint** [comment]
I would not bother trying. A single camera four inches in front of your eyes does not relate to two views from your eye positions.
