### ISSUE TITLE
D3D12 Debug Layer shows an error when calling submit.

### ISSUE THREAD

**Issue by Slin** [ValveSoftware/openvr#486]
The debug layer shows the following error when calling submit:

> D3D12 ERROR: ID3D12CommandList::CopyResource: Source and Destination resource must have the same size. But pSrcResource has resource size (8978432) and pDstResource has resource size (-1). [ RESOURCE_MANIPULATION ERROR #944: COPYRESOURCE_INVALIDDSTRESOURCE]

**Comment by danginsburg** [comment]
I believe this should be fixed in the latest SteamVR Beta release.  Can you check again and see if it still broken?  If so, can you provide more information including posting Steam -> Help -> System Information.

**Comment by Slin** [comment]
Sorry, I didn't realize that I didn't opt into the beta yet.
Works perfectly with the beta!
