### ISSUE TITLE
linux64 build

### ISSUE THREAD

**Issue by ssantos** [ValveSoftware/openvr#49]
Hi there - I am on an older version of linux and my machines are using GLIBC_2.12. I see the linux64 build uses GLIBC_2.14 - any way to get a build with the older version of libc? Thanks.

**Comment by johnv-valve** [comment]
Sorry, openvr on Linux requires at least the same minimum as Steam on Linux - Ubuntu 12.04 or better. Also recommend running your process in the Steam Runtime to ensure binary compatibility across distros.

**Comment by ssantos** [comment]
Thanks johnv-valve. I successfully compiled/ran a test app on a Centos 7.  I was trying Centos 6 previously.

Is it possible to just use openvr standalone - without the Steam Runtime? I have controllers and a head mounted device, and I simply want to use them as tracking input devices. Is that possible without running Steam Runtime? Currently my test app doesn't find any active installation of the VR API, despite plugging my controllers and devices.

Sorry if this isn't the forum for these questions but any help would be appreciated. Thanks.
