### ISSUE TITLE
VRInitErrorAsSymbol missing VRInitError_Init_VRDashboardNotFound and VRInitError_Init_VRDashboardStartupFailed

### ISSUE THREAD

**Issue by spayne** [ValveSoftware/openvr#494]
There are a couple missing enum to string converters.  These are missing in 1.07 and 1.06. (I don't know about 1.05).

To reproduce:
printf("%s\n", vr::VR_GetVRInitErrorAsSymbol(vr::VRInitError_Init_VRDashboardNotFound));
printf("%s\n", vr::VR_GetVRInitErrorAsEnglishDescription(vr::VRInitError_Init_VRDashboardNotFound));

printf("%s\n", vr::VR_GetVRInitErrorAsSymbol(vr::VRInitError_Init_VRDashboardStartupFailed));
printf("%s\n", vr::VR_GetVRInitErrorAsEnglishDescription(vr::VRInitError_Init_VRDashboardStartupFailed));

Expected output (example)
VRInitError_Init_VRDashboardNotFound
The dashboard could not be found.
VRInitError_Init_VRDashboardStartupFailed.
The dashboard was found, but failed to startup.

Actual output:
Unknown error (133)
Unknown error (133)
Unknown error (134)
Unknown error (134)

**Comment by JoeLudwig** [comment]
Thanks. These (and some others that were missing) will be in the next beta and in an SDK sometime after that.
