### ISSUE TITLE
Added TrackedDeviceClass_DisplayRedirect, Present not called

### ISSUE THREAD

**Issue by thezenmaster** [ValveSoftware/openvr#497]
I have added a TrackedDeviceClass_DisplayRedirect device (using the TrackedDeviceAdded method) which implements IVRVirtualDisplay. However, present is not called. Also, on Activate, I set Prop_HasVirtualDisplayComponent_Bool to true. 

Is this the the intended way to use IVRVirtualDisplay? Am I missing something?

**Comment by sencercoltu** [comment]
I think the Prop_HasVirtualDisplayComponent_Bool  property is set
automatically if your driver implements IVRVirtualDisplay and you return
the interface pointer in your drivers GetComponent function . I got the
component working without setting the Prop_HasVirtualDisplayComponent_Bool
  and without adding the TrackedDeviceClass_DisplayRedirect in my driver.

**Comment by thezenmaster** [comment]
Hey, thanks for the super quick reply!

So, yeah, that was the first thing I tried, but then the surface I'm getting on Present is all black. I'm missing something.. 

What should I return in IsDisplayOnDesktop and IsDisplayRealDisplay? Any direct mode properties I need to disable (I've commented out my implementation of IVRDriverDirectModeComponent)? 

Thanks!

**Comment by LoSealL** [comment]
@thezenmaster If you want to redirect to a wireless display, IsDisplayRealDisplay and IsDisplayOnDesktop should both return false. By the way, I don't think IVRDriverDirectModeComponent has conflict with IVRVirtualDisplay.

**Comment by thezenmaster** [comment]
@LoSealL Thanks for the reply! I changed both of them functions to return false, same luck. Just to make sure, this update is live on Steam VR, right? No need for beta access or something?

**Comment by LoSealL** [comment]
@thezenmaster Yeah, doesn't need beta

**Comment by TheDeveloperGuy** [comment]
@thezenmaster Get a basic driver up with the sample driver supplied with the SDK. Once you have that going, add the IVRVirtualDisplay component. Don't try to guess the device class. I don't know what the display redirect device class is for, but it's not this. It must be TrackedDeviceClass_HMD. If you've done everything right and are getting Present() called, you'll need to get the keyed mutex interface from the texture provided to Present() and Acquire() and Release() it or you'll get an all-black texture. This interface works (properly) in both the current Beta and non-Beta versions of SteamVR.

**Comment by thezenmaster** [comment]
@TheDeveloperGuy, thanks! That totally makes sense. I got it to work after acquiring a mutex. 

BTW, I got it to work with acquire and release key 0. That's usually not a good practice, since you can run into sync issues. Any advice? 

Thanks!

**Comment by TheDeveloperGuy** [comment]
@thezenmaster We're in "suck it and see" mode here as there's no guidance on what should be done. Using key index 0 works, so use it until there's a reason not to. Also as your issue is now resolved, please close this issue.

**Comment by thezenmaster** [comment]
Sure, was waiting for your response. Thanks

**Comment by TheDeveloperGuy** [comment]
Not sure what timeout to use, but it seems a sensible one is about 10ms. If you don't get access to the frame in that time abandon the wait as the frame will be too late.
