### ISSUE TITLE
Lib contents appear wrong for non-windows platforms. 

### ISSUE THREAD

**Issue by jherico** [ValveSoftware/openvr#5]
The bin folder, for all platforms, contains shared libraries, as expected.  However, while lib/win* folders contain static libraries (.lib files) the other appear to contain shared libraries again (.so instead for linux, .dylib for OSX instead of .a files).

**Comment by JoeLudwig** [comment]
The lib directory contains import libraries for Windows. There is no static library version of openvr_api.

**Comment by jherico** [comment]
Sorry, yes, I meant the imports for the DLL, not 'static library'.  So, on Linux and OSX, applications can directly use the shared library to link, correct?  So why are the lib folder versions of the files so much bigger than the bin folder version?  Have they simply not been stripped of their debug symbols?

**Comment by feilen** [comment]
I got the OpenVR hellovr project to compile correctly on my system (Arch Linux x86_64) with a handful of small modifications, and it just needs to link straight against the shared library to work.

**Comment by ChristophHaag** [comment]
@feilen Does it actually work this way? I tried https://github.com/ChristophHaag/openvr/commit/ece16455acdf6dcf9d4556d025eed4e9961842c6 but it doesn't work for me, probably because I don't have OpenGL 4.1 here.

**Comment by feilen** [comment]
It works for me, but it appears that the SteamVR Linux client is missing quite a number of things, including the compositor and some parts of the 64-bit runtime.

To get it working, try compiling with `-m32` and running with the `-nocompositor` argument.

**Comment by ChristophHaag** [comment]
If you look at my build_linux.sh, I already used -m32 because for some reason SteamApps/common/OpenVR/bin/linux64/vrserver is a 32 bit application

I tried using `MESA_GL_VERSION_OVERRIDE=4.1 MESA_GLSL_VERSION_OVERRIDE=410 "<...>/run_hellovr.sh" -nocompositor` as the "Target" in steam" but I only got

```
Failed to execute process '/home/chris/oldhome/games/SteamLibraryLinux/SteamApps/common/OpenVR/bin/linux32/vrcompositor': 2
Compositor initialization failed with error: Connect to VR Server Failed (301)
BInit - Failed to initialize VR Compositor!
```
Hm... Maybe I should open a new feature request for documentation how to build and use this stuff.

**Comment by feilen** [comment]
I mentioned! It fails to run OpenVR/bin/linux32/vrcompositor because that
file does not exist. There's chunks missing from the Linux OpenVR it
appears, try running the hellovr demo app with "-nocompositor" arguments.

**Comment by ChristophHaag** [comment]
Ah, I'm just stupid. I forgot that my run script eats all arguments.

Thanks, it actually works with `-nocompositor`.
