### ISSUE TITLE
VR_IVRSystem_GetControllerState doesn't register touchpad button presses

### ISSUE THREAD

**Issue by lukexi** [ValveSoftware/openvr#50]
The `VRControllerState_t` 's `ulButtonPressed` and `ulButtonTouched` both stay 0 when pressing the touchpad in as a button. (Touchpad & trigger axes + grip & application buttons are working fine)

**Comment by JoeLudwig** [comment]
I'm not able to reproduce this. If I run "vrcmd --pollcontrollers" I see the trackpad be touched, then pressed, then not pressed, then not touched.

Are you still seeing it?

**Comment by kazoo-osaro** [comment]
To me, it only returns zero and doesn't work.

**Comment by Balderick** [comment]
Where is the documentation for vrcmd?
A man page or readme describing supported commands and arguments would be useful.
