### ISSUE TITLE
OpenVR Driver Re-ComputeDistortion ?

### ISSUE THREAD

**Issue by zezba9000** [ValveSoftware/openvr#500]
Is it possible to trigger a "IVRDisplayComponent::ComputeDistortion" while the game is running?
This would be nice for testing out distortion algorithms in a real world situation in the OpenVR pipeline.

**Comment by TheDeveloperGuy** [comment]
You'd have to implement a IVRDriverDirectModeComponent driver to be able to do this. In that type of driver you have to write your own shaders for lens distortion, which you can then tweak at runtime (I allow different lens profiles to be loaded at runtime in my driver). Someone has open-sourced one of these drivers, and you can find a link to it here somewhere. I can't speak for it's quality (or whether it even works) as I have only briefly looked at it, but it would probably be useful as either a starting point or an indication of quite how complex one of these drivers is.

**Comment by JoeLudwig** [comment]
@TheDeveloperGuy is on the money. That will cause the compositor to regenerate its distortion mesh.

**Comment by zezba9000** [comment]
Awesome I will give it a try, tnx!
