### ISSUE TITLE
OpenVR Driver custom distortion geometry and not just UVs?

### ISSUE THREAD

**Issue by zezba9000** [ValveSoftware/openvr#501]
We have a custom distortion mesh algorithm for our mesh geometry.
Is it possible to use this distortion mesh XY pos info?

I see in "openvr.h" BUT NOT "openvr_driver.h" that the method "Submit" can take in the arg "EVRSubmitFlags::Submit_LensDistortionAlreadyApplied".

Why is that arg not a driver side thing? Distorting the image using custom geometry should be in the driver but I see no way to do this.

**Comment by JoeLudwig** [comment]
I don't understand what you're asking for.

The app uses this flag to indicate that it has already applied distortion using the values returned from ComputeDistortion and that the compositor shouldn't distort things again. Drivers don't submit textures, though, so a driver wouldn't have an opportunity to submit an already-distorted texture.

It sounds like you just need to implement ComputeDistortion in your driver to look up distortion values from your mesh and return them. That way the compositor (or app) can apply distortion appropriately before presenting the final frame buffer.

**Comment by zezba9000** [comment]
The "ComputeDistortion" method returns a "DistortionCoordinates_t" object. That object only has rgb UVs and no XY pos info I can override. The goal is to use custom distortion vertices not just UVs.

**Comment by JoeLudwig** [comment]
UVs are just XY coordinates divided by the width and height of the viewport.

We do not currently support having the driver provide the distortion mesh directly. You would need to sample your mesh in ComputeDistortion, then the compositor will produce its own mesh internally from those sampled values.

**Comment by zezba9000** [comment]
I know what UVs are. The reason for this issue is the distortion mesh geometry we have is laid out in a way that handles the UV linear interpolation better for our lens for a smoother picture. In short the mesh is not a squared grid.

Can we just disable the OpenVR distortion and manually apply our own distortion pass in some other way?

**Comment by JoeLudwig** [comment]
I understand why you would want to provide the mesh, that's just not something we support at the moment.

You can own the entire display with IVRDriverDirectModeComponent. That's significantly more complex than just distortion, but it's an option.  Right now your only other option is to let the compositor resample your mesh.

**Comment by zezba9000** [comment]
Are there any examples of "IVRDriverDirectModeComponent"? It looked like that was only for OVR.
When I added the IVRDriverDirectModeComponent interface before "DestroySwapTextureSet" was the only method that ever got called. So not sure what is needed to get OpenVR to use this method.

I've made a DirectMode runtime from scratch and am porting support from it to OpenVR instead. So I know all about DirectMode in general, the issue is meshing that with OpenVR.

**Comment by JoeLudwig** [comment]
How many points are in your distortion mesh? Have you tried sampling it in ComputeDistortion and you know that it looks bad? 

IVRDriverDirectModeComponent is going to be significantly more work to implement, so it might be worth trying the simple thing first and then you can try the complex thing if that doesn't work. And unfortunately there's not much documentation available for it at the moment, and there's no sample (in the SDK at least.)

**Comment by zezba9000** [comment]
I'll get back tomorrow after I go over a few things.

**Comment by zezba9000** [comment]
Our distortion algorithm uses a two pass system.
We first do a distortion "kinda" standard pass, then a second pass to adjusts those results based on some bounding boxes to place the UVs within the mesh correctly.

Because a bounding box requires that all UVs be known to wrap them I do this is the first pass, I then did the second pass in RunFrame and use "VREvent_LensDistortionChanged" to apply the final result. **No luck though as the second pass wont index correctly because the two passes have "ComputeDistortion" getting called different amounts of times**.

The problem is it seems the "ComputeDistortion" method gets called different amounts of time depending on what the UV info coming in looks like. This is a huge problem. That black box method isn't powerful enough for our algorithm.

Now I'm stuck with two less ideal time consuming options. re-create the whole mesh that was tweaked for weeks and has been used for half a year now with many people running through it OR some other DirectMode way.

There really needs to be a method to pass in verts like you can for the CVRHiddenAreaHelpers::SetHiddenArea method. I see no reason for this limitation in the API.

To answer your question our mesh is non-squared:
Vertices: 16377
Indices: 73683

**Comment by JoeLudwig** [comment]
The distortion mesh used in the compositor is always the same size, but the edges of it might be tweaked to account for the hidden area mesh (since there's no point in drawing output pixels that consist entirely of hidden stuff.) We also fetch the distortion values of the line loop to fix up some other artifacts, so you may see calls to ComputeDistortion that aren't directly used in the distortion mesh. That might result in slightly different numbers of calls if source pixels move in or our of the hidden area on your mesh refinement.

I don't understand what you mean by "won't index correctly." When you send that event the entire mesh is regenerated with a bunch of calls to ComputeDistortion. You should not try to depend on the order of those calls in any way. Use the incoming UVs to figure out what the outgoing UVs need to be... you can't assume anything else.

I would think that you would do something like this:

1. in Activate: 
 A. Do your first pass and load your mesh. 
 B. Then do your second pass before ever returning from Activate. 
 C.At this point you have your mesh and can use it for responding to ComputeDistortion calls.
2. In ComputeDistortion: Use the incoming target UVs to look up the source UVs in your mesh. 

And that's it. Obviously the mesh used by the compositor will be a re-sampled version of the original mesh, but it might not be visible to a human. No need to recreate your mesh since having a different mesh wouldn't do you any good. The number of verts used in the compositor's distortion mesh is completely out of your control. The compositor could change with any update and those numbers would change. So even without the "changed" event you have no way to predict how many calls you'll get or what order they'll be in.

**Comment by zezba9000** [comment]
Ported our distortion algorithm to work in your system.

**Comment by HelenXR** [comment]
@zezba9000 
Recently also adjust the function of distortion, the last you use which way to achieve it(ComputeDistortion or IVRDriverDirectModeComponent)?

**Comment by zezba9000** [comment]
If I understand you correctly, you use "ComputeDistortion" in your HMD driver class.

```
class DriverHMD : public ITrackedDeviceServerDriver, public IVRDisplayComponent
{
DistortionCoordinates_t ComputeDistortion(EVREye eEye, float fU, float fV)
{
        // Implement your distortion method here...
	return BrownsDistortionUV(eEye, fU, fV);
}
};
```

**Comment by HelenXR** [comment]
@zezba9000 
Thank you for your reply, but what I want to know is how to deal with distortion, which is how BrownsDistortionUV,i use below code
```
	rr = sqrt((fU - 0.5f)*(fU - 0.5f) + (fV - 0.5f)*(fV - 0.5f));
	r2 = rr * (1 + m_fDistortionK1*(rr*rr) + m_fDistortionK2*(rr*rr*rr*rr));
	theta = atan2(fU-0.5f, fV-0.5f);
	hX = sin(theta)*r2*m_fZoomWidth;
	hY = cos(theta)*r2*m_fZoomHeight;
	
	coordinates.rfBlue[0] = hX + 0.5f;
	coordinates.rfBlue[1] = hY + 0.5f;
	coordinates.rfGreen[0] = hX + 0.5f;
	coordinates.rfGreen[1] = hY + 0.5f;
	coordinates.rfRed[0] = hX + 0.5f;

```
it work,but not good enough, I do not know my K1 K2 have problems, or the algorithm is a problem.
Can you tell me how to get the parameters(k1,k2)?

**Comment by zezba9000** [comment]
This is how you calculate the browns distortion.

Create some object like "distortionGenerator" to hold your distortion values.

```
DistortionCoordinates_t BrownsDistortionUV(EVREye eEye, float fU, float fV, DistortionGenerator* distortionGenerator, bool flip)
{
	bool isLeft = eEye == EVREye::Eye_Left;
	int eyeIndex = isLeft ? 0 : 1;

	auto distortion = distortionGenerator->state.distortion;

	auto distortionOffset = distortionGenerator->state.distortionOffset;
	float distortionScale = distortionGenerator->state.distortionScale;
	float distortionAspect = distortionGenerator->state.distortionAspect;
	if (isLeft) distortionOffset.x = -distortionOffset.x;
	if (!flip) distortionOffset.x = -distortionOffset.x;

	float aberationR = distortionGenerator->state.aberationR;
	float aberationG = distortionGenerator->state.aberationG;
	float aberationB = distortionGenerator->state.aberationB;

	// add vertex
	auto pos = Vector2(fU - .5f, fV - .5f) * 2.0f * distortionScale;
	pos.x *= distortionAspect;

	// add uvs
	Vector2 center = isLeft ? Vector2(distortion.z, distortion.w) : Vector2(-distortion.z, distortion.w);
	Vector2 dir = pos - (center + distortionOffset);
	float dirDot = dir.Dot(dir);
	float poly = 1.0f + (distortion.x + distortion.y * dirDot) * dirDot;

	Vector2 uvR = (dir * poly * aberationR) + center;
	Vector2 uvG = (dir * poly * aberationG) + center;
	Vector2 uvB = (dir * poly * aberationB) + center;

	constexpr float mul = .5f;
	uvR.x *= mul;
	uvR.y *= mul;
	uvG.x *= mul;
	uvG.y *= mul;
	uvB.x *= mul;
	uvB.y *= mul;

	constexpr float offset = .5f;
	uvR.x += offset;
	uvR.y += offset;
	uvG.x += offset;
	uvG.y += offset;
	uvB.x += offset;
	uvB.y += offset;


	// Flip if HMD screen is upside down
	if (flip)
	{
		uvR.x = 1.0f - uvR.x;
		uvR.y = 1.0f - uvR.y;

		uvG.x = 1.0f - uvG.x;
		uvG.y = 1.0f - uvG.y;

		uvB.x = 1.0f - uvB.x;
		uvB.y = 1.0f - uvB.y;
	}

	// finish
	DistortionCoordinates_t cord;
	cord.rfRed[0] = uvR.x;
	cord.rfRed[1] = uvR.y;

	cord.rfGreen[0] = uvG.x;
	cord.rfGreen[1] = uvG.y;

	cord.rfBlue[0] = uvB.x;
	cord.rfBlue[1] = uvB.y;
	return cord;
}
```

**Comment by zezba9000** [comment]
Another side note. Your horizontal FOV may feel better if its wider than the vertical. Take note of this when creating your project matrix.

**Comment by zezba9000** [comment]
Here are some helper identity states.

defaultState.distortion = Vector4(0.5f, 0.5f, 0, 0);
defaultState.distortionOffset = Vector2(0.0f, 0.0f);
defaultState.distortionScale = 1.0f;
defaultState.distortionAspect = 1.0f;
defaultState.aberationR = 1.0f;
defaultState.aberationG = 1.0f;
defaultState.aberationB = 1.0f;
