### ISSUE TITLE
Anyone managed to get non-blank texture out of IVRVirtualDisplay yet?

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#503]
Using the code below, everything succeeds, all I get back is a blank (all zeros) texture. With no documents or samples, it's anyone's guess what is supposed to be done here (or whether this new interface even works). 

	ID3D11Texture2D *texture;
	m_pDevice->OpenSharedResource((HANDLE)backbufferTextureHandle, __uuidof(ID3D11Texture2D), (void**)&texture);
	if (texture != NULL)
	{
		// Create staging texture
		ID3D11Texture2D *stagingTexture;
		D3D11_TEXTURE2D_DESC tex_desc;
		texture->GetDesc(&tex_desc);
		tex_desc.MipLevels = 1;
		tex_desc.ArraySize = 1;
		tex_desc.SampleDesc.Count = 1;
		tex_desc.SampleDesc.Quality = 0;
		tex_desc.Usage = D3D11_USAGE_STAGING;
		tex_desc.BindFlags = 0;
		tex_desc.CPUAccessFlags = D3D11_CPU_ACCESS_READ;
		tex_desc.MiscFlags = 0;

		HRESULT hr = m_pDevice->CreateTexture2D(&tex_desc, NULL, &stagingTexture);
		if (SUCCEEDED(hr))
		{
			// Copy frame texture to staging
			m_pContext->CopyResource(stagingTexture, texture);

			// Map staging texture to memory bitmap
			D3D11_MAPPED_SUBRESOURCE map;
			hr = m_pContext->Map(stagingTexture, 0, D3D11_MAP_READ, 0, &map);
			if (SUCCEEDED(hr))
			{
				// Do something with texture data

				// Unmap texture from memory
				m_pContext->Unmap(texture, 0);
			}

			// Release staging texture
			stagingTexture->Release();
		}

		// Release shared resource
		texture->Release();
	}

**Comment by sencercoltu** [comment]
I'm feeding the textures received from IVRVirtualDisplay::Present to H.264
HW encoder.
I can confirm that the it works with SteamVR-beta.

**Comment by TheDeveloperGuy** [comment]
Well I must be doing something wrong then, as the code above doesn't work for Beta SteamVR either. Guess I'll keep on guessing... :/

**Comment by sencercoltu** [comment]
@TheDeveloperGuy 
I did a quick test. Without using keyedmutex I also got black only texture.
Try copy the resource after aquiring the mutex:

IDXGIKeyedMutex *pMutex;
if (SUCCEEDED(texture->QueryInterface(__uuidof(IDXGIKeyedMutex), (void **)&pMutex)))
{
	if (SUCCEEDED(pMutex->AcquireSync(0, 4563554)))
	{
		D3DX11SaveTextureToFile(m_pContext, texture, D3DX11_IFF_JPG, L"D:\\OUT\\IMG\\texture.jpg");
		pMutex->ReleaseSync(0);
	}
	pMutex->Release();
}

**Comment by TheDeveloperGuy** [comment]
Thanks! Using the mutex is the key

**Comment by TheDeveloperGuy** [comment]
@sencercoltu I'd change that timeout to about 10ms (what is 4563554?). If you don't get the mutex in that time you can abandon the wait, as the frame will be too late.

**Comment by sencercoltu** [comment]
That was a one time running code to get save the texture, which was deleted after I've seen that the mutex should be used to be able to read the texture. I just entered a random timeout value since it won't matter. 
A timeout value of 10 is also what i use in my original code 👍
