### ISSUE TITLE
So which is better, IVRDriverDirectModeComponent or IVRVirtualDisplay?

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#507]
I have implemented both in my driver, and it's possible to switch between the two by changing a setting value for my driver, and restarting SteamVR. 

Assuming optimal (I don't see much room left in my driver for performance improvements) implementations of both, is any preferable over the other? My observations so far:

1) Performance appears to be equal - I get 90FPS on both 
2) Latency appears to be equal - I don't notice any difference in latency between the two
3) Bogus warnings/errors - "virtual" doesn't show 'extended mode' warning, "direct" does. Both show bogus 'DXGI thread failed to get SDL display index' error in logs.
4) Vignetting options - "virtual" has none, "direct" has whatever you provide as you will do lens distortion in your driver.
5) Code-sharing - about 80-90% of code is shared between the modes, with "direct" having more code/complexity due to needing to implement texture management and image composition.

Obviously, if you're starting a driver from scratch and don't need the extra flexibility offered by "direct", then it is much simpler to implement "virtual".

So far (4) is a decider for me to continue to use "direct", as my driver has options to render "image circle" (round) vignettes and to 'fuzz' the edges of either "warped rectangle" or "image circle" vignettes. This is an important psychological advantage, as hard edges on the display are distracting (even if in periphery vision), whereas soft edges are not noticeable even if well inside the eye's normal field of view.  Hopefully a future version of OpenVR will allow soft edged vignettes for IVRVirtualDisplay.

**Comment by TheDeveloperGuy** [comment]
On further testing it appears that the "virtual" interface is quite a bit more performant than the "direct" one! When running apps that can't maintain 90Hz, the "virtual" interface can generate up to 30% more FPS than the "direct" one. So apart from not having finer control over what the distorted output looks like, it seems like a win for the "virtual" interface.

I'll leave this open for a bit if anyone else wants to add their observations.

**Comment by TheDeveloperGuy** [comment]
It's possible (with negligible performance impact) to do a shader pass on the texture provided to Present() in "virtual" mode to apply vignetting (I used a modified version of my distortion shader). With this the "virtual" interface wins on all counts! :)

**Comment by godbyk** [comment]
@TheDeveloperGuy Thanks for the detailed comparison! I was wondering about this myself but hadn't had a chance to do the legwork yet.

**Comment by LoSealL** [comment]
`IVRVirtualDisplay` doesn't contain head positions of the rendered texture, that's the most important reason to abandon using it in wireless solution.
Unless you don't care the latency and dizzy.

**Comment by TheDeveloperGuy** [comment]
@LoSealL I'm curious, how do you use the pose data supplied with the eye textures in the "direct" interface? Are you doing a "space" warp in your driver?

**Comment by LoSealL** [comment]
Yep.

**Comment by shensheng27** [comment]
@LoSealL Do you mean that texture from IVRVirtualDisplay don't be "space" warpped by openVR?

**Comment by LoSealL** [comment]
@shensheng27 No, but you need to warp in remote display by yourself.

**Comment by shensheng27** [comment]
implement IVRVirtualDisplay result in the blur when moving hmd (compare to direct mode controlled by openVR)
so the conclusion is texture from IVRVirtualDisplay don't be "space" warpped by openVR?

**Comment by HelenXR** [comment]
@TheDeveloperGuy 
Thank you for sharing the results of these two interfaces.
Did not achieve any of these two interfaces, only by modifying EDID and whitelist so that the custom HMD into the direct rendering mode, this situation with the above two are different?

**Comment by TheDeveloperGuy** [comment]
@HelenXR I don't understand your question. However you are using the IVRDisplayComponent so any discussion of the other HMD interfaces does not apply to your driver.

**Comment by TheDeveloperGuy** [comment]
BTW, this situation has now reversed. The "direct" driver interface appears to provide better performance on latest versions of SteamVR. In addition, there is a "black screen" feature/bug that manifests on the IVRVirtualDisplay interface, so I am defaulting to IVRDriverDirectModeComponent in my driver, as at present it provides both better performance and compatibility.

https://github.com/ValveSoftware/openvr/issues/598

**Comment by HelenXR** [comment]
@TheDeveloperGuy 
1. I did not implement the IVRDriverDirectModeComponent and IVRVirtualDisplay interface (my HMD class only inherited the ITrackedDeviceServerDriver and IVRDisplayComponent), the driver only modified the Prop_EdidVendorID_Int32 and Prop_EdidProductID_Int32 attributes, and the registry of the white list information, HMD can normally enter the direct rendering mode. What is the difference between IVRDisplayComponent and IVRDriverDirectModeComponent   ?
2. as you say in #598 ,IVRDriverDirectModeComponent  is better than IVRVirtualDisplay ,How to implement this interface(I can not find this information in openvr).
thanks.

**Comment by Balderick** [comment]
> So which is better, IVRDriverDirectModeComponent or IVRVirtualDisplay?

Surely these are two different functions for different scenarios!?

What has there not been any input in this thread from Valve developers?   Maybe, because they gave the answer in other threads!?

Masterofshapes indicated nearly a year ago they were waiting on Valve devs making changes to openvr api regarding their steamvr tracked daydream device projects,  are we all still waiting on those changes?   I think they are related to what is being discussed here.

**Comment by JoeLudwig** [comment]
Best is to use neither one and let the compositor own the display. That will be the most efficient and highest quality.

Second best depends on what your situation is. 

Virtual display is after distortion and compositing. If you can provide your distortion data but not the output for some reason, this is probably the way to go. An example of this would be a display that's over some wireless link that isn't physically connected to the box.

Driver direct mode happens before compositing. If your distortion data is impossible to provide you might need to do this. If you're also doing compositing in your own system, you might be better off using driver direct mode because you can read from multiple layers in one pass. So depending on the specifics of your own compositor you might be better off using driver direct mode.

**Comment by TheDeveloperGuy** [comment]
@HelenXR Simple rule: if you don't *have* to use one of these interfaces, then you don't need to use one of these interfaces. 😉

**Comment by HelenXR** [comment]
ok,thanks.

**Comment by cyrilmyself** [comment]
@TheDeveloperGuy ，
do you have any ideas about implementing the IVRDriverDirectModeComponent interface.
I want to implement pre-distortion,Timewrap and directMode on my own,do you have any ideas?

**Comment by xjqxzh1** [comment]
@LoSealL Your answer is very helpful to me. I have a preliminary understanding of IVRDriverDirectModeComponent. But I still have some confusion. I want to know how to get the relevant documents?

**Comment by LoSealL** [comment]
@xjqxzh1 By reverse engineer...

**Comment by TheDeveloperGuy** [comment]
I'm closing this, it can be summarised as follows:

1) Don't use "virtual" or "direct" modes unless you have to (HMD not connected via HDMI/DP).
2) Use "direct" mode if you have a headset that can do it's own distortion/ATW.
3) Use "virtual" mode for simplicity. Generally, you don't want to be using this as you will have latency issues that you can't correct. It is useful for experimental HMD drivers where you need to manipulate the final output in some way before displaying it.
