### ISSUE TITLE
Direct3d 9 support not working

### ISSUE THREAD

**Issue by joel-juvel-sb** [ValveSoftware/openvr#52]
Direct 3d 9 support doesn't seem to work. There are a few issue. 
Regular **D3D9** fails on CreateDevice with **D3DERR_LOSTDEVICE** when using the HMD. On the other hand the device can be created when using the Null Driver. 
If I use **D3D9Ex** instead, the CreateDevice call will succeed with both HMD & Null Driver.

In **D3D9 mode** the compositor **submit** will fail with the **VRCompositorError_TextureUsesUnsupportedFormat** error code. In **D3D9Ex mode** it will fail with the **VRCompositorError_InvalidTexture** error code.

**Comment by JoeLudwig** [comment]
At the moment OpenVR supports DX10 and DX11, but not DX9. We have no timeline for when that might change.

**Comment by seanlis** [comment]
Is DX9 still not supported?

**Comment by Noah670** [comment]
No DX9 is not being supported.

**Comment by seanlis** [comment]
OK. Thanks
