### ISSUE TITLE
TriggerHapticPulse never called?

### ISSUE THREAD

**Issue by zezba9000** [ValveSoftware/openvr#524]
Have a Unity app invoking "controller.TriggerHapticPulse();".
However in the custom OpenVR driver I have, the "TriggerHapticPulse" method is never called.

Is there some other event I bind to to check for this?

**Comment by HelenXR** [comment]
TriggerHapticPulse method is in IVRControllerComponent.
Typically, this interface is not integrated by HMD.

**Comment by zezba9000** [comment]
I'm not sure what you mean? Its not being integrated by the HMD, its being integrated with the OpenVR controller interface.

**Comment by HelenXR** [comment]
if conttroller had integrated this interface,and you use  the ID('unControllerDeviceIndex' param) which corresponds to controller,I'm sure it will work.

**Comment by zezba9000** [comment]
Maybe I made a mistake will check tomorrow.

**Comment by zezba9000** [comment]
You're right, it works. Not sure what was wrong before.
