### ISSUE TITLE
Getting the POSE information for every frame in case of virtual display

### ISSUE THREAD

**Issue by rmallela0426** [ValveSoftware/openvr#525]
Hi,
I'm writing a openvr driver which uses the IVRVirtualDisplay concept, and was successful in dumping the frames that are received from IVRVirtualDisplay::present() function call.  My requirement is to send the frame data along with the pose (that is used for generating that frame by the application) information to HMD. 
In  case of direct mode, submit() method will have the Pose information which is sent as an argument to the function. Similarly is there any way for getting the Pose information for every frame in case of virtual display? 
Also, is there a way that we can tell the SteamVR to not process the distortion?

**Comment by JoeLudwig** [comment]
The whole point of IVRVirtualDisplay is that SteamVR does the compositing and hands off the final texture.

If you want to do distortion processing inside your driver you will need to use IVRDriverDirectModeComponent. That interface already provides the pose.

**Comment by TheDeveloperGuy** [comment]
> is there a way that we can tell the SteamVR to not process the distortion?

As you need to provide the distortion function in your driver, all you need to do to not distort is do a pass-through in ComputeDistortion().

**Comment by HelenXR** [comment]
@rmallela0426 
as TheDeveloperGuy say, you can add your distort algorithm in ComputeDistortion interface,a example code is below:
```
DistortionCoordinates_t CHeadMountDisplayDevice::ComputeDistortion( EVREye eEye, float fU, float fV ) 
{
	DistortionCoordinates_t coordinates;
	//add distortion for lens
	float hX;
	float hY;
	double rr;
	double r2;
	double theta;	

	//The formula is derived from this video:https://www.youtube.com/watch?v=B7qrgrrHry0&feature=youtu.be
    //and Distortion correction algorithm for Wikipedia:https://en.wikipedia.org/wiki/Distortion_(optics)#Software_correction
	rr = sqrt((fU - 0.5f)*(fU - 0.5f) + (fV - 0.5f)*(fV - 0.5f));
	r2 = rr * (1 + m_fDistortionK1*(rr*rr) + m_fDistortionK2*(rr*rr*rr*rr));
	theta = atan2(fU-0.5f, fV-0.5f);
	hX = sin(theta)*r2*m_fZoomWidth;
	hY = cos(theta)*r2*m_fZoomHeight;
	
	coordinates.rfBlue[0] = hX + 0.5f;
	coordinates.rfBlue[1] = hY + 0.5f;
	coordinates.rfGreen[0] = hX + 0.5f;
	coordinates.rfGreen[1] = hY + 0.5f;
	coordinates.rfRed[0] = hX + 0.5f;
	coordinates.rfRed[1] = hY + 0.5f;

	return coordinates;
}
```
you can test it in [openvr_survivor](https://github.com/HelenXR/openvr_survivor),
or in [sharderToy](https://www.shadertoy.com/view/4sXcDN).
