### ISSUE TITLE
[Qeustion]What should I do if I want to access raw image before distortion?

### ISSUE THREAD

**Issue by cjlong1213** [ValveSoftware/openvr#526]
Does GetOverlayTexture() work? I have an idea to transform the raw image of Steam APP to HMD by wireless, then the distrotion is done by HMD, Is there any way or OpenVR interface function can achieve this?
Thanks!

**Comment by TheDeveloperGuy** [comment]
If you want to do your own distortion you will need to use the IVRDriverDirectModeComponent interface. You'll need to dig through here to find the link to an Open Source driver using this interface. It is non-trivial to implement.

**Comment by cjlong1213** [comment]
@TheDeveloperGuy Thanks for your quickly reply.
I think this is what I want. I have checked the header file in the latest version 1.0.7 then found some functions defined in class IVRDriverDirectModeComponent. there are some questions here:
Does the "Texture" mentioned here related to ID3D11 Resource? Can we access the raw texture by the function GetNexSwapTextureSetIndex()? Is there any sample code for this?
I am evaluating the feasibility of  getting raw texture from SteamVR APP then do my own compositer work in HMD side.
Thanks!

**Comment by xjqxzh1** [comment]
I'm doing the same thing. Have you found a way, please?
