### ISSUE TITLE
Open Source the Null Driver

### ISSUE THREAD

**Issue by KnightHawk3** [ValveSoftware/openvr#53]
Could you please allow us to see the source for the null driver? It would save people beginning to write their own drivers some work and shouldn't contain anything secret.

I am currently trying to write my own and almost done, so it would be nice if I could get my hands on the null driver shipped with this.

**Comment by toxicFork** [comment]
+1

**Comment by JoeLudwig** [comment]
The next SDK update will include a sample driver. That sample is basically the null driver with "null" replaced with "sample".

**Comment by KnightHawk3** [comment]
Any chance of an ETA?

Can't wait.

**Comment by JoeLudwig** [comment]
How about today? 0.9.16 includes the sample driver.

**Comment by KnightHawk3** [comment]
Thank you :)
