### ISSUE TITLE
Portable (vive vs oculus) getter for UI selection ray?

### ISSUE THREAD

**Issue by mlfarrell** [ValveSoftware/openvr#531]
Is there an API for this?  I had a hard coded "forward" ray for vive which is wrong for oculus.

**Comment by aleiby** [comment]
For headsets or motion controllers?

Headset pose should be the midpoint between eyes and I would expect that to be portable (though discouraged for UX).

Controllers have components which we try to maintain between devices.
https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L3143

You can see an example usage of this in the Unity plugin here:
https://github.com/ValveSoftware/steamvr_unity_plugin/blob/master/Assets/SteamVR/Scripts/SteamVR_RenderModel.cs#L720

Example 'tip' attach point across three different controllers which could be used for ray casting.

![tip_attach_knuckles](https://user-images.githubusercontent.com/3761351/27711723-df6bfed8-5cd8-11e7-8444-879ba69b3ac7.PNG)
![tip_attach_touch](https://user-images.githubusercontent.com/3761351/27711722-df6b6360-5cd8-11e7-941c-5f66ca30e48c.PNG)
![tip_attach_vive](https://user-images.githubusercontent.com/3761351/27711724-df7d877a-5cd8-11e7-8a5e-766cdb5ce295.PNG)
