### ISSUE TITLE
Does the Oculus touch controllers work well with the SDK?

### ISSUE THREAD

**Issue by BlakeR07** [ValveSoftware/openvr#532]
I am currently about to write my VR game engine. I am trying to decide if I should use the Oculus SDK or the OpenVR SDK. I have looked everywhere and can't find how well the Oculus Touch contollers work with the OpenVR SDK.

**Comment by natbro** [comment]
Oculus touch controllers work very well with the OpenVR SDK - they are exposed as right and left controllers with some specific button and axis mappings. See openvr.h as well as https://steamcommunity.com/app/250820/discussions/0/152390648088797512/.
