### ISSUE TITLE
Prop_RenderModelName_String doesn't load models stored in custom driver "resources\rendermodels" folder

### ISSUE THREAD

**Issue by zezba9000** [ValveSoftware/openvr#534]
When this method is invoked in the 'IVRControllerComponent' with the model stored in the custom drivers "resources\rendermodels" folder, it fails to load. However, if I put the model in "C:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources" it does work.
```
VRProperties()->SetStringProperty(propertyContainer, Prop_RenderModelName_String, "light_gun");
```

Are render models required to be installed into the main steam install folder?

**Comment by JoeLudwig** [comment]
You'll need to be explicit about where the system is to find your render model. Instead of setting "light_gun", set "{mydriver}light_gun" (where mydriver is the name of your driver.)  That will cause it to search in the driver's resources/rendermodels directory instead of the global system one.

**Comment by zezba9000** [comment]
Aww of course. Forgot about that, tnx.

**Comment by zezba9000** [comment]
This doesn't work.
```
VRProperties()->SetStringProperty(propertyContainer, Prop_RenderModelName_String, "{vrstudios}light_gun");
```

This does work in the HMD but it has a "Prop_IconPathName_String" that doesn't exist for the Controllers respectively.
```
VRProperties()->SetStringProperty(propertyContainer, Prop_IconPathName_String, "icons");
VRProperties()->SetStringProperty(propertyContainer, Prop_NamedIconPathDeviceOff_String, "{vrstudios}headset_sample_status_off.png");
```

**Comment by zezba9000** [comment]
k cool works. My bad

**Comment by HelenXR** [comment]
@zezba9000 
I was using HTC VIVE rendering model, I would like to replace their own rendering model, what tools can be produced, if convenient, then help guide the production process.

**Comment by zezba9000** [comment]
@HelenXR Are you asking for more details on how to use your own "rendering models" for a custom OpenVR driver? If so I can try to get you more info later today.

**Comment by HelenXR** [comment]
@zezba9000  yes, i want to create one "rendering models" like vr_controller_vive_1_5(hydra_controller is a little simple). thanks.

**Comment by zezba9000** [comment]
You need to set the model name like so:

> VRProperties()->SetStringProperty(propertyContainer, Prop_RenderModelName_String, "{company_name}gun");

company_name is stored in your "driver.vrdrivermanifest" file under {"name" : "company_name"}

RenderModels need to be stored in your OpenVR driver folder. Example: "myDriverFolder\resources\rendermodels\gun"

NOTE: "myDriverFolder" should have the "driver.vrdrivermanifest" file in it.

Inside the "gun" folder you need a file called "gun.json". It should look something like this inside.

> {
>     "thumbnail" : "touch_controller_thumbnail.png",
>     "components": {
> 					"body": {
> 						"filename": "gun.obj",
> 						"component_local": {
> 							"origin": [ 0.0, 0.0, 0.0 ],
> 							"rotate_xyz": [ 0.0, 0.0, 0.0 ]
> 						}
> 					}
>     }
> }

For more reference look at: "..\Steam\steamapps\common\SteamVR\resources\rendermodels\oculus_cv1_controller_left"

**Comment by HelenXR** [comment]
@zezba9000 Thank you for your reply,but maybe I did not describe it clearly,What I need is how to generate mtl, obj,tga.

**Comment by jgwinner** [comment]
Normally you export those from your CAD modeling package - most systems (almost everything) has a .OBJ exporter.

**Comment by zezba9000** [comment]
@HelenXR Take a look at Blender: https://www.blender.org/

obj, mtl and tga are all standard formats.
Take a look at "..\Steam\steamapps\common\SteamVR\resources\rendermodels\oculus_cv1_controller_left" OBJ files in Blender or some other 3D app for more info on how the files should be set up.

**Comment by HelenXR** [comment]
@zezba9000  ok , I wiil use the blender tool to generate these files. thanks.

**Comment by HelenXR** [comment]
@zezba9000 I try to use [my rendermodel](https://github.com/HelenXR/Documents/blob/master/openvr_issue/1.rar)whick generate by maya2015 ,but  fail,the rendermodel is not display like below
![controller not display](https://github.com/HelenXR/Documents/blob/master/openvr_issue/controller_missing.png)
I think the configuration is no problem, because I can normally use "hydra_controller" and "vr_controller_vive_1_5".
Looking forward to your reply.

**Comment by zezba9000** [comment]
@HelenXR For testing, first use a model you know works. Such as the Oculus one I suggested. After you get one of the existing built in Models working from StreamVR, than move onto getting your own to work.

**Comment by HelenXR** [comment]
@zezba9000 I move oculus_cv1_controller_left to {mydriver}\resources\rendermodels folder,then set "Prop_RenderModelName_String" to "{mydriver}oculus_cv1_controller_left".start steamVR ,I can see the oculus model.
Before that I tested the hydra_controller and vr_controller_vive_1_5 in the same way.
Can you test [my model](https://github.com/HelenXR/Documents/blob/master/openvr_issue/1.rar) for me?

**Comment by zezba9000** [comment]
Because your model is to large. Its about 100x to large. Here is an example: https://ufile.io/puieo

**Comment by HelenXR** [comment]
@zezba9000 Thank you for your patience,but after I reduced the model by 250 times, I still couldn't load it.
[new model](https://github.com/HelenXR/Documents/blob/master/openvr_issue/2.rar),[same size as the oculus model](https://github.com/HelenXR/Documents/blob/master/openvr_issue/2.png)

**Comment by zezba9000** [comment]
I don't see any "2.json" file? Does that file have ("filename": "2.obj") in it?

Also in your "1.json" file this line seems wrong: ("1" : "1.jpg")

**Comment by HelenXR** [comment]
@zezba9000 
Because I didn't include the JSON file when I was using hydra_controller, so I didn't add it either.
Now, I followed your say and reworked a [cube model](https://github.com/HelenXR/Documents/blob/master/openvr_issue/Cube.rar) ,then added the JSON file. I saw the following log in the file "vrclient_vrcompositor.txt":
```
...
Wed Oct 11 2017 10:25:31.703 - RendermodelManager: Reading data from D:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources\rendermodels\Cube\Cube.json
Wed Oct 11 2017 10:25:31.703 - RendermodelManager: name=body inputRouting=0 filename=Cube.obj
Wed Oct 11 2017 10:25:31.705 - Collision Bounds distances: flMinAxis=1.000000, Hmd=0.350000->0.700000, Controllers=0.262500->0.525000
Wed Oct 11 2017 10:25:31.706 - Render model D:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources\rendermodels\Cube\Cube.obj has 0 texture coordinates, expected 48
...
```
"Cube.obj has 0 texture coordinates, expected 48",here seems to be the problem of making my model in blender, I haven't used this software before, can you help me point it out?

**Comment by zezba9000** [comment]
I see, yes I forgot your model must have a texture.
The .mtl file should look something like this:

> illum 4
> Kd 0.00 0.00 0.00
> Ka 0.00 0.00 0.00
> Tf 1.00 1.00 1.00
> map_Kd DesignWand.png
> Ni 1.00
> Ks 0.40 0.40 0.40

Here is a step by step example: https://1drv.ms/u/s!Alt5wRhQYKD7gdUaDzdufkRWNhgTKA

**Comment by HelenXR** [comment]
@zezba9000 
According to the way you said my rendering model normal display，thanks 。
