### ISSUE TITLE
Cannot close dashboard overlay from within the dashboard.

### ISSUE THREAD

**Issue by Hoodad** [ValveSoftware/openvr#536]
I'm lacking the API calls to close the dashboard overlay. I might be missing something but as far as I can tell there is only one way to close a dashboard overlay and that is from the input from the user.

It would be of great use to have the option to close your own dashboard overlay through code.

**Comment by kisak-valve** [comment]
Hello @Hoodad, this is already being discussed at #321.

**Comment by Hoodad** [comment]
Alright sorry, closing this issue.
