### ISSUE TITLE
Cmake Error: Unknown CMake command "setTargetOutputDirectory".

### ISSUE THREAD

**Issue by alex9099** [ValveSoftware/openvr#537]
Hi, i'm trying to follow the example to create a driver for openvr but i'm gettint this error(s)

```
$ cmake .. -G "Unix Makefiles" -DCMAKE_PREFIX_PATH=/opt/Qt/5.6/gcc_64/lib/cmake -DCMAKE_BUILD_TYPE=Release

CMake Error at CMakeLists.txt:16 (setTargetOutputDirectory):
  Unknown CMake command "setTargetOutputDirectory".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.8)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/alexandre/Documents/steamvr/openvr/samples/CMakeFiles/CMakeOutput.log".
```

**Comment by natbro** [comment]
you'll get this error if you just try to cmake a sub-project below /samples, I assume you're in /samples/driver_sample within a <build> subdirectory there? setTargetOutputDirectory is a function defined in /samples/CMakeLists.txt
make your <build> subdirectory right under /samples and cmake from that. pass -Wno-dev to avoid the irrelevant cmake warnings.

**Comment by elect86** [comment]
Hi, I'm getting the same error for the `helloWorldOverlay` sample.

Obviously I tried to run in from within `openvr\samples\helloworldoverlay`..

So I tried to launch it directly from `/samples`, but I get the same error

```
`PS D:\Visual Studio 2017\Projects\openvr\samples> cmake -G "Visual Studio 15 2017 Win64" .\helloworldoverlay
CMake Error at CMakeLists.txt:38 (setTargetOutputDirectory):
  Unknown CMake command "setTargetOutputDirectory".
```

I have no idea how I should 

> make my subdirectory right under /samples and cmake from that.

**Comment by elect86** [comment]
Ok, it worked, compiled, but when I run:

msvcp120d.dll is missing

**Comment by bipul-mohanto** [comment]
> Hi, I'm getting the same error for the `helloWorldOverlay` sample.
> 
> Obviously I tried to run in from within `openvr\samples\helloworldoverlay`..
> 
> So I tried to launch it directly from `/samples`, but I get the same error
> 
> ```
> `PS D:\Visual Studio 2017\Projects\openvr\samples> cmake -G "Visual Studio 15 2017 Win64" .\helloworldoverlay
> CMake Error at CMakeLists.txt:38 (setTargetOutputDirectory):
>   Unknown CMake command "setTargetOutputDirectory".
> ```
> 
> If I simply run `PS D:\Visual Studio 2017\Projects\openvr\samples> cmake -G "Visual Studio 15 2017 Win64"` then it simply generates the hello opengl sample..
> 
> I have no idea how I should
> 
> > make my subdirectory right under /samples and cmake from that.
> 
> Edit: I tried:
> 
> ```
> PS D:\Visual Studio 2017\Projects\openvr\samples\helloworldoverlay> cmake ../ -G "Visual Studio 15 2017 Win64"
> -- Compilation set for 64bits architectures.
> CMake Warning at CMakeLists.txt:41 (message):
>   SDL x64 runtime binaries not provided on Windows.
> 
> 
> CMake Error at CMakeLists.txt:194 (find_package):
>   By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "Qt5", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5" with any of
>   the following names:
> 
>     Qt5Config.cmake
>     qt5-config.cmake
> 
>   Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
>   to a directory containing one of the above files.  If "Qt5" provides a
>   separate development package or SDK, be sure it has been installed.
> ```
> 
> Seems it worked? I need qt5?
> 
> Edit: sorry, I completely missed to read the `README` under `/samples`...

I have exact the same error while building the samples. How did you solve this? I have installed Qt6.2.3 (x64), and add new line in the samples's CMakeLists.txt `set(module ${module} "C:/Qt/Tools/QtDesignStudio/qt5_design_studio_reduced_version/lib/cmake/Qt5/Qt5Config.cmake")`, but not working.
