### ISSUE TITLE
hellovr_opengl needs updating for 0.9.16

### ISSUE THREAD

**Issue by ChristophHaag** [ValveSoftware/openvr#54]
In c174bafe1e3d150ff44d23209f89e312bda93189: LoadRenderModel has become LoadRenderModel_Async

Yet there is https://github.com/ValveSoftware/openvr/blob/c95571027b79644643bca044538144c96194c4f2/samples/hellovr_opengl/hellovr_opengl_main.cpp#L1671

**Comment by osbike** [comment]
Thanks.
And LoadTexture need to be modified to LoadTexture_Async.
It works.

**Comment by ChristophHaag** [comment]
https://github.com/ValveSoftware/openvr/pull/55

**Comment by assumptionsoup** [comment]
Thanks @ChristophHaag I ran into the same problem and couldn't compile the sample without this fix.

**Comment by elect86** [comment]
Actually it'd need to be updated to 0.9.20 now...

I am pretty sure someone already did it, may willing to share it?

**Comment by elect86** [comment]
Also, for the distortion the shader expects a `vec4 position` but you set up a vec2

`glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, sizeof(VertexDataLens), (void *)offsetof( VertexDataLens, position ) );`

The driver comes in help, but better to avoid

**Comment by ChristophHaag** [comment]
Better make this a separate bug report, doesn't look like Valve is watching this one.

**Comment by JoeLudwig** [comment]
The LoadTexture/LoadModel problem will be fixed in the next SDK update.

Please add the distortion problem in its own bug. The correct fix there is probably to just remove the distortion from the sample. It relies on the compositor to do the distortion that the user sees in any case.

**Comment by elect86** [comment]
Also, I'd move `UpdateHMDMatrixPose()` at the begin of `void CMainApplication::RenderFrame()`, otherwise the first frame the hmd matrix is uninitialized..
