### ISSUE TITLE
How to make HMD drivers for OSX SteamVR?

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#541]
Due to lack of Direct3D on OSX, it's safe to assume that the Windows SteamVR driver architecture can't be used for OSX. Is there (or will there ever be) a way for developers to make OpenVR HMD drivers for OSX?

**Comment by natbro** [comment]
There should be nothing limiting writing OSX drivers for input devices or HMDs - the entire OpenVR driver architecture runs the same way on OSX, it's how we write our lighthouse, Vive, and other drivers. If there is anything Windows-specific or incomprehensible in the HMD driver interface that is blocking you, let me know, we can iron it out. It is definitely our goal to support HMD experimentation on all platforms, to make sure that new devices can test out and compare themselves to existing OpenVR content so the whole ecosystem can improve.

**Comment by TheDeveloperGuy** [comment]
I expect you are referring to IVRDisplayComponent based drivers and not IVRVirtualDisplay or IVRDriverDirectModeComponent based drivers, as these drivers are ridiculously undocumented, with no sample code, and are based heavily on a Direct X 11 subsystem. Is it safe to assume that these driver types are currently unsupported on OSX and are likely to remain so for the forseeable future, or is there someone at Valve who can take a little time to explain how these driver types are supposed to work in general (I for one can certainly not be bothered to slave again through weeks/months of guessing and reverse-engineering to make a driver for a marginal at best platform), and on OSX in particular?
