### ISSUE TITLE
Null Driver to OpenSource

### ISSUE THREAD

**Issue by r57zone** [ValveSoftware/openvr#546]
Please add the source code driver "driver_null" to GitHub.

**Comment by JoeLudwig** [comment]
See https://github.com/ValveSoftware/openvr/tree/master/samples/driver_sample

The sample driver is the same as the null driver, just cleaned up to be compiled outside of the main SteamVR codebase.

**Comment by r57zone** [comment]
To make the Sample driver work as a Null driver, you need to add:

> vr::VRProperties()->SetBoolProperty(m_ulPropertyContainer, Prop_DisplayDebugMode_Bool, true);

Debug mode activate Windowed Mode (borderless fullscreen) on "Headset Window" and you can move window to second screen with buttons (Shift + Win + Right or Left).
