### ISSUE TITLE
Driver fails to work in new runtime

### ISSUE THREAD

**Issue by dashingstag** [ValveSoftware/openvr#547]
I have a custom driver that works with the previous runtime but fails with the latest steamvr runtime.

Error I received is :
"SteamVR failed to initialized for unknown reasons (Error: Shared IPC Compositor Invalid Connect Response (307))"

My openvr version 1.0.7 

Anyone experiencing the same issue?

**Comment by Balderick** [comment]
The steamvr troubleshooting and bug report forums are being flooded with such reports from software devs and hardware devs as well as steam users.

Looks like  Valve might have to roll back steamvr home back to beta

Am seeeing apps, plugins and drivers being broken because of latest update to default steam client.

OSVR-Vive is broken too.

**Comment by JoeLudwig** [comment]
@dashingstag Please use the "report a bug" feature in SteamVR to send us a system report. 

@Balderick OSVR-Vive loads driver_lighthouse directly, which is not supported. It's bound to break from time to time. If you're running into any problems with other applications, please let us know.

**Comment by Balderick** [comment]
@JoeLudwig    my issues are related to setting up a multi vendor vr setup which there an open issue at https://github.com/ValveSoftware/openvr/issues/535

I'll try updating op there to try and describe why I was trying to use osvr-vive.  Am looking for any alternatives or advice on what I could be trying to do.

**Comment by dashingstag** [comment]
Ah I found out the issue. It was a silly thing on my part. The new SteamVR update had wiped my old driver settings folders which I had placed in the steamvr folder/drivers/my_driver for convenience. I realize there is the option to add the external driver to avoid this problem but I had done it this way for easy folder navigating.
