### ISSUE TITLE
Writing the OpenVR Runtime Configuration path (openvrpaths.vrpath)

### ISSUE THREAD

**Issue by PakRaden** [ValveSoftware/openvr#548]
Is it possible to get OpenVR to write its own runtime path settings? (not just check if they exist)

e.g

{
   "config" : [ "C:\\Games\\Steam\\config" ],
   "external_drivers" : null,
   "jsonid" : "vrpathreg",
   "log" : [ "C:\\Games\\Steam\\logs" ],
   "runtime" : [
      "C:\\steamcmd\\steamapps\\common\\SteamVR\\",
      "C:\\steamcmd\\steamapps\\common\\SteamVR"
   ],
   "version" : 1
}

If vrmonitor.exe was run it normally would write or update the settings based on where it ran from.

The latest version of SteamVR (build 1496873977) , neither vrmonitor.exe or vrstartup.exe reliably write all the values correctly.
It'd be good to know this might be available in the OpenVR API so any config values might stay up to date in the future as versions change etc.

edit:
This look like it
https://github.com/ValveSoftware/openvr/blob/master/src/vrcommon/vrpathregistry_public.h
but it does not allow for manual setting of the runtime, config and log directories.
It only seems like you can load from a valid file, in order to save it.

**Comment by natbro** [comment]
hm, I'm not seeing any failure with vrmonitor or vrstartup failing to write their values?

the broader issue of the public openvr_api not having a write function is maybe a good point, we'll talk about this internally.

**Comment by JulianConesa** [comment]
Can you tell me where I can download the OpenXR API?

**Comment by JoeLudwig** [comment]
@JulianConesa You can find the latest OpenXR spec here: https://www.khronos.org/registry/OpenXR/specs/0.90/html/xrspec.html

and the SDK (with the header) is here: https://github.com/KhronosGroup/OpenXR-SDK

Note that SteamVR doesn't support OpenXR yet.

The answer to @PakRaden's question is to call vrpathreg.exe with the setting you'd like to change. That binary is in the SteamVR install at bin/win64/vrpathreg.exe.
