### ISSUE TITLE
Unable to init VR runtime (102) - Linux

### ISSUE THREAD

**Issue by lipsamol** [ValveSoftware/openvr#549]
VR client shared lib not found

I have built openvr and the openvr samples without errors.
But when I try to run hellovr_opengl or the other samples from the bin folder I get the init runtime error.

How do I link to the runtime correctly and run the samples?

My openvrpaths.vrpath points to user/.local/share/Steam/steamapps/common/SteamVR/

**Comment by natbro** [comment]
you should have a libopenvr_api.so in the same directory as your hellovr_opengl binary/executable. if your openvrpaths.vrpah points to user/.local/share/Steam/steamapps/common/SteamVR/, then the libopenvr_api.so bootstrapper will be looking to load user/.local/share/Steam/steamapps/common/SteamVR/bin/vrclient.so, and the rest of the runtime executables should be in user/.local/share/Steam/steamapps/common/SteamVR/bin/linux64.

**Comment by lipsamol** [comment]
I have libopenvr_api.so in...
OPENVR/samples/bin/linux64/
OPENVR/bin/linux64/ 
usr/local/lib
.local/share/Steam/steamapps/common/SteamVR/bin/linux64/

I am unsure how to solve the problem.

When I build/make openvr should I link it to the libopenvr_api.so in steam folder or how do I get openvr linked correctly?
Should it not be possible to build openvr and create app without running steam client?

**Comment by natbro** [comment]
you shouldn't need to build/make libopenvr_api.so on your own - there is a 64-bit .so provided. whether you build it or not, this is a library that you bundle with your applications - per the /openvr/src/README "Applications should not install the client binding library
globally or attempt to link to a globally installed client binding library" - worth reading that whole document - so definitely don't drop one in /usr/local/lib or any other global spot - you put it in the same directory as your application.

libopenvr_api.so is looking to find vrclient.so in user/.local/share/Steam/steamapps/common/SteamVR/bin/linux64 - do you have vrclient.so in that location, do you have a proper vrserver and vrcompositor runtime there and can you launch them standalone?

**Comment by lipsamol** [comment]
I had not seen the readme inside src, only the one in root folder.
So I removed .so in usr/local/lib and unpacked the openvr folder again.
I went into samples, created build folder and built samples.
I did not build the openvr root folder, to avoid building own .so file.

Now when I run hellovr_opengl I still get the same error. 102.
But I get some output like this:
.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available

When I look in .local/share/Steam/ubuntu12_32 I have the vrclient.so but I do not have a vrclient.so in .local/share/Steam/steamapps/common/SteamVR/bin/linux64 folder.
So I am thinking does it have something to do with 32/64 bit mismatch?

Anyway I am still without progress and have no idea how to solve it.
Hope you have more suggestions for a solution...

**Comment by johnv-valve** [comment]
You need to run steamvr applications inside the steam runtime.
    ~/.steam/steam/ubuntu12_32/steam-runtime/run.sh ./hellovr_opengl

Also note that GL is not well supported in the current Linux release. Please see https://github.com/ValveSoftware/SteamVR-for-Linux for all the latest instructions for Linux.

**Comment by lipsamol** [comment]
It still does not work
If I run run.sh line I get the following error:
relocation error: /OPENVR/samples/bin/linux64/hellovr_opengl: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6resizeEmc, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

**Comment by kisak-valve** [comment]
Hello @lipsamol, this error usually occurs when something is built against the system variant of libstdc++.so.6 and that library is newer than the steam runtime variant. The fast and dirty workaround is to move or delete the steam runtime variant of that library, so that it can fall-through to the system variant.

**Comment by toastedcrumpets** [comment]
For others struggling with the same issues, a neater solution is to try switching toolchains as suggested here:
http://steamcommunity.com/app/250820/discussions/5/1290691937710639221/
The runtime currently defaults to gcc-4.8 (see https://github.com/ValveSoftware/steam-runtime)

However, there is an issue with the hellovr_vulkan example on older gcc toolchains, and the OpenGL example has terrible performance, even on my 1080 ti so you really want to use the vulkan pathway. Thankfully, to get the vulkan example to work you just need a simple patch: 
https://gist.github.com/toastedcrumpets/d4dde447d9d23fcea4181bbbfadd3487

So, the full instructions for Ubuntu 16.04 were:
```bash
sudo apt-get install g++-4.9 
git clone https://github.com/ValveSoftware/openvr.git
#Apply the patch https://gist.github.com/toastedcrumpets/d4dde447d9d23fcea4181bbbfadd3487
cd openvr/samples/
mkdir build
cd build
CXX=g++-4.9 cmake ../
make
#Now run the examples using the steam runtime environment
~/.steam/steam/ubuntu12_32/steam-runtime/run.sh ../bin/linux64/hellovr_vulkan
```

I can't seem to get the tracked camera example to work though.

**Comment by username223** [comment]
I got `vrclient Shared Lib Not Found (102)` on a completely fresh Ubuntu 18.04 (steam installed through the .deb file on steampowered) in a VM when trying to run a program using the `openvr.h` runtime.

Running `ldd` on my binary did not reveal any missing library files.

Running `ldd` on `~/.local/share/Steam/steamapps/common/SteamVR/bin/vrclient.so` revealed that `libSDL2-2.0.so.0` and `libvulkan.so.1` weren't found.

Installing `libsdl2-dev` and `libvulkan-dev` with `apt` solved the problem.

The same problem was present on Ubuntu 19.10 (steam installed through package manager, path was `~/.steam/steam/steamapps/common/SteamVR/bin/vrclient.so`) and installing the above libraries fixed the issue.

**Comment by JoeLudwig** [comment]
@username223 Please open a fresh issue instead of resurrecting this old one.

**Comment by username223** [comment]
@JoeLudwig It was not intended to be a new issue, this issue is the top result when searching for `vrclient Shared Lib Not Found (102)` so I just wanted to provide a fix for others since none of the previous solutions worked for me.

Linux SteamVR information is a little hard to come by, so I just wanted to share my solution. Sorry if I bumped the thread or something.
