### ISSUE TITLE
Does the OSX version of SteamVR support IVRVirtualDisplay or IVRDriverDirectModeComponent based drivers?

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#551]
And if so, what is the format of the shared texture passed to these drivers, and what are the semantics for mutexing the textures?

**Comment by natbro** [comment]
Yes (IVRVirtualDisplay) and not-really (IVRDriverDirectModeComponent), but I haven't built an OS X sample or tested through either, so you'll be bleeding edge playing with it for a bit.
We're not super inclined to ensure IVRDriverDirectModeComponent unless there is a great reason, but we do want the newer and more robust IVRVirtualDisplay to work. The texture format is currently an IOSurfaceRef, so an MTLTexture needs to be created that is backed by an IOSurface. Since macOS support is in beta, the texture allocation and submission process is still subject to change, as is how the texture is synchronized - we may need to have the application indicate which MTLCommandQueue they are working on to write to their MTLTexture in order to ensure read/write ordering.

**Comment by TheDeveloperGuy** [comment]
Ok, sounds like a world of pain. Don't care enough about IVRDriverDirectModeComponent to implement an Oculus subsystem on OSX, so happy to forget about that one. Will start messing around with IVRVirtualDisplay, as I'm gonna need to implement an OSX driver sooner rather than later (ie. be production ready when SteamVR goes out of beta on OSX). 

Gonna be needing a bit of help I'm sure on getting that together, so is here the best place to ask the questions when I have them? First off, IVRVirtualDisplay doesn't allocate textures on Windows, so was that bit talking about IVRDriverDirectModeComponent on OSX? Would help a lot to have a code snippet for getting usable texture from handle passed to driver, as well as how to do sync.

**Comment by TheDeveloperGuy** [comment]
@natbro How is virtual driver support going on macOS? I've been working on some other projects, but am going to need to address macOS in earnest now. Is there anything like a macOS driver sample or any kind of starting point for this? Thx

**Comment by natbro** [comment]
as of (1516057341) http://steamcommunity.com/games/250820/announcements/detail/2810677293055410331 I've ensured it's working on macOS. No sample yet, but should arrive in the next SDK release or two. IVRVirtualDisplay requires a supported headset (so Vive on macOS) also be attached, it is reflecting an existing driver to a virtual display, not creating a completely virtualized one.

**Comment by TheDeveloperGuy** [comment]
@natbro Thanks for the update! The sample may not be urgent if you can clarify:

> The texture format is currently an IOSurfaceRef, so an MTLTexture needs to be created that is backed by an IOSurface. Since macOS support is in beta, the texture allocation and submission process is still subject to change, as is how the texture is synchronized - we may need to have the application indicate which MTLCommandQueue they are working on to write to their MTLTexture in order to ensure read/write ordering.

Is it possible to reflect something like a variation of the null driver on macOS? It's certainly a user demand on my end to be able to create virtualised HMDs on macOS, so *any* way of getting that to work on current or near future macOS OpenVR?

**Comment by natbro** [comment]
yes, you should be able to reflect the null driver or any driver - IVRVirtualDisplay just needs some other driver that the compositor thinks it's presenting to but then reflects it's texture elsewhere. I haven't tried it but will check with my porto-sample at some point soon to confirm. if you write a complex enough null-like driver (with distortion parameters, frequency information, etc) you should be able to then use IVRVirtualDisplay to reflect it to the display device you want, and that could be somewhat more flexible than implementing IVRDriverDirectModeComponent on that device. What are you hesitant about with IVRDriverDirectModeComponent? Just that it's not implemented on macOS or is there some Windows history to frustration there?

**Comment by TheDeveloperGuy** [comment]
@natbro Ok, so that sounds a lot like the Windows IVRVirtualDisplay (or at least the way I've implemented mine, in that I have a IVRDisplayComponent that also returns a IVRVirtualDisplay component). I actually implement IVRDriverDirectModeComponent as well in my driver, and can switch at Activate() which "mode" the driver is going to run in. The ouput for "direct" and "virtual" components for me ends up in the same backend, so it's mostly historical ("direct" was around for quite some time before "virtual") that I have "direct". Occasionally I find it's useful (for the user) to switch to "virtual" but default to "direct", as I get a slight peformance increase in "direct" mode.

I'd happily port that entire (Windows) driver over to macOS if I could, but am missing the info on how to deal with shared texture handles, synchronisation etc. Definitely don't need a full blown sample to port to macOS, if you're able to offer macOS code snippets for things like this (simplified Windows code):

Dealing with texture handle passed to IVRVirtualDisplay::Present():

    		ID3D11Texture2D *pTexture
    		device->OpenSharedResource((HANDLE)backbufferTextureHandle, __uuidof(ID3D11Texture2D), (void**)&pTexture);

Locking mutex:

    		// Get mutex from texture
		IDXGIKeyedMutex *pSyncMutex = NULL;
		pTexture->QueryInterface(__uuidof(IDXGIKeyedMutex), (void **)&pSyncMutex));

		// Lock mutex
		pSyncMutex->AcquireSync(0, 10));

Getting shared handle for texture created in IVRDriverDirectModeComponent::CreateSwapTextureSet:

		// Get IDXGIResource interface
		IDXGIResource* pOtherResource;
		texture->QueryInterface(__uuidof(IDXGIResource), (void**)&pOtherResource);

		// Get shared handle for texture
		HANDLE sharedHandle;
		pOtherResource->GetSharedHandle(&sharedHandle);

The texture format specified in IVRDriverDirectModeComponent::CreateSwapTextureSet( uint32_t unPid, uint32_t unFormat, uint32_t unWidth, uint32_t unHeight, vr::SharedTextureHandle_t( *pSharedTextureHandles )[ 3 ] );

**Comment by TheDeveloperGuy** [comment]
@natbro @JoeLudwig So it appears that the answer to this question is "No, macOS SteamVR does not support IVRVirtualDisplay or IVRDriverDirectModeComponent based drivers", as support includes some level of documentation that would allow a developer to implement the driver, and that for whatever reason is being withheld.
