### ISSUE TITLE
Wrong OpenVR installation registry path on macOS

### ISSUE THREAD

**Issue by OskarGroth** [ValveSoftware/openvr#553]
Upon running an Xcode project with the OpenVR framework correctly embedded and linked, and trying to init the runtime:

```
    // Loading the SteamVR Runtime
    
    vr::EVRInitError eError = vr::VRInitError_None;
    hmd = vr::VR_Init( &eError, vr::VRApplication_Scene );
    
    if ( eError != vr::VRInitError_None ) {
        hmd = NULL;
        NSLog(@"Unable to init VR runtime: %s", vr::VR_GetVRInitErrorAsEnglishDescription( eError ));
        return nil;
    }
```

I get:

```
Unable to read VR Path Registry from /Users/oskar/Library/Containers/org.cindori.SteamVR/Data/Library/Application Support/OpenVR/.openvr/openvrpaths.vrpath
2017-06-16 07:33:13.077414+0200 SteamVR[8487:2296918] Unable to init VR runtime: Installation path could not be located (110)
```

When the actual OpenVR installation path, after installing SteamVR through steam, is found at  "~/Library/Application Support/OpenVR/.openvr/openvrpaths.vrpath"

**Comment by OskarGroth** [comment]
Solved by turning off app sandbox.

**Comment by SoylentGraham** [comment]
Is there a workaround that doesn't involve turning off the sandbox?

Excuse my naivety, but I'm not sure how the sandbox stops the lib getting this info from the steamvr runtime... (blocked IPC?)

**Comment by OskarGroth** [comment]
Sandboxed apps only have access to their container and it's subfolders. Hence why the path is redirected to /Users/oskar/Library/Containers/org.cindori.SteamVR. Probably works by adding the relevant entitlements too.

**Comment by SoylentGraham** [comment]
[For future reference] In my case, going through unity. Their mac-vr experimental build doesn't have the same errors/problems. So MAYBE I was loading the library wrong, or MAYBE their library has some specific changes.
But I'm using their library (in the app's package contents) with the `openvr_lib.cs` interface here successfully
