### ISSUE TITLE
How to use same GPU as SteamVR in driver?

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#556]
Some computers have multiple GPUs (eg. laptops with Optimus). SteamVR deals with this (in the case of Optimus) by "Added Optimus hints to prefer dedicated GPU". How can the driver know (when creating DirectX contexts) which GPU SteamVR is using?

**Comment by TheDeveloperGuy** [comment]
Querying the Prop_GraphicsAdapterLuid_Uint64 property returns 0

**Comment by aleiby** [comment]
That property is to allow display redirect drivers to tell SteamVR which gpu they would prefer to use:
https://github.com/ValveSoftware/virtual_display/blob/master/driver_virtual_display/driver_virtual_display.cpp

The IVRSystem interface has a couple functions for getting which graphics adapter to use.  This is for applications to call to ensure they create their D3D device, etc. properly, but unfortunately IVRSystem isn't accessible from OpenVR drivers.

https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L1293

**Comment by TheDeveloperGuy** [comment]
@aleiby Would it be "hard" or "wrong" to add the adapter LUID for the adapter SteamVR is using to the properties accessible from the driver? Would certainly be useful...

**Comment by TheDeveloperGuy** [comment]
@aleiby @JoeLudwig @jeremyselan This is becoming a support issue for me, and would (I expect) be an issue for any HMD driver that needs its own D3D context (ie. any virtual or direct driver). If OpenVR isn't able to give any clues as to which GPU it's using (which it really needs to), then can someone at least detail (or provide code) as to how OpenVR is making its choice (so that the driver can make the same choice)?

An easy (temporary) fix could be to take the first non-Intel GPU in the case of a system with multiple GPUs. This would cover some instances, but obviously falls apart in the case of it being an AMD system or there being multiple discrete GPUs.

**Comment by dashingstag** [comment]
@TheDeveloperGuy @aleiby @JoeLudwig @jeremyselan I encountered issues activating direct mode on different computers and I suspect that the default gpu used on different computers may differ. As such I am trying to define the gpu I want steam to use. Is setting Prop_GraphicsAdapterLuid_Uint64 the right way to go? Note that I have not written my own direct component and am using the default direct mode steam provides .

As such I tried retrieving and setting this property Prop_GraphicsAdapterLuid_Uint64
I get the luid by 
`IDXGIFactory * pFactory = NULL;
	IDXGIAdapter * pAdapter;

	CreateDXGIFactory(__uuidof(IDXGIFactory), (void**)&pFactory);

	for (UINT i = 0; pFactory->EnumAdapters(i, &pAdapter) != DXGI_ERROR_NOT_FOUND; ++i)
	{
		DXGI_ADAPTER_DESC pdesc;
                pAdapter->GetDesc(&pdesc);
		char DefChar = ' ';
		char ch[128];
		WideCharToMultiByte(CP_ACP, 0, pdesc.Description, -1, ch, 128, &DefChar, NULL);
		printf("gpu desc: %s\n", &ch);
		printf("ll:%" PRIu64"\n", pdesc.AdapterLuid);
	}

	if (pFactory)
	{
		pFactory->Release();
	}`


In which I can see my Nvidia GTX 1060 card and the  Microsoft Basicc Render Driver.
However setting  Prop_GraphicsAdapterLuid_Uint64 to my nvidia driver by 
`vr::VRProperties()->SetUint64Property(h_ulPropertyContainer, vr::Prop_GraphicsAdapterLuid_Uint64, (uint64_t)132194);`

causes my driver to fail. I understand the luid might change if my computer is restarted but it should work in this particular session. Any help would be appreciated.

**Comment by TheDeveloperGuy** [comment]
@dashingstag AFAIK, there isn't an easy way to do what you want to do. What I do is look through all of the adapters and filter out MS and Intel, reverting to Intel if I can't find anything else. This works in most cases, as it results in the same GPU as SteamVR wants to use. 

The edge cases are caused by VR apps that don't do the same. So, in the case of an "auto" Optimus configuration, my driver and SteamVR will both choose the discrete GPU, but an app (so far I have only found Virtual Desktop to be a problem) can get this wrong and choose the integrated GPU. 

So, in this case, being told which GPU SteamVR is using wouldn't help, as you can't tell what the app is using. 

However, if you're not using "virtual" or "driver direct" modes, your driver doesn't and shouldn't care which GPU is being used, and the issues that there are can't be corrected or worked around in your driver anyway.

**Comment by dashingstag** [comment]
@TheDeveloperGuy Thanks for the reply. I found out the true problem in which devices without HDCP support has a chance of failing to activate direct mode on newer graphic cards. (this might mean the same graphic card or drivers but bought at a different date/setup)

**Comment by TheDeveloperGuy** [comment]
What I do is look through all of the adapters and filter out MS and Intel, reverting to Intel if I can't find anything else. This works in most cases, as it results in the same GPU as SteamVR wants to use.
