### ISSUE TITLE
UE4 game problem when implementing the IVRDriverDirectModeComponent in driver

### ISSUE THREAD

**Issue by bsufo111** [ValveSoftware/openvr#559]
Hello, I met a problem when implementing the IVRDriverDirectModeComponent. With the direct mode, the vrmonitor and Unity games run normally, but it seems there are some problems for UE4 games. The UE4 game texture can't be displayed and I even can't save the UE4 texture to file with the system call D3DX11SaveTextureToFile. 
I see when launching the UE4 game, CreateSwapTextureSet will be called with the texture format to DXGI_FORMAT_B8G8R8A8_UNORM_SRGB, different from the vrmonitor and Unity games which using DXGI_FORMAT_R8G8B8A8_UNORM_SRGB. Did anyone ever met similar issue? Do you have any idea for this? Thanks in advance.

**Comment by TheDeveloperGuy** [comment]
Always use DXGI_FORMAT_B8G8R8A8_UNORM_SRGB for your render target texture format. Works for me.

**Comment by bsufo111** [comment]
@TheDeveloperGuy Thanks a lot. I'll have a try.

**Comment by bsufo111** [comment]
@TheDeveloperGuy Hello, I tried the way that using DXGI_FORMAT_B8G8R8A8_UNORM_SRGB for the texture. But this time the SteamVR do not identify my created texture and could not render the normal image to the texture. That's the SteamVR Headset Mirror of the two cases that I use DXGI_FORMAT_R8G8B8A8_UNORM_SRGB and DXGI_FORMAT_B8G8R8A8_UNORM_SRGB.
Do I still miss something?

![r8g8b8a8](https://user-images.githubusercontent.com/11459774/27432055-412d5d36-5781-11e7-8ab3-871698ee9560.png)


![r8g8b8a8](https://user-images.githubusercontent.com/11459774/27432169-a096a39a-5781-11e7-9561-72ed6bbefc39.png)

**Comment by TheDeveloperGuy** [comment]
The render target is your final texture that you render to (ie. compose all of the eye textures into in the case of IVRDriverDirectModeComponent). (Should be) Obviously changing the texture format of requested textures before allocating them is not going to work. Copy and paste error on my part, your render target should be DXGI_FORMAT_R8G8B8A8_UNORM_SRGB

**Comment by bsufo111** [comment]
@TheDeveloperGuy Hi, I almost get what you mean after having another try. Seems need to redesign my project for this. Thanks a lot for your help.
