### ISSUE TITLE
Custom driver init error since the addition of SteamVR Home

### ISSUE THREAD

**Issue by thezenmaster** [ValveSoftware/openvr#561]
Since the last update of SteamVR that added SteamVR Home (among other things I suppose), I keep getting the following error when I start my custom driver:

"SteamVR failed to initialized for unknown reasons. (Error: Connect to VR Server Failed (301))."

After that SteamVR suggests to relaunch VR Server. However, it appears that VR Compositor hasn't reconnected, so IVRVirtualDisplay::Present is no longer called. The VR Compositor log only states:

IPCPipe(VR_CompositorPipe_8800): Process disconnected.
Lost IPC connection
VR compositor shutting down

I should note that starting apps directly works in some cases, for example with Job Simulator or theBlu. I can see that Present is being called normally. It seams the issue is constrained to SteamVR Home and other (UE4??) apps.

Has anyone else run into this issue? I debugged the initialization of our driver and everything seams fine. The regular Vive (Lighthouse) driver starts up normally. Latest GeForce driver is installed.

Thanks!

**Comment by TheDeveloperGuy** [comment]
Seems like the latest beta might have a fix for this. We're going through a pretty unstable time with SteamVR right now. Every other release is breaking something.

**Comment by thezenmaster** [comment]
I think I have the latest beta installed, and the issue is still present. No change (Built June 23, Version 1498179029).

**Comment by thezenmaster** [comment]
Does anyone have an update on that? It's been open for over 8 months now.

**Comment by JoeLudwig** [comment]
Can you post a system report from right after this problem appears? 

"SteamVR suggests to relaunch VR Server"

I'm not sure what you mean here. We don't suggest anything about restarting vrserver.exe. Is it prompting you to restart SteamVR?


This likely has nothing to do with SteamVR Home. Maybe there was a driver interface change in the same update that broke your driver?

**Comment by thezenmaster** [comment]
Thanks for getting back to me, Joe! I'm attaching a system report that I did right after the error occurred. There's also a screenshot of the message "Launch VR Server" that I'm getting.

I agree, this must be a driver interface change that we missed, but I haven't been able to track it down.

![steamvr](https://user-images.githubusercontent.com/4326216/36709080-f129fa2e-1b2a-11e8-8b87-5b7eba62eb6d.jpg)

[report right after error.txt](https://github.com/ValveSoftware/openvr/files/1761107/report.right.after.error.txt)

**Comment by JoeLudwig** [comment]
It looks like vrserver.exe is crashing. Do you have any .dmp files in C:/Program Files (x86)/Steam/dumps?

**Comment by thezenmaster** [comment]
Yes, there actually is a dump file. Attaching. 

Looks like the exception is in our driver code, I'll see if this helps me track it down.
[crash_vrserver.exe_20180226191646_1.dmp.zip](https://github.com/ValveSoftware/openvr/files/1764116/crash_vrserver.exe_20180226191646_1.dmp.zip)

**Comment by kisak-valve** [comment]
For reference, the attached minidump is an EXCEPTION_ACCESS_VIOLATION_READ in QuarkVRCore.dll.

**Comment by thezenmaster** [comment]
Yeah, I'm on that. I'll close the issue if that's all to it. Thanks for the support!

**Comment by JoeLudwig** [comment]
You bet. Sorry that took so long. :)
