### ISSUE TITLE
What to change to run "Headset window" on the second monitor?

### ISSUE THREAD

**Issue by r57zone** [ValveSoftware/openvr#563]
What to change to run "Headset window" on the second monitor (headset)?
"steamvr.vrsettings" config:
> {
>    "driver_null" : {
>       "enable" : true,
>       "id" : "Null Driver",
>       "renderHeight" : 1512,
>       "renderWidth" : 1344,
>       "secondsFromVsyncToPhotons" : 0.10000000149011612,
>       "serialNumber" : "Null 4711",
>       "windowHeight" : 1080,
>       "windowWidth" : 1920,
>       "windowX" : 0,
>       "windowY" : 0
>    },
>    "steamvr" : {
>       "activateMultipleDrivers" : true,
>       "enableHomeApp" : false,
>       "forcedDriver" : "null",
>       "mirrorViewGeometry" : "0 0 960 540"
>    }
> }
> 
if change "WindowsX" to 1921 nothing happens.

**Comment by r57zone** [comment]
I changed result in metod to:
... IsDisplayRealDisplay() 
{
	return true;
	//return false;
}

windowX stil not working, if i change this then show me error problem "Shared ipc compositor connect failded (306)"

**Comment by r57zone** [comment]
In default "driver_null" Headset window in Windowed Mode (borderless fullscreen) and i can move with buttons "Shift + Win + Right", in "driver_sample" is not Windowed Mode. What should I change in "driver sample" for run in Windowed Mode?

**Comment by TheDeveloperGuy** [comment]
Set Prop_DisplayDebugMode_Bool property

**Comment by r57zone** [comment]
@TheDeveloperGuy It working, thank you very much!

**Comment by TheDeveloperGuy** [comment]
@r57zone Monitor coordinates are zero-based, so you should be giving 1920 as the offset, not 1921... ;)

**Comment by r57zone** [comment]
@TheDeveloperGuy The window moves to the second screen, but has a red screen, to fix it need to click on it, but then it is launched back in Fullscreen back to the first screen.

**Comment by TheDeveloperGuy** [comment]
The problem is most likely that your driver is called "driver_null" or "driver_sample". AFAIK, these are special driver names that are reserved for SteamVR and invoke special behaviour. Your own driver should be called something else.

**Comment by TheDeveloperGuy** [comment]
In fact, as far as I know, the null driver is built from the sample driver source code. Renaming the sample driver to null has the same effect as setting the debug mode property.

**Comment by r57zone** [comment]
With any other name, driver_sample don't to work.

**Comment by TheDeveloperGuy** [comment]
Make sure you return true from IsDisplayRealDisplay() in your driver, as per https://github.com/ValveSoftware/openvr/issues/200#issuecomment-311612609

**Comment by r57zone** [comment]
Yes, did it.

**Comment by r57zone** [comment]
The problem is not solved.
Maybe related [issues 580](https://github.com/ValveSoftware/openvr/issues/580).

**Comment by Balderick** [comment]
Have you tried enabling nulll driver without using forcedDriver?

**Comment by r57zone** [comment]
@Balderick without using forcedDriver sometimes does not work.

That's exactly what I did. Here is [my driver](https://github.com/r57zone/OpenVR-OpenTrack/blob/master/OpenVR/samples/driver_sample/driver_sample.cpp), here is [my config](https://pastebin.com/raw/2Y6E8DWp).

Tried to change IsDisplayRealDisplay return to true, generally ceases to work. Could anyone please see what's wrong? The default "driver_sample" with OpenTrack support head tracking rotation.

**Comment by r57zone** [comment]
Found the error, it turns out I was wrong and did not change the renderWidth parameter, renderHeight, in the config. It should be strictly renderWidth = windowWidth, renderHeight = windowHeight, with IsDisplayRealDisplay return to true.

Normal picture (without red screen).

**Comment by Balderick** [comment]
Hi again r57zone

I just had a look at https://github.com/r57zone/OpenVR-OpenTrack/blob/master/README.md and what you describe there is not recommended.

The null driver is provided for testing drivers.

You need to apply what is described for using your proven working driver https://github.com/ValveSoftware/openvr/wiki/Driver-Documentation
