### ISSUE TITLE
How to create virtual HMD?

### ISSUE THREAD

**Issue by huytn22** [ValveSoftware/openvr#568]
i want to create virtual HMD, that can capture rendering image as Virtual_display sample without connect HTV Vive HMD. Does anyone know how to do that?

**Comment by Balderick** [comment]
Use the null driver.

All openvr drivers started life as null driver.   The null driver uses a virtual hmd ootb.   All you need to do is enable null driver in steamvr.vr settings.

Here is an example of how to use null driver to allow the use of vive controllers when no hmd is physically connected to PC.
http://help.triadsemi.com/steamvr-tracking/steamvr-tracking-without-an-hmd

**Comment by shensheng27** [comment]
also you can view https://github.com/ValveSoftware/virtual_display to see the demo code

**Comment by TheDeveloperGuy** [comment]
Yes, take the "virtual_display" sample as a starting point, remove the bit where it outputs frames to a server process via shared memory and put your own implementation of whatever you'd like to do instead in its place. There is a PDF file in that sample folder that describes how the sample works.
