### ISSUE TITLE
vrserver stucked on my created hmd driver.

### ISSUE THREAD

**Issue by osbike** [ValveSoftware/openvr#57]
Hi,

I am trying to create a hmd driver.
I read/build 0.9.16 driver sample and put it to steamapps\common\SteamVR\drivers.
But there are still some problems:

1. In ITrackedDeviceServerDriver constructor, it get settings via IServerDriverHost (which might be from vrserver). And I get string/int/bool from the setting object, it always gets default value (I expected get value from setting object). 
for example:
float headingoffset = pSettings->GetFloat(k_pch_Lighthouse_Section, k_pch_Lighthouse_HeadingOffset_Float, 0.0);

It looks I get an un-workable setting object from driver host. Should I do any step to make it correct?

2. the result is that vrserver stuck before launch compositor. I think it might due to no hmd found. I returned EDID vendor ID via GetInt32TrackedDeviceProperty, but seems not workable.

Could someone give me advice?

Thanks,

**Comment by osbike** [comment]
Looks like vrcompositor didn't work due to waiting for IPC from VR server. But VR server stucked for some reason.

Thu Mar 03 2016 16:54:24.618 - Starting vrcompositor process: C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win32\vrcompositor.exe 
Thu Mar 03 2016 16:54:32.744 - IPCPipe(VR_Compositor): Process disconnected.
Thu Mar 03 2016 16:54:32.744 - GetNextMessage failed while waiting for message of type VRMsg_CompositorConnectResponse on pipe VR_Compositor
Thu Mar 03 2016 16:54:32.744 - Invalid response to connect message. Connect failed

**Comment by osbike** [comment]
Thu Mar 10 2016 11:18:19.608 - Timeout while waiting for message of type VRMsg_GetPropertyResponse on pipe VR_Pipe
Thu Mar 10 2016 11:18:19.608 - Timeout fetching property 1001 from server
Prop_ModelNumber_String:

**Comment by JoeLudwig** [comment]
You shouldn't use the Lighthouse section for your driver's settings. Use the name of your driver there instead. What result do you expect? What is in steamvr.vrsettings under that section and key?

What calls are you receiving from vrserver? Does vrserver.txt report any errors?

You should get one call to get the device count, and then assuming you return at least 1 you'll get subsequent calls to get details on the devices. Are you getting those calls?

**Comment by osbike** [comment]
I expect to see content in HMD with my driver.dll. So the section information is from steamvr.vrsettings? And I should fill values of keys by myself? After I return 1 for device count, I get several calls as below:
9:52:26:880 - GetInt32TrackedDeviceProperty: 1029
9:52:26:881 - GetTrackedDeviceCount
9:52:26:883 - GetStringTrackedDeviceProperty: 1002
9:52:26:884 - GetStringTrackedDeviceProperty: 1002
9:52:26:885 - GetFloatTrackedDeviceProperty: 2003
9:52:26:886 - GetFloatTrackedDeviceProperty: 2026
9:52:26:888 - GetWindowBounds
9:52:26:889 - IsDisplayOnDesktop
9:52:26:890 - IsDisplayRealDisplay
9:52:26:892 - GetRecommendedRenderTargetSize
9:52:26:894 - GetProjectionRaw
9:52:26:896 - GetEyeOutputViewport
9:52:26:899 - GetProjectionRaw
9:52:26:901 - GetEyeOutputViewport
9:52:26:903 - GetStringTrackedDeviceProperty: 1002
9:52:26:906 - GetStringTrackedDeviceProperty: 1002
9:52:26:908 - GetInt32TrackedDeviceProperty: 1029
9:52:26:910 - GetBoolTrackedDeviceProperty: 1004
9:52:26:912 - GetBoolTrackedDeviceProperty: 1030
9:52:26:913 - GetBoolTrackedDeviceProperty: 2000
9:52:26:915 - GetFloatTrackedDeviceProperty: 2001
9:52:26:916 - GetFloatTrackedDeviceProperty: 2002
9:52:26:918 - GetInt32TrackedDeviceProperty: 2011
 
After I hardcoded the values, I can see content in HMD. But there are still some problems:
1. It only works on direct mode. For normal mode, it shows below error in vrcompositor.log
    Mon Mar 14 2016 10:41:52.059 - Invalid adapter (-1, -1) specified!
    Mon Mar 14 2016 10:41:52.060 - Failed to initialize compositor
    Mon Mar 14 2016 10:41:52.060 - Failed to start compositor: VRInitError_Compositor_Failed
2. Hellovr works but unity application shows HmdNotFound as below:
    Fri Mar 11 2016 15:08:09.911 - vrclient startup with PID=12204, config=C:\Program Files (x86)\Steam\config
    Fri Mar 11 2016 15:08:09.913 - Returning HmdNotFound because the client-side presence check failed.

**Comment by osbike** [comment]
Hi Joe,
My second problem is due to lack of x64 library. After build x64 library. Unity application could be showed in hmd.

**Comment by JoeLudwig** [comment]
You definitely need both win64 and win32 versions of your driver DLL.

In non-direct mode what are you returning from GetWIndowBounds? Are they actual window bounds of a display?

**Comment by osbike** [comment]
Hi Joe,
After checking returning value from GetWindowBounds, I noticed that the value is different between direct mode and non-direct mode. Now it works. Thanks lots.
