### ISSUE TITLE
question: openvr without steam/steamvr?

### ISSUE THREAD

**Issue by imaginaryeast** [ValveSoftware/openvr#572]
I have an application that doesn't run through steam, but it uses openVR. Is there a way to run an HMD without installing Steam/SteamVR? it uses an oculus rift, and i don't know how to get the openvr drivers without steamvr.

**Comment by JoeLudwig** [comment]
SteamVR is the only implementation of the OpenVR API that I'm aware of. You'll need it to run OpenVR apps.
