### ISSUE TITLE
No controllers using the latest SteamVR with 2017.1

### ISSUE THREAD

**Issue by pateras** [ValveSoftware/openvr#579]
I did the following:

1. Installed the latest Unity 2017.1 release candidate.
2. Imported the latest version of SteamVR via the asset store.
3. Per the SteamVR Quickstart PDF, I clicked on MainCamera, added a "Steam VR_Camera" script, and then clicked Expand.
4. This didn't work at all (moving the headset did nothing), so I went to Player Settings > Other Settings, checked "Virtual Reality Supported" and added the OpenVR SDK.

That got the headset working, but now the controllers don't show up.

**Comment by bddckr** [comment]
Wrong repo, new one is here: [ValveSoftware/steamvr_unity_plugin](https://github.com/ValveSoftware/steamvr_unity_plugin/)

Also make sure to use the new update (SteamVR plugin 1.2.2).

**Comment by pateras** [comment]
Oops. Thanks!
