### ISSUE TITLE
Distortion question

### ISSUE THREAD

**Issue by nerogcy** [ValveSoftware/openvr#585]
Do i need to manually apply distortion shader effect to my output RenderTarget before submit to compositor? Or compositor will help me to apply correct distortion?

**Comment by JoeLudwig** [comment]
You should submit your undistorted textures and let the compositor take care of it.

You **can** distort before submitting with the Submit_LensDistortionAlreadyApplied flag, but that's a bunch of work you don't need to do in your application.

**Comment by nerogcy** [comment]
Thanks :)
