### ISSUE TITLE
Access violation in nvoglv64.dll when calling Submit

### ISSUE THREAD

**Issue by mtsep** [ValveSoftware/openvr#589]
Hello,
I have a following issue in my OpenGL + OpenVR project:
the program crashes with an access violation in nvoglv64.dll when submitting an OpenGL texture to the Compositor.
The funny thing is, it started after an NVidia driver update. I have tested several driver versions and found out that the last version that worked was 378.92. Any version after that (including the newest 384.76) leads to the crash.
I am using the lastest OpenVR SDK, GPU is Geforce GTX1080, OS is Windows 10.
The project where this happens is really huge with several OpenGL contexts and a lot of dependencies, however I made an example test function that is called as the first thing after program start. This function successfully submits the frame when using the driver 378.92 and crashes when any newer driver is installed.

I also tried to debug using the CodeXL debugger, found no OpenGL errors. The crash error message is different when using CodeXL, it says that the data alignment is wrong. Also, using CodeXL I could view the OpenGL function call history and found the point where the crash happens inside the Submit function.

I attached several screenshots  to this post:
The crash message from VisualStudio:
![ex2](https://user-images.githubusercontent.com/25152877/28468217-94619f40-6e32-11e7-8edb-b6dd5eba6ee8.png)

The crash message from CodeXL:
![ex1](https://user-images.githubusercontent.com/25152877/28468216-945ec176-6e32-11e7-9f33-7dc46f5ea49d.png)

The OpenGL call history inside Submit, viewed using CodeXL
![history](https://user-images.githubusercontent.com/25152877/28468215-945cc100-6e32-11e7-8f9e-6a2fdd4d6808.png)

Test code I used to reproduce the crash is at the bottom of this post.

Does anyone have an idea what could cause this issue or how to avoid it?

`	
vr::HmdError err;
	auto vrsys = vr::VR_Init(&err, vr::VRApplication_Scene);
	auto compositor = vr::VRCompositor();
	
	vr::TrackedDevicePose_t trackedPose[vr::k_unMaxTrackedDeviceCount];
	vr::VRCompositor()->WaitGetPoses(trackedPose, vr::k_unMaxTrackedDeviceCount, NULL, 0);

	/// application instance
	HINSTANCE hInstance;
	/// window handle
	HWND hwnd;
	/// window context
	HDC hdc;
	/// OpenGL context
	HGLRC hglrc;

	hInstance = GetModuleHandle(NULL);
	
	// register window class
	WNDCLASSEX wcex;
	wcex.cbSize = sizeof(WNDCLASSEX);
	wcex.style = CS_OWNDC | CS_HREDRAW | CS_VREDRAW;
	wcex.lpfnWndProc = WndProc2;
	wcex.cbClsExtra = 0;
	wcex.cbWndExtra = 0;
	wcex.hInstance = hInstance;
	wcex.hIcon = NULL;
	wcex.hCursor = LoadCursor(NULL, IDC_ARROW);
	wcex.hbrBackground = NULL;
	wcex.lpszMenuName = NULL;
	wcex.lpszClassName = szWindowClass;
	wcex.hIconSm = NULL;
	RegisterClassEx(&wcex);

	hwnd = CreateWindow(szWindowClass, _T("TESTWINDOW"), WS_OVERLAPPEDWINDOW,
		0, 0, 800, 600, NULL, NULL, hInstance, NULL);

	hdc = GetDC(hwnd);
	
	// choose and set pixel format
	PIXELFORMATDESCRIPTOR pfd =
	{
		sizeof(PIXELFORMATDESCRIPTOR),
		1,
		PFD_DRAW_TO_WINDOW | PFD_SUPPORT_OPENGL | PFD_DOUBLEBUFFER,
		PFD_TYPE_RGBA,
		(BYTE)32, // color bits
		0, 0, 0, 0, 0, 0,
		0, // alpha bits
		0,
		0,
		0, 0, 0, 0,
		24,	// depth bits
		0,	// stencil bits
		0,
		PFD_MAIN_PLANE,
		0,
		0, 0, 0
	};

	int pixelformat = ChoosePixelFormat(hdc, &pfd);
	DescribePixelFormat(hdc, pixelformat, sizeof(pfd), &pfd);

	BOOL bResult = SetPixelFormat(hdc, pixelformat, &pfd);

	// create OpenGL context
	hglrc = wglCreateContext(hdc);

	wglMakeCurrent(hdc, hglrc);

 	GLEWContext	m_glew_context;
 	WGLEWContext m_wglew_context;
	wglewContextInit(&m_wglew_context);
 	glewContextInit(&m_glew_context);

	// show and redraw
	ShowWindow(hwnd, SW_SHOW);
	UpdateWindow(hwnd);

	uint32_t w, h;
	vrsys->GetRecommendedRenderTargetSize(&w, &h);
	
	unsigned int gltexid;
	glGenTextures(1, &gltexid);
	glBindTexture(GL_TEXTURE_2D, gltexid);
	unsigned char* imgPtr = new unsigned char[4 * w * h];
	memset(imgPtr, 255, 4 * w * h);
	glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA8, w, h, 0, GL_RGBA, GL_UNSIGNED_BYTE, imgPtr);
	auto rrrr = glIsTexture(gltexid);
	glFlush();
	const vr::Texture_t tex = { reinterpret_cast<void*>(intptr_t(gltexid)),vr::TextureType_OpenGL,vr::ColorSpace_Gamma };
	vr::EVRCompositorError res2;
	res2 = vr::VRCompositor()->Submit(vr::Eye_Left, &tex);	
`

**Comment by danginsburg** [comment]
I attempted to repro this crash by modifying hellovr_opengl in the OpenVR SDK to do something similar to your code.  One bug you have there is that the texture being supplied is incomplete because only mip level 0 is provided but the default GL_TEXTURE_MIN_FILTER has mipmaps.  That will cause an error in the Submit call.  Try adding this after the call to glTexImage2D:

```
glTexParameteri( GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
glTexParameteri( GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
```

Does that fix your issue?

**Comment by danginsburg** [comment]
The specific problem I believe you would be hitting is that Submit uses glCopyImageSubData and it will throw an error because the texture is incomplete:

https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glCopyImageSubData.xhtml
"GL_INVALID_OPERATION is generated if either object is a texture and the texture is not complete."

**Comment by mtsep** [comment]
Thank you for your replies!
Unfortunately setting the MinFilter and MagFilter to linear did not help. I also tried setting GL_TEXTURE_BASE_LEVEL and GL_TEXTURE_MAX_LEVEL to 0, as written here:
https://www.khronos.org/opengl/wiki/Common_Mistakes#Creating_a_complete_texture

But it still did not change the behavior (works with the old driver, but does not with the newer one).

**Comment by danginsburg** [comment]
Could you post the complete source code/project and/or a built executable version of it?  So far I am not able to repro this crash with code doing something similar on Win10 x64 NVIDIA 384.72 GTX 1070 with either SteamVR or SteamVR [beta].

**Comment by mtsep** [comment]
Hm, this keeps getting weirder. I can't post the source code or an executable from this particular project, because of my company's policy, so I tried to make a standalone example. And the same code I posted here seems to work perfectly there, regardless of the used driver... Must be some other dependency in the big project interfering with the driver, or something about the project configuration. Actually weird, because the posted test function in the big project crashes even when it is called as the first thing directly in the entry point, before any other component has a chance to interact with OpenGL. At the time there are no other OpenGL contexts present, etc.
I'll have to try to reproduce the crash in a standalone example, then I will be able to post the example here.

**Comment by mtsep** [comment]
OK, I think I got this. I believe the crash reason is the Control Flow Guard flag (/guard:cf) in the project Code Generation properties.
Could you try enabling it in any test project to reproduce the crash? 
I'm using MS Visual Studio 2015 (Toolset v140). The flag can be enabled in C/C++ Properties, Code Generation.
I could also upload my test project, if you need it.
