### ISSUE TITLE
Front camera not working under linux

### ISSUE THREAD

**Issue by marcosswald** [ValveSoftware/openvr#593]
I can't get the front camera to work under linux. All the rest works perfectly fine. When I plug in the Vive, I can see a video device listed under /dev/video0 but I don't see a video when opening with cheese or camorama. In fact, camorma reports an error. So does SteamVR itself when I go to settings and select the camera. It reports that the camera was not recognized on the current usb port. I tried different ports with no effect. However, the camera always remained listed under /dev/video0.

**Comment by kisak-valve** [comment]
Hello @marcosswald, are you still experiencing this issue on an up to date system?

**Comment by messier-45** [comment]
Hello, I am also using a Vive on a Linux machine. I'm not sure if this answers your question, but when I press the system button, the front camera view screen tied to the controller works just fine for me.

**Comment by kisak-valve** [comment]
Thanks for testing @messier-45, @Zamundaaa. Closing.
