### ISSUE TITLE
BUG: HMD blanking when using IVRVirtualDisplay

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#598]
It appears to be related somehow to tracking, as it manifests with some tracking systems but not others, where in some SteamVR apps (most notably Home and The Lab), the HMD will start being sent blank (black) textures. I've stepped through all of my driver code and as far as I can see there are no DirectX errors, the driver is actually being passed a blank texture. In some scenarios (eg. The Lab) the situation will right itself (seems like opening/closing SteamVR dashboard a few times can correct it), in others it will fix itself while SteamVR is shutting down (if you choose to exit SteamVR). 

If I run the exact same setup with a IVRDriverDirectModeComponent driver (same driver, different mode of operation), then I don't get this issue at all. If I run with a different tracking system (in this case, only orientation, no position) I also don't get this issue. At first I thought it was something to do with the tracking rate being too close to the frame rate (the problematic tracking is 60Hz, whereas the orientation only tracking is 100Hz), but that doesn't appear to be (entirely) the issue.

When it is displaying correctly (most of the time), there can be an occasional black texture sent through (looks like a blink), so it looks to me that there is some kind of test that OpenVR is doing to determine to render or not (maybe standby or something?) that this setup is failing. 

So, what (tracking related?) scenarios can cause the IVRVirtualDisplay to be sent blank (black) textures?

**Comment by prsyahmi** [comment]
Have you check if the blink causes by timeout during AcquireSync?

**Comment by TheDeveloperGuy** [comment]
Yes, I have checked and AFAIK it is not a timeout. This is an actual black texture being passed.

**Comment by TheDeveloperGuy** [comment]
So, it turns out this has nothing to do with tracking, but is actually related to the vertical refresh rate of the virtual display. If the vertical refresh is 60-62Hz (maybe also for less, but who cares), then this problem can occur. On 60-61Hz the display blanks completely, and on 62Hz there is an occasional "blink". Setting the refresh rate to 63Hz or higher gets rid of the problem (but doesn't really help as the "display" itself is 60Hz). Note this is a Wifi connected display, and so the vertical blank interval is completely synthetic and is maintained (to microsecond accuracy).

I've implemented 2 virtual display drivers from scratch, and they both exhibit this issue (mostly on the The Lab, where you can see it on the loading screen). Drivers based on IVRDriverDirectModeComponent do not have this issue, nor is it an issue above 62Hz.

**Comment by TheDeveloperGuy** [comment]
@JoeLudwig  Bumping this, as I don't want the solution to this issue to be "don't use IVRVirtualDisplay".

**Comment by Balderick** [comment]
Do you see the blanking on machines using amd and nvidia GPUs?
If you are seeing this on nvidia machines only, have you tried rolling back to 382 version drivers?

**Comment by TheDeveloperGuy** [comment]
@aleiby @JoeLudwig This is a really weird issue, which only manifests on certain (mainly Valve) apps. It seems to be related to vertical sync frequency (and not actual FPS), where it seems to hit some kind of threshold below which rendering is switched off. It's also not consistent (ie. it doesn't always happen, when running the same apps at the same refresh rate). I'll do some more testing around this as latest Beta may have fixed this by happy accident. FWIW, it never happens in the SteamVR landing screen, but can happen often in "steamtours.exe" (aka. SteamVR Home).

I guess the most useful would be trying to figure out what if any scenarios would cause SteamVR (or apps) to turn off rendering (eg. trigger into standby etc.), and preventing that in my driver.

**Comment by TheDeveloperGuy** [comment]
Seems to be fixed in later versions.
