### ISSUE TITLE
C API isn't actually C, requires non-existent files

### ISSUE THREAD

**Issue by jherico** [ValveSoftware/openvr#6]
The C API header has the following includes:

```
#include "ivrsystem.h"
#include "ivrcameraaccess.h"
#include "ivrchaperone.h"
#include "ivrchaperonesetup.h"
#include "ivrcompositor.h"
```

None of which are in the release.  Additionally, it includes `openvr.h` itself, which makes use of namespaces, immediately making it impossible to use in C.

**Comment by KateAdams** [comment]
Additionally, it should be `openvr.h` for the C api; and `opencvr.hpp` or `opencvr.hh` for the C++ variant.

**Comment by JoeLudwig** [comment]
@jherico : Fixed in https://github.com/ValveSoftware/openvr/commit/29d6b20cb0e566461de829c98bfe2aecaac1beb3#diff-1aed950f5e3868e2a73cdbd7ba439a2b

@KateAdams : The coding standard we use at Valve uses .h for both C++ and C files.
