### ISSUE TITLE
How do I use Visual Studio Graphics Debugger with OpenVR?

### ISSUE THREAD

**Issue by Compynerd255** [ValveSoftware/openvr#602]
Visual Studio comes with an optional Graphics Debugger component that allows you to capture individual rendered frames and see all of the DirectX draw calls that compose that frame, including being able to step and trace through shaders. The tools normally rely on DXGI Present calls to determine the boundaries between these frames, but since the actual Present calls are in another process (the compositor) my application does not get them and thus the Graphics Debugger hangs when I try to capture a frame. Is there a way I can get those frames and thus use the debugger?

**Comment by BlakeR07** [comment]
You should still be doing a present call for DirectX. I suggest you look at hellovr written for DirectX 11.

**Comment by Compynerd255** [comment]
OK, that makes sense - I remember something to that effect in the Compositor documentation to that effect. I guess I was trying to avoid it for the particular case of my app's rendering pipeline, but I can probably figure something out.
