### ISSUE TITLE
Controller in mouse input mode

### ISSUE THREAD

**Issue by elect86** [ValveSoftware/openvr#603]
I see from the [`openvr.h`](https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L672-L674)

```
/** when in mouse input mode you can receive data from the touchpad, these events are only 
     sent if the users finger is on the touchpad (or just released from it) 
**/
```

How can I set the controller in mouse input mode? Does this have anything to do with overlays?

**Comment by bddckr** [comment]
[Yep](https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L2489), search the same header for "mouse" and find it talking about "simulated mouse events in overlay space".

**Comment by elect86** [comment]
Thanks Christopher, I managed somehow to get a basic sample working..

And what about the touchpad? is there a way to get the position of the user finger on it?

**Comment by JoeLudwig** [comment]
These events are sent to overlays with the VROverlayFlags_SendVRTouchpadEvents flag set. If you want to interpret the touchpad as mouse input outside the context of an overlay, you'll need to do that from the raw input data in GetControllerState.

**Comment by elect86** [comment]
Clear, thanks!
