### ISSUE TITLE
How To Use Vive Tracker As Head Tracker?

### ISSUE THREAD

**Issue by Balderick** [ValveSoftware/openvr#605]
Trying to use a pair of vive pre controllers, a pair of base stations along with a vive tracker to steamvr trackify my osvr hdk hmd.

Using https://github.com/OSVR/OSVR-Docs/blob/master/Extending-OSVR/ConfiguringHDKViveTracking.md as main source I enabled multiple drivers in steamvr.vr settings and get all tracked devices showing up as expected in steamvr room layout but because of osvr api using different coordination system I find I need to use openvr-inputemulator to try and fix pose.

Going for the full osvr implementation of vive tracker using osvr-vive along with adjusting Alias's using semantic paths to run an osvr app gave me head tracking using vive tracker but again pose was FUBAR making osvr app unusable.   I used Parabolic for testing and I could not even get to pilots seat.  Could walk around the outside of ship and look around.   
EDIT:  After trying to reproduce all of above I have working head tracking in osvr runtime and osvr apps.  See comment below.  Pressing `C` in osvr app recentered pose.   OSVR Tracker Viewer was also used to confirm pose is usable.

**1.** Does openvr have the ability to use semantic paths to use aliases for selecting trackers for objects/devices?
EDIT:  Yes it does.  Through steamvr-osvr driver.

Have found making osvr hdk orientation only by removing the ir array and ir board from hmd has greatly improved juddering issues with this setup in steamvr.

**2.** How do I change vive tracker class to ivrsystem trackeddeviceclass_HMD in openvr?

**3.** Would the provision of a proper openvr driver for osvr hdk display available to download from steam store like the steamvr driver for Hydra greatly improve the chances of steamvr tracked devices being used as intended and to their best potetntial in steamvr with this set up?

Hoping Valve devs still have an OSVR hdk kicking around the office to see why I think current steam-osvr driver could be optimised better for using osvr hdk in openvr.  

Any help or advice is appreciated.

**Comment by Balderick** [comment]
https://github.com/OSVR/SteamVR-OSVR/issues/126

Vive Tracker as head tracker for osvr hdk display works with osvr-vive running osvr apps in osvr runtime.

**Comment by Balderick** [comment]
https://github.com/OSVR/SteamVR-OSVR/issues/126#issuecomment-321877070
Should we be using null_driver to create a proper openvr driver for this type of multi vendor setup?

**Comment by bjj** [comment]
Regarding questions 1 and 3: It would be best to work with the authors of the OSVR driver and their SteamVR plugin to resolve issues you have with OSVR and their native support for the HDK.

Regarding your comment on driver_null:  I think you are combining two different things:  The SteamVR runtime is happy to run without an HMD with requireHmd:false.  Almost no *applications* are going to be happy to run without an HMD.  People who use requireHmd:false to get standalone controller support are typically running custom applications where they only care about position.  Using multiple drivers and getting an HMD from driver_null makes the application happy, but it won't render what you need because the null driver always returns position 0,0,0.  Also, while SteamVR will activate multiple drivers, there is no provision for unifying their coordinate systems.  (The hydra driver actually does that itself internally)

Regarding question 2:  The puck itself declares that it is a controller rather than an HMD.  There is no provision at the moment for overriding this, but if you wanted to execute the click-through license agreement via https://partner.steamgames.com/vrtracking you would have access to documentation which would give you an idea how to modify (via software, but at your own risk) an HTC tracking puck.

HOWEVER, the next question you will have is how to describe the OSVR HDK display and lens system in the puck calibration so that the scene looks correct.  This requires knowing simple facts about the display (resolution, orientation, etc) but it also requires having a calibration to describe the lenses.  I don't have that information.  You would have to get it from the HMD maker.

**Comment by Balderick** [comment]
Thanks for the explanation for why the expected behaviour for when `requireHmd` set to false gives "Not Ready"
I have vive tracker working as hmd in osvr apps in osvr euntime and openvr apps in steamvr runtime using osvr semantic paths.  For osvr semantic paths and to work in steamvr an osvr hdk and a running osvr server is needed.

That is how "requireHmd' can be proven too ignore connected hmds.

What I did to get around the " Not Ready" thing because the connected osvr hdk is being ignored is described at



https://github.com/OSVR/SteamVR-OSVR/issues/126#issuecomment-321939037

**Comment by Balderick** [comment]
Using a different steam account i have installed  SteamVR Tracking HDK and I'll admit i would find it rewarding if i could work out what is described regarding using software to better adapt the vive tracker for being integrated into an hmd, or at least use one openvr driver for both vive tracker and hmd optics as well as hmd display.

I'll use the appropriate support channels for any issues with SteamVR TRacking HDK project so feel we can close this due to the information provided.   Thanks again.

**Comment by Balderick** [comment]
After spending a little bit of time in SteamVR Tracking HDK documentation i can see that the information described in pathto\Steam\steamapps\common\SteamVR Tracking HDK\docs\the_json_file.pdf and https://github.com/OSVR/OSVR-Docs/blob/master/Configuring/projectionAndViewMatrices.md  should help too use HMD Designer GUI with my custom osvrhdkfaceplate-vivetracker head tracker.

Have found FreeCAD provides conversion of osvr-hdk production files for osvr hdk 1.4 which are .stp too .stl in order too appease HMD Designer GUI.

A lot of what i have been reading about over the last year is now starting to make sense, am finding this a very rewarding little project.

**Comment by Balderick** [comment]
> Regarding question 2: The puck itself declares that it is a controller rather than an HMD. 

Referring to the_json_file.pdf in HDK docs it shares how to download the_json_file used to configure vive tracker and its device class is defined as generic_tracker like so [code]{
    "acc_bias": [
        0.09097,
        0.1188,
        -0.3113
    ],
    "acc_scale": [
        1.001,
        0.9989,
        0.9929
    ],
    "device_class": "generic_tracker",
    "device_pid": 8226,
    "device_serial_number": "LHR-0DC2AC5D",
    "device_vid": 10462,
    "gyro_bias": [
        -0.0239,
        0.01872,
        -0.01441
    ],[/code]

Would simply changing device class to hmd make the the vive tracker work as head tracker? and when null driver is called?.


Setting the tracker as camera in unity projects seem to be the way folks are setting vive tracker as head tracker in client side projects. https://www.youtube.com/watch?v=hvrT7FqpPQE   https://github.com/JamesBear/ViveSingleBaseStationTracking

 Not much info available on hardware projects yet for setting vive tracker as head tracker, not that i can find anyhows.

Am having a hard time with requireHmd : false and steamvr wiping my steamvr.vrsettings and other issues with osvr hdk but am really trying to set vive tracker as head tracker with vr apps being renedered to main monitor.    I found the info discussed at https://github.com/JamesBear/ViveSingleBaseStationTracking helped a lot to get steamvr srtarting reliably and vrapps being able to use steamvr tracked devices but the vive tracker works as a controller.

I removed osvr hdk and osvr from the equation for now to simplify things.

**Comment by Balderick** [comment]
This is the ultimate solution for my wants -  i think 

<img width="1306" alt="007capture" src="https://user-images.githubusercontent.com/6255884/29440670-c34578bc-83be-11e7-8b77-e4c7fee20558.PNG">


Are these being manufactured anywhere at all?

**Comment by u-cap** [comment]
This appears to be the Thor's Hammer reference object which is/was provided (and presumably printed) by Synapse to SteamVR Tracking training session attendees. 

Triad Semiconductor has been working on a version of this:
https://twitter.com/reidwender/status/885047945690828801
https://twitter.com/reidwender/status/885557539458494465

It might be worth asking them whether they plan on/will be able to release this on Thingieverse and/or github (as they have done with other work of theirs). I expect it to be designed to work with their HDK hardware.

**Comment by bjj** [comment]
All of the CAD for that object is included with the HDK.  I don't believe there is anyone currently producing the molded plastic parts (Triad is producing only the electronics), so you'd want to look into adapting for 3d printing.

The HDK also includes instructions and tutorials for developing your own shapes (which you could 3d print) which is going to let you build something much better suited to your application.

**Comment by Balderick** [comment]
Building something more specific for what I am trying to do is going too work better.

Still playing about with using vive tracker as head tracker with an osvr hdk.   The vive tracker is connected to hmd by usb as i thought this would make the vive trackers usb dongle redundent.  Which leave the two internal usb ports for controller dongles.

I am stuck on using vive tracker as hmd because of the custom hardware (I suspect and firmware for) as I need to work out how too set USB hid parameters to make it use winIndex 2 and 0xB3.

All the documentation points to non device config solution or  non hardware solutions and describe setting 0xB3 and 0xB4 simultaenously.   I used node.is to adjust settings but they do not stick and need to use unity project to use them or adding scripts to each app that gets used.

Is it possible to set 0xB3 on vive tracker through device config ?
