### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [ValveSoftware/openvr#61]
I would like to point out that an identifier like "[`__OPENVR_API_FLAT_H__`](https://github.com/ValveSoftware/openvr/blob/217ae22879404b61fd8fcbca0109286c6b273537/headers/openvr_capi.h#L8)" [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by JoeLudwig** [comment]
Is there some other file defining __OPENVR_API_FLAT_H__ that we're colliding with? That seems unlikely.

**Comment by stfairy** [comment]
It is unlikely, but is not a good practice.  Names starting with a double underscore is reserved to the language implementation for any use.  http://stackoverflow.com/a/228797/940313

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by zao** [comment]
Please note that elfring is an semiautomated entity who likes wasting valuable developer time on technicalities.
