### ISSUE TITLE
Should IVRSystem::ComputeDistortion provide a different distortion map based on lense position?

### ISSUE THREAD

**Issue by dignakov** [ValveSoftware/openvr#616]
Hi,

I was wondering if the distortion map calculated by IVRSystem::ComputeDistortion should change based on how far apart the lenses are positioned with the knob. Right now I seem to get the same distortion map no matter how far apart the lenses are set.

While this may not introduce much error, would it not be more correct to vary the distortion to be aligned with where the centre of the lens projects onto the screen? Or am I doing something wrong, and just not seeing that openvr does this already . . .

Thanks.

**Comment by Balderick** [comment]
The ipd adjustment just moves the overlap of the two distorted images for each eye from users perspective.  Adjusting ipd does not change distortion map as the screen, nor the rendered images have been adjusted or changed at all.

For steamvr tracked hmd's  lighthouse console can be used to downloadconfig which will show you how your optics, imu, photosensors and display parameters are defined for openvr to calculate distortion.

**Comment by TheDeveloperGuy** [comment]
The values returned by ComputeDistortion() are cached, and so if you want to use a different distortion map (for whatever reason), you need to issue a VREvent_LensDistortionChanged event, which will cause the distortion map to be recalculated. The distortion map is per eye, so doesn't take into account IPD. If you want to do offset from lens center calculations, you'll need to do that yourself (in general most drivers don't).

If you are changing the IPD, you should set the Prop_UserIpdMeters_Float property, which will then notify OpenVR of the IPD change and cause it to do whatever it does in relation to that.

**Comment by dignakov** [comment]
Thanks for your answer.

Basically I was wondering how sensitive the distortion is to the change in lens position w.r.t. the screen, since the IPD knob changes the position of the lens.

Having use the vive for 2 weeks, I see little distortion change as the lenses move, so for all intents and purposes the error seems to be small.
