### ISSUE TITLE
Hello VR example broken - Interface not found VS2015

### ISSUE THREAD

**Issue by khlorghaal** [ValveSoftware/openvr#619]
Making my own app and getting an EVRInitError interface not found.
All EVRApplicationType s passed to VR_Init result in interface not found.
VR_IsRuntimeInstalled()==true
VR_IsHmdPresent()==false

I've tried the HelloVR GL example and it gets the same result. The DX HelloVR wont compile.
Non-development apps work fine.  
Visual Studio 2015, 64 bit build.

Can someone replicate?

**Comment by Harha** [comment]
I haven't bothered building the examples but I'm getting the same issue on my own application. I'm suspecting it might be because I have probably an older SteamVR runtime installed than the OpenVR API expects?

My application at the moment does just this when it comes to OpenVR (I'm very new to OpenVR, this might be incorrect)

`		vr::EVRInitError return_code = vr::VRInitError_None;

		// Init ivr system
		m_ivrSystem = vr::VR_Init(&return_code, vr::VRApplication_Scene);
		if (return_code != vr::VRInitError_None)
		{
			throw std::runtime_error("VREngine::VREngine error! OpenVR initialization failed (ivr system steamvr runtime): " + std::string(vr::VR_GetVRInitErrorAsEnglishDescription(return_code)));
		}

		// Init ivr render models
		m_ivrRenderModels = static_cast<vr::IVRRenderModels *>(vr::VR_GetGenericInterface(vr::IVRRenderModels_Version, &return_code));
		if (!m_ivrRenderModels)
		{
			throw std::runtime_error("VREngine::VREngine error! OpenVR initialization failed (ivr render model interface): " + std::string(vr::VR_GetVRInitErrorAsEnglishDescription(return_code)));
		}`

So at least in some sense I can 'replicate' the issue. I'll investigate this more tomorrow after work...

**Comment by JoeLudwig** [comment]
Does this work if you opt-in to the current SteamVR beta?

We accidentally shipped the SDK a couple days ahead of sending the beta out to everyone. Should be cleaned up tomorrow.

**Comment by Harha** [comment]
@JoeLudwig 

I opted in the beta and tested again. It's working, thanks for the clarification!

**Comment by JoeLudwig** [comment]
Normally that wouldn't be necessary we just jumped the gun a bit with this SDK. If, after tomorrow, you see this problem again with this SDK please let us know.

**Comment by JoeLudwig** [comment]
This should be fixed now: http://steamcommunity.com/games/250820/announcements/detail/1439319410146645956

**Comment by natbro** [comment]
yep, this was my bad - the main/public SteamVR is now updated to be 1.0.10 compatible. sorry for the troubles.

**Comment by khlorghaal** [comment]
Confirmed fixed
