### ISSUE TITLE
What should I do if I want to do one eye a little slower than the other eye?

### ISSUE THREAD

**Issue by nantianliao** [ValveSoftware/openvr#620]
I have a special requirement for the work I do, that is, one eye is rendered slower than the other eye for a few milliseconds or a few frames. I don't know how to do it. If you know, please let me know. Thank you!

**Comment by LoSealL** [comment]
Some artifact? 
- Few milliseconds: hard to do (less than one frame)
- Few frames: easy to do. Remember you can render left/right eye separately, so you can just render right eye and keep the left eye unchanged.

**Comment by nantianliao** [comment]
@LoSealL Thank you for your reply! Could you tell me exactly what I should do if I slowed down a few frames? Thank you very much.

**Comment by LoSealL** [comment]
Why do you want to do this?
Suppose my understanding is the same as yours, you can cache rendered frames, and when you call `virtual EVRCompositorError Submit( EVREye eEye, const Texture_t *pTexture, const VRTextureBounds_t* pBounds = 0, EVRSubmitFlags nSubmitFlags = Submit_Default )` api, use whatever pTexture you want.
