### ISSUE TITLE
SteamVR enabled Direct Mode

### ISSUE THREAD

**Issue by ZiruWang** [ValveSoftware/openvr#621]
Hi, all. 

I want to enable Direct Mode in SteamVR with my HMD. I've check some issues like https://github.com/ValveSoftware/openvr/issues/615 and  https://github.com/ValveSoftware/openvr/issues/431. I did "exactly" the same thing, return VID and PID, whitelist the HMD, set IsDisplayOnDesktop() false and IsDisplayRealDisplay() true, but I can't find Prop_UsesDriverDirectMode_Bool. Instead, I set Prop_HasDriverDirectModeComponent_Bool to false. Is this property removed or being replaced? 

When I open SteamVR, the HMD could only run in extended mode (although it looks fine). So forgive me for asking a stupid question, if I want to implement the "Direct" mode (not the Oculus one) in SteamVR, do I just need to do the things above and whitelist the device to graphic card? Do I miss something or need to create more function instances?

**Comment by TheDeveloperGuy** [comment]
Prop_HasDriverDirectModeComponent_Bool must be set to false for direct mode. It replaces Prop_UsesDriverDirectMode_Bool. Driverdirect mode is also known as "Oculus" direct mode. If you've whitelisted your device and enabled direct mode for it, it should not display anything before you start SteamVR.

**Comment by ZiruWang** [comment]
Hi, TheDeveloperGuy, thanks for replying. 

I believe I have whitelisted my device, adjusting from the method mentioned in https://github.com/ValveSoftware/openvr/issues/200. What do you mean by saying "enabled direct mode for it"? Do I need to enable direct mode before I start SteamVR? Right now the HMD is recognized as an extended monitor when plugged in.

**Comment by Balderick** [comment]
You should provide a software switch for enabling and disabling direct mode.   That software switch could then hooked into steamvr settings gui for disabling and enabling direct mode.

**Comment by TheDeveloperGuy** [comment]
@ZiruWang AFAIK you have to white-list it (ie. register your hardware) with nVidia (or AMD). You can get older driver versions that let you do it via the registry. Also note that AFAIK all mobile (laptop) GPU chipsets are black-listed (ie. even if you have a white-listed HMD they won't allow direct-mode).

**Comment by Balderick** [comment]
You can view which GPUs support vrworks at nvidia website.

**Comment by ZiruWang** [comment]
@Balderick Thanks for the reply. I will add the disabling/enabling direct mode switch after I have the hmd run in direct mode. As for the graphic card, I am using GTX960 with the latest driver. This one should support directmode since I have a HTC VIVE run successfully in direct mode with SteamVR.

**Comment by ZiruWang** [comment]
A new problem appears. Vid is stucked at 0xD222 and Pid is stucked at 0xAA01 after I plugged in HTC VIVE. I can't change them through vr::VRProperties()->SetInt32Property. Does anyone meet this problem before?

**Comment by ZiruWang** [comment]
Finally I found out where the problem is. The EDID should be 0x3328 rather than 0x2833. Thank you all for your time and effort!

**Comment by cjlong1213** [comment]
@ZiruWang I am developing my custom HMD, and I want to enable the feature direct mode in my driver. Can you share more about it? such as the detail steps. By the way, I connect my PC to HMD with DP port (GTX980)not HDMI port, is it OK? Many thanks!

**Comment by aaronleaver** [comment]
hey im having trouble with my steam vr with direct mode n its say extended mode how do i fix it as i got gforce gtx 960 nvidia n its for my ps4 vr
