### ISSUE TITLE
Openvr 1.0.10, VRInitError_Init_InterfaceNotFound

### ISSUE THREAD

**Issue by elect86** [ValveSoftware/openvr#623]
Just update to OpenVR 1.0.10 and keep getting this error in our [jvm binding](https://github.com/kotlin-graphics/openvr)

Tried the opengl sample, same result: `Init_InterfaceNotFound`

The only difference is that the C sample register the `Init_InterfaceNotFound` already [here](https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L3749), at this call in `eError`:

`VRToken() = VR_InitInternal2( &eError, eApplicationType, pStartupInfo );`

Our bindings gets past that, but it gets the same shortly after, [here](https://github.com/kotlin-graphics/openvr/blob/master/src/main/kotlin/openvr/lib/openvr.kt#L2497)

`if (VR_IsInterfaceVersionValid(IVRSystem_Version))`

To notice:
- our call to `VR_InitInternal2` returns `eError` equal `None`... ( `vrToken` is `0`)
- `IVRSystem_Version` is "IVRSystem_017" (tried also the previous 16, nothing changed)
- I modified the c sample and called `VR_IsInterfaceVersionValid( IVRSystem_Version )` anyway, I get the same error `Init_InterfaceNotFound`

ideas?

**Comment by LoSealL** [comment]
Have you updated SteamVR to latest beta?

**Comment by elect86** [comment]
I guess, I tried to quit and re-run, nothing changed

this is what I have

SteamVR Version 2017-07-04 (1499136050)

**Comment by elect86** [comment]
tried on another machine. Same error

**Comment by kisak-valve** [comment]
Hello @elect86, this should be the same issue as https://github.com/ValveSoftware/openvr/issues/619#issuecomment-327029021. Opt into the SteamVR beta until the next stable update ships if you want to use 1.0.10.

**Comment by elect86** [comment]
yep, worked.

Sorry, I missed that issue because I forgot to look into the closed ones... (shall I leave this open until fixed in stable?)

Thanks

Ps: for those who don't know what it means, right click property on SteamVR, http://imgur.com/a/mnwXH

**Comment by JoeLudwig** [comment]
This should be fixed now: http://steamcommunity.com/games/250820/announcements/detail/1439319410146645956
