### ISSUE TITLE
Feature request: Controllers sample driver

### ISSUE THREAD

**Issue by r57zone** [ValveSoftware/openvr#624]
For the HMD, there is a ready-made "driver sample" driver. Would like to see the driver for the controllers, updatable and working on the latest SDK.

Thanks.

**Comment by Balderick** [comment]
I probably have a wrong perspective here but for steamvr tracked devices like the vive controllers so much functionality is set using the device config json which allows things like setting device class to hmd as well as parameters for all other openvr supported arguments.

I.e. the vive controller can be set to hmd device class because its device json contains the info to allow easy switching of device class.

Steamvr is highly optimised for steamvr tracked devices.    Are you asking for a sample to be provided for a non steamvr tracked controller?   Would the steamvr driver for hydra be the sample driver you are looking for?

**Comment by r57zone** [comment]
The hydra sample does not fit, because there's a lot of extra stuff and it's on the old SDK.

**Comment by TheDeveloperGuy** [comment]
@r57zone It would certainly be useful to have a "proper" example for controllers. Unfortunately, it's hard to provide as generally you'd need a working example and that's hard to do for "no hardware" (unlike the HMD examples which either render to a window or a Vive). At this stage the best to use (as a basis for a controller driver) is a modified version of the sample HMD driver (which has an up to date architecture at least), and then use the Hydra controller example as a reference on how to do things like buttons/axes etc. It's not ideal, but that's what there is.

It is a lot of hit and miss though, so it would certainly be *very useful* if Valve at least made the Hydra driver an SDK example and kept it up to date like they do with the HMD examples. I can see why they don't though, as it relies on an external SDK to build and obviously can't do anything without Hydra hardware, so shipping an example that doesn't build or have any function would cause more problems than it would solve... 😕

**Comment by r57zone** [comment]
@TheDeveloperGuy Maybe make move controllers and press the buttons of the controllers using the keyboard. Or make can simply comment these lines.

**Comment by TheDeveloperGuy** [comment]
@r57zone Sure, it is certainly possible to think up examples, even if they are not particularly useful ones. The reality is that there most likely won't be another SDK for a month or so, so you'd have the choice of waiting for a month (assuming Valve read this and made an example for the next SDK), or spending a day integrating the sample HMD driver and your version of the Hydra code. I know which one I'd choose... 😉

**Comment by Balderick** [comment]
Maybe Valve could provide bridging libraries along with a toolset to do everything for you so you don't need to write everything line by line?

Example drivers still do not explain post translation or coordinate methodology?

**Comment by r57zone** [comment]
If someone has updated driver to latest api and Visual Studio 2017 and removed sixtence it was a very cool for DIY VR.

**Comment by r57zone** [comment]
If anyone needs to - https://github.com/r57zone/OpenVR-driver-for-DIY
