### ISSUE TITLE
openvr_capi.h has incorrect struct definitions

### ISSUE THREAD

**Issue by Ralith** [ValveSoftware/openvr#631]
C definitions:
```c
typedef struct VREvent_Keyboard_t
{
	char * cNewInput[8]; //char[8]
	uint64_t uUserValue;
} VREvent_Keyboard_t;

typedef struct VRTextureWithPose_t
{
	struct HmdMatrix34_t mDeviceToAbsoluteTracking;
} VRTextureWithPose_t;
```

C++ definitions:
```c++
struct VREvent_Keyboard_t
{
	char cNewInput[8];	// Up to 11 bytes of new input
	uint64_t uUserValue;	// Possible flags about the new input
};

struct VRTextureWithPose_t : public Texture_t
{
	HmdMatrix34_t mDeviceToAbsoluteTracking; // Actual pose used to render scene textures.
};
```

That's just what I've encountered so far, in addition to the issues discussed in #89. These are frustrating undefined-behavior stumbling blocks when attempting to use OpenVR from anywhere but C++.

**Comment by kisak-valve** [comment]
Closing per "Fixed cNewInput and rchRenderModelComponentName having an incorrect type" in the [v1.0.17](https://github.com/ValveSoftware/openvr/releases/tag/v1.0.17) openvr release.

**Comment by Ralith** [comment]
What a pleasant surprise! Unfortunately, `VRTextureWithPose_t` is still incorrect.
