### ISSUE TITLE
VRSystem::GetEventTypeNameFromEnum is missing the new wireless events

### ISSUE THREAD

**Issue by spayne** [ValveSoftware/openvr#636]
Passing the VREvent_WirelessDisconnect and VREvent_WirelessReconnect value to VRSystem::GetEventTypeNameFromEnum() function in v1.0.10 Win32 returns 
"Unknown EVREventType (112)" and "Unknown EVREventType (113)"

expected the string equivalents. ie:
"VREvent_WirelessDisconnect" and "VREvent_WirelessReconnect"

**Comment by JoeLudwig** [comment]
Thanks. This will be fixed in the next beta update.
