### ISSUE TITLE
GetRawZeroPoseToStandingAbsoluteTrackingPose always returns empty data.

### ISSUE THREAD

**Issue by SteffanDonal** [ValveSoftware/openvr#641]
How can I translate between raw device driver coordinates and the standing tracking space?

**Comment by aleiby** [comment]
Have you run room setup?  You need a valid chaperone setup for this to work as well as have tracking at the time you make the call.  It might be that you are just calling the function before the runtime has determined where you are.

**Comment by SteffanDonal** [comment]
Update:

This method, `System.GetRawZeroPoseToStandingAbsoluteTrackingPose` still returns an empty `HmdMatrix34_t` (0, 0, 0; 1, 0, 0, 0), however I have been able to get the same data by doing:

```csharp
var rawPoses = new TrackedDevicePose_t[OpenVR.k_unMaxTrackedDeviceCount];
var standingPoses = new TrackedDevicePose_t[OpenVR.k_unMaxTrackedDeviceCount];

System.GetDeviceToAbsoluteTrackingPose(ETrackingUniverseOrigin.TrackingUniverseRawAndUncalibrated, 0, rawPoses);
System.GetDeviceToAbsoluteTrackingPose(ETrackingUniverseOrigin.TrackingUniverseStanding, 0, standingPoses);

var rawHmdTransform = new RigidTransform(rawPoses[0].mDeviceToAbsoluteTracking);
var standingHmdTransform = new RigidTransform(standingPoses[0].mDeviceToAbsoluteTracking);
var difference = rawHmdTransform * standingHmdTransform.GetInverse();
```
