### ISSUE TITLE
C# openvr_api.cs immutable string pchResponseBuffer in DriverDebugRequest

### ISSUE THREAD

**Issue by seiferth** [ValveSoftware/openvr#645]
Hi,

I'm trying to make a DriverDebugRequest to a custom driver from Unity, but the pchResponseBuffer where the answer should be written is an immutable string. Unsurprisingly, it doesn't work (and actually crashes the Unity editor). It seems to me, that it should be a System.Text.StringBuilder, as is used in GetStringTrackedDeviceProperty. Can I just change that in openvr_api.cs myself?

Thanks for an answer,
Hagen

Edit:
So I changed the definitions in openvr_api.cs to the following and it seems to work:

	public uint DriverDebugRequest(uint unDeviceIndex,string pchRequest,System.Text.StringBuilder pchResponseBuffer,uint unResponseBufferSize)
	{
		uint result = FnTable.DriverDebugRequest(unDeviceIndex,pchRequest,pchResponseBuffer,unResponseBufferSize);
		return result;
	}

	[UnmanagedFunctionPointer(CallingConvention.StdCall)]
	internal delegate uint _DriverDebugRequest(uint unDeviceIndex, string pchRequest, System.Text.StringBuilder pchResponseBuffer, uint unResponseBufferSize);
	[MarshalAs(UnmanagedType.FunctionPtr)]
	internal _DriverDebugRequest DriverDebugRequest;

**Comment by aleiby** [comment]
This (and several other similar missed parameters) should be fixed in the next SDK.  Thanks!
