### ISSUE TITLE
GetHiddenAreaMesh never gets called

### ISSUE THREAD

**Issue by matrixcr** [ValveSoftware/openvr#649]
I've implemented  IClientTrackedDeviceProvider:: GetHiddenAreaMesh to add hidden area mesh support in my custom steamvr driver, but it turns out that the method was never called no matter I called IVRSystem: :GetHiddenAreaMesh manually or not. I'm using openvr sdk 1.0.5 now. I also tried the latest CVRHiddenAreaHelpers, but no luck.

**Comment by JoeLudwig** [comment]
You should update to a newer SDK. This functionality moved into the server driver a few versions back, and is now accessed via CVRHiddenAreaHelpers. (You don't get called, though. The server driver sets the mesh and remembers what it was set to.)

**Comment by matrixcr** [comment]
Thanks for the reply. 
But I still can't make it work even with porting to the latest OpenVR SDK version. I just put calls to vr::VRHiddenArea()->SetHiddenArea() with hard coded simple triangle and lineloop after hmd device has been added using vr::VRServerDriverHost()->TrackedDeviceAdded in IServerTrackedDeviceProvider::Init() when server driver initialization. Still nothing changed in the render output, and I get zero vertex count and empty mesh from IVRSystem: :GetHiddenAreaMesh.
Anything was wrong or I missed?

**Comment by JoeLudwig** [comment]
Does CVRHiddenAreaHelpers::SetHiddenArea return success?

**Comment by matrixcr** [comment]
I forgot to check the return, actually CVRHiddenAreaHelpers::SetHiddenArea doesn't return success., it returns unknown enum value -858993460.

**Comment by JoeLudwig** [comment]
That number is 0xCCCCCCCC. We had a bug in property writing that's fixed in the latest beta where it would return unitialized memory in the case of "invalid container". Maybe that's what's happening? 

Is it possible that you're calling SetHiddenArea before Activate has been called on the HMD?

**Comment by matrixcr** [comment]
Yes, I think it's possible. How can I make sure SetHiddenArea is called after HMD Activate has been called since the Activate method is called by sdk runtime and I'm not very clear about the timing? I've tried to call SetHiddenArea in HMD Activate, it returns same error. Is there any event to notify HMD activation is done?

**Comment by JoeLudwig** [comment]
The Lighthouse driver calls it from inside the Activate method on the HMD device.

**Comment by matrixcr** [comment]
Thanks a lot! I finally make it work. HMD ComputeDistortion method also need to update for the input floats fU, fV might be not a number after hidden area mesh is applied.
