### ISSUE TITLE
helloworldoverlay sample with Qt

### ISSUE THREAD

**Issue by drayden-lin** [ValveSoftware/openvr#65]
Hi there, I have a couple of questions:

First, I can't seem to get helloworldoverlay sample to work; after trying with Qt, nothing seems to happen when I use the controller. I made sure nothing was showing up behind me either.  I've tried issue #20 and it's still not working for me. Is there any version requirements or anything I'm missing? I've tried this on 0.9.2, 0.9.16 and after.

Second, when I press the system button on the controller while in a steam app, is the menu that shows up the "dashboard"?

Let me know if you need to know anything more specific on my end. Thanks a lot!

**Comment by BoJunHuang** [comment]
Hi @drayden-lin,
The helloworldoverlay sample is a "Dashboard overlay" which would be displayed in the dashboard. You should see a tab with text "SYSTEMOVERLAY" next to the "Steam" tab when you press system button.

**Comment by drayden-lin** [comment]
Hi @BoJunHuang ,

Thanks for the swift reply. As aforementioned, I actually can't even get the dashboard to show up as it isn't responding when I press the system button. Perhaps my environment wasn't set up correctly. Would you mind sharing your steam runtime/openvr version? Maybe I would be able to track down the problem from there.

Thanks again!

**Comment by BoJunHuang** [comment]
Hi @drayden-lin ,
Did you start SteamVR before you run the sample code? For now, the dashboard seems to be started only when SteamVR starts.

**Comment by hanjiang08** [comment]
@drayden-lin I met the same question with you. Do you resolve it and how? Thank you very much!

**Comment by joeWerly** [comment]
@drayden-lin cant make overlay project work...
