### ISSUE TITLE
Support depth buffer for VR overlays

### ISSUE THREAD

**Issue by xiaoguid** [ValveSoftware/openvr#660]
Hello,

Overlays allow high quality UI rendering in VR, but the current openvr implementation does not support depth for overlays.  Oculus supports this in their UE4 implementation (https://docs.unrealengine.com/latest/INT/Platforms/VR/StereoLayers - SupportDepth).

Since it's quite useful to intersect (timewrapped) UIs with the scene depth and as all the information is available to the programmer I think this feature is essential, especially since openvr is continually becoming the only SDK required to support VR on multiple headsets.

Any chance of getting this implemented? If this is made possible I would be able to happily implement all our commercial UIs with overlays, for multiple projects.

Much appreciated!

**Comment by xiaoguid** [comment]
This is now officially supported in Oculus November SDK as depth buffer layers:
https://developer.oculus.com/blog/november-monthly-tech-release-notes/

Can we have this exposed in SteamVR?

**Comment by TheWhiteAmbit** [comment]
+1 this would be very helpfull

**Comment by BenWoodford** [comment]
+1, didn't realise this was here or I would have just +1'd it instead.

**Comment by aleiby** [comment]
The ability to pass depth textures via IVRCompositor::Submit will be in the next SDK update.  Initially, it only pipes the data through to the Oculus SDK to support their new Dash overlay rendering properly.  Eventually, we will make Overlay compositing depth-aware generally.

As for stereo overlays, those have been supported for some time via IVROverlay::SetOverlayFlag with any of the following:
- VROverlayFlags_SideBySide_Parallel
- VROverlayFlags_SideBySide_Crossed 
- VROverlayFlags_StereoPanorama

**Comment by BenWoodford** [comment]
Awesome! Will this also be a default in future updates to the Unity plugin?

**Comment by TheWhiteAmbit** [comment]
@aleiby is there any news on depth compositing of OpenVR-Overlays or is it still only used as a pass through to Oculus SDK only? We are using depth compositing for layers with LibOVR and now OpenVR looks bad compared to LibOVR. In case this will not be implemented soon, we might drop using OpenVR-Overlays and render our own Quads.

**Comment by Peamon** [comment]
@aleiby Why this issue is closed ?
Depth on overlay seem's not to be supported for know.
The goal is to create a pure overlay application to inject depth aware rendering in an other running scene application.

**Comment by rygo6** [comment]
Was this ever implemented in openvr?
