### ISSUE TITLE
SetOverlayRenderModel requires a null pointer which is not supported in openvr_api.cs

### ISSUE THREAD

**Issue by MHDante** [ValveSoftware/openvr#664]
In order to have the render model use the same color as the overlay texture, SetOverlayRenderModel is required to be passed a nullptr (Seen in openvr.h). The ref calling method in openvr_api.cs does not allow this.

**Comment by BenWoodford** [comment]
I haven't had any issue passing a 1,1,1,1 `HmdColor_t` to it when a texture is applied.

But maybe that's why I can only get texture mapped models to work, not ones with vertex colours in the OBJ.
