### ISSUE TITLE
Do a SteamVR Home - SetDefaultApplicationForMimeType

### ISSUE THREAD

**Issue by AlexandreDelan** [ValveSoftware/openvr#666]
Hello,

I working on an application launcher similar to SteamVR Home.

I found a lot of function to do so but I did not succeed to replace SteamVR Home by code.

I try this method without success.
OpenVR.Applications.SetDefaultApplicationForMimeType("myApp", OpenVR.k_pch_MimeType_HomeApp);

I succeed to do so by changing by hand the path of the exe the tools.vrmanifest of the SteamVR Home, but the way to do it is not good enough I think.

My goal is to launch my own SteamVR Home, this one will registered itself thanks to :
OpenVR.Applications.AddApplicationManifest

And then set my app to be the Default VR Home.

This app will then launch application using OpenVR.Applications.LaunchApplication(pchAppKey);

And when the user go to the menu and click on Go Home, it return to my app and not the SteamVR Home.

I success to do all exept replacing the SteamVR Home. Is it a bug? is it implemented? is it possible?

Thank a lot for your help.

**Comment by JoeLudwig** [comment]
We don't currently support replacing SteamVR Home with another home app.
