### ISSUE TITLE
 LoadRenderModel and LoadTexture function call in hellovr_opengl_main.cpp not updated to 0.9.19

### ISSUE THREAD

**Issue by rabtun5555** [ValveSoftware/openvr#67]
When I compile hellovr_opengl project for the first time, the compiler doesn't recognize LoadRenderModel and LoadTexture function calls in CGLRenderModel *CMainApplication::FindOrLoadRenderModel. Looking over the release notes, I noticed you changed the functions to LoadRenderModel_Async and LoadTexture_Async when you commited 0.9.16. I made the changes and the compiler was happy. Can't verify everything else is working because I just started looking into it.

**Comment by rabtun5555** [comment]
Didn't read through the previous issues. This has already been posted.

**Comment by ChristophHaag** [comment]
Nah it's fine, there are already https://github.com/ValveSoftware/openvr/pull/55, https://github.com/ValveSoftware/openvr/pull/60, and https://github.com/ValveSoftware/openvr/pull/62 open and Valve keeps ignoring it. Maybe if they keep receiving email notifications they will finally fix it.
