### ISSUE TITLE
Coordinate systems?

### ISSUE THREAD

**Issue by blitz-research** [ValveSoftware/openvr#675]
What coord system does openvr use?

I've had a look at both the gl and dx12 samples and it seems that coordinate system detection is 'automatic', ie: there is no conversion in either sample or projection matrices etc!

But how does this work? When you first VR_Init(), what coord system is used by default? Is it possible to change the coord system?

I use a dx coord system with gl by building my own projection matrices etc. Will this cause any issues?

Bye,
Mark

**Comment by SpyderTL** [comment]
From my experience, it seems to be Right Handed coordinates.  I had to set my projection matrix up as Right Handed to get it to match up correctly.  Also, the XAudio2 library is Left Handed, so I had to translate everything by Z * -1 to get it to work correctly.

Hope that helps...

**Comment by Balderick** [comment]
You can see openvr coord struct being defined in openvr.h found in the SDK source code.
    
// right-handed system
// +y is up
// +x is to the right
// -z is going away from you
// Distance unit is  meters
struct HmdMatrix34_t
{

**Comment by SpyderTL** [comment]
> // -z is going away from you

That's not terribly helpful.  :)

It should be

> // -z is in front of you, +z is behind you

**Comment by Balderick** [comment]
Valve made the SDK available through github for a reason.    Anybody can provide  or suggest fixes or changes as a Pull Request which Valve devs could merge after reviewing   😁

**Comment by JoeLudwig** [comment]
The next SDK will say "-z is forward".

> Valve made the SDK available through github for a reason. Anybody can provide or suggest fixes or changes as a Pull Request which Valve devs could merge after reviewing 😁

We did, but that's not the reason. The canonical version of openvr.h is a bunch of loose files in Perforce. So taking pull requests on that file (or openvr_driver.h) isn't really an option. We can usually apply the same fix in P4 and it will flow forward from there, though.

**Comment by calvertdw** [comment]
When referencing a "right handed system", one wants to hold their right hand up to visualize. Pointing your index finger at yourself while doing that seems like the most awful way to describe that. How about this. Using your right hand, no matter where it is pointing, the coordinate frame is:

Thumb: +Y
Index: +Z
Middle: +X

So then, you could give the default orientation of that frame relative to your eyes would be such that your index finger is pointing toward your face and you thumb pointing up.
