### ISSUE TITLE
Help! HMD screen turn to RED at EXTEND mode

### ISSUE THREAD

**Issue by cjlong1213** [ValveSoftware/openvr#676]
I'm developing my custom HMD at EXTEND mode, everything is ok but When I accidentally drag a window from primary screen to the extended screen(HMD), the HMD screen turns red. Does anyone encounter the same problem? How to avoid this situation?

**Comment by dashingstag** [comment]
From what I experienced, there is no way to stop the red screen from appearing if you choose to drag a window over the extended screen. From what I gather, it is an intended effect that the compositor does not render when there is another window in the foreground where the compositor is.

The manual workaround is to click the red screen with your mouse.

A programmatic workaround I can think of is to have an additional tool to detect if "Headset window" is in the foreground, if not bring it to the foreground and simulate a click to make it the foreground window.

**Comment by cjlong1213** [comment]
@dashingstag Thanks.

**Comment by sols000** [comment]
Anyone solved this issue? help!
