### ISSUE TITLE
[IDEA] Receive screen space depth maps from scene applications

### ISSUE THREAD

**Issue by BenWoodford** [ValveSoftware/openvr#682]
Why? Because then overlays could be depth-sensitive. If they go behind a wall in the scene then they’d actually be behind the wall. The compositor would simply need to depth test the overlay pixels against the depth map and see whether it should draw them or not.

By default, overlays should have a new flag of “AlwaysOnTop” set to true, or “DepthSensitive” as false, so not break existing behaviour.

Likewise, overlay render models could then be depth sensitive too

**Comment by xiaoguid** [comment]
Already an open issue: #660

**Comment by kisak-valve** [comment]
Closing in favor of the existing feature request.
