### ISSUE TITLE
Allow configuring the standby timeout

### ISSUE THREAD

**Issue by glopesdev** [ValveSoftware/openvr#685]
Currently the timeout is less than half a minute. This makes it impossible to develop certain apps that require the user to sit still for a certain period of time. The timeout is simply too low.

Also for simple debugging it is extremely frustrating to have to constantly jog the headset around so it resumes rendering.

Please allow configuring this timeout, or disabling it altogether, at least for developer mode.

**Comment by JoeLudwig** [comment]
The default timeout is supposed to be 5 seconds. Maybe something's wrong?

In any case you can set this to up to 10 minutes in the Power settings in the dashboard. Just put on the HMD and hit the system button on your controller.

**Comment by glopesdev** [comment]
@JoeLudwig I don't know how I missed this menu! I was using the SteamVR settings panel to configure all of the device settings, but I never realized that there were settings you can only reach through the dashboard. Thanks a lot, this will be enough for our needs.

**Comment by JoeLudwig** [comment]
>  I never realized that there were settings you can only reach through the dashboard.

Fixing that is on the list. :)
