### ISSUE TITLE
1.0.11 missing string conversions

### ISSUE THREAD

**Issue by spayne** [ValveSoftware/openvr#692]
1.0.11 introduced a few new enum values, but some of the enum to string utility functions were not updated.

1. VRSystem()->GetEventTypeNameFromEnum(e) is missing convertors for the section setting events:
 VREvent_SteamVRSectionSettingChanged
 VREvent_LighthouseSectionSettingChanged
 VREvent_NullSectionSettingChanged
 VREvent_UserInterfaceSectionSettingChanged
 VREvent_NotificationsSectionSettingChanged
 VREvent_KeyboardSectionSettingChanged
 VREvent_PerfSectionSettingChanged
 VREvent_DashboardSectionSettingChanged

2. VR_GetVRInitErrorAsSymbol is missing a convertor for: VRInitError_Init_USBServiceBusy

**Comment by aleiby** [comment]
Added, thanks!
