### ISSUE TITLE
我如何用staramVR模拟掉落

### ISSUE THREAD

**Issue by taxingmu** [ValveSoftware/openvr#693]
类似于高空救猫，人物不慎掉下

(Rough translation: How do I simulate falling with SteamVR? Similar to the high-altitude rescue cats, people accidentally fell)

**Comment by TheWhiteAmbit** [comment]
rough translation: this is not a bug-report or an issue!

**Comment by TTimo** [comment]
Agreed - sorry @taxingmu this is not a development forum. Please report bugs and issues only here.
