### ISSUE TITLE
Retreiving default head pos?

### ISSUE THREAD

**Issue by blitz-research** [ValveSoftware/openvr#694]
Hi,

Is there a way to get the 'default' head position, so I can make sure the player's head is placed in the correct position relative to vehicles etc?

Also, what does IVRSystem::ResetSeatedZeroPose() do exactly? Seems to have no effect here...

Bye!
Mark

**Comment by echuber2** [comment]
You would use ResetSeatedZeroPose() to calibrate the user's head position (as they are seated and currently facing) to be the origin position and forward direction (-Z), assuming you make subsequent calls to GetDeviceToAbsoluteTrackingPose with the TrackingUniverseSeated argument flag.

https://github.com/ValveSoftware/openvr/wiki/IVRSystem::ResetSeatedZeroPose
https://github.com/ValveSoftware/openvr/wiki/IVRSystem::GetDeviceToAbsoluteTrackingPose

Note that if you use GDTATP, you need to implement the correct prediction calculation yourself as described in the article. HOWEVER there are extra details not covered there. Please read the following thread in detail: #518 

When using GDTATP you still need to use WaitGetPoses each frame to make sure the HMD is updated.

You could instead rely on the poses from WGP relative to the play space as usual and implement your own zeroing calibration, adding an extra transformation matrix to make the user's calibrated head position the origin, and transforming the scene contents relative to that for as long as the seated gameplay continues.

**Comment by blitz-research** [comment]
Ok, thanks.

I am currently using WaitGetPoses and my own calibration logic and it works
fine, but is there any drawback to do it this way? For example, will
tracking be 'predicted' using WGP the way it can be with GDTATP? Just
asking as WGP has no cool sounding 'secondsToPhotons' param. It is all
currently very smooth regardless.

**Comment by echuber2** [comment]
WGP handles prediction for you automatically. If you're doing your own calibration to get a stationary zero for the head when seated, then it's probably fine. When I used this previously, I did it the manual way with the seated flag, but in that case I was also trying to manipulate the prediction anyhow. You could put this question on the Steam developer forums to see what others did in your situation.

**Comment by echuber2** [comment]
Something I haven't tried, is this function: https://github.com/ValveSoftware/openvr/wiki/IVRSystem::GetSeatedZeroPoseToStandingAbsoluteTrackingPose
It might allow you to use the current WGP pose and coordinate with the zero set by ResetSeatedZeroPose as well, but I haven't tried it.

**Comment by blitz-research** [comment]
Thanks a heap, that gives me lots to play with for now!

**Comment by blitz-research** [comment]
Actually, turns out VRCompositor().SetTrackingSpace( TrackingUniverseSeated
) solves all our problems here!

This sets the coord system used by WaitGetPoses to 'seated', so HMD
defaults to 0,0,0 when users head is in 'default' position and I just need
to offset it to local 'cockpit' position.

**Comment by echuber2** [comment]
I see, I'm glad there's a simpler solution. I'll do that if I ever have to implement something like this again.
