### ISSUE TITLE
CAPI header was broken in 1.0.11

### ISSUE THREAD

**Issue by burito** [ValveSoftware/openvr#697]
Fix provided https://github.com/ValveSoftware/openvr/pull/695

**Comment by bddckr** [comment]
Already fixed by #687 and probably even others. This repo seems pretty dead.

**Comment by burito** [comment]
I think it's more SteamVR is pretty dead regarding bug fixing in general. The amount of times I've made it crash just by simply initialising it...

**Comment by kisak-valve** [comment]
There's no benefit in creating issue reports pointing to pull requests. Closing in favor of #687.

**Comment by burito** [comment]
I think there is a benefit, as you just shipped a version with the bug that these PR's fix.

**Comment by burito** [comment]
Yeah pretty sure there is a benefit, you just shipped a new version with the same bug, should I message with more gusto?

**Comment by bddckr** [comment]
@burito All they said is an *issue* is unnecessary since they prefer to have one thing for anything. Since there's already a PR for it there's no need for this issue. Note that said PR is still open, so they didn't close it and think it's actually done.

**Comment by burito** [comment]
I just checked the new release, 1.0.12, still not fixed :-/

**Comment by bddckr** [comment]
That's probably why the PR is still open.
