### ISSUE TITLE
sample hellovr_opengl errata

### ISSUE THREAD

**Issue by burito** [ValveSoftware/openvr#698]
hellovr_opengl incorrectly calls glDisableVertexAttribArray() without a bound Vertex Array, this will cause a GL_INVALID_OPERATION.

Fix provided https://github.com/ValveSoftware/openvr/pull/696

**Comment by kisak-valve** [comment]
Hello @burito, there's no need for a separate issue report to go with a pull request. Closing as a duplicate of #696.
