### ISSUE TITLE
glBegin(GL_LINES) doesn't align properly

### ISSUE THREAD

**Issue by ElegantToast** [ValveSoftware/openvr#699]
I've been trying to get this one to work, and it just doesn't.  Maybe this isn't supported?

I'm trying to draw lines centered around the handset (using **glBegin(GL_LINES)**), but the transformation doesn't come out right in my own project (It renders, and it's clearly based on the handset location, but it's scaled wrong).  I added some test code to the **hellovr_opengl** project.  The project itself uses a shader to draw the axis lines.  As far as I can tell, the code below ought to make the same axis lines the shader does, but doesn't draw anything at all.

I added this to the project code (just after the part that draws the axis lines with the shader), and it doesn't render.

```
                glUseProgram(0);


		const Matrix4 & mat = m_rmat4DevicePose[m_pHMD->GetTrackedDeviceIndexForControllerRole(vr::ETrackedControllerRole::TrackedControllerRole_RightHand)];
		const Matrix4 & matVP = GetCurrentViewProjectionMatrix(nEye);

		Matrix4& matT = matVP * mat;

		Vector4 center = matT * Vector4(0, 0, 0, 1);

		for (int i = 0; i < 3; ++i)
		{
                       glBegin(GL_LINES);
			Vector3 color(0, 0, 0);
			Vector4 point(0, 0, 0, 1);
			point[i] += 0.05f;  // offset in X, Y, Z
			color[i] = 1.0;  // R, G, B
			point = matT * point;
			

			glColor4f(color.x, color.y, color.z, 1.0f);
			glVertex3f(center.x, center.y, center.z);
			glVertex3f(point.x, point.y, point.z);
                        glEnd();
		}
		
		
```

**Comment by ElegantToast** [comment]
I'm ok with it if I've just screwed up my matrices somewhere, I just want to make sure this basic capability is supported.

**Comment by echuber2** [comment]
In the first place, I'm not sure if you can use the legacy immediate mode commands as they aren't modern OpenGL (that means no glBegin, glEnd, glVertex, etc.).

But more importantly, you shouldn't be using these calls right here, as it's most likely being erased in a buffer clear shortly thereafter. If you study hellovr, you'll see it buffers some lines into a VAO in DrawControllers, but those aren't actually drawn until later: RenderStereoTargets calls RenderScene for each eye, and RenderScene draws the lines. RenderStereoTargets is making sure everything gets drawn to a framebuffer, as these are what ultimately gets sent to each eye with Submit() calls in RenderFrame.

**Comment by ElegantToast** [comment]
Ok, that makes sense.  Thank you.
