### ISSUE TITLE
C++ reference type should not appear in C API ovenvr_capi.h

### ISSUE THREAD

**Issue by cmbruns** [ValveSoftware/openvr#701]
In OpenVR version 1.0.11 in the file `openvr_capi.h` there is a C++ reference type in the signature of `SetOverlayDualAnalogTransform()`. I don't think you can do that in C.

     `EVROverlayError (OPENVR_FNTABLE_CALLTYPE *SetOverlayDualAnalogTransform)(VROverlayHandle_t ulOverlay, EDualAnalogWhich eWhich, struct HmdVector2_t & vCenter, float fRadius);`

The type `HmdVector2_t &` is a C++ reference type.

https://github.com/ValveSoftware/openvr/blob/167e26e4b9b352614c5f3a83a8434b185f63ed0f/headers/openvr_capi.h#L1905

**Comment by kisak-valve** [comment]
Hello @cmbruns, this issue is already being tracked at #687. Closing as a duplicate.
