### ISSUE TITLE
Shifting lens center

### ISSUE THREAD

**Issue by dashingstag** [ValveSoftware/openvr#703]
What is the proper way to shift lens center?

Adjusting vr::Prop_LensCenterLeftU_Float/vr::Prop_LensCenterLeftV_Float/vr::Prop_LensCenterRightU_Float/vr::Prop_LensCenterRightV_Float seems to have no effect.

I can shift using GetEyeOutputViewport to shift the pixels of the buffer, but that causes an overlap of the eye buffers.(causes the right eye to be seen in the left eye)

Ipd adjusts the distance ingame but it does not affect the lens center

The hmd scene looks right when I shift the right buffer to the left and the left buffer to the right

Is there another way to do it?

**Comment by JoeLudwig** [comment]
This is something you would do in your distortion function, which is defined by ComputeDistortion, or in the projection, which is defined by GetProjectionRaw.
