### ISSUE TITLE
SteamVR Beta OpenVR Driver problem

### ISSUE THREAD

**Issue by pottedmeat7** [ValveSoftware/openvr#704]
Any insight into why OpenVR drivers, with SDK 1.0.9, no longer work with SteamVR beta?
Confirmed not working with OpenVR 1.0.9, SteamVR Beta and Windows 10.

**Comment by JoeLudwig** [comment]
See my reply over on the Steam forums: http://steamcommunity.com/app/358720/discussions/0/1620600279664613668/
