### ISSUE TITLE
Building a 64-bit static library with OpenVR forces x86

### ISSUE THREAD

**Issue by JoshKlint** [ValveSoftware/openvr#710]
I am compiling a 64-bit C++ static library that includes the OpenVR headers. When I try to load this static lib from another C++ project I get an error complaining that the library contains x86 functions. Here is part of the output from dumpbin.exe:
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64>dumpbin.exe Leadwerks.lib /headers
Microsoft (R) COFF/PE Dumper Version 14.00.24225.1
Copyright (C) Microsoft Corporation.  All rights reserved.

Dump of file Leadwerks.lib

File Type: LIBRARY

  Version      : 0
  Machine      : 14C (x86)
  TimeDateStamp: 5A26152F Mon Dec  4 20:40:31 2017
  SizeOfData   : 00000024
  DLL name     : openvr_api.dll
  Symbol name  : _VR_ShutdownInternal
  Type         : code
  Name type    : no prefix
  Hint         : 21
  Name         : VR_ShutdownInternal
```
I have no idea why the DLL information is showing up inside the static library, but somehow Visual Studio is detecting this DLL and making the function x86, even though the library is being built in x64 mode.

**Comment by JoeLudwig** [comment]
We have a bunch of 64 bit apps using openvr_api.dll (but possibly not a bunch of static libs.)

Are you sure you're linking against the 64 bit link library (aka lib/win64/openvr_api.lib) and not the 32 bit link library (aka lib/win32/openvr_api.lib)?

**Comment by JoshKlint** [comment]
That's the thing...if I replace the x86 static lib with the x64 one it compiles correctly, but how the heck is a static lib linking at all? There are no linker settings in a static library configuration, and I have no idea how VS even thinks it is supposed to link anything.

**Comment by JoshKlint** [comment]
Eh, I am dumb...this was the ONE lib I dragged into the code explorer. 👯‍♂️
