### ISSUE TITLE
Driver TriggerHapticPulse with IVRDriverInput in version 1.0.12

### ISSUE THREAD

**Issue by zodsoft** [ValveSoftware/openvr#711]
Driver IVRControllerComponent  was removed in version 1.0.12.
How to Trigger Haptic with IVRDriverInput?

[https://github.com/ValveSoftware/openvr/wiki/IVRDriverInput-Overview](url)
**`EVRInputError CreateHapticComponent( PropertyContainerHandle_t ulContainer, const char *pchName, VRInputComponentHandle_t *pHandle )`**
After CreateHapticComponent，how to receive Haptic Event From application level?

**Comment by bddckr** [comment]
Read the release notes:
>>>
* Replaced the haptic API into drivers with an events. Drivers will receive an event of type VREvent_Input_HapticVibration which uses the hapticVibration member of the data until to specify parameters.

**Comment by JoeLudwig** [comment]
@zodsoft I added a similar note to the API documentation so it's more clear. Thanks for the report.
