### ISSUE TITLE
VRApplication_Background no longer receives buttonpress events in latest SteamVR beta after steam button press

### ISSUE THREAD

**Issue by GimpMaster** [ValveSoftware/openvr#715]
I've been running a background application for a long time and the January 5th SteamVR release no longer sends button press events to the background Application AFTER a steam button is pressed. We have Steam Dashboard disabled and we "enable system menu button" i.e.

"sendSystemButtonToAllApps" : true,

in steamvr.vrsettings

Fortunately there is a beta "openvr-input-temporary" that still works. However some of the latest beta versions have it broken as well. INCLUDING 

SteamVR Beta Updated (1515701852)
Vive:
Fixed issue with the system button on Vive controllers.

Anyone else seeing this problem?

Also the only way to fix it and get regular buttons to come back to background application is to restart SteamVR

**Comment by GimpMaster** [comment]
Is anyone else seeing this issue? @JoeLudwig

**Comment by GimpMaster** [comment]
@JoeLudwig 
Just tired the latest beta steamvr released today. Still broken unfortunately. You don't even need to run an app.

Just follow these steps:

1. Disable VR Dashboard in developer settings.
2. Press the system menu button.
3. Controller no longer works and most of the time disappears.
4. Only way to fix is to restart SteamVR and enable VR dashboard.

**Comment by Brekel** [comment]
Same thing here so it seems.

**Comment by GimpMaster** [comment]
Glad to hear I'm not the only one. This causes lots of problems in VR Arcades where the steam dashboard is disabled.. @alexvalve @jeffmvalve @VivekValve @EricS-Valve

**Comment by JoeLudwig** [comment]
The latest beta includes a fix that would have prevented all input after the first system button press. I think that'll fix your issue, but if it doesn't, please let me know and we can reopen.

http://steamcommunity.com/games/250820/announcements/detail/1656630338902191258

**Comment by GimpMaster** [comment]
Thank you @JoeLudwig !!!

I can confirm that it works.......most of the time. I pretty much always get the system menu button RELEASE, but only half the time do I get a button PRESS. 

Also overlay input still doesn't work. I don't see the laser beam.

I am using vr::VROverlay()->SetOverlayInputMethod(mOverlayHandle, vr::VROverlayInputMethod_Mouse);

For the past year it has been working just fine. However it still doesn't show mouse input when I: 

vr::VROverlay()->SetOverlayTexture(mOverlayHandle, &texture);

**Comment by GimpMaster** [comment]
@JoeLudwig 

If you want you can email me directly joshua.hintze@gmail.com and I can send you a simple sample Qt Application that exhibits the problem.

Thanks!

**Comment by GimpMaster** [comment]
@JoeLudwig Any more thoughts on this? Like I said I can provide sample code that shows the issue.

**Comment by dwaldrum** [comment]
We are using the "sendSystemButtonToAllApps": true in order to provide a custom overlay for a VR arcade. Unfortunately we ran into the same issue as here in regards to all input stopping after pressing the system button.

We've tried the new beta, and although the bug is fixed, as GimpMaster said, we are now also receiving sporadic system button events.

**Comment by JoeLudwig** [comment]
@dwaldrum Still? The beta update on Saturday included the fix for that bug and I'm getting reliable system button events now.

**Comment by GimpMaster** [comment]
@JoeLudwig  I did not see the Saturday release. I'll try it out tonight and give you my feedback. Thanks!

**Comment by GimpMaster** [comment]
@JoeLudwig  New beta works great!!!  I just have this one last issue #740 and then our arcades will be back to pre-January update regressions. Thank you so much!

**Comment by dwaldrum** [comment]
I'm still getting intermittent system key presses. It seems to be a lot better, but even with the latest beta I have to press the system key 2-3 times sometimes in order to register the key being down.

**Comment by manxjason** [comment]
Can this issue be re-opened - also seeing this problem.

**Comment by ksloan** [comment]
Also seeing this on latest beta — please reopen.
