### ISSUE TITLE
Overlay app fails on specific laptop

### ISSUE THREAD

**Issue by httc805155** [ValveSoftware/openvr#718]
I have built the "helloworldoverlay" by my own.

The building tool is QT 5.9 MSVC2015 64bit.
It can runs on runs on many computers, but fail on the laptop: MSI GS73VR.

The error occurs at "vr::VROverlay()->SetOverlayTexture" and get the return error 24: "Invalid Texture".
The program can run and shows the tab, but the overlay cannot be rendered on screen.

Any help would be appreciated, thanks !

**Comment by kisak-valve** [comment]
Hello @httc805155, I suspect what is going on here is that this is an Optimus laptop and the internal display is attached to the Intel gpu while the HMD is getting attached to the nVidia chipset and you're seeing a similar scenario to the issue in #556.

**Comment by httc805155** [comment]
@kisak-valve
Thanks, this is the actual reason !

The method I solved is using the method provided by NVIDIA:
https://docs.nvidia.com/gameworks/content/technologies/desktop/optimus.htm

**Comment by kisak-valve** [comment]
Thanks for testing. Closing in favor of the existing issue report at #556.
