### ISSUE TITLE
VRInputError_InvalidParam from IVRDriverInput

### ISSUE THREAD

**Issue by gb2111** [ValveSoftware/openvr#720]
Hi,
I am always getting VRInputError_InvalidParam from CreateScalar/Boolean Component.
However I am still getting handle.
I got System button working. But I cannot get trigger working. It works in Steam menu but not in games.
I observed that there is /input/trigger/touch Boolean Component but even if I set it trigger don't work.
Thanks,
Greg

**Comment by gb2111** [comment]
#719

**Comment by TheDeveloperGuy** [comment]
@gb2111 Did you sort this out with '/input/trigger/value'?

**Comment by gb2111** [comment]
no. i was hooking WritePropertyBatch. after i removed hook i am not getting error any more.

**Comment by TheDeveloperGuy** [comment]
@gb2111 I've resolved everything (including haptic) except for JSON input profile. I seem to have lost @JoeLudwig 's attention, so going nowhere on that one. Maybe that doesn't work anyway. Did you manage to get any result from JSON? I can't get any messages in the log (with correct or incorrect JSON path) and nothing I do there seems to make any difference (which is good, I guess, everything works without it, so not sure what the point of it is anyway).

**Comment by TheDeveloperGuy** [comment]
@gb2111 All resolved, you can probably close this.

**Comment by gb2111** [comment]
yes. that can be closed now. thanks.
