### ISSUE TITLE
SteamVR Dashboard doesn't work with XBox controller

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#721]
Some time in the last month or so, XBox controller support in SteamVR (Home & Dashboard) was completely broken. What doesn't work:

- Opening/closing Dashboard with "Nexus" button
- Navigating in Dashboard with Joystick (sounds like it's working, but no visual indication given)

**Comment by JoeLudwig** [comment]
A fix for the dashboard is in progress.  Is Home also broken?

**Comment by TheDeveloperGuy** [comment]
@JoeLudwig Yes, Home has been broken for as long as I can remember (with XBox controller). Dashboard is more recent.

**Comment by TheDeveloperGuy** [comment]
Fixed in recent releases.
