### ISSUE TITLE
Juttering with my  IVRDriverDirectModeComponent direct mode driver

### ISSUE THREAD

**Issue by matrixcr** [ValveSoftware/openvr#722]
Rendering by vrcompositor works well on the same machine with same SteamVR Home scene, but my  implementation of IVRDriverDirectModeComponent causes consistent juttering in the HMD. From the the frame timing, the New Poses Ready and WaitGetPoses events are fluctuating synchronously. It seems that WaitGetPoses doesn't wait correctly until runing start.  Could anybody tell me what I most probably does wrong with the interfaces. Any comment is highly appreciated, thanks.

![image](https://user-images.githubusercontent.com/4946788/34978680-ff4a6c54-fad9-11e7-8396-dda537a5e15d.png)

**Comment by matrixcr** [comment]
Did i miss any kind of synchronization in SubmitLayer or Present method?
Is there anything I need to take care in the IVRDriverDirectModeComponent implementation related to asynchronous reprojection, interleave reprojection? 
It's supposed that the pose input of SubmitLayer method is predicted to midpoint when the frame is scanned out, will the implementation of IVRDriverDirectModeComponent affect the pose prediction?

**Comment by TheDeveloperGuy** [comment]
Virtually impossible to say without either the source code or a very detailed description of what you are doing. Implementing IVRDriverDirectModeComponent is very complicated and completely undocumented (except for "This component is used for drivers that implement direct mode entirely on their own without allowing the VR Compositor to own the window/device. Chances are you don't need to implement this component in your driver.").

**Comment by matrixcr** [comment]
Thanks TheDeveloperGuy! Let me have the questions specific step by step. 

1. What is the mechanism vrcompositor uses to detect the frame missing? Is any interface of IVRDriverDirectModeComponent involved the interaction? And how?

2. What's the correct way to deal with the syncTexture passed into Present method? Besides acquiring the mutex, do we need to map it to place a cpu-gpu sync point? or copy 1 pixels from the submitted textures to it?

Following is the pseudo code of my implementation.  
void Present(vr::SharedTextureHandle_t syncTexture)
{
        RenderContext *p = GetRenderContext();

	if (p->swapTextureSets.syncTextureHandle != syncTexture)
	{ 
		p->swapTextureSets.syncTextureHandle = syncTexture;
		SAFE_RELEASE(p->swapTextureSets.syncTexture);

		if (syncTexture)
		{
			p->dev->OpenSharedResource((HANDLE)syncTexture, __uuidof(ID3D11Texture2D), (void **)&(p->swapTextureSets.syncTexture));
		}
	}

	IDXGIKeyedMutex *syncMutex = NULL;
	if (p->swapTextureSets.syncTexture != NULL &&
		SUCCEEDED(p->swapTextureSets.syncTexture->QueryInterface(__uuidof(IDXGIKeyedMutex), (void **)&syncMutex)))
	{
		if (syncMutex->AcquireSync(0, 14) != S_OK)
		{
			syncMutex->Release();
			return;
		}
	}

	//if (p->swapTextureSets.syncTexture)
	//{
	//	D3D11_MAPPED_SUBRESOURCE mapped = { 0 };
	//	if (SUCCEEDED(p->context->Map(p->swapTextureSets.syncTexture, 0, D3D11_MAP_READ, 0, &mapped)))
	//	{
	//		p->context->Unmap(p->swapTextureSets.syncTexture, 0);
	//	}
	//}

       // This will update a swap texture set queue of length 3, which a reprojection correction thread use priority gpu context to present in the hmd. and block if the queue is full on waiting repojection thread to consume. 
        SendPresentCommandDx11(&p->swapTextureSets);

	if (syncMutex)
	{
		syncMutex->ReleaseSync(0);
		syncMutex->Release();
	}
}

**Comment by matrixcr** [comment]
Should I flush the commands and spin query until gpu finishes the work in Present method?

**Comment by TheDeveloperGuy** [comment]
Going from the comments in my code (was a long time ago that I implemented this), it seems you should do a flush after you've drawn the textures or you will get tied to the refresh rate of your primary monitor.

**Comment by matrixcr** [comment]
I eventually fixed the juttering by flushing the vrcompositor d3d submissions and removing the hmd vsync notification, nevertheless I'm not quite clear why it works.
