### ISSUE TITLE
Emulating other devices using the new input interface

### ISSUE THREAD

**Issue by petethor** [ValveSoftware/openvr#723]
With 1.0.12 the input interface has changed. I've been emulating buttons on other devices (especially the axis and touch) but this is no longer possible (e.g. TrackedDeviceAxisUpdated() no longer exists). 

Is there a short- and long term solution to this that we can expect? 

Thanks for a great hw/sw suite.

**Comment by bddckr** [comment]
`IVRDriverInput`: https://github.com/ValveSoftware/openvr/wiki/IVRDriverInput-Overview

#719 is very interesting and helpful probably.

**Comment by TheDeveloperGuy** [comment]
My recommendation is to build against the 1.0.11 SDK and forget about this new input interface for now. It's a mess, and dealing with it is going to cause you a lot of frustration. Eventually you'll have to use the newer interface, but as it doesn't work properly right now, you're better off waiting until they've fixed it and documented it properly...

**Comment by TheDeveloperGuy** [comment]
In fact, as the older interface is still supported in the latest runtimes (and probably will be for at least the next year). I'm going to port some of the headers from the old SDK to the new one, so that the driver can be built with the new SDK (for other new features) but not have to deal with this 'half baked' input solution. I'll post a topic on here once I have done that.

**Comment by petethor** [comment]
@bddckr thanks i did not see it until now. 
@TheDeveloperGuy I see, ill halt this activity then. Well the code I had running before clearly does not work with the new runtime. Ill have to revert to old setups I guess. I will await and see what you come up with.

**Comment by TheDeveloperGuy** [comment]
#724

**Comment by petethor** [comment]
@TheDeveloperGuy thanks for the information, that reply and the discussions resolved this for now.
