### ISSUE TITLE
opengl:oculus sdk 0.8 + dk2 = vr::VRCompositor()->Submit return error

### ISSUE THREAD

**Issue by ravarcade** [ValveSoftware/openvr#73]
I try to run hellovr_opengl. (after changing LoadRenderModel to LoadRenderModel_Async).
My config: Win 8.1 pro, oculus DK2, sdk 0.8, gfx intel iris 6100 (driver: 20.19.15.4404), ovr 9.1.19, SteamVR(beta) 1459383055.
I got no image on hmd display (black screen).

I checked where it fails: in hellovr_opengl_main.cpp lines: 677, 679:
 vr::VRCompositor()->Submit(..) it return error 102 = VRCompositorError_InvalidTexture

SteamVR works fine for me.

I tested also Oculus SDK 0.8 demos: OculusRoomTiny (DX11) works fine, but OculusRoomTiny (GL) fails is similiary place: ovr_CreateSwapTextureSetGL(hmd, GL_SRGB8_ALPHA8, size.w, size.h, &TextureSet) return error -3000 = ovrError_Initialize.

I searched littlebit. Oculus in Direct Mode don't allow to use own final textures. They must be created with ovr_CreateSwapTextureSetGL. I don't see something similiary in ovr.

I'm not sure if it fail only on my computer (and intel gfx).

I try to update to oculus home 1.3 but it fails to detect my DK2 (on support pages they only say that integrated gfx cards are not supported).

---- update ---
It is only Intel opengl drivers fault.
I tested on desktop with old geforce GT 550 Ti.
It works wind oculus home 1.3 and and beta sdk 0.8. 
Sdk 0.8 is faster than "home 1.3". On home 1.3 i have a lot of stuttering. On Sdk 0.8 hellovr is smooth.

Problem solved.

**Comment by ravarcade** [comment]
It is only Intel opengl drivers fault.
I tested on desktop with old geforce GT 550 Ti.
It works wind oculus home 1.3 and and beta sdk 0.8. 
Sdk 0.8 is faster than "home 1.3".  On home 1.3 i have a lot of stuttering. On Sdk 0.8 hellovr is smooth.

**Comment by TheWhiteAmbit** [comment]
So why not closing it when solved?

**Comment by ravarcade** [comment]
Git is new for me. I did not notice "Close" button.
