### ISSUE TITLE
Unity app crashes randomly if GetNativeTexturePtr is not called before SetOverlayTexture

### ISSUE THREAD

**Issue by tewiscky** [ValveSoftware/openvr#742]
I use Unity 2017.3.0f3 and OVRLay (https://github.com/benotter/OVRLay) for testing program.

In the original code of OVRLay, GetNativeTexturePtr is called every time before SetOverlayTexture.

```
void Update() {
    // Call GetNativeTexturePtr every time before SetOverlayTexture.
    texture_t = new Texture_t();
    texture_t.handle = overlayTexture.GetNativeTexturePtr();
    texture_t.eType = ETextureType.DirectX;
    texture_t.eColorSpace = EColorSpace.Auto;
    OpenVR.Overlay.SetOverlayTexture(overlay.overlayHandle, ref texture_t);
}
```

However, if GetNativeTexturePtr is called only at initialization time, the program will crash randomly.
(Suggested by Unity document
https://docs.unity3d.com/ScriptReference/Texture.GetNativeTexturePtr.html)

```
void Start() {
    // Call GetNativeTexturePtr only at initialization time because the native texture pointer will not change.
    texture_t = new Texture_t();
    texture_t.handle = overlayTexture.GetNativeTexturePtr();
    texture_t.eType = ETextureType.DirectX;
    texture_t.eColorSpace = EColorSpace.Auto;
}

void Update() {
    // Call SetOverlayTexture directly. It will crash.
    OpenVR.Overlay.SetOverlayTexture(overlay.overlayHandle, ref texture_t);
}
```

testing projects:
[Crash.zip](https://github.com/ValveSoftware/openvr/files/1723079/Crash.zip)
[Original version.zip](https://github.com/ValveSoftware/openvr/files/1723080/Original.version.zip)

**Comment by bddckr** [comment]
Have you debug printed the native pointer?

I think you're better off asking in Unity support channels, rather than on the OpenVR repo.

**Comment by tewiscky** [comment]
@bddckr I printed the return value of GetNativeTexturePtr every time before SetOverlayTexture.
The pointer doesn't change until release, but if GetNativeTexturePtr is not called just before SetOverlayTexture, the program will crash.
I also tried to call GetNativeTexturePtr before SetOverlayTexture and ignore the returned value. It will not crash.

```
void Update() {
    overlayTexture.GetNativeTexturePtr();
    OpenVR.Overlay.SetOverlayTexture(overlay.overlayHandle, ref texture_t);
}
```

According to Unity document (https://docs.unity3d.com/ScriptReference/Texture.GetNativeTexturePtr.html), GetNativeTexturePtr will synchronize with the rendering thread.
I wonder if this is related? There is no relative documentation for details.

**Comment by borishsu** [comment]
Got the same question here. @tewiscky did you find the answer? Thanks!

**Comment by tewiscky** [comment]
> Got the same question here. @tewiscky did you find the answer? Thanks!

Unity enables Multithreaded Rendering by default.
https://unity3d.com/learn/tutorials/topics/best-practices/multithreaded-rendering-graphics-jobs

In my environment, Multithreaded Rendering is enabled. SetOverlayTexture() is called from main thread but the native texture must be access from render thread.
If not, the app will crash.
You can use Singlethreaded Rendering or GL.IssuePluginEvent() to solve this problem.

https://docs.unity3d.com/ScriptReference/GL.IssuePluginEvent.html
https://docs.unity3d.com/Manual/NativePluginInterface.html

**Comment by Cliwo** [comment]
> > Got the same question here. @tewiscky did you find the answer? Thanks!
> 
> Unity enables Multithreaded Rendering by default.
> https://unity3d.com/learn/tutorials/topics/best-practices/multithreaded-rendering-graphics-jobs
> 
> In my environment, Multithreaded Rendering is enabled. SetOverlayTexture() is called from main thread but the native texture must be accessed from render thread.
> If not, the app will crash.
> You can use Singlethreaded Rendering or GL.IssuePluginEvent() to solve this problem.
> 
> https://docs.unity3d.com/ScriptReference/GL.IssuePluginEvent.html
> https://docs.unity3d.com/Manual/NativePluginInterface.html

Hi I'm experiencing random crash in my App because of the GetNativeTexturePtr().
And I found your comment. I just applied Singlethreaded rendering and there is no more random crash.
I wonder where did you get your information.
'Native texture must be accessed from render thread' <- where I can find this information? or did you learned this with yourself?

Anyway, I really appreciate you. Thank you for the comment!

**Comment by tewiscky** [comment]
> > > Got the same question here. @tewiscky did you find the answer? Thanks!
> > 
> > 
> > Unity enables Multithreaded Rendering by default.
> > https://unity3d.com/learn/tutorials/topics/best-practices/multithreaded-rendering-graphics-jobs
> > In my environment, Multithreaded Rendering is enabled. SetOverlayTexture() is called from main thread but the native texture must be accessed from render thread.
> > If not, the app will crash.
> > You can use Singlethreaded Rendering or GL.IssuePluginEvent() to solve this problem.
> > https://docs.unity3d.com/ScriptReference/GL.IssuePluginEvent.html
> > https://docs.unity3d.com/Manual/NativePluginInterface.html
> 
> Hi I'm experiencing random crash in my App because of the GetNativeTexturePtr().
> And I found your comment. I just applied Singlethreaded rendering and there is no more random crash.
> I wonder where did you get your information.
> 'Native texture must be accessed from render thread' <- where I can find this information? or did you learned this with yourself?
> 
> Anyway, I really appreciate you. Thank you for the comment!

https://docs.unity3d.com/ScriptReference/GL.IssuePluginEvent.html

> When multithreaded rendering is used, the rendering API commands happen on a thread which is completely separate from the one that runs the scripts. Consequently, it is not possible for your plugin to start rendering immediately, **since it might interfere with what the render thread is doing at the time.**

In multithreaded rendering, when SetOverlayTexture() is called from main thread, the native texture is accessed by openvr. However if the texture is also used by Unity render thread at the same time, it will cause crash.

In singlethreaded rendering, rendering is done by main thread so that it will not interfere the rendering when SetOverlayTexture() is called.
Singlethread rendering is also OK but it might have lower FPS.

> This is suboptimal, because all commands you execute on the main thread subtract from important frametime which you could use for other subsystems running on the main thread.
