### ISSUE TITLE
IVRDriverDirectModeComponent.SubmitLayer

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#745]
@jeremyselan In latest SDK release notes, change to IVRDriverDirectModeComponent.SubmitLayer is cited, but no details given. Are depth textures to be used for depth precision? Any more info available?

**Comment by LoSealL** [comment]
Track this issue, also want this information.
What I found in Oculus Reference:

> Depth texture for positional timewarp.
Must map 1:1 to the ColorTexture.

**Comment by TheDeveloperGuy** [comment]
It seems like it may be possible to just ignore the depth textures with the new API, but without knowing anything about what the intention of those are, I'm hesitant to release a driver based on the new OpenVR SDK.

**Comment by TheDeveloperGuy** [comment]
Still waiting. Can't release a driver based on this SDK without the information. Can someone at least answer whether these can be ignored if the driver doesn't know how to use them?

**Comment by TheDeveloperGuy** [comment]
How about we document changes to driver interfaces before releasing new SDK versions? Still waiting...

**Comment by TheDeveloperGuy** [comment]
@JoeLudwig @aleiby It's been 2 months since this issue was opened. I assume someone at Valve knows what the intention behind changing this interface was, and how it is supposed to be used. Please address this!

**Comment by TheDeveloperGuy** [comment]
According to @natbro this is "depth data can be passed by applications such that when it goes through to the Oculus/OVR driver it can participate in their “Oculus Desktop” where controllers and panels take advantage of depth.", and can be ignored if you are not doing composition where you need this.
