### ISSUE TITLE
IVRDriverInput path '/input/system/click' no longer working with Dashboard

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#746]
Up until recently setting the boolean component of IVRDriverInput path '/input/system/click' would open/close SteamVR Dashboard. This is no longer working (nor can Dashboard be opened/closed with XBox controller 'system' button). Is this a bug, or is there another input path that should be used? Same behaviour on latest release and beta.

**Comment by TheDeveloperGuy** [comment]
Was result of changes to default input mapping. Specifying input mapping fixes issue. XBox controller issue still remains.

**Comment by JoeLudwig** [comment]
Which Xbox controller issues are those?  With the Steam Client Beta, and either build of SteamVR, Xbox controller support should be fixed.

**Comment by TheDeveloperGuy** [comment]
Guide (system) button isn't working to open/close dashboard. If you get dashboard up another way, XBox seems to be working inside there.

**Comment by TheDeveloperGuy** [comment]
Seems like the system button is mapped to the "back" button on XBox 360 instead of the "guide" (XBox) button now. So, "back" can be used to open/close dashboard. I don't know if this is expected behaviour.

**Comment by JoeLudwig** [comment]
That is expected behavior. We can't use the guide button on certain headsets.

Once the new binding system is available you'll be able to move it to guide for yourself if you're not on one of those headsets.
