### ISSUE TITLE
macOS: Format of textures allocated in IVRDriverDirectModeComponent::CreateSwapTextureSet?

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#749]
On Windows the following code is used to create a shared handle to a newly allocated texture:

		// Get IDXGIResource interface
		IDXGIResource* pOtherResource;
		texture->QueryInterface(__uuidof(IDXGIResource), (void**)&pOtherResource);

		// Get shared handle for texture
		HANDLE sharedHandle;
		pOtherResource->GetSharedHandle(&sharedHandle);

What format is the allocated texture? How does one get a shared handle to the allocated texture? What is the unFormat parametere to CreateSwapTextureSet on macOS? Is IVRDriverDirectModeComponent even supported on macOS? The only information I have on this is "We're not super inclined to ensure IVRDriverDirectModeComponent"

**Comment by natbro** [comment]
yep, no `IVRDriverDirectModeComponent` will come to macOS or Linux unless `IVRVirtualDisplay` is found to be completely lacking. the consumption of `IVRDriverDirectModeComponent` is entangled in Win32-specific code and concepts.

**Comment by TheDeveloperGuy** [comment]
@natbro Thanks for the clarification.
