### ISSUE TITLE
Mac OS X

### ISSUE THREAD

**Issue by Aruna-Sree** [ValveSoftware/openvr#759]
is this supports Mac OS X? If yes, then please give us steps to intigrate in Mac application.

**Comment by soswow** [comment]
@OskarGroth "This invite link is no longer active."

**Comment by OskarGroth** [comment]
@soswow Updated link:
https://join.slack.com/t/applevr/shared_invite/enQtMzcxMjkzOTExNTg2LTBiMWQ3MDIzYmRkZmU4YmM5MTA3NGM3NDlhN2E2ZjQ5NTU4NDlkMTBhZDUxMjVhYmI2MmQxMmI2YWM5YzljMjg
