### ISSUE TITLE
Can't disable SteamVR_LaserPointer once it's been added to a controller

### ISSUE THREAD

**Issue by david-jarman** [ValveSoftware/openvr#766]
Using SteamVR plugin with Unity3D (2017.3.1f1)

I have code that performs a raycast from the controller to detect if a menu is being pointed at. If the controller is pointed at a menu, then I want the laser pointer to turn on. 

The is that once the laser pointer has been added as a component to the controller, I can't get the laser to go away. I tried disabling the component, setting active to false, and even removing the component doesn't disable the laser from being rendered.

**Comment by bddckr** [comment]
The Unity plugin moved. It's now available here:
https://github.com/ValveSoftware/steamvr_unity_plugin

I suggest to close this issue and open a new one over there! :)

**Comment by david-jarman** [comment]
Thanks for the heads up!
