### ISSUE TITLE
HelloWorldOverlay.exe can not run

### ISSUE THREAD

**Issue by Zeyuan-Ma** [ValveSoftware/openvr#773]
![qq 20180411194937](https://user-images.githubusercontent.com/32922213/38614933-80aa28e6-3dc1-11e8-8c09-aa57d7947992.jpg)

![qq 20180411195035](https://user-images.githubusercontent.com/32922213/38614994-adb35cea-3dc1-11e8-9271-d6a375408bd7.jpg)
it means the procedure enter point "......" can not be located in the dynamic link library: D:\openvr-master\samples\bin\win64\helloworldoverlay.exe

After building in qt 5.6 64bit when I go to run the exe file it gives me this error. Has anyone else run into this as well?

Any help would be appreciated, thanks !

**Comment by JoeLudwig** [comment]
You might need to set your working directory to something with the QT DLLs in it before running. There is a copy of them in samples/bin/win32, which is where the helloworldoverlay sample should build into.

**Comment by Zeyuan-Ma** [comment]
Actually, i have already build helloworldoverlay into samples/bin/win64, and may working direction is openvr-master\samples\bin\win64. But it still gives  me this error.

**Comment by Zeyuan-Ma** [comment]
I changed my QT DLL version to 5.3. And it runs. Howerer, it also has a problem:
![qq 20180412170447](https://user-images.githubusercontent.com/32922213/38667393-e2d946a2-3e73-11e8-8576-bdc1ad268584.jpg)
Has anyone  else met this problem?
Thanks!

**Comment by JoeLudwig** [comment]
Try cleaning and rebuilding the sample after changing to 5.3. That looks like a debug/release problem or maybe a Qt interface change to me.

**Comment by Zeyuan-Ma** [comment]
After changing to 5.3, i generated all the project from CMake. 
And i found  `std::string sKey = std::string("sample.") + m_strName.toStdString();` has problem; So i changed it.
Now helloworldoverlay run correctly. But it only shows a console and doesn't continue and nothing happen.
@JoeLudwig Do you meet this problem? And which version of vs and QT you use? Thanks!

**Comment by Zeyuan-Ma** [comment]
After changing to 5.3, i generated all the project from CMake.
And i found std::string sKey = std::string("sample.") + m_strName.toStdString(); has problem; And i changed it.
Now helloworldoverlay runs well. 
@JoeLudwig Thanks!
