### ISSUE TITLE
How to exit standby for driver

### ISSUE THREAD

**Issue by peroht** [ValveSoftware/openvr#774]
After my device driver has been "placed" in standby how do I tell the system that the device is no longer in standby? Sending button press events etc still works after my device has been placed in standby, they are happily received by the system. However it does not really "wake" up the device and my implementation of LeaveStandby() is not fired. 

I've looked into VendorSpecificEvent() and EVREventType but it seems that many of those are ourside of reserved range.

I also do seem to get ShouldBlockStandbyMode() to hinder this.

Using openvr 1.0.13.

Update:
Im also setting Prop_NeverTracked_Bool to true but does not seem to have an effect.

**Comment by TheDeveloperGuy** [comment]
Your device gets put into standby when it gives poses that don't change (eg. it's sitting on a table). To bring it out of standby start giving poses that change (ie. move it).

**Comment by peroht** [comment]
Tahnks for the comment. My use case is a device that never changes it pose, it is always static on the ground. Using TrackedDevicePoseUpdate() with the same (static) pose does not make the driver leave standby.

**Comment by TheDeveloperGuy** [comment]
Do this instead:

vr::VRProperties()->SetBoolProperty(m_ulPropertyContainer, vr::Prop_NeverTracked_Bool, true);

**Comment by JoeLudwig** [comment]
@peroht It sounds like your device does have a pose, so Prop_NeverTracked_Bool isn't appropriate. (And that property doesn't affect standby in any case. It just keeps the status window icon from blinking.)

The fact that updating boolean component (or sending button presses) doesn't wake a device from standby is a bug. I'll get that fixed and out in a beta update later today.

Does this device actually have inputs, or is it just a static thing that has a pose? Maybe we should add a property you can set that means "don't put this device into standby in the first place"?

**Comment by JoeLudwig** [comment]
This beta update should fix the bug with boolean components not reviving a controller that's in Standby: https://steamcommunity.com/games/250820/announcements/detail/1658889742644238659

**Comment by SteffanDonal** [comment]
@JoeLudwig I would very much like such a flag!

**Comment by peroht** [comment]
> It sounds like your device does have a pose, so Prop_NeverTracked_Bool isn't appropriate. (And that property doesn't affect standby in any case. It just keeps the status window icon from blinking.)
@JoeLudwig thanks for the information on that property.

> The fact that updating boolean component (or sending button presses) doesn't wake a device from standby is a bug. I'll get that fixed and out in a beta update later today.

Excellent work.

> Does this device actually have inputs, or is it just a static thing that has a pose? Maybe we should add a property you can set that means "don't put this device into standby in the first place"?

Yes, the device (Omnideck 360 degree motorized treadmill) has got inputs that can be used to e.g. drive games equipped with locomotion scheme built for the Vive. It has a pose e.g. when mounted on a vibration platform.

And yes, it would be handy with a property to hinder standby, which is the reason i started fideling with this.

**Comment by 18128381510** [comment]
在GetPose()函数内pose.qRotation和pose.vecPosition长时间未更新时steamvr会将驱动设置为standby模式，退出standby模式的方法是更新pose.qRotation或pose.vecPosition的值！
