### ISSUE TITLE
DX11: Calling CreateDeviceContextState() causes access violations on Submit().

### ISSUE THREAD

**Issue by LibreVR** [ValveSoftware/openvr#78]
Calling [`CreateDeviceContextState()`](https://msdn.microsoft.com/en-us/library/windows/desktop/hh404583%28v=vs.85%29.aspx) within any DX11.1 application will cause it to support both DX10 and DX11 interfaces on all objects.

OpenVR seems to work with the assumption that DX11 applications will never return DX10 interfaces, this assumption is incorrect. Thereby causing access violations when calling `Submit()`.

This can easily be reproduced with any DX11.1 application by adding this snippet of code after creating the device:

```
ID3D11Device1* Device1;
Device->QueryInterface(&Device1);
D3D_FEATURE_LEVEL level = Device->GetFeatureLevel();
ID3DDeviceContextState* state;
hr = Device1->CreateDeviceContextState(0, &level, 1, D3D11_SDK_VERSION, __uuidof(ID3D11Device1), nullptr, &state);
Release(Device1);
```

Now the application will crash on the next call to `Submit()` or any other function that forces OpenVR to interact with DX11 objects, which it now incorrectly assumes are DX10 objects. An easy fix would be to prefer the DX11 interfaces above the DX10 interfaces.

**Comment by LibreVR** [comment]
@JoeLudwig I think this should be a high priority bug within OpenVR, it's a pretty big oversight.

**Comment by TheWhiteAmbit** [comment]
have you tried getting an DXGI interface of the correct DX-API as workaround?

**Comment by TheWhiteAmbit** [comment]
https://msdn.microsoft.com/de-de/library/windows/desktop/ff476531(v=vs.85).aspx

**Comment by aleiby** [comment]
Good catch!  This will be fixed in the next beta.

**Comment by LibreVR** [comment]
Thanks for fixing the crash, the application now works.

However while the crash has been fixed, it looks like OpenVR still handles this case incorrectly. Every frame I submit I get the following warnings from DirectX:

```
D3D11 WARNING: ID3D10Device::CopyResource: This ID3D10Device[1] method of the immediate context is locked out because an ID3D11Device[1] device context state is active. [ STATE_SETTING WARNING #3145945: DEVICE_LOCKEDOUT_INTERFACE]
D3D11 WARNING: ID3D10Device::CopySubresourceRegion: This ID3D10Device[1] method of the immediate context is locked out because an ID3D11Device[1] device context state is active. [ STATE_SETTING WARNING #3145945: DEVICE_LOCKEDOUT_INTERFACE]
D3D11 WARNING: ID3D10Device::CopyResource: This ID3D10Device[1] method of the immediate context is locked out because an ID3D11Device[1] device context state is active. [ STATE_SETTING WARNING #3145945: DEVICE_LOCKEDOUT_INTERFACE]
D3D11 WARNING: ID3D10Device::CopySubresourceRegion: This ID3D10Device[1] method of the immediate context is locked out because an ID3D11Device[1] device context state is active. [ STATE_SETTING WARNING #3145945: DEVICE_LOCKEDOUT_INTERFACE]
D3D11 WARNING: ID3D10Device::Flush: This ID3D10Device[1] method of the immediate context is locked out because an ID3D11Device[1] device context state is active. [ STATE_SETTING WARNING #3145945: DEVICE_LOCKEDOUT_INTERFACE]
```

It looks like OpenVR still uses the `ID3D10Device` interface for DX11 applications.

**Comment by LibreVR** [comment]
@aleiby I just double-checked, this is also a problem when using the Vive Driver. Should I make a new issue or can we just reopen this one as it is closely related?

**Comment by LibreVR** [comment]
@aleiby This exact issue has returned in the beta. Still works correctly in the stable version of SteamVR.

**Comment by aleiby** [comment]
A fix for this is included in this new build:
http://steamcommunity.com/games/250820/announcements/detail/522809610149317693

Let me know if you are still having issues.

**Comment by aleiby** [comment]
Also, re: the warnings..

When applications use CreateDeviceContextState, OpenVR doesn't know if it should use the DX10 interfaces or the DX11 interfaces, so it tries both and assumes one of them will succeed.  DX doesn't provide errors in this case, but the debug runtime will still spam warnings.  I'm not aware of anything I can do about that though.

**Comment by LibreVR** [comment]
@aleiby It works fine again, thanks.

I did have some trouble switching back to the SteamVR beta, something about missing files. Solved it by reinstalling SteamVR, but it's something to keep in mind if there are any other reports like it.
