### ISSUE TITLE
OpenVR program crashes on SetOverlayTexture

### ISSUE THREAD

**Issue by rathdrummer** [ValveSoftware/openvr#787]
I have implemented a C++ system on a Linux machine which streams video to an Overlay with successive images. I managed to get it working with SetOverlayRaw for each frame, but on my HTC Vive there is latency between frames in which the entire overlay disappears - I'm told this is to be expected for SetOverlayRaw.

So I'm trying to make an OpenGL texture, to pass to SetOverlayTexture. 
I only have the one overlay in my program. There are no visual issues with the chaperone or anything else. Here's a simplified version of my code; the image I get from nextImageToDisplay is a proper BGR image.

    cv::Mat image = nextImageToDisplay();

    // Convert OpenCV Mat to OpenGL texture
    unsigned int textureID;

    glGenTextures(1, &textureID);  
    glBindTexture(GL_TEXTURE_2D, textureID);

    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
 
    // Create the texture
    glTexImage2D(GL_TEXTURE_2D,     // Type of texture
                 0,                 // Pyramid level (for mip-mapping) - 0 is the top level
                 GL_RGBA8,          // Internal colour format to convert to
                 image->cols,       // Image width
                 image->rows,       // Image height
                 0,                 // Border width in pixels 
                 GL_BGR,            // Input image format
                 GL_UNSIGNED_BYTE,  // Image data type
                 image->ptr());     // The image data
    

    // Submit texture
    if( textureID != 0 ){
        vr::Texture_t texture = {(void*)(uintptr_t)textureID, vr::TextureType_OpenGL, vr::ColorSpace_Linear };
        pOverlay_->SetOverlayTexture(*pOverlayHandle_,&texture);
    } else {error_("Null texture");}

Whenever a valid image goes through, the entire program crashes on SetOverlayTexture; it's not returning an overlay error struct and it's not throwing any exceptions for me to catch. After several weeks stuck on this, trying every solution I find online with no success, I'm submitting this as an issue. Any help would be greatly appreciated.

**Comment by rathdrummer** [comment]
I'll close this issue, mistake on my part; I forgot to create an OpenGL context before handling textures. In the end I made the basic window in the [1st OpenGL tutorial page](http://www.opengl-tutorial.org/beginners-tutorials/tutorial-1-opening-a-window/), and once it was made the textures just worked.

**Comment by nguyenha1121** [comment]
Hi @rathdrummer i''m new in openvr overlay can u share your code to display a opencv image stream to vr overlay? Thank you!

**Comment by rathdrummer** [comment]
Hi @nguyenha1121 , the key was to make an OpenGL context in my situation. Take a look at the [tutorial I linked](http://www.opengl-tutorial.org/beginners-tutorials/tutorial-1-opening-a-window/) for a general case, what I did was create an OpenGL window:
I can't share all of my code online but I can show you the gist of it to answer your question.

In my initialization method I created the OGL context:

~~~~
bool MyProgramClass::Init(){

  /* Other, program-specific initialization code goes here */


  glewExperimental = true; // Needed for core profile
  if( !glfwInit() ) // Creation of OGL context
  {
    e("Failed to initialize GLFW");
    return false;
  }

  window = glfwCreateWindow(1024,768,"MY_VIVE_PROGRAM",NULL,NULL);
  if (window == NULL){
    e("Failed to open GLFW window");
    glfwTerminate();
    return false;
  }

  glfwMakeContextCurrent(window);
  glewExperimental=GL_TRUE; // Needed in core profile
  
  GLenum err = glewInit();
  if (err != GLEW_OK) {
    e("Failed to initialize GLEW "+std::to_string(err));
    return false;
  }
  
  // Here you generate the texture you'll use for setting the overlay.
  // textureID can be an unsigned int field from your main class (MyProgramClass)
  glGenTextures(1, &textureID);

  return true;
}

~~~~

Then when you're updating the image, call code similar to the one I put in my first post in this thread, but LEAVE OUT the `glGenTextures(1, &textureID)` part; if you leave that in you'll be generating a new texture every time you update the image, essentially a huge memory leak.

Now when you start your program a blank window will appear on your desktop. You can program it to disappear if you don't want it, or maybe use it for some kind of interface or feedback.

I did this on Linux Ubuntu, it took me a while to install all the required dependencies but keep at it and you'll manage.
Also this only works if you're using OpenGL textures like me, depending on your project you might want to use a different graphics context!

**Comment by nguyenha1121** [comment]
Thank you @rathdrummer i done with sdl window but what type overlay you use for this ? in my case i want to set a stream video to overlay take entire vr screen can you suggest me ?
