### ISSUE TITLE
VREvent_Input_HapticVibration  Event  can not get The correct TrackedDeviceIndex_t

### ISSUE THREAD

**Issue by ranruiyuan** [ValveSoftware/openvr#792]
In openvr 1.0.13.
I have called vr::VRDriverInput()->CreateHapticComponent(...)
Then, I called vr::VRServerDriverHost()->PollNextEvent()   Fillter event type using  VREvent_Input_HapticVibration in a thread,Aftar The Game Querry a series of HapticPulse,
I Can get the  correct VREvent_t..data.hapticVibration, But I Get the Wrong VREvent_t.trackedDeviceIndex. it was allways -1 .How can I get the Correct trackedDeviceIndex.

**Comment by TheDeveloperGuy** [comment]
When you create the haptic component you get a handle for it. By checking the haptic event's containerHandle and componentHandle you can determine which controller instance the event is for.

**Comment by ranruiyuan** [comment]
vr::VRServerDriverHost()->PollNextEvent  Returns nothing about containerHandle ,How Can I Get it
in the Thread loop.
