### ISSUE TITLE
Custom driver failing to load (VRInitError_Init_FileNotFound(103))

### ISSUE THREAD

**Issue by walrus** [ValveSoftware/openvr#799]
I've been working on an OpenVR driver, and when running SteamVR it's failing to load with the following error (from [vrserver.txt](https://github.com/ValveSoftware/openvr/files/2016690/vrserver.txt)):

```
Unable to load driver tg0driver from C:\Users\daniel\Documents\openvr-driver\tg0driver\bin\win64\driver_tg0driver.dll.
Unable to load driver tg0driver because of error VRInitError_Init_FileNotFound(103). Skipping
```

This looks quite like issue #121. I've used [Dependency Walker](http://www.dependencywalker.com/) to check the dependencies and none seem to be missing ([depends_driver_tg0.txt](https://github.com/ValveSoftware/openvr/files/2016674/depends_driver_tg0.txt)).

Likewise, the folder name and `vrpathreg` entry seem to match:

```
C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win64>vrpathreg
Runtime path = C:\Program Files (x86)\Steam\steamapps\common\SteamVR\
Config path = C:/Program Files (x86)/Steam/steamapps/common/SteamVR
Log path = C:\Program Files (x86)\Steam\logs
External Drivers:
        C:\Users\daniel\Documents\openvr-driver\tg0driver\
```

```
C:\Users\daniel\Documents\openvr-driver\tg0driver\bin\win64>dir
 Volume in drive C is Windows
 Volume Serial Number is 8273-E957

 Directory of C:\Users\daniel\Documents\openvr-driver\tg0driver\bin\win64

18/05/2018  11:14    <DIR>          .
18/05/2018  11:14    <DIR>          ..
17/05/2018  14:58           164,468 depends.chm
17/05/2018  14:58            12,288 depends.dll
17/05/2018  14:58           566,272 depends.exe
18/05/2018  11:12            37,470 depends_driver_tg0.txt
18/05/2018  09:41            81,920 driver_tg0driver.dll
18/05/2018  09:41             1,932 driver_tg0driver.lib
27/04/2018  14:34             6,606 openvr_api.lib
               7 File(s)        870,956 bytes
               2 Dir(s)  19,880,054,784 bytes free
```

Given the above, my current thinking is that it's a 32/64 bit issue but the dll is definitely compiled for a 64 bit platform and all of the dependencies seem to be too. Do I need to recompile for 32 bit or something?

**Comment by walrus** [comment]
More digging has revealed that the issue appears to be caused by the logging code, which I borrowed from the sample driver at `https://github.com/ValveSoftware/openvr/blob/master/samples/driver_sample/driverlog.h` and `https://github.com/ValveSoftware/openvr/blob/master/samples/driver_sample/driverlog.cpp`

I'm still not sure what exactly the cause is, but it's only when I attempt to instantiate `DriverLog` that it breaks.

**Comment by TheDeveloperGuy** [comment]
Looks like you're probably missing the debug MS DLLs in your path. Try building in release mode.

**Comment by walrus** [comment]
Thanks; I already thought of this and switched to release mode though.

**Comment by TheDeveloperGuy** [comment]
Well, you're missing a DLL, that's what's causing this. It's a dependency you've added, as I'm sure if you build the sample driver it will load just fine.

**Comment by walrus** [comment]
Apologies; that post was before I spotted that I was building in debug mode and switched. I would post an updated one, but having come back to this after the bank holiday weekend the issue seems to have resolved itself. :| I'm not sure how, but there we are. Thank you for your help.

**Comment by xDShot** [comment]
Any clues how can workaround this?
