### ISSUE TITLE
Skipping driver because it is not an HMD

### ISSUE THREAD

**Issue by betavr** [ValveSoftware/openvr#80]
I tried to interface SteamVR with the Razer Hydra, but unfortunately it looks like this isn't possible, because only hmd drivers are supported.

So, my question is, Is this something by design? Do you allow other controllers than the Vive motion controllers to be interfaced with SteamVR?

**Comment by TheWhiteAmbit** [comment]
you could write an own OpenVR driver, mapping to the vive or DK2 for HMD but controllers from Razer Hydra, but I guess it wont be easy

**Comment by betavr** [comment]
It wouldn't be too hard if Valve opened up the Oculus driver's source code... 

In the meantime I'm going to try to add controller support in the steamvr-osvr driver, which is open source fortunately.

**Comment by bjj** [comment]
If you set "activateMultipleDrivers": true in the "steamvr" section of the settings the system will activate all the controllers from all drivers after it picks one driver with the HMD to be the main driver.

We don't yet have built-in support for unifying the coordinate systems of the different drivers.

If you have a Hydra and want to get it working with some HMD, and you have the expertise necessary to write an openvr driver for it, contact me at benj at valvesoftware dot com.

**Comment by betavr** [comment]
Thank you, it works with activateMultipleDrivers together with the oculus driver!
