### ISSUE TITLE
Frequent firing of VREvent_SceneApplicationChanged when HMD is in standby

### ISSUE THREAD

**Issue by peroht** [ValveSoftware/openvr#806]
I am wondering about the lifecycle of steamvr and expecially `EVREventType::VREvent_SceneApplicationChanged`. If having no game running (being in the home screen) it seems like it gets fired twice every 1.5 s or so. What is the reason for this behavior?

When mirroring the display one can see that it switches between showing the home screen and a "loading bar". I guess there is nothing wrong with this and most users wont mirror the display - it just feels that it is "esthetically" bad to switch back and forth leading to users (me including) believing that there is something wrong. Maybe this is to save on CPU/GPU computing power?

Or more likely this is maybe a heartbeat call for the system? Then maybe it should be renamed to more clearly specify so.

**Comment by peroht** [comment]
No interest shown. Closing.

**Comment by BOLL7708** [comment]
Saw this just because you closed it. I think it's SteamVR Home that does this, I stopped using it because seeing that flash up and down in the mirror window was annoying. I think it went in and out of idle continually. It can be disabled in the SteamVR settings.
