### ISSUE TITLE
How do you bind IVRDriverInput Components that don't match existing input component paths?

### ISSUE THREAD

**Issue by walrus** [ValveSoftware/openvr#808]
If I want my custom driver to bind to, say, the `/input/trigger` path I can do the following in my profile JSON file:

```
"/input/trigger" : {
        "type" : "trigger",
        "binding_image_point" : [ 41, 64 ],
        "order" : 1
    },
```
And then this in my driver.cpp:
```
vr::VRDriverInput()->CreateScalarComponent(propertyContainer, "/input/trigger/value", &triggerHandle, vr::EVRScalarType::VRScalarType_Absolute, vr::EVRScalarUnits::VRScalarUnits_NormalizedOneSided);
```
So far, so good. However, in #724 @JoeLudwig says that this only applies to the 'standard buttons', and that for other components the following rules apply:

> Any axis with type k_eControllerAxis_Trackpad will be mapped to /input/trackpad/... (x, y, click, touch) for the first one and trackpad1, trackpad2, etc. for additional trackpads.
Any axis with type k_eControllerAxis_Joystick will be mapped to /input/joystick/... (x, y, click, touch) for the first one and joystick1, joystick2, etc. for additional joysticks.
Any axis with type k_eControllerAxis_Trigger will be mapped to /input/trigger/... (value, click, touch) for the first one and trigger1, trigger2, etc. for additional joysticks.

If I instead want to create a joystick at `/input/axis3/` (so I can match the input components that Knuckles seem to use), how can I do this (for both normal and legacy input profiles)? I've tried a bunch of different things but I only seem to be able to receive input when using the 'standard buttons'. I feel like this would be much easier to debug if the binding UI allowed you to see which components, and their values, a driver had.

**Comment by metainf** [comment]
If you want to see the binding UI debugging outputs, go to the Developer tab in the desktop steamVR settings, and enable debugging options in the input binding user interface. Then in the binding interface, edit any bindings, and there should be a `input debugger` button that lets you see the components and values of a driver.

**Comment by walrus** [comment]
Yeah, I worked around the issue (just set different component paths and used the binding UI to hook them up to the desired actions) and forgot I'd posted this.
