### ISSUE TITLE
IVROverlay::CreateOverlay crashing without Error

### ISSUE THREAD

**Issue by TheWhiteAmbit** [ValveSoftware/openvr#81]
sometimes a call to IVROverlay::CreateOverlay just lets the whole application hang. There is no EVROverlayError code, since the method does not return at all.

https://github.com/ValveSoftware/openvr/wiki/IVROverlay::CreateOverlay

**Comment by JoeLudwig** [comment]
Is the compositor up and running when this call hangs (or crashes?)  Can you provide a minidump file for the crash?

**Comment by TheWhiteAmbit** [comment]
Sorry, as my software is developed as plugin, it is hard to have some minidump. I call 
if (!vr::VRCompositor()) return ;
after
vr::VROverlay()->CreateOverlay(...)
So I will try altering order and give feedback if this still happens. Thank you.

**Comment by TheWhiteAmbit** [comment]
Update: I found noiw, that the call any call vr::VRCompositor()
This might had to do with initing in another thread. However, this works 90% off all time. I just shutdown and reinit in the renderthread and keep an eye on it.

**Comment by TheWhiteAmbit** [comment]
Ok, the second call to fails, but with an Error so I guess I can handle it somehow. Thank you for Rubberducking :)
