### ISSUE TITLE
Getting the Vive tracker current time position

### ISSUE THREAD

**Issue by tomassykora** [ValveSoftware/openvr#813]
So far I've been using `GetControllerStateWithPose()` to get the position of a Vive tracker. Then I noticed the part of the documentation saying:

> Use this form if you need a precise controller pose as input to your application when the user presses or releases a button. This pose is always older than the current time, so it should not be used for rendering.

What does this even mean for a Vive tracker? There is no button to press, so from what time is the position obtained by this function? Or should the `GetDeviceToAbsoluteTrackingPose()` function be always used for obtaining the current time position?

**Comment by JoeLudwig** [comment]
The Vive Tracker has a power button, and has pogo pins that allow it to be connected to devices with more buttons. GetControllerStateWithPose() will return the pose of the device as of when one of those changed.

Assuming you're building a scene app (i.e. the main thing rendering to the display) you should use WaitGetPoses. The Vive Tracker is in that list of poses.

If you're using the new input system, you should include a pose action and bind that to the tracker. Passing in 0 for the time when you retrieve the pose action's data will get you the result from the most recent WaitGetPoses call. (Tracker support in the new input system is still a little rough, so you may want to hold off on that for a bit.)
