### ISSUE TITLE
Using the Binding UI with a custom driver

### ISSUE THREAD

**Issue by metainf** [ValveSoftware/openvr#821]
I'm working on a driver where I would like to remap the trackpad inputs of the vive controller to a virtual controller. I can see that the vitural controller's trackpad input is working from the input debugging menu, but when I go to the rebinding UI, its empty except for some text.
![test_controller binding api](https://user-images.githubusercontent.com/6304908/42177052-3a70b174-7df9-11e8-924d-0b7059795167.PNG)
I'm fairly certain that I have the input profile correct, and I'm using the generic legacy input file.

```
{
  "jsonid": "input_profile",
  "controller_type": "test_controller",
  "legacy_binding": "config/legacy_bindings_generic.json",
  "legacy_profile": "none",
  "input_bindingui_mode": "single_device ",
  "input_bindingui_right": {
    "image": "{testController}/icons/vive_wand.svg"
  },
  "input_source": {
    "/input/trackpad": {
      "type": "trackpad",
      "binding_image_point": [ 66, 59 ],
      "order": 1
    }
  }
}
```
I know I'm missing something, but I have no idea what, could anyone help me with this?

**Comment by walrus** [comment]
It looks like you're trying to use the standard input profile layout in the legacy bindings file. The legacy bindings should look more like this:

```
{
   "bindings" : {
      "/actions/legacy" : {
        "sources" : [
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/legacy/in/left_axis0_press"
                  },
                  "position" : {
                     "output" : "/actions/legacy/in/left_axis0_value"
                  },
                  "touch" : {
                     "output" : "/actions/legacy/in/left_axis0_touch"
                  }
               },
               "mode" : "trackpad",
               "path" : "/user/hand/left/input/trackpad"
            },
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/legacy/in/right_axis0_press"
                  },
                  "position" : {
                     "output" : "/actions/legacy/in/right_axis0_value"
                  },
                  "touch" : {
                     "output" : "/actions/legacy/in/right_axis0_touch"
                  }
               },
               "mode" : "trackpad",
               "path" : "/user/hand/right/input/trackpad"
            }
         ]
      }
   },
   "controller_type" : "test_controller",
   "description" : "Default binding values for legacy apps using the test controller",
   "name" : "Test Controller Legacy Defaults"
}
```

Have a look at the actual `vive_controller_profile.json` and `legacy_bindings_vive_controller.json`, which you can probably find in `Steam\steamapps\common\SteamVR\drivers\htc\resources\input`

**Comment by metainf** [comment]
@walrus I should clarify, the file I pasted is what I'm using for my normal input profile. and I was using the generic legacy binding file `legacy_binding_generic.json`, which is in  `Steam\steamapps\common\SteamVR\resources\config`

Although I think I fixed the issue now that the binding UI shows up with the emulated touchpad somehow, even though I didn't make any changes to the binding file.
