### ISSUE TITLE
Hellovr on Linux - displaying controller axes/render models

### ISSUE THREAD

**Issue by messier-45** [ValveSoftware/openvr#824]
I am working with a Vive on a Linux machine. The hellovr examples run, and I have played around with the code to render meshes to the Vive with a custom graphics engine. 

I am now interested in displaying the controllers. The hellovr example contains a lot of framework to render controller axes and load the render models, but I am not seeing the axes drawn nor the models loaded, even after turning on/moving the controllers.

I have found an article from a Linux user who adapted the hellovr code to run before linux support was available (https://www.gamingonlinux.com/articles/first-steps-with-openvr-and-the-vive-on-linux.7229), and the author was unable to render axes or rendermodels as well.

I'm new to this, and it could be that I am simply missing the obvious. Is the hellovr code even meant to display the controller axes or render models, or just provide framework to implement this? How have other users had success rendering the controllers axes and/or their rendermodels?

**Comment by TheWhiteAmbit** [comment]
If this helps, I haven't found a way of letting OpenVR render the controllers either. I think this must be done by hand in the renderer you use (OpenGL, Vulkan or an Engine like Unity or Unreal)

**Comment by messier-45** [comment]
@TheWhiteAmbit, thank you for your reply! I am starting off with the OpenGL example, and I'll move forward with rendering by hand. I would love to use the work they've already put into rendering the controllers or even the axes before working on my own project, it's a bit frustrating how little documentation I can find.

**Comment by john-j-oneill** [comment]
I have also noticed this issue with the latest OpenVR version 1.0.15, they used to render for me in Ubuntu 16.04 but they no longer do in the latest openvr opengl sample, however they do still render in the latest vulkan demo.
Try using the version [1.0.14](https://github.com/ValveSoftware/openvr/commit/7027f517983ccaae7d972b7735891bb8244e59fb) `hellovr_opengl_main.cpp` and see if the controllers render correctly. I haven't dug through the changes, but it looks like in the change to "actions" something got missed regarding controller/lighthouse rendering.

**Comment by messier-45** [comment]
@john-j-oneill, thank you for sharing your experience! After I got the Vulkan example running, I started digging into the OpenGL code more closely and never ran the Vulkan code with controllers on. I can see the OpenGL framework for rendering these models and would love to take advantage of it rather than starting from scratch! 

I have Fedora 28. I just ran both hellovr examples with controllers off, charging, or on and wireless. 

The hellovr_opengl example shows 0 controllers, and PoseCount is null (here is the terminal output):
PoseCount:-2123602136((null)) Controllers:0
PoseCount:-2123602136((null)) Controllers:0

The interesting thing is that I ran the code in debug mode in QtCreator and the controllers & lighthouses ARE still being seen as tracked devices in the function UpdateHMDMatrixPose. 

Reardless, the OpenGL example is simply not recognizing the controllers. The lighthouses are also not rendered in opengl.

The hellovr_vulkan example is even worse off. The example runs fine unless a controller is on, charging, or turned on after the program begins. Once a controller is recognized, the program crashes with a segfault. However, the lighthouses ARE rendered in the Vulkan example.

I'll check out the previous version you mentioned and see what happens next. Something in the actions handling definitely got messed up.

**Comment by john-j-oneill** [comment]
Well that does seem to be a bit worse than my experience, although I do believe that , especially with the Vulkan. Ubuntu is better supported by Steam if I recall correctly. I did have the code segfault when I connected a controller a few times, but it usually works otherwise. The silly overflow numbers are the same as I saw on the new hello opengl though, so I think we at least have that problem in common.

**Comment by john-j-oneill** [comment]
@messier-45 Well I think that's up to you, if you are just learning anyways you can always just start from the 1.0.14 version and check back later for updates. I tested out the 1.0.14 version of the [cpp](https://github.com/ValveSoftware/openvr/blob/7027f517983ccaae7d972b7735891bb8244e59fb/samples/hellovr_opengl/hellovr_opengl_main.cpp) with the latest libs this morning, and it renders the controllers just fine, although it still says `PoseCount:-1181344344((null)) Controllers:0` so I'm not sure what's going on there.

**Comment by john-j-oneill** [comment]
@messier-45 I think I figured out the problem, the issue is that the new input system requires a controller setup. [This](https://github.com/ValveSoftware/openvr/wiki/SteamVR-Input) explains how it's supposed to work. First of all, I had to change to the Beta branch of steamvr in steam (under the update settings) and then I ran the controller config, made a dummy json file, then replaced that with [hellovr_bindings_vive_controller.json](https://github.com/ValveSoftware/openvr/blob/master/samples/bin/hellovr_bindings_vive_controller.json) and it works. According to the docs, it's supposed to find the json automagically, and maybe it does on Windows (I don't have a windows machine to test on) but for me (and apparently you) it didn't, and so that's where the failure was.
If you are interested in where this was in the code, `vr::VRInput()->GetPoseActionData()` was returning `vr::VRInputError_InvalidHandle` because it didn't have any bindings for the controllers. I suppose you could check for that error and tell the user to set up their controller.

**Comment by messier-45** [comment]
@john-j-oneill Thank you! I tried the previous version's .cpp file -- it mostly works! The controllers are rendered with lighthouse rendermodels for an unknown reason, but it's way closer to working than I've seen elsewhere so far. I can track down that odd behaviour on my own.

Thank you for finding where in the code it was breaking. I will fix my bindings and see where that gets me with the current version's .cpp. You've been a huge help!

**Comment by john-j-oneill** [comment]
@messier-45 that's great to hear, I'm also glad to have finally figured this out. Although I ended up just reverting to the old way for my ROS project, at least now I know what was going on.

**Comment by messier-45** [comment]
![screenshot_2018-07-13_10-32-19](https://user-images.githubusercontent.com/31603298/42703850-feb0f5fa-868a-11e8-88b4-0deca3a9b52b.png)
After following the steps to set up the controller bindings in the 1.0.15 version of hellovr_opengl, I am getting this error when I go under "settings -> view bindings in your desktop browser." The action manifest json file contains the default text that john-j-oneill pointed me to, but on my machine the controller action still isn't happy. 

While I'm glad that the previous 1.0.14 version renders the controllers, I'd like to work with the current controller handling and input system. Has anyone else received this error?

**Comment by messier-45** [comment]
Closing this due to the issue being covered more specifically by newer issue #829
