### ISSUE TITLE
Custom Run Frame call to TrackedDeviceAxisUpdated in race with Oculus Touch

### ISSUE THREAD

**Issue by SamRelativeDimensions** [ValveSoftware/openvr#828]
Hi all,

Original Post on Steam Discussions here: https://steamcommunity.com/app/250820/discussions/0/1726450077684919159/

I'm working with a custom peripheral, and the driver I've created overrides trackpad/thumbstick input data. It works great for VIVE, overriding the touchpad's input, presumably because when untouched - the VIVE controller doesn't report an axis update on axis 0.

However, now I've made the necessary additions for Rift support, it appears that when at position 0,0 - the Touch controllers report their axis via TrackedDeviceAxisUpdated. This means that sometimes the custom peripheral is last in and used, and sometimes it's the zeroed data from the thumbstick, leading to inconsistent input data.

It seems like there is a race in code between my run frame (and eventually TrackedDeviceAxisUpdated) calls, and the Oculus Touch controllers calls. Is there an easy way to get around this race?

Thanks

**Comment by JoeLudwig** [comment]
What do you mean by "override"?

**Comment by SamRelativeDimensions** [comment]
The driver mimics the trackpad input in-place of the VIVE's trackpad via the UpdateScalarComponent function.

For instance, in some games, you're able to use the trackpad for locomotion. The peripheral I'm working with sends it's joystick input data using (through a few function calls) the UpdateScalarComponent, on chosen controllers (left or right) for axis 0 (trackpad/thumbstick). Essentially acting as a replacement for the VIVE trackpad/Touch thumbstick.

This works great with the VIVE with only the custom peripherals input being handled (unless the user uses the trackpad at the same time). However, the Oculus Touch controllers seem to be sending 'conflicting' data to the Server Host Driver that results in both the custom peripheral, and Touch Controller data being received by the server. It appears that only the last in gets executed by the server into said games. This results in the locomotion moving along (due to peripheral) and then halting (due to idle Touch controller joystick).

**Comment by JoeLudwig** [comment]
You should be able to unbind the trackpad/joystick in the binding UI so the application won't ever see that data. And then you can bind those actions to your custom device instead. Both device's data will be received by the server, but they're stored per-device, so it shouldn't matter. The binding you set will determine which of those streams of data actually get delivered to the application.

**Comment by SamRelativeDimensions** [comment]
Hi Joe,

I've been rewriting the driver from scratch (used to work by the old "override" method which was essentially injecting a custom driver in place of Oculus or Vive). The device now has it's own driver set up appropriately according to the sample project.

I've set it up accordingly for a controller, removing the IVRDisplayComponent, setting properties related to controller and removing HMD specific props etc.

I'm now looking at the RunFrame function - for a joystick, would I send the latest information through vr::VRDriverInput()->UpdateScalarComponent() ? 

If so, how would I get hold of the joystick component, do I have to manually create a ScalarComponent (CreateScalarComponent() ) during activate/init with a unique name (pchName) and then use that pchName when I call to update?

Thanks,
Sam
