### ISSUE TITLE
[Question] Will there be access to raw image from the Vive camera?

### ISSUE THREAD

**Issue by tmladek** [ValveSoftware/openvr#83]
I realize this is quite Vive specific, but as I don't imagine there will be a separate SDK for it, I'm wondering whether there will be a way to access the camera feed directly - so far, I could find no references to the camera in the SDK docs.

Is this planned to be or not be supported, or is it unknown?  
Thanks!

**Comment by JoeLudwig** [comment]
This is planned. We don't have an ETA for when it will be relesed.

**Comment by tmladek** [comment]
Thanks for the heads-up!
