### ISSUE TITLE
change status of a device [openvr driver]

### ISSUE THREAD

**Issue by miguel-neurodigital** [ValveSoftware/openvr#834]
Hello everyone!

I'm creating a driver for steamvr, but when I detect that my device is disconnected from the pc, I'm not able to change the status of my device on steamvr window. At the end, I want that the icon of the device in steamvr changes to gray. 

I've tried the following code:
```
vr::VREvent_Data_t data;
data.status.statusState = vr::VRState_Off;
vr::VRServerDriverHost()->VendorSpecificEvent(m_unObjectId, vr::VREvent_StatusUpdate, (VREvent_Data_t&)data, 0);
```

But in the log (vrserver.txt), I got the following 'error':

> VendorSpecificEvent 900 outside of reserved range

Please, any idea on how to accomplish this? 

Thanks all!

**Comment by JoeLudwig** [comment]
You should be able to do this with vr::VRServerDriverHost()->TrackedDevicePoseUpdated(...).  One of the fields on the driver pose struct is deviceIsConnected. Set that to false and everything else should happen automatically.
