### ISSUE TITLE
Controller inputs not working

### ISSUE THREAD

**Issue by Zamundaaa** [ValveSoftware/openvr#835]
I am using lwjgl on my Ubuntu machine (kernel updated to 4.17.9) any I'm trying to get inputs in general working. What I've got so far is the poses that seem to be working just fine. Adding and removing devices works, too. Button touches and presses are registered as events, and other events work as expected. The only problem I've got so far is that there's no chance I can get the button bitmasks (ulButtonPressed and ulButtonTouched)  to be anything else than 0. Controller axis like the trigger or the touchpad are always 0, too.

**Comment by JoeLudwig** [comment]
We're going to need to know more about what you're doing to help.  What HMD and controllers do you have, for instance?

Is the HelloVR sample working for you? Do the input calls in there give you the results you expect?  Is the rest of the system (the dashboard for instance) working as expected?

**Comment by Zamundaaa** [comment]
I'm using the Vive with the Vive Wands. SteamVR home for example is working fine with using the controllers as lasers for the displays, as using them to grab and resize stuff. The dashboard is working ... kind of. Desktop view doesn't show anything, mouse is just stuck at (0, 0). Steam view doesn't show anything, too. But I can navigate the menu and change preferences in it just fine, no problem.
The HelloVR example... well there doesn't seem to be one for java and I'm not experienced at all in compiling and running a C++ project. If there's just a simple executable to run or I can compile+run it without installing an IDE, then I'll surely try though.
One thing I just found out is that I can't capture input focus. To my understanding this shouldn't alter the results though, as it only makes sure that input is exclusive to my app, which it doesn't have to. If another app had the exclusive input, it would probably be the cause of the issue, but there isn't anything else running besides stuff from SteamVR and I'd wager that I wouldn't get button press events if something else had input focus

**Comment by Zamundaaa** [comment]
I've got further information: The VREvent_Controller button field is always 0x02, so it reports the grip button as pressed. The button bitmask returned by VRSystem_GetControllerState(WithPose) is still 0

**Comment by JoeLudwig** [comment]
It sounds like other apps are getting the right data. I would look into the c++->Java marshaling (in lwjgl?) and see what the raw data from C++ comes through as.

**Comment by Zamundaaa** [comment]
Oh and it sems like the complete controller state struct is always 0. That could either mean that it doesn't see any change or, as you suggested that it might be a problem with data transfer

**Comment by Zamundaaa** [comment]
As I found out that what I've tried using is deprecated and that I've been using a really old version of the library, I tried to switch to the IVR input system. I've come as far as setting up all the actions and the action manifest etc. but when I try to create default bindings via the interface in VR or via the web interface, I just get a empty dark blue background and nothing else. No error message or whatever
The first time I tried this I got to the normal screen but since I've tried to add a single binding to the trigger I have this issue and can't do anything. Deleting the file generated by the first edit didn't work either. This works fine with all other (steam!) VR applications and I can reconfigure them without a problem
Tried on Windows and Kubuntu, same behaviour

**Comment by Zamundaaa** [comment]
Still can't bind my actions. If I try to start Vivecraft it has the same bindings as my game, so not working ones. Trying to create new bindings results in exactly the same dark blue background... Any idea on how to fix that?

**Comment by Zamundaaa** [comment]
I used the Web Console in Firefox to look at what happens when I try to access the controller binding interface and it gives me the following output: https://gist.github.com/Zamundaaa/a02f2d4f68474e0afb5e1076523b7273

**Comment by Zamundaaa** [comment]
The button problem seems to just have been an error of the C api. And as I can now bind my actions this issue is solved
