### ISSUE TITLE
How to use GetRawTrackedDevicePoses()

### ISSUE THREAD

**Issue by metainf** [ValveSoftware/openvr#837]
I'm trying to use GetRawTrackedDevicePoses in a driver to get the pose of a tracker, but it often causes a stack corruption to occur. Am I using GetRawTrackedDevicePoses in the proper manner, or should I launch another app to get the pose of other devices to my driver?

**Comment by JoeLudwig** [comment]
What arguments are you passing to GetRawTrackedDevicePoses?

**Comment by fuzhongqi** [comment]
@JoeLudwig What's the meaning of  "unTrackedDevicePoseArrayCount"? And could you please give an example of GetRawTrackedDevicePoses？ Thank you very much!

**Comment by JoeLudwig** [comment]
We don't have a sample driver that needs that function, so we don't have an example.

That's the number of elements in the array you're filling with poses.

What arguments are you passing to GetRawTrackedDevicePoses?

**Comment by metainf** [comment]
I've moved away from using GetRawTrackedDevicePoses, but I think i was using it wrong. I thought unTrackedDevicePoseArrayCount was the device id, so I passed in the id of the device I was looking for, and I passed in the address of a single TrackedDevicePose_t.

If I wanted to use GetRawTrackedDevicePoses in the future, would I have to pass in an array of size k_unMaxTrackedDeviceCount?

**Comment by miketacticalhaptics** [comment]
This wasn't immediately obvious to me but you can use GetRawTrackedDevicePoses() to get the pose of any tracker. It will populate an array with poses. 
```
 TrackedDevicePose_t hmd_pose[10];
 VRServerDriverHost()->GetRawTrackedDevicePoses(0, hmd_pose, 10); 
```

Your tracker pose will be in the array at the same index as it's objectId. You can iterate through the objectId's and grab properties to figure out the correct index of your tracker. 

```
for (int i = 0; i < 10; i++)
{
	auto props = vr::VRProperties()->TrackedDeviceToPropertyContainer(i);

	string modelNumber = VRProperties()->GetStringProperty(props, Prop_ModelNumber_String);
	string renderModel = VRProperties()->GetStringProperty(props, Prop_RenderModelName_String);

	DriverLog("Device %d = %s %s\n", i, modelNumber.c_str(), renderModel.c_str());
}
```

It might be convenient in the future to be able to directly provide the index for the pose you want rather than getting an array of poses.

**Comment by metainf** [comment]
So I did use that function, but as far as I can tell, it returns the pose of the trackers in their tracking space, not the pose provided on the app side. What I did to make it work in the end was using a background app that uses DebugRequest to send the required information to my driver.
