### ISSUE TITLE
GetPoseActionData returns VRInputError_WrongType

### ISSUE THREAD

**Issue by ltorroba** [ValveSoftware/openvr#847]
I have setup an action, in my action manifest, that is bound to the pose:

```json
{
    "name" : "/actions/main/in/rotate_pose",
    "type" : "pose"
}
```

However, whenever I try to obtain the data from this pose, I get a `VRInputError_WrongType`. Still, I can't see the issue.

```c++
InputPoseActionData_t action_data = {};
EVRInputError error = VRInput()->GetPoseActionData(action_handle_rotate_pose, TrackingUniverseSeated, 0.0f, &action_data, 1);
if (error != VRInputError_None)
    throw std::exception("Cannot get action state.");  // Will always throw
```

Other actions seem to be working, so it must be something specific to this action.

Could this be due to this action not being bound? (I have tried to find out how to bind poses in the SteamVR controller interface but I have so far not been able to find any options for it, so I just assumed that it would bind it automatically). If so, how do I bind poses in the interface?

Any help would be really appreciated.

**Comment by Zamundaaa** [comment]
The same happens for me, too. I assume it has to be bound... I haven't managed to create a binding for my game due to some bug (or perhaps due to something I did wrong) but it's normally bound manually in the interface in vr or at http://localhost:8998/dashboard/controllerbinding.html. This is so you could add more trackers as replacements for poses etc.

**Comment by Zamundaaa** [comment]
Soo I can now create bindings and now I still always get a VRInputError_WrongType, even though my pose action is bound to raw left & right controller poses like in the legacy or hellovr sample controller bindings. The workaround I use for now is that I get the poses with GetWaitPoses but that's neither a solution for this problem nor good to use

**Comment by peroht** [comment]
Lucas,
is your 

`action_handle_rotate_pose `

of the type:

`vr::VRActionHandle_t`

?

**Comment by JoeLudwig** [comment]
`EVRInputError error = VRInput()->GetPoseActionData(action_handle_rotate_pose, TrackingUniverseSeated, 0.0f, &action_data, 1);
`
That last argument is meant to be the size of the struct you're passing on. Change 1 to sizeof( action_data).
