### ISSUE TITLE
VREvent_TrackedDeviceRoleChanged gives an invalid device index

### ISSUE THREAD

**Issue by q009** [ValveSoftware/openvr#853]
Whenever I try to handle that event, when the controller is turned on the 'trackedDeviceIndex' field is always -1, so I have no way of knowing which device had its role actually changed.

Is this intentional? If so, what's the proper way to handle this event?

**Comment by JoeLudwig** [comment]
This event is meant as a hint to tell applications that they should re-query anything they have cached about right/left handed devices. Multiple devices may have changed... the app should just requery them all.

A couple other options:
1) Call GetTrackedDeviceIndexForControllerRole each frame and don't cache anything. It should take minimal time.
2) Use the new input system, which is based on bindings to "right hand" or "left hand" and doesn't use tracked device indices at all.
