### ISSUE TITLE
Question about input system, cannot bind Devices to Actions

### ISSUE THREAD

**Issue by cwlmyjm** [ValveSoftware/openvr#856]
Hi,
I am currently developping a driver for my custom device, I have create a simple driver with 
```/input/trackpad/touch```
```/input/trackpad/x```
```/input/trackpad/y```

Here is my profile
```
{
  "jsonid" : "input_profile",
  "controller_type": "walk_mini_controller",
  "legacy_profile": "walk_mini_controller",
  "legacy_binding" : "{walk_mini}/input/legacy_bindings_walk_mini_controller.json",
  "input_bindingui_mode" : "single_device",
  "input_bindingui_right" :
  {
    "image": "{walk_mini}/icons/gamepad.svg"
  },
  "input_source" :
  {
    "/input/trackpad" : { 
        "type" : "trackpad",
        "binding_image_point" : [ 66, 59 ],
        "order" : 1
    }
  }
}
```

And my default binding file
```
{
	"bindings": {
		"/actions/legacy": {
			"poses": [],
			"haptics": [],
			"sources": [{
				"path": "/devices/walk_mini_controller/input/trackpad",
				"mode": "trackpad",
				"inputs": {
					"position": {
						"output": "/actions/legacy/in/left_axis0_value"
					},
					"touch": {
						"output": "/actions/legacy/in/left_axis0_touch"
					}
				}
			}]
		}
	},
	"controller_type": "walk_mini_controller",
	"description": "",
	"name": "Default bindings for legacy applications for Walk Mini123456"
}
```

Then load the profile in driver by
```
properties->SetStringProperty(handle, ETrackedDeviceProperty::Prop_InputProfilePath_String, "{walk_mini}/input/walk_mini_controller_profile.json");
```

but while I try input debug, it show Unbound(The following picture show debug page)

![9f39d725-650c-464b-992a-fccf01ba3b91](https://user-images.githubusercontent.com/10350872/43934760-6e9dede2-9c83-11e8-8908-b6f5b89cc8d8.png)

I am not sure which step I lose, hope get some suggestion. 😄

**Comment by SamRelativeDimensions** [comment]
I've run into the same issue here, issue number #886 
If you managed to find a solution, it would be great if you could assist me

**Comment by JoeLudwig** [comment]
This looks like a candidate for the new treadmill controller role, which was added in the latest SDK.  Closing this issue to move discussion over to #937 

https://github.com/ValveSoftware/openvr/releases/tag/v1.1.3
