### ISSUE TITLE
Access same vr headset from two different programs

### ISSUE THREAD

**Issue by tyrellturley** [ValveSoftware/openvr#857]
I have two separate but related applications that both need access to my VivePro headset (specifically the head pose tracking data) at the same time. I use the IVRSystem::VR_Init to initialize the headset in both. I can start up and run one of the applications, and the headset initializes fine. However, if I start up the second application, it crashes the first one, presumably because it tries to reinitialize the headset after it's already going. 
Is there a way to have two instances of the same headset running in separate programs at the same time?

**Comment by bddckr** [comment]
I have no problem doing this over here and given that even stock SteamVR does this as its various processes are all `.Init`ing and getting data out and into SteamVR via OpenVR I'm thinking this isn't an issue.

Are you perhaps calling `Init` with the scene app enum case? There can only be one scene app, so the runtime kills the previously running scene app whenever a new one `Init`s in my experience.

**Comment by tyrellturley** [comment]
Yep. That fixed it. I had tried running one instance with the `VRApplication_Scene` enum and the other with `VRApplication_Background`, but that didn't work. I had to run the second instance as `VRApplication_Overlay` overlay.
Thanks for your help!

**Comment by JoeLudwig** [comment]
Background is essentially "Overlay, but don't start SteamVR if it's not already running". If you use Background and Scene and start the background app first, that won't work. The other order should be fine though.

In any case, it sounds like you have this working now.
