### ISSUE TITLE
SteamVR freeze on starting (1533664367)

### ISSUE THREAD

**Issue by SeungYongWoo** [ValveSoftware/openvr#862]
Older version of steamvr(July 3), driver works well.

With 1533664367 version, I have trouble.

When I run SteamVR, hmd display SteamVR's initial empty space and head tracking works fine.(phase 2. below)

But does not changed to SteamVR home.

1. run SteamVR
2. Starting (No response)
![steamvr_starting](https://user-images.githubusercontent.com/14284853/44325689-72075b80-a494-11e8-86ba-a5d4799e16c2.png)
3. wait
4. terminated

crash dump 

[crash_vrserver.exe_20180820161546_2.zip](https://github.com/ValveSoftware/openvr/files/2301475/crash_vrserver.exe_20180820161546_2.zip)

crash debug log

**\src\common\pipes.cpp (774) : Assertion Failed: stalled cross-thread pipe
vrserver.exe has triggered a breakpoint.

\src\clientdll\steamclient.cpp (774) : Assertion Failed: bufRet.TellPut() == sizeof(uint8)
vrserver.exe has triggered a breakpoint.**

vrmonitor.txt when crash

**Mon Aug 20 2018 15:00:42.509 - [Audio] Audio init
Mon Aug 20 2018 15:00:42.509 - [System] Check for dismissable warnings at init.
Mon Aug 20 2018 15:00:42.530 - [System] Chaperone Universe changes for the first time
Mon Aug 20 2018 15:00:42.530 - [System] Chaperone does not indicate room setup
Mon Aug 20 2018 15:00:42.567 - [Steam] Connected to Steam in 0.06 seconds.
Mon Aug 20 2018 15:00:42.568 - [System] Runtime: 1533664367 250820  SteamVR
Mon Aug 20 2018 15:00:42.569 - [Steam] Connect to Steam finished: check for dismissable warnings**

vrmonitor.txt when working

**Mon Aug 20 2018 11:47:46.157 - [Audio] Audio init
Mon Aug 20 2018 11:47:46.158 - [System] Check for dismissable warnings at init.
Mon Aug 20 2018 11:47:46.190 - [System] Chaperone Universe changes for the first time
Mon Aug 20 2018 11:47:46.190 - [System] Chaperone does not indicate room setup
Mon Aug 20 2018 11:47:46.247 - [Steam] Connected to Steam in 0.09 seconds.
Mon Aug 20 2018 11:47:46.248 - [System] Runtime: 1533664367 250820  SteamVR
Mon Aug 20 2018 11:47:46.249 - [Steam] Connect to Steam finished: check for dismissable warnings
Mon Aug 20 2018 11:47:46.580 - [Status] Graphics driver version is 398.82.
Mon Aug 20 2018 11:47:46.584 - [System] Transition from 'Starting' to 'Connecting'.
Mon Aug 20 2018 11:47:46.594 - [System] Transition from 'Connecting' to 'Ready'.
Mon Aug 20 2018 11:47:55.416 - [System] System is running for 10 seconds.
Mon Aug 20 2018 11:47:55.416 - [System] Check for dismissable warnings at startup.
Mon Aug 20 2018 11:48:00.758 - [System] Transition from 'Ready' to 'Shutdown'.
Mon Aug 20 2018 11:48:00.758 - [Audio] Audio shutdown!
Mon Aug 20 2018 11:48:01.758 - [Bluetooth Controller] Shutdown: Power managing these bases: 
Mon Aug 20 2018 11:48:01.758 - [Bluetooth Controller] Shutdown: Wait for worker thread to finish...
Mon Aug 20 2018 11:48:01.758 - [Bluetooth Controller] Shutdown: Completed.
Mon Aug 20 2018 11:48:01.875 - [System] Set VRMonitor PID to 0
Mon Aug 20 2018 11:48:01.880 - Drops over entire run:-  3 single frame-  0 2 frame-  0 3 frame-  0 4 or more- Total 3 in 1290 frames
Mon Aug 20 2018 11:48:01.881 - [System] Restore operating system environment
Mon Aug 20 2018 11:48:01.881 - [System] Restore power settings to previous power savings.
Mon Aug 20 2018 11:48:01.962 - [System] Set VRMonitor PID to 0**

I was testing two same hardware, with different firmware.

One hardware works well on 1533664367 version.

Local test without OpenVR(SteamVR) two hardware works well.

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a EXCEPTION_ACCESS_VIOLATION_WRITE in ntdll.dll coming from driver_lgvr.dll.

**Comment by SeungYongWoo** [comment]
I fixed crash on terminate, so no crash with vrserver. But still no response on starting.

![steamvr_starting](https://user-images.githubusercontent.com/14284853/44696205-890c0600-aab1-11e8-855c-0aa838092268.png)

1. Head tracking works on starting(no response)

2. And wait for a while

3. SteamVR terminated

attach logs and dump after terimnated

[logs_and_dumps.zip](https://github.com/ValveSoftware/openvr/files/2326196/logs_and_dumps.zip)
