### ISSUE TITLE
VRDriverInput integration issues with the new OpenVR SDK 1.0.16

### ISSUE THREAD

**Issue by salians** [ValveSoftware/openvr#869]
Did anyone successfully integrate with VRDriverInput in OpenVR SDK 1.0.16? 

I moved to the new OpenVR SDK 1.0.16 version after a recent steam update broke my input controllers i.e the input triggers stopped working while the laser continued to work. My tiny driver uses the default htc controllers and worked perfectly fine without the VRDriverInput.

The supplied sample driver in OpenVR SDK doesn't help much so without any good code sample/s this turned out to be much more complicated than what I expected. I am looking for feedback specifically on VRDriverInput integration regarding the create and update calls below for VRDriverInput.

My controller activate code tweaks for VRDriverInput looks like this for which the returned VRInputComponent handles are valid numbers:
```vr::VRProperties()->SetStringProperty(m_ulPropertyContainer, Prop_InputProfilePath_String, "{vision}/input/vive_pro_profile.json");
    vr::VRDriverInput()->CreateBooleanComponent(m_ulPropertyContainer, "/input/system/click", &m_inputController[vr::EVRButtonId::k_EButton_System]);
    // Grip button component
    vr::VRDriverInput()->CreateBooleanComponent(m_ulPropertyContainer, "/input/grip/click", &m_inputController[vr::EVRButtonId::k_EButton_Grip]);
    // Application Menu button component
    vr::VRDriverInput()->CreateBooleanComponent(m_ulPropertyContainer, "/input/application_menu/click", &m_inputController[vr::EVRButtonId::k_EButton_ApplicationMenu]);
    // Trigger button component
    //k_EButton_SteamVR_Trigger	= k_EButton_Axis1
    vr::VRDriverInput()->CreateScalarComponent(m_ulPropertyContainer, "/input/trigger/value", &m_inputController[vr::EVRButtonId::k_EButton_SteamVR_Trigger],
                                                vr::VRScalarType_Absolute, vr::VRScalarUnits_NormalizedOneSided);
    // Trigger touch component
    //k_EButton_SteamVR_Touchpad = k_EButton_Axis0
    vr::VRDriverInput()->CreateScalarComponent(m_ulPropertyContainer, "/input/trackpad/value", &m_inputController[vr::EVRButtonId::k_EButton_SteamVR_Touchpad],
                                                vr::VRScalarType_Absolute, vr::VRScalarUnits_NormalizedOneSided);
    // create our haptic component
    vr::VRDriverInput()->CreateHapticComponent(m_ulPropertyContainer, "/output/haptic", &m_compHaptic);
```
My controller update function is as follows for which I process valid button 32, 33 pressed and depressed states but passing that info using the UpdateBooleanComponent and UpdateScalarComponent functions does seem to help i.e. doesn't reach the app. The controller is not even visible in the HMD which seem to indicate pose is not getting updated either:
```        VRServerDriverHost()->TrackedDevicePoseUpdated(m_unObjectId, m_pose, sizeof(m_pose));

        // state
        m_state = state.state;

        for (int i = 0; i < k_unControllerStateAxisCount; i++)
        {
            if (abs(m_state.rAxis[i].x - m_lastAxis[i].x) > 0.015f
                || abs(m_state.rAxis[i].y - m_lastAxis[i].y) > 0.015f)
            {
                vr::VRDriverInput()->UpdateScalarComponent(m_inputController[vr::EVRButtonId::k_EButton_Axis0], m_state.rAxis[i].x, 0);
                vr::VRDriverInput()->UpdateScalarComponent(m_inputController[vr::EVRButtonId::k_EButton_Axis1], m_state.rAxis[i].y, 0);
                m_lastAxis[i] = m_state.rAxis[i];
            }
        }

        uint64_t newPress = m_state.ulButtonPressed & ~m_lastPressed;
        uint64_t newDepress = ~m_state.ulButtonPressed & m_lastPressed;
        uint64_t newTouch = m_state.ulButtonTouched & ~m_lastTouched;
        uint64_t newUntouch = ~m_state.ulButtonTouched & m_lastTouched;

        for (int i = 0; i < k_EButton_Max; i++)
        {
            if (m_inputController[(EVRButtonId)i] == 0) //process only valid VRInputComponent handles
                continue;

            vr::VREvent_t vrEvent = { 0 };
            VREvent_Data_t vrEventData = { 0 };

            uint64_t mask = (uint64_t)1 << i;
            //uint64_t mask = ButtonMaskFromId((EVRButtonId)i);
            vrEventData.controller.button = (EVRButtonId)i;

            if (newPress & mask)
            {
                vr::VRDriverInput()->UpdateBooleanComponent(m_inputController[(EVRButtonId)i], true, 0);
                vlog("Button %d pressed.", i);
            }
            else if (newDepress & mask)
            {
                vr::VRDriverInput()->UpdateBooleanComponent(m_inputController[(EVRButtonId)i], false, 0);
                vlog("Button %d depressed.", i);
            }
```
Anything interesting or obviously wrong?

**Comment by salians** [comment]
After a few more tweaks, I see the controller and the yellow glowing trigger button but the click code mapping still evades me... More to come.

**Comment by TheDeveloperGuy** [comment]
Looks like you're missing the '/touch' and '/click' components for the trigger. If you're using standard mappings you'll need to add these (IIRC). The grip, system and application button code looks fine.

**Comment by TheDeveloperGuy** [comment]
You're also missing the '/touch' and '/click' components for the trackpad.

**Comment by salians** [comment]
Thanks, I am on the road travelling, so I will update when I get back after long weekend on Tuesday:-)

**Comment by salians** [comment]
@TheDeveloperGuy did you have any integration issues with IVRInput please see https://github.com/ValveSoftware/openvr/issues/895

**Comment by TheDeveloperGuy** [comment]
@salians That's an application API. I'm writing drivers, so no. 

https://github.com/ValveSoftware/openvr/wiki/SteamVR-Input

**Comment by salians** [comment]
I finished the IVRDriverInput but I also have to integrate with IVRInput for the app side. That wiki from Joe is useful. On Step9 controller binding settings, there was a json file parsing error only visible in the HMD. The issue I guess was some typo, I re-did the manifest json file for all the controls. After that I am good I can detect button states now.
