### ISSUE TITLE
When I close SteamVR, my application close too.

### ISSUE THREAD

**Issue by adshavd** [ValveSoftware/openvr#878]
I'm currently using Openvr in my C# project. I want to maintain my application when I close SteamVR runtime. But I don't know how to fix this issue. I think that there are some functions to close application. Is there any way to disable it?

**Comment by bddckr** [comment]
Query the events and handle the Quit event by first calling the AcknowledgeQuit method (buying you time so SteamVR doesn't think your process is unresponsive and kills it quickly), then call the Shutdown method to disconnect from OpenVR.

**Comment by BOLL7708** [comment]
In the [header file](https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L1868) it still says that the application is still expected to terminate even if we acknowledge quitting 🤔 Kind of annoying when background applications could just as well be living forever and just keep connecting/disconnecting. 

I know the OpenVR Input Plugin has exactly this [problem](https://github.com/baffler/OBS-OpenVR-Input-Plugin/issues/3), that it still gets terminated. I'll try this myself at some point, when I've finished battling with the new input system.

**Comment by bddckr** [comment]
@BOLL7708 "Process is exiting" means you call `OpenVR.Shutdown` - you don't have to end your process, just the connection to OpenVR.

**Comment by BOLL7708** [comment]
@bddckr Just tried this, when receiving `VREvent_Quit` I run `OpenVR.System.AcknowledgeQuit_Exiting();`, finish my work and then run `OpenVR.Shutdown();` So far so good, my application survives while SteamVR is gone, thanks for this tip 😃

**Comment by bddckr** [comment]
👍 I'd even suggest not doing anything in between to ensure you're not timing out from the point of view of the runtime. I.e. acknowledge, then call `OpenVR.Shutdown` immediately.
