### ISSUE TITLE
OpenVR.System.GetControllerState() do not fill the state anymore (C#)

### ISSUE THREAD

**Issue by BOLL7708** [ValveSoftware/openvr#881]
I noticed my application stopped working between the 4th and 8th this month (Sep 2018), I'm not getting the controller state (nor controller events but I haven't debugged that yet). As mentioned in the title I'm using the C# headers and I'm calling:
```
VRControllerState_t state = new VRControllerState_t();
var success = OpenVR.System.GetControllerState(index, ref state, (uint) System.Runtime.InteropServices.Marshal.SizeOf(state));
```
This has worked since 2016, but not now. If I revert SteamVR to the beta branch `v1527117754 . 6/21/2018 hotfix` everything starts working again, but it stops filling `state` both on the release and beta branches.

I've updated to the most current `openvr_api.dll` and `openvr_api.cs` with no noticeable difference.

-----
When reading the comments in [openvr_api.h](https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L1810) it is clear that this function is being deprecated, but is it already non-functional? In the same place I'm told to implement the new input system instead but got [stumped](https://github.com/ValveSoftware/openvr/issues/879) trying to figure out how to use it with a non-Steam background app.

**Comment by BOLL7708** [comment]
Eh, think I should close this as it's just deprecated and will just stay like that in perpetuity 😅

**Comment by salians** [comment]
I had a similar issue with GetControllerState so switched to IVRInput where I am hitting another problem, see https://github.com/ValveSoftware/openvr/issues/895
