### ISSUE TITLE
Imposible Enable/Disable or read current state of Async. reprojection through API with SteamVR Beta 1538082325

### ISSUE THREAD

**Issue by sergioberg** [ValveSoftware/openvr#897]
Imposible Enable/Disable or read current state of Async. reprojection through API with SteamVR Beta 1538082325
Seems like k_pch_SteamVR_AllowAsyncReprojection_Bool is not associated with this setting.

k_pch_SteamVR_AllowReprojection_Bool and k_pch_SteamVR_ForceReprojection_Bool works fine.

**Comment by sergioberg** [comment]
And now it's not working correctly in the new non-beta SteamVR version.

**Comment by kisak-valve** [comment]
Hello @sergioberg, per "Fix for allowAsyncReprojection setting" in the [2018-09-05](https://steamcommunity.com/games/250820/announcements/detail/1692682595726560078) SteamVR Beta update, please retest this issue.

**Comment by sergioberg** [comment]
Yes, it's work fine now. 

Possible another problem: if Interleaved reprojection is disabled in SteamVR settings it's still continue to work...

**Comment by Nova64** [comment]
https://steamcommunity.com/games/250820/announcements/detail/1692682595726560078

**Comment by Nova64** [comment]
Imposible Enable/Disable or read current state of Async. reprojection through API with SteamVR Beta 1538082325
