### ISSUE TITLE
SteamVR_PlayArea fails to load built-in material in Editor ( SteamVR plugin for Unity - v1.0.8)

### ISSUE THREAD

**Issue by bradowado** [ValveSoftware/openvr#90]
SteamVR_PlayArea.cs, Line 170 has the following code which fails when running in the Editor:
`renderer.material = Resources.GetBuiltinResource<Material>("Sprites-Default.mat");`

ERROR:
```
Failed to find Sprites-Default.mat
UnityEngine.Resources:GetBuiltinResource(String)
The resource Sprites-Default.mat could not be loaded from the resource file!
UnityEngine.Resources:GetBuiltinResource(String)
```

I think you need to use a define to check if it's running in the editor and then call UnityEditor.AssetDatabase.GetBuiltinExtraResource instead of Resources.GetBuiltinResource.

```
#if UNITY_EDITOR
        renderer.material = UnityEditor.AssetDatabase.GetBuiltinExtraResource<Material>("Sprites-Default.mat");
#else
        renderer.material = Resources.GetBuiltinResource<Material>("Sprites-Default.mat");
#endif
```

**Comment by aleiby** [comment]
Awesome, I was just looking into this!
