### ISSUE TITLE
BUG: compositor crash when calling SetWorkingStandingZeroPoseToRawTrackingPose

### ISSUE THREAD

**Issue by gb2111** [ValveSoftware/openvr#900]
Hi,
In WalkinVR project I play VR with disabled people and they are often on wheelchair or bad and have quite limited ability to move hands. They are either very weak or spastic. So I support their gameplay with Xbox Gamepad as I move their position around with this. Like in this video.
https://www.youtube.com/watch?v=Axj_wyGHhcg

I need call repeatedly SetWorkingStandingZeroPoseToRawTrackingPose to implement this and this is causing compositor to crash. SteamVR is still working but only compositor crashes. This bug is for very long time but I overcome it by reducing how often I call as initially it 40fps but then I reduced to 30fps and was working fine. Now it crashes even with 10fps.

Please help. I can make some demo app if needed.
Greg

**Comment by echuber2** [comment]
Have you tried using seated mode instead? It's intended for this sort of thing. Then you can use ResetSeatedZeroPose. (Sorry if this isn't helpful for your specific use case.)

**Comment by gb2111** [comment]
i think it will not work. i want o move or rotate space by specific values.

**Comment by echuber2** [comment]
You still can. The point of this is, there are two basic ways to use the VR tracking space:

1. Standing mode: The user can walk around the space. The center of the floor is the origin. The user can move the room origin with "teleport" or other methods in game.

2. Seated mode: The user stays seated. They can look around in VR and their head position is the origin. They use controls to move through the world; then the control just change the transform matrix between the current seated origin and the intended game world position. This is suitable for cockpit views in vehicles, first-person shooters, etc. where you only want head-look without walking around physically.

So, it sounds like your use case is just like 2 here, but I don't know if you're developing the app from scratch yourself or trying to mod an existing app. If you're modding another game for accessibility, then maybe it's not so simple to change it to seated mode. But if you're developing the game yourself, you can just choose to work with seated mode.

**Comment by gb2111** [comment]
ok. i think I have not clarified my case. i am not doing games but I allow use xbox controller to play room scale games where user cannot physically move due to disability.
so in fact I am emulating physical move. and that works very well. except that it crashes.
i hope I am clear now. would you agree?

**Comment by echuber2** [comment]
Yes, that sounds like what I thought you were doing. I don't know how you're injecting code into other games though. Depending on how you're modifying them it _might_ be possible to do as I've suggested and avoid calling the function that is causing the crash.

Anyway, I hope either the bug can be fixed, or you can get another engineer to help you implement a workaround. I appreciate what you're trying to do with this project.

**Comment by gb2111** [comment]
i am also looking to get this fixed.
can y ou please clarify bit about your walkaround? it is not clear how it suppose to work. thanks.

**Comment by echuber2** [comment]
I still can't tell from your description whether you have access to the source code for your project or not. Are you writing it all in OpenVR or are you injecting code as a hack to another application for accessibility purposes? If it's the latter, I probably can't help at all, because I don't know how to do that. If it's the former, you should study the HelloVR example in the OpenVR SDK carefully and the thread I linked above. By changing the tracking mode to seated instead of room, you can calibrate the headset to be at the origin (0,0,0) in tracking space. Then it's up to you to rewrite the program to move the camera transform in the game world space as desired. This is just like in a FPS game, where you move the camera with a controller and use mouse look. In this case, you want the camera to move with the controller that you operate, while the user wears the HMD and has free head look.

**Comment by gb2111** [comment]
Hello.
I am not injecting code, I use openvr_api. Will check example and see.
When you say like in FPS game then I only hope there will be still head tracking.

Many thanks for reply.

@JoeLudwig what is your view to get this bug resolved?

Greg

**Comment by echuber2** [comment]
You're welcome. I did mean, FPS but with head tracking. Rather than FPS, perhaps "flight simulator" is a better example. The user sits still instead of moving with their feet, they use WASD or joystick to move, but they can still look around with head tracking.

**Comment by gb2111** [comment]
thanks. i will give it a try :)
again in this example I see differences as WASD or joystick is what game is reacting but not tracking space which is my case.  anyway it is time to look into the code :)

i hope really this bug can be fixed soon.

**Comment by gb2111** [comment]
@JoeLudwig 
thank you for 1.1.3 update. this is beautiful!
