### ISSUE TITLE
vr::VRChaperoneSetup()->CommitWorkingCopy() discards pitch and roll rotations.

### ISSUE THREAD

**Issue by naelstrof** [ValveSoftware/openvr#905]
It'd be nice if it didn't so that players can walk on walls and such in VRChat with software like https://github.com/naelstrof/VRPlayspaceMover

**Comment by JoeLudwig** [comment]
Pitch and roll are not supported by the chaperone system. The file literally stores a translation and a yaw. This is unlikely to change just to enable spiderman mode. :)

**Comment by Nipeno** [comment]
that sucks... it would open a whole new world to users (with trackers for full body tracking)
I hope you guys rethink this idea in the future and add support for it, I think a lot of people would enjoy it.

**Comment by Michael4Numbers** [comment]
Rethink this, some people really would enjoy this, just walking on walls and stuff, would be cool. Add support for it in the future.

**Comment by Nipeno** [comment]
Hey I want to ask if it is possible these days to add walking on wallks, idk if the system changed or so.
