### ISSUE TITLE
SteamVR EDeviceActivityLevel heuristic is *backwards*, causes huge delays in transitioning

### ISSUE THREAD

**Issue by muchcharles** [ValveSoftware/openvr#906]
SteamVR seems to try to avoid false positives from the proximity sensor (due to floppy strap?) when determining EDeviceActivityLevel.  However, the logic being used is backwards.

When the proximity sensor is triggered, EDeviceActivityLevel immediately enters UserInteraction.  But when the proximity sensor is not triggered, EDeviceActivityLevel only leaves UserInteraction after a long, excruciating timeout iff there is no significant movement.

The current long timeout on proximity sensor \*not triggered\* doesn't make any sense, because there should be no false positives on proximity sensor \*not triggered\*.

**Comment by muchcharles** [comment]
I do my own checking of the proximity sensor to work around this and get responsive transitioning, but that is broken by #904

**Comment by bddckr** [comment]
I can confirm this one. Thanks to #629 also being a thing this makes this API really unusable.

**Comment by muchcharles** [comment]
@bddckr The latest beta has finally fixed this.  Still can't read proximity sensor directly when an overlay is up, but now activity level uses the proximity sensor for deactivating, so you can stick to a pure activity level approach and get responsive switching.

**Comment by bddckr** [comment]
Thanks for letting me know! That's definitely a fix for this issue, too bad it's not one for #629 (more of a workaround for that one, isn't it...).

I'm kinda leaning against using "activity" API that changes this much, but at least we now have a way to (indirectly) get to the proximity sensor state!
