### ISSUE TITLE
C# wrapper - Could not load type Valve.VR.VREvent_Data_t

### ISSUE THREAD

**Issue by OndrejPetrzilka** [ValveSoftware/openvr#91]
{"Could not load type 'Valve.VR.VREvent_Data_t' from assembly 'VRage.OpenVRWrapper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' because it contains an object field at offset 0 that is incorrectly aligned or overlapped by a non-object field.":"Valve.VR.VREvent_Data_t"}

This is because 'VREvent_Keyboard_t' contains reference type (string) and it's used as part of union.
To fix this issue replace this in 'VREvent_Keyboard_t':

```
[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 8)]
public string cNewInput; //char[8]
```

with:
```
public fixed char cNewInput[8];
```

I would have made pull request, but it says: **This file is auto-generated, do not edit it**

**Comment by aleiby** [comment]
Thanks!  Sadly we cannot use fixed since it requires an unsafe context, but we've just done a lame expansion instead (cNewInput0, cNewInput1, etc.).
