### ISSUE TITLE
"Late Start" on CPU graph with Vive Wireless Adapter

### ISSUE THREAD

**Issue by sergioberg** [ValveSoftware/openvr#913]
"Late Start" on CPU graph with Vive Wireless Adapter:
![Frame Timing](https://cdn.discordapp.com/attachments/351354713628737546/501444361431678976/unknown.png)
i7-8700K/1080Ti/Vive Pro
In most games. Especially noticed in "The Lab".

**Comment by sergioberg** [comment]
With 100% (for Vive Pro) render resolution there is practically no "Late Start"
but with 150%... 200%.... it's appear more and more frequently... even if game easily can handle 300% render resolution.

**Comment by hybrid11** [comment]
I just have terrible performance in general going from wired to wireless. At least 40% worse. Vive Pro 7700k, 1080 ti. Maybe it's one of  these issues, because I refuse to believe the thing just runs like that...but I use 100% SS for now and it makes no difference.

**Comment by sergioberg** [comment]
With new option in beta to disable all Reprojection by Shift + A - no Late Start and it helps avoid performance impact.

**Comment by sergioberg** [comment]
Same with non-beta SteamVR - Async Off, Interleaved - Off, Always-On - On = no Late Start and it helps avoid performance impact.

**Comment by peteostro** [comment]
Nice, But are you sure this isn't Microsoft anti malware doing this? Every time I launch a game in StreamVR on Windows 10 Microsoft's anti malware kicks and and uses 20-30% of the cpu. after a few mins it goes down.

**Comment by sergioberg** [comment]
Yes, i'm sure. It's not related to Microsoft anti malware software.
Some people confirm that issue fixed with new beta.
https://www.reddit.com/r/Vive/comments/9yvf02/new_steamvr_beta_completely_resolve_performance/

**Comment by peteostro** [comment]
yeah I saw that thread, I'll have to try it tonight. Thanks
