### ISSUE TITLE
Input Binding from one controller type to another

### ISSUE THREAD

**Issue by pottedmeat7** [ValveSoftware/openvr#915]
Is it possible to create a input binding from a custom controller trackpad to a Vive controller trackpad?
It seems that the "left" and "right" terms in the input bindings only apply to left and right of the same type ie. a left/right vive or a left/right custom.
Is this how its supposed to work? 
Shouldn't all "Left trackpad" actions be input to the game as "Left trackpad" input?
Or maybe get rid of the left/right terms and send actions to any device "device {id} trackpad"

**Comment by SamRelativeDimensions** [comment]
Hey pottedmeat7,

The new input binding system is supposed to do exactly this - allow the entire input system to be agnostic, allowing any new custom drivers to input into actions, or into the legacy system as specified input actions.

Unfortunately, I've been working with this new system trying to get my industry partner's custom driver bound to legacy actions in various games and applications and the system doesn't seem to work as expected.

Long and short of it - yes the new input binding system does do exactly what you're looking for (for example, inputting a joystick onto the vive controller trackpad) but I am yet to see a developer or driver successfully use it.

**Comment by pottedmeat7** [comment]
This now works if the device uses the new "treadmill" controller role! Thank-you OpenVR devs!
