### ISSUE TITLE
Is there a function to get the current SteamVR version number? If not, please add it! I need this.

### ISSUE THREAD

**Issue by JohnAlcatraz** [ValveSoftware/openvr#918]
Is there a function to get the current SteamVR version number? If not, please add it! I need this.

![image](https://user-images.githubusercontent.com/12215210/47262254-a83c7800-d4e3-11e8-917a-3ac62298d4ae.png)

**Comment by muchcharles** [comment]
This would be nice for diagnostics.  Right now  vr::Prop_DriverVersion_String doesn't always work either, though driver could update separately from steamvr runtime?

**Comment by bddckr** [comment]
`VR_IsRuntimeInstalled` -> `VR_RuntimePath` -> `C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\version.txt` lists it

**Comment by JohnAlcatraz** [comment]
> `VR_IsRuntimeInstalled` -> `VR_RuntimePath` -> `C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\version.txt` lists it.

Thanks very much! That works perfectly :)
