### ISSUE TITLE
Acces Raw transformation matrices

### ISSUE THREAD

**Issue by virgileTN** [ValveSoftware/openvr#920]
Hello ! 

I'm currently trying to access raw transformation matrix instead of the pose of Controllers/Trackers computed by (personal guess) internal Bayesian filter. 

In other words, I'm interested in `Lighthouse1 => Controller1` or `Lighthouse2 => Controller1` raw transformation matrices, before the data fusion. Despite many efforts, I'm still unable to reach those. Is there any way to do it ? 

I would be grateful if you took the time to consider my request.
Best regards,
virgile

**Comment by JoeLudwig** [comment]
That data doesn't exist. The fusion between the raw "light hit a sensor" data and the IMU happens in one filter.  There is no intermediate transformation matrix. We also don't provide the raw "light hit a sensor" data in any form so we can handle making that whole system compatible with future hardware.
