### ISSUE TITLE
Controller Bindings link missing from developer settings

### ISSUE THREAD

**Issue by kelihlodversson** [ValveSoftware/openvr#924]
Until a recent update, the controller bindings editor were accessible from the developer settings:
![2018-09-10 1](https://user-images.githubusercontent.com/3471537/47585305-2b832100-d95d-11e8-81d0-80cbfde68b8c.png)

This link has now disappeared, and the only way to edit them seems to be entering the URL (http://localhost:8998/dashboard/controllerbinding.html) for the dashboard manually.

**Comment by SamRelativeDimensions** [comment]
It's now it's own window (non-browser) that you open via the Steam VR Window > Devices, Controller Input Bindings (or somewhere like that, I don't have it in front of me right now)

**Comment by JoeLudwig** [comment]
As @SamRelativeDimensions points out, it's still available on the desktop, just in a browser window hosted by SteamVR (so we don't need the Chrome or Firefox caveat and it'll work for everybody.) 

If you'd like to open it in your browser, you can also do that: http://127.0.0.1:8998/dashboard/controllerbinding.html

**Comment by Snacko** [comment]
Found this after wasting 2 days trying to make this work...   "Click on steamVR,  go to settings,  go to controllers, 'Show old binding interface", select app that you want to change binding for, edit binding!"
