### ISSUE TITLE
UpdateActionState takes about 0.5-1.0 ms

### ISSUE THREAD

**Issue by klacansky** [ValveSoftware/openvr#925]
I have very simple action files with few buttons mapped (below), but it takes almost 1 ms to update the state for them when calling UpdateActionState. There are several context switches to vrserver.exe. I used OpenVR 1.0.17.

![updateactionstate_pix](https://user-images.githubusercontent.com/39973218/47619238-2bd90480-daa2-11e8-8f6e-90103b6187f7.png)

bindings.json
```
{
   "bindings" : {
      "/actions/main" : {
         "poses" : [
            {
               "output" : "/actions/main/in/hand_left",
               "path" : "/user/hand/left/pose/raw"
            },
            {
               "output" : "/actions/main/in/hand_right",
               "path" : "/user/hand/right/pose/raw"
            }
         ],        
         "sources" : [
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/main/in/move"
                  }
               },
               "mode" : "button",
               "path" : "/user/hand/left/input/trigger"
            },
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/main/in/move"
                  }
               },
               "mode" : "button",
               "path" : "/user/hand/right/input/trigger"
            },
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/main/in/tools"
                  }
               },
               "mode" : "button",
               "path" : "/user/hand/left/input/trackpad"
            },
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/main/in/tools"
                  }
               },
               "mode" : "button",
               "path" : "/user/hand/right/input/trackpad"
            }
         ]
      }
   },
   "controller_type" : "vive_controller",
   "description" : "Bindings for tool for the Vive controller",
   "name" : "Binding for tool"
}
```

actions.json
```
{
  "default_bindings": [
   {
      "controller_type": "vive_controller",
      "binding_url": "bindings.json"
   }
  ], 
  "actions": [
    {
      "name": "/actions/main/in/move",
      "type": "boolean"
    },
    {
      "name": "/actions/main/in/tools",
      "type": "boolean"
    },
    {
      "name": "/actions/main/in/hand_left",
      "type": "pose"
    },
    {
      "name": "/actions/main/in/hand_right",
      "type": "pose"
    }
  ],
  "localization" : [
   {
       "language_tag": "en_US",

        "/actions/main" : "Tool Actions",

        "/actions/main/in/move" : "Move Objects",
        "/actions/main/in/tools" : "Access Tools",
        "/actions/main/in/hand_left" : "Left Hand Pose",
        "/actions/main/in/hand_right" : "Right Hand Pose"
    }
  ]
}
```

**Comment by JoeLudwig** [comment]
Is this only happening the first few times UpdateActionState is called (or the first few times after a controller is turned on) or are you seeing this once the hardware has been on for a bit and everything is in steady state?

The input system has to do some work to load and prepare bindings per app, and it does that work in UpdateActionState. Once things settle down it shouldn't take much time.

**Comment by klacansky** [comment]
I have measured it again (without any profiling, just timing) and the numbers I got are much better, between 150 and 250 us. Unfortunately, I can't see the context switches if I want to get accurate timing and those could be caused by my cpu having only 4 cores and the cpu getting oversubscribed. Sorry for the inaccurate timing.

Both timings reported here are after the application is running for few seconds with controllers present (everything is in steady state).

This time is certainly much better and I am not sure how much time is appropriate for the function to take. Could you explain what roughly is that function doing and what is the cost breakdown?

**Comment by JoeLudwig** [comment]
In the steady state it's reading the driver-provided state of all the input devices and processing it for the app. That's mostly a bunch of lockless shared memory reads. Cost breakdown depends a lot on what bindings you have for your app.

The reason waiting for a steady state before you measure is that it first has to load the binding setup for the app over IPC and then allocate a bunch of objects to represent that state. That takes more work and involves waiting for vrserver to reply to some messages.

**Comment by sbsce** [comment]
I found this issue because I also see UpdateActionState take a significant % of my games performance. On average, that function alone takes 0.3 ms, which I find a lot. Is it supposed to take so long?

@klacansky said that his new numbers are "much better", but still between 0.15 and 0.25 ms, so it's also still quite a lot.

I am profiling on an i7 5820k, with newest SteamVR beta (1.7.12).

@JoeLudwig You said "Once things settle down it shouldn't take much time", but how much is "not much time"? Would you say it's normal that it takes 0.3 ms, and that can't be improved in any way? 0.3 ms is a lot for something like this when you only have a frame budget of 6.9 ms on 144 hz.
