### ISSUE TITLE
Can't sample hellovr_opengl run under win64 platform?

### ISSUE THREAD

**Issue by ByteChen** [ValveSoftware/openvr#929]
* Hi all, I compiled the samples in Windows 10 64bit computer, with cmake command:
``` shell
cmake .. -G "Visual Studio 14 2015 Win64" -DCMAKE_PREFIX_PATH=D:/Qt/Qt5.7.0/5.7/msvc2015_64/lib/cmake
```
* And it compiled and built successfully, but when I am about to run this project, it shows an error as picture below:
> The program can not launch normally.

![image](https://user-images.githubusercontent.com/15138804/48108538-76b30300-e27e-11e8-9e99-241c8eb5bfdb.png)

* Any help is of great appreciate!! I need to run this program under x64 platform cause I need to malloc memory larger than 2~4GB, so x86 is not capable.
* Thanks!

**Comment by ByteChen** [comment]
I solved the problem by myself. The program failed to launch because of wrong version of OpenGL, so I reinstalled **glew** by Nuget and solved the problem.

**Comment by kisak-valve** [comment]
Closing per the last comment.
