### ISSUE TITLE
Java wrapper?

### ISSUE THREAD

**Issue by i-make-robots** [ValveSoftware/openvr#93]
I'd really like to tie this into https://github.com/marginallyclever/Robot-Overlord, written in Java with JogAmp (opengl).  Is anyone working on a java wrapper?

**Comment by thesbros** [comment]
I don't believe there is a separate library, but there is [this one](https://github.com/phr00t/jMonkeyVR/tree/master/src/jopenvr) from jMonkeyVR, which you should be able to extract out. That is what Minecrift Vive uses.

**Comment by i-make-robots** [comment]
Thanks!

On Tue, Apr 26, 2016 at 10:03 PM, Oden <notifications@github.com> wrote:

> I don't believe there is a separate library, but there is this one
> <https://github.com/phr00t/jMonkeyVR/tree/master/src/jopenvr> from
> jMonkeyVR, which you should be able to extract out. That is what Minecrift
> Vive uses.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ValveSoftware/openvr/issues/93#issuecomment-214970707>
>



-- 
Dan Royer, Owner, Marginally Clever Robots
<https://www.marginallyclever.com/>
Ph: +1 (604) 259-9564
Mo: +1 (604) 916-2281

**Comment by elect86** [comment]
Hi i-make-robots!

I am also interested in that, can we unite our effort to make a small binding library? :)

**Comment by i-make-robots** [comment]
@elect86 I'm in.  I have the hardware due to arrive in late June.

**Comment by elect86** [comment]
Excellent, I already have the hw, I am contacting both jherico and phroot to check the availability/plans

**Comment by i-make-robots** [comment]
Phr00t has https://github.com/phr00t/jMonkeyVR.  AFAIK it doesn't use jogamp yet.

**Comment by elect86** [comment]
I created an organization for the purpouse, [jovr](https://github.com/jovr)

I am trying to unite all the spare people interested in that, such as you, [jherico](https://github.com/jherico/JOpenVR), phr00t and [StellaArtis](https://github.com/StellaArtois/JOpenVR)

It doesn't make sense anyone having its own binding...

Yep, it doesn't use jogamp, but I hope we can make it binding-neutral :)

**Comment by elect86** [comment]
Just a note for anyone finding this thread, binding is [here](https://github.com/kotlin-graphics/openvr)
