### ISSUE TITLE
CAPI broken, *VERY* simple fix

### ISSUE THREAD

**Issue by burito** [ValveSoftware/openvr#930]
This has been around for *seven* releases now.

    sed -i 's/struct HmdVector2_t & vCenter/struct HmdVector2_t * vCenter/' openvr_capi.h

For those without access to sed, the solution is to open up ```openvr_capi.h``` search for...

    struct HmdVector2_t & vCenter

and replace it with

    struct HmdVector2_t * vCenter

This has been around for over a year, but Valve wont fix it. They also don't like people creating issues for this. Well if you don't like it, fix it. It could not be simpler.

**Comment by echuber2** [comment]
I'm curious why they won't fix it.

**Comment by kisak-valve** [comment]
Hello @burito, this issue is already being tracked at #687 / #805. Closing as a duplicate.

**Comment by burito** [comment]
So... what's happening? The oldest still existing pull request fixing this
bug is coming up to its first birthday...
