### ISSUE TITLE
Unity Plugin PDF Manual: Redundant paragraph

### ISSUE THREAD

**Issue by glock00** [ValveSoftware/openvr#931]
In the Unity SteamVR 2.0 plugin, there's a PDF manual for the new input system named "SteamVR Unity Plugin - Input System.pdf".

On page 7, the third paragraph is a paraphrase of the first and second paragraph:

First and second paragraph:

> Creating actions is half of the process, the other half is **setting up default
> bindings**. When your users load your application for the first time they will
> load whatever default binding you’ve created for their controller type. If
> there isn’t one they’ll be prompted to create a binding themselves or pick
> from an existing community binding.
> 
> The SteamVR Unity Plugin has a quick link to this UI. If you open the
> SteamVR Input window at the bottom you’ll see **“Open binding UI”.** This will
> open the SteamVR Binding UI in your default browser and select the unity
> application you’re currently editing

Third paragraph:

> Once you’ve created your actions and generated them you’ll need to **setup
> default bindings** for each controller. Turn on your controllers and in the
> SteamVR Input window select **“Open binding UI”**. This will open SteamVR’s
> binding UI in your default browser.

**Comment by bddckr** [comment]
Wrong repo. The Unity plugin lives at [ValveSoftware/steamvr_unity_plugin](https://github.com/ValveSoftware/steamvr_unity_plugin).
