### ISSUE TITLE
Build instructions in src/README fail on linux

### ISSUE THREAD

**Issue by jrandom** [ValveSoftware/openvr#932]
Header search paths are not set up, POSIX never gets defined, and even after attempting to patch these up by hand there are still missing methods and the like, lots of errors that read:

openvr/src/vrcommon/pathtools_public.cpp:70:2: error: ‘AssertMsg’ was not declared in this scope
  AssertMsg( false, "Implement Plat_GetExecutablePath" );

What is the actual correct procedure for building static libs from source on linux? Can the src/README please be updated?

**Comment by echuber2** [comment]
Do the build instructions for the samples help? I haven't tried doing this... https://github.com/ValveSoftware/openvr/tree/master/samples

**Comment by jrandom** [comment]
I copied over some system sections and then patched up the include_directories line since even with corrected paths it does not work as written -- I had to break it up into multiple lines:

```
# Add include folders.
include_directories(${CMAKE_SOURCE_DIR})
include_directories(${CMAKE_SOURCE_DIR}/../headers)
include_directories(${CMAKE_SOURCE_DIR}/vrcommon)
```

The full CMakeFile with alterations can be found here: [CMakeLists.txt](https://gist.github.com/jrandom/a245192f7e9c9ebebca4c445f8bb7798).

Here are the slightly modified instructions to build (as from the src/README file):

```
cd src
mkdir _build
cd _build
cmake .. -DCMAKE_BUILD_TYPE=Release
make
```

It would be nice if the maintainers could come up with a permanent fix, either in the CMakeLists.txt file and/or the actual instructions.
