### ISSUE TITLE
adopting vr::VROverlay()->SetOverlayRaw() to show video from opencv mat, and arises screen flicker.

### ISSUE THREAD

**Issue by SamXiaosheng** [ValveSoftware/openvr#941]

**Comment by JoeLudwig** [comment]
SetOverlayRaw is shockingly inefficient. Don't use it for video. It's really only useful for things you're not going to update more than once.

If you need to update video in an overlay, make your own graphics device, get the data into a texture, and call SetOverlayTexture.

**Comment by JoeLudwig** [comment]
That would be much better than SetOverlayRaw. Depending on what content you're showing as video you might also be able to just find a copy of the video frames already on the video card and call SetOverlayTexture with that.
