### ISSUE TITLE
Black screen when selecting "Controller Input Binding"

### ISSUE THREAD

**Issue by bevanmckechnie** [ValveSoftware/openvr#942]
Hello!

SteamVR Version 1542414933 (Beta)
OS Windows 8.1 (Japanese) 
Vive + Knuckles EV3

I have an issue where if I select "Controller Input Binding" from the devices menu I am greeted with a blank, black window with no text etc. 

What other information should I provide to help diagnose the issue? Are there any workarounds for the meantime?

Thank you

**Comment by elliotstaker** [comment]
I have just started receiving the same issue again.

The previous temporary fix was to change a line in the .js file within the dashboard folder, but this doesn't seem to be generated anymore. Could this be the issue? Or is that just a design change?

Cheers!

**Comment by JoeLudwig** [comment]
@elliotstaker If you're seeing this in the SteamVR Beta we just pushed out a fix:
https://steamcommunity.com/games/250820/announcements/detail/3038136886322358281

If either of you are still seeing a black screen after today's beta update, please post a system report and we can reopen this issue.
