### ISSUE TITLE
path_handle.json query

### ISSUE THREAD

**Issue by AgentMilkshake1** [ValveSoftware/openvr#943]
In the Json that can be retrieved from this address at runtime (http://127.0.0.1:8998/path_handles.json) which part of the path elements is the Handle (vr::VRInputComponentHandle_t) of said path (if any):

- dec
- dec_property
- hex
- hex_property

Due to the size of the dec value, it feels like this should be the corresponding uint64_t handle to any given path. 

Thanks

**Comment by JoeLudwig** [comment]
dec and hex are both the path handles, hex is just the path handled in hexadecimal. Neither of these are component handles which get a globally unique ID.  

Why do you ask? Depending on this (undocumented) web API in any way is probably not going to work out long-term. It could go away or change without warning and there's no guarantee of version safety.

**Comment by AgentMilkshake1** [comment]
That's fair, thanks for the reply.

In this particular case, it's relating to the custom driver I've been writing for the treadmill like device (as I'm sure you've been seeing me complain about haha).

As I've been having trouble implementing through the expected methods (as a controller) I was attempting to actually grab the left trackpad/thumbstick handle through the json and pass the handle in to the update scalar component function. I know this is a bit hacky but if it worked as a temporary get around to input onto the trackpad/thumbstick, then I was all for it.

I actually tried implementing the driver as a GenericTracker rather than a Controller. This is very hit and miss as it worked about 2 days ago before a beta update. I then reverted to the latest non-beta release and it worked flawlessly (allowing my custom tracker to input joystick input and bind to the left trackpad/thumbstick whilst simultaneously using the motion controllers).

That was yesterday that it worked seamlessly across multiple tests (both Oculus and Vive, on 2/3 titles). Today I've turned on my PC and it's no not working and the input binding menu has broken (you can get to the bit where you click "edit" but as soon as you click edit, it goes to a black screen - this is on the non-beta version).

It appears I've got a Schrodinger's driver on my hands, so close to working too! Any tips @JoeLudwig ?
