### ISSUE TITLE
[Potential Feature Request] SteamVR Install Path Registry Key

### ISSUE THREAD

**Issue by AgentMilkshake1** [ValveSoftware/openvr#945]
Hi there,

I'm trying to grab the SteamVR installation path via code so that I can call VRPathReg.exe upon installing my custom driver to automatically register the driver through the add driver command.

I've looked through the registry and cannot find a key for the SteamVR Installation. Does this exist? If not can it be added as a feature request. Thanks

**Comment by AgentMilkshake1** [comment]
Suggestion - Perhaps adding it under the registry directory:

Computer\HKEY_CURRENT_USER\Software\Valve\Steam\Apps\250820

key name: InstallPath
where the value is a string to the root SteamVR folder.

**Comment by TheDeveloperGuy** [comment]
$LOCALAPPDATA\openvr\openvrpaths.vrpath is a JSON file. You can get the runtime (SteamVR) path from the "runtime" key once you've parsed the JSON. You can also add your driver path to that file directly (to the "external_drivers" key so that you don't have to run external commands.

**Comment by TheDeveloperGuy** [comment]
$LOCALAPPDATA\openvr\openvrpaths.vrpath is a JSON file. You can get the runtime (SteamVR) path from the "runtime" key once you've parsed the JSON. You can also add your driver path to that file directly (to the "external_drivers" key so that you don't have to run external commands.

**Comment by AgentMilkshake1** [comment]
Ah that's perfect, exactly what I was looking for, thank you!
