### ISSUE TITLE
OpenVR is VR for programmers only?

### ISSUE THREAD

**Issue by Rynerak** [ValveSoftware/openvr#946]
I have a game that only supports OpenVR and I have the HTC Vive and SteamVR will not pick up the game, everything keeps pointing to OpenVR and yet all I keep getting led to is forums and guides that keep going into 50 steps of programming.
So how do I get a game that only supports OpenVR to run on my HTC Vive?
Or do I have to spend 2 years learning programming just to use these OpenVR games?

**Comment by BOLL7708** [comment]
You're just trying to play a title? As you mention SteamVR I presume you have SteamVR installed. If the game is not on Steam you can add it as an external app and check the "Include in VR library" option in properties, which might help. Some applications can take launch parameters like "--vr" or similar.

Care to go into specifics of what you're trying to do?
