### ISSUE TITLE
the definition of more controllers than there really is

### ISSUE THREAD

**Issue by antonovaa** [ValveSoftware/openvr#948]
Hi all! 

My name is Andrey, i am Unreal Engine dev.
Unreal engine 4.18.3
SteamVR
5 HTC truckers + hmd + 2 controllers.
I have a problem: the controller triggers spontaneously shut down (TriggerAnalog and other button not work). when debugging I get, sometimes, that there are more than two controllers attached 

for (uint32 DeviceIndex = 0; DeviceIndex < vr::k_unMaxTrackedDeviceCount; ++DeviceIndex)
			{
				vr::ETrackedDeviceClass DeviceClass = VRSystem->GetTrackedDeviceClass(DeviceIndex);
}
(however there are only two controllers)

**Comment by JoeLudwig** [comment]
Look under the devices->Manage Vive Trackers UI and check how your trackers are configured. If they're all set to "held in hand" they are acting as controllers. Set them to whatever you're actually using them for (or "disabled" if there's no reasonable option) and their tracked device class will be Generic Tracker.
