### ISSUE TITLE
What should I do to make my own driver work with vrcompositor in direct mode

### ISSUE THREAD

**Issue by matrixcr** [ValveSoftware/openvr#95]
I just DIYed a HMD and made a custom openvr driver for it. But it doesn't work:

1. The vrcompositor always rendered to my primary display (plugged in the DVI port) instead of the HMD (HDMI port) in extended mode.
2. How can I tell vrcompositor, vrserver and vrmonitor that the HMD is in direct mode when I initialize the device driver to direct mode? How can I get the D3D device and context to render to the compositor window?
3. Could I made my own compoistor? Then how incorporate it to steamvr.

Any input is highly appreciated. Thanks

**Comment by sencercoltu** [comment]
Hi, 
For #1: I managed to create the vrcompositor window on my HMD monitor. My desktop is extended to the HMD monitor. The position & resolution is auto detected while server driver is initialized, and vrcompositor creates the fullscreen window on my hmd. Check my primitive custom driver code here, maybe it helps: https://github.com/sencercoltu/openvr-customhmd

**Comment by aleiby** [comment]
You mostly just need to return the following values for your display's edid:
Prop_EdidVendorID_Int32
Prop_EdidProductID_Int32

For Nvidia, you also need to add a registry key to whitelist the device, or talk with nvidia to get your device automatically whitelisted.

**Comment by matrixcr** [comment]
Thanks aleiby!!! I can eventually enter direct mode. But I never got the following direct mode interfaces called. What else I missed?

	// -----------------------------------
	// Direct mode methods
	// -----------------------------------

	/** Specific to Oculus compositor support, textures supplied must be created using this method. */
	virtual void CreateSwapTextureSet(uint32_t unPid, uint32_t unFormat, uint32_t unWidth, uint32_t unHeight, void *(*pSharedTextureHandles)[3]) override;

	/** Used to textures created using CreateSwapTextureSet.  Only one of the set's handles needs to be used to destroy the entire set. */
	virtual void DestroySwapTextureSet(void *pSharedTextureHandle) override;

	/** After Present returns, calls this to get the next index to use for rendering. */
	virtual void GetNextSwapTextureSetIndex(void *pSharedTextureHandles[2], uint32_t(*pIndices)[2]) override;

	/** Call once per layer to draw for this frame.  One shared texture handle per eye.  Textures must be created
	* using CreateSwapTextureSet and should be alternated per frame.  Call Present once all layers have been submitted. */
	virtual void SubmitLayer(void *pSharedTextureHandles[2], const vr::VRTextureBounds_t(&bounds)[2], const vr::HmdMatrix34_t *pPose) override;

**Comment by JoeLudwig** [comment]
You can ignore all those functions. Those only apply to the Oculus compositor and not to hardware that uses OpenVR's direct mode directly.

**Comment by otri** [comment]
I'm also working on using OpenVR's direct mode. But finding it hard to understand how vrserver and vrcompositor interact.

vrserver looks like it operates the ITrackedDeviceServerDriver, which in turn holds the IVRDriverDirectModeComponent interface, however we never get a call to SubmitLayer().  Looking harder I can't find any entry point for when a frame is ready for delivery to the direct driver, and it's ready to present, outside of those in the IVRDriverDirectModeComponent.

vrcompositor uses the IClientTrackedDriverProvider, but it never calls the GetMCImage called, which looks like a transport buffer of some kind.  Is this for when the composited image is ready to roll?

How do we know is a frame is ready to go out to HMD?

VR app finishes rendering, then calls these:
VRCompositor()->Submit(Eye_Left,leftTexture)
VRCompositor()->Submit(Eye_Right,rightTexture)
glFinish();
SwapBuffers(hdc);

Swap chain I assume triggers the sequence of events to present the final composited output.
Does it work like this?
 -> vrserver ITrackedDeviceServerDriver
 -> vrcompositor IClientTrackedDriverProvider
 -> vrserver IVRDriverDirectModeComponent

What actually gets called on swap?
What is MC and GG? Does anyone have an idea what do these stand for?

**Comment by xiangzi8576** [comment]
@JoeLudwig 
I'm confused with your comment."You can ignore all those functions. Those only apply to the Oculus compositor and not to hardware that uses OpenVR's direct mode directly."
If we don't use these functions, how can we enable direct mode with OpenVR?
Look farward to your feedback and thanks in advance~

**Comment by JoeLudwig** [comment]
See @aleiby's comment above. Just return those two properties and direct mode should work. (Assume you've added yourself to the whitelist if you're on an NVIDIA card.)

**Comment by otri** [comment]
I think we need more details about what direct mode should be doing.  Like, what gets called?   I need to transpose pixels across the display interface, but I can't if my driver doesn't get called.

**Comment by JoeLudwig** [comment]
There's not currently any driver-level access to the pixels before they go out. You can transpose in your distortion function, though, and the compositor will do that for you.

**Comment by david-clement** [comment]
Would it just transpose the pixels in the rendered scene layer or all pixels in every layer?  Essentially we have to transpose the pixels in all layers for the composited result to look correct.

**Comment by JoeLudwig** [comment]
All pixels in all layers go through the distortion function to come out looking correct on the other side of the lenses. 

What do you mean by "transpose"? Is this a portrait vs. landscape rotation or something else?

**Comment by david-clement** [comment]
Yes.  Its a piece of hardware that reformats a portrait HDMI image into a landscape one by streaming 1080 pixel scan lines into 1920 pixel wide spans to create a 1080p image that can be transmitted wirelessly with microsecond latency.

**Comment by JoeLudwig** [comment]
If I understand what you're saying this is something you should be able to do by returning different values from ComputeDistortion.

**Comment by otri** [comment]
Unfortunately the ComputeDistortion is confined to the left or right eye-side of the framebuffer.  So even though we tried remapping with returned results for ComputeDistortion, we are fundamentally unable to pull right eye pixels into the left eye portion of the screen and vice versa.
If I had a clear signal of when the compositor is done presenting the framebuffer, I could tap the compositor's framebuffer for the purpose of remapping the pixels into another window.

**Comment by david-clement** [comment]
Given that we don't have a resolution on this issue should I create a new one?
