### ISSUE TITLE
No bindings found, just a brief fadeout

### ISSUE THREAD

**Issue by kallisti-linden-lab** [ValveSoftware/openvr#950]
I am currently at step 9 of the SteamVR Input Getting Started list.   The manifest, action set, action and input handles all are called with no error.  I have a loop calling UpdateActionState and then GetDigitalActionData.   The last one returns an error NoData, I assume this is because I haven't bound it yet.

When I run the app and go to Controller Binding in SteamVR, the application shows as current application.  When I press the button to edit the bindings, the screen dims slightly for about 3 seconds and then returns.  All other applications go to a change bindings screen.     Does this imply that there's something wrong with my manifest?

**Comment by kallisti-linden-lab** [comment]
Problem was my fault.   

For the record, passing in a non-normalized manifest path returns VRInputError_None, so there isn't any indication that things did not work.   Similarly for the various Get___Handle methods.

**Comment by JoeLudwig** [comment]
@kallisti-linden-lab When you say "non normalized" you mean a relative path?

**Comment by kallisti-linden-lab** [comment]
The path was in the form  c:\a\b\c\..\..\OpenVR\my.json

**Comment by JoeLudwig** [comment]
You mean literally four dots in the middle? Or was is more like:
`c:\a\b\c\..\..\OpenVR\my.json`

Meaning that the full path should have been:
`c:\a\OpenVR\my.json`

**Comment by kallisti-linden-lab** [comment]
Yes.  I am unsure where that middle slash disappeared to.
