### ISSUE TITLE
Please explain VR_getInitToken and COpenVRContext getters

### ISSUE THREAD

**Issue by vahur** [ValveSoftware/openvr#953]
I'm planning to use CAPI and trying to find any info about the logic which is used to reload interface handles. Can you please explain, what the token represents? Why is it necessary to reload interface handles and under which conditions will this happen? Does it mean that interface handles should not be stored in some local variable and before calling any method I have to always fetch them from COpenVRContext via a getter method?
Since these getters can potentially return NULL (in case the interface handles are reloaded?) do I have to check for NULL every time I'm about to call a method?

**Comment by JoeLudwig** [comment]
VR_GetInitToken is an internal interface that allows the cached interface handles to be invalidated in one very specific circumstance: When one DLL in a larger application is responsible for VR_Init and VR_Shutdown calls, and another is trying to use the API. In this circumstance, the token will change on each VR_Init or VR_Shutdown call and signal to the other modules in the same process that they should invalidate their cached interface pointers.

As long as you control all the code that calls OpenVR interfaces, you can safely ignore VR_GetInitToken.
