### ISSUE TITLE
Vive Tracker Unity documentation

### ISSUE THREAD

**Issue by mtsandmeyer** [ValveSoftware/openvr#955]
Hi, I am looking for documentation about how to get GameObjects in Unity to follow Vive trackers.

This was previously possible using the Steam_VR_Tracked_Object script, but this appears to be 
deprecated. 

Thank you!

**Comment by bddckr** [comment]
You're looking at the wrong repo, that may be why 😄

Here's the one for the Unity plugin: https://github.com/ValveSoftware/steamvr_unity_plugin
