### ISSUE TITLE
Where is the binding file for specific game?

### ISSUE THREAD

**Issue by cwlmyjm** [ValveSoftware/openvr#964]
Hi,
I am trying to modify the binding for some specific game in binding system. But I cannot find the binding file after saving. The reason why I want to do this is that for some game might use different binding file rather that the default one. Is there any way to do that?
Thanks!

**Comment by JoeLudwig** [comment]
They're stored in the Steam Workshop. You can export them to a file from the UI if you enable input debug options in the developer settings in SteamVR.
