### ISSUE TITLE
BUG: SteamVR creates headset window for IVRVirtualDisplay

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#973]
When using the IVRDisplayComponent driver component in extended mode, SteamVR will create a fullscreen output window for the headset. When using IVRVirtualDisplay or IVRDriverDirectModeComponent driver components, the window should not be created, as the driver is dealing with output to the actual headset. For IVRDriverDirectModeComponent drivers this holds true, as expected. However for IVRVirtualDisplay this window is created when it should not be. 

How to prevent this window from being created for IVRVirtualDisplay drivers?

**Comment by natbro** [comment]
good issue - this was resolved in 1.2.6: https://steamcommunity.com/games/250820/announcements/detail/1705075920701480358.

**Comment by TheDeveloperGuy** [comment]
Thanks! I've made a separate issue for the remaining related bug:

https://github.com/ValveSoftware/openvr/issues/987
