### ISSUE TITLE
Many "GL Errors ..." occurred when I run hellovr_opengl project with command line parameter -gldebug

### ISSUE THREAD

**Issue by jigetage** [ValveSoftware/openvr#976]
I was trying to study hellovr_opengl project. 
Compilation is correct, but when I run it with command line parameter "-gldebug", it shows many debug information starting with "GL Error: ...". Detailed information shows down below.

![gldebug](https://user-images.githubusercontent.com/17247590/50535666-3178c680-0b87-11e9-8d9f-a4bbbc302759.JPG)

platform: windows 10 64bits 
IDE：vs2017 
compilation options: win64 debug
command:  ./hellovr_opengl.exe -gldebug

Is any one encountered with the same problem before? 
Any answer is highly appreciated!
Thx~~~

**Comment by wadim-al** [comment]
1) I have other error messages. 
2) The HMD shows the black screen. (may be connected to [https://github.com/ValveSoftware/openvr/issues/744)])
3) Positional tracking works.
4) Black screen occurs in other openvr based projects like jrbudda/minecrift, Zackin5/Quakespasm-OpenVR, cmbruns/gz3doom.

Here is my log
[log.txt](https://github.com/ValveSoftware/openvr/files/2719590/log.txt)

platform: windows 10 64bits
IDE：vs2017 community
compilation options: win32 debug
command: ./hellovr_opengl.exe -gldebug -verbose
GPU: Intel UHD630
HMD: WindowsMR (Lenovo explorer)

**Comment by jigetage** [comment]
> 1. I have other error messages.
> 2. The HMD shows the black screen. (may be connected to [https://github.com/[/issues/744](https://github.com/ValveSoftware/openvr/issues/744))])
> 3. Positional tracking works.
> 4. Black screen occurs in other openvr based projects like jrbudda/minecrift, Zackin5/Quakespasm-OpenVR, cmbruns/gz3doom.
> 
> Here is my log
> [log.txt](https://github.com/ValveSoftware/openvr/files/2719590/log.txt)
> 
> platform: windows 10 64bits
> IDE：vs2017 community
> compilation options: win32 debug
> command: ./hellovr_opengl.exe -gldebug -verbose
> GPU: Intel UHD630
> HMD: WindowsMR (Lenovo explorer)

according to your log, it seems that you call a wrong open_gl method or misuse it.

**Comment by jigetage** [comment]
it's not open_gl errors, just open_gl warnings.

**Comment by wadim-al** [comment]
> > 1. I have other error messages.
> > 2. The HMD shows the black screen. (may be connected to [https://github.com/[/issues/744](https://github.com/ValveSoftware/openvr/issues/744))])
> > 3. Positional tracking works.
> > 4. Black screen occurs in other openvr based projects like jrbudda/minecrift, Zackin5/Quakespasm-OpenVR, cmbruns/gz3doom.
> > 
> > Here is my log
> > [log.txt](https://github.com/ValveSoftware/openvr/files/2719590/log.txt)
> > platform: windows 10 64bits
> > IDE：vs2017 community
> > compilation options: win32 debug
> > command: ./hellovr_opengl.exe -gldebug -verbose
> > GPU: Intel UHD630
> > HMD: WindowsMR (Lenovo explorer)
> 
> according to your log, it seems that you call a wrong open_gl method or misuse it.

I mean the unmodified opengl hellovr_opengl having problem running with Intel's Opengl drivers possibly connected to issue 744. I'm not changing or calling anything. Just compiled with VS2017 and enabled the logging.
