### ISSUE TITLE
Linker bug, openvr.h uses __declspec( dllexport/import ) even when built statically

### ISSUE THREAD

**Issue by n8vm** [ValveSoftware/openvr#980]
openvr.h doesn't seem to take into account declspec(export/import) when openvr is built statically, and there is no way to define the decoration away without hacking openvr.h

Simple fix here: https://github.com/ValveSoftware/openvr/pull/483

Please accept this pull request.

**Comment by kisak-valve** [comment]
Hello @n8vm, there's no value in opening an issue report to comment about a pull request when you can comment directly on the pull request. Closing in favor of #483.
