### ISSUE TITLE
BUG: SteamVR gives "Extended Mode" warning for IVRDriverDirectModeComponent and IVRVirtualDisplay drivers

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#987]
When using a HMD driver that deals with the display itself (ie. a IVRDriverDirectModeComponent or IVRVirtualDisplay driver), SteamVR should not be concerned about or displaying messages regarding "Extended mode", particularly for remote (ie. non DP or HDMI) HMDs. Although benign, it is confusing for users to be presented with a warning of "Extended Mode is not recommended. For the best results , please switch to Direct Mode", when it's not possible to do so, or relevant to be warned about it.

**Comment by natbro** [comment]
thanks for pointing this out. a fix will be in the next public beta.

**Comment by TheDeveloperGuy** [comment]
@natbro There is no fix for this in the most recent public beta. Please also look at related:

https://github.com/ValveSoftware/openvr/issues/1004

**Comment by TheDeveloperGuy** [comment]
There is a "dismissable" warning key that can be added to the steamvr.vrsettings config file to turn off this warning.
