### ISSUE TITLE
How to running Multiple VR applications at the same time.

### ISSUE THREAD

**Issue by SlimSnow** [ValveSoftware/openvr#989]
Hi there,I want to running Multiple VR applications at the same time.But I do not have any ideas,Is there any 
good ideas for me to solve my problem?  I'd appreciate it very much.

**Comment by JoeLudwig** [comment]
When you say multiple applications, do you mean multiple "scene" applications? i.e. two apps providing the 3D scene that is shown to the user?

SteamVR supports one scene application and multiple overlay apps, but does not support more than one scene app.

**Comment by SlimSnow** [comment]
Hi, JoeLudwig.
Thank you for the explain previous,My purpose is that one PC connect two or more VR equipment just like HTC vive , and different VR equipment start different VR app.Is this can be implement ?

**Comment by JoeLudwig** [comment]
SteamVR also supports only one HMD at a time. That's unlikely to change anytime soon.

**Comment by SlimSnow** [comment]
@BOLL7708 Thanks,I will check it later.
