### ISSUE TITLE
openvr_driver.h is outdated

### ISSUE THREAD

**Issue by godbyk** [ValveSoftware/openvr#99]
Recent releases of SteamVR have surpassed the `openvr_driver.h` file found in this repository.

A colleague of mine ran `strings` against the drivers that come with SteamVR (e.g., lighthouse and oculus) and found that the version of the server is `IServerTrackedDeviceProvider_003`. However, the `openvr_driver.h` header file in the OpenVR Github repository [still has this set as `IServerTrackedDeviceProvider_002`](https://github.com/ValveSoftware/openvr/blob/master/headers/openvr_driver.h#L1545).

So it seems apparent that the Github repository isn't being kept up to date with the released version of SteamVR.

Please update this repository to reflect the latest interfaces and versions required for open-source drivers to maintain compatibility with SteamVR.

**Comment by JoeLudwig** [comment]
Fixed in 
https://github.com/ValveSoftware/openvr/releases/tag/v0.9.20

**Comment by JoeLudwig** [comment]
I should note: the drivers in the SteamVR depot are one version ahead, but vrserver will load back to IServerTrackedDeviceProvider_002. And the IVRComponentDisplay interface that changed has been updated in the SDK.

**Comment by godbyk** [comment]
@JoeLudwig So should I expect v0.9.20 to work with the latest released version (or beta?) of SteamVR?

**Comment by JoeLudwig** [comment]
Yes.  If you have any problems please let us know.

**Comment by godbyk** [comment]
Will do. Thanks, Joe!
