### ISSUE TITLE
Access Violation after ComputeDistortion call

### ISSUE THREAD

**Issue by Seneral** [ValveSoftware/openvr#995]
Hello, I have one more issue that I'm not sure how it is related to my code.

In short, whole SteamVR and/or my driver crashes - apparently an access violation - 350ms after a call to my ComputeDistortion. But I'm currently using the sample function only (returning undistorted UVs), and there should be no error in it... Here are the relevant logs:

vrserver:
```
Mon Jan 14 2019 10:48:19.643 - serialhmd: Display: ComputeDistortion: (0.000000,0.000000) (0.000000,0.000000) (0.000000,0.000000) 
Mon Jan 14 2019 10:48:20.000 - Exception c0000005
```
vrcompositor:
```
Mon Jan 14 2019 10:48:19.643 - Creating samplers
Mon Jan 14 2019 10:48:19.643 - Creating util resources
Mon Jan 14 2019 10:48:19.643 - Creating/Updating distortion surfaces
Mon Jan 14 2019 10:48:20.645 - Failed to compute distortion parameters! 1/2401
Mon Jan 14 2019 10:48:20.645 - Failed to create distortion surfaces
Mon Jan 14 2019 10:48:20.645 - Failed to init graphics device
Mon Jan 14 2019 10:48:20.646 - Failed to initialize compositor
Mon Jan 14 2019 10:48:20.646 - Failed to start compositor: VRInitError_Compositor_Failed
```

The timing is interesting and implies the actual error is not in my code, but from right after it. Just in case I've logged every single function with a DriverLog at the beginning, but nothing except Server RunFrame is called after it. So I've taken a look at the return of my function, but it's the same as every other implementation I've seen. Just in case it was because the return was a local variable that was released right after the function call, I unsuccessfully tried the following:
`DistortionCoordinates_t coordinates = *(new DistortionCoordinates_t);`
instead of `vr::DistortionCoordinates_t coordinates;`

Here's the full implementation for reference:
```
DistortionCoordinates_t SerialHMDDisplay::ComputeDistortion(EVREye eEye, float fU, float fV)
{
	vr::DistortionCoordinates_t coordinates;
	coordinates.rfBlue[0] = fU;
	coordinates.rfBlue[1] = fV;
	coordinates.rfGreen[0] = fU;
	coordinates.rfGreen[1] = fV;
	coordinates.rfRed[0] = fU;
	coordinates.rfRed[1] = fV;
	DriverLog("Display: ComputeDistortion: (%f,%f) (%f,%f) (%f,%f) \n", coordinates.rfBlue[0], coordinates.rfBlue[1], coordinates.rfGreen[0], coordinates.rfGreen[1], coordinates.rfRed[0], coordinates.rfRed[1]);
	return coordinates;
}
```

So I assume my error lies 'around it', in the properties or functions that I am missing. I've yet to implement the hidden area mesh but that can't possibly affect that, right?
Again, any help greatly appreciated. Sorry for dumping my errors here...

EDIT: Here's the dump file from that crash if it helps: https://drive.google.com/open?id=1blLMUL5h0WqGEi6IUCHJHcweCXUXCTh3

**Comment by kisak-valve** [comment]
For reference, the attached minidump is an EXCEPTION_ACCESS_VIOLATION_READ in vrserver.exe.

**Comment by TheDeveloperGuy** [comment]
Probably providing incorrect values in one of the other methods (eg. GetProjectionRaw). SteamVR (in general) is not error-checking what you give it, so will crash if you give it bad values. It's up to your driver to make sure you don't give invalid values.

**Comment by Seneral** [comment]
Ok I'll test some more later when I'm home, but I return pretty standard values for now, most straight from the sample driver. GetProjectionRaw returns (-1,1,-1,1) for example, will change it to (-.3, .3, -.5, .5) and see if they're more sensible.

**Comment by Seneral** [comment]
I know that, but I can't figure out why with the little documentation that there is. Went over the code a lot of times now, and if values the sample functions return are valid (albeit not useable), then my driver should be fine.
To rule out the last (obvious) variable: A controller does not need to be created, right? I removed the sample controller implementation from my driver until I actually need to implement it.

Here's an excerpt from my log that prints every function's return value (on a dual Full-HD-monitor setup, without HMD display):
```
13.796 - serialhmd: Server: Init
13.796 - serialhmd: Driver: Init
13.796 - serialhmd: Driver: Serial Number: 311220181850
13.796 - serialhmd: Driver: Model Number: Serial HMD DIY 1
13.796 - serialhmd: Driver: Seconds from Vsync to Photons: 0.011111
13.796 - serialhmd: Driver: Display Frequency: 60.000000
13.796 - serialhmd: Driver: IPD: 0.063000
13.796 - Driver 'serialhmd' started activation of tracked device with serial number '311220181850'
13.796 -   driver serialhmd implements interfaces IVRSettings_002 ITrackedDeviceServerDriver_005 IVRDisplayComponent_002 IVRDriverDirectModeComponent_005 IVRCameraComponent_003 IServerTrackedDeviceProvider_004 IVRWatchdogProvider_001 IVRVirtualDisplay_002 IVRDriverManager_001 IVRResources_001 IVRCompositorPluginProvider_001 
13.796 - Loaded server driver serialhmd (IServerTrackedDeviceProvider_004) from D:\GAMES\STEAM\driver_serialhmd\bin\win64\driver_serialhmd.dll
13.796 - serialhmd: Driver: Activating HMD! 
13.796 - serialhmd: Driver: Set Prop Model/Serial/IPD/HeadToEye/Freq/VSyncSec 
13.796 - serialhmd: Driver: Set Prop_CurrentUniverseId_Uint64 : 11
13.796 - serialhmd: Driver: Set Prop_IsOnDesktop_Bool : True
13.796 - serialhmd: Driver: Set Prop_DisplayDebugMode_Bool : False 
13.796 - serialhmd: Driver: SetHiddenArea Left: 0 (TrackedProp_Success)
13.796 - serialhmd: Driver: SetHiddenArea Right: 0 (TrackedProp_Success)
13.796 - serialhmd: Driver: Requested unimplemented component 'IVRDriverDirectModeComponent_005'! 
13.796 - serialhmd: Driver: Requested unimplemented component 'IVRCameraComponent_003'! 
13.796 - serialhmd: Driver: Requested unimplemented component 'IVRVirtualDisplay_002'! 
13.796 - Active HMD set to serialhmd.311220181850
13.796 - serialhmd: Display: GetWindowBounds (1920, 0)(1920, 1080) 
13.799 - serialhmd: Display: IsDisplayOnDesktop: true 
13.799 - serialhmd: Display: IsDisplayRealDisplay: true 
13.799 - serialhmd: Display: GetRecommendedRenderTargetSize (1920, 1080) 
13.799 - serialhmd: Display: GetProjectionRaw Left (L -0.300000, R 0.300000, T -0.500000, B 0.500000)
13.799 - serialhmd: Display: GetEyeOutputViewport Left (0, 0)(960, 1080) 
13.799 - serialhmd: Display: GetProjectionRaw Right (L -0.300000, R 0.300000, T -0.500000, B 0.500000)
13.799 - serialhmd: Display: GetEyeOutputViewport Right (960, 0)(960, 1080) 
13.799 - Initialized EyeToHead Left Translation -0.031500 0.000000 0.000000 
13.799 - Initialized EyeToHead Right Translation 0.031500 0.000000 0.000000 
13.800 - Adding controller type to serialhmd_hmd
13.800 - serialhmd: Driver: Requested unimplemented component 'IVRControllerComponent_001'! 
13.800 - Driver 'serialhmd' finished adding tracked device with serial number '311220181850'
13.801 - Processing message VRMsg_Connect from vrstartup (9356) took 0.0504 seconds
13.802 - App system.generated.vrstartup.exe (serialhmd_hmd) loaded fallback binding file file:///D:/GAMES/STEAM/steamapps/common/SteamVR/resources/config/legacy_bindings_generic_hmd.json
13.819 - Invalid input type click for controller (/user/head/proximity)
14.274 - [Steam] Steam INIT.
15.993 - New Connect message from D:\GAMES\STEAM\steamapps\common\SteamVR\bin\win64\vrcompositor.exe (VRApplication_Background) (Args: ) 9424 
15.998 - Setting app openvr.component.vrcompositor PID to 9424
16.000 - App openvr.component.vrcompositor (serialhmd_hmd) loaded fallback binding file file:///D:/GAMES/STEAM/steamapps/common/SteamVR/resources/config/vrcompositor_bindings_generic_hmd.json
16.000 - Using existing HMD serialhmd.311220181850
16.000 - Processing message VRMsg_Connect from vrcompositor (9424) took 0.00715 seconds
16.358 - [Settings] Save Json Settings to C:\Program Files (x86)\Steam\config\steamvr.vrsettings
16.360 - serialhmd: Display: ComputeDistortion: B(0.000000,0.000000) G(0.000000,0.000000) R(0.000000,0.000000) 
16.699 - Exception c0000005
22.469 - ================================================================================================
22.469 - ================================================================================================
22.469 - Found saved crash timestamp time 1547490676 v1543961514 uptime 2 -- Using safe mode
22.472 - Setting shared memory namespace, but it is already set to 10316. Process is NOT running
22.472 - Setting shared memory namespace to 7472
```
I don't expect you to analyze it, but if there's anything that sticks out as unusual, please tell me. I could of course give you the code, but I doubt you'd want that. To the best of my knowledge, with the documentation and with what the documentation does NOT tell, this should be fine. I've looked at some other driver implementations aswell, nothing out of the ordinary...

**Comment by JoeLudwig** [comment]
The dump indicates that the crash is happening when trying to call ComputeDistortion in your implementation.  

What does GetComponent in your device look like?

**Comment by Seneral** [comment]
Yeah, but 300-400ms after that - it returns successfully and with correct parameters (as to my knowledge), and no other function of the driver is called after that, except the RunFrame which most likely is on a separate thread.
So it is not necessarily the ComputeDistortion function, but could be anything else that only now get's processed. But the stack trace "Failed to create distortion surfaces" logically limits that to values that are related to the ComputeDistortion function. But as I said, returning the same coordinates undistorted should be fine...

This is my GetComponent function:
```
void *SerialHMDDriver::GetComponent(const char *pchComponentNameAndVersion)
{
	if (!strcmp(pchComponentNameAndVersion, vr::IVRDisplayComponent_Version))
	{
		return (vr::IVRDisplayComponent *)this;
		DriverLog("Driver: Provided requested component '%s'! \n", pchComponentNameAndVersion);
	}
	DriverLog("Driver: Requested unimplemented component '%s'! \n", pchComponentNameAndVersion);
	return NULL;
}
```
I've had a version before where the DisplayComponent implementation is in a different class, but obviously makes no difference.

**Comment by Seneral** [comment]
Ok if you do want to take a look into the code, just uploaded it: https://github.com/Seneral/SerialHMD

**Comment by Seneral** [comment]
Ah, have seen a release is out! With more specific error messages for many compositor startup failures - sounds very promising! Have had no luck so far finding the error myself, and will try with the new version tomorrow. Thank you!

**Comment by Seneral** [comment]
Still in exam phase, but after a few thoughts:
Didn't occur to me before, but since ComputeDistortion would need to be called on multiple UVs in rapid succession (but only being called once), plus the 1/2401 from the error log, indicates that the error was indeed found right after the function completed.
Can anyone with access to the source code tell me which values could be involved in triggering such an error? There function ComputeDistortion really isn't that complicated, yet it gives me so much problems and I just can't figure out what the error is. I've checked with different implementations of this, used some actual distortion functions, tried different ways of creating the DistortionCoordinates struct, etc. - there seems nothing wrong with the ComputeDistortion function itself (especially since returning the same coordinates without distortion should be no problem).
I tried with both HiddenAreaMeshes and without. I tried adjusting Prop_DistortionMeshResolution_Int32 from 0 to 64 and 4 and found the error adjusting from 1/2401 to 1/4096 and 1/16 respectively. But no indication on why the code fails...

Any help is again greatly appeciated. I can't continue onward without some help here, unfortunately. I'd be willing to improve the docs once I find out my problem, although it looks like I'm the only one with it, others not even encountering it. I might have another PC in a few weeks to test this on, in case it is my PC.

**Comment by TheDeveloperGuy** [comment]
ComputeDistortion() gets called in 3 batches in my driver. First batch is about ~6200 calls, then that is repeated (so, another ~6200 calls), then the final batch is about ~33000 calls. Having a brief look at your code, what stands out is the hidden area mesh code in Activate(). Have you tried your driver without that code? It's certainly not necessary to provide that in a working driver.

**Comment by TheDeveloperGuy** [comment]
In any case, you'll need to run your driver in a debugger if you want to find out what is causing the access violation, noone is going to be able to help you (both technically and from a time point of view) deal with issues that are not common and are most likely due to a configuration or coding error in your particular setup. 

To run the driver in the debugger, you'll need to set the Debugging "Command" to "{full path to your steam installation}\steamapps\common\SteamVR\bin\win64\vrserver.exe", and the "Command Arguments" to "--keepalive --earlyload" in Visual Studio "Debugging".

**Comment by Seneral** [comment]
Yes, only implemented the hidden area to see if that did anything.
The debugger is a good idea, didn't know how that would work though. Thanks, will try it out!

**Comment by Seneral** [comment]
Hm even with earlyload it seems to terminate before trying to start vrcompositor - instead of the usual 
"Processing message VRMsg_Connect from vrstartup (10336) took 0.0308 seconds"
I only get "Early HMD load result: VRInitError_None" after the driver initially finishes adding the tracked device.
Instead, I managed to catch the exception with a normal SteamVR startup:
"Exception thrown at 0x00007FF73C543D88 in vrserver.exe: 0xC0000005: Access violation reading location 0x0000000000000030." Doesn't help very much though:(

**Comment by TheDeveloperGuy** [comment]
Put breakpoint on ComputeDistortion(), "Start Debugging (F5)". Your location for access violation says it's probably a class or structure pointer that's NULL (0) when trying to access method/member at offset 0x30.

**Comment by Seneral** [comment]
Oh sorry my fault, didn't have the project loaded, tried to debug only the executable.
I did not develop with VS, but with VS Code + GCC, seems I'll have to refactor alot of code to get it to work with MS's compiler. Thanks!

**Comment by TheDeveloperGuy** [comment]
I'm pretty certain that you can't use GCC compilers on Windows with OpenVR unless you're using the "C" interface, GCC and MS Compilers use a different ABI for C++. 

"MSVC binaries are only compatible with MinGW for C interfaces. C++ binaries produced by MSVC are not compatible."

**Comment by Seneral** [comment]
So finally got around to getting it to work, and yes that was the problem all along. Can't tell why it worked up to this point and started breaking only there...
Thank you so much, and sorry for getting so desparate. First time using C++, and started in Linux with GCC before switching to windows since SteamVR on linux is in beta. So I just kept using GCC, and didn't know the difference it would make compared to MSVC.
